# REPAIR & ADDITIONS LEDGER — The Method 1.6
# The next session's PRIMARY work object. Close this list, THEN resume prose (M's ruling).
# LIVING LIST: new entries are expected as prose work progresses. Append; never silently drop.
# Discipline: NO-SILENT-CHANGE — every volume change recorded by a Register entry in the same build;
#   guard.py OLD_DIR NEW_DIR before any bundle is declared current; a FAIL blocks the handoff.
#   Register is append-only (Ruling 27): a superseded entry is corrected by a NEW entry citing it.
# ============================================================================================

## STATUS KEY: OPEN (needs doing) · OWED-RECOMPUTE (needs a computation) · DONE (closed this/earlier)

## ── A. VOLUME REPAIRS (measured, from original-works Request-4 return) ──

### A1. Index of Indices — tower rows print the non-closing exact-triangle object  [OPEN]
Canonical is the envelope build; the printed 22,275/64,290 is the exact-triangle object (E=35,570),
already named at Mathematical Compendium line 1515 (the reconciling entry — DO NOT touch it).
Fixes, Index of Indices ONLY:
  - row Λ₁₂ → `| Λ₁₂ | 70,905 | 12 | — | — | 2K ≤ 2J_c + 2f_max |`
  - row Λ₁₃ → `| Λ₁₃ | 199,130 | 13 | — | — | |2J − 2K| ≤ 1 |`
  - prose line 321: "runs to 64,290 cells at Λ₁₃" → "...199,130..."
Recorded by a new Register entry citing the correction; slip 04 ready.

### A2. Index of Indices — composable columns computed on the wrong object  [OWED-RECOMPUTE]
The composable counts/fractions in the Λ₁₂/Λ₁₃ rows (14,242 / 0.6394, 39,772 / 0.6186) were computed
on the TRIANGLE object. Recompute on the canonical envelope build (Λ₁₂=70,905, Λ₁₃=199,130) and replace.
Needs tower.json (regenerable in seconds from banked scripts tower.py/tower3.py).

### A3. Main volume §12.11.3.1 — axis-10 "parity" annotation mislabels the bound  [OPEN]
2,535 is canonical (bare interval 2S′ ≤ v ≤ g). "Parity" belongs to the exact set (§12.11.1), not the
admissible bound. Fix, main volume, one annotation:
  - §12.11.3.1 row 10: strike ", parity" from the bound column, leaving "2S′ ≤ v ≤ g".
  - optional provenance cell: "seniority, Racah 1943 — parity lives in the exact set, §12.11.1."
MC-22/23 carry the count without the annotation → no compendium repair.

### A4. Triangle-object E census — named, not verified  [OWED-RECOMPUTE, low priority]
MC line 1515's E = 35,570 for the exact-triangle object was not recomputed (5.3M-cell census).
Either recompute during repair, or accept MC 1515 as the standing record. Identification rests on two
exact counts (22,275; 64,290) + the compendium's own naming — already solid; census is confirmation only.

## ── B. COMPENDIUM ADDITIONS (owed expansions from the prose pass so far) ──
## These are the [MC-]/[PC-]/[IoI-] tokens placed in approved chapters, owed as full expansions when the
## compendia are authored. FULL DETAIL + bindings live in OWED-EXPANSIONS.md (Drive). Summary counts here:
##   Mathematical Compendium: MC-01..MC-51, MC-54, MC-55 live (MC-52, MC-53 RETIRED — sampled findings refuted).
##   Physics Compendium: PC-01..PC-05.
##   Index of Indices: IoI-01..IoI-03.
##   Spectra Compendium: (none placed yet.)
## Delivered-with-proofs already (author verbatim): MC-54 (EXPANSION-MC54.md), MC-55 (03-1D-lands-inside-14D.md),
##   PC-05 (attribution block in EXPANSION-MC54.md).
## Highest tokens at handoff: MC-55, PC-05, IoI-03. Next new tokens continue from these.

## ── C. REGISTER ADDITIONS (subject-matter proof-of-work owed to the subject Register 1.1) ──
## FULL DETAIL in OWED-REGISTER-EXPANSIONS.md (Drive). Summary:
##   R-01..R-06 (Ch14 seed/closure workshop as proof-of-work).
##   Correction batch: R 602–605 (seed bit-structure refuted/corrected; P4 raised to law).
##   Slips 01–04 ready for Register 1.1 to allocate numbers (append-only; new entries cite superseded ones).

## ── D. SLIPS & SCRIPTS TO BANK (must not die with the container) ──
## Slips 01–04 → Register 1.1 (R-numbers theirs to assign).
## Scripts (in Drive restore-packs folder 1XX_5f3PZB6tjRtiZ2GIgd8Tt7i_4GgkY): tower.py, tower3.py, factor.py,
##   req4.py, verify2.py, verify3.py. tower.json regenerable from these (seconds, fingerprints included).
## Recovered: archive/transitions/Transitions.md in method16_rp_A_instruments.tar.gz
##   (Drive 18RTwgMdnpN1hNdBDR4TgB7opb4buGedh, 1,005,510 bytes verified) — closes the Transitions.md location item.

## ── CLOSE CONDITION ──
## The repair pass is COMPLETE when A1, A2, A3 are done (A4 recompute or accept), each recorded by a Register
## entry, guard.py PASS, and the Index of Indices + main volume re-bundled current. THEN resume prose at 14B.
## New repair/addition entries are EXPECTED as prose resumes — this list stays open and grows.
