# REPAIR & ADDITIONS LEDGER — The Method 1.6
# LIVING LIST: new entries are expected as prose work progresses. Append; never silently drop.
# Discipline: NO-SILENT-CHANGE — every volume change recorded by a Register entry in the same build;
# guard.py OLD_DIR NEW_DIR before any bundle is declared current; a FAIL blocks the handoff.
# Register is append-only (Ruling 27): a superseded entry is corrected by a NEW entry citing it.
# ============================================================================================

## STATUS KEY: OPEN (needs doing) · OWED-RECOMPUTE (needs a computation) · DONE (closed this/earlier)

## ── A. VOLUME REPAIRS ──

### A1. Index of Indices — tower rows printed the non-closing exact-triangle object [DONE — chat 53]
Repaired in the delivered .REPAIRED files, M approved:
 - row Λ₁₂ → `| **Λ₁₂** | 70,905 | 12 | 46,740 | **0.6592** | 2K ≤ 2J_c + 2f_max |`
 - row Λ₁₃ → `| **Λ₁₃** | 199,130 | 13 | 127,070 | **0.6381** | \|2J − 2K\| ≤ 1 |`
 - prose "runs to 64,290 cells at Λ₁₃" → "...199,130...".
Recorded: SLIP 05 (REGISTER-QUEUE-APPEND-repair-pass.md, for Register 1.1 to number).
MC tree-or-tightness entry (the reconciling entry) untouched, per ruling.

### A2. Composable columns recomputed on the canonical envelope build [DONE — chat 53]
Λ₁₂: 46,740 / 70,905 = 0.6592 · Λ₁₃: 127,070 / 199,130 = 0.6381 (a2_canonical.py on tower.json
regenerated from banked tower.py/tower3.py). Instrument VALIDATED by exact reproduction of every
recorded count: Λ₉ 1,169 · Λ₁₀ 2,050 · Λ₁₁ 9,450 · triangle Λ₁₂ 14,242 · triangle Λ₁₃ 39,772 ·
register 627's 11,188/5,116/8,214. Signature measured: base (e,f,g,2S′)→(n,ℓ,k,2S); from Λ₁₁ the
outermost coupling matches the follower's core (2J_c→2J_c, 2K→2J_c, 2J→2J_c).
Register-626 dichotomy HOLDS on the canonical sequence: 0.0000, 0.7068, 0.8087, 0.6956, 0.6592,
0.6381 — peak stays at Λ₁₀, every coupling axis still lowers it. Values in SLIP 05.

### A3. Main volume §12.11.3.1 — ", parity" struck from the axis-10 bound column [DONE — chat 53]
Bound left as `2S′ ≤ v ≤ g` (column alignment preserved); provenance cell (seniority, Racah 1943)
unchanged; the optional provenance extension was offered and not taken. Recorded: SLIP 06.
Measured basis re-verified this pass: bare interval = 2,535, parity build = 1,841 (req4.py).

### A4. Triangle-object E census [CLOSED — MC 1515 accepted as standing record; chat 53]
Recompute attempted twice on the regenerated triangle build (22,275 cells, 5,308,416 box):
raw pairwise double-projection E = 11,535 (a4_census.py); pairwise monotone-bounds (staircase)
E = 28,780 (a4b_census.py). Neither reproduces 35,570; the ORIGINAL E-instrument for that census
is absent from every banked location searched (restore-packs folder; instruments archive
method16_rp_A_instruments.tar.gz, 551 files; project knowledge). Per governance — a rebuilt
instrument contradicting the record is presumed wrong — MC 1515 STANDS. The two reconstruction
results are logged with commands as findings about the reconstructions. If the original
instrument surfaces, re-run; until then this item is closed, not open.

### A5. Main volume §12.11.1.4–1.5 — same triangle-object figures in the main text [DONE — chat 53]
§12.11.1.4's stage table (source lines 3266–3269) prints Λ₁₂ 22,275 / 14,242 / 0.6394 and
Λ₁₃ 64,290 / 39,772 / 0.6186 — the triangle object again; §12.11.1.5's Λ₁₃ decomposition
(11,188 + 5,116 + 8,214 = 24,518 of 64,290, 38.14%) is triangle-computed. Canonical replacement
figures already MEASURED and banked in SLIP 05's addendum: 46,740/0.6592 · 127,070/0.6381;
decomposition 35,630 (g=0) + 13,750 (2J∈{6,7,8}) + 22,680 (combination) = 72,060 of 199,130
(= 36.19%). The three kinds remain exhaustive; the structural kind survives (2J reaches 8,
2J_c reaches 5). Applied: table rows and the full decomposition block replaced; residual sweep zero. Slip 07.
NOTE: registers 622–627 are NEVER edited — corrections ride SLIP 05 and, if needed, a further slip.

### A6. Mathematical Compendium `K.peak` object — repeats the triangle fractions [DONE — chat 53]
The K.peak entry prints "...0.6956, 0.6394, 0.6186 across Λ₈ to Λ₁₃". Canonical sequence ends
0.6592, 0.6381 (A2). The entry's law-statement (peak at Λ₁₀, counting raises / coupling lowers,
no exception) SURVIVES unchanged — only the two trailing numbers moved. Applied; slip 08.

### A7. Index of Indices Figure 2 asset (fig-i1-tower.png) — plots the stale fractions [DONE — chat 53]
The figure plots the composable fraction by stage; its Λ₁₂/Λ₁₃ points are the triangle values.
Caption text survives (both claims true on canonical). Regenerated with the ORIGINAL banked
instrument (fig_indices.py i1, two data values patched). Slip 09. Also produces one of register
1741's eight missing compendium assets.

### A8. fig-i2-landscape.png plotted Λ₁₃ at the triangle count [DONE — chat 53]
Regenerated from the original instrument, one data value moved to 199,130. Slip 10. Also produces
one of register 1741's eight missing compendium assets; i3/i4 verified clean-by-data.

### A9. MC `K.deadend` printed the triangle Λ₁₃ decomposition as current fact [DONE — chat 53]
Found by the ruled all-volumes sweep. 11,188/5,116/8,214 → 35,630/13,750/22,680; Λ₁₀ half and
interpretive line survive. Slip 11. Final sweep certificate in the queue file: no live prose,
table, compendium object, or figure carries a triangle composability figure anywhere; only
append-only registers and audit history remain, by design.

## ── B. COMPENDIUM ADDITIONS — M RULING (chat 53): author the FULL B-list before prose resumes ──
## AUTHORED (chat 53, slip 12): MC-54 (S.gen/S.alpha/S.krein + S.bits/S.channel/S.core/S.unit
## corrected), MC-55 (K.bracket), PC-05 (PC prior-art chain).
## REMAINING TO AUTHOR, in batches, each computationally verified before writing, presented per batch:
##   Batch 1: MC-01..06 (Ch5-6: L.closed worked proof; distributive; modular; Birkhoff 976 down-sets;
##            Sperner/log-concavity/Dilworth; order dimension 8) — all verifiable on the L8 build.
##   Batch 2: MC-07..11 (Ch7, Ch10: omega<=dim; occupancy metric; Mobius/transfer; correlation 1.49x;
##            closed-form void count).
##   Batch 3: MC-12..16 (Ch11: circuit cut; ten combinations; detachable spin; three-facts; F(-1)=2).
##   Batch 4: MC-17..21 (shape); Batch 5: MC-22..26 (tower); Batch 6: MC-27..35 (time, incl. the
##            M-flagged MC-35 not-a-triangle proof, full representation required).
##   Batch 7: MC-36..41 (EM index, languages, g<=q most active); Batch 8: MC-42..51 (Ch14A).
##   Batch 9: PC-01..04 (multipole map; intercombination; coupling chains; Thm 14.1 attribution).
##   Batch 10: IoI-01..03 (EM quotient entry; languages-as-coordinate-systems; the other closed indexes).
## Every batch: house style; grade lines honest (PROVED only where proved); slips per batch;
## MC-52/53 stay RETIRED. Token resolution is the LAST step, after compendium numbering.
## FULL DETAIL + bindings: OWED-EXPANSIONS-2.md (Drive; supersedes OWED-EXPANSIONS-1.md and the
## stale project-knowledge copy named OWED-EXPANSIONS.md, which is the -1 text).

## ── C. REGISTER ADDITIONS ──
## R-01..R-06 (Ch14 workshop) · correction batch R 602–605 · slips 01–04 (queue file) ·
## NEW: slips 05–06 + A4 disposition + canonical decomposition — REGISTER-QUEUE-APPEND-repair-pass.md,
## to be appended to OWED-REGISTER-EXPANSIONS.md in Drive. All for Register 1.1 to number.

## ── D. SLIPS & SCRIPTS TO BANK ──
## Existing: tower.py, tower3.py, factor.py, req4.py, verify2.py, verify3.py (Drive restore-packs).
## NEW instruments from this pass (must not die with the container): compose.py, sig_sweep.py,
## sig_val.py, sig_l13.py, a2_canonical.py, a4_census.py, a4b_census.py — packed as
## repair-pass-instruments.tar.gz for the restore-packs folder.
## MISSING INSTRUMENT [OPEN]: guard.py is in NO banked location (restore-packs, instruments
## archive — 551 files listed, project files). The no-silent-change rule requires it before any
## bundle is declared current. This pass substituted a measured OLD/NEW diff verification
## (exactly the four authorized line changes, line counts unchanged) and REPORTS THE GUARD STEP
## NOT RUN AS guard.py. Bank guard.py, or M rules on its restoration (cf. Ruling 63's appf.py gate).

## ── CLOSE CONDITION (updated) ──
## A1–A3, A5–A9 DONE and recorded (slips 05–11); A4 CLOSED. THE A-LIST IS EMPTY — prose may resume
## per M's ruling once the build thread runs guard + re-bundle-current. guard.py banking still owed (D).
## Prose pass resumes at source Chapter 14B per the handoff once M releases it.
