#!/usr/bin/env python3
"""series_gen.py — SERIES CONSTRUCTION for the Reading List (Board Row 1).

store_gen.py closes the VALUE derivation but inherits the SERIES LIST from the
authored store (DIGEST: 'closes the VALUE derivation and not the SERIES
construction'). Nothing on disk constructs series from a raw level table. This
does, using store_gen's own readers, under the rules already on record:

  R 1650  series split by (l, term, parent) AS PRINTED, decoration kept
  T8      limit GENERATED by store_gen.assign_limit (parent-matched · NIST
          ordinal · forced · positional · unwitnessed) — never a fallback
  R 1663  language read from the term: '[' → jK (mult 2), leading '(' → jj
          (mult 0, NULL BY LANGUAGE), ^\d[A-Z] → LS (mult = leading digit),
          else unresolved (mult 0)
  R 1666  span = 'single-n' where every member sits at one n; not a series
  T2/T6   delta = MEDIAN of member defects; mean and asymptotic (deepest
          member) carried alongside; single-member cells written, not refused
  §2.9    no silent default: R_M where the mass is in store_gen.MASS, else
          RINF with R_status flagged — the effect on delta is < 1e-4 and is
          stated, not hidden
  ions    n* = zeta * sqrt(R/(lim-E)), zeta = spectroscopic charge

Two routes (§2.8): run on the 24 store species first and diff against
MEASUREMENTS.tsv before a single new species is trusted.

Zeno: one species per segment, checkpointed to captures/.series_gen.done.
Writes captures/READING-LIST-STAGING.tsv. Touches nothing in the store.
"""
import os, re, sys, statistics, json
import store_gen as sg

ROMAN = {'I':1,'II':2,'III':3,'IV':4,'V':5,'VI':6,'VII':7,'VIII':8,'IX':9,'X':10}
OUT = 'captures/READING-LIST-STAGING.tsv'
DONE = 'captures/.series_gen.done'
HDR = ['Z','charge','l','mult','delta','spread','term','parent','language','n_lo','n_hi',
       'members','limit','limit_label','limit_status','delta_status','span','cell_exists',
       'delta_mean','delta_asym','R_status','file']

_cache = {}
def raw(sym, ch):
    """Level rows for species (sym, charge). Looks in spectra_raw/ then queue2/."""
    key = (sym, ch)
    if key in _cache: return _cache[key]
    name = f'{sym}{[k for k,v in ROMAN.items() if v==ch][0]}.tsv'
    for d in ('spectra_raw', 'spectra_raw/queue2'):
        p = os.path.join(d, name)
        if os.path.exists(p):
            rows = [l.rstrip('\n\r').split('\t') for l in open(p, encoding='utf-8')
                    if l.strip() and not l.startswith('#')]
            if rows and 'onfig' in rows[0][0]: rows = rows[1:]
            _cache[key] = (rows, p); return _cache[key]
    _cache[key] = ([], None); return _cache[key]

def language(term):
    t = term.strip()
    if '[' in t: return 'jK', 2
    if t.startswith('('): return 'jj', 0
    m = re.match(r'^(\d+)[A-Z]', t)
    if m: return 'LS', int(m.group(1))
    return 'unresolved', 0

def cells():
    s = set()
    with open('COORDINATES.tsv', encoding='utf-8') as f:
        h = f.readline().rstrip('\n').split('\t')
        iZ,ic,il,im = (h.index(x) for x in ('Z','charge','l','mult'))
        for line in f:
            r = line.rstrip('\n').split('\t')
            s.add((r[iZ], r[ic], r[il], r[im]))
    return s

def run_species(Z, sym, ch, CELLS):
    rows, path = raw(sym, ch)
    if not rows:
        return [[Z, ch] + ['']*(len(HDR)-3) + ['no_table_on_disk']]
    # temporarily point store_gen at this table so limits()/assign_limit see it
    sg._cache[sym] = rows
    if Z in sg.MASS:
        R = sg.RINF / (1 + 1 / (sg.MASS[Z][1] * sg.AMU)); rstat = 'R_M'
    else:
        R = sg.RINF; rstat = 'RINF — mass not in table (flagged)'
    keys = {}
    for r in rows:
        if len(r) < 4: continue
        n, l, why = sg.outer(r[0].strip())
        if why: continue
        term = r[1].strip()
        if not term or term == 'Limit': continue
        keys.setdefault((l, term, sg.parent_of(r[0].strip())), []).append(n)
    out = []
    for (l, term, parent), ns in sorted(keys.items()):
        lang, mult = language(term)
        topE = sg.top_member_E(sym, l, term, parent)
        lim, lstat, llab = sg.assign_limit(sym, parent, topE)
        base = [Z, ch, l, mult]
        if lim is None:
            out.append(base + ['', '', term, parent, lang, min(ns), max(ns), 0, '', '',
                               lstat, 'unusable — no limit', '', 
                               'yes' if (str(Z),str(ch),str(l),str(mult)) in CELLS else 'no',
                               '', '', rstat, path])
            continue
        # strict parent equality throughout (R 1678: an unparented ladder is the
        # set with NO printed parent, not the union) — so store_gen.members is
        # not used; _energies applies the same key the split used
        mem = sorted((n, n - ch * (R ** 0.5) / ((lim - E) ** 0.5), br)
                     for (n, E, br) in _energies(rows, l, term, parent, lim))
        if not mem:
            out.append(base + ['', '', term, parent, lang, min(ns), max(ns), 0, lim, llab,
                               lstat, 'unusable — no members below limit', '',
                               'yes' if (str(Z),str(ch),str(l),str(mult)) in CELLS else 'no',
                               '', '', rstat, path]); continue
        ds = [d for _, d, _ in mem]
        nlo, nhi = mem[0][0], mem[-1][0]
        span = 'series' if nlo != nhi else 'single-n'
        dstat = 'usable' if not lstat.startswith('unwitnessed') else 'unwitnessed'
        out.append(base + [f'{statistics.median(ds):.5f}', f'{max(ds)-min(ds):.5f}', term,
                           parent, lang, nlo, nhi, len(mem), lim, llab, lstat, dstat, span,
                           'yes' if (str(Z),str(ch),str(l),str(mult)) in CELLS else 'no',
                           f'{statistics.mean(ds):.5f}', f'{mem[-1][1]:.5f}', rstat, path])
    return out

def _energies(rows, L, term, parent, lim):
    for r in rows:
        if len(r) < 4 or r[1].strip() != term: continue
        cfg = r[0].strip()
        n, l, why = sg.outer(cfg)
        if why or l != L: continue
        if parent and sg.parent_of(cfg) != parent: continue
        v = r[3].strip()
        try: E = float(v.strip('[]').replace('+',''))
        except ValueError: continue
        if E >= lim: continue
        yield n, E, v.startswith('[')

def main():
    which = sys.argv[1] if len(sys.argv) > 1 else 'reading-list'
    if which == 'store':
        species = sorted({(int(a), int(b)) for a, b in
                          (l.split('\t')[:2] for l in open('MEASUREMENTS.tsv') if l[0].isdigit())})
        species = [(Z, sg.MASS[Z][0], ch) for Z, ch in species]
        out, done = 'captures/STORE-RECONSTRUCT.tsv', 'captures/.series_gen_store.done'
    else:
        species = []
        for l in open('captures/READING-LIST.tsv', encoding='utf-8'):
            if l.startswith('#') or not l.strip(): continue
            f = l.rstrip('\n').split('\t')
            species.append((int(f[0]), f[1], int(f[2])))
        out, done = OUT, DONE
    CELLS = cells()
    seen = set(open(done).read().split()) if os.path.exists(done) else set()
    if not os.path.exists(out):
        open(out, 'w').write('\t'.join(HDR) + '\n')
    n = 0
    for Z, sym, ch in species:
        tag = f'{sym}{ch}'
        if tag in seen: continue
        rows = run_species(Z, sym, ch, CELLS)
        with open(out, 'a') as f:
            for r in rows: f.write('\t'.join(str(x) for x in r) + '\n')
        open(done, 'a').write(tag + '\n')
        n += 1
        if n >= int(os.environ.get('SEG', '10')): break
    left = len([1 for Z, s, c in species if f'{s}{c}' not in seen]) - n
    print(f'segment: {n} species written to {out}; {left} remaining')

if __name__ == '__main__':
    main()
