import numpy as np, spglib
exec(open('build.py').read().split('# --- validate')[0])

def hallmap():
    m={}
    for h in range(1,531):
        t=spglib.get_spacegroup_type(h); n=t.number if hasattr(t,'number') else t['number']
        m.setdefault(n,h)
    return m

def hnf_basis(vecs, D=24):
    """Basis of the lattice generated by Z^3 and the given fractional vectors.

    Columns of the returned P are the primitive vectors in CONVENTIONAL
    fractional coordinates.
    """
    M=np.vstack([np.eye(3)*D, np.round(np.asarray(vecs)*D)]).astype(np.int64)
    # column-style HNF by integer row reduction on the transpose
    A=M.T.copy()                                   # 3 x N
    piv=[]
    r=0
    for c in range(3):
        # find a row r..2 with nonzero entry in some column, use gcd elimination
        while True:
            nz=[j for j in range(A.shape[1]) if A[r,j]!=0]
            if not nz: break
            j0=min(nz,key=lambda j:abs(A[r,j]))
            for j in nz:
                if j==j0: continue
                q=A[r,j]//A[r,j0]
                A[:,j]-=q*A[:,j0]
            nz2=[j for j in range(A.shape[1]) if A[r,j]!=0 and j!=j0]
            if not nz2:
                A[:,[c,j0]]=A[:,[j0,c]]
                break
        r+=1
    P=A[:,:3].astype(float)/D
    if abs(np.linalg.det(P))<1e-9: raise RuntimeError("degenerate primitive basis")
    return P

def primitive_ops(sg,HN):
    d=spglib.get_symmetry_from_database(HN[sg])
    R=np.asarray(d['rotations']); T=np.asarray(d['translations'])%1.0
    I=K(np.eye(3))
    C=[T[i] for i in range(len(R)) if K(R[i])==I]
    P=hnf_basis(C)
    Pi=np.linalg.inv(P)
    out={}
    for Ri,ti in zip(R,T):
        Rp=Pi@Ri@P; tp=(Pi@ti)%1.0
        Rr=np.rint(Rp)
        if np.max(np.abs(Rp-Rr))>1e-6: raise RuntimeError("non-integer rotation in primitive basis")
        key=(K(Rr), tuple(int(round(x*24))%24 for x in tp))
        out[key]=(Rr,tp)
    return P, [v[0] for v in out.values()], [v[1] for v in out.values()], len(C)

HN=hallmap()
print("%-6s %-6s %-8s %-9s %-8s %s" % ("SG","centr","conv ops","prim ops","rots","uniq t per rot"))
for sg in (1,2,70,141,166,194,216,221,225,227,229,230):
    P,Rp,Tp,nc = primitive_ops(sg,HN)
    from collections import defaultdict
    tc=defaultdict(set)
    for R,t in zip(Rp,Tp): tc[K(R)].add(tuple(np.round(t,4)))
    d=spglib.get_symmetry_from_database(HN[sg])
    print("%-6d %-6d %-8d %-9d %-8d %d"
          % (sg,nc,len(d['rotations']),len(Rp),len(tc),max(len(v) for v in tc.values())))
