import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "morris-thorne-1988-wormhole-throat",
 "name": "Morris-Thorne (1988) wormhole throat: b(r_0)=r_0, flare-out b'(r_0)<1, tau(r_0)=1/(8 pi r_0^2), m=b/2; 'near neighbour / folklore' as certify.py and tolman.py use it",
 "source": {
   "located": "M.S. Morris & K.S. Thorne, Am. J. Phys. 56, 395 (1988) -- pre-arXiv, no copy at alphaXiv. Read through two exact restatements: F.S.N. Lobo, arXiv:0710.4474 (2007) Sec. II.A-II.D, eqs (1),(9)-(10),(21)-(33),(37)-(39),(71) [metric, embedding flare-out (b-b'r)/2b^2>0, orthonormal Einstein tensor, throat values rho(r_0)=b'/8pi r_0^2, tau(r_0)=1/8pi r_0^2, m(r)=b/2, NEC violation rho-tau<0 at the throat]; and D. Hochberg & M. Visser, gr-qc/9704082 (1997) eqs (26),(68),(72) and p.23 [the covariant generalisation, and 'the Morris-Thorne result that tau = 1/(8 pi G r_0^2)' and 'rho = b'(r_0)/8 pi G r_0^2 <= 1/8 pi G r_0^2 at the throat', with the MT 'at or near the throat' phrase traced to MT p.405 eq (56)]. Witness solution READ: Agnese & La Camera gr-qc/0203067 eqs (11),(13),(17).",
   "read_status": "READ-VIA-RESTATEMENT",
   "via": "mcp__alphaXiv__answer_pdf_queries on 0710.4474, gr-qc/9704082, gr-qc/0203067 (page text returned and quoted above); Morris-Thorne 1988 itself is NAMED-NOT-READ"
 },
 "published_statement": "Lobo 0710.4474 restating MT: for ds^2 = -e^{2Phi(r)}dt^2 + dr^2/(1-b(r)/r) + r^2 dOmega^2 with Phi finite everywhere (no horizon) and b(r_0)=r_0 the throat, the embedding flares out iff d^2r/dz^2 = (b - b'r)/(2b^2) > 0 at or near the throat, i.e. b'(r_0) < 1 (eq 10). Einstein's equations give rho = b'/(8 pi r^2), tau = -p_r = [b/r^3 - 2(1-b/r)Phi'/r]/(8 pi) (eqs 26-27); at the throat rho(r_0) = b'(r_0)/(8 pi r_0^2), tau(r_0) = 1/(8 pi r_0^2) (eqs 29-30); b(r) = 2m(r) with m(r) = r_0/2 + int_{r_0}^r 4 pi rho r'^2 dr' (eqs 32-33); the exoticity xi(r_0) = (tau_0 - rho_0)/|rho_0| > 0 (eq 39), i.e. rho - tau < 0: the NEC is violated at the throat (eq 71). Hochberg-Visser eq (68): 'tau = 1/(8 pi G r_0^2) at the throat of the special class of model wormholes they considered'; eq (72): rho = b'(r_0)/(8 pi G r_0^2) <= 1/(8 pi G r_0^2).",
 "published_hypotheses": [
   "static spacetime (time-independent Phi, b)",
   "spherical symmetry, areal radius r with proper circumference 2 pi r",
   "Phi(r) finite everywhere (no event horizon) -- traversability; Kim 1302.3337 sharpens this to lim (r-b)Phi' = 0 at the throat, the alternative giving a divergent tangential pressure or a horizon",
   "b(r_0) = r_0 defines the throat; 1 - b/r >= 0 for r >= r_0; proper radial distance finite",
   "flare-out: (b - b'r)/(2b^2) > 0 at or near the throat, i.e. b'(r_0) < 1 (MT p.405 eq 56 says 'at or near', which Hochberg-Visser read as an N-fold degenerate flare-out for unspecified finite N)",
   "asymptotic flatness of both sides (b/r -> 0, Phi -> const) -- used by MT for the two-universe interpretation, NOT used for any throat value",
   "Einstein's equations G = 8 pi T with G = c = 1, orthonormal-frame stress tensor diag(rho, -tau, p, p); rho finite (so b' finite) at the throat",
   "the embedding-diagram form of flare-out is coordinate-dependent; the covariant form is tr(K)=0 with d tr(K)/dn < 0 on a minimal-area 2-surface (Hochberg-Visser 1997), or d theta/du >= 0 at a marginally anti-trapped surface (Hochberg-Visser 1998)"
 ],
 "hypothesis_drift": [
   "ADDED (tolman.py:1439-1441 docstring 'b(r_0) = r_0, Phi' = 0'; tolman.py:1785 'V18a a throat has Phi' = 0'; ledger.py:2008 W4 'Phi' = 0 is an exactness route'; task text 'Phi' = 0 is the wormhole branch'): the source does not require Phi'(r_0) = 0. The throat values tau(r_0) = 1/(8 pi r_0^2) and m(r_0) = r_0/2 hold for ANY finite Phi' because the Phi' term in G^r_r is (1-b/r)Phi'/r, which vanishes at b = r_0 identically (Lobo eq 27 -> 30; rederivation C2'). Phi' = 0 everywhere is the zero-tidal-force SUBCLASS (Lobo eq 40), not 'the wormhole branch'. The added hypothesis is stronger than needed, so every value the tree quotes is inside the source's class; it does not weaken the tree's conclusion, it under-states its generality.",
   "CONFLATED, prose only (tolman.py:532-536 'THE FLARE-OUT CONDITION IS NOT THIS IDENTITY; IT IS THE SAME QUANTITY WITH THE OPPOSITE SIGN'; tolman.py:183-187): the throat identity 4 pi r_0^3 p_r = -m follows from b(r_0) = r_0 and Phi finite alone and does not use flare-out; the flare-out condition proper is the separate inequality b'(r_0) < 1 <=> rho + p_r < 0 at the throat (Lobo eqs 10, 71; rederivation C5c), an inequality in rho, not the sign of 4 pi r^3 p_r against m. The code (tolman.py:2984-2989) checks the identity and tags it CONSTRUCTION; nothing computed rests on the label. A misdescription, not a refutation.",
   "DROPPED, harmlessly (certify.py:174-177, 496-498; tolman.py:2543-2544): 'flare-out iff negative enclosed Misner-Sharp mass' is recorded NOT-FOUND with the reason DERIVED. The source agrees for a stronger reason than the sign of p_r: m(r_0) = b(r_0)/2 = r_0/2 > 0 at EVERY Morris-Thorne throat whatever b'(r_0) is (Lobo eq 33; rederivation C5d, z3 C8b), so flare-out never coincides with negative Misner-Sharp mass. certify.py's theorem (contraction iff m(r) < 0) and the flare-out condition are therefore neighbours only in kind (both are sign statements about b at a radius); the tree claims no more than that (NOVELTY_CLAIMED = False, certify.py:385).",
   "SCOPE KEPT: certify.py:181 'IT IS STATIC AND SPHERICALLY SYMMETRIC ONLY' matches MT's hypotheses; Hochberg-Visser 1997/1998 show the flare-out/NEC statement survives without spherical symmetry, asymptotic flatness or staticity, so the tree's stated scope is narrower than the neighbour's, which is the safe direction."
 ],
 "data_at_publication": [
   {"quantity": "G = c = 1 (units); the 8 pi in tau(r_0) = 1/(8 pi r_0^2) is the Einstein coupling 8 pi G/c^4",
    "value_then": "8 pi G/c^4 with G = c = 1 (Morris-Thorne 1988; Lobo eq 26-30; Hochberg-Visser eq 68 writes 1/(8 pi G r_0^2))",
    "value_now": "unchanged: a convention, not a measurement. CODATA G = 6.674e-11 m^3 kg^-1 s^-2 enters only if r_0 is converted to SI, and cancels from every sign and ratio the tree uses (4 pi r_0^3 p_r / m = -1 is dimensionless and G-free)",
    "source_now": "Hochberg-Visser gr-qc/9704082 eq (68) (READ); no PDG/CODATA value is an input",
    "moves_conclusion": "no -- the result is an algebraic identity of the field equations for an assumed metric form; there is no measured datum in it"},
   {"quantity": "sign convention for extrinsic curvature K_ab in the covariant flare-out d tr(K)/dn < 0",
    "value_then": "MTW convention K_ab = -(1/2) dg_ab/dn (Hochberg-Visser 1997 eq 22, who note Visser's 1995 book uses the opposite sign)",
    "value_now": "convention; the tree uses only the embedding form b'(r_0) < 1, which carries no such sign choice",
    "source_now": "gr-qc/9704082 p.6 (READ)",
    "moves_conclusion": "no"}
 ],
 "rederivation": {
   "method": "sympy",
   "script_path": D + "/rederive/morris-thorne-1988-wormhole-throat.py",
   "outcome": "22/22 PASS (sympy 1.14.0 curvature from the metric, plus z3 5.1.0 for C8). C1: orthonormal G_tt = b'/r^2 and G_rr = -b/r^3 + 2(1-b/r)Phi'/r reproduce Lobo eqs 21-22 from the metric. C2: p_r(r_0) = -1/(8 pi r_0^2) for an arbitrary finite symbolic Phi'(r_0) (Phi' = 0 not assumed) and C2' the Phi' term vanishes identically at b = r_0. C3: m = b/2 from g_rr, m(r_0) = r_0/2, dm/dr = 4 pi r^2 rho (certify.py's definition). C4: 4 pi r_0^3 p_r = -m and the +m form fails by exactly -r_0. C5: flare-out (1-b'(r_0))/(2 r_0) > 0 <=> b'(r_0) < 1 <=> rho + p_r = (b'(r_0)-1)/(8 pi r_0^2) < 0, with the exact proportionality -4 pi r_0 (rho+p_r) = flare-out; and m(r_0) = r_0/2 carries no b'(r_0) dependence. C6: Agnese-La Camera eq (17) p_par = -m/(4 pi beta r_0^3) = -beta^2/(32 pi m^2) = -1/(8 pi r_0^2) exactly, m_MS = m/beta = r_0/2, 4 pi r_0^3 p_par = -m_MS (the tree's V19). C7: tolman.wormhole_throat(3.0) reproduced literally, fw = -1.5 = -m. C8: z3 unsat for any r_0 > 0 refuting 4 pi r_0^3 p_r = -m; unsat for m(r_0) = r_0/2 < 0; vacuity guard sat.",
   "agrees_with_source": "yes"
 },
 "later_literature": [
   {"ref": "Hochberg & Visser, gr-qc/9704082, Phys. Rev. D 56, 4745 (1997)", "effect": "extends", "what": "Defines the throat covariantly as a minimal-area 2-surface (tr K = 0, d trK/dn <= 0, 'simple/strong/weak/N-fold degenerate' flare-out) with no spherical symmetry, no asymptotic flatness, no topology assumption; proves the NEC is violated or marginal on any static throat (eqs 78, 83, 100, 113) and reduces to MT: tau = 1/(8 pi G r_0^2) (eq 68), rho <= 1/(8 pi G r_0^2) (eq 72). Notes MT's 'at or near the throat' (MT p.405 eq 56) is an N-fold degenerate flare-out.", "read_status": "READ (answer_pdf_queries, pages 1-3, 6-24)"},
   {"ref": "Hochberg & Visser, gr-qc/9802046, Phys. Rev. D 58, 044021 (1998)", "effect": "extends", "what": "Dynamic throats as marginally anti-trapped surfaces (theta = 0, d theta/du >= 0); eqs (77),(82),(90): a hypersurface is a simply-flared throat IFF the NEC is violated or marginal there, for arbitrary time dependence; eq (86)-(88): theta_+ = 0 <=> 2m(r,v) = r, so the throat sits at Misner-Sharp m = r/2 > 0 in the dynamic case too; static limit eq (83) d theta/du|_{r_0} = (1 - b'(r_0))/r_0^2 >= 0 recovers b'(r_0) <= 1. Temporarily suspending the NEC violation eradicates the throat.", "read_status": "READ (answer_pdf_queries, pages 1, 4-5, 11-14, 17, 21, 24-30)"},
   {"ref": "S.-W. Kim, arXiv:1302.3337 (2013), Flare-out condition of Morris-Thorne wormhole and finiteness of pressure", "effect": "narrows", "what": "The matter form of flare-out, zeta = (tau - rho)/|rho| > 0 at the throat, equals the geometric form (b - b'r)/2b^2 > 0 only when lim_{r->b}(r-b)Phi' = 0 (eq 12); the alternative Phi' = B/(r-b) with B finite non-zero makes tau(r_0) = b/8pi r^3 - B/4pi r^2 (eq 20) and either forces a horizon e^{2Phi} = r^2(1-b/r) (eq 26) or a divergent tangential pressure (eq 23). So tau(r_0) = 1/(8 pi r_0^2) carries the hypothesis (r-b)Phi' -> 0, which every regular horizonless MT wormhole -- and the tree's Phi' = 0 -- satisfies. Conclusion: 'the high tension flare-out condition is reasonable and acceptable without any flaw'.", "read_status": "READ (answer_pdf_queries, all 4 pages)"},
   {"ref": "Agnese & La Camera, gr-qc/0203067, Traceless stress-energy and traversable wormholes (2002)", "effect": "confirms", "what": "A published exact traceless (rho = 0) wormhole with throat r_0 = 2m/beta, 0 < beta < 1, and eq (17) p_par(r_0) = -m/(4 pi beta r_0^3) = -beta^2/(32 pi m^2); rederivation C6 shows this equals -1/(8 pi r_0^2) with m_MS = r_0/2 > 0 -- the MT throat values realised in a solution with positive Misner-Sharp mass everywhere.", "read_status": "READ (answer_pdf_queries, pages 1-7)"},
   {"ref": "Harko, Lobo, Mak, Sushkov, arXiv:1301.6878, Modified-gravity wormholes without exotic matter (2013)", "effect": "extends", "what": "In modified gravity the geometric flare-out is unchanged but the NEC violation it entails can be carried by the effective curvature stress tensor while ordinary matter obeys the energy conditions -- Hochberg-Visser 1998 p.5 already warn that the TOTAL effective stress-energy still violates the NEC at the throat. Bears on the interpretation of which sector is exotic, not on any throat value the tree uses.", "read_status": "abstract only (discover_papers); not read at page level"}
 ],
 "lacked_data": "Morris-Thorne 1988 used no measured datum: the throat values are a two-line consequence of Einstein's equations applied to an assumed static spherically symmetric metric, and the rederivation here recovers every one of them from the metric alone with no numerical input (C1-C5). What came later is not data but theorems and sharper hypotheses: Hochberg-Visser 1997/1998 removed spherical symmetry, asymptotic flatness and staticity and found the same conclusion (flare-out iff NEC violated-or-marginal at the throat; throat at m = r/2); Ford-Roman quantum inequalities (1995-96, cited in Lobo Sec. II.F.4) bound the AMOUNT of exotic matter, not its necessity; Kim 2013 showed the tacit regularity hypothesis (r-b)Phi' -> 0 is forced by finite pressure. None of these changes the throat identities, and no later measurement could, since no physical constant survives in them (4 pi r_0^3 p_r / m = -1 is dimensionless and G-free). The only route by which the conclusion moves is a change of field equations (modified gravity), which relocates the NEC violation to an effective sector without removing it (Hochberg-Visser 1998 p.5; Harko et al. 2013). Evidence against M's hypothesis for THIS result: the tree's use of it is exactly the source's algebra, verified symbolically and by z3; there was no data to lack.",
 "grade": "STANDS",
 "grade_evidence": "Every value the tree quotes -- p_r(r_0) = -1/(8 pi r_0^2), m = b(r_0)/2 = r_0/2 > 0, 4 pi r_0^3 p_r = -m, and the sign remark that flare-out is not negative Misner-Sharp mass -- is stated in the restatements READ at source (Lobo 0710.4474 eqs 30, 32-33; Hochberg-Visser gr-qc/9704082 eq 68) and is rederived here from the metric with sympy (22/22 PASS, z3 unsat on both negations). The one published witness solution (Agnese-La Camera eq 17) realises the same values exactly. certify.py's use is a disclaimer of novelty only (NOVELTY_CLAIMED = False), and the literature confirms the disclaimer: m = b/2 and NEC violation at the throat are standard (Lobo eq 32, 71; Hochberg-Visser 1997 Sec. 5). No numerical datum enters. The two hypothesis drifts recorded are both over-strong hypotheses on the tree's side (Phi' = 0 at the throat, which the source does not need; and the prose label 'flare-out condition' attached to an identity that needs only b(r_0) = r_0), so the tree's class sits strictly inside the source's class -- the direction that cannot invalidate a use. Not NARROWED: the result holds on a larger class than the tree uses, not a smaller one. Not DATA-DEPENDENT: no datum. Morris-Thorne 1988 itself remains NAMED-NOT-READ, read via two independent restatements that agree with each other and with the rederivation.",
 "what_would_change_the_grade": "To OPEN: if the two restatements were found to disagree with Morris-Thorne 1988's own eqs (the Am. J. Phys. paper is not at alphaXiv) -- reading the original would close this. To NARROWED: a published static spherically symmetric horizonless wormhole with finite pressures at which tau(r_0) != 1/(8 pi r_0^2); Kim 2013 shows the only escape (lim (r-b)Phi' != 0) costs a horizon or a divergent p_t, so such an example would have to evade his eq (23)-(27) analysis. To WRONG: a computed counterexample to m(r_0) = r_0/2 or to 4 pi r_0^3 p_r = -m within the metric form -- z3 reports both negations unsat, so this would need a different metric form, i.e. a different hypothesis, not a refutation. A repair of the tree's prose (Phi' = 0 stated as needed; 'flare-out condition' used for the throat identity) would remove the two drifts but would not move the grade, since neither drift touches a computed value.",
 "reverify_command": "python3 " + D + "/rederive/morris-thorne-1988-wormhole-throat.py",
 "report_path": D + "/audits/morris-thorne-1988-wormhole-throat.json"
}
with open(rep["report_path"], "w") as f:
    json.dump(rep, f, indent=1)
print("wrote", rep["report_path"])
