import json,hashlib,difflib,re
L=json.load(open('/tmp/L.json'))['L']; new=open('/tmp/new.txt').read()
k=next(kk for kk,l in enumerate(L) if l.startswith('REGRADED CONDITIONAL 2026-08-11 (R 1507).'))
plain=(new+
'The statement carries the standardness clause (register 1481): a half-sided modular inclusion is N ⊆ M with a vector Ω cyclic and separating for both, and σ_t(N) ⊆ N for t ≤ 0 (Lechner–Scotford, Def. 2.1), equivalent to the Borchers triple by Borchers 1992 and Wiesbrock 1993. The earlier statement gave only the inclusion clause. The omitted clause is the one Faulkner and Speranza assume rather than derive — arXiv:2405.00847 §3.1 assumes Ω cyclic for the smaller algebra — and Reeh–Schlieder does not supply it, since their Ω is a vacuum for the averaged null energy operators and, in their words, may not coincide with a global minimal-energy state. Araki and Zsidó, Rev. Math. Phys. 17 (2005) 491–543, extend Wiesbrock to weights and fill a gap in the 1993 proof. '
'The geometric route is closed: Sorce 2024 shows a geometric modular flow needs a conformal Killing vector, and a non-expanding horizon has none; Chandrasekaran and Flanagan (arXiv:2601.07915) have the Killing case. The algebraic route is not blocked: the Borchers–Wiesbrock characterisation is by a one-parameter unitary group with positive generator and mentions no Killing field, and the commutator of the presymplectic potential is already an algebraic object. That route was attempted (registers 1018–1022). Its free half goes through — the commutator gives a positive generator per null generator, negative-to-positive spectral weight 5 × 10⁻⁵, so a standard pair exists per generator and block diagonality keeps them unmixed. The obstruction is in the corner edge modes, where Chandrasekaran and Flanagan show the null translation generator is necessarily two-sided. The proposal that Θ = 0 supplies the missing relative boost fails: θ_ab → a(y) θ_ab under ℓ → a(y) ℓ, so Θ = 0 is invariant under the rescaling and cannot fix its parameter. The paper\'s own route (§7.3) takes the boost from smoothness — local Rindler frames give χ = κ(u ∂_u − v ∂_v) with ∇_(μ χ_ν) = O(u, v), and its footnote 44 needs only a local boost Killing field — establishing the modular flow\'s geometric action to first order at any cut, and states that these cannot be patched together; this object needs finite u₁ < u₂. '
'The reduction bottoms out at positivity of the null translation generator, which Hadamard does not imply: Hadamard is microlocal, a wavefront-set condition, while positivity is a global spectral one; a smooth deformation of the vacuum raises the negative-to-positive spectral weight from 4.8 × 10⁻⁵ to 2.6 × 10⁻³ while leaving the UV tail unchanged, and thermal states are Hadamard and carry both signs. Positivity is a selection criterion assumed by everyone who needs it — Chandrasekaran–Flanagan §8 and Dappiaggi–Moretti–Pinamonti both — and Kay–Wald 1991 obtain uniqueness only for states invariant under the Killing flow, the hypothesis this object drops. '
'The hypothesis is not purely geometric (registers 1038–1042): the standard non-expanding-horizon definition\'s third condition — the Einstein equations hold on Δ and −T^a_b ℓ^b is future causal — is an energy condition on the state, which by Raychaudhuri forces T_ab ℓ^a ℓ^b = 0 and σ_ab = 0, hence £_ℓ q_ab = 0, the hypothesis of the presymplectic potential; so that object assumes a consequence of the definition. The shortfall is one of order: the condition fixes the background, while half-sidedness is spectral on the perturbations.')
L[k]=plain
s='\n'.join(L)
o='Pauli bound (the Pauli bound (register 1141)) already'; assert s.count(o)==1; s=s.replace(o,'Pauli bound (register 1141) already')
open('BUILD83_compendia.md','w',encoding='utf-8',newline='').write(s)
A=open('BUILD81_compendia.md',encoding='utf-8').read()
d=list(difflib.unified_diff(A.split('\n'),s.split('\n'),lineterm='',n=0))
print('hunks',sum(l.startswith('@@') for l in d),'del',sum(l.startswith('-') and not l.startswith('---') for l in d),'add',sum(l.startswith('+') and not l.startswith('+++') for l in d))
print('reverse recovers BUILD81:',hashlib.md5(A.encode()).hexdigest()=='597f5c4326498820d3966e68bf706c98')
print('caps left in M body:',re.findall(r'\b[A-Z]{4,}\b',plain))
b=s.encode();print('BUILD83',len(b),hashlib.md5(b).hexdigest(),b.count(b'\n'))