B.push(h3('16.2  The comparison completed at n ≤ 9'));
B.push(p([t('Section 16.1 compares the frontier with relativistic calculation and finds agreement for every column the ceilings of Equation (1) permit the lattice to name, which is three of the seven Pyykkö fills. It notes that extending to n ≤ 9 would allow the remaining four to be addressed. That extension is a straightforward computation and has been carried out; it changes the standing of the result, and Section 25.3 anticipates that it might.')]));
B.push(p([t('The lattice is rebuilt with n ≤ 9, giving 310 admissible cells against 210, and the occupied set is left unchanged. The frontier is then tracked dynamically rather than statically: at each step the minimal elements of the complement are computed, the column Pyykkö fills next is checked against them, and that column is then filled and the frontier recomputed. This is the correct test, because the frontier is not fixed — opening one column makes others available.')]));
B.push(tcap(9,'The frontier tracked through Pyykkö\'s sequence for Z = 119–172. At each step the frontier is the set of columns the lattice permits to open next; the column actually filled is checked against it. Narrowing is the ratio of unfilled columns to permitted ones.'));
B.push(table(
  ['Step','Pyykkö fills','In frontier','Frontier columns','Unfilled','Narrowing'],
  [['1','8s','yes','5g, 6f, 7d, 8s','16','4.0×'],
   ['2','5g','yes','5g, 6f, 7d, 8p, 9s','15','3.0×'],
   ['3','8p','yes','6f, 7d, 8p, 9s','14','3.5×'],
   ['4','6f','yes','6f, 7d, 9s','13','4.3×'],
   ['5','7d','yes','6g, 7d, 9s','12','4.0×'],
   ['6','9s','yes','6g, 7f, 8d, 9s','11','2.8×'],
   ['7','9p','yes','6g, 7f, 8d, 9p','10','2.5×']],
  [700,1400,1200,2600,900,1100]));
B.push(p([t('Every column Pyykkö fills lies in the frontier at the moment he fills it: seven of seven, with no column forbidden at its filling step. The frontier admits between three and five columns where between ten and sixteen remain unfilled, a narrowing of between 2.5 and 4.3 at each step. Taking the null hypothesis that the next column is drawn uniformly from those still unfilled, the joint probability of seven consecutive hits is 2.0 × 10⁻⁴, or about one in five thousand.')],
  {spacing:{before:160,after:120}}));
B.push(p([t('Three columns are admitted at some step and never filled below Z = 172: 6g, 7f and 8d. These are the false admissions, and they are not contradictions — relativistic calculation places them beyond the range Pyykkö tabulates, so they are untested rather than refuted. The lattice is a permissive condition, not a determination: it narrows the field by a factor of three or four and does not pick within it.')]));
B.push(p([t('What gives the result its weight is the comparison with the rule from which the lattice was built. Both the Madelung rule and the lattice impose order conditions on filling, and Pyykkö\'s sequence violates one and not the other. Madelung places 6f before 8p, since both lie at n + ℓ = 9 and 6f has the smaller n; the calculation reverses them. It also places 8p₃/₂ at level 9 before 9p₁/₂ at level 10; the calculation reverses that too, inverting the level order itself, as Section 11.4 records. The componentwise condition of the lattice survives both, because it constrains only columns comparable in each coordinate separately and says nothing about pairs like 5g and 8s that are incomparable.')]));
B.push(p([t('That is the substance of the comparison, and it should be stated with its scope. The lattice does not predict the order of filling — Section 11.4 establishes that no functional on its coordinates can. What it supplies is a necessary condition on that order, and the condition holds through the whole of Pyykkö\'s tabulated range, where the Madelung rule from which the lattice takes its shape does not. A weaker condition surviving where a stronger one fails is a modest thing; it is nonetheless a checkable claim about configurations beyond those known, which was tested against independent calculation and was not falsified.')]));
