print('  WHAT TURNS ALGEBRA INTO GEOMETRY')
print()
print('  INPUT   purely algebraic:  ( M, N subset M, Omega )')
print('             no manifold, no metric, no coordinates, no generators.')
print('             one condition: sigma_t^M (N) subset N for t <= 0.')
print()
print('  OUTPUT  by Borchers + Wiesbrock:')
print('             U(a) = e^{iPa},  P >= 0')
print('             Delta^{it} U(a) Delta^{-it} = U(e^{-2 pi t} a)')
print('             J U(a) J = U(-a)')
print()
print('             those relations ARE the affine group of the line:')
print('                translations   a  ->  a + s')
print('                dilations      a  ->  e^{2 pi t} a')
print('             the ax+b group, acting on a real line.')
print()
print('  -> a NULL GENERATOR, with its affine parameter, emerges from the modular data.')
print('     that is the converter. it manufactures one-dimensional geometry from')
print('     an inclusion of algebras.')
print()
print('  WHERE THIS IS ALREADY USED')
U=[('Leutheusser-Liu','the emergence of a half-sided modular inclusion in the large-N limit '
    'of a high-temperature thermofield double IS the emergence of a black hole horizon '
    'and of time in the interior','algebra -> geometry'),
   ('Witten, crossed product','the extra L^2(R) factor read as an observer\'s clock',
    'algebra -> a temporal degree of freedom'),
   ('Chandrasekaran-Flanagan','the corner charges generate half-sided boosts and translations '
    'ON the horizon','geometry -> algebra, the other direction'),
   ('CTT','the modular Hamiltonian is a local integral along the generators',
    'geometry -> algebra')]
print('  %-26s %-72s %s' % ('work','what it does','direction'))
for a,b,c in U:
    print('  %-26s %-72s %s' % (a,b[:72],c))
    if len(b)>72: print('  %-26s %s' % ('',b[72:]))
print()
print('  AND HERE IS THE INVERSION')
print()
print('     in holography the algebra is given and the geometry is DERIVED.')
print('     a horizon appears because an inclusion becomes half-sided.')
print()
print('     on an isolated horizon the GEOMETRY IS GIVEN. we have the null generators,')
print('     their affine parameters, the cuts, the cross-sections. all of it.')
print('     what is missing is the ALGEBRAIC CERTIFICATE that the given geometry is')
print('     the one the converter would have produced.')
print()
print('     -> we are asking the converter to run in the direction it already ran,')
print('        and to confirm an answer we already hold.')
print()
print('  WHICH IS WHY THE PROBLEM HAS THE SHAPE IT HAS')
print('     the geometry cannot supply the certificate, because both geometric routes')
print('     (Killing, corner charge) are switched off at Theta = 0 with no Killing field.')
print('     the certificate must come from the state, and that is C2.')
print()
print('     the converter needs one input and one only: sigma_t(N) subset N.')
print('     everything geometric it would output, we already have.')
print('     everything algebraic it needs, we have except that one containment.')
print()
print('  A CAUTION')
print('     "algebra becomes geometry" is a description of what Borchers-Wiesbrock')
print('     DELIVERS, not a mechanism. the theorem produces a group representation;')
print('     calling that group "a null line" is an identification we make, and it is')
print('     justified on a null plane because the group ACTS as translations there.')
print('     on an isolated horizon the identification is what would need establishing,')
print('     and it is not free.')