import base64, hashlib
b64 = "ZnJvbSBpdGVydG9vbHMgaW1wb3J0IHByb2R1Y3QKZGVmIEw4KCk6CiAgICBvdXQ9W10KICAgIGZvciBuIGluIHJhbmdlKDEsNCk6CiAgICAgIGZvciBsIGluIHJhbmdlKDAsbWluKDEsbi0xKSsxKToKICAgICAgICBmb3IgayBpbiByYW5nZSgxLG1pbigzLDQqbCsyKSsxKToKICAgICAgICAgIGZvciBxIGluIHJhbmdlKDAsaysxKToKICAgICAgICAgICAgZm9yIGUgaW4gcmFuZ2UoMSw0KToKICAgICAgICAgICAgICBmb3IgZiBpbiByYW5nZSgwLG1pbigxLGUtMSkrMSk6CiAgICAgICAgICAgICAgICBmb3IgZyBpbiByYW5nZSgwLG1pbig0KmYrMixxKSsxKToKICAgICAgICAgICAgICAgICAgZm9yIFMyIGluIHJhbmdlKDAsaysxKToKICAgICAgICAgICAgICAgICAgICBvdXQuYXBwZW5kKChuLGwsayxxLGUsZixnLFMyKSkKICAgIHJldHVybiBvdXQKZGVmIEw5KCk6CiAgICByZXR1cm4gW3grKHMsKSBmb3IgeCBpbiBMOCgpIGZvciBzIGluIHJhbmdlKDAseFs2XSsxKV0KaWYgX19uYW1lX189PSdfX21haW5fXyc6CiAgICBwcmludCgnfM6bOHw9JyxsZW4oTDgoKSksJyB8zps5fD0nLGxlbihMOSgpKSkK"
data = base64.b64decode(b64, validate=True)
open("lam8.py","wb").write(data)
print("md5:", hashlib.md5(data).hexdigest())
print("bytes:", len(data))