import sys; sys.path.insert(0,"/home/claude/work")
import ground as G
L="spdfg"
print("  EVERY NEUTRAL WITH A FILLED f SHELL INSIDE ITS CORE\n")
F14=[]; NOF=[]
for Z in range(1,109):
    cfg=G.expand(Z)
    f14=[(n,o) for n,l,o in cfg if l==3 and o==14]
    if f14: F14.append((Z,G.GROUND[Z][0],f14[0][0],G.GROUND[Z][1]))
print(f"      {'Z':>4}{'el':>4}{'f shell':>9}   ground shells")
for Z,el,n,sh in F14:
    print(f"      {Z:>4}{el:>4}{f'{n}f14':>9}   {sh}")
print(f"\n      {len(F14)} elements carry a filled f shell\n")
print("  WHAT THEY HAVE IN COMMON\n")
print("      the filled 4f¹⁴ first appears at Yb (Z=70) and persists to Z=86;")
print("      the filled 5f¹⁴ first appears at No (Z=102) and persists.")
print("      so the set is Z = 70–86 and Z = 102–108.\n")
print("  AND HOW THEY DIFFER FROM ALL THE REST\n")
print("      an f¹⁴ shell contributes 14 electrons at ℓ = 3 with ZERO net")
print("      angular momentum and zero net spin — it is spherically symmetric,")
print("      like any closed shell. so it does not change the ANGULAR part.")
print()
print("      what it changes is the RADIAL screening: 14 electrons packed at")
print("      n = 4 (or 5), INSIDE the valence n = 6 (or 7). the 4f shell is")
print("      radially compact — it sits under the 5s5p shells — so it screens")
print("      the nucleus almost completely for anything outside it.")
print()
print("      that is the lanthanide contraction, and it is exactly the")
print("      difference between Nₑ = 56 (no 4f) and Nₑ = 70 (4f¹⁴).\n")
print("  THE COUNT\n")
print(f"      {'Nₑ':>5}{'f electrons in core':>22}{'crosses at c':>14}")
for ne,nf,cc in ((20,0,2),(38,0,2),(56,0,2),(70,14,3),(88,14,3),(102,28,5)):
    print(f"      {ne:>5}{nf:>22}{cc:>14}")
print()
print("      0 f electrons  → c = 2, 2, 2")
print("      14 f electrons → c = 3, 3")
print("      28 f electrons → c = 5")
print()
print("      → the crossing charge is a function of the f-electron count in")
print("        the core, and ONLY of that, across all six ladders.")
print()
print("  THE RELATION\n")
for nf,cc in ((0,2),(14,3),(28,5)):
    print(f"      n_f = {nf:>2}  →  c = {cc}")
print()
print("      differences: 14 → +1, then 14 → +2.  not linear.")
print("      but with only three distinct values this is 3 points and 2 gaps;")
print("      any monotone form fits. what IS established is that n_f")
print("      SEPARATES the ladders completely — 0/14/28 maps to 2/3/5 with")
print("      no overlap and no exception in six ladders.")