print('  BUILDING THE CURVED-SPACE EXTENSION FROM EACH SIDE')
print()
print('  SIDE A -- what Hartman-type arguments NEED')
A=[('a lightcone OPE','local operators expanded in the lightcone limit; the averaged null '
    'energy appears as a non-local term'),
   ('a positive sum rule','isolating that term and showing it manifestly non-negative'),
   ('microcausality','commutators vanish at spacelike separation -- available in curved space'),
   ('conformal / Poincare symmetry','the OPE coefficients and the lightcone limit are '
    'organised by the symmetry group. THIS is what curved space lacks.')]
for a,b in A: print('     %-28s %s' % (a,b))
print()
print('  SIDE B -- what the relative-entropy route NEEDS')
B=[('a modular Hamiltonian','K_psi = -log rho_psi for the region'),
   ('monotonicity of relative entropy','available in general; a theorem about algebras'),
   ('K GEOMETRIC','the crucial step: K must equal an integral of the stress tensor. '
    'in flat space this is Bisognano-Wichmann. in curved space it holds ONLY for '
    'bifurcate Killing horizons (Kay-Wald).'),
   ('a regulator for entropy differences','SUPPLIED, in general curved spacetime, '
    'by the modular crossed product (Kudler-Flam et al 2025)')]
for a,b in B: print('     %-28s %s' % (a,b))
print()
print('  WHAT EACH CURVED-SPACE RESULT ACTUALLY ASSUMES')
R=[('Bekenstein bound (crossed product, 2025)','a globally KMS state w.r.t. a Killing field'),
   ('QNEC (crossed product, 2025)','cuts of a RINDLER horizon in Minkowski'),
   ('Wall, ANEC from the GSL','causal horizons; the GSL for those horizons'),
   ('Kontou-Olum','free, minimal, small curvature, null convergence condition'),
   ('Iizuka-Ishibashi-Maeda','a holographic bulk dual; the no-bulk-shortcut principle'),
   ('Rosso','maximally symmetric backgrounds -- maximal Killing symmetry')]
for a,b in R: print('     %-42s %s' % (a,b))
print()
print('  THE COMMON RESTRICTION')
print('     six independent curved-space routes.')
print('     five of the six require a Killing field or a horizon generated by one.')
print('     the sixth (Iizuka et al) replaces it with a holographic dual and gets')
print('     a WEIGHTED bound rather than the ANEC.')
print()
print('     -> the shared missing object is a GEOMETRIC MODULAR HAMILTONIAN')
print('        in the absence of a Killing symmetry.')
print()
print('  CAN THE TWO SIDES BE JOINED WITH WHAT EXISTS?')
print('     Side B has the regulator in general curved spacetime (2025).')
print('     Side B has monotonicity of relative entropy in general.')
print('     Side B LACKS K geometric without a Killing field.')
print('     Side A LACKS the symmetry that organises the lightcone OPE.')
print()
print('     both gaps are the SAME gap in different language:')
print('        "K is an integral of T" and "the OPE is organised by a symmetry group"')
print('        are both statements that a spacetime symmetry exists.')
print()
print('     so the join is NOT available. and it is not two problems, it is one.')
print()
print('  WHAT WOULD CONSTITUTE THE EXTENSION')
print('     a theorem of the form:')
print('        for a causal diamond in a general globally hyperbolic spacetime,')
print('        the modular Hamiltonian of the vacuum-like state is, to leading order')
print('        near the horizon, the boost generator of the local Rindler wedge.')
print('     that is the known hard problem. it is what Bisognano-Wichmann gives in')
print('     flat space and what Kay-Wald gives only with a bifurcate Killing horizon.')
print()
print('  HONEST STATUS')
print('     we do NOT have what we need to build it from each side.')
print('     what we DO have is the identification: the two sides fail for one reason,')
print('     and that reason is nameable and is not the ANEC.')
print('     the ANEC gap in curved spacetime is a MODULAR THEORY gap.')