import pickle
from itertools import combinations
D=pickle.load(open('/home/claude/stage/s1.pkl','rb'))
res=pickle.load(open('/home/claude/stage/s2.pkl','rb'))
cells=D['cells']; n=len(cells); d=3
print("="*88)
print("  IS THERE A GROWTH MECHANISM?")
print("="*88)
print("""
  **The test.** Every reorderable set should be reachable from a small one by
  adding cells ONE AT A TIME, reorderable at every step. **If so the YES table
  is generated by a growth process and no box exhaustion is needed** — the
  mechanism builds only the entries it reaches.

  Exhaustive data is available for the 2×3×3 box: 260,800 classified subsets.
""")
YES={m for m in range(1<<n) if res[m]==2}
print("     reorderable subsets : %d"%len(YES))
bysize={}
for m in YES: bysize.setdefault(bin(m).count('1'),[]).append(m)
print("     by size :",{k:len(v) for k,v in sorted(bysize.items())})
print("="*88)
print("  UPWARD REACHABILITY — can each YES set be grown from a smaller YES set?")
print("="*88)
sizes=sorted(bysize)
reach={}
base=min(sizes)
for m in bysize[base]: reach[m]=True
print("\n  %8s%12s%16s%16s"%("size","YES sets","grown from YES","orphans"))
print("  "+"-"*54)
print("  %8d%12d%16s%16d"%(base,len(bysize[base]),"(base)",0))
for s in sizes[1:]:
    ok=0; orph=0
    for m in bysize[s]:
        found=False
        for i in range(n):
            if m>>i & 1:
                p=m & ~(1<<i)
                if res[p]==2 and reach.get(p,False): found=True; break
        reach[m]=found
        ok+=found; orph+= (not found)
    print("  %8d%12d%16d%16d"%(s,len(bysize[s]),ok,orph))
tot=len(YES); grown=sum(1 for m in YES if reach.get(m,False))
print("\n     **reachable by single-cell growth : %d of %d  (%.1f%%)**"%(grown,tot,100*grown/tot))
print("="*88)
print("  AND THE MECHANISM'S COST")
print("="*88)
print("""
  If growth is complete, the mechanism is:

     1. start from the minimal reorderable sets
     2. add one cell; keep it if still reorderable
     3. record the signature

  **The cost is |YES| × |X| lattice tests, not 2^box.** For this box that is
  %d × 18 against 260,800 — **a factor of %.1f.**
"""%(tot,260800/(tot*18/1000+1e-9)/1000 if tot else 0))
print("="*88)
print("  DOES IT COVER THE SIGNATURES?")
print("="*88)
tab=D['tab']; NF=D['nforms']
def sig(m):
    idx=[i for i in range(n) if m>>i & 1]
    c=[0]*NF
    for T in combinations(idx,3): c[tab[T]]+=1
    return tuple(c)
allY={sig(m) for m in YES}
grownY={sig(m) for m in YES if reach.get(m,False)}
print("\n     YES signatures, all      : %d"%len(allY))
print("     YES signatures, grown    : %d"%len(grownY))
print("     **missed by the mechanism: %d**"%len(allY-grownY))