h2('13.  The Occupied Cells Form an Order Ideal'));
B.push(p([t('An order ideal, or down-set, of a poset is a subset closed downward: if x belongs to it, so does every element below x. Testing this for the occupied cells of Λ — for every occupied x and every admissible y with y ≤ x componentwise, is y also occupied? — returns no violations across all 118 cells. The downward closure of the occupied set is exactly the occupied set.')]));
B.push(p([t('In chemical terms the statement is this. If an element exists whose ground-state valence configuration is (n, ℓ, k), then every configuration with no larger shell, no larger subshell and no larger occupancy is likewise realised by some element. There are no gaps beneath any occupied cell. The test is not vacuous: the number of admissible cells lying below an occupied cell ranges from one to ninety-two across the 118, and every one of those cells is occupied, as Figure 9(b) records.')]));
B.push(img('F10_ideal.png',640,211));
B.push(cap(9,'The periodic system as an order ideal of Λ. (a) The 210 admissible cells arranged by shell, with the 118 occupied cells filled. The occupied region is closed downward; the three maximal cells are outlined in green and the five cells covering them in gold. (b) For each occupied cell x, the number of admissible cells below it against the number of those that are occupied. All 118 points lie on the diagonal, with counts ranging from 1 to 92. (c) The discovery frontier: any element beyond those known must occupy a cell covering one of the three maximal cells, giving five candidate addresses.'));

B.push(h3('13.1  The property is a corollary, and the derivation is short'));
B.push(p([t('It would be a mistake to present this as a discovery. The property follows from two facts, one arithmetic and one physical, and the derivation is two lines. It is set out here rather than left implicit, because a reader entitled to ask whether the result is more than a restatement deserves the answer.')]));
B.push(p([t('First, the cell-level statement reduces to a statement about columns. Group the admissible cells into columns indexed by (n, ℓ), each of capacity 2(2ℓ+1). Suppose every occupied column is filled to capacity — which Section 14 establishes. Let x = (n, ℓ, k) be occupied and let y = (n′, ℓ′, k′) ≤ x be admissible. Since y ∈ Λ we have k′ ≤ 2(2ℓ′+1), so if the column (n′, ℓ′) is full then y is occupied. Conversely a missing column below an occupied one breaks closure immediately. Cell-level closure and column-level closure are therefore equivalent, and direct computation confirms that both hold.')]));
B.push(p([t('Second, column-level closure follows from the filling rule. The componentwise order on columns refines the Madelung order, because n′ ≤ n and ℓ′ ≤ ℓ together give n′ + ℓ′ ≤ n + ℓ; this is arithmetic and admits no exceptions, as direct enumeration over all pairs of columns confirms. And aufbau fills a column to capacity before opening the next. Together these give the result: if a column is reached at all, every column beneath it in the componentwise order was reached earlier and completed. Downward closure is the order-theoretic shadow of monotone filling, and calling it anything more would overstate it.')]));

B.push(h3('13.2  What does not follow, and why it is worth having'));
B.push(p([t('Three things about the property are not corollaries, and they are what makes the section worth its place.')]));
B.push(p([t('The first is that it survives the anomalies. Thirty elements sit out of Madelung sequence and twenty have configurations that depart from the Madelung prediction outright. If the down-set property were simply a restatement of Madelung filling, those departures ought to threaten it. They do not, and the reason requires an argument that the two-line derivation does not supply: the property concerns the accumulated set over all 118 elements, not the configuration of any single one. An anomaly relocates an electron at one atomic number; it does not remove a cell that an earlier element already occupied as its valence cell. Chromium is 3d⁵4s¹ rather than 3d⁴4s², so at Z = 24 the 4s column holds one electron — but potassium and calcium already contributed (4, 0, 1) and (4, 0, 2), and the accumulated set has that column complete. Ordering is disturbed; closure is not. Section 2 records that the result is moreover identical under either of the two conventions for assigning anomalous configurations.')]));
B.push(p([t('The second is that it survives every extension to excited states that could be constructed, which Section 15 sets out, and that one such extension separates it cleanly from the saturation property of Section 14. That separation is not predictable from the derivation above.')]));
B.push(p([t('The third is quantitative. That the occupied columns number nineteen against six empty and none partial, that the resulting configuration is one of exactly 120 admissible ones, and that the frontier reduces to five addresses are counts rather than consequences. They are established in Sections 14 and 16 and none of them follows from monotone filling alone.')]));

B.push(