mv fig1_cells.png       F01_census.png
mv fig2_lattice3d.png   F02_elements.png
mv fig07_dimension.png  F03_dimension.png
mv fig8_closure.png     F04_closure.png
mv figB_rigidity.png    F05_rigidity.png
mv fig7_order.png       F06_madelung_janet.png
mv fig11_fibres.png     F07_fibres.png
mv fig3_classes.png     F08_classes.png
mv fig4_adjacency.png   F09_adjacency.png
mv fig9_ideal.png       F10_ideal.png
mv fig10_columns.png    F11_columns.png
mv figA_linext.png      F12_linext.png
mv fig5b_hydride.png    F13_hydride.png
mv fig5c_benchmark.png  F14_benchmark.png
mv figC_limits.png      F15_limits.png
mv fig5_screen.png      F16_screening.png
mv fig6_convention.png  F17_convention.png
mv fig7_scalegap.png    F18_scalegap.png