B.push(h2('12.  Why These Coordinates and Not Others'));
B.push(p([t('Section 10 established by exhaustive checking that Λ is closed under join and meet. That leaves the more useful question of why, and whether the closure is a coincidence of the particular numbers involved. It is not, and the reason places the lattice within a standard piece of order theory rather than establishing anything new. Stating it correctly also settles the fate of an extension proposed in an earlier draft of this work.')]));

B.push(h3('12.1  Λ as an intersection of sublattices'));
B.push(p([t('A subset of a product of chains that is closed under componentwise join and meet is a sublattice of that product, and finite intersections of sublattices are sublattices. The relevant observation is that certain elementary constraint types cut out sublattices of the full box, and that Λ is an intersection of exactly such sets.')]));
B.push(p([t('Constraints of the forms x_i ≤ x_j, x_i ≤ c and x_i ≥ c each define sublattices, as do constraints x_i ≤ f(x_j) with f monotone non-decreasing. What these share is that every coordinate appears with the same orientation on both sides: raising the operands raises both the constrained quantity and its bound, and lowering them lowers both. Direct verification on a 6 × 6 × 6 box confirms closure for each such constraint individually and for every pairwise and triple intersection tested.')]));
B.push(p([t('Λ is built this way. Starting from the box n ≤ 7, ℓ ≤ 4, k ≤ 18, which contains 630 cells and is trivially a sublattice, the constraint ℓ ≤ n − 1 reduces it to 450 cells and the constraint k ≤ 2(2ℓ+1) to the 210 admissible cells of Λ. Each step intersects with a sublattice, so closure is inherited rather than coincidental. The lower bounds n ≥ 1, ℓ ≥ 0 and k ≥ 1 are constants and impose no further condition.')]));
B.push(p([t('This is a standard argument and no novelty is claimed for it. What is worth recording is that the coordinates of Part I happen to satisfy the condition, which is why the results of Sections 10 and 11 hold.')]));

B.push(h3('12.2  Where the hydrogenic labelling fails'));
B.push(p([t('An earlier draft observed that the occupancy index k conflates the magnetic quantum number m with the spin projection, and proposed unfolding k into those constituents in the hope of admitting the SO(4,2) representation theory that the three-axis form cannot support. The account just given shows why that cannot work, and locates the obstruction precisely.')]));
B.push(p([t('The hydrogenic constraint is |m| ≤ ℓ, which is the conjunction of two inequalities: m ≤ ℓ and −m ≤ ℓ. The first is of the permitted form. The second is not, because the coordinate m enters negated, and orientation is reversed: raising m makes the left-hand side smaller rather than larger. Constraints in which a coordinate appears with mixed orientation do not in general define sublattices, and the same defect appears in familiar examples such as |x − 2| ≤ y, which fails closure on a 6 × 6 box.')]));
B.push(p([t('Building Λ′ = {(n, ℓ, m, s)} constraint by constraint shows the failure entering at a single identifiable step. The hydrogenic box is a sublattice; adding ℓ ≤ n − 1 leaves 450 cells and preserves closure; adding m ≤ ℓ leaves 330 cells and still preserves it; adding −m ≤ ℓ gives the 210 admissible cells and destroys it. Exhaustive checking of the resulting set returns zero join failures and 4,040 meet failures.')]));
B.push(p([t('A concrete instance makes the mechanism plain. The cells (ℓ, m) = (3, −3) and (1, 1) are both admissible. Their componentwise meet is (1, −3), for which |−3| > 1, and the meet leaves the admissible set. Figure 8 contrasts this with the behaviour of k, whose bounds carry no orientation reversal.')]));
B.push(img('fig8_closure.png', 640, 211));
B.push(cap(8, 'Why the occupancy coordinate is load-bearing. (a) The constraint on k: a ceiling rising with ℓ and a constant floor at k = 1, both monotone in the same orientation, so meets remain admissible. (b) The hydrogenic constraint on m: the ceiling m ≤ ℓ is permitted, but the floor m ≥ −ℓ places m on the left with reversed orientation. The meet of (ℓ, m) = (3, −3) and (1, 1) is (1, −3), which violates |m| ≤ ℓ. (c) Closure across four coordinate systems, each containing exactly 210 cells. Only the signed hydrogenic labelling fails, and it fails on meet alone.'));

B.push(h3('12.3  Why the repair is not a repair'));
B.push(p([t('Closure can be restored by substituting m′ = m + ℓ, which converts the pair into m′ ≤ 2ℓ and m′ ≥ 0 — a monotone ceiling and a constant floor, both permitted. Verification confirms that the shifted four-axis set is again closed, and re-indexing the magnetic states from 1 to 2ℓ+1 achieves the same effect.')]));
B.push(p([t('But the repair defeats its own purpose. The coordinate m′ is not the magnetic quantum number; it is m displaced by an amount that varies across the lattice. The representation theory that motivated the unfolding acts on m, not on m shifted by a position-dependent offset, and so has no more purchase on the shifted lattice than on the original. Closure is recovered precisely by abandoning the object the unfolding was performed to obtain. The proposal is therefore withdrawn: no four-axis refactoring of Λ both preserves the order structure of Sections 10 and 11 and exposes the hydrogenic labels in a form on which group theory can act.')]));

B.push(h3('12.4  What this means for the rest of the paper'));
B.push(p([t('The account above clarifies the standing of results elsewhere in this work, in three ways.')]));
B.push(p([t('It explains rather than merely reports. The facts of Section 10 — that Λ is a bounded lattice, that hydrogen is its unique minimum, that shell capacities appear as slice volumes — follow from the constraints being of a permitted form, rather than resting on exhaustive verification alone. Hydrogen occupies the least position because all three floors are constants and n begins at 1.')]));
B.push(p([t('It identifies what is load-bearing. The occupancy coordinate k, introduced in Part I as nothing more than the electron count, is the coordinate that makes the structure work: its bounds carry no orientation reversal, and the results of Part II would not survive its replacement by the hydrogenic labels it conflates. This gives independent significance to the finding of Section 8.3, where k was the coordinate carrying information orthogonal to established chemical descriptors. The same coordinate does the work in both the order-theoretic and the empirical results.')]));
B.push(p([t('And it sets a boundary. Because no admissible refactoring exposes m, the framework cannot be connected to the dynamical symmetry group of the hydrogen atom by any route considered here. Whatever the lattice is, it is not a representation-theoretic object in disguise; it is a combinatorial one, and its correspondences are with other combinatorial descriptions of the periodic system, of which the Janet arrangement of Section 11 is the principal example.')]));
B.push(p([t('A final observation belongs here, since it concerns where the substance of this work resides. The identities underlying Equation (4) were verified symbolically and hold exactly: the normalisation cos²(Ωt) + 2·[sin(Ωt)/√2]² = 1 is identically satisfied, as is cos(Ωt) + sin(Ωt) = √2 sin(Ωt + π/4). But the summation in Equation (4) carries no element label and its prefactor is element-independent, so all 118 elements share a single envelope. The expression is a correct normalisation statement about Λ rather than a dynamical law distinguishing one element from another; everything element-specific resides in ΔQ and σ²(t), which are geometric quantities. Taken together with the results of this part, the substantive content of the framework is the lattice and its order structure. The field equation from which the work takes its name is the weakest component, and readers should weigh it accordingly.')]));
