B.push(h2('25.  Two Objections'));
B.push(p([t('A framework of this kind attracts two objections that no amount of internal checking answers, and it is better to put them in the author\'s own words than to leave them to a reader. Both are serious. One is partly answerable and one is not.')]));

B.push(h3('25.1  That it re-describes rather than discovers'));
B.push(p([t('Janet\'s arrangement dates from 1929, the Madelung rule is older, secondary periodicity was named by Biron in 1915, and kainosymmetry has an established literature. A reader is entitled to ask how much of this paper is new and how much is familiar chemistry rewritten in coordinates. Table 8 answers the question by listing both, and the honest summary is that the paper contains twelve re-descriptions and fourteen results not located elsewhere.')]));
B.push(tcap(8,'What is re-described and what is not. The first column records material already established, for which this paper supplies a coordinate expression; the second records results that the searches of Section 21.1 did not locate elsewhere. The division is stated at the level of claims rather than of sections, and several sections contain both.'));
B.push(table(
  ['Established elsewhere, here re-expressed','Source','Not located elsewhere','Section'],
  [['The Madelung filling rule','Madelung 1936','Order dimension of Λ is exactly three','7'],
   ['The Janet left-step arrangement','Janet 1929','Which coordinates may be adjoined, and three failure modes','9.1, 9.4'],
   ['That the left-step form follows from Madelung','Thyssen & Ceulemans','A closed relativistic lattice on j-subshells','9.3'],
   ['Period-length doubling in the left-step table','Ceulemans & Thyssen','Proof of the pairing V(2m−1) = V(2m) = 2m²','11.1'],
   ['Shell capacities 2n²','Bohr onward','The shear carrying a shell onto its paired slices','11.1'],
   ['Chemical groups as valence columns','Mendeleev onward','Why secondary periodicity recurs every second period','12.3'],
   ['The contested placement of helium','long debated','ℓ-axis rigidity: one ordering of 120','12.4'],
   ['Kainosymmetry and its consequences','Biron; Schwarz; Kaupp','Uniqueness of the Madelung shear','12.4'],
   ['Secondary periodicity and its cause','Biron 1915','Column saturation; the system as one of 120','14'],
   ['The twenty anomalous configurations','standard','Convention dependence: seven holes','13.3'],
   ['Pettifor and Miedema descriptors','Pettifor; Miedema','Z and Madelung are linear extensions; Pettifor is not','19'],
   ['Relativistic reordering above Z ≈ 120','Pyykkö 2011','Non-linearity of the Mendeleev number, as a theorem','20'],
   ['—','—','Λ ⊆ ℕ³; no metric coordinate can be adjoined','22'],
   ['—','—','Frontier columns matching relativistic prediction','16.1']],
  [2500,1300,2900,700]));
B.push(p([t('The objection is therefore partly sustained and partly not. It is sustained in that the physics is not new: every phenomenon the lattice touches was known before it, and in several cases the explanation was known too. Where the paper claims to account for something — the recurrence of secondary periodicity, the doubling of period lengths — what it supplies is a derivation of a regularity whose cause was already understood, not the cause itself. It is not sustained in that the fourteen entries in the second column are not re-descriptions of anything: an order dimension, a closure criterion, a bijection and four impossibility results are statements that had no prior expression in this subject, whatever their standing in order theory generally.')],
  {spacing:{before:160,after:120}}));
B.push(p([t('The fair characterisation is that the contribution is a formalisation. That is a smaller thing than a discovery and a larger thing than a notation: a notation renames, whereas a formalisation supports proof, and the second column consists of theorems and exhaustive computations rather than restatements. Whether a formalisation earns its place is a judgement the paper cannot make for itself. Janet\'s table earned its place without predicting anything.')]));

B.push(h3('25.2  That it predicts nothing'));
B.push(p([t('The second objection is harder and the paper does not answer it. Six predictive applications were attempted and all six failed or were outperformed by descriptors available since the 1980s. That is the number on which a referee will fasten, and the fastening is correct. A framework that reorganises known structure and predicts nothing new is a notation whatever its internal elegance, and the burden of showing otherwise lies with the framework.')]));
B.push(p([t('What can be said against it is thin and should be stated as thin. One prediction was made and confirmed: the frontier columns 5g, 6f and 7d of Section 16.1, which are exactly those that relativistic calculation independently places next among the columns the lattice\'s ceilings permit it to name. But the agreement is at the level of columns rather than order, it is agreement with a calculation rather than a measurement since no element beyond Z = 118 exists, and it constrains valence configuration rather than nuclear stability. Two retrodictions succeed — the placement of secondary periodicity at twelve of fourteen group–diagnostic pairs, and the flagging of Mendeleev\'s three predicted elements among thirteen candidates in the 1869 set — but both concern phenomena already known when they were tested, and the second flags the noble gases too, which Mendeleev did not predict.')]));
B.push(p([t('One narrow empirical result survives benchmarking, and Section 23.2 establishes that it does not generalise: valence occupancy carries information about hydride formation enthalpy that Pettifor\'s scale does not encode, and carries nothing about the structure-map separation that scale was built for. That is a contribution to one method on one task, tested on thirty-nine metals.')]));
B.push(p([t('So the ledger stands at six failures, one confirmed prediction of limited scope, two retrodictions of known phenomena, and one single-task empirical gain. Section 23.6 already draws the conclusion the referee would draw: the lattice organises and does not predict. This section records that the author agrees, and that the paper is offered on that basis rather than in spite of it.')]));

B.push(h3('25.3  What would change the verdict'));
B.push(p([t('It is worth saying what a successful prediction would have to look like, since the absence of one is the paper\'s principal weakness and the shape of the missing thing constrains where to look.')]));
B.push(p([t('It would have to be ordinal, because Section 22 establishes that the lattice cannot reach metric quantities and Section 12.3 that it supplies position and rank but not magnitude. It would have to concern configuration rather than energy, since every metric application tried has failed and the reason is structural rather than incidental. And it would have to be checkable against something not yet known, since the two successful retrodictions concern phenomena that were established before the test.')]));
B.push(p([t('Those three conditions point to a narrow target: the ordering of properties among elements not yet characterised, or a structural statement about configurations at atomic numbers beyond 118. The frontier result of Section 16.1 is of exactly that kind and is the reason it is the one prediction that survives. Extending the lattice to n ≤ 9, which Section 16.1 notes is a straightforward computation, would allow the remaining four columns of Pyykkö\'s sequence to be addressed and would make that comparison complete. If the framework has a predictive future it is most likely there, and if a complete comparison failed, the verdict of Section 25.2 would become final rather than provisional.')]));
