s=open('mkmd2.py').read()

# insert a new Part XIII before Part X, and renumber by inserting after Part IX
anchor = """---

## Part X · Results"""
newpart = """---

## Part X · Six more indices, and what the null case is

Part I's thesis needs instances that are not the two it was built from. Six were built.

### 10.1 The vocabularies that are indices

{hdr(['index','letters','cells','box','E','non-monotone','verdict'])}
{row(['**V3 geometry**','5',F['V3']['cells'],F['V3']['box'],F['V3']['E'],F['V3']['nonmono'],'**CLOSED**'])}
{row(['**V6 solution**','4',F['V6']['cells'],F['V6']['box'],F['V6']['E'],F['V6']['nonmono'],'**CLOSED**'])}
{row(['**local null surface**','6',F['null_surface']['cells'],F['null_surface']['box'],F['null_surface']['E'],F['null_surface']['nonmono'],'**CLOSED**'])}
{row(['ANEC proofs','4',F['anec_index']['covered'],F['anec_index']['box'],F['anec_index']['E'],F['anec_index']['nonmono'],'**CLOSED**'])}
{row(['charger index','6',F['charger_index']['cells'],F['charger_index']['box'],F['charger_index']['E'],F['charger_index']['nonmono'],'open, but at {F['charger_index']['density']}% density'])}

**Everything built outside V1 closes.** The defect is in V1, on the V1–V3 edge, and in the partition
itself — nowhere else.

**V6 carries the conjecture.** Four of five known achronal-ANEC violations fall outside its admissible
region — chronal geodesics, fixed backgrounds, Planck-scale — and the fifth was withdrawn by its own
authors as a conformal artefact. **The self-consistent achronal ANEC is free of counterexamples because
V6 excludes them.** That is a scoping fact about the solution index, not a physical fact about the laws.

**And the charger index converges with Part VIII independently.** Six chargers over six properties: every
one has trigger arity 1, and **none is universal.** The empty JUR = 0 direction is exactly the charger
shape that would close the law index — §8.2 computes that an unjurisdicted forcing gives E = 0 at 1,938
cells. **The missing cell in the charger index and the defect in the law index are one absence at two
levels**, and the two computations share no code.

### 10.2 The measure

Part II's §2.8 says the measure is external. It is, and not for the reason given.

{hdr(['measure','resolves','distinct values','faithful'])}
{chr(10).join(row([m['name'], str(m['resolves'])+'%', m['values'], 'YES' if m['faithful'] else 'no']) for m in F['measure_index']['measures'])}

**A faithful measure exists and compresses 976 cells to eighteen values.** Any strictly monotone function
of the coordinates is automatically faithful, since a strict descent in the order drops some coordinate
and raises none. **Physics does not use it.** The Coulomb energy resolves 47.7% of the order; the grade
resolves all of it and means nothing.

> The obstruction is not that the measure cannot be compressed. **It is that the compression which works
> is not the one that corresponds to anything.**

### 10.3 Λ audited, and the null case relocated

{hdr(['','conflated','clean','ungrounded','missing','rate'])}
{row(['violation index V1','5','—','—','—',str(F['lambda_audit']['v1_rate'])+'%'])}
{row(['**Λ**',F['lambda_audit']['conflated'],F['lambda_audit']['clean'],F['lambda_audit']['ungrounded'],F['lambda_audit']['missing'],'**'+str(F['lambda_audit']['rate'])+'%**'])}

**The rates are indistinguishable.** The paper presented Λ as the clean control and the violation index
as the contested case; proportionally they are the same.

**The causes differ.** V1 conflates because two literatures used one word. **Λ conflates because an
approximation is not a coordinate**: n and ℓ are exact eigenvalues in hydrogen and configuration labels
everywhere else, and the central-field approximation is nowhere in the index.

**And q is ungrounded** — no referent in the spectroscopic literature at all. Not conflated: there is
nothing to conflate with. **Audit 22 cannot detect this**, because if no theorem names the term, the pair
never enters its table.

{hdr(['','clean','conflated'])}
{row(['**closed**','**V3 geometry**','**Λ**  ·  V6 solution'])}
{row(['**open**','*empty*','**V1 laws**'])}

> **Closure does not certify the letters. An index can be globally consistent and still not mean what it
> says.** E states that the cells are mutually consistent; it says nothing about whether the coordinates
> refer to anything. **That is why audit 22 has to exist**, and the paper has never given the reason that
> plainly.

**Λ is not the control. It is the closed-and-conflated instance**, and the clean null case transfers to V3,
whose five letters all carry exact Hawking–Ellis definitions.

### 10.4 Where the null-energy gap actually is

Six independent curved-space routes to the ANEC. **Five require a Killing field or a horizon generated by
one**; the sixth replaces it with a holographic dual and yields a weighted bound rather than the ANEC.

> **The ANEC gap in curved spacetime is not an ANEC problem. It is a modular theory problem.**

Both routes fail for one reason. The causality route needs a lightcone OPE, organised by a symmetry group.
The relative-entropy route needs the modular Hamiltonian to be **geometric** — an integral of the stress
tensor — which is Bisognano–Wichmann in flat space and Kay–Wald only for bifurcate Killing horizons.
**"K is an integral of T" and "the OPE is organised by a symmetry group" are the same statement.**

**And the obvious repair is excluded by theorem.** Sorce (2024): *any geometric modular flow must be
generated by a conformal Killing field.* So a near-horizon-boost extension does not exist in general — not
hard, excluded.

**The route that does not need geometric flow is half-sided modular inclusion**, which gives K in terms of
T for null cuts even where the flow is non-local. Localising the target in the null-surface index of §10.1:

{hdr(['region','cells','status'])}
{row(['Killing horizons — STAT = 0',F['null_surface']['killing_cells'],'HSMI established, arbitrary interacting QFT'])}
{row(['non-expanding, Killing or not — THETA = 0',F['null_surface']['nonexpanding_cells'],'the target'])}

> **The open question is HSMI on isolated horizons** — non-expanding, quasi-local, no Killing field, no
> asymptotic structure. One cell from where it is proved, and the cell is standard in general relativity.

**The frontier moved in 2026.** Chandrasekaran and Flanagan construct half-sided supertranslation
generators from corner edge modes, with the modes serving both as the anchor for gravitational dressing
and as the source of the translation generator, giving a Type II∞ algebra per horizon cut. The generator's
two-sided dependence enters **only through the expansion**, so on a non-expanding horizon it is one-sided
at leading order — the regime that matters.

### 10.5 A term whose status is scope-dependent

{chr(10).join(row([a,b]) for a,b in [('instance','what changes across the scope')]+F['shape']['instances'])}

**Five instances, one shape**, and the last is stated as physics rather than bookkeeping. Chandrasekaran
and Flanagan, following Rovelli: *gauge redundancy is not merely a redundancy; it is the bookkeeping
needed to relationally describe subsystems in a gauge-invariant system.* Their footnote: the edge modes
"appear as gauge degrees of freedom in the top down approach, but as physical degrees of freedom in the
bottom up approach."

**One directed test.** Where an anchor exists — null infinity — BMS supertranslations carry nonvanishing
charges and parametrise the final state of collapse alongside mass and angular momentum: **physical in the
geometry too.** Where it is absent, an NEH's free data is provably supertranslation-invariant.
**The reversal is present exactly where the anchor is absent**, and the test facts come from a literature
the shape was not built from.

**Status: one test passed, one directed search for a counterexample finding none.** That is thin evidence,
and it is more than the six-instance pattern withdrawn in §11.2 had.

---

## Part XI · Results"""
assert anchor in s
s=s.replace(anchor,newpart,1)
# renumber the parts after X
for a,b in [('## Part XI · Register','## Part XII · Register'),
            ('## Part XII · Open','## Part XIII · Open')]:
    s=s.replace(a,b,1)
s=s.replace('- [Part X · Results](#part-x--results)',
 '- [Part X · Six more indices, and what the null case is](#part-x--six-more-indices-and-what-the-null-case-is)\n'
 '- [Part XI · Results](#part-xi--results)')
s=s.replace('- [Part XI · Register](#part-xi--register)','- [Part XII · Register](#part-xii--register)')
s=s.replace('- [Part XII · Open](#part-xii--open)','- [Part XIII · Open](#part-xiii--open)')
open('mkmd2.py','w').write(s)
print('Part X inserted; parts renumbered')