p=open('paper.md').read()
def sub(old,new,label):
    global p
    assert old in p, f"NOT FOUND: {label}"
    p=p.replace(old,new,1); print("patched:",label)

# --- figure callouts ---
sub("Base q, fibre A(q) × B(q), profile 165 · 330 · 345 · 136, summing to 976",
    "Base q, fibre A(q) × B(q), profile 165 · 330 · 345 · 136, summing to 976 (Figure 2)","fig2")
sub("**Tree.** e — f — g — q — k — ℓ — n, with 2S attached to k:",
    "**Tree** (Figure 1)**.** e — f — g — q — k — ℓ — n, with 2S attached to k:","fig1")
sub("**Birkhoff.** 976 cells are generated by 17 join-irreducibles",
    "**Birkhoff** (Figure 4)**.** 976 cells are generated by 17 join-irreducibles","fig4")
sub("The rank profile runs 1 · 5 · 15",
    "The rank profile (Figure 3) runs 1 · 5 · 15","fig3")
sub("Two candidate involutions differ precisely on the three coordinates whose realised minimum is 1. Computed against the reconstructed object **[V]**:",
    "Two candidate involutions differ precisely on the three coordinates whose realised minimum is 1. Computed against the reconstructed object (Figure 5) **[V]**:","fig5")
sub("Its validity requires T monotone along every axis used",
    "Its geometry is shown in Figure 7(a). Its validity requires T monotone along every axis used","fig7a")
sub("The lattice bracket tightened the deductive interval by a factor of roughly 2 at ℓ ≤ 2 and roughly 134 at ℓ ≥ 3.",
    "The lattice bracket tightened the deductive interval by a factor of roughly 2 at ℓ ≤ 2 and roughly 134 at ℓ ≥ 3 (Figure 7b; recomputed from the recorded per-cell ratios in the compilation session as 1.90× and 134.1× respectively **[V]**).","fig7b")
sub("The mechanism is analytic and was verified independently in the compilation session **[V]**:",
    "The mechanism is analytic and was verified independently in the compilation session (Figure 8) **[V]**:","fig8")
sub("| 7f–7g | 0.800 | 0.20 | 4.01 | exits |",
    "| 7f–7g | 0.800 | 0.20 | 4.01 | exits |\n\nFigure 9 shows the exit against the bound's own ν⁻³ trend.","fig9")
sub("The book's §13.6 states that E(X) is the prediction budget.",
    "The book's §13.6 states that E(X) is the prediction budget (Figure 10).","fig10")

# --- provenance upgrade: the two EM indices were rebuilt in the compilation session ---
sub("the object is a join-semilattice, not a lattice **[S]**. Computation confirmed: 0 join failures and 768 meet failures in 15,400 pairs, deterministic **[S]**.",
    "the object is a join-semilattice, not a lattice **[S]**. Computation confirmed: 0 join failures and 768 meet failures in 15,400 pairs, deterministic — reconstructed and re-verified against the committed values in the compilation session, together with the count identity |Λ_cav| = 176 matching the direct TE+TM enumeration and the closure of the (m,n,l) core **[R]**.",
    "5.3 provenance")
sub("0 distributivity violations in 216,000 triples, E(X) = 0 **[S]**.",
    "0 distributivity violations, E(X) = 0, Sperner width 41, F(−1) = 0 **[R]**.",
    "5.4 provenance")
sub("### 5.4 The spherical cavity: a predicted success, and Λ's own cap without its factor of two\n",
    "### 5.4 The spherical cavity: a predicted success, and Λ's own cap without its factor of two\n\n*Reconstruction note.* The spherical index was not available from the original session's environment, but its stated invariants over-determine it: the requirements |Λ_sph| = 480, height 22 and 114,960 pairs admit the single construction (t, ℓ′, m′, n′) with t ≤ 1, ℓ′ ≤ 5, m′ ≤ 2ℓ′ + 2, n′ ≤ 4. Rebuilt on that basis, the object further reproduced Sperner width 41 and F(−1) = 0 — neither of which was used to locate it. All figures in this subsection are therefore recomputed **[R]** rather than recalled.\n",
    "5.4 reconstruction note")
sub("The criterion predicted the outcome from the arity of the cap alone and was right in both directions, which is what makes it a criterion rather than an observation.",
    "The criterion predicted the outcome from the arity of the cap alone and was right in both directions (Figure 6), which is what makes it a criterion rather than an observation.",
    "fig6")

# --- appendices ---
sub("[R] — reconstruction and 18/18 invariant verification; cylinder, skeleton, asymmetry, void; complete cell definition; meet-irreducible count.",
    "[R] — reconstruction and 18/18 invariant verification; cylinder, skeleton, asymmetry, void; complete cell definition; meet-irreducible count; reconstruction and 17/17 verification of Λ_cav and Λ_sph; all ten figures.")
sub("[V] — duality convention (both candidates computed); Be II r_ℓ arithmetic, ΔT–Δδ consistency, analytic direction claim; audit-grid arithmetic and budget accounting.",
    "[V] — duality convention (both candidates computed); Be II r_ℓ arithmetic, ΔT–Δδ consistency, analytic direction claim; audit-grid arithmetic and budget accounting; lattice-bracket tightening factors recomputed from recorded per-cell ratios.")
sub("[S] — EM census and declines; Maxwell analysis; Λ_cav and Λ_sph builds and counts; lattice-bracket empirical results",
    "[S] — EM census and declines; Maxwell analysis; the committed predictions preceding the Λ_cav and Λ_sph builds; lattice-bracket empirical results")

# --- list of figures, inserted before Appendix A ---
figs = """
---

## List of figures

**Figure 1.** The constraint graph of Λ is a tree: 8 nodes, 7 edges, treewidth 1. The source end (n, ℓ, k, 2S) and the target end (e, f, g) meet only at the transfer q. Three of the book's central results follow from acyclicity alone. *§2.1, §4.2.*

**Figure 2.** Λ as a cylinder over the transfer. (a) |A(q)| falls monotonically as |B(q)| rises: the source can only give away what it has, the target can only receive into what it has room for. (b) The fibre profile 165·330·345·136 peaks at q = 2 — a crossing, not a maximum of either factor. *§4.1.*

**Figure 3.** Rank profile: eighteen levels, widest 122 at rank 11, log-concave, and asymmetric — 5 against 4 one step from each end. *§4.3.*

**Figure 4.** The 17 join-irreducibles and their 20 covering relations. All 976 down-sets of this poset are precisely the 976 cells: a 57-fold compression, exact. *§4.2.*

**Figure 5.** The duality convention resolved by computation. Only σ(x) = max − x reproduces the stated count; its eight survivors are all of even rank, symmetric about rank 10, contributing +8. The range-reflection convention yields 112 survivors of mixed rank and is refuted. *§4.3.*

**Figure 6.** Cap arity decides lattice closure. (a) A single-argument cap is a tree edge and preserves meets; a multi-argument cap is a hyperedge and does not. (b) The prediction was committed before either object was built and was correct in both directions: 768 meet failures in 15,400 pairs for the rectangular cavity, zero in 114,960 for the spherical. *§5.3–5.4.*

**Figure 7.** The lattice bracket. (a) Bracketing by all lattice covers rather than along one channel. (b) Measured width ratios on Na I, Mg II, Al I and He I: mean 0.53 at ℓ ≤ 2 (1.9× tighter) and 0.0075 at ℓ ≥ 3 (134× tighter). *§7.1–7.2.*

**Figure 8.** The falsification that corrected the framework. Since T = Z²R/(n−δ)² is increasing in δ, ℓ-order is preserved exactly when δ is non-increasing. He I's crossing is a rise and inverts the order; Be II's is a fall and preserves it. A sign change is not the failure condition — a rise is. *§7.4.*

**Figure 9.** The first observed r_ℓ exit on real data, under the source compilation's own uncertainties. The bracket at the exiting cells still holds; it has become unresolvable rather than wrong. *§7.5.*

**Figure 10.** The prediction budget. E(X) = 5 with exactly five predictions outstanding; the Be II campaign resolved two — one refuted, one confirmed — and E fell to 3. The budget spent equals the cells closed, cell for cell. *§8.2.*

"""
sub("\n## Appendix A. Reproducibility", figs+"\n## Appendix A. Reproducibility","list of figures")
sub("The complete 976-cell definition, including the full 3,749-relation Hasse structure, is provided as a companion file.",
    "The complete 976-cell definition, including the full 3,749-relation Hasse structure, is provided as a companion file. Both electromagnetic indices are reproducible from the constructions stated in §5.3 and §5.4; the figure scripts regenerate all ten figures from the constructions and the recorded measurement values, with no external data.")
open('paper.md','w').write(p)
print("\nOK. bytes:",len(p))