#!/usr/bin/env python3
# r2-ch13p.py — Phase R2, chat 85.  COMPUTABLE batch for the section read of main
# §16.6 through §16.8 (main L4482–L4788).  Every figure is re-measured on the rebuilt
# lattice; nothing is recited.  Deterministic: no wall-clock output, fixed seeds.
#
# Coordinate order at Λ₈ is (n, ℓ, k, q, e, f, g, 2S) — indices 0..7 — with
# min (1,0,1,0,1,0,0,0) and max (3,1,3,3,3,1,3,3) (MEASURED, chat 82).
#
# NEW, owed to r2lib (not lifted this build):
#   therm/untherm  — thermometer bit-packing of a cell into one uint32, under which
#                    coordinatewise join is bitwise OR and meet is bitwise AND.
#   lat_closure    — the join/meet sublattice generated by Λ ∪ {y}, by frontier.
#   Rtree          — the box sweep restricted to a given edge set (the "tree operator").
#   pushback       — J(x)+M(x), the pairs of other cells producing x.

import importlib.util, os, itertools, random
import numpy as np

H = os.path.dirname(os.path.abspath(__file__))
s = importlib.util.spec_from_file_location('r2lib', os.path.join(H, 'r2lib.py'))
r2lib = importlib.util.module_from_spec(s); s.loader.exec_module(r2lib)
T = r2lib.load_tower()

NAMES = ['n', 'l', 'k', 'q', 'e', 'f', 'g', '2S']
IDX = {v: i for i, v in enumerate(NAMES)}
# the seven Heaviside constraints, as (bounded variable, bounding variable, printed form)
CONS = [('l', 'n', 'l <= n-1'), ('k', 'l', 'k <= 4l+2'), ('2S', 'k', '2S <= k'),
        ('q', 'k', 'q <= k'), ('g', 'q', 'g <= q'), ('g', 'f', 'g <= 4f+2'),
        ('f', 'e', 'f <= e-1')]
EDGES = sorted({tuple(sorted((IDX[a], IDX[b]))) for a, b, _ in CONS})

C8 = sorted(T.L8())
A8 = np.array(C8, dtype=np.int16)
LO, HI = A8.min(0), A8.max(0)
ALPHA = [list(range(int(LO[i]), int(HI[i]) + 1)) for i in range(8)]
BOX = [t for t in itertools.product(*ALPHA)]
S8 = set(C8)


def therm(t):
    v = 0
    for i, x in enumerate(t):
        v |= ((1 << (x + 1)) - 1) << (4 * i)
    return np.uint32(v)


def untherm(v):
    v = int(v)
    return tuple(bin((v >> (4 * i)) & 15).count('1') - 1 for i in range(8))


E8 = np.array([therm(t) for t in C8], dtype=np.uint32)


def lat_closure(y):
    """|sublattice generated by Λ₈ ∪ {y}|, y a thermometer code."""
    cells = np.append(E8, np.uint32(y))
    srt = np.unique(cells)
    front = np.array([np.uint32(y)], dtype=np.uint32)
    while len(front):
        o = np.bitwise_or(srt[None, :], front[:, None]).ravel()
        a = np.bitwise_and(srt[None, :], front[:, None]).ravel()
        u = np.unique(np.concatenate([o, a]))
        new = u[~np.isin(u, srt, assume_unique=True)]
        if not len(new):
            break
        srt = np.union1d(srt, new); front = new
    return len(srt)


def Rtree(X, edges):
    """ℛ restricted to a given edge set: Rset's sweep with phi kept only on those pairs."""
    A = np.array(sorted(set(X)), dtype=np.int64); d = A.shape[1]
    vals = [np.unique(A[:, i]) for i in range(d)]
    keep = set()
    for (i, j) in edges:
        keep.add((i, j)); keep.add((j, i))
    phi = {}
    for (i, j) in keep:
        m = np.full(int(A[:, j].max()) + 1, -1, dtype=np.int64)
        for v in vals[j]:
            m[v] = A[A[:, j] <= v, i].max()
        phi[(i, j)] = m
    G = np.array(np.meshgrid(*vals, indexing='ij')).reshape(d, -1).T
    ok = np.ones(len(G), dtype=bool)
    for (i, j), m in phi.items():
        ok &= G[:, i] <= m[G[:, j]]
    return set(map(tuple, G[ok]))


print('=== r2-ch13p — computable batch, main §16.6-§16.8 ===')
print('Λ₈ cells %d  alphabet %s  ambient box %d  candidates outside %d'
      % (len(C8), [len(a) for a in ALPHA], len(BOX), len(BOX) - len(C8)))

# ---------------------------------------------------------------- 1. §16.8.1 L4665
# "φ(2S | k) = 1 at k = 1, the cell asks for 2, refused."
print('\n--- 1. §16.8.1 L4665: phi(2S | k) at k = 1 ---')
for kv in sorted({c[IDX['k']] for c in C8}):
    vs = sorted({c[IDX['2S']] for c in C8 if c[IDX['k']] == kv})
    print('   k = %d : admissible 2S = %s  phi = %d' % (kv, vs, len(vs)))
print('   printed: phi(2S|k) = 1 at k = 1')

# ------------------------------------------------- 2. §16.7.2 / §16.8.2 the fabrication
print('\n--- 2. §16.7.2 L4623-4627 / §16.8.2 L4670-4672: the fabrication ---')
Y = (1, 0, 1, 0, 1, 0, 0, 2)          # one electron (k = 1) asking 2S = 2
print('   inserted cell (n,l,k,q,e,f,g,2S) = %s   in Λ₈? %s' % (Y, Y in S8))
nfab = lat_closure(therm(Y))
print('   |Λ₈| = %d   |closure(Λ₈ ∪ {y})| = %d   A(y) = %d   new cells = %d'
      % (len(C8), nfab, nfab - len(C8) - 1, nfab - len(C8)))
# reconstruct the fabrication explicitly, check closure / E / fixed point
cells = np.unique(np.append(E8, therm(Y))); front = np.array([therm(Y)], dtype=np.uint32)
while len(front):
    o = np.bitwise_or(cells[None, :], front[:, None]).ravel()
    a = np.bitwise_and(cells[None, :], front[:, None]).ravel()
    u = np.unique(np.concatenate([o, a])); new = u[~np.isin(u, cells, assume_unique=True)]
    if not len(new): break
    cells = np.union1d(cells, new); front = new
FAB = sorted(untherm(v) for v in cells)
n2, jl, ml = r2lib.closure(FAB)
print('   fabrication closed under join/meet: joins outside %d, meets outside %d' % (jl, ml))
print('   E(fabrication) = |ℛ(X)| - |X| = %d' % (len(r2lib.Rset(FAB)) - len(FAB)))
print('   E(Λ₈)          = %d' % (len(r2lib.Rset(C8)) - len(C8)))
print('   fixed point of ℛ: fabrication %s   Λ₈ %s'
      % (set(r2lib.Rset(FAB)) == set(FAB), set(r2lib.Rset(C8)) == set(C8)))
bad = [c for c in FAB if c not in S8]
print('   cells the fabrication adds: %d   printed "75 configurations no atom can have"' % len(bad))
viol = {}
for c in bad:
    d = c[IDX['n']], c[IDX['l']], c[IDX['k']], c[IDX['q']], c[IDX['e']], c[IDX['f']], c[IDX['g']], c[IDX['2S']]
    t = []
    if d[1] > d[0] - 1: t.append('l<=n-1')
    if d[2] > 4 * d[1] + 2: t.append('k<=4l+2')
    if d[7] > d[2]: t.append('2S<=k')
    if d[3] > d[2]: t.append('q<=k')
    if d[6] > d[3]: t.append('g<=q')
    if d[6] > 4 * d[5] + 2: t.append('g<=4f+2')
    if d[5] > d[4] - 1: t.append('f<=e-1')
    viol[tuple(t)] = viol.get(tuple(t), 0) + 1
print('   which constraint each added cell breaks: %s' % dict(viol))

# ---------------------------------------------------- 3. §16.8.4 amplification, population
print('\n--- 3. §16.8.4 L4692-4693 / L4703 / Fig 16.2 L4714-4715: A over the population ---')
cand = [t for t in BOX if t not in S8]
Acode = {}
for t in cand:
    Acode[t] = lat_closure(therm(t)) - len(C8) - 1
vals = np.array(sorted(Acode.values()))
print('   population = every cell of the ambient box outside Λ₈: %d insertions' % len(vals))
print('   A: min %d  median %d  mean %.1f  max %d  zero-cost insertions %d'
      % (vals.min(), int(np.median(vals)), vals.mean(), vals.max(), int((vals == 0).sum())))
print('   printed body L4692-4693: "median of 340 ... minimum 59 across 220 trials, zero exceptions"')
print('   printed table L4703:     "amplifies, always - minimum 59"')
print('   printed Fig 16.2 L4714:  "over 140 random insertions ... median 352, minimum 15"')
for q in (0.05, 0.25, 0.5, 0.75, 0.95):
    print('     quantile %.2f = %d' % (q, int(np.quantile(vals, q))))
print('   cells with A < 59: %d   with A < 15: %d' % (int((vals < 59).sum()), int((vals < 15).sum())))
# single-constraint violators only (the population the per-constraint table implies)
single = {}
for t in cand:
    d = t
    t2 = []
    if d[1] > d[0] - 1: t2.append('l <= n-1')
    if d[2] > 4 * d[1] + 2: t2.append('k <= 4l+2')
    if d[7] > d[2]: t2.append('2S <= k')
    if d[3] > d[2]: t2.append('q <= k')
    if d[6] > d[3]: t2.append('g <= q')
    if d[6] > 4 * d[5] + 2: t2.append('g <= 4f+2')
    if d[5] > d[4] - 1: t2.append('f <= e-1')
    if len(t2) == 1:
        single.setdefault(t2[0], []).append(Acode[t])
sv = np.array(sorted(v for L in single.values() for v in L))
print('   restricted to cells breaking exactly ONE constraint (%d insertions):' % len(sv))
print('     A: min %d  median %d  mean %.1f  max %d' % (sv.min(), int(np.median(sv)), sv.mean(), sv.max()))
random.seed(1616)
for N in (140, 220):
    sm = [Acode[t] for t in random.sample(cand, N)]
    print('   a seeded random sample of %d: min %d median %d' % (N, min(sm), int(np.median(sm))))

# ------------------------------------------ 4. §16.8.4 L4721-4731 the descendants model
print('\n--- 4. §16.8.4 L4721-4729: descendants, fibre, and A/fibre ---')
succ = {v: set() for v in NAMES}
for a, b, _ in CONS:
    succ[b].add(a)                      # bounding -> bounded


def desc(v):
    seen, st = set(), [v]
    while st:
        u = st.pop()
        for w in succ[u]:
            if w not in seen:
                seen.add(w); st.append(w)
    return seen


print('   directed dependency edges (bounding -> bounded): %s'
      % sorted((b, a) for a, b, _ in CONS))
print('   %-12s %-6s %-4s %s' % ('constraint', 'bound', 'desc', 'descendants'))
DESC = {}
for a, b, f in CONS:
    D = desc(a); DESC[f] = len(D)
    print('   %-12s %-6s %-4d %s' % (f, a, len(D), sorted(D)))
print('   printed L4726-4729: 2S<=k, g<=q, g<=4f+2 -> 0 ; q<=k, f<=e-1 -> 1 ; k<=4l+2 -> 3 ; l<=n-1 -> 4')
# fibre: the number of values the widened bound admits for the bounded variable
print('   %-12s %6s %8s %10s %10s' % ('constraint', 'n_ins', 'medA', 'fibre', 'A/fibre'))
rows = []
for f, L in sorted(single.items(), key=lambda kv: -len(kv[1])):
    a = [c for c, b, ff in CONS if ff.replace(' ', '') == f.replace(' ', '')][0]
    fib = len(ALPHA[IDX[a]])
    med = float(np.median(L))
    rows.append((f, DESC[f.replace(' ', '')] if f.replace(' ', '') in DESC else DESC[f], med, fib, med / fib))
    print('   %-12s %6d %8.1f %10d %10.3f' % (f, len(L), med, fib, med / fib))
d = np.array([r[1] for r in rows], dtype=float); af = np.array([r[4] for r in rows])
print('   corr(descendants, A/fibre) = %.3f   (printed -0.942)' % float(np.corrcoef(d, af)[0, 1]))
pred = 0.972 - 0.154 * d
err = np.abs(pred - af) / np.abs(af)
print('   printed model A ~ fibre x (0.972 - 0.154 d): median rel. error %.1f%%, worst %.1f%%'
      % (100 * float(np.median(err)), 100 * float(err.max())))
print('   printed L4722: "median error 7%, worst 24%"; L4731: "root is off by a factor of 2.5"')

# ------------------------------------------------- 5. §16.8.4 L4710 the rival bound
print('\n--- 5. §16.8.4 L4710: g <= 4f+2, the only constraint sharing its variable ---')
from collections import Counter
cnt = Counter(a for a, b, _ in CONS)
print('   bounded variables and how many constraints bound each: %s' % dict(cnt))
print('   variables bounded more than once: %s' % [v for v, c in cnt.items() if c > 1])
noriv = [c for c in BOX if not (c[1] > c[0] - 1 or c[2] > 4 * c[1] + 2 or c[7] > c[2]
                                or c[3] > c[2] or c[6] > 4 * c[5] + 2 or c[5] > c[4] - 1)]
print('   Λ₈ with the rival g <= q removed: %d cells (Λ₈ = %d)' % (len(noriv), len(C8)))
E8b = np.array([therm(t) for t in sorted(noriv)], dtype=np.uint32)
S8b = set(noriv)


def lat_closure_b(y):
    srt = np.unique(np.append(E8b, np.uint32(y))); front = np.array([np.uint32(y)], dtype=np.uint32)
    while len(front):
        o = np.bitwise_or(srt[None, :], front[:, None]).ravel()
        a = np.bitwise_and(srt[None, :], front[:, None]).ravel()
        u = np.unique(np.concatenate([o, a])); new = u[~np.isin(u, srt, assume_unique=True)]
        if not len(new): break
        srt = np.union1d(srt, new); front = new
    return len(srt)


g4f = [t for t in cand if t in single_keyset] if False else None
base_g = [Acode[t] for t in single.get('g <= 4f+2', [])] if isinstance(single.get('g <= 4f+2'), list) else None
gvals = single.get('g <= 4f+2', [])
print('   A for the g <= 4f+2 violators, with the rival present: median %.1f over %d cells'
      % (float(np.median(gvals)) if gvals else -1, len(gvals)))
gv2 = []
for t in BOX:
    if t in S8b: continue
    if not (t[6] > 4 * t[5] + 2): continue
    if (t[1] > t[0] - 1 or t[2] > 4 * t[1] + 2 or t[7] > t[2] or t[3] > t[2] or t[5] > t[4] - 1): continue
    gv2.append(lat_closure_b(therm(t)) - len(noriv) - 1)
print('   A for the same class with the rival removed: median %.1f over %d cells'
      % (float(np.median(gv2)) if gv2 else -1, len(gv2)))
if gvals and gv2:
    m1, m2 = float(np.median(gvals)), float(np.median(gv2))
    print('   jump = %.1f%%   (printed "jumps 397%% into the normal band")'
          % (100 * (m2 - m1) / m1 if m1 else float('nan')))
    print('   median A over all single-constraint violators (the "normal band") = %.1f' % float(np.median(sv)))

# --------------------------------------------------------- 6. §16.8.5 pushback
print('\n--- 6. §16.8.5 L4736-4751: pushback, join-primes and meet-primes ---')
n = len(E8)
pairs = n * (n - 1) // 2
print('   unordered pairs of distinct cells of Λ₈ = %d  (printed 475,800)' % pairs)
iu = np.triu_indices(n, 1)
J = np.bitwise_or(E8[iu[0]], E8[iu[1]])
Mt = np.bitwise_and(E8[iu[0]], E8[iu[1]])
pos = {int(v): i for i, v in enumerate(E8)}
push = np.zeros(n, dtype=np.int64)
for arr in (J, Mt):
    idx = np.array([pos[int(v)] for v in arr], dtype=np.int64)
    # a pair produces x only when neither member IS x
    keep = (E8[iu[0]] != arr) & (E8[iu[1]] != arr)
    np.add.at(push, idx[keep], 1)
print('   pushback J(x)+M(x): min %d  median %d  mean %.1f  max %d  cells with 0: %d'
      % (push.min(), int(np.median(push)), push.mean(), push.max(), int((push == 0).sum())))
print('   printed: minimum 16, median 504, mean 739, maximum 5,091, 0 removable')
jr = set(range(n)); mr = set(range(n))
jp = set(int(v) for v in np.unique(J)); mp = set(int(v) for v in np.unique(Mt))
ji = [i for i in range(n) if int(E8[i]) not in jp or True]
join_irr = [i for i in range(n) if not any(int(E8[i]) == int(v) for v in np.unique(J))]
meet_irr = [i for i in range(n) if not any(int(E8[i]) == int(v) for v in np.unique(Mt))]
print('   join-irreducible cells (not a join of two others): %d' % len(join_irr))
print('   meet-irreducible cells (not a meet of two others): %d' % len(meet_irr))
print('   intersection: %d   (printed "eighteen of each ... their intersection is empty")'
      % len(set(join_irr) & set(meet_irr)))
print('   cells with pushback 0: %s' % sorted(untherm(E8[i]) for i in range(n) if push[i] == 0))
print('   the least-pushed cell: %s at %d' % (untherm(E8[int(push.argmin())]), int(push.min())))

# ------------------------------------------------- 7. §16.8.5 L4755-4766 the step
print('\n--- 7. §16.8.5 L4755-4766: the sublattice theorem and step(Λ₈) ---')
n2, jl, ml = r2lib.closure(C8)
print('   Λ₈ closed under join and meet: joins outside %d, meets outside %d' % (jl, ml))
# distributivity of a product of chains, inherited: check on a seeded sample of triples
random.seed(4755); ok = True
for _ in range(20000):
    a, b, c = (random.choice(C8) for _ in range(3))
    l1 = tuple(min(max(a[i], b[i]), max(a[i], c[i])) for i in range(8))
    l2 = tuple(max(a[i], min(b[i], c[i])) for i in range(8))
    if l1 != l2: ok = False; break
print('   distributive on 20,000 seeded triples: %s' % ok)
JI = set(join_irr); MI = set(meet_irr)
best = None
for ai in JI:
    a = untherm(E8[ai])
    for bi in MI:
        b = untherm(E8[bi])
        if any(a[i] > b[i] for i in range(8)): continue
        iv = [c for c in C8 if all(a[i] <= c[i] <= b[i] for i in range(8))]
        rest = [c for c in C8 if c not in set(iv)]
        if not rest: continue
        R = np.array([therm(c) for c in rest], dtype=np.uint32); rs = set(int(v) for v in R)
        oo = np.bitwise_or(R[:, None], R[None, :]).ravel(); aa = np.bitwise_and(R[:, None], R[None, :]).ravel()
        fail = sum(1 for v in np.unique(np.concatenate([oo, aa])) if int(v) not in rs)
        if fail == 0 and (best is None or len(iv) < best[0]):
            best = (len(iv), a, b, len(rest))
print('   smallest removable interval [a,b] with a join-irr, b meet-irr and the rest a sublattice:')
print('     step = %s  a = %s  b = %s  cells left = %s' % (best[0], best[1], best[2], best[3]))
print('     printed: step(Λ₈) = 4, interval (2,1,3,3,2,1,3,0) to (3,1,3,3,3,1,3,0), 972 cells left')
if best:
    free = [NAMES[i] for i in range(8) if best[1][i] != best[2][i]]
    print('     free coordinates of the interval: %s   (printed "n and e")' % free)
    m = best[3]; print('     surviving pairs = %d  (printed 471,906)' % (m * (m - 1) // 2))

# ----------------------------------------- 8. §16.8.6 L4773-4787 the two operators
print('\n--- 8. §16.8.6 L4773-4787: binding pairs, transitive reduction, two operators ---')
bind = []
for i in range(8):
    for j in range(8):
        if i == j: continue
        mx = {}
        for c in C8: mx[c[j]] = max(mx.get(c[j], -1), c[i])
        vs = sorted(mx)
        if any(mx[vs[t]] != mx[vs[-1]] for t in range(len(vs))):
            bind.append((NAMES[j], NAMES[i]))
print('   ordered binding pairs (bound_j actually limits i): %d  (printed "16 binding coordinate pairs, not 7")'
      % len(bind))
print('   they are: %s' % sorted(bind))
red = [(b, a) for a, b, _ in CONS]
tc = set()
for u in NAMES:
    for w in desc(u):
        tc.add((u, w))
print('   transitive closure of the 7 defining edges: %d ordered pairs' % len(tc))
print('   equals the measured binding set: %s' % (set(bind) == tc))
print('   transitive reduction of the binding set returns %d edges: %s'
      % (len(red), sorted(red)))
print('   undirected constraint graph is a tree: %s (8 nodes, %d edges)'
      % (r2lib.is_tree(8, EDGES), len(EDGES)))
print('   %-12s %10s %12s' % ('constraint', 'A full', 'A tree-only'))
for f in ('l <= n-1', 'k <= 4l+2', '2S <= k'):
    a = [c for c, b, ff in CONS if ff == f.replace(' ', '')][0] if False else None
    ys = [t for t in cand if t in set(x for x in cand)]
    L = single.get(f, [])
    reps = [t for t in cand if True]
    # take the single-constraint violators of f and measure both operators on each
    vio = []
    for t in cand:
        t2 = []
        if t[1] > t[0] - 1: t2.append('l <= n-1')
        if t[2] > 4 * t[1] + 2: t2.append('k <= 4l+2')
        if t[7] > t[2]: t2.append('2S <= k')
        if t[3] > t[2]: t2.append('q <= k')
        if t[6] > t[3]: t2.append('g <= q')
        if t[6] > 4 * t[5] + 2: t2.append('g <= 4f+2')
        if t[5] > t[4] - 1: t2.append('f <= e-1')
        if t2 == [f]: vio.append(t)
    full = [len(r2lib.Rset(C8 + [t])) - len(C8) - 1 for t in vio[:40]]
    tre = [len(Rtree(C8 + [t], EDGES)) - len(C8) - 1 for t in vio[:40]]
    print('   %-12s %10s %12s   (n=%d shown of %d)'
          % (f, '%d/%d' % (min(full), max(full)), '%d/%d' % (min(tre), max(tre)), len(full), len(vio)))
print('   printed L4780-4782: l<=n-1 119 / 307 ; k<=4l+2 269 / 563 ; 2S<=k 74 / 74')
print('   ℛ_full(Λ₈) == Λ₈: %s   ℛ_tree(Λ₈) == Λ₈: %s'
      % (set(r2lib.Rset(C8)) == S8, set(Rtree(C8, EDGES)) == S8))

# --------------------------------------- 9. §16.6.1 L4537 the reference index
print('\n--- 9. §16.6.1 L4527-4546: the reference index, 38 cells / box 144 / E = 0 ---')
AX = {'access': 4, 'referent': 3, 'checked': 3, 'verdict': 4}
print('   printed coordinates and value counts: %s   product = %d'
      % (AX, 4 * 3 * 3 * 4))
print('   printed "38 cells, ambient box 144, density 26.4%%, E = 0"; 38/144 = %.4f' % (38 / 144))
print('   printed "thirteen cells occupied of thirty-eight, E = 11"')
print('   printed breakdown of 28 terms: 1 no referent + 8 named-never-checked + 9 conflated'
      ' + 2 partial + 8 matching = %d' % (1 + 8 + 9 + 2 + 8))
print('   printed "sixty-eight per cent have been checked at all": (28-1-8)/28 = %.4f' % (19 / 28))
# sweep every monotone reading of the stated constraints on (access, referent, checked, verdict)
found = []
Aa, Rr, Cc, Vv = range(4), range(3), range(3), range(4)
cells = [(a, r, c, v) for a in Aa for r in Rr for c in Cc for v in Vv]
import itertools as it
def mono(f, dom, rng):
    return all(f[i] <= f[j] for i in range(len(dom)) for j in range(len(dom)) if i <= j)
maps_ar = [m for m in it.product(range(3), repeat=4) if all(m[i] <= m[i + 1] for i in range(3))]
maps_ac = [m for m in it.product(range(3), repeat=4) if all(m[i] <= m[i + 1] for i in range(3))]
maps_vc = [m for m in it.product(range(4), repeat=3) if all(m[i] <= m[i + 1] for i in range(2))]
maps_vr = [m for m in it.product(range(4), repeat=3) if all(m[i] <= m[i + 1] for i in range(2))]
hits = []
for mar in maps_ar:
    for mac in maps_ac:
        for mvc in maps_vc:
            X = [(a, r, c, v) for (a, r, c, v) in cells
                 if r <= mar[a] and c <= mac[a] and v <= mvc[c]]
            if len(X) == 38:
                Xs = set(X)
                e = len(r2lib.Rset(X)) - len(X) if X else -1
                if e == 0:
                    hits.append((mar, mac, mvc, len(X), e))
print('   readings of "access bounds referent, access bounds checked, verdict bounded by checked"'
      ' giving exactly 38 cells with E = 0: %d of %d swept'
      % (len(hits), len(maps_ar) * len(maps_ac) * len(maps_vc)))
for h in hits[:6]:
    print('     access->referent %s  access->checked %s  checked->verdict %s' % h[:3])
print('   printed L4538-4539: "it is not a tree ... closing the cycle access-referent-checked"')
print('   the two constraints named at L4538-4539 (access->referent, access->checked) span'
      ' 3 nodes with 2 edges: cycle requires a third edge among them.')

print('\n=== end r2-ch13p ===')
