import eldata as ed, itertools
CAP={0:2,1:6,2:10,3:14,4:18}
def leq(x,y): return all(p<=q for p,q in zip(x,y))
def group_at(Zmax):
    occ=set(ed.E[z] for z in ed.E if z<=Zmax)
    def test(perm):
        pos={perm[i]:i+1 for i in range(7)}
        Lx=[(i+1,l,k) for i in range(7) for l in range(0,min(i+1,5)) for k in range(1,CAP[l]+1)]
        Ox=set()
        for (n,l,k) in occ:
            i=pos[n]
            if l>i-1: return False
            Ox.add((i,l,k))
        return not any(leq(y,x) and y not in Ox for x in Ox for y in Lx)
    return [p for p in itertools.permutations(range(1,8)) if test(p)]

print("="*76); print("STEP 8: GROUP ORDER AS A FUNCTION OF TRUNCATION"); print("="*76)
print(f"  {'Zmax':>6} {'|G|':>5}  generators")
for Z in [54,86,102,112,118]:
    g=group_at(Z)
    gens=set()
    for p in g:
        pos={p[i]:i+1 for i in range(7)}
        for s in range(1,8):
            if pos[s]!=s and s<pos[s]: gens.add((s,pos[s]))
    print(f"  {Z:>6} {len(g):>5}  {sorted(gens)}")
print()
print("""  The group is generated by transpositions of shells with IDENTICAL
  occupied (ℓ,k) profiles. Such shells are literally indistinguishable
  to any test that looks only at the occupied set, so the 'reflection'
  is a statement that the periodic system does not distinguish them.""")
print()
print("="*76); print("STEP 9: IS THIS A SYMMETRY OF Λ OR OF THE OCCUPIED SET?"); print("="*76)
occ=set(ed.E[z] for z in ed.E)
# does the swap (2,7) preserve Lambda itself?
Lx=[(n,l,k) for n in range(1,8) for l in range(0,min(n,5)) for k in range(1,CAP[l]+1)]
S=set(Lx)
sw={2:7,7:2}
img=set((sw.get(n,n),l,k) for (n,l,k) in Lx)
print(f"  |Λ| = {len(S)},  |swap(Λ)| = {len(img)},  equal? {img==S}")
bad=[c for c in img if c not in S]
print(f"  cells sent outside Λ: {len(bad)}  e.g. {sorted(bad)[:4]}")
print()
print("""  The swap does NOT preserve Λ: it maps admissible cells at n=7 (which
  allow ℓ up to 4) onto n=2 (which allows only ℓ ≤ 1). So this is not a
  symmetry of the lattice. It is a symmetry only of the OCCUPIED SUBSET,
  and only because that subset happens not to use the extra columns at
  n=5,6,7.""")