B.push(h3('11.3  Chemical groups as fibres of the lattice'));
B.push(p([t('The Janet correspondence of Section 11.2 concerns the projection of Λ along n + ℓ. A second and independent relationship emerges from a different operation on the same lattice: fixing the pair (ℓ, k) and allowing n to vary.')]));
B.push(p([t('Each such fibre is a line through Λ parallel to the n-axis, and the elements lying on it are precisely a conventional chemical group. Fixing (ℓ, k) = (0, 1) gives hydrogen, lithium, sodium, potassium, rubidium, caesium and francium; (1, 4) gives oxygen, sulphur, selenium, tellurium, polonium and livermorium; and so on across the main groups. The columns of the two-dimensional table are one-dimensional fibres of the three-dimensional lattice, and the periodicity that the conventional layout represents by adjacency of columns is here a statement about parallel lines.')]));
B.push(img('fig11_fibres.png', 640, 211));
B.push(cap(11, 'Fibres, the lattice boundary, and parity. (a) Fixing (ℓ, k) and varying n traces a fibre of Λ; each fibre is a conventional chemical group. The fibre (ℓ, k) = (0, 2) contains helium alongside beryllium and the alkaline earths rather than the noble gases. (b) The kainosymmetric subshells 1s, 2p, 3d, 4f and 5g occupy the diagonal ℓ = n − 1, the boundary at which the constraint ℓ ≤ n − 1 is tight. (c) Parity balance: Λ divides evenly between cells of even and odd rank, and the occupied set inherits the division, a consequence of every column capacity being even.'));
B.push(p([t('Seven of the eight main groups are reproduced exactly. The single departure is instructive. Helium has valence configuration 1s², placing it at (1, 0, 2) and hence on the fibre (ℓ, k) = (0, 2) together with beryllium, magnesium, calcium and the remaining alkaline earths — not on the fibre (1, 6) occupied by neon, argon and the other noble gases. The lattice separates helium from the group with which the conventional table places it.')]));
B.push(p([t('This is exactly the placement that the Janet left-step table adopts, and Section 11.2 obtained it by a different route: as a consequence of projecting along n + ℓ. That two independent operations on Λ — projection along a linear functional, and fibration along the n-axis — converge on the same contested placement is a point in favour of the arrangement, though the question of whether helium is better classified by electron configuration or by chemical behaviour is one on which the philosophy-of-chemistry literature remains divided, and nothing here settles it.')]));

B.push(h3('11.4  The lattice boundary and kainosymmetry'));
B.push(p([t('A further correspondence concerns the diagonal ℓ = n − 1, where the angular-momentum constraint is tight. The cells on this diagonal are 1s, 2p, 3d, 4f and 5g: the subshells that are first of their kind, possessing no radial node.')]));
B.push(p([t('These subshells are anomalous in well-documented ways. The phenomenon is known as kainosymmetry or primogenic repulsion: a first-of-kind subshell is unusually compact, is not screened by an inner subshell of the same ℓ, and produces the irregularities of the first short period, the anomalous properties of the 3d series relative to 4d and 5d, and part of the divergence of the lanthanides from the actinides. In the conventional table these anomalies appear as scattered exceptions distributed across the layout.')]));
B.push(p([t('In Λ they are the boundary. The kainosymmetric subshells are exactly the cells where ℓ attains its maximum permitted value for the given n, and their anomalous character corresponds to their lying on the surface of the admissible region rather than in its interior. This is a structural observation rather than an explanation — the lattice does not say why a first-of-kind subshell should be compact — but it does locate a known family of chemical anomalies at a single identifiable feature of the geometry.')]));
