B.push(h2('14.  Relation to Existing Work'));
B.push(p([t('Alternative periodic arrangements have a long history — helical, cylindrical, pyramidal and left-step forms among them. These generally reorganise by atomic number and chemical periodicity while preserving a two-dimensional surface. The present construction differs in treating the three quantum numbers as independent geometric axes and, more importantly, in classifying the resulting empty volume into physically distinguished regimes. The mathematical ingredients — bra-ket notation, superposition, the Pauli principle — are entirely standard; what is offered here is a coordinate choice and the structural facts it reveals.')]));

B.push(h3('14.1  Order-theoretic treatments of chemical systems'));
B.push(p([t('Order theory has an established presence in chemistry, and two lines of work stand close enough to the present one to require explicit comparison.')]));
B.push(p([t('Leal and Restrepo have developed a formal account of the periodic system as an ordered hypergraph, in which the elements are vertices, chemical similarity classes are hyperedges, and the order relation is induced by measured properties such as atomic number or electronegativity. Their construction and the present one order different objects by different relations: theirs orders elements by properties, the present work orders electron configurations by componentwise comparison of quantum numbers. The two are complementary rather than competing, and a remark of Restrepo\'s is worth recording — that the several periodic tables in circulation may be understood as projections of a single underlying structure. Section 11.2 arrives at a particular instance of that idea from the opposite direction, obtaining the Janet arrangement as the projection of Λ along n + ℓ.')]));
B.push(p([t('Quintero, Brüggemann and Restrepo have separately introduced what they term posetic coordinates, assigning to each object of a poset the triple of cardinalities of its up-set, its down-set and its incomparable set, and mapping those triples into ternary and FOU plots for visualisation. Despite the superficial similarity of vocabulary, the notion of dimension employed there is not the order dimension of Section 10.1: their mappings are visualisation devices reducing a Hasse diagram to a readable plot, whereas order dimension is an intrinsic invariant counting the linear orders needed to reconstruct the relation. Their coordinates describe an object\'s position within a given poset; the coordinates of the present work define the poset. The two notions are independent, and the results of Section 10.1 neither follow from nor conflict with theirs.')]));
B.push(p([t('Their machinery is nonetheless applicable to Λ and would answer a question this paper does not address: where the 118 occupied cells sit within the lattice as characterised by their up-set, down-set and incomparability profiles. That is a natural continuation and is noted here as such.')]));

B.push(h3('14.2  A note on novelty'));
B.push(p([t('The order-theoretic results of Part II use standard techniques throughout: the sublattice argument of Section 12 is elementary, the Sperner property is established by Dilworth\'s theorem, Birkhoff\'s representation theorem is invoked as stated, and the dimension argument of Section 10.1 applies the standard example in the textbook manner. What is claimed is the application of these techniques to the configuration lattice, not the techniques themselves.')]));
B.push(p([t('Whether the particular results are new to the literature has not been established. A limited search located the works discussed above and no closer prior art, but dimension theory alone is the subject of a substantial monograph literature, and the possibility that componentwise-ordered configuration posets have been treated elsewhere cannot be excluded on the evidence gathered here. The results are offered as correct and checkable rather than as novel, and readers in a position to identify precedent are encouraged to do so.')]));
