import random
from itertools import product, permutations, combinations
random.seed(641)
print("="*88)
print("  THE EXACT FORMULATION AT BINARY ALPHABETS")
print("="*88)
print("""
  For binary axes a relabelling is a FLIP VECTOR s ∈ {0,1}^d. Under s, the
  join becomes: **max where s_i = 0, min where s_i = 1.** So:

     X reorderable  ⟺  ∃ s such that for every pair x,y ∈ X, the corner
                        selected by s, and its complement, both lie in X

  **Each absent corner of each pair forbids one assignment of s on the axes
  where x,y differ — a SAT CLAUSE of width |I|.**

  > **Binary-alphabet reorderability ≡ SAT over d variables with clauses
  > generated by the cell set.** Verify.
""")
def sublat_flip(S,d,s):
    Ss=set(S)
    for x,y in combinations(sorted(S),2):
        j=tuple((min if s[i] else max)(x[i],y[i]) for i in range(d))
        m=tuple((max if s[i] else min)(x[i],y[i]) for i in range(d))
        if j not in Ss or m not in Ss: return False
    return True
def reord_flip(S,d):
    for s in product([0,1],repeat=d):
        if sublat_flip(S,d,s): return True,s
    return False,None
def reord_relab(S,d):
    for ps in product(*[list(permutations(range(2)))]*d):
        T={tuple(ps[k][x[k]] for k in range(d)) for x in S}
        Ts=set(T); ok=True
        for x,y in combinations(sorted(T),2):
            if tuple(max(x[i],y[i]) for i in range(d)) not in Ts: ok=False; break
            if tuple(min(x[i],y[i]) for i in range(d)) not in Ts: ok=False; break
        if ok: return True
    return False
print("  VERIFY the flip formulation equals the relabelling definition\n")
n=ag=0
for _ in range(600):
    d=random.choice([3,4,5])
    cells=list(product(*[range(2)]*d))
    S=set(random.sample(cells,random.randint(3,min(len(cells),9))))
    if any(len({x[k] for x in S})<2 for k in range(d)): continue
    a,_=reord_flip(S,d); b=reord_relab(S,d)
    n+=1; ag+= (a==b)
print("     %d instances    flip == relabelling : %d  (%.1f%%)"%(n,ag,100*ag/max(n,1)))
print("="*88)
print("  AND THE CLAUSE STRUCTURE")
print("="*88)
def clauses(S,d):
    Ss=set(S); out=[]
    for x,y in combinations(sorted(S),2):
        I=[i for i in range(d) if x[i]!=y[i]]
        if not I: continue
        for bits in product([0,1],repeat=len(I)):
            j=list(x); m=list(x)
            for t,i in enumerate(I):
                if bits[t]: j[i]=min(x[i],y[i]); m[i]=max(x[i],y[i])
                else:       j[i]=max(x[i],y[i]); m[i]=min(x[i],y[i])
            if tuple(j) not in Ss or tuple(m) not in Ss:
                out.append(tuple((I[t],bits[t]) for t in range(len(I))))
    return out
print("\n  %6s%10s%14s%14s%14s"%("d","|X|","clauses","distinct","max width"))
print("  "+"-"*60)
for d in (3,4,5):
    for _ in range(1):
        cells=list(product(*[range(2)]*d))
        S=set(random.sample(cells,min(len(cells),8)))
        cl=clauses(S,d); dc=set(cl)
        print("  %6d%10d%14d%14d%14d"%(d,len(S),len(cl),len(dc),max((len(c) for c in cl),default=0)))
print("="*88)
print("  IS THIS CLOSABLE?")
print("="*88)
print("""
  **The formulation is exact:** binary reorderability is SAT over d variables
  with clauses generated by the cell set, of width up to d.

  **To close 'is it polynomial in |X| and d' needs one of:**

     (a) a polynomial algorithm             — not found; 22 formulations
     (b) a reduction FROM a hard problem    — **the clauses are generated by
                                              a cell set, not chosen freely**

  **And (b) is exactly what failed twice.** A cell set cannot produce an
  arbitrary CNF: **clauses sharing variables share corners**, so removing a
  corner for one clause alters another. **That is a structural obstruction to
  the reduction, measured twice, and it cuts BOTH ways** — it blocks the
  hardness proof and it suggests the instances are special.

  > **So the question is NOT closable with what is established.** It needs
  > either an algorithm or a reduction, and the reduction is blocked by a
  > property of the encoding rather than by a failure of effort.
""")