#!/usr/bin/env python3
"""seal.py N -- build MANIFEST-HANDOFF-N.txt and verify N.sh from ONE source.

WHY THIS EXISTS.  s57 rebuilt the manifest three times and re-tarred twice, all from
two self-inflicted faults:
  (a) `sed 's/56/57/g' verify56.sh` silently rewrote sha256sum -> sha257sum;
  (b) the manifest wrote paths as './x' while verify's find emitted 'x', so every
      file read as both missing and extra.
Both are the same fault: the seal was produced by editing text instead of by running
one program.  This is that program.  Do not hand-edit a verify script again.

Half one : every manifest line still hashes.
Half two : COMPLETENESS -- nothing in the tree is absent from the manifest (F43.1).

Usage:  python3 pack57/seal.py 58        # writes MANIFEST-HANDOFF-58.txt + verify58.sh
        python3 pack57/seal.py 58 --check   # verify only, write nothing
"""
import hashlib, os, subprocess, sys

SKIP_DIRS = {"rt", "__pycache__", "receipts", ".git"}

def tree(root="."):
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in sorted(files):
            yield os.path.relpath(os.path.join(dirpath, f), root)

def build(N):
    man, ver = f"MANIFEST-HANDOFF-{N}.txt", f"verify{N}.sh"
    lines = []
    for p in tree():
        if p in (man, ver):
            continue
        with open(p, "rb") as fh:
            lines.append(f"{hashlib.sha256(fh.read()).hexdigest()}  {p}")
    open(man, "w").write("\n".join(sorted(lines)) + "\n")
    open(ver, "w").write(f'''#!/bin/bash
# verify{N}.sh -- GENERATED BY pack57/seal.py.  DO NOT HAND-EDIT.  Both halves (F43.1).
cd "$(dirname "$0")"
exec python3 pack57/seal.py {N} --check
''')
    os.chmod(ver, 0o755)
    return len(lines)

def check(N):
    man, ver = f"MANIFEST-HANDOFF-{N}.txt", f"verify{N}.sh"
    listed, ok, bad = set(), 0, 0
    for line in open(man):
        h, p = line.rstrip("\n").split("  ", 1)
        listed.add(p)
        if not os.path.isfile(p):
            print(f"MISSING {p}"); bad += 1; continue
        with open(p, "rb") as fh:
            if hashlib.sha256(fh.read()).hexdigest() == h: ok += 1
            else: print(f"HASH {p}"); bad += 1
    extra = [p for p in tree() if p not in listed and p not in (man, ver)]
    for p in extra[:20]:
        print(f"EXTRA {p}")
    print(f"HANDOFF-{N}: ok={ok} bad={bad} extra={len(extra)}")
    return 0 if (bad == 0 and not extra) else 1

if __name__ == "__main__":
    N = sys.argv[1]
    if "--check" in sys.argv:
        sys.exit(check(N))
    n = build(N)
    print(f"sealed {n} files")
    sys.exit(check(N))
