B.push(h2('12.  The Closure Theorem: Why These Coordinates and Not Others'));
B.push(p([t('Section 10 established that Λ is closed under join and meet. That result invites a question the earlier draft of this work did not ask: is the closure a coincidence of the particular constraints chosen, or does it follow from something about their form? The answer is the latter, and stating it precisely both explains the results of Sections 10 and 11 and settles the fate of an extension proposed previously.')]));

B.push(h3('12.1  A criterion for closure'));
B.push(p([t('Consider any set of integer tuples defined by constraints of the two kinds that appear in Λ: upper bounds in which one coordinate is limited by a function of others, and lower bounds. Closure under componentwise join requires that raising any coordinate cannot violate a constraint; closure under meet requires that lowering any coordinate cannot violate one either.')]));
B.push(p([t('Upper bounds of the form x ≤ f(y) with f monotone non-decreasing are safe in both directions. Under join, x rises but so does f(y), because y rises too. Under meet, x falls and f(y) falls with it, but x was already the smaller of two admissible values and so remains beneath the reduced ceiling. Lower bounds behave differently. A constant floor x ≥ c is preserved under meet, since the minimum of two values each at least c is itself at least c. But a floor that varies with another coordinate, x ≥ g(y) with g increasing, is not: taking the meet may lower y and thus g(y), yet may take x from the other operand where x was permitted only because that operand had a larger y.')]));
B.push(p([t('The criterion is therefore that a componentwise poset on integer tuples forms a bounded lattice when every upper bound is monotone in the other coordinates and every lower bound is constant. Λ satisfies it exactly:')]));
B.push(eq('ℓ ≤ n − 1          upper bound, monotone in n', '9'));
B.push(eq('k ≤ 2(2ℓ + 1)      upper bound, monotone in ℓ', '10'));
B.push(eq('k ≥ 1,   ℓ ≥ 0,   n ≥ 1      constant floors', '11'));
B.push(p([t('Every constraint in the lattice of Part I is of a permitted form. The closure demonstrated exhaustively in Section 10 is not an accident of the numbers 2(2ℓ+1) and n−1; it is a consequence of the constraints being one-sided in the required sense.')]));

B.push(h3('12.2  The hydrogenic unfolding fails'));
B.push(p([t('Section 10.5 of the earlier draft observed that the occupancy index k conflates two hydrogenic labels — the magnetic quantum number m and the spin projection — and proposed unfolding k into those constituents as the natural extension of the framework, on the grounds that it might admit the SO(4,2) representation theory the three-axis form cannot support. The criterion just stated shows why this cannot work.')]));
B.push(p([t('The hydrogenic constraint is |m| ≤ ℓ, which is the conjunction of an upper bound m ≤ ℓ and a lower bound m ≥ −ℓ. The upper bound is of a permitted form. The lower bound is not: it varies with ℓ. Meet closure must therefore fail, and it does. Exhaustive checking of the four-axis set Λ′ = {(n, ℓ, m, s)} returns zero join failures and 4,040 meet failures out of the pairs available.')]));
B.push(p([t('A concrete instance makes the mechanism plain. The cells (3, −3) and (1, 1) in the (ℓ, m) plane are both admissible, since |−3| ≤ 3 and |1| ≤ 1. Their componentwise meet is (1, −3), for which |−3| > 1. The meet leaves the admissible set. Figure 8 contrasts this with the behaviour of k, whose constant floor keeps every meet inside Λ.')]));
B.push(img('fig8_closure.png', 640, 211));
B.push(cap(8, 'Why the occupancy coordinate is load-bearing. (a) The constraint on k: a ceiling that rises with ℓ and a constant floor at k = 1. The meet of two admissible cells is admissible, because lowering k can never fall below a floor that does not move. (b) The hydrogenic constraint on m: ceiling at +ℓ and floor at −ℓ. Because the floor varies with ℓ, the meet of (ℓ, m) = (3, −3) and (1, 1) is (1, −3), which violates |m| ≤ ℓ and falls outside the admissible set. (c) Closure across four coordinate systems, each containing exactly 210 cells. Only the signed hydrogenic unfolding fails, and it fails on meet alone.'));

B.push(h3('12.3  Why the repair is not a repair'));
B.push(p([t('Closure can be restored by substituting m′ = m + ℓ, which converts the pair of constraints into m′ ≤ 2ℓ and m′ ≥ 0 — an upper bound monotone in ℓ and a constant floor, both permitted. Exhaustive checking confirms that the shifted four-axis set is again a bounded lattice, and that the shell capacities 2n² are recovered. Re-indexing the magnetic states from 1 to 2ℓ+1 achieves the same effect.')]));
B.push(p([t('But the repair defeats its own purpose. The coordinate m′ = m + ℓ is not the magnetic quantum number; it is m displaced by an amount that itself varies across the lattice. The representation theory that motivated the unfolding is built on m, not on m shifted by a position-dependent offset, and so has no more purchase on the shifted lattice than on the original. Closure is recovered precisely by abandoning the object the unfolding was performed to obtain.')]));
B.push(p([t('The proposal of the earlier draft is therefore withdrawn. There is no four-axis refactoring of Λ that both preserves the order structure of Sections 10 and 11 and exposes the hydrogenic labels in a form that group theory can act on. This is a limitation of the framework, and it appears to be a structural one rather than a gap awaiting further work.')]));

B.push(h3('12.4  What the theorem means for the rest of the paper'));
B.push(p([t('The closure criterion clarifies the standing of results elsewhere in this work, in three ways.')]));
B.push(p([t('It explains rather than merely reports. The facts of Section 10 — that Λ is a bounded lattice, that hydrogen is its unique minimum, that shell capacities appear as slice volumes — now follow from a stated property of the constraints instead of resting on exhaustive verification alone. Hydrogen occupies the least position because k and ℓ have constant floors and n begins at 1; the minimum is (1, 0, 1) for that reason and no other.')]));
B.push(p([t('It identifies what is load-bearing. The occupancy coordinate k, which Part I introduced simply as the electron count, turns out to be the coordinate that makes the structure work. Its one-sided bound is what permits closure, and the results of Part II would not survive its replacement by the hydrogenic labels it conflates. This also gives independent significance to the finding of Section 8.3, where k was the coordinate carrying information orthogonal to established chemical descriptors. The same coordinate is doing the work in both the order-theoretic and the empirical results.')]));
B.push(p([t('And it sets a boundary. Because no admissible refactoring exposes m, the framework cannot be connected to the dynamical symmetry group of the hydrogen atom by any route considered here. Whatever the lattice is, it is not a representation-theoretic object in disguise; it is a combinatorial one, and its correspondences are with other combinatorial descriptions of the periodic system, of which the Janet arrangement of Section 11 is the principal example.')]));
