B.push(h2('10.  Order-Theoretic Structure and Existing Formalisms'));
B.push(p([t('Sections 8 and 9 tested the lattice against measured data and found it outclassed by established descriptors on the one task where a direct comparison was possible. This section asks a different question. Rather than what the lattice predicts, it asks what the lattice is — and here the answer is more favourable, because the structure turns out to have properties that were not designed into it and to stand in an exact relationship to an existing periodic formalism.')]));

B.push(h3('10.1  Λ is a bounded lattice in the algebraic sense'));
B.push(p([t('Order the admissible cells componentwise: (n, ℓ, k) ≤ (n′, ℓ′, k′) when each coordinate is no greater than its counterpart. The question is whether Λ is closed under the resulting join and meet — that is, whether the componentwise maximum and minimum of any two admissible cells are themselves admissible. Exhaustive checking of all 21,945 pairs drawn from the 210 admissible cells returns no failures in either direction.')]));
B.push(p([t('The reason is structural. Raising n never violates ℓ ≤ n − 1, and raising ℓ raises the capacity ceiling 2(2ℓ+1), so a raised k remains admissible; lowering ℓ lowers the ceiling but k is lowered in step. Both constraints are therefore preserved under join and meet, and Λ is a bounded lattice with least element (1, 0, 1) and greatest element (7, 4, 18).')]));
B.push(p([t('One consequence deserves emphasis. Hydrogen was placed at the origin in Section 2 as a reference choice. It is not a choice: (1, 0, 1) is the unique minimum of the poset, the only cell below every other. The anchoring of the framework at hydrogen is a theorem about the structure rather than a convention imposed on it.')]));
B.push(p([t('A related point settles a question that might otherwise seem open. The quantities ΔQ and σ²(t) are differences of coordinates and are therefore invariant under any translation of the origin; so are the direction classes of Section 6 and the adjacency of Section 7. Order-theoretic facts are likewise preserved, since a coordinate shift is an order isomorphism. Only |Q₀|, and hence H_cp, depends on where the origin is placed — and that quantity was shown in Section 8 to have negative cross-validated predictive value under every origin tested. Nothing that works in this framework depends on the origin, and nothing that fails is rescued by moving it.')]));

B.push(h3('10.2  Shell capacity as lattice volume'));
B.push(p([t('Counting the admissible cells at fixed n gives')]));
B.push(eq('Σ(ℓ=0 to n−1)  2(2ℓ+1)  =  2n²', '8'));
B.push(p([t('so the shell capacities 2, 8, 18, 32, 50, 72, 98 are the volumes of the horizontal slices of Λ. The Pauli capacities of the periodic system are not an input to the lattice; they are what one obtains by counting it. This is a small result, but it indicates that the coordinate choice is capturing genuine structure rather than merely relabelling it.')]));

B.push(h3('10.3  The Madelung rule as a linear functional'));
B.push(p([t('The Madelung or aufbau rule fills subshells in order of increasing n + ℓ, ties broken by increasing n. On the lattice, n + ℓ is a linear functional, and its level sets are parallel diagonal planes cutting through Λ. The filling sequence of the elements is a sweep of these planes, illustrated in Figure 7(a).')]));
B.push(p([t('Sorting the 118 occupied cells by (n + ℓ, n, k) and reading off atomic number reproduces the true ordering with Kendall τ = 0.992; the 28 inversions are the known lanthanide and actinide irregularities, where measured ground states depart from the idealised rule. The lattice is compatible with Madelung ordering but does not derive it: the rule remains an empirical input, imposed on Λ rather than produced by it.')]));
B.push(p([t('What the lattice does supply is an explanation for the pattern of period lengths. Computing the volume of each Madelung slice gives 2, 2, 8, 8, 18, 18, 32, 32, 50, 50, 72, 72 — the slices come in exactly equal consecutive pairs, shown in Figure 7(b). This pairing is the reason the periods of the periodic table repeat their lengths, a regularity that the conventional two-dimensional layout must impose by construction and cannot explain. Here it is a counting fact about parallel slices of a three-dimensional structure.')]));
B.push(img('fig7_order.png', 640, 203));
B.push(cap(7, 'Order-theoretic structure of the lattice. (a) The (n, ℓ) face of Λ, each cell carrying its capacity 2(2ℓ+1) and shaded by Madelung level; the dashed diagonals are the planes n + ℓ = constant. (b) Volume of each Madelung slice. The slices pair exactly — 2, 2, 8, 8, 18, 18, 32, 32, 50, 50 — reproducing the observed period lengths of the periodic system. (c) The Janet left-step table, obtained by projecting Λ along the functional n + ℓ; each row is one Madelung slice and its width is the slice volume from panel (b).'));

B.push(h3('10.4  Correspondence with the Janet left-step table'));
B.push(p([t('The projection just described is not a new arrangement. Charles Janet proposed in 1929 a reordering of the periodic table by n + ℓ blocks, producing period lengths 2, 2, 8, 8, 18, 18, 32, 32 and placing helium above beryllium rather than above neon. The left-step table has been argued in the philosophy of chemistry to be the most natural periodic form, on the grounds that it follows the quantum-mechanical filling order rather than chemical resemblance.')]));
B.push(p([t('The relationship to the present framework is exact. Janet\'s blocks are the level sets of the linear functional n + ℓ on Λ, and his table is the two-dimensional projection of the lattice along that functional, as Figure 7(c) shows. This is a correspondence rather than an analogy: the two structures contain the same information, with Janet\'s form arising from Λ by a specific and identifiable projection.')]));
B.push(p([t('The claim this supports is modest but real. The left-step table is customarily justified by appeal to the Madelung rule; the lattice shows that it is the shadow of a three-dimensional object, and that the pairing of period lengths which Janet\'s form exhibits is a volumetric property of that object. Whether this constitutes an improved justification for the left-step arrangement is a question for the philosophy-of-chemistry literature, where such matters are actively debated.')]));

B.push(h3('10.5  Where the correspondence fails'));
B.push(p([t('Two connections that might be expected do not hold, and stating them limits the claims above.')]));
B.push(p([t('The hydrogen atom possesses a well-known dynamical symmetry, SO(4) for bound states at fixed n and SO(4,2) as a spectrum-generating algebra, under which the n² degeneracy of hydrogenic states is a representation-theoretic fact. It is tempting to look for a corresponding symmetry acting on Λ. There is none available, because the objects differ: hydrogenic states are labelled |n, ℓ, m⟩ where m is the magnetic quantum number, whereas the lattice is labelled (n, ℓ, k) where k is an occupancy count. The factor of two relating 2n² to n² is spin degeneracy, and k already conflates m and m_s into a single index. Representation theory built on |n, ℓ, m⟩ therefore has nothing to attach to in Λ.')]));
B.push(p([t('This observation identifies the natural extension of the framework. Unfolding k into its constituent m and m_s indices would give a four-axis lattice with the same 210 cells but a factored structure, in which the hydrogenic labels appear explicitly. Whether that extension admits the symmetry the present three-axis form lacks is an open question, and the more promising direction for further mathematical development than anything pursued in Part II.')]));
B.push(p([t('Second, a remark on Equation (4). The identities on which it rests were verified symbolically: the normalisation cos²(Ωt) + 2·[sin(Ωt)/√2]² = 1 holds identically, as does cos(Ωt) + sin(Ωt) = √2 sin(Ωt + π/4). But the summation in Equation (4) carries no element label and its prefactor is element-independent, so all 118 elements share a single envelope. The expression is a correct normalisation statement about Λ rather than a dynamical law distinguishing one element from another; everything element-specific in this framework resides in ΔQ and σ²(t), which are geometric quantities defined in Section 5. Readers should weigh the lattice and its order structure, not the field equation, as the substantive content of Part I.')]));
