B.push(h3('23.2  The structure-map test'));
B.push(p([t('Section 23.1 leaves a question open, and the answer determines how the result there should be read. Occupancy improves prediction of hydride formation enthalpy when appended to Pettifor\\'s scale. But that scale was not constructed to predict formation enthalpies; it was constructed so that binary compounds of the same structure type occupy adjacent positions in a two-dimensional map. Whether occupancy helps on that task is a separate question, and it can be tested.')]));
B.push(p([t('A set of 139 binary AB compounds with well-established structure types was assembled from standard inorganic and intermetallic references, spanning nine types: rock salt, zinc blende, wurtzite, caesium chloride, nickel arsenide, copper gold, sodium thallide, chromium boride and iron boride. The quality of a structure map is conventionally measured by whether compounds of the same type fall together, and the standard quantitative proxy is leave-one-out nearest-neighbour accuracy in the coordinate space: for each compound, does its closest neighbour in the map share its structure type? The majority-class baseline on this set is 0.317.')]));
B.push(tcap(3,'Structure-map separation for 139 binary AB compounds across nine structure types, measured by leave-one-out nearest-neighbour accuracy. Features standardised; the unstandardised results differ by less than 0.02 and change no conclusion.'));
B.push(table(
  ['Coordinate set','Dimensions','LOO-NN accuracy','Gain over Pettifor'],
  [['majority class','—','0.317','—'],
   ['occupancy k alone','2','0.547','−0.266'],
   ['lattice (ℓ, k) alone','4','0.662','−0.151'],
   ['Pettifor MN','2','0.813','—'],
   ['Pettifor + ℓ','4','0.799','−0.014'],
   ['Pettifor + k','4','0.813','+0.000'],
   ['Pettifor + k/k_max','4','0.835','+0.022'],
   ['Pettifor + k + ℓ','6','0.813','+0.000']],
  [2600,1300,1600,1700],['Pettifor + k']));
B.push(p([t('The answer is negative. Appending occupancy to Pettifor\\'s coordinates changes the separation accuracy by +0.000; a McNemar test on the paired outcomes gives p = 1.000, with three compounds gained and three lost. The fractional variant k/k_max yields +0.022, which is three compounds and not significant at p = 0.250. Pettifor\\'s two coordinates alone reach 0.813, and the lattice coordinates alone reach only 0.662 — well below the scale they were meant to augment.')],
  {spacing:{before:160,after:120}}));
B.push(p([t('One feature of the result requires care, because it is easily misread. A permutation test that shuffles the occupancy values while holding the Pettifor coordinates fixed gives p < 0.0001, which looks at first like evidence that occupancy matters. It is not. Shuffled occupancies reduce accuracy by 0.234 on average, because adding uninformative dimensions actively degrades nearest-neighbour classification, whereas the real occupancies leave accuracy unchanged. The test therefore establishes that k is not noise; it does not establish that k adds anything. The correct reading is that occupancy carries real information which is redundant with Pettifor\\'s scale for this purpose.')]));
B.push(p([t('The consequence for Section 23.1 is direct. Occupancy is uncorrelated with the Mendeleev number, at r = −0.05, and it adds orthogonal information about hydride formation enthalpy; it adds nothing about binary structure-type separation. Orthogonality of a descriptor and usefulness of a descriptor are therefore not the same thing, and the usefulness here is task-specific. The claim that survives is confined to one property, and the natural generalisation has now been tested and does not hold.')]));
B.push(p([t('Two limitations of the test should be recorded. The compound set was compiled from standard references rather than extracted from a crystallographic database, so it is smaller than the sets used by Pettifor or by later data-mining work and may contain assignment errors; a test on the full Inorganic Crystal Structure Database would be more authoritative. And nearest-neighbour accuracy is a proxy for map quality rather than the quality itself, though it is the proxy the data-mining literature uses. Neither limitation is likely to convert a gain of +0.000 into a real effect.')]));
