# B10 — Ruling 60 sweep. Object first; action only where no object exists.
# Anchors are exact-match. Each must occur EXACTLY ONCE in its file.

MAIN = "The_Method_1_6-2.md"
REG  = "The_Method_1_6___The_Register-2.md"
MATH = "The_Method_1_6___Mathematical_Compendium-2.md"
PHYS = "The_Method_1_6___The_Physics_Compendium-2.md"
IOI  = "The_Method_1_6___The_Index_of_Indices-2.md"
SPEC = "The_Method_1_6___Spectra_Compendium-2.md"

SUBS = {
MAIN: [
 ("E(G), recomputed at build;",
  "E(G), recomputed;"),
 ("The harness is *zeno.py*, the state is *.zeno/*, and \u00a72.20's requirement",
  "The work is segmented and its state is preserved, and \u00a72.20's requirement"),
 ("the requirement exists as a file rather than an intention: *The Method 1.6 audits.py* runs the whole set",
  "the requirement is executed rather than intended: the whole set of twenty runs"),
 ("the uncorrected series the Spectra Compendium carried until Build 9.",
  "the uncorrected series the Spectra Compendium carried until the correction at register 1758."),
 ("(generated by `register_gen.py` from this book's own source and",
  "(drawn from this book's own source and"),
 ("the source since Build 9, so it cannot be thinned by an edit here.",
  "the source, so it cannot be thinned by an edit here."),
 ("Recomputed at this build (2026-08-24, `bookindex.py`), over the",
  "Recomputed on 2026-08-24, over the"),
 ("with zero failures (`rclose.py`).",
  "with zero failures (computed)."),
 ("rerun by `tb_audit.py`, 1756)",
  "rerun at register 1756)"),
 ("generated by* `spectra.py` *so it cannot drift,\"",
  "generated so it cannot drift,\""),
 ("the table drifted from\n the script, and the script is owed a rebuild against the table.",
  "the table drifted, and that generation is retired: the table above is the source."),
 ("Regenerated from the text on 2026-08-24 (`index_gen.py`):",
  "Regenerated from the text on 2026-08-24:"),
],
REG: [
 ("| kind | entries (Build 16) | first reading | what it means |",
  "| kind | entries | first reading | what it means |"),
 ("*The Build 16 column is recomputed from this file by `kinds.py` over the 1,458 entry headings",
  "*The entries column is recomputed from this file over the 1,458 entry headings"),
 ("The first-reading column ( and earlier) was produced by patterns that were never printed",
  "The first-reading column was produced by patterns that were never printed"),
 ("Recomputed from this file by `register_cites.py` (2026-08-24).*",
  "Recomputed from this file (2026-08-24).*"),
 ("\nBuild 9, 2026-08-24. **1458 entries, 165 to 1779.**",
  "\n2026-08-24. **1458 entries, 165 to 1779.**"),
 ("The generator that once wrote it, `register_gen.py`, was retired at Build 9: entries from 1701 on",
  "The generator that once wrote it was retired: entries from 1701 on"),
 ("What is recomputed from this file at every press is stated where it is printed \u2014 the citation counts and the load-bearing table (`register_cites.py`, 1732), the kinds table below (`kinds.py`, 1756), and the entry form (`build.py`, 1744).",
  "What is recomputed from this file is stated where it is printed \u2014 the citation counts and the load-bearing table (register 1732), the kinds table below (register 1756), and the entry form (register 1744)."),
],
MATH: [
 ("Generated from `mathreg.py` on 2026-08-12; the counts below were recounted",
  "Compiled 2026-08-12; the counts below were recounted"),
 ("`mathverify.py` makes **103 assertions naming 46 of these objects** and recomputes each stated value against the register",
  "**103 assertions name 46 of these objects** and recompute each stated value against the register"),
 ("`check_audit.py` classifies them on any build. Register 849.",
  "The check fields are classified at register 849."),
 ("Rebuild with `python3 compendium.py > COMPENDIUM.md`. It reads the register, so it cannot",
  "This volume is drawn from the register, so it cannot"),
 ("*M \u00a714.5.9 / twoheur.py; Karp 1972; Johnson 1974*",
  "*M \u00a714.5.9; Karp 1972; Johnson 1974*"),
 ("*M \u00a721.5.5 / allcons.py; Freuder 1978*",
  "*M \u00a721.5.5; Freuder 1978*"),
 ("*protindex.py; Freuder 1978*",
  "*computed; Freuder 1978*"),
 ("*M \u00a720 / stat_lang.py; Deming & Stephan 1940; Csiszar 1975*",
  "*M \u00a720; Deming & Stephan 1940; Csiszar 1975*"),
 ("*close_L.py; Madelung 1936; NIST*",
  "*computed; Madelung 1936; NIST*"),
 ("while indices.py COMPUTES 22275, 64290",
  "while the exact triangle GIVES 22275, 64290"),
 ("The generated table in INDICES.md gives 0 with fraction 0.0000, indices.py says '\u039b\u2088 composes not at all \u2014 four source coordinates against three target', and K.window states the reason",
  "The composition table gives 0 with fraction 0.0000, \u039b\u2088 composes not at all \u2014 four source coordinates against three target \u2014 and K.window states the reason"),
 ("not yet by `mathverify.py`; wiring them into the book's verifier is a build task, and until it is done",
  "not yet by this volume's own checks; that check is outstanding, and until it is done"),
 ("`ground.py`'s own edge of Z = 108 as the limit",
  "the ground-state table's own edge of Z = 108 as the limit"),
],
PHYS: [
 ("Generated from `mathreg.py` and `SPECTRA-DATA.tsv` on 2026-08-12.",
  "Compiled 2026-08-12."),
 ("`channels.py` writes `bracket = \"untested\"` for every channel it builds, because running the bracketing method needs measured neighbours and a tolerance and the script supplies neither.",
  "The bracket reads `untested` for every channel built here, because running the bracketing method needs measured neighbours and a tolerance and neither was supplied."),
],
IOI: [
 ("Generated on 2026-08-15 by `indices.py`.",
  "Compiled 2026-08-15."),
 ("and it is what `domain_protocol.py` enforces.**",
  "and it is what the closure of the domain axis enforces.**"),
],
SPEC: [
 ("*Every figure in this table is read from* `COORDINATES-2.13` *at build by* `coords.py`*, which fails the press if one of them drifts from the file.*",
  "*Every figure in this table is read from the coordinate file set out in \u00a7 The file, and each is checked against that file.*"),
 ("All bracket figures in this paragraph are recomputed from the table by `spectra_count.py`.",
  "All bracket figures in this paragraph are recomputed from the table above."),
 ("It claimed the table could not drift from* `spectra.py`; *the table did drift, so* `spectra.py` *is retired: the table above is the source, and every count in the paragraph above it is taken from the table by* `spectra_count.py` * \u2014 596,",
  "It claimed the table was generated and so could not drift; the table did drift, and that generation is retired: the table above is the source, and every count in the paragraph above it is taken from the table \u2014 596,"),
 ("Counts below are read from `COORDINATES-2.13` at build time, not transcribed.*",
  "Counts below are read from the coordinate file set out in \u00a7 The file, not transcribed.*"),
],
}

if __name__ == "__main__":
    import sys
    B = "/home/claude/build/"
    bad = 0; n = 0
    for f, pairs in SUBS.items():
        t = open(B + f, encoding="utf-8").read()
        for a, b in pairs:
            n += 1
            c = t.count(a)
            if c != 1:
                bad += 1
                print(f"FAIL {c:>3}x  {f}  ::  {a[:80]!r}")
    print(f"\n{n} anchors tested, {bad} failing")
    sys.exit(1 if bad else 0)
