S2 = [
("and `ladder_index2.py` is deleted \u2014 two scripts for one index", "and the duplicate index is deleted \u2014 two indexes for one object"),
("*`sixpair_screen.py`.*", "*Screened over the six pairs.*"),
("*`indices.py`* **computes** *its tower", "*The exact triangle* **computes** *its tower"),
("`mathreg.py`'s T.tower* **states**", "T.tower* **states**"),
("*`zeno.py` printed its checkpoint log to stdout while `indices.py` writes its artefact to stdout", "*The checkpoint log printed to stdout while the index writes its artefact to stdout"),
("And `roundtrip.py`'s normalisation is", "And the round-trip normalisation is"),
("*`balance.py`.*", "*Computed.*"),
("*`null_madelung.py`.*", "*Measured.*"),
("*`scorer.py`, a REBUILD", "*A REBUILD"),
("`xray_index.py`, `traj_index.py`, the captures", "the X-ray index, the trajectory index, the captures"),
("*`scorer.py` placed a using each step's OWN corridor \u2014 and a corridor is built by `brack.py` FROM the observed entrant", "*The scoring placed a using each step's OWN corridor \u2014 and a corridor is built FROM the observed entrant"),
("and `ground.py` matches all five exactly, so our table is faithful to the source.", "and the ground-configuration table matches all five exactly, so it is faithful to the source."),
("`contingency.py` exists in this tree to catch exactly that", "The contingency test exists to catch exactly that"),
("and is now enforced in `belokolos_spectrum.py` with a comment saying why.", "and is now enforced in the ranking, with the reason recorded."),
("Corrected to 0 in `a5c.py` and `merged_triples.py`.*", "Corrected to 0 in both counts.*"),
("**The counts move: a5c.py goes from six of thirty-five systems closing to FIVE", "**The counts move: the A5c systems go from six of thirty-five closing to FIVE"),
("merged_triples.py goes from three of forty-six to FOUR", "the merged triples go from three of forty-six to FOUR"),
("`contingency.py` has been in this tree since it was rebuilt this morning", "The contingency test has stood since it was rebuilt this morning"),
("preference: `indices.py` says", "preference: the composition table says"),
("`roundtrip.py`'s normalisation substituted", "the round-trip normalisation substituted"),
("Applying 1481's correction to `mathreg.py` broke the file twice in succession.", "Applying 1481's correction to the object list broke it twice in succession."),
("the three that depend on `mathreg.py` loading.", "the three that depend on the object list loading."),
("Built as `vi_decorrelate.py`, seeded from vi_best", "Built as a decorrelation, seeded from vi_best"),
("while `vi_final.py` reports 79 under its own weights 4,1,3,3,1,1", "while the weighted count is 79 under weights 4,1,3,3,1,1"),
("same answer `sudoku_index.py` returned this morning", "same answer the sudoku index returned this morning"),
("exactly what `contingency.py` exists to catch, committed in the sentence", "exactly what the contingency test exists to catch, committed in the sentence"),
("The census in `The_Method_1_6_audits.py` matches phrases", "The census matches phrases"),
("eighteen ground configurations match `ground.py` exactly", "eighteen ground configurations match the ground-configuration table exactly"),
("and `ground.py` was written from the aufbau work", "and that table was written from the aufbau work"),
("`mathreg.py` states it as a RESULT:", "The record states it as a RESULT:"),
("Built `register_review.py` to find candidates on six mechanical failure modes", "Candidates were found on six mechanical failure modes"),
("three were not defined in `mathreg.py`.", "three were not defined in the object list."),
("`appendix_audit.py` at 595, and seven more.", "the appendix checks at 595, and seven more."),
("Built as `sudoku3.py`: three independent determinations of one cell", "Built as a three-way index: three independent determinations of one cell"),
("`coords.py` labelled every measured cell", "Every measured cell was labelled"),
("`coords.py` declares every cell above charge 10 improbable", "Every cell above charge 10 is declared improbable"),
("311 CELLS WERE INHERITED IN `aufbau.py`'s OWN measured() FUNCTION", "311 CELLS WERE INHERITED FROM THE AUFBAU WORK'S OWN MEASURED SET"),
("`scorer.py` reads the corridor for the CURRENT step", "the scoring reads the corridor for the CURRENT step"),
("while `brack.py` builds that corridor FROM the observed entrant", "while that corridor is built FROM the observed entrant"),
("**BUILT AS `trajectory.py`, WITH NOTHING ELSE CHANGED", "**BUILT AS A HELD-OUT TRAJECTORY, WITH NOTHING ELSE CHANGED"),
]