import numpy as np, random, math
from itertools import product, permutations, combinations
random.seed(521)
print("="*88)
print("  TESTS C, D, E — THREE EXPLANATIONS OF EQUAL-SIZED COMPONENTS")
print("="*88)
print("""
  **TEST C.** #components = |Aut(X)|, where Aut(X) is the group of value
  permutations mapping X to itself. Computable from X alone.

  **TEST D — the simpler one I should have checked first.** If two values on
  an axis have IDENTICAL fibres, F(u) = F(v), they are interchangeable:
  swapping them maps valid orders to valid orders. **The group generated by
  those swaps acts freely, giving orbits of equal size ∏ (class size)!** —
  and it needs no valid order and no automorphism computation.

  **TEST E.** The sharp version of C: are the ORBITS of Aut(X) actually the
  components, not merely equal in number?
""")
def alph(S,d): return [sorted({x[i] for x in S}) for i in range(d)]
def relab(S,o,d):
    ix=[{v:i for i,v in enumerate(p)} for p in o]
    return {tuple(ix[k][x[k]] for k in range(d)) for x in S}
def lat(S,d):
    Ss=set(S)
    for x,y in combinations(sorted(S),2):
        if tuple(max(x[i],y[i]) for i in range(d)) not in Ss: return False
        if tuple(min(x[i],y[i]) for i in range(d)) not in Ss: return False
    return True
def valid(S,d,cap=60000):
    A=alph(S,d)
    if int(np.prod([math.factorial(len(a)) for a in A]))>cap: return None
    return [tuple(ps) for ps in product(*[list(permutations(a)) for a in A])
            if lat(relab(S,[list(p) for p in ps],d),d)]
def nbrs(o):
    out=[]
    for i in range(len(o)):
        p=list(o[i])
        for t in range(len(p)-1):
            q=list(p); q[t],q[t+1]=q[t+1],q[t]
            oo=list(o); oo[i]=tuple(q); out.append(tuple(oo))
    return out
def comps(V):
    VS=set(V); seen=set(); C=[]
    for v in V:
        if v in seen: continue
        st=[v]; seen.add(v); c=[]
        while st:
            u=st.pop(); c.append(u)
            for w in nbrs(u):
                if w in VS and w not in seen: seen.add(w); st.append(w)
        C.append(c)
    return C
def fibre(S,d,i,u): return frozenset(tuple(x[k] for k in range(d) if k!=i) for x in S if x[i]==u)
def identical_classes(S,d):
    """per axis, group values by identical fibre"""
    A=alph(S,d); out=[]
    for i in range(d):
        g={}
        for u in A[i]: g.setdefault(fibre(S,d,i,u),[]).append(u)
        out.append([v for v in g.values()])
    return out
def predD(S,d):
    cls=identical_classes(S,d)
    p=1
    for axis in cls:
        for c in axis: p*=math.factorial(len(c))
    return p
def autX(S,d):
    """value permutations (per axis) mapping X to itself"""
    A=alph(S,d); out=[]
    maps=[]
    for i in range(d):
        maps.append([dict(zip(A[i],p)) for p in permutations(A[i])])
    for combo in product(*maps):
        T={tuple(combo[k][x[k]] for k in range(d)) for x in S}
        if T==set(S): out.append(combo)
    return out
print("  %6s%6s%8s%10s%12s%14s%14s%12s"%("d","|A|","n","comps","comp size","pred D","|Aut(X)|","D match"))
print("  "+"-"*82)
ROWS=[]
for d,a,lim in [(2,3,300),(2,4,120),(3,2,300),(3,3,80)]:
    n=0; cc=[]; cs=[]; pd=[]; au=[]; dm=0; cm=0
    for _ in range(lim):
        Ax=[list(range(a)) for _ in range(d)]
        cl=list(product(*Ax))
        S=set(random.sample(cl,random.randint(2,len(cl))))
        A=alph(S,d)
        if any(len(x)<2 for x in A): continue
        V=valid(S,d)
        if not V or len(V)<2: continue
        C=comps(V)
        sz=len(C[0])
        if len({len(c) for c in C})!=1: continue
        n+=1
        p=predD(S,d)
        try: al=len(autX(S,d))
        except Exception: al=-1
        cc.append(len(C)); cs.append(sz); pd.append(p); au.append(al)
        dm+= (sz==p); cm+= (len(C)==al)
    if n:
        print("  %6d%6d%8d%10.2f%12.2f%14.2f%14.2f%11d%%"%(d,a,n,np.mean(cc),np.mean(cs),np.mean(pd),np.mean(au),int(100*dm/n)))
        ROWS.append((d,a,n,dm,cm))
print("\n  %6s%6s%8s%18s%18s"%("d","|A|","n","D: size = pred","C: comps = |Aut|"))
print("  "+"-"*58)
for d,a,n,dm,cm in ROWS:
    print("  %6d%6d%8d%17d%%%17d%%"%(d,a,n,int(100*dm/n),int(100*cm/n)))
print("="*88)
print("  TEST E — ARE THE Aut ORBITS THE COMPONENTS?")
print("="*88)
n=hit=0
for _ in range(300):
    d=random.choice([2,3]); a=random.choice([2,3])
    Ax=[list(range(a)) for _ in range(d)]
    cl=list(product(*Ax))
    S=set(random.sample(cl,random.randint(2,len(cl))))
    A=alph(S,d)
    if any(len(x)<2 for x in A): continue
    V=valid(S,d)
    if not V or len(V)<2: continue
    C=comps(V)
    try: Au=autX(S,d)
    except Exception: continue
    VS=set(V); n+=1
    # orbit of the first valid order under Aut(X)
    o=V[0]
    orb=set()
    for g in Au:
        oo=tuple(tuple(g[k][v] for v in p) for k,p in enumerate(o))
        if oo in VS: orb.add(oo)
    mine=next(c for c in C if o in c)
    hit+= (orb==set(mine))
print("\n     instances %d     Aut orbit == its component : %d  (%.0f%%)"%(n,hit,100*hit/max(n,1)))