print('  THE TWO ALGEBRAIC RETURN EQUATIONS')
print()
print('  R1  BORCHERS   (translation -> modular)')
print('      GIVEN   a one-parameter unitary group U(a) = e^{iPa} with P >= 0,')
print('              and U(a) M U(-a) subset M for a >= 0,')
print('              with Omega invariant: U(a)Omega = Omega')
print('      THEN    Delta^{it} U(a) Delta^{-it}  =  U(e^{-2 pi t} a)')
print('              J U(a) J                     =  U(-a)')
print('      -> the modular data is DETERMINED by the translation.')
print()
print('  R2  WIESBROCK  (modular -> translation)')
print('      GIVEN   an inclusion  N subset M  with a common cyclic separating Omega,')
print('              such that   sigma_t^M (N) subset N   for all t <= 0')
print('              [ this is the definition of a half-sided modular inclusion ]')
print('      THEN    there exists U(a) = e^{iPa} with P >= 0, U(a)Omega = Omega,')
print('              U(a) M U(-a) subset M for a >= 0,   and   N = U(1) M U(-1)')
print('      -> the translation is DETERMINED by the modular data and the inclusion.')
print()
print('      (Wiesbrock CMP 184 (1997); gap filled and extended to weights by Araki-Zsido 2004)')
print()
print('  THEY ARE INVERSE')
print('     R1: U  ->  Delta        R2: (Delta, inclusion)  ->  U')
print('     together they are the CHARACTERISATION: HSMI <=> a positive-generator U.')
print()
print('  WHICH LANGUAGE HAVE WE BEEN READING?')
print()
T=[('geometric','build U from a clock on the surface, then apply R1 to get the modular relation',
    'Killing parameter, or the area form via Theta',
    'REQUIRES: a quantity varying along the generators',
    'BLOCKED on an isolated horizon: nothing intrinsic varies'),
   ('algebraic','establish the inclusion property, then apply R2 to get U',
    'sigma_t(M(u+delta)) subset M(u+delta) for one sign of t',
    'REQUIRES: MOD (the modular flow) and NEST (the inclusion)',
    'BOTH PRESENT on an isolated horizon')]
for a,b,c,d,e in T:
    print('  %-11s %s' % (a,b))
    print('  %-11s   instrument: %s' % ('',c))
    print('  %-11s   %s' % ('',d))
    print('  %-11s   %s' % ('',e))
    print()
print('  THE TRANSLATION OF THE TRANSLATOR')
print('     we have been reading in the GEOMETRIC language, in which the sentence is')
print('        "construct a positive-generator unitary group"')
print('     and it is unsayable on an isolated horizon because the geometry has no clock.')
print()
print('     read in the ALGEBRAIC language, the same sentence is')
print('        "show that the modular flow of one cut preserves the later cuts"')
print('     and it mentions no metric, no clock, and no generator.')
print()
print('     R2 is what carries one to the other. it is the translator between the two')
print('     readings, and it runs Delta -> U, which is the direction we were not using.')
print()
print('  WHAT THE ALGEBRAIC READING ACTUALLY DEMANDS')
print('     for cuts u < u+delta on an isolated horizon:')
print('        M(u+delta) subset M(u)                        NEST      present')
print('        Omega cyclic and separating for both          CYC       present')
print('        sigma_t^{M(u)} ( M(u+delta) ) subset M(u+delta)   for t <= 0     ????')
print()
print('     the third line is the whole problem, and it is a statement about the')
print('     MODULAR FLOW OF A HADAMARD STATE, not about the horizon geometry.')
print()
print('  AND IT IS FALSIFIABLE IN A WAY THE GEOMETRIC READING IS NOT')
print('     geometric reading: "no construction is known" - an absence of evidence.')
print('     algebraic reading:  "sigma_t(N) subset N or it does not" - a property that')
print('        either holds or fails, and a single counterexample settles it.')
print()
print('     -> the two readings differ in FALSIFIABILITY, not only in difficulty.')