#!/usr/bin/env python3
"""predict_channels.py -- the channel index extended to all 118 elements, marked.

Register 837. Two things can be predicted and they are not the same thing:

    EXISTENCE   which (element, charge, l) channels are physical. This follows from
                the index — L.real establishes Lambda's constraints on 247 subshells
                across all 118 elements, 18,288 tests, 0 failures — and costs nothing
                but generation.

    THE DEFECT  what delta such a channel has. This does NOT follow from the index.
                Register 835: Lambda is a recoding and adds nothing; register 834:
                closure coexists with a bracket that holds and one that fails. The
                only route to a predicted defect is INTERPOLATION along an
                isoelectronic sequence, where P.iso is monotone at s and p above
                0.005 (register 773), and that route reaches only elements whose
                sequence neighbours are both measured.

Every generated row is marked with which of the two it carries. A row marked
EXISTS-ONLY is a statement that a channel is there to be measured; it is not a
prediction of any number, and the compendium must not let it read as one.
"""
import re, math, statistics as st
from collections import defaultdict
from zeno import State, step

LM = {"s":0,"p":1,"d":2,"f":3,"g":4,"h":5,"i":6,"k":7}
ZNUM = {"H":1,"He":2,"Li":3,"Be":4,"B":5,"C":6,"N":7,"O":8,"F":9,"Ne":10,"Na":11,
        "Mg":12,"Al":13,"Si":14,"P":15,"S":16,"Cl":17,"Ar":18,"K":19,"Ca":20,
        "Sc":21,"Ti":22,"V":23,"Cr":24,"Mn":25,"Fe":26,"Co":27,"Ni":28,"Cu":29,
        "Zn":30,"Ga":31,"Ge":32,"As":33,"Se":34,"Br":35,"Kr":36,"Rb":37,"Sr":38,
        "Y":39,"Zr":40,"Nb":41,"Mo":42,"Tc":43,"Ru":44,"Rh":45,"Pd":46,"Ag":47,
        "Cd":48,"In":49,"Sn":50,"Sb":51,"Te":52,"I":53,"Xe":54,"Cs":55,"Ba":56,
        "Hg":80,"Tl":81,"Pb":82,"Bi":83}
INV = {v:k for k, v in ZNUM.items()}
ROM = {1:"I",2:"II",3:"III",4:"IV",5:"V"}

def held():
    """what the compendium actually measures: (Z, charge, l) -> mean defect"""
    rows = [l.rstrip().split("\t") for l in open("SPECTRA-DATA.tsv", encoding="utf-8")][1:]
    out = defaultdict(list)
    for r in rows:
        m = re.search(r"n([spdfghik])\b", r[1]); el = re.match(r"([A-Z][a-z]?)", r[0].strip())
        if not (m and el) or el.group(1) not in ZNUM: continue
        try: out[(ZNUM[el.group(1)], int(r[9]), LM[m.group(1)])].append(float(r[7]))
        except Exception: pass
    return {k: st.mean(v) for k, v in out.items()}

def generate(H):
    """every (Z, charge, l) the structure admits, across all 118 elements.

    A channel needs an outer electron in nl bound to a core of charge `charge`,
    which requires Z > charge (an electron must remain). l runs to 7, the highest
    the compendium has measured. Charge runs to 4, the highest it holds.
    """
    out = []
    for Z in range(1, 119):
        for c in range(1, 5):
            if Z <= c: continue            # no electron left to be Rydberg
            for l in range(0, 8):
                out.append((Z, c, l))
    return out

def interpolate(H, cells):
    """where an isoelectronic sequence BRACKETS a missing cell, predict its defect.

    P.iso: for one electron count and one l, the defect falls monotonically as the
    charge rises. If a missing cell has a measured neighbour on each side of the
    same sequence, its defect lies between them — a deductive bracket, not a fit,
    and only at s and p where register 773 established monotonicity above 0.005.
    """
    seq = defaultdict(list)
    for (Z, c, l), d in H.items():
        seq[(Z - c + 1, l)].append((c, d, Z))     # electron count = Z - charge + 1
    out = []
    for (ne, l), v in seq.items():
        if l > 1 or len(v) < 2: continue
        v.sort()
        for c in range(v[0][0] + 1, v[-1][0]):
            if any(x[0] == c for x in v): continue
            lo = max((x for x in v if x[0] < c), key=lambda x: x[0])
            hi = min((x for x in v if x[0] > c), key=lambda x: x[0])
            Z = ne + c - 1
            if not (1 <= Z <= 118): continue
            a, b = sorted((lo[1], hi[1]))
            if b - a < 0.005: continue                # below where P.iso governs
            out.append((Z, c, l, a, b, ne, lo[2], hi[2]))
    return out

with State("predict_channels") as s:
    H     = step(s, "read what the compendium measures", held,            budget=120)
    cells = step(s, "generate every channel the structure admits",
                 lambda: generate(H), budget=300)
    interp= step(s, "interpolate defects where a sequence brackets",
                 lambda: interpolate(H, cells), budget=300)

meas = set(H)
print(f"  CHANNELS ACROSS ALL 118 ELEMENTS\n")
print(f"      generated by the structure   {len(cells):>7}")
print(f"      MEASURED in the compendium   {len(meas):>7}   ({100*len(meas)/len(cells):.1f}%)")
print(f"      EXISTS-ONLY                  {len(cells)-len(meas):>7}   no defect predicted")
print()
print(f"  DEFECTS PREDICTED BY INTERPOLATION — P.iso brackets the cell\n")
print(f"      {len(interp)} cells lie between two measured members of their own")
print(f"      isoelectronic sequence at s or p, so their defect is bracketed.\n")
print(f"  {'element':>9}{'charge':>7}{'l':>3}{'e-':>5}{'bracket on delta':>26}{'from':>14}")
for Z, c, l, a, b, ne, zlo, zhi in sorted(interp)[:20]:
    print(f"  {INV.get(Z,Z):>9}{ROM.get(c,c):>7}{'sp'[l]:>3}{ne:>5}"
          f"{f'{a:.4f} - {b:.4f}':>26}{INV.get(zlo,'')+'/'+INV.get(zhi,''):>14}")
if len(interp) > 20: print(f"  ... and {len(interp)-20} more")
print()
print(f"  Everything else is EXISTS-ONLY: the structure says a channel is there,")
print(f"  and says nothing whatever about its defect (registers 834, 835).")
