#!/usr/bin/env python3
"""close_rebank.py — the guarded RE-BANK of goldens whose instruments now measure a changed volume.

    python3 members/close_rebank.py --old OLD --new NEW --w W-NNN.md
                                    [--append NAME PATH ...] --rebank NAME [NAME ...]

`close.py` builds the compendia bundle and refuses, by design, to let ANY seated member change:
its change set is {WORKING-REGISTER.md, MANIFEST.tsv} plus the --append targets, and each of those
must equal old body + appended text. That is the "no silent change" rule and it is right. It also
assumed a golden never legitimately moves — true while the volumes were frozen under the chat-67
hold, and false the moment a build seats Register entries. Four entries at BUILD92 moved 28 of 86
goldens. This is the missing route, built to close.py's own discipline:

  1. NEW must not exist. Every --rebank NAME must already be a seated member NAME.out.
  2. EACH GOLDEN IS REGENERATED BY RUNNING ITS INSTRUMENT HERE — never copied, never hand-edited.
     The command is gate.py's: SPECIAL[NAME] if listed, else `python3 NAME.py`, run in members/.
     A non-zero exit REFUSES the whole build: an instrument that fails is not re-banked, it is
     superseded by a successor instrument, which is a reading and not a mechanical act.
  3. A golden whose output is unchanged REFUSES the build too — re-banking a golden that did not
     move hides the fact that nothing moved.
  4. The W text is appended to the WORKING-REGISTER.md body and each --append PATH to its member,
     exactly as close.py does, with the same well-formedness assertions.
  5. MANIFEST.tsv is recomputed over both bundles' members.
  6. CHANGE SET: only WORKING-REGISTER.md, MANIFEST.tsv, the --append targets and the named
     goldens differ. Any other member differing refuses the build.
  7. REVERSE GUARD: every re-banked golden is put back, the MANIFEST restored, the appended text
     and the W text stripped, and the result must reproduce the OLD bundle's own md5.
  8. Only then is NEW written.

What this does NOT do: it never edits an instrument, never adds or removes a member, and never
touches a reader-facing volume. Re-banking records that a measurement moved. It does not decide
whether the movement is a finding — that is the reading's, and the reading is in READ-*/W-*.
"""
import sys, os, re, hashlib, subprocess

MEMBER = re.compile(rb'^<<<FILE: (.+?)>>>\n(.*?)<<<END FILE: \1>>>\n', re.S | re.M)
md5 = lambda b: hashlib.md5(b).hexdigest()
H = os.path.dirname(os.path.abspath(__file__))

def arg(k, default=None):
    return sys.argv[sys.argv.index(k) + 1] if k in sys.argv else default
def parse(t):
    ms = [(m.group(1).decode(), m.group(2)) for m in MEMBER.finditer(t)]
    assert len(set(n for n, _ in ms)) == len(ms), 'duplicate member name'
    return ms
def manifest_text(main_members, comp_members):
    rows = ['bundle\tname\tbytes\tmd5\tlines']
    for tag, ms in (('main', main_members), ('compendia', comp_members)):
        for n, b in sorted(ms):
            if n == 'MANIFEST.tsv': continue
            rows.append(f'{tag}\t{n}\t{len(b)}\t{md5(b)}\t{b.count(b"\n")}')
    return ('\n'.join(rows) + '\n').encode('utf-8')
def body_block(name, body):
    return b'<<<FILE: ' + name.encode() + b'>>>\n' + body + b'<<<END FILE: ' + name.encode() + b'>>>\n'

sys.path.insert(0, H)
import importlib.util
_s = importlib.util.spec_from_file_location('gate', os.path.join(H, 'gate.py'))
SPECIAL = {}
try:
    src = open(os.path.join(H, 'gate.py'), encoding='utf-8').read()
    ns = {}
    exec(compile(src[src.index('SPECIAL = {'):src.index('CORE = [')], 'gate-special', 'exec'), ns)
    SPECIAL = ns['SPECIAL']
except Exception as e:
    print('note: could not read gate.py SPECIAL (%s); using `python3 NAME.py` for every name' % e)

old_p, new_p, w_p = arg('--old'), arg('--new'), arg('--w')
main_p = arg('--main', os.path.join(H, '..', 'The_Method_1_6_BUILD92_main_and_register.md'))
appends = [(sys.argv[i + 1], open(sys.argv[i + 2], 'rb').read()) for i, a in enumerate(sys.argv) if a == '--append']
names = sys.argv[sys.argv.index('--rebank') + 1:] if '--rebank' in sys.argv else []
assert old_p and new_p and w_p and names, 'need --old --new --w --rebank'
assert not os.path.exists(new_p), f'{new_p} exists — never overwrite'

old = open(old_p, 'rb').read(); old_ms = parse(old); od = dict(old_ms); old_names = [n for n, _ in old_ms]
main_ms = parse(open(main_p, 'rb').read())
W = open(w_p, 'rb').read()
assert W.startswith(b'### W-') and W.endswith(b'\n\n'), 'W text must begin "### W-" and end with a blank line'

# (1)(2)(3) regenerate every golden by RUNNING its instrument
fresh = {}
for n in names:
    g = n + '.out'
    assert g in old_names, f'{g} is not a seated member'
    cmd = SPECIAL.get(n, ['python3', n + '.py'])
    p = subprocess.run(cmd, cwd=H, capture_output=True)
    assert p.returncode == 0, (f'{n}: exit {p.returncode} — REFUSED. A failing instrument is not '
                               f'a re-bank; it is superseded by a successor.\n' + p.stderr.decode()[-800:])
    body = p.stdout
    assert body != od[g], f'{n}: output is unchanged — REFUSED, there is nothing to re-bank'
    fresh[g] = body
    print(f'  ran {" ".join(cmd):<52} {g:<20} {len(od[g]):>8,} -> {len(body):>8,} B   {md5(od[g])[:8]} -> {md5(body)[:8]}')

# (4) W text and appends into their bodies
end = b'<<<END FILE: WORKING-REGISTER.md>>>\n'; assert old.count(end) == 1
i = old.index(end); assert old[i - 2:i] == b'\n\n', 'WR body must end with a blank line'
new = old[:i] + W + old[i:]
for n, txt in appends:
    e = b'<<<END FILE: ' + n.encode() + b'>>>\n'
    assert n in old_names and new.count(e) == 1, f'--append target {n} not a unique old member'
    assert txt.endswith(b'\n'), f'--append text for {n} must end with a newline'
    j = new.index(e); new = new[:j] + txt + new[j:]

# (5) replace the golden bodies, then the manifest
for g, body in fresh.items():
    ob = body_block(g, od[g]); assert new.count(ob) == 1, f'{g}: body block not unique'
    new = new.replace(ob, body_block(g, body))
man_old = od.get('MANIFEST.tsv')
man = manifest_text(main_ms, parse(new))
ob = body_block('MANIFEST.tsv', man_old); assert new.count(ob) == 1
new = new.replace(ob, body_block('MANIFEST.tsv', man))

new_ms = parse(new); nd = dict(new_ms)
print(f'old {os.path.basename(old_p)}  {len(old):,} B  md5 {md5(old)}  {old.count(b"\n"):,} lines  {len(old_ms)} members')
print(f'new {os.path.basename(new_p)}  {len(new):,} B  md5 {md5(new)}  {new.count(b"\n"):,} lines  {len(new_ms)} members')
print(f'MANIFEST.tsv  {len(man):,} B  md5 {md5(man)}  {man.count(b"\n")} lines;  WORKING-REGISTER.md  {len(nd["WORKING-REGISTER.md"]):,} B  md5 {md5(nd["WORKING-REGISTER.md"])}  {nd["WORKING-REGISTER.md"].count(b"\n"):,} lines')

# (6) change set
allowed = {'WORKING-REGISTER.md', 'MANIFEST.tsv'} | {n for n, _ in appends} | set(fresh)
changed = [n for n in old_names if nd[n] != od[n]]
assert set(changed) <= allowed, f'unexpected change in old members: {sorted(set(changed) - allowed)}'
assert set(fresh) <= set(changed), f'named goldens that did not change: {sorted(set(fresh) - set(changed))}'
assert nd['WORKING-REGISTER.md'] == od['WORKING-REGISTER.md'] + W, 'WR is not old + W'
for n, txt in appends: assert nd[n] == od[n] + txt, f'{n} is not old + appended text'
assert [n for n, _ in new_ms] == old_names, 'member set changed — this tool adds and removes nothing'
print(f're-banked {len(fresh)} goldens; changed old members: {sorted(changed)}; added: none; lines {new.count(b"\n") - old.count(b"\n"):+d}')

# (7) reverse guard
rev = new
rev = rev.replace(body_block('MANIFEST.tsv', man), body_block('MANIFEST.tsv', man_old))
for g, body in fresh.items():
    nb = body_block(g, body); assert rev.count(nb) == 1; rev = rev.replace(nb, body_block(g, od[g]))
for n, txt in reversed(appends):
    e = b'<<<END FILE: ' + n.encode() + b'>>>\n'; assert rev.count(txt + e) == 1; rev = rev.replace(txt + e, e)
assert rev.count(W + end) == 1; rev = rev.replace(W + end, end)
print(f'reverse recovers md5 {md5(rev)}  == old: {md5(rev) == md5(old)}')
assert md5(rev) == md5(old), 'REVERSE GUARD FAILED — nothing written'

open(new_p, 'wb').write(new); print('written', new_p)
