#!/usr/bin/env python3
"""close_census2.py — close_census.py's successor: the census regenerated with ids matched by CONTENT, not by line.

    python3 tools/close_census2.py --dry [--retire ID,ID] [--mark W-NNN] [--save PATH]      run census2.py, match, report; write nothing
    python3 tools/close_census2.py --old OLD --new NEW --w W-NNN.md --main MAIN [--retire ID,ID] [--append NAME PATH ...]

WHY. `close_census.py` keys an id's stability to (class, volume, line). That was the right guard while the volumes were
frozen; the moment a build moved a main-volume line it refused on 1,280 ids at once (DEF-153O), and it has had no route
since. An id is an address cited by every CENSUS-CLOSURES-*.tsv, so it must survive; but the address is the DEFECT — the
class, the member, the item and the words — not the line the defect happened to sit on when the census was first taken.

THE MATCH, in tiers; every pairing below tier 1 is printed in full, with both texts:
  1  exact     (class, member, item, detail) equal — the k-th such old row to the k-th such new row when repeated;
  2  by item   (class, member, item) equal and unique among the rows still unmatched on both sides — the detail changed
               (a site count in a C6 or C8 row, a shifted line quoted in a C13 row);
  3  by text   (class, member, item) equal and the quoted line equal — only the tally prefix of the detail, up to its last
               " | ", changed (a C7 number whose "other sites" grew); k-th to k-th when repeated;
  4  by run    (class, member, item) equal and the two quoted lines share a run of characters containing the item as a whole
               word, at least six characters longer than the item — the line was reflowed or reworded around the same words;
               each old row takes the still-unmatched new row with the longest run, the nearest line breaking ties. The run
               is printed with the pair.
  Nothing else. An old row still unmatched is GONE: its defect does not measure at this build. The tool REFUSES unless every
  GONE id is named in --retire, and a retired row is CARRIED: the seated row verbatim, its detail prefixed
  "RETIRED W-NNN: not measured at this build | ", so that the id every CENSUS-CLOSURES-*.tsv cites still resolves and the row
  says plainly that it is no longer a measurement. A row so marked is carried by its mark on every later regeneration and
  never re-measured; if the defect measures again it is a NEW row with a new id. Retirement is a ruling, never the tool's:
  --retire is typed, and the W text says why. A new row with no match is NEW and takes the next id above the seated
  maximum, in measurement order. For each GONE row the report says whether its quoted line still occurs in the member.
The regenerated census carries the seated ids with their new lines and details, sorted by id; new rows appended. Then
close_census.py's discipline unchanged: the census is REGENERATED BY RUNNING census2.py (never copied; a carried row is the
one exception, and it is carried by a mark the seated member itself bears), the W text goes to WORKING-REGISTER.md,
MANIFEST.tsv is recomputed, the change set is asserted, and the reverse guard must recover the old bundle's md5 before
anything is written. This tool adds and removes no member. --save (dry only) writes the renumbered census to PATH;
--seated PATH (dry only) matches against that file instead of the seated member — run it on a --save output to prove the
regeneration is a fixed point: every row exact, nothing NEW, nothing GONE, the carried rows carried, "== the seated member".
"""
import sys, os, re, hashlib, subprocess, collections, tempfile, shutil
MEMBER = re.compile(rb'^<<<FILE: (.+?)>>>\n(.*?)<<<END FILE: \1>>>\n', re.S | re.M)
md5 = lambda b: hashlib.md5(b).hexdigest()
T = os.path.dirname(os.path.abspath(__file__)); H = T if os.path.basename(T) == 'members' else os.path.join(os.path.dirname(T), 'method', 'members'); HOME = os.path.dirname(H)   # from tools/ or from a seated copy
CENSUS = 'DEFECT-CENSUS.tsv'; RETIRED = 'RETIRED '
F = {'main': 'The_Method_1_6-2.md', 'reg': 'The_Method_1_6___The_Register-2.md', 'mc': 'The_Method_1_6___Mathematical_Compendium-2.md',
     'pc': 'The_Method_1_6___The_Physics_Compendium-2.md', 'ioi': 'The_Method_1_6___The_Index_of_Indices-2.md', 'sc': 'The_Method_1_6___Spectra_Compendium-2.md'}
def arg(k, d=None): return sys.argv[sys.argv.index(k) + 1] if k in sys.argv else d
def parse(t):
    ms = [(m.group(1).decode(), m.group(2)) for m in MEMBER.finditer(t)]
    assert len(set(n for n, _ in ms)) == len(ms), 'duplicate member name'; return ms
def blk(n, b): return b'<<<FILE: ' + n.encode() + b'>>>\n' + b + b'<<<END FILE: ' + n.encode() + b'>>>\n'
def manifest_text(main_ms, comp_ms):
    rows = ['bundle\tname\tbytes\tmd5\tlines']
    for tag, ms in (('main', main_ms), ('compendia', comp_ms)):
        for n, b in sorted(ms):
            if n == 'MANIFEST.tsv': continue
            rows.append(f'{tag}\t{n}\t{len(b)}\t{md5(b)}\t{b.count(b"\n")}')
    return ('\n'.join(rows) + '\n').encode('utf-8')
def rows_of(text):
    out = []
    for line in text.decode('utf-8').splitlines():
        f = line.split('\t')
        if len(f) < 6 or not f[0].isdigit(): continue
        out.append((int(f[0]), f[1], f[2], f[3], f[4], '\t'.join(f[5:])))   # id, class, member, line, item, detail
    return out
def text(d): return d.rsplit(' | ', 1)[-1] if ' | ' in d else d   # the quoted line, after any tally prefix
def run(a, b, item):
    """the longest common substring of a and b containing item as a whole word: (length, string); (0, '') if none."""
    pat = r'(?<!\w)' + re.escape(item) + r'(?!\w)'; best = (0, '')
    for i in (m.start() for m in re.finditer(pat, a)):
        for j in (m.start() for m in re.finditer(pat, b)):
            l = 0
            while i - l > 0 and j - l > 0 and a[i - l - 1] == b[j - l - 1]: l += 1
            r = len(item)
            while i + r < len(a) and j + r < len(b) and a[i + r] == b[j + r]: r += 1
            if l + r > best[0]: best = (l + r, a[i - l:i + r])
    return best
def match(old, new):
    """returns (assign, tiers, gone, fresh): assign[new_index] = old id or None; tiers = [(tier, old_row, new_row, run)]."""
    assign = [None] * len(new); used = set(); tiers = []
    def take(t, o, i, r=''): assign[i] = o[0]; used.add(o[0]); tiers.append((t, o, new[i], r))
    def rest(): return [r for r in old if r[0] not in used], [i for i in range(len(new)) if assign[i] is None]
    for t, key in ((1, lambda r: (r[1], r[2], r[4], r[5])), (3, lambda r: (r[1], r[2], r[4], text(r[5])))):
        if t == 3:   # tier 2 sits between the two grouping tiers
            ro, rn = rest()
            c_old = collections.Counter((r[1], r[2], r[4]) for r in ro); c_new = collections.Counter((new[i][1], new[i][2], new[i][4]) for i in rn)
            idx = {(new[i][1], new[i][2], new[i][4]): i for i in rn}
            for r in ro:
                k = (r[1], r[2], r[4])
                if c_old[k] == 1 and c_new.get(k) == 1: take(2, r, idx[k])
        ro, rn = rest(); g_old = collections.defaultdict(list); g_new = collections.defaultdict(list)
        for r in ro: g_old[key(r)].append(r)
        for i in rn: g_new[key(new[i])].append(i)
        for k, olds in g_old.items():
            for o, i in zip(olds, g_new.get(k, [])): take(t, o, i)
    ro, rn = rest()
    for r in ro:
        cands = []
        for i in rn:
            n = new[i]
            if assign[i] is not None or (n[1], n[2], n[4]) != (r[1], r[2], r[4]): continue
            ln, s = run(text(r[5]), text(n[5]), r[4])
            if ln >= len(r[4]) + 6: cands.append((-ln, abs(int(n[3]) - int(r[3])), i, s))
        if cands: cands.sort(); take(4, r, cands[0][2], cands[0][3])
    gone = [r for r in old if r[0] not in used]; fresh = [i for i in range(len(new)) if assign[i] is None]
    return assign, tiers, gone, fresh
def still_there(r):
    """for a GONE row: what the member holds at this build — the quoted line's whereabouts, or for a C6 row (which quotes
    numbers, not a line) where each missing number now occurs in the volumes."""
    if r[2] not in F: return 'member not a file'
    lines = lambda m: open(os.path.join(H, F[m]), encoding='utf-8').read().split('\n')
    m6 = re.match(r'(\d+) of (\d+): (.*?) \| sources', r[5])
    if r[1].startswith('C6-') and m6:
        L = lines(r[2]); here = 'entry %r still at %s L%s; ' % (r[4], r[2], r[3]) if int(r[3]) <= len(L) and r[4] in L[int(r[3]) - 1] else 'entry not at %s L%s; ' % (r[2], r[3])
        for n in m6.group(3).split():
            hits = ['%s L%s' % (m, ','.join(str(i + 1) for i, l in enumerate(lines(m)) if n in l)[:60]) for m in ('main', 'reg') if any(n in l for l in lines(m))]
            here += '%s now in %s' % (n, '; '.join(hits) if hits else 'no volume')
        return here
    t = text(r[5]); hits = [i + 1 for i, l in enumerate(lines(r[2])) if t and t in l]
    return ('quoted line still at L%s' % ','.join(map(str, hits[:3]))) if hits else 'quoted line no longer in the member'
def regenerate():
    d = tempfile.mkdtemp(prefix='census2-'); out = os.path.join(d, CENSUS)
    p = subprocess.run([sys.executable, 'census2.py', out], cwd=H, capture_output=True)
    assert p.returncode == 0, f'census2.py exit {p.returncode} — REFUSED\n' + p.stderr.decode()[-800:]
    t = open(out, 'rb').read(); shutil.rmtree(d); return t, p.stdout.decode()
def renumber(old_text, fresh_text, retire=(), mark='W-?'):
    old_all, new = rows_of(old_text), rows_of(fresh_text)
    carried = [r for r in old_all if r[5].startswith(RETIRED)]; old = [r for r in old_all if not r[5].startswith(RETIRED)]
    assign, tiers, gone, fresh = match(old, new)
    n_t = collections.Counter(t[0] for t in tiers)
    print(f'  seated {len(old_all):,} rows ({len(carried)} carried as retired) -> regenerated {len(new):,}   exact {n_t[1]:,}   by item {n_t[2]}   by text {n_t[3]}   by run {n_t[4]}   NEW {len(fresh)}   GONE {len(gone)}')
    for t in tiers:
        if t[0] == 1: continue
        print(f'    tier {t[0]}  id {t[1][0]:<5} {t[1][1]} {t[1][2]} L{t[1][3]}->L{t[2][3]}  {t[1][4][:40]!r}' + (f'  run {t[3]!r}' if t[3] else ''))
        print(f'            was: {t[1][5][:110]}\n            now: {t[2][5][:110]}')
    for i in fresh: r = new[i]; print(f'    NEW    {r[1]} {r[2]} L{r[3]} {r[4][:50]!r} | {r[5][:90]}')
    for r in gone: print(f'    GONE   id {r[0]} {r[1]} {r[2]} L{r[3]} {r[4][:50]!r} | {r[5][:90]}\n            {still_there(r)}')
    retire = set(retire); gone_ids = {r[0] for r in gone}
    bad = retire - gone_ids; assert not bad, f'REFUSED: --retire names ids that are matched, carried or unknown: {sorted(bad)}'
    left = gone_ids - retire; assert not left, f'REFUSED: {len(left)} seated census ids have no match and are not named in --retire — a row is never dropped by a regeneration: {sorted(left)}'
    top = max(r[0] for r in old_all); nxt = top; out = {}
    for r in carried: out[r[0]] = r
    for r in gone: out[r[0]] = r[:5] + (f'{RETIRED}{mark}: not measured at this build | ' + r[5],); print(f'    RETIRE id {r[0]} under {mark}')
    for i, r in enumerate(new):
        if assign[i] is None: nxt += 1; assign[i] = nxt
        out[assign[i]] = (assign[i],) + r[1:]
    assert len(out) == len(new) + len(carried) + len(gone), 'id collision'
    lines = ['id\tclass\tmember\tline\titem\tdetail'] + ['%d\t%s\t%s\t%s\t%s\t%s' % out[k] for k in sorted(out)]
    return ('\n'.join(lines) + '\n').encode('utf-8'), n_t, len(fresh), len(gone)
def retire_arg(): return [int(x) for x in arg('--retire', '').split(',') if x]
if __name__ == '__main__':
    if '--dry' in sys.argv:
        seated = open(arg('--seated', os.path.join(H, CENSUS)), 'rb').read(); fresh, log = regenerate(); print(log.strip()[:600])
        text_, *_ = renumber(seated, fresh, retire_arg(), arg('--mark', 'W-?'))
        print(f'  renumbered census {len(text_):,} B md5 {md5(text_)}  {"== the seated member" if text_ == seated else "differs from the seated member"}' + ('' if '--save' in sys.argv else '  (written nowhere: --dry)'))
        if '--save' in sys.argv: open(arg('--save'), 'wb').write(text_); print('  saved', arg('--save'))
        sys.exit(0)
    old_p, new_p, w_p, main_p = arg('--old'), arg('--new'), arg('--w'), arg('--main')
    appends = [(sys.argv[i + 1], open(sys.argv[i + 2], 'rb').read()) for i, a in enumerate(sys.argv) if a == '--append']
    assert old_p and new_p and w_p and main_p, 'need --old --new --w --main'
    assert not os.path.exists(new_p), f'{new_p} exists — never overwrite'
    old = open(old_p, 'rb').read(); old_ms = parse(old); od = dict(old_ms); old_names = [n for n, _ in old_ms]
    assert CENSUS in od, f'{CENSUS} is not a seated member'
    main_ms = parse(open(main_p, 'rb').read()); W = open(w_p, 'rb').read()
    assert W.startswith(b'### W-') and W.endswith(b'\n\n'), 'W text must begin "### W-" and end with a blank line'
    mark = re.match(rb'### (W-\d+)', W).group(1).decode()
    fresh, log = regenerate(); print(log.strip()[:400])
    text_, n_t, newn, gonen = renumber(od[CENSUS], fresh, retire_arg(), mark)
    assert text_ != od[CENSUS], f'{CENSUS} is unchanged — REFUSED, there is nothing to regenerate'
    end = b'<<<END FILE: WORKING-REGISTER.md>>>\n'; assert old.count(end) == 1
    i = old.index(end); assert old[i - 2:i] == b'\n\n', 'WR body must end with a blank line'
    new = old[:i] + W + old[i:]
    for n, txt in appends:
        e = b'<<<END FILE: ' + n.encode() + b'>>>\n'; assert n in old_names and new.count(e) == 1 and txt.endswith(b'\n')
        j = new.index(e); new = new[:j] + txt + new[j:]
    ob = blk(CENSUS, od[CENSUS]); assert new.count(ob) == 1; new = new.replace(ob, blk(CENSUS, text_))
    man_old = od['MANIFEST.tsv']; man = manifest_text(main_ms, parse(new))
    ob = blk('MANIFEST.tsv', man_old); assert new.count(ob) == 1; new = new.replace(ob, blk('MANIFEST.tsv', man))
    new_ms = parse(new); nd = dict(new_ms)
    print(f'old {os.path.basename(old_p)}  {len(old):,} B  md5 {md5(old)}  {old.count(b"\n"):,} lines  {len(old_ms)} members')
    print(f'new {os.path.basename(new_p)}  {len(new):,} B  md5 {md5(new)}  {new.count(b"\n"):,} lines  {len(new_ms)} members')
    allowed = {'WORKING-REGISTER.md', 'MANIFEST.tsv', CENSUS} | {n for n, _ in appends}
    ch = [n for n in old_names if nd[n] != od[n]]; assert set(ch) <= allowed, f'unexpected change: {sorted(set(ch) - allowed)}'
    assert nd['WORKING-REGISTER.md'] == od['WORKING-REGISTER.md'] + W and [n for n, _ in new_ms] == old_names
    for n, txt in appends: assert nd[n] == od[n] + txt
    rev = new.replace(blk('MANIFEST.tsv', man), blk('MANIFEST.tsv', man_old))
    nb = blk(CENSUS, text_); assert rev.count(nb) == 1; rev = rev.replace(nb, blk(CENSUS, od[CENSUS]))
    for n, txt in reversed(appends):
        e = b'<<<END FILE: ' + n.encode() + b'>>>\n'; assert rev.count(txt + e) == 1; rev = rev.replace(txt + e, e)
    assert rev.count(W + end) == 1; rev = rev.replace(W + end, end)
    print(f'reverse recovers md5 {md5(rev)}  == old: {md5(rev) == md5(old)}'); assert md5(rev) == md5(old), 'REVERSE GUARD FAILED'
    open(new_p, 'wb').write(new); print('written', new_p)
