import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R={
"key":"hep-th/0302039#domain",
"name":"Popov: the AHS approximation is derived/established only for asymptotically flat spacetimes",
"source":{
 "located":"arXiv:hep-th/0302039 (A. A. Popov; the tree cites v2, and records reading eqs. (21), (55), (70), (83), Sec. IV, Sec. VI, App. B at hpscentre.py:118-120 during DOCKET 64). NOT re-read in this audit.",
 "read_status":"NAMED-NOT-READ",
 "via":"Every route failed this session and the failures are recorded: alphaXiv get_paper_content(url=https://arxiv.org/abs/hep-th/0302039, fullText=true), answer_pdf_queries(paper='hep-th/0302039', 6 queries) and discover_papers each returned 'alphaXiv assistant quota exceeded'; curl to arxiv.org/pdf/hep-th/0302039v2, export.arxiv.org, api.semanticscholar.org and inspirehep.net returned 'CONNECT tunnel failed, response 403'; WebFetch to arxiv.org and www.alphaxiv.org returned EGRESS_BLOCKED. No cached copy exists anywhere under the scratchpad or /tmp (find -iname '*0302039*' empty; no Popov-2003 text in d67/src). The tree's DOCKET-64 READ status is the tree's record and is NOT re-attested here. The HPS paper (gr-qc/9701064v1) WAS read from the cached text layer d67/src/hps/hps_0.xml for the throat's non-flatness sentence and footnote [20]."},
"published_statement":"NOT QUOTED: Popov's text was not readable in this audit, so no sentence of it is quoted as published. What the TREE records it as saying (hpscentre.py:94-98, 299-301, 118-120): the AHS approximation 'has been DERIVED OR ESTABLISHED' under asymptotic flatness (p.1, eq. (70), Sec. VI); 'Popov (p.2, Sec. IV) shows the high-frequency part, which is the AHS expression, does not depend on the state; asymptotic flatness enters through the low-frequency part'; 'Popov states his (T)^(4) IS the AHS analytic approximation (after eq. (67))'. A re-read must quote p.1, eq. (70) and its surrounding sentence, Sec. IV and Sec. VI verbatim.",
"published_hypotheses":[
 "NOT READ this session. As the tree records them (hpscentre.py:94-98, 118-120, 139): static spherically symmetric spacetime; quantized scalar field of arbitrary coupling xi (tree uses xi = 1/6) and mass (tree uses m = 0); <T> split into high- and low-frequency parts; the high-frequency part = (T)^(4) = the AHS expression, state-independent; the low-frequency part computed under asymptotic flatness (eq. (70), Sec. VI).",
 "Not recorded by the tree and not verifiable here: the quantum state in which the low-frequency part is computed (the tree's own Sec. IV reading implies all state dependence sits in the low-frequency part, so a state hypothesis must accompany AF) and the validity condition on the scale L (eq. (21)), which the tree uses separately as a measurement (hpscentre.py:102-107)."],
"hypothesis_drift":[
 "SCOPE OF 'THE AHS APPROXIMATION' (wording discrepancy inside the tree, not a refutation) -- hpscentre.py:299-301 DOMAIN_WORD says the approximation 'has been DERIVED or established only for asymptotically flat spacetimes', while hpscentre.py:96-98 records Popov's Sec. IV as showing the AHS EXPRESSION is the high-frequency part and that asymptotic flatness enters only through the LOW-frequency part. Machine-checked (z3, rederive C2): the tree's own Sec. IV reading together with R1 = 'the expression was derived only under AF' is UNSAT; with R2 = 'the approximation <T> ~ (T)^(4), i.e. control of the low-frequency remainder, was established only under AF' it is SAT (vacuity guard sat; control sat). So 'derived' over-states on the tree's own reading; 'established' (approximation-to-<T>) is the reading consistent with it. The tree's hpscentre.py:108-109 withdrawal of 'VALIDITY' already moves in this direction.",
 "ADDED STRENGTH: 'ONLY' -- hpscentre.py:94-96, 299-301 and LEDGER.md:85 assert a universal negative over the literature ('derived or established ONLY for AF') on one paper; the original AHS paper, PRD 51 4337, is NOT-REACHED (hpscentre.py:126-132, AHS_REACHED = False at :249) and no later-literature search could be run here. At most the READ support is 'Popov computes the low-frequency part only for AF'; 'only' across all derivations is a NOT-FOUND-elsewhere, not a READ.",
 "DROPPED FROM DOMAIN_WORD: the state hypothesis -- DOMAIN_WORD (hpscentre.py:299-301) names asymptotic flatness alone; on the tree's own Sec. IV reading the state dependence lives in the low-frequency part, so 'established' is also relative to the state in which that part is computed. The state IS named at a different site: linstab.py:417-420 ('not the renormalised <T_ab> of a specified state (AMM (2.9))').",
 "OWNER SET INCOMPLETE IN THE CANONICAL ENTRY: linstab.py:417-420 (HPS_READ_REASON) also rests on hpscentre.DOMAIN_WORD ('it lies outside the domain the approximation is established in'); canonical lists owners = [hpscentre.py], rests_on_it = [O5, specthm R7] only. ledger.py:1746 carries DOMAIN_WORD into LEDGER.md:85.",
 "NO DRIFT (checked): the tree does NOT claim invalidity -- 'nothing here shows it invalid' (hpscentre.py:300-301), 'WITHDRAWN: outside the approximation's domain of VALIDITY' (hpscentre.py:108-109); sub-Planck L is reported as a measurement, not the ground of the verdict (hpscentre.py:102-107, selftest line 113 confirms L is not uniformly sub-Planck)."],
"data_at_publication":[
 {"quantity":"any numerical input to the domain conclusion","value_then":"none -- the result is a statement about the hypotheses under which an expression was derived/established, not a number","value_now":"none","source_now":"n/a (no datum enters)","moves_conclusion":"no -- there is no datum to move"},
 {"quantity":"M_NEGATIVE_FOUND_INSIDE_DOMAIN (tree's data_used)","value_then":"False (DOCKET 64)","value_now":"False -- a RECORD pin, 'printed, not counted' (hpscentre.py:274; selftest section 10, re-run 2026-09-26 SELFTEST OK)","source_now":"rederive/hep-th_0302039_domain.hpscentre-selftest.out line 119","moves_conclusion":"no, but it is not computed: it is the conjunction of this domain claim with the non-flatness of each m<0 instance -- throat: HPS's own sentence 'the metric as a whole is not asymptotically flat' (READ, cached HPS text layer); linear centre: section-8 theorem (selftest ok); nonlinear centre: measured only for c3 K^2 = 1e-4, x <= 300 K and the large-amplitude runs, NONLINEAR_CENTRE_ASYMPTOTICS = OPEN. 'FOUND inside = False' stays true as a not-found; it is not 'none exists inside'."},
 {"quantity":"HPS state parameters (the instance the domain is applied to)","value_then":"m = kappa = 0 (HPS fn [20]: 'We have also set the scalar mass and temperature to zero'); xi = 1/6","value_now":"same (READ, d67/src/hps/hps_0.xml)","source_now":"gr-qc/9701064v1 text layer","moves_conclusion":"no"}],
"rederivation":{
 "method":"z3",
 "script_path":D+"/rederive/hep-th_0302039_domain.py",
 "outcome":"REDERIVE AGREES, 16/16 checks (output rederive/hep-th_0302039_domain.out). C1 sympy: 8 pi/(46080 pi^2) = K^2 = 1/(5760 pi), the unit map used to transcribe Popov (B1)-(B3) against HPS. C2 z3: tree's own Sec. IV reading & 'expression derived only under AF' UNSAT; & 'approximation established only under AF' SAT; vacuity guard and control fire as expected -- a scope finding about a WORD, not physics. C3: the domain clause is carried identically by hpscentre.py and LEDGER.md; ledger.py builds the row from hpscentre. C4: hpscentre.py --selftest re-run read-only (python3.11, PYTHONDONTWRITEBYTECODE=1, 3m21s) ends SELFTEST OK; M_NEGATIVE_FOUND_INSIDE_DOMAIN is a record pin (False); nonlinear non-flatness checked only at c3 K^2 = 1e-4, x <= 300 K; asymptotics OPEN; HPS text layer carries 'the metric as a whole is not asymptotically flat' and fn [20] m = kappa = 0. WHAT IS NOT CHECKED: the domain statement itself -- it is a claim about Popov's text (and, via 'only', about the literature), which could not be read; nothing closed-form stands in for it.",
 "agrees_with_source":"not-run"},
"later_literature":[],
"lacked_data":"Not testable this session in either direction. The result is a SCOPE statement (which hypotheses an approximation was derived/established under), so no measured datum enters its conclusion and none has moved (data_at_publication row 1). The data Popov (2003) would have lacked that could bear on it are exact numerical renormalised <T_ab> in static spherically symmetric spacetimes that are NOT asymptotically flat, against which the AHS (T)^(4) could be compared -- if such comparisons now exist, 'established only for AF' is narrowed (not refuted: 'established' is a claim about the record at a date). Whether they exist could not be searched: discover_papers returned 'quota exceeded'. Evidence against M's hypothesis having purchase here: the tree uses the result only as 'not established', explicitly not 'invalid' (hpscentre.py:108-109, 300-301), so a later extension would move O5 from 'outside the established domain' toward testable, but could not make the tree's statement WRONG as of its reading. Evidence that the original record itself is thin: AHS PRD 51 4337 has never been reached (AHS_REACHED = False), and the massless AHS approximation carries 'an arbitrary parameter whose value cannot be fixed except by experiment' (TSH gr-qc/9608036 as the tree quotes it, hpscentre.py:121-123; NOT re-read here).",
"grade":"OPEN",
"grade_evidence":"The source could not be read at alphaXiv or anywhere else this session (quota exceeded on all three alphaXiv tools; arxiv/export.arxiv/alphaxiv/semanticscholar/inspire refused 403/EGRESS_BLOCKED; no cached copy), so the statement cannot be graded STANDS -- the tree's DOCKET-64 READ is its own record and is not re-attested -- and nothing here refutes it, so not WRONG. What is checkable agrees (rederive 16/16; owner selftest OK). One discrepancy is recorded, not repaired: on the tree's OWN reading of Popov Sec. IV, DOMAIN_WORD's 'derived ... only for asymptotically flat spacetimes' is inconsistent (z3 UNSAT) if 'the AHS approximation' means the expression (T)^(4); it is consistent only as 'the approximation <T> ~ (T)^(4) is established (low-frequency part computed) only for AF'. Two further scope items: 'only' is a universal negative resting on one paper with AHS NOT-REACHED; DOMAIN_WORD omits the state hypothesis that linstab.py:417-420 names. These point toward NARROWED of the wording, but a NARROWED grade requires Popov's own sentence, which was not read.",
"what_would_change_the_grade":"Re-read hep-th/0302039 when the alphaXiv quota resets: answer_pdf_queries(paper='hep-th/0302039', queries=[abstract verbatim; p.1 sentence on asymptotic flatness; eq. (70) and its sentence; Sec. IV high/low split and what it assumes; Sec. VI verbatim; the state in which the low-frequency part is computed; eq. (21) validity condition]). -> STANDS if Popov says the approximation (expression and its use for <T>) is justified only for AF and the tree's reading of Sec. IV is confirmed with 'derived' read as 'established'; -> NARROWED if Popov restricts only the low-frequency computation (e.g. as one worked case) to AF, or ties it to a named state, so that 'derived ... only for AF' over-states; -> NARROWED ('only') if AHS PRD 51 4337 or a later paper establishes the approximation (comparison with exact numerics) in a non-asymptotically-flat static spherically symmetric spacetime; -> WRONG only if Popov's text shows the tree's Sec. IV reading itself inverted (AF entering the high-frequency part) AND something shown here depends on it.",
"reverify_command":"python3 /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/rederive/hep-th_0302039_domain.py   # uses the recorded selftest output; to refresh it: cd /tmp && PYTHONDONTWRITEBYTECODE=1 python3 /home/user/Claude-Method-Works/research/warp-drive/hpscentre.py --selftest > /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/rederive/hep-th_0302039_domain.hpscentre-selftest.out",
"report_path":D+"/audits/hep-th_0302039_domain.json"}
json.dump(R,open(R["report_path"],"w"),indent=1,ensure_ascii=False)
print("written",R["report_path"])
