import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/"
S=D+"rederive/teleportation-transfers-state-not-matter.py"
r={
"key":"teleportation-transfers-state-not-matter",
"name":"Teleportation transfers a quantum state onto matter already at the destination; no mass or energy moves",
"source":{
 "located":"Bennett, Brassard, Crepeau, Jozsa, Peres, Wootters, 'Teleporting an unknown quantum state via dual classical and Einstein-Podolsky-Rosen channels', Phys. Rev. Lett. 70, 1895 (1993) -- no arXiv copy; alphaXiv resolved the title to Boschi et al. instead. Restated in: Pirandola, Eisert, Weedbrook, Furusawa, Braunstein, 'Advances in quantum teleportation', arXiv:1505.07831 (2015), p.1-3 and p.7; Boschi, Branca, De Martini, Hardy, Popescu, arXiv:quant-ph/9710013 (PRL 80, 1121, 1998), p.1-2, which quotes Bennett's abstract. The energy clause is read at source in Hotta, 'Quantum Energy Teleportation: An Introductory Review', arXiv:1101.3954 (2011), p.4 (standard teleportation), sec.3 p.18-24 (the minimal QET model), and in Ikeda, arXiv:2301.02666v5 (PRApplied 20, 024051, 2023), p.1-4 and Table II.",
 "read_status":"READ-VIA-RESTATEMENT",
 "via":"alphaXiv answer_pdf_queries on 1505.07831, quant-ph/9710013, 1101.3954 (two calls), 2301.02666 and 2601.18718. Bennett 1993 itself is NAMED-NOT-READ: its content is taken only from the restatements quoted below."},
"published_statement":"Bennett 1993 as quoted by Boschi et al. (quant-ph/9710013 p.1-2): an unknown quantum state can be \"disassembled into, then later reconstructed from, purely classical information and purely nonclassical Einstein-Podolsky-Rosen (EPR) correlations.\" Pirandola et al. 2015 (p.1): \"an unknown quantum state of a physical system is measured and subsequently reconstructed or 'reassembled' at a remote location (the physical constituents of the original system remain at the sending location). This process requires classical communication and excludes superluminal communication. Most importantly, it requires the resource of quantum entanglement.\" Pirandola p.1-2 on the protocol: Alice and Bob \"share two qubits, A and B, prepared in a pure entangled state\"; Alice makes a Bell detection on a and A; Bob's qubit B \"is simultaneously projected onto P_k^dagger rho P_k\"; Alice \"communicates the classical outcome k to Bob, who then applies P_k to recover the original input state rho\"; \"Alice's input state is assumed to be unknown, otherwise the protocol reduces to remote state preparation.\" ENERGY (Hotta 2011 p.4, not a Bennett claim): standard teleportation \"is not sufficient to teleport energy by itself. Transfer of an excited state to a distant point requires preparation in advance of the same amount of energy of the state at the point\"; in his qubit example the energy b \"must be provided by an external operation device of Bob with a battery\"; \"available energy for Bob moves around the region of Bob without any increase of its total amount. No energy is teleported in this case.\" He then states the exception (p.4-5, p.15-16): Quantum Energy Teleportation (QET) achieves \"effective energy transportation simply via local operations and classical communication\" by \"extracting zero-point energy of entangled many-body systems\", with E_A >= E_B (p.16).",
"published_hypotheses":[
 "H1 (Bennett, via Pirandola p.1-2): Alice and Bob already share an entangled pair (ideally maximally entangled); Bob's half B is at the destination before the protocol runs.",
 "H2: two classical bits per qubit (d^2 outcomes for dimension d) reach Bob through an ordinary classical channel; no superluminal communication (Pirandola p.1).",
 "H3: the input state is UNKNOWN to Alice; a known state reduces to remote state preparation (Pirandola p.2).",
 "H4: Bob's system has a Hilbert space that can carry the state (qubit to qubit; for dimension d a d-dimensional receiver; CV for optical modes). Same species is NOT required: light-to-matter and matter-to-matter teleportation are reported (Pirandola p.7, Sherson 2006, Krauter 2013).",
 "H5 (Pirandola p.1): the physical constituents of the input system stay at the sending location.",
 "H6 (energy, Hotta p.4): for standard teleportation with no interaction between Alice's and Bob's systems, the energy of the teleported state is supplied or absorbed locally by Bob's device.",
 "H7 (the QET exception, Hotta sec.3-5; Ikeda 2023): if the medium joining A and B is an interacting many-body system in an entangled ground state, local operations plus classical communication let Bob extract E_B > 0 from local zero-point fluctuations, with E_B <= E_A; what is sent is classical information, not energy (Ikeda p.1)."],
"hypothesis_drift":[
 "WEAKENED (added hypothesis) -- transit.py:57-59 and transit.py:260-263: 'an identical stock of matter must already be there -- and that had to travel.' The source needs a receiver whose Hilbert space can hold the state and which is entangled with Alice's system (H1, H4). That receiver need not be the same species: Pirandola p.7 reports light-to-matter teleportation (a coherent optical state into a collective spin of ~10^12 Cs atoms). It also need not have travelled from the source. What must cross D at <= c is whatever carried the entanglement, and that can be photons: Pirandola p.7 panels c-d report ions and atoms entangled through emitted photons, and p.3 describes entanglement swapping. transit.py:46-47 itself states the correct form ('A Bell pair spanning distance D required something to cross D at <= c beforehand'). Within the tree, stockgate.py:801 GATE treats the stock as 'a CONDENSED body ... holding at least M(p,s) * m_payload of accessible mass' within the arrival aperture, which is feedstock found at the destination, not matter that travelled. This is recorded as a discrepancy inside the tree; nothing is repaired.",
 "WEAKENED (scope) -- transit.py:56-58: 'onto matter ALREADY AT THE DESTINATION'. The receiver can be a field mode, such as an optical mode in CV teleportation (Pirandola p.2), which is not matter in the massive sense. The conclusion that a physical receiver must be pre-positioned is unaffected.",
 "DROPPED (qualifier) -- transit.py:58 and 261-262: 'It moves no mass and no energy' / 'No energy moves'. This is stated without condition. The source that supports it (Hotta p.4) supports it for standard teleportation between non-interacting systems (H6). Hotta also names the exception H7 (QET), in which LOCC produces effective energy transfer E_B > 0 in a ground-state-entangled medium already spanning A and B. The canonical entry records this as a hypothesis ('energy transfer by quantum energy teleportation is not addressed here'), and ledger.py:250-251 folds QET into DOCKET 66, still not run, with its literature 'CITED, not READ' (ledger.py:807-810). The owner sentence carries no such qualifier.",
 "DROPPED (cost) -- Hotta p.4: the energy of the teleported state 'requires preparation in advance of the same amount of energy of the state at the point'. transit.py puts a destination requirement on matter only. The destination energy requirement goes unstated, and stockgate.GATE (stockgate.py:801) prices accessible mass, not the state's excitation energy. This is a cost the tree does not carry, not a refutation.",
 "ADDED (none of its own) -- transit.py:155 CARRIES_SUBSTANCE = False is a declared constant with no source cited (canonical status 'none (declared)'). This audit supplies the source (Pirandola p.1, H5). The constant agrees with it."],
"data_at_publication":[
 {"quantity":"numerical inputs to the theorem","value_then":"none. Bennett 1993 is a theorem of finite-dimensional quantum mechanics, and its conclusion depends on no measured constant","value_now":"none","source_now":"Pirandola 2015 p.1-2 (restatement)","moves_conclusion":"no. There is no datum to move"},
 {"quantity":"classical bits per teleported qubit","value_then":"2 (Bennett 1993, restated by Pirandola p.2: d^2 outcomes, d=2)","value_now":"2; re-derived symbolically here, four outcomes each with p = 1/4","source_now":"rederive script PART 1; transit.py CLASSICAL_BITS_PER_QUBIT = 2","moves_conclusion":"no"},
 {"quantity":"classical (measure-prepare) fidelity benchmark","value_then":"2/3 (Massar-Popescu 1995, which postdates Bennett)","value_now":"F_class = 2/3 for qubits; CV coherent states 1/2, no-cloning threshold 2/3","source_now":"Pirandola 2015 p.2-3","moves_conclusion":"no. It bounds fidelity, not what is transferred"},
 {"quantity":"experimental confirmation","value_then":"none in 1993 (first photonic demonstrations 1997-98: Bouwmeester, Boschi S = 0.831 +/- 0.009 against a classical 3/4)","value_now":"many platforms, including matter-to-matter (trapped ions 1 m, Rb atoms 21 m, Cs ensembles) and free-space 143 km (Ma 2012). The 1,400 km satellite figure is NAMED-NOT-READ here","source_now":"Pirandola 2015 p.1, p.7; Boschi quant-ph/9710013 p.8-9","moves_conclusion":"no. In every experiment the receiver system was pre-positioned and the input's constituents stayed at the sender"},
 {"quantity":"energy extractable at the destination by LOCC (QET minimal model, units of the coupling)","value_then":"not known in 1993: QET was proposed in 2008","value_now":"E_B/E_A = 0.0049, 0.162, 0.114, 0.024, 0.250 at (h,k) = (1,0.1), (1,1), (1.5,1), (3,0.7), (0.2,5), computed here. Ikeda's analytical <E_1> reproduced to 4 decimals (-0.0049, -0.0180, -0.0726, -0.1147, -0.1425). Hardware observed <E_1> < 0 after error mitigation, e.g. -0.1079 +/- 0.0140 (ibmq_jakarta, h=1.5, k=1). For gapped unique-ground-state lattices the extractable energy is bounded by C e^{-mu d} (Haque 2026, single-author v1)","source_now":"Hotta arXiv:1101.3954 eqs. (8), (11), (14); Ikeda arXiv:2301.02666 Tables II, IV; Haque arXiv:2601.18718 eq. (17); rederive script PART 3","moves_conclusion":"it moves the unqualified 'no energy moves' clause, not CARRIES_SUBSTANCE or BEATS_LIGHT. QET energy is drawn at B from B's own zero-point fluctuation, needs a correlated medium already spanning A-B, has E_B <= E_A, and arrives no faster than the classical bits (<= c)"}],
"rederivation":{"method":"sympy","script_path":S,
 "outcome":"34/34 checks pass, exit 0. PART 1: Bennett teleportation for arbitrary (a,b), symbolic. Each of the four Bell outcomes has p = 1/4 for every normalised input, and the Pauli-corrected output equals the input exactly. PART 2: uncoupled H = w*sz per qubit. Bob's energy in the Bell state is 0. Alice's Bell measurement with the bits withheld changes Bob's average energy by exactly 0 (and a random 4x4 Alice unitary moves it by at most 3.7e-16). After his correction Bob's energy is w(|a|^2-|b|^2), produced by his own local unitary, so his device supplies or absorbs it: no energy crosses the channel, as Hotta p.4 says. PART 3: Hotta's minimal QET model. <g|H_A|g> = <g|H_B|g> = <g|V|g> = 0 symbolically; H|g> = 0 at six exact-rational points to 50 digits (sympy.simplify does not close the nested radicals symbolically, so this one check is numeric); H >= 0; E_A = h^2/sqrt(h^2+k^2) (eq. 8) symbolically; Alice's measurement leaves <H_B> and <V> at 0; E_B(theta) equals eq. (14) symbolically; eq. (14) at eqs. (9)-(10) equals eq. (11); Ikeda's Table II analytical <E_1> is reproduced at all five (h,k); 0 < E_B <= E_A at five points; twenty random alpha-independent Bob unitaries extract <= 0 (best -0.111), which is Hotta eq. (13). Not machine-checkable: 'no mass moves' is structural. Every operation in the protocol is a local map on a fixed tensor factor, so which systems sit where is an input of the model, not an output that can be computed.",
 "agrees_with_source":"yes"},
"later_literature":[
 {"ref":"Pirandola, Eisert, Weedbrook, Furusawa, Braunstein, arXiv:1505.07831 (Nat. Photon. 2015)","effect":"confirms","what":"Review of two decades of theory and experiment. Teleportation reconstructs the state at a remote location while 'the physical constituents of the original system remain at the sending location'; it needs a classical channel and pre-shared entanglement. Its light-to-matter and matter-to-matter experiments narrow the tree's 'identical stock' wording.","read_status":"READ (p.1-3, p.7, refs p.11-12)"},
 {"ref":"Boschi, Branca, De Martini, Hardy, Popescu, arXiv:quant-ph/9710013 (PRL 80, 1121, 1998)","effect":"confirms","what":"Quotes Bennett's abstract and demonstrates teleportation with S = 0.831 +/- 0.009 against the classical limit 3/4.","read_status":"READ (p.1-10)"},
 {"ref":"Hotta, arXiv:1101.3954 (2011), QET introductory review; QET first proposed 2008 (PLA 372, 5671; PRD 78, 045006, NAMED-NOT-READ)","effect":"narrows","what":"Confirms that standard teleportation teleports no energy (p.4). Establishes that LOCC on a ground-state-entangled interacting medium extracts E_B > 0 at B with E_B <= E_A, from local zero-point fluctuations. This is a named exception to the tree's unqualified 'no energy moves', and it moves no matter.","read_status":"READ (p.1, 3-6, 12-24, 26-28, 31-40, 41-49)"},
 {"ref":"Ikeda, arXiv:2301.02666v5 (PRApplied 20, 024051, 2023)","effect":"extends","what":"Implements the minimal QET model on IBM superconducting hardware and observes negative <V> in every configuration, with <E_1> < 0 only after error mitigation, and not at every (h,k) or on every backend (Table IV). States that 'it is classical information, not energy, that is sent'. Cites an NMR verification (Rodriguez-Briones et al., PRL 130, 110801, 2023, NAMED-NOT-READ).","read_status":"READ (p.1-5, 10-13)"},
 {"ref":"Haque, arXiv:2601.18718v1 (2026)","effect":"narrows","what":"For finite-range gapped lattice Hamiltonians with a unique ground state, the energy extractable at distance d is bounded by C e^{-mu d} (eq. 17). This further limits QET's reach. DISCREPANCY, recorded and not repaired: the abstract writes '|E_A - E_B| <= C e^{-mu d}', while the body defines E_B as the post-protocol excess energy and bounds DeltaE := E_A - E_B, the extraction. The two readings differ in notation only. Single-author v1; refereeing status not read.","read_status":"READ (p.1-4)"},
 {"ref":"discover_papers results named but not read: arXiv:2505.04689 (QET review 2025), arXiv:2504.05353 (timelike QET), arXiv:2411.08927, arXiv:0803.0348","effect":"extends","what":"The QET line continues. None of the abstracts read in the discovery listing claims transfer of matter or superluminal energy transfer.","read_status":"NAMED-NOT-READ (abstract snippets only)"}],
"lacked_data":"Bennett et al. 1993 is a theorem with no numerical inputs. What its authors lacked in 1993 was experiment (the first demonstrations came in 1997-98) and QET (2008; hardware and NMR demonstrations in 2023). Evidence that the experiments do not change the conclusion: every platform in Pirandola 2015 (photons, optical modes, atomic ensembles, trapped ions and atoms, solid state) pre-positioned the receiver and left the input's constituents at the sender, which confirms H1 and H5. Evidence that QET changes something: it moves the tree's energy clause, which is not Bennett's claim (Bennett is NAMED-NOT-READ here; the 'no energy' gloss is supported at source only by Hotta p.4, and only for non-interacting systems). QET shows that LOCC can deliver E_B > 0 at the destination, computed here in the minimal model and reproduced against Ikeda's table. It does not change the conclusions the tree draws. The energy comes from B's own local zero-point fluctuations in a medium that must already span A-B, E_B <= E_A, the bits travel at <= c, and for gapped systems E_B decays exponentially with separation (Haque 2026). No matter moves, so CARRIES_SUBSTANCE = False and BEATS_LIGHT = False are untouched. So later data narrows the tree's paraphrase and does not overturn the result. M's hypothesis ('previous physicists may have lacked certain data') is borne out for the energy clause as the tree states it, and not for the state-not-matter core.",
"grade":"NARROWED",
"grade_evidence":"CORE STANDS. Teleportation transfers a state onto a pre-positioned receiver; the input's constituents stay at the sender (Pirandola p.1, READ); two classical bits cross at <= c. This is re-derived symbolically (PART 1, 8/8) and consistent with every experiment in the review. NARROWED on three counts, each shown here. (1) 'It moves no mass and no energy' holds for standard teleportation between non-interacting systems: PART 2 computes that Alice's measurement changes Bob's energy by exactly 0 and that Bob's own device pays w(|a|^2-|b|^2), as Hotta p.4 says. The sentence carries no qualifier, and Hotta's QET (PART 3, 22/22 including Ikeda's table) gives E_B > 0 at the destination by LOCC in a ground-state-entangled medium. The tree names this as unaddressed, with DOCKET 66 not yet run. (2) 'an identical stock of matter ... had to travel' adds a hypothesis the source does not carry. The receiver need not be the same species (light-to-matter, Pirandola p.7), and only the entanglement carrier, possibly photons, must have crossed at <= c. transit.py:46-47 and stockgate.py:801 GATE (a condensed body at the destination) themselves use the weaker, correct form. (3) The destination must also supply the teleported state's energy (Hotta p.4), and the tree does not price it. None of the three reaches CARRIES_SUBSTANCE = False, BEATS_LIGHT = False or the zero advantage over light, which is what R11, Rec and M-S1A-P5 consume. Not WRONG: no counterexample to 'state, not substance' exists or is shown.",
"what_would_change_the_grade":"-> STANDS if the owner sentence is read, or annotated, as scoped to standard (Bennett) teleportation between non-interacting systems, with 'identical ... had to travel' read as 'a suitable receiver, pre-positioned, whose entanglement with the sender was carried at <= c'. -> OPEN on the energy clause if DOCKET 66 finds a QET variant whose E_B is not bounded by E_A or by a local zero-point budget; none is known from the papers read here. -> WRONG only if a protocol were shown to transfer rest mass or conserved particle number by LOCC plus pre-shared entanglement. No such result is known, and it would contradict the tensor-product locality every paper read here assumes. Reading Bennett 1993 at source could only change source.read_status, since the restatements quote its abstract.",
"reverify_command":"python3 "+S+"   # expect 'ALL CHECKS PASS', exit 0 (34 checks); plus: sed -n 56,59p /home/user/Claude-Method-Works/research/warp-drive/transit.py; sed -n 801,803p /home/user/Claude-Method-Works/research/warp-drive/stockgate.py; sed -n 250,252p /home/user/Claude-Method-Works/research/warp-drive/ledger.py",
"report_path":D+"audits/teleportation-transfers-state-not-matter.json"}
json.dump(r,open(r["report_path"],"w"),indent=1)
print("written")
