import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep={
"key":"misner-sharp-hernandez-evolution-equations",
"name":"Misner-Sharp / Hernandez-Misner mass-flux and evolution equations (MS-r, MS-t, EV-U, EV-W, EV-U'), in particular D_t Gamma = 4 pi R j + U D_r Phi, as used by nonstatic.py, driven.py, foliation.py",
"source":{
 "located":"C. W. Misner & D. H. Sharp, Phys. Rev. 136, B571 (1964) and W. C. Hernandez & C. W. Misner, Astrophys. J. 143, 452 (1966): no arXiv copies. Read via exact restatements: (i) I. Musco, J. C. Miller & L. Rezzolla, arXiv gr-qc/0412063 (CQG 2005), sec. 2.1 eqs (1),(4)-(14) 'formulations ... given by Misner & Sharp (1964) [40]' (comoving perfect fluid, p = p(e)) and sec. 2.2 eqs (15)-(27) 'Hernandez & Misner [34]' observer-time forms; (ii) L. Herrera, N. O. Santos & A. Wang, arXiv 0810.1083 (PRD 78, 084026, 2008), sec. 2-3 eqs (1),(2),(6),(12)-(18),(25)-(31),(37): 'the mass function m(t,r) introduced by Misner and Sharp [9]' and 'following Misner and Sharp [9], the proper time derivative D_T', generalised to a dissipative anisotropic comoving fluid with heat flux q. Also read: Herrera et al. gr-qc/0403006 (noncomoving, Schwarzschild-like coordinates, eqs 1-15) as background.",
 "read_status":"READ-VIA-RESTATEMENT",
 "via":"alphaXiv answer_pdf_queries on gr-qc/0412063 (pp.1,3-4,6-12), 0810.1083 (pp.1-24, full), gr-qc/0403006 (pp.1-29). Misner-Sharp 1964 and Hernandez-Misner 1966 themselves NAMED-NOT-READ."
},
"published_statement":"MMR gr-qc/0412063 p.7-8 (restating MS 1964): metric ds^2 = -a^2 dt^2 + b^2 dr^2 + R^2 dOmega^2 (comoving, Lagrangian), D_t = (1/a) d/dt, D_r = (1/b) d/dr, U = D_t R, Gamma = D_r R; for p = p(e): (9) D_t U = -[Gamma/(e+p) D_r p + M/R^2 + 4 pi R p]; (12) D_r a = -a/(e+p) D_r p; (13) D_r M = 4 pi Gamma e R^2; (14) Gamma^2 = 1 + U^2 - 2M/R. Hernandez-Misner (MMR p.9-10): f du = a dt - b dr, D_k = (1/b) d/dr across the null slice, D_r = D_k - D_t (20); (25) D_k M = 4 pi R^2 [e Gamma - p U]; (26) Gamma = D_k R - U. HSW 0810.1083 (dissipative anisotropic generalisation, comoving, ds^2 = -A^2dt^2 + B^2dr^2 + R^2dOmega^2): (14) 8 pi T_01 = -8 pi (q+eps) A B = -2(Rdot'/R - Bdot R'/(B R) - Rdot A'/(R A)); (18) m = (R/2)[(Rdot/A)^2 - (R'/B)^2 + 1]; (28) E = R'/B = (1 + U^2 - 2m/R)^{1/2}; (30) D_T m = -4 pi [(P_r + eps - 4 eta sigma/3) U + (q+eps) E] R^2; (31) D_R m = 4 pi [mu + eps + (q+eps) U/E] R^2 with D_R = (1/R') d/dr; (37) D_T U = -m/R^2 - 4 pi (P_r + eps - 4 eta sigma/3) R + E a, a = A'/(AB). No published source read here writes a separate D_T Gamma equation; in these sources it is the content of the tr (momentum-constraint) Einstein equation (HSW eq.14).",
"published_hypotheses":[
 "spherical symmetry; four-dimensional general relativity, G_ab = 8 pi T_ab, no cosmological constant (MMR p.18: Lambda is included only by adding e_v = Lambda/8pi, p_v = -Lambda/8pi to e and p)",
 "diagonal metric -a^2dt^2 + b^2dr^2 + R^2dOmega^2 with R the areal (circumference) radius; MS: coordinates COMOVING with the fluid (Lagrangian labels, r = rest mass mu inside the shell, MMR eq.2-3)",
 "MS 1964 as restated by MMR: perfect fluid with one-parameter equation of state p = p(e) (MMR p.8 'For one-parameter equations of state')",
 "HSW generalisation: anisotropic pressure (P_r != P_perp), heat flux q, null radiation eps, shear viscosity eta, still comoving",
 "Hernandez-Misner: outgoing null ('observer time') slicing, integrating factor f; perfect fluid",
 "for m = integral of density: regular centre m(0) = 0 (HSW eq.32)",
 "HSW: A, B, R positive (HSW p.4); D_R = (1/R') d/dr requires R' != 0"
],
"hypothesis_drift":[
 "BROADENED, and supported: MS/HSW comoving fluid frame -> the tree's EULERIAN (slice-normal) frame with arbitrary anisotropic T and radial energy flux j = -T_ab u^a n^b (nonstatic.py:56-62, 66-70). Re-derived here from an independently coded Einstein tensor (C1a-e, all residual 0), and mapped onto HSW (14),(28),(30),(31),(37) with A = e^Phi, B = e^Lambda, q = j, eps = eta = 0 (C3a-b, C4a-d) and onto MMR (9),(12),(13),(14) at j = 0 using the radial conservation law nabla_a T^a_r = p' + (rho+p)Phi' computed here (C5a-d). No harm: the tree's five lines are identities for ANY diagonal slicing once T is defined as G/8pi.",
 "ADDED by the tree, and correct: EV-W 'D_t W = 4 pi R j + U D_r Phi' (nonstatic.py:69, driven.py:238-242, foliation.py:338-341) does not appear as a separate line in MMR or HSW; it is exactly the momentum constraint HSW eq.(14): EV-W residual = -(R e^{-Phi-Lambda}/2)(G_tr - 8 pi T_tr) (C2c, C3a). It is also IMPLIED by the definition of m plus EV-U plus MS-t wherever W != 0 (C7a).",
 "COUNTED TWICE (discrepancy, not an error): nonstatic.py:69-70 lists EV-W and EV-U' as two equations; their difference (D_tW - U D_rPhi) - (D_rU - W D_tLambda) vanishes identically with no field equation used (C2a-b): they are one equation (the tr component), written with the mixed partial taken in the two orders. No owner is found here to rely on their independence.",
 "UNSTATED (nonstatic.py:297 'T = Ein / (8 pi)'): no cosmological constant, or equivalently vacuum energy absorbed into rho and p_r. With G + Lambda g = 8 pi T^matter: EV-W is UNCHANGED (g_tr = 0; C10a), MS-r gains + Lambda R^2 W/2, MS-t gains + Lambda R^2 U/2, EV-U gains + Lambda R/2 with m the full MS mass (C10b-e). The load-bearing EV-W is Lambda-independent; at the Proxima span Lambda R^3/6 = 8.05e-7 M_sun against the 2.72e13 M_sun bill (N3).",
 "UNSTATED: four-dimensional general relativity. The tree's identities hold for T := G/8pi in any theory, but reading rho, p_r, j as matter requires GR; in f(R) and scalar-tensor gravity a quasi-local MS energy exists only under a constraint (Cai, Cao, Hu & Ohta 0910.2387, eq.3.7/3.13). Named, not load-bearing inside a GR-only tree.",
 "DROPPED at the use site nonstatic.py:87 'geodesic slicing (Phi = 0, always available)' (also driven.py:239-241, foliation.py:338-341): with zero shift and Phi = 0 the coordinates are Gaussian normal, which exist only up to the first focal point of the slice-normal congruence. Shown here: contracting Milne has R = -t sinh chi -> 0 at t -> 0- for every chi (C9a): all normals meet at one event a finite proper time from the slice, while W = cosh chi is still constant (C9b). So 'always available' holds LOCALLY. The tree's witnesses (expanding Milne, open FRW; C8d-e) are global to the future and the verdict SUSTAINING_FORCES_NEGATIVE_RHO = False does not move; 'holding Gamma costs no flux' (driven.py:240-241) holds for as long as the geodesic slicing exists.",
 "OVER-READING (discrepancy): nonstatic.py:82-83 'The contraction variable does not know the energy density exists.' Literally true of EV-W's time derivative (neither rho nor p_r appears; C1d, C7a), but rho constrains W on every slice through W^2 = 1 + U^2 - 2m/R and MS-r D_r m = 4 pi R^2 (rho W + j U) (C4a, C1a). The tree's conclusion (sustaining does not force rho < 0) rests on its exact witnesses, not on this sentence.",
 "HYPOTHESIS MISMATCH BETWEEN OWNERS (recorded, not adjudicated): foliation.py:338-341 says E = R dGamma is obtained with U D_r Phi 'set to zero by choosing geodesic slicing'; nonstatic.py:178-184 derives it with '(R held fixed)', i.e. U = 0 along the integration, which zeroes that term in ANY slicing (C11) and makes 'exactly' hold only if R is fixed. At U = 0, Gamma = sqrt(1 - 2m/R) is a scalar (C12a-b; foliation.py:803 O2 states the same floor), so dGamma != 0 there needs dm != 0 (dm = -R(W_f^2 - W_i^2)/2 at fixed R, = -1.5R for W 1 -> 2; C11b), while foliation.py's V13 comparison (foliation.py:343-347, Gamma to 7071 at m = 0) necessarily has U ~ Gamma != 0. Geodesic slicing AND U = 0 held together force m = -4 pi R^3 p_r (C12c). Whether BUILD_BILL_IS_GAUGE_CONDITIONAL (foliation.py:868) survives this reading is a question for the owners; nothing is repaired here."
],
"data_at_publication":[
 {"quantity":"numerical inputs of the MS / HM / EV equations themselves","value_then":"none: the equations are identities of the Einstein tensor plus definitions (MS 1964, HM 1966)","value_now":"none","source_now":"re-derived here (C1-C2), no datum enters","moves_conclusion":"no -- nothing to move"},
 {"quantity":"cosmological constant Lambda (absent from MS 1964; measured 1998)","value_then":"0 (assumed; unmeasured)","value_now":"~1.1e-52 m^-2 (Planck-2018-type value, NAMED-NOT-READ in this audit)","source_now":"not re-read here; used only for an order-of-magnitude bound","moves_conclusion":"no -- EV-W is exactly Lambda-independent (C10a); in MS-r/MS-t/EV-U it adds Lambda R^2 W/2 etc. (C10b-d), = 8.05e-7 M_sun at the Proxima span vs 2.72e13 M_sun (N3); a 10^6 error in Lambda would not move it"},
 {"quantity":"G (tree: gauge bill E = R dGamma c^2/G)","value_then":"6.67430e-11 m^3 kg^-1 s^-2 (tree, foliation.py G_NEWTON)","value_now":"6.67430(15)e-11 (CODATA 2018; unchanged in CODATA 2022 -- not re-read at source here)","source_now":"CODATA (NAMED-NOT-READ)","moves_conclusion":"no -- using IAU 2015 nominal GM_sun = 1.3271244e20 directly instead of G*M_sun gives 2.720730782e13 vs 2.720744289e13 (rel. -5.0e-6; N section)"},
 {"quantity":"M_sun (tree 1.98840e30 kg)","value_then":"1.98840e30 kg","value_now":"GM_sun (IAU 2015 B3 nominal) / G = 1.98841e30 kg","source_now":"IAU 2015 B3 (NAMED-NOT-READ)","moves_conclusion":"no -- 5e-6 relative"},
 {"quantity":"Proxima distance (tree 4.2465 ly, 'Gaia DR3 parallax distance')","value_then":"4.2465 ly","value_now":"parallax 768.0665 +- 0.0499 mas -> 4.24646 ly (value quoted from memory; NOT re-read at source in this audit)","source_now":"Gaia DR3 (NAMED-NOT-READ)","moves_conclusion":"no -- 6.5e-5 relative; the bill 2.720744289e13 M_sun per unit dGamma is reproduced to 1e-9 with the tree's constants (N1)"},
 {"quantity":"flat foliation Gamma at eps = 1e-8","value_then":"7071.067813726","value_now":"7071.067813726 (recomputed, 1/sqrt(1-(1-eps)^2))","source_now":"computed here (N2)","moves_conclusion":"no"}
],
"rederivation":{
 "method":"sympy",
 "script_path":D+"/rederive/misner-sharp-hernandez-evolution-equations.py",
 "outcome":"41 PASS, 0 FAIL (output in rederive/misner-sharp-hernandez-evolution-equations.out, ~11 s). Einstein tensor built by an independent routine (not nonstatic.general_einstein). C1: all five tree equations residual 0. C2: EV-W == EV-U' identically, and EV-W is the tr momentum constraint. C3/C4: exact agreement with HSW 0810.1083 eqs (14),(28),(30),(31),(37) under A = e^Phi, B = e^Lambda, q = j. C5: MMR (MS 1964) eqs (9),(12),(13),(14) recovered at j = 0, with nabla_a T^a_r = p' + (rho+p)Phi' computed. C6: Hernandez-Misner (25),(26) follow from MS-r + MS-t at j = 0 (with j != 0 an extra 4 pi R^2 j (U - W) appears). C7: EV-W follows from m's definition + EV-U + MS-t for W != 0 (rho, p_r cancel). C8: geodesic-slicing witnesses Lemaitre-Schwarzschild (G = 0, W = 1), LTB (W = sqrt(1+2E(r))), Milne (G = 0, W = cosh chi) all have D_t W = 0. C9: contracting Milne focuses (geodesic slicing is local). C10: Lambda leaves EV-W unchanged, adds Lambda R^2 W/2, Lambda R^2 U/2, Lambda R/2 to MS-r, MS-t, EV-U. C11/C12: E = R dW needs only U = 0 at the sphere; at U = 0 W = sqrt(1-2m/R) is a scalar; geodesic + U = 0 forces m = -4 pi R^3 p_r. N: 2.720744289e13 M_sun reproduced to 1e-9; Gamma = 7071.067813726 reproduced; Lambda term 8.05e-7 M_sun. One first-draft check (C10d with Lambda R/3) failed because it paired the full MS mass with the matter-mass coefficient; corrected to Lambda R/2 (full m) and Lambda R/3 (matter m), both pass -- recorded so the correction is visible.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"Herrera, Santos & Wang, arXiv 0810.1083 (PRD 78, 084026, 2008)","effect":"extends","what":"Full MS system for a dissipative anisotropic viscous comoving fluid: eq.(14) momentum constraint (= tree's EV-W with q = j), (30) D_T m, (31) D_R m, (37) D_T U; all agree with the tree's lines (C3, C4).","read_status":"READ (pp.1-24)"},
 {"ref":"Musco, Miller & Rezzolla, arXiv gr-qc/0412063 (CQG 22, 1405, 2005)","effect":"confirms","what":"Restates MS 1964 (perfect fluid, comoving) and HM 1966 (observer time) equations exactly as used in numerical collapse codes; tree reproduces both at j = 0 (C5, C6). Notes cosmic-time (MS) slicing hits singularities early in continuing collapse -- a slicing limitation, consistent with C9.","read_status":"READ (pp.1,3-4,6-12,14-18,20-23,28-29)"},
 {"ref":"Herrera, Di Prisco, Martin, Ospino, Santos & Troconis, arXiv gr-qc/0403006 (PRD 69, 084026, 2004)","effect":"extends","what":"Noncomoving (Schwarzschild-like coordinate) form of the dissipative anisotropic system; eq.(6) -8 pi T_10 = -lambdadot/r is the momentum constraint in areal gauge. Consistent; not needed for the tree's form.","read_status":"READ (pp.1-29)"},
 {"ref":"Cai, Cao, Hu & Ohta, arXiv 0910.2387 (PRD 80, 104016, 2009)","effect":"narrows","what":"In f(R) (and scalar-tensor) gravity the generalised MS energy exists only if the integrability constraint (3.7)/(3.13) holds and is generally not quasi-local; in Einstein and Gauss-Bonnet gravity it always exists. Narrows the MS machinery to GR(-like) theories -- a hypothesis the tree leaves unstated but does not violate.","read_status":"READ (pp.1-18)"},
 {"ref":"Jai-akson & Yokokura, arXiv 2601.03077 (2026)","effect":"extends","what":"Einstein equations in spherical symmetry recast in an arbitrary foliation-adapted frame: L_u M = A T_un (eq.52/91), L_k M = -A T_uk (eq.53/93); MS energy evolution in any frame sourced by the matter energy flux. Frame-general content consistent with the tree's MS-t / MS-r; no contradiction found.","read_status":"READ (pp.1,5-8,11,21-25,31-34,47-48,51)"},
 {"ref":"Maeda & Nozawa, arXiv 0709.1199 (PRD 77, 064031, 2008)","effect":"extends","what":"Generalised MS energy with cosmological constant / Gauss-Bonnet (as cited in 0910.2387 eq.2.12). Consistent with C10's Lambda terms.","read_status":"NAMED-NOT-READ in this audit (restated in 0910.2387 p.6)"}
],
"lacked_data":"M's hypothesis tested for this result. The MS 1964 / HM 1966 equations take NO numerical input: they are identities of the Einstein tensor of a diagonal spherically symmetric metric plus definitions (re-derived here, C1-C2, and matched to two independent later restatements, C3-C6). The one physical fact the 1964 authors lacked that enters their setting is a nonzero cosmological constant (measured 1998). Having it: EV-W, the tree's load-bearing line, is exactly unchanged (C10a); MS-r, MS-t, EV-U acquire Lambda R^2 W/2, Lambda R^2 U/2, Lambda R/2 terms (C10b-d), which the tree already absorbs by defining T := G/8pi (nonstatic.py:297), and which amount to 8.05e-7 M_sun at the Proxima span (N3). Evidence the other way: later work generalised the system to heat flux, anisotropy, viscosity and radiation (HSW 0810.1083, gr-qc/0403006) and to arbitrary frames (2601.03077) without correcting any MS line; the only narrowing found (0910.2387) concerns theories beyond GR, not missing data. Verdict on the hypothesis for this result: no data the authors lacked changes the conclusion.",
"grade":"NARROWED",
"grade_evidence":"The external result STANDS as mathematics: all five of the tree's lines re-derive with residual 0 from an independently coded Einstein tensor (C1) and agree exactly with the published restatements of Misner-Sharp (MMR eqs 9,12-14; C5), Hernandez-Misner (MMR eqs 25-26; C6) and their dissipative generalisation (HSW eqs 14,28,30,31,37; C3-C4); no datum enters it and the one missing 1964 fact (Lambda) leaves EV-W exactly unchanged (C10a). The grade is NARROWED, not STANDS, only because the tree's USE drops a hypothesis: 'geodesic slicing (Phi = 0, always available)' (nonstatic.py:87; relied on at driven.py:239-241 and foliation.py:338-341) is available only up to the first focal point of the normal congruence (C9: contracting Milne focuses at finite proper time), and GR / Lambda-absorption are unstated (nonstatic.py:297). No verdict in rests_on_it is shown to move: SUSTAINING_FORCES_NEGATIVE_RHO = False rests on global exact witnesses (C8); E = R dGamma needs only U = 0 at the sphere, not geodesic slicing (C11). Recorded discrepancies, not refutations: EV-W and EV-U' are one equation counted as two (C2a); 'does not know the energy density exists' (nonstatic.py:82-83) over-reads EV-W (rho fixes W on each slice, C7/C4a); and the owners state different hypotheses for E = R dGamma (foliation.py:338-341 geodesic slicing vs nonstatic.py:178-184 R held fixed), under the latter of which Gamma = sqrt(1 - 2m/R) is a scalar (C12) -- a question for foliation.py's BUILD_BILL_IS_GAUGE_CONDITIONAL that this audit records and does not adjudicate.",
"what_would_change_the_grade":"To STANDS: nonstatic.py:87 restated as 'geodesic slicing, available locally (until the normal congruence focuses)' and GR with Lambda absorbed into T named as hypotheses -- the equations themselves need no change. To WRONG: a residual != 0 in any of C1a-e under a different, verified Einstein-tensor code, or a published MS/HM line contradicting the tree's form once conventions are matched (none found). A reading of the MS 1964 or HM 1966 originals (NAMED-NOT-READ here) that differed from both MMR and HSW restatements would reopen the source status but not the identities, which are checked independently.",
"reverify_command":"python3 "+D+"/rederive/misner-sharp-hernandez-evolution-equations.py  # expect 41 PASS, 0 FAIL, exit 0",
"report_path":D+"/audits/misner-sharp-hernandez-evolution-equations.json"
}
json.dump(rep,open(rep["report_path"],"w"),indent=1)
print("ok")
