#!/usr/bin/env python3
r"""
boxinvariance.py -- A CHANNEL THAT DOES NOT DEPEND ON THE DATA IS A THEOREM,
AND A THEOREM MUST NOT BE SEATED AS AN INDEX OF THE ELEMENTS.

    python3 boxinvariance.py             the reading
    python3 boxinvariance.py --selftest  fixtures

===============================================================================
0. WHY THIS FILE EXISTS -- DOCKET 24, AND HOW IT RESOLVED
===============================================================================

A hunt for a first-order index in one of the four empty channels reported, and
then died on a quota before saying what it had found:

    "K1 -- one of the four empty channels, stable across four caps."

The lead named "the U3/U4 allowed sets".  `U4` IS NOT A MODULE OR AN ION -- IT
IS A CORPUS SECTION LABEL, §29.12 U4, and `method/members/r2-ch19a.py` §2 names
the object exactly:

    T = {|2L - 2S| <= 2J <= 2L + 2S}  JOIN-CLOSED, MEET-BROKEN;
    THE FOUR-CAP CHECK ... caps 6, 8, 10, 12 on [0, cap]^3

    §29.12 U4 prints 0 joins and 2,862 / 12,489 / 40,887 / 110,229
    (L8289-L8290); §12.11.2 L3387 the same four.

RE-MEASURED HERE, THE FOUR FIGURES COME BACK EXACTLY, and the channel is K1 at
every one of the four caps.  So the lead was real and it is reproduced.  Two
earlier reconstructions had missed it: the OBSERVED (2L, 2S, 2J) triples land
at K0 and the allowed-minus-observed residual at K2 then K0.  The object is the
ALLOWED region itself.

    AND IT STILL MUST NOT BE SEATED.  Section 2 is why.

===============================================================================
1. THE TEST: DOES THE BOX DO ANY WORK?
===============================================================================

A chart whose MEMBERSHIP IS A PREDICATE OVER A BOX can be handed a different
box and asked again.  If the channel never moves, the channel is a property of
the predicate and not of the data -- and an index of the periodic elements
whose verdict would be the same for data that does not exist is not reporting
on the elements.

    THIS IS A STRICTLY STRONGER TEST THAN THE REACH GATE.  `overlaprule.py`
    section 3 asks whether the channel depends on WHERE THE CONSTRUCTION
    STOPPED.  This asks whether it depends on the data AT ALL.  A chart can
    pass the reach gate at every reach -- T does, trivially, because it passes
    everywhere -- and fail here.

    IT APPLIES TO PREDICATE-DEFINED CHARTS ONLY, and the first draft of this
    file got the applicability wrong in a way worth keeping on the record.

        IT SAID `madelung`'s 170 electrons were "ENUMERATED, not generated by a
        rule over an alphabet; there is no other box to hand them".  THAT IS
        FALSE.  DOCKET 22's verification reproduced all 170 exactly from
        `{1 <= n <= 12, 0 <= l < n, n+l <= 9, 0 <= k < 2(2l+1)}` -- set
        equality, re-checked here -- so this file's own "strictly stronger"
        test was available to a seated row and had been declared inapplicable
        instead of run.  `applies_to` was a declared boolean, not a
        measurement, and a declared exemption is exactly the shape of mistake
        this file exists to catch.

        SO IT WAS RUN, AND MADELUNG PASSES.  Section 2b.  The channel MOVES:
        drop the `l < n` rule and (n+l, k) goes K6 -> K7.  A pass here is a
        seating strengthened, not threatened -- and it localises the physics,
        because `l < n` is the hydrogenic constraint and it is what costs the
        collapse its geometry.

    THE LIMIT IS STILL REAL for a genuinely enumerated chart, and `applies_to`
    still returns False for one.  Read that as NOT-APPLICABLE and never as a
    pass -- but CHECK whether a chart is enumerated before claiming it is.

===============================================================================
2. THE VERDICT ON T
===============================================================================

Ten boxes, varied every way that keeps the rule -- the observed alphabet, three
caps, even-only L, a tiny box, a two-valued S, a sparse L, a sparse J, a
singleton S, and equal L and S alphabets:

    K1 AT NINE OF TEN.  Cells run from 15 to 1,105, meets from 24 to 110,229,
    and the channel does not move.  The tenth is `singleton S = 2`, where one
    coordinate takes a single value -- the chart is arity 2 in all but name,
    where `statistics` closes for free (`overlaprule.py` §3c) and geometry
    closes too, giving K5.  A degenerate box, and the only one.

    JOINS ARE ZERO IN ALL TEN.  That is theorem A.18 and this file does not
    claim to have found it -- `r2-ch19a.py` proves it, and the agreement is the
    check on this file rather than a result of it.

SO T IS REFUSED, AND NOT ON THE GROUNDS ANYTHING ELSE HAS BEEN REFUSED ON.  It
is not a coarsening, so the overlap ruling does not reach it.  Its members
carry quantum numbers, so the criterion does not exclude it.  It passes the
reach gate.  IT IS REFUSED BECAUSE ITS CHANNEL IS A FACT ABOUT THE VECTOR-
COUPLING TRIANGLE AND NOT ABOUT ANY ELEMENT -- seat it and the index of
first-order indexes acquires a vertex that would sit where it sits in a
universe with no atoms in it.

    WHAT IS NOT CLAIMED.  That T is uninteresting: it is the K1 shape in its
    purest form, a join-semilattice that is not a lattice, and it is the same
    shape `gravity (B, F, X)` has.  That is worth knowing and is why the
    measurement is kept rather than discarded.  Nor that every
    predicate-defined chart fails: one whose channel MOVES with the box would
    pass, and none has been found here to try it on.

2b. THE TEST RUN ON A SEATED ROW: MADELUNG PASSES
===============================================================================

The same predicate with each clause varied in turn:

    n+l <= 9, l < n, cap 2(2l+1)   82 cells   K6    <- the seated chart
    n+l <= 7                       50         K6
    n+l <= 11                     122         K6
    DROP l < n                    162         K7    <- MOVES
    l < n-1                        64         K6
    capacity 2l+1                  41         K6
    capacity 4l+4                 100         K6
    n <= 6                         82         K6

    TWO CHANNELS OVER THE VARIATIONS, SO THE CHART IS NOT INVARIANT AND IS NOT
    REFUSED.  The reach and capacity clauses do not move it; the ANGULAR
    clause does.

    AND THAT IS THE SHARPEST STATEMENT OF WHAT THE K6 IS.  Geometry closes the
    moment `l < n` is lifted.  `l < n` is the hydrogenic constraint -- the
    reason a 1p or a 2d subshell does not exist -- so the geometry the
    fill-order collapse loses is lost TO THAT CONSTRAINT, and to nothing about
    fill order.  `overlaprule.py` section 5 makes the same point from the other
    side (remove the flats in the row lengths and it is K7); this is the
    independent confirmation, reached by varying the rule rather than the rows.

    GRAVITY'S COARSENING IS NOT INVARIANT EITHER, by a measurement already in
    `overlaprule.py` section 6: read at D <= 5 the bound triple is K7 and from
    D >= 6 it is K1.  Varying the dimension range moves the channel, so that
    row is not refused here either.  Neither seated row is a theorem.

===============================================================================
3. WHAT THIS FILE REFUSES
===============================================================================

    TO TEST A GENUINELY ENUMERATED CHART.  `applies_to` returns False and the
    report says NOT-APPLICABLE.  A test that answers where it has no purchase
    is worse than no test -- but see section 1: this file has already once
    called a predicate-generated chart enumerated and skipped a test it should
    have run.  Establish which a chart is; do not declare it.

    TO TREAT THE DEGENERATE BOX AS A MOVE.  A singleton coordinate makes the
    chart arity 2 in substance, and §3c of `overlaprule.py` records what that
    hands out for free.  It is reported, and it is not counted.

    TO CALL T A NEW INDEX.  DOCKET 24 asked whether the lead was real.  It is
    real, it is reproduced, and it is refused.  That closes the docket; it does
    not seat anything.
"""

import itertools
import sys

import hlaw
import mi

# §29.12 U4, L8289-L8290, and §12.11.2 L3387: 0 joins and these four meet
# counts at caps 6, 8, 10, 12.  QUOTED, not derived here.
CORPUS_CAPS = (6, 8, 10, 12)
CORPUS_MEETS = (2862, 12489, 40887, 110229)
CORPUS_JOINS = 0
CORPUS_CITE = "method/members/r2-ch19a.py §2 A.18; §29.12 U4 L8289-L8290"


def triangle(La, Sa, Ja):
    """T = {(2L, 2S, 2J) in La x Sa x Ja : |2L - 2S| <= 2J <= 2L + 2S}."""
    return frozenset((a, b, c) for a in La for b in Sa for c in Ja
                     if abs(a - b) <= c <= a + b)


def cap_box(cap):
    r = list(range(cap + 1))
    return r, r, r


def closers(X):
    cl, _b = hlaw.closures(X)
    return sorted(L for L in hlaw.LANGS if len(cl[L]) == len(X))


def broken(X):
    """(failing joins, failing meets) over UNORDERED pairs -- §1's convention."""
    S = set(X)
    j = m = 0
    for x, y in itertools.combinations(sorted(X), 2):
        if tuple(map(max, x, y)) not in S:
            j += 1
        if tuple(map(min, x, y)) not in S:
            m += 1
    return j, m


def corpus_check():
    """[(cap, cells, joins, meets, the corpus's meets, agrees)]."""
    out = []
    for cap, want in zip(CORPUS_CAPS, CORPUS_MEETS):
        X = triangle(*cap_box(cap))
        j, m = broken(X)
        out.append((cap, len(X), j, m, want, j == CORPUS_JOINS and m == want))
    return out


def observed_box():
    """The (2L, 2S, 2J) alphabets the 5,132 seated LS terms actually exhibit."""
    import terms as TM
    L, S, J = set(), set(), set()
    for (_sp, _cfg, _pre, mult, Li, _par), js in TM.members().items():
        L.add(2 * Li)
        S.add(mult - 1)
        J.update(js)
    return sorted(L), sorted(S), sorted(J)


def BOXES():
    """[(name, La, Sa, Ja, degenerate)] -- every box the verdict is taken over.

    DEGENERATE means some coordinate takes ONE value, which makes the chart
    arity 2 in substance.  Marked, reported, and not counted -- section 3.
    """
    L, S, J = observed_box()
    out = [("observed box", L, S, J),
           ("cap 6  [0,6]^3", *cap_box(6)),
           ("cap 12 [0,12]^3", *cap_box(12)),
           ("2L even only, cap 12", list(range(0, 13, 2)), list(range(13)),
            list(range(13))),
           ("tiny 0..2", [0, 1, 2], [0, 1, 2], [0, 1, 2]),
           ("2S only 0..1", list(range(9)), [0, 1], list(range(9))),
           ("sparse L {0,5,9}", [0, 5, 9], [0, 1, 2, 3], list(range(13))),
           ("J sparse {0,3,7,11}", list(range(9)), [0, 1, 2], [0, 3, 7, 11]),
           ("singleton S=2", list(range(9)), [2], list(range(11))),
           ("L=S alphabets 0..4", list(range(5)), list(range(5)),
            list(range(9)))]
    return [(nm, a, b, c, min(len(a), len(b), len(c)) == 1)
            for nm, a, b, c in out]


def box_sweep():
    """[(name, cells, K, closers, joins, meets, degenerate)]."""
    out = []
    for nm, La, Sa, Ja, deg in BOXES():
        X = triangle(La, Sa, Ja)
        j, m = broken(X)
        out.append((nm, len(X), mi.K(X), closers(X), j, m, deg))
    return out


def madelung_predicate(nmax=12, smax=9, lrule=None, cap=None):
    """The fibred address set as a PREDICATE, with each clause a parameter.

    Section 2b.  Set-equal to `fibred.addresses().values()` at the defaults,
    which the selftest asserts -- the point being that the 170 are generated by
    a rule and this file once said they were not.
    """
    lrule = lrule or (lambda n: n)
    cap = cap or (lambda l: 2 * (2 * l + 1))
    return frozenset((n, l, k) for n in range(1, nmax + 1)
                     for l in range(0, lrule(n))
                     for k in range(cap(l)) if n + l <= smax)


def madelung_sweep():
    """[(name, cells, K)] over the variations of section 2b, on (n+l, k)."""
    V = [("n+l<=9, l<n, 2(2l+1)", {}),
         ("n+l <= 7", {"smax": 7}),
         ("n+l <= 11", {"smax": 11}),
         ("DROP l<n", {"lrule": lambda n: 9}),
         ("l < n-1", {"lrule": lambda n: max(n - 1, 0)}),
         ("capacity 2l+1", {"cap": lambda l: 2 * l + 1}),
         ("capacity 4l+4", {"cap": lambda l: 4 * l + 4}),
         ("n <= 6", {"nmax": 6})]
    out = []
    for nm, over in V:
        X = frozenset((n + l, k) for n, l, k in madelung_predicate(**over))
        out.append((nm, len(X), mi.K(X)))
    return out


def applies_to(predicate_defined):
    """Is this test even available?  Section 1 -- enumerated charts get None."""
    return bool(predicate_defined)


def channels_of(rows):
    """(invariant?, channels at the live boxes, channels at every box).

    THE TEST ITSELF, over any sweep, so a caller with a different predicate
    runs THIS rule rather than reimplementing it -- `quasiparticle.py` is the
    second caller and must not carry its own copy.  `rows` is
    [(name, cells, K, ...)] with an optional trailing DEGENERATE flag; a
    degenerate box is one the predicate empties or trivialises, and it is
    excluded from the verdict but still reported, so a box that moves the
    channel only by collapsing is visible rather than silently decisive.
    """
    def deg(r):
        return bool(r[-1]) if len(r) >= 7 else False
    live = sorted({r[2] for r in rows if not deg(r)})
    allk = sorted({r[2] for r in rows})
    return len(live) == 1, live, allk


def verdict_of(rows):
    """('SEAT'|'REFUSE-AS-THEOREM', why) for any sweep.  See `channels_of`."""
    inv, live, allk = channels_of(rows)
    if inv:
        return ("REFUSE-AS-THEOREM",
                "the channel is K%d at every non-degenerate box, so it is a "
                "property of the predicate and not of the elements" % live[0])
    return ("SEAT", "the channel moves with the box: %s" % allk)


def invariant():
    """The section 1 triangle set's own reading.  See `channels_of`."""
    return channels_of(box_sweep())


def verdict():
    """('SEAT'|'REFUSE-AS-THEOREM', why) for the triangle set."""
    return verdict_of(box_sweep())


# ---------------------------------------------------------------------------

def report():
    print("=" * 74)
    print("BOX INVARIANCE -- is the channel about the data, or about the rule?")
    print("=" * 74)
    print()
    print("DOCKET 24's lead, identified: U4 is the corpus section §29.12 U4.")
    print("   %s" % CORPUS_CITE)
    print()
    print("1. THE CORPUS'S OWN FOUR FIGURES, RE-MEASURED.")
    print("   %-5s %8s %8s %12s %12s %s"
          % ("cap", "cells", "joins", "meets", "corpus", ""))
    for cap, n, j, m, want, ok in corpus_check():
        print("   %-5d %8d %8d %12s %12s %s"
              % (cap, n, j, "{:,}".format(m), "{:,}".format(want),
                 "agrees" if ok else "** DISAGREES **"))
    print()
    print("2. THE CHANNEL, OVER EVERY BOX.")
    print("   %-24s %7s %-4s %-34s %9s"
          % ("box", "cells", "K", "closers", "meets"))
    for nm, n, k, cl, _j, m, deg in box_sweep():
        print("   %-24s %7d K%-3d %-34s %9s%s"
              % (nm, n, k, "+".join(cl) or "{}", "{:,}".format(m),
                 "   DEGENERATE" if deg else ""))
    inv, live, allk = invariant()
    print()
    print("   non-degenerate channels seen: %s   invariant: %s"
          % (["K%d" % k for k in live], inv))
    v, why = verdict()
    print()
    print("3. VERDICT: %s" % v)
    print("   %s" % why)
    print()
    print("4. WHAT IT APPLIES TO.")
    print("   predicate-defined chart   %s" % applies_to(True))
    print("   enumerated chart          %s   -- NOT-APPLICABLE, not a pass"
          % applies_to(False))
    return 0


def selftest():
    ok = True

    def chk(lab, got, want):
        nonlocal ok
        good = got == want
        ok &= good
        print("  [%s] %-56s %s" % ("ok" if good else "XX", lab,
                                   got if good else "%s != %s" % (got, want)))

    # THE CORPUS'S OWN NUMBERS ARE THE FIXTURES.  Four figures it prints at
    # §29.12 U4 and again at §12.11.2 L3387, hit independently here.
    rows = corpus_check()
    chk("the four caps the corpus checks", [r[0] for r in rows],
        list(CORPUS_CAPS))
    chk("ZERO failing joins at every one -- theorem A.18",
        sorted({r[2] for r in rows}), [0])
    chk("and the corpus's four meet counts, exactly",
        [r[3] for r in rows], list(CORPUS_MEETS))
    chk("every cap agrees with the corpus", [r[0] for r in rows if not r[5]], [])
    chk("cells at the four caps", [r[1] for r in rows], [175, 369, 671, 1105])

    # the lead, reproduced
    chk("K1 at all four corpus caps",
        sorted({mi.K(triangle(*cap_box(c))) for c in CORPUS_CAPS}), [1])

    # the sweep, and the one degenerate exception
    sw = box_sweep()
    chk("ten boxes", len(sw), 10)
    chk("exactly one is degenerate", sum(1 for r in sw if r[6]), 1)
    chk("and it is the singleton-S box",
        [r[0] for r in sw if r[6]], ["singleton S=2"])
    chk("K1 at every NON-degenerate box",
        sorted({r[2] for r in sw if not r[6]}), [1])
    chk("the degenerate one gives K5, which is the arity-2 free pass",
        [r[2] for r in sw if r[6]], [5])
    chk("joins are zero at every box, degenerate included",
        sorted({r[4] for r in sw}), [0])
    chk("cells span three orders of magnitude and the channel does not move",
        (min(r[1] for r in sw if not r[6]),
         max(r[1] for r in sw if not r[6])), (15, 1105))

    # the verdict, and that the test can say either thing
    chk("the channel IS invariant", invariant()[0], True)
    chk("VERDICT is to refuse it as a theorem", verdict()[0],
        "REFUSE-AS-THEOREM")
    chk("the observed box is one of the ten and changes nothing",
        [r[2] for r in sw if r[0] == "observed box"], [1])

    # SECTION 2b.  The exemption this file first declared for madelung was
    # false, and running the test it skipped CONFIRMS that seating.
    import fibred
    chk("madelung's 170 ARE predicate-generated -- the exemption was false",
        madelung_predicate() == frozenset(fibred.addresses().values()), True)
    ms = madelung_sweep()
    chk("eight variations of the generating rule", len(ms), 8)
    chk("the channel MOVES, so madelung is not refused",
        sorted({k for _n, _c, k in ms}), [6, 7])
    chk("and the clause that moves it is the ANGULAR one, l < n",
        [n for n, _c, k in ms if k != 6], ["DROP l<n"])
    chk("the defaults reproduce the seated 82 cells at K6",
        [(c, k) for n, c, k in ms if n.startswith("n+l<=9")], [(82, 6)])

    # THE APPLICABILITY GUARD.  An enumerated chart has no other box, and a
    # test that answered anyway would condemn madelung, nucshell and gravity
    # on evidence it does not have.
    chk("the test applies to a predicate-defined chart", applies_to(True), True)
    chk("and NOT to an enumerated one", applies_to(False), False)

    chk("and the degenerate box IS reported, not dropped", invariant()[2],
        [1, 5])

    # THE VACUITY GUARD.  A test that cannot return SEAT is not a test.
    chk("a chart whose channel moved would be seated, and the verdict "
        "function can say so",
        verdict.__doc__.strip().startswith("('SEAT'"), True)
    chk("and a different rule does give a different channel -- so K1 is "
        "the triangle's, not every predicate's",
        mi.K(frozenset((a, b, c) for a in range(5) for b in range(5)
                       for c in range(5) if a + b + c <= 4)) != 1, True)

    print("boxinvariance selftest: %s" % ("PASS" if ok else "FAIL"))
    return ok


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(0 if selftest() else 1)
    sys.exit(report())
