#!/usr/bin/env python3
r"""
decomposable.py -- OUR OWN FORMALIZATION OF THE STAIRCASE IDENTITY, WITH THE
PROVENANCE LEDGER THAT GOES WITH IT.  AND THE HEADLINE OF THE LEDGER IS THAT
THE THEOREM IS PROBABLY NOT OURS.

M: "The formalization will be entirely our own then, because the proof we are
currently working could indeed be novel.  The formalization will be supported by
the provenance of the pieces within that are attributed to other art."

THE FORMALIZATION IS OURS.  THE THEOREM PROBABLY IS NOT, AND THAT IS THE FIRST
THING THE LEDGER HAS TO SAY.

===============================================================================
0. THE PROVENANCE FINDING, BEFORE ANY MATHEMATICS
===============================================================================

A search for prior art returned, as the central subject of a published paper:

    Maurice Queyranne and Fabio Tardella, "Sublattices of product spaces:
    Hulls, representations and counting", Discrete Mathematics 308(9) (2008),
    1508-1523.

whose stated content is "sufficient conditions on the dimension of the product
space and/or on the sublattice hull of a subset Q, for it to be entirely
defined by the sublattice hulls of the two-dimensional projections of Q", and
which treats "the case of a finite product of finite chains" in detail.

    THAT IS THIS THEOREM'S EXACT QUESTION, IN THIS THEOREM'S EXACT SETTING,
    INCLUDING THE FACT THAT IT NEEDS HYPOTHESES.

THE PAPER WAS NOT READ.  ScienceDirect, HAL and Semantic Scholar are all
blocked by this session's egress proxy, and the paper is not on arXiv -- a
lookup by title resolved to an unrelated paper on permutation polytopes.  The
description above is a search-engine summary of a page nobody opened.

    STATUS: PRIOR ART, READ IN PART.  NOT "NOVEL".  The paper was later
    reconstructed from screenshots (refs/QUEYRANNE-TARDELLA-2008.md) and its
    Theorem 9(ii) and Theorem 11 are this theorem.

Claiming novelty against a paper one could not read is the error this corpus
exists to refuse.  What is ours is the FORMALIZATION -- the definitions written
out, the witness construction, the necessity table, the bridge to the running
code, and the decision procedure -- and that is what this file records.

===============================================================================
1. DEFINITIONS -- WRITTEN FROM THE MATHEMATICS, NOT IMPORTED
===============================================================================

Every definition below is implemented in this file FROM THE STATEMENT, with no
import from tools/cypher.py.  Section 6 then checks that the running program
computes these objects, which is the bridge a referee asked for and which had
been a reading rather than a check.

    D1  A_i := pi_i(X), the values X realises at coordinate i, totally ordered.
    D2  Box(X) := A_1 x ... x A_d, a finite product of finite chains, a lattice
        under coordinatewise min (/\) and max (\/).
    D3  <X> := the sublattice of Box(X) generated by X.
    D4  phi_ij(a) := max{ y_i : y in X, y_j <= a }, undefined if that set is empty.
    D5  R(X) := { x in Box(X) : x_i <= phi_ij(x_j) for all i != j }.   THE STAIRCASE.
    D6  J(X) := the join-closure of X (coordinatewise max only).
    D7  S is k-DETERMINED iff S = { x in Box : every k-fold projection of x is a
        k-fold projection of some element of S }.

===============================================================================
2. THE THEOREM AND ITS PROOF
===============================================================================

    THEOREM T1.  For finite non-empty X with d >= 2,   R(X) = <X>.

L1 (phi is total and monotone).  For a in A_j some y in X has y_j = a, so the
   set in D4 is non-empty and phi_ij(a) is defined.  It is a max over a set
   growing with a, hence non-decreasing.        [uses D1; see N1 in section 4]

L2 (R is a sublattice containing X).  Each x in X witnesses itself, so
   X subset R(X).  Let p, q in R(X) and fix i != j.
     join: take p_i >= q_i; then (p\/q)_i = p_i <= phi_ij(p_j) <= phi_ij((p\/q)_j).
     meet: take p_j <= q_j; then (p/\q)_i <= p_i <= phi_ij(p_j) = phi_ij((p/\q)_j).
   Both use L1's monotonicity.  Hence <X> subset R(X).

L3 (d = 2, the content).  Let (a,b) in R(X).  Four witnesses exist in X:
     y with y_A = a           (a is observed)
     z with z_B = b           (b is observed)
     u with u_A <= a, u_B >= b     (from b <= phi_BA(a), which is attained)
     v with v_A >= a, v_B <= b     (from a <= phi_AB(b), which is attained)
   Put alpha := y \/ u = (a, beta) with beta >= b, and gamma := z \/ v = (alpha', b)
   with alpha' >= a.  Then alpha /\ gamma = (a, b).  Both lie in <X>, so
   R(X) subset <X>, and with L2, equality.

L4 (projection commutes with generation).  pi_ij is a lattice homomorphism, so
   pi_ij(<X>) = <pi_ij(X)>.  phi_ij depends only on pi_ij(X), and
   pi_i(pi_ij(X)) = A_i, so D1 passes to the projection.  By L3 this equals
   R_ij := { (s,t) : s <= phi_ij(t), t <= phi_ji(s) }.

L5 (the lift).  Lattices have the majority term m(x,y,z) = (x/\y)\/(y/\z)\/(z/\x).
   By Baker-Pixley a subalgebra of a product of finitely many algebras in a
   variety with a majority term is determined by its two-fold projections:
       <X> = { x in Box(X) : (x_i,x_j) in pi_ij(<X>) for all i < j }.
   By L4 the right-hand side is exactly D5.  Hence T1.               [PRIOR ART]

L6 (monotone, as a corollary and not as new work).  T subset S implies
   <T> subset <S> because generation is monotone, and R = <.> by T1, so R is
   monotone too.  A referee was right that this had never been proved and that
   the ambient had been left ambiguous; it is a corollary, and the earlier
   "measurement" of it was measuring the wrong thing.

L7 (information).  J(X) is join-closed and contains X, so J(X) contains the
   join-closure of any subset of X; and every x in X is a join of
   join-irreducibles of X by induction on the number of elements of X strictly
   below x.  Hence op_information(X) = J(X), and J(X) subset <X> since a
   sublattice is join-closed.  SO information subset algebra IS A THEOREM.

===============================================================================
3. WHAT L5 COSTS, AND WHY IT IS NOT AVOIDABLE
===============================================================================

L1-L4 leave R(X) a sublattice containing X whose pairwise projections are
exactly those of <X>.  Without a two-determinacy theorem that does not close.
For d = 2 the lift is not needed -- L3 is the whole proof.  For d >= 3 it is.

    Baker-Pixley citation, CONFIRMED ONLY BY SEARCH SUMMARY, NOT READ:
    Kirby A. Baker and Alden F. Pixley, "Polynomial interpolation and the
    Chinese Remainder Theorem for algebraic systems", Mathematische Zeitschrift
    143 (1975), 165-174, DOI 10.1007/BF01187059.

    THE PROPERTY IS CALLED k-DECOMPOSABILITY.  It is NOT called "near-unanimity"
    -- that names the TERM, and a (k+1)-ary near-unanimity term is what is
    equivalent to k-decomposability.  It is NOT "skew-free", which is the
    Fraser-Horn property about congruences of a product and a live trap because
    it sits in the same textbook section.  And the factors need not be finite;
    it is the NUMBER OF FACTORS that must be.

===============================================================================
4. THE NECESSITY TABLE -- EACH HYPOTHESIS DROPPED UNTIL IT BREAKS
===============================================================================

N1  A_i = pi_i(X), the observed alphabet.       SUFFICIENT, NOT NECESSARY.
    This was recorded earlier in this thread as NECESSARY and that was wrong.
    Over a declared box larger than the observed one the identity often fails
    -- but not always.  The weaker sufficient condition is ORDER-CONVEXITY:
    it is enough that each pi_i(X) be order-convex in A_i, i.e. that no value
    of A_i strictly between min pi_i(X) and max pi_i(X) go unobserved.
    Unobserved values ABOVE the max or BELOW the min are harmless.
    Convexity is itself not necessary: gapped worlds can still hold.

N2  each A_i is a CHAIN.                        NECESSARY, AND ONE-DIRECTIONAL.
    Off the chains the staircase never OVER-generates; it UNDER-generates.
    R(X) subset <X> survives arbitrary finite lattice factors -- it is L2, which
    needs phi monotone and hence a total order, that dies.  Measured on the
    diamond M3 and the pentagon N5 as factors.

N3  d >= 2.                                     A CONVENTION, NOT A THEOREM.
    At d = 1 cypher.py's op_order returns SILENT.  Both sides would be X.

N4  X finite and non-empty.                     FINITENESS OF d IS WHAT L5 NEEDS.
    Baker-Pixley wants finitely many factors; the factors themselves need not
    be finite.  Not pursued further here -- see section 7.

===============================================================================
5. THE 2-DETERMINACY PARTITION, AND HOW MUCH OF IT IS TRIVIAL
===============================================================================

Measured, all five operators: order, algebra, geometry and statistics are
2-determined; information is not.  THREE OF THOSE FOUR ARE TRIVIAL AND THIS FILE
SAYS SO.  If L(X) = { x in Box : (x_i,x_j) in C_ij for all i<j } for ANY pair
conditions C_ij, then pi_ij(L(X)) subset C_ij, so the rebuild from L(X)'s own
projections is contained in L(X), and the reverse inclusion is free.  Two lines.
op_order, op_geometry and op_statistics are each DEFINED that way.

    THE CONTENT IS IN THE OTHER TWO.  op_algebra is defined by closure under
    operations, not by pair conditions, and its 2-determinacy is L5 -- real work.
    op_information is not 2-determined at all, and the minimal witness is three
    cells in three dimensions:

        X = {(0,0,0), (0,1,1), (1,0,1)}      J(X) adds (1,1,1) and stops at 4
        rebuilt from its own pair projections, J(X) invents (0,0,1)

    On that same X all four other operators are 2-determined.  ONE THREE-ELEMENT
    SET SEPARATES information FROM THE REST OF THE HIERARCHY, and the reason is
    structural: join-semilattices have no majority term.

===============================================================================
6. THE BRIDGE -- THIS FILE'S OBJECTS ARE THE PROGRAM'S OBJECTS
===============================================================================

A referee's standing objection was that identifying op_order with D5 and
op_algebra with D3 was A READING OF THE SOURCE, not a check.  Section 6 checks
it: the from-scratch definitions here are compared against tools/cypher.py's
operators on random indexes, in the recoded coordinates the Index actually uses.

===============================================================================
6b. THE FRONTIER -- WHAT "EXHAUSTIVE" MEANS HERE, EXACTLY
===============================================================================

Every number below is recomputed and pinned by --selftest; none is quoted from
a run that is not reproduced here.

    T1 over observed boxes      36,252 cases      0 failures
        shapes 3x3 (all subsets), 4x4 and 3x3x3 (|X| <= 4),
        2^4 (|X| <= 5), 2^5 (|X| <= 3)
    L3's construction BUILT     54,392 cells      0 failures
    L5 checked directly          4,128 sublattices, 0 not-2-determined,
                                 0 majority-term failures
    N1 over DECLARED boxes       convex: 1,853 hold, 0 FAIL
                                 gapped:   632 hold, 1,643 FAIL
    the bridge (section 6)         400 indexes, 400 agree, 400 agree

    THE 632 ARE THE POINT.  A gapped world can still satisfy the identity, so
    order-convexity is SUFFICIENT AND NOT NECESSARY, and the earlier claim in
    this thread that the observed alphabet is NECESSARY was wrong twice over.

===============================================================================
7. WHAT IS NOT DONE, STATED AS QUESTIONS
===============================================================================

  - The Queyranne-Tardella paper is unread.  Does it contain T1?  Does its
    sufficient condition coincide with order-convexity?
  - Baker-Pixley is unread.  Only the statement, as paraphrased by citing work.
  - THE CORE IS NOW MACHINE-CHECKED.  z3-solver installs from pypi, which the
    egress proxy allows (github, and so Lean and Coq, it does not) -- see
    PROOF-ASSISTANT.md.  machinecheck.py discharges 21 obligations over EVERY
    subset of boxes up to 3x3x3.  Statuses kept apart: PROVED-HERE, MACHINE-
    CHECKED, EXHAUSTIVE (a stated finite family), SAMPLED (a seeded sweep),
    CITED.  Clauses D-H are NOT machine-checked; §10 of the paper says why.
  - Whether the identity survives infinite chains.
  - Whether order-convexity is the weakest sufficient condition, or only a
    weaker one than N1.

NOTHING IS REPAIRED.  tools/cypher.py IS NOT TOUCHED.
"""

import itertools
import random
import sys

# ------------------------------------------------------------------ provenance

PROVENANCE = [
    ("T1  R(X) = <X>", "PRIOR ART, READ (partial reconstruction)",
     "Queyranne & Tardella, Discrete Math. 308(9) (2008) 1508-1523, Thm 9(ii) and "
     "Thm 11.  Sections 1-3 reconstructed from screenshots at "
     "refs/QUEYRANNE-TARDELLA-2008.md; notation restored by hand, so the prose is "
     "close to verbatim and the formulas are a reading."),
    ("L5  2-decomposability", "PRIOR ART, CITED-UNREAD",
     "Baker & Pixley, Math. Z. 143 (1975) 165-174, DOI 10.1007/BF01187059."),
    ("the majority term", "PRIOR ART, STANDARD",
     "m(x,y,z) = (x^y) v (y^z) v (z^x); folklore in lattice theory."),
    ("<X> as sublattice closure", "PRIOR ART, CITED BY cypher.py",
     "Birkhoff, Lattice Theory -- already the citation on op_algebra."),
    ("L3  the four-witness construction", "OURS, PROVED-HERE",
     "alpha = y v u, gamma = z v v, alpha ^ gamma = (a,b).  No source known; "
     "no novelty claimed, because the paper that would settle it is unread."),
    ("N1  order-convexity", "OURS, PROVED-HERE + EXHAUSTIVE",
     "supersedes this thread's earlier claim that the observed alphabet is "
     "NECESSARY, which was wrong."),
    ("N2  chains, one-directional failure", "OURS, EXHAUSTIVE",
     "off the chains R(X) subset <X> survives; equality does not."),
    ("L7  information = join-closure", "OURS, PROVED-HERE + EXHAUSTIVE",
     "and hence information subset algebra is a theorem."),
    ("the 2-determinacy partition", "OURS, PARTLY TRIVIAL",
     "three of the four are two lines; the content is op_algebra (= L5) and "
     "op_information's failure."),
    ("the bridge, section 6", "OURS, SAMPLED (3 of 5 operators)",
     "closes a referee's objection that the identification was a reading -- but it "
     "calls op_order, op_algebra and op_information only, never op_geometry or "
     "op_statistics, and it is a seeded sample rather than a decision procedure."),
]

MACHINE_CHECKED_CORE = True   # machinecheck.py, 21 of 21 by Z3; see PROOF-ASSISTANT.md
NOVELTY_NOT_CLAIMED = True
CYPHER_NOT_TOUCHED = True
NOTHING_IS_REPAIRED = True


# ---------------------------------------------- 1. definitions, from scratch

def box_of(X, d):
    return [sorted({x[i] for x in X}) for i in range(d)]


def gen(X):
    S = set(X)
    while True:
        new = set()
        for x, y in itertools.combinations(sorted(S), 2):
            for z in (tuple(map(min, x, y)), tuple(map(max, x, y))):
                if z not in S:
                    new.add(z)
        if not new:
            return frozenset(S)
        S |= new


def joinclose(X):
    S = set(X)
    while True:
        new = {tuple(map(max, x, y)) for x, y in itertools.combinations(sorted(S), 2)} - S
        if not new:
            return frozenset(S)
        S |= new


def phi(X, i, j, a):
    c = [y[i] for y in X if y[j] <= a]
    return max(c) if c else None


def stair(X, box):
    X = sorted(X)
    d = len(box)
    P = {(i, j, a): phi(X, i, j, a)
         for i in range(d) for j in range(d) if i != j for a in box[j]}
    return frozenset(x for x in itertools.product(*box)
                     if all(P[(i, j, x[j])] is not None and x[i] <= P[(i, j, x[j])]
                            for i in range(d) for j in range(d) if i != j))


def kdet(S, box, k):
    d = len(box)
    if k >= d:
        return True
    pr = {T: {tuple(x[i] for i in T) for x in S}
          for T in itertools.combinations(range(d), k)}
    return frozenset(x for x in itertools.product(*box)
                     if all(tuple(x[i] for i in T) in pr[T] for T in pr)) == frozenset(S)


def convex(X, box):
    for i, A in enumerate(box):
        P = sorted({x[i] for x in X})
        if any(v not in P for v in A if P[0] <= v <= P[-1]):
            return False
    return True


def majority(x, y, z):
    return tuple(max(min(a, b), min(b, c), min(c, a)) for a, b, c in zip(x, y, z))


# ---------------------------------------------------- 2. the exhaustive suite

FRONTIER = [((3, 3), 9), ((4, 4), 4), ((3, 3, 3), 4), ((2, 2, 2, 2), 5), ((2, 2, 2, 2, 2), 3)]


def exhaustive():
    """T1 over observed boxes, at the stated frontier.  (cases, failures)."""
    cases = fails = 0
    for shape, kmax in FRONTIER:
        allc = list(itertools.product(*[range(a) for a in shape]))
        for k in range(1, kmax + 1):
            for X in itertools.combinations(allc, k):
                X = set(X)
                b = box_of(X, len(shape))
                if len(b) < 2:
                    continue
                cases += 1
                fails += stair(X, b) != gen(X)
    return cases, fails


def witness_check():
    """L3's construction, built rather than inferred.  (cells, failures)."""
    cells = fails = 0
    for shape in ((3, 3), (4, 4)):
        allc = list(itertools.product(*[range(a) for a in shape]))
        for k in range(1, 6):
            for Y in itertools.combinations(allc, k):
                Y = set(Y)
                b = box_of(Y, 2)
                for (a, bb) in stair(Y, b):
                    cells += 1
                    y = next((p for p in Y if p[0] == a), None)
                    z = next((p for p in Y if p[1] == bb), None)
                    u = next((p for p in Y if p[0] <= a and p[1] >= bb), None)
                    v = next((p for p in Y if p[0] >= a and p[1] <= bb), None)
                    if None in (y, z, u, v):
                        fails += 1
                        continue
                    al = (max(y[0], u[0]), max(y[1], u[1]))
                    ga = (max(z[0], v[0]), max(z[1], v[1]))
                    if (al[0], ga[1]) != (a, bb) or al[1] < bb or ga[0] < a \
                       or (min(al[0], ga[0]), min(al[1], ga[1])) != (a, bb):
                        fails += 1
    return cells, fails


def lift_check():
    """L5's conclusion, checked directly.  (sublattices, not-2-determined, majority failures)."""
    n = bad = mbad = 0
    for shape in ((3, 3), (3, 3, 3), (2, 2, 2, 2)):
        allc = list(itertools.product(*[range(a) for a in shape]))
        for k in range(1, 4):
            for X in itertools.combinations(allc, k):
                L = gen(set(X))
                b = box_of(L, len(shape))
                n += 1
                bad += not kdet(L, b, 2)
                for x, y, z in itertools.combinations(sorted(L), 3):
                    if majority(x, y, z) not in L:
                        mbad += 1
    return n, bad, mbad


def convexity_check():
    """N1.  (convex&hold, convex&FAIL, gapped&hold, gapped&FAIL) over DECLARED boxes."""
    ch = cf = gh = gf = 0
    for shape, kmax in (((3, 3), 3), ((4, 4), 3), ((3, 3, 3), 3)):
        box = [list(range(a)) for a in shape]
        allc = list(itertools.product(*box))
        for k in range(1, kmax + 1):
            for X in itertools.combinations(allc, k):
                X = set(X)
                eq = stair(X, box) == gen(X)
                if convex(X, box):
                    ch, cf = ch + eq, cf + (not eq)
                else:
                    gh, gf = gh + eq, gf + (not eq)
    return ch, cf, gh, gf


def bridge(n=400, seed=17):
    """Section 6.  (tested, order+algebra agree, information agrees)."""
    import necindex          # its loader registers the module before exec,
    cy = necindex.cypher     # which cypher.py's @dataclass requires
    opts = {"statistics_order": 2, "algebra_budget": 200000}
    rnd = random.Random(seed)
    tot = oa = inf = 0
    for _ in range(n):
        d = rnd.randint(2, 4)
        alpha = [rnd.randint(2, 3) for _ in range(d)]
        allc = list(itertools.product(*[range(a) for a in alpha]))
        X = sorted(rnd.sample(allc, rnd.randint(2, min(len(allc), 9))))
        co = tuple("c%d" % i for i in range(d))
        vo = {co[i]: sorted({c[i] for c in X}) for i in range(d)}
        ix = cy.Index("b", co, X, value_order=vo)
        Xr = [tuple(ix.code[i][v] for i, v in enumerate(c)) for c in X]
        b = box_of(Xr, d)
        o, _ = cy.op_order(ix, opts)
        a, _ = cy.op_algebra(ix, opts)
        I, _ = cy.op_information(ix, opts)
        if o is None:
            continue
        tot += 1
        oa += frozenset(o) == stair(Xr, b) and frozenset(a) == gen(Xr)
        inf += frozenset(I) == joinclose(Xr)
    return tot, oa, inf


INFO_WITNESS = [(0, 0, 0), (0, 1, 1), (1, 0, 1)]


# ------------------------------------------------------------------- report

def report():
    print(__doc__)
    print("=" * 79)
    print("THE PROVENANCE LEDGER")
    print("=" * 79)
    print()
    for what, status, note in PROVENANCE:
        print("  %-34s %s" % (what, status))
        print("      %s" % note)
    print()
    print("=" * 79)
    print("MEASURED")
    print("=" * 79)
    print()
    c, f = exhaustive()
    print("  T1, exhaustive over observed boxes")
    print("      %-42s %d" % ("cases", c))
    print("      %-42s %d" % ("failures", f))
    cc, cf = witness_check()
    print("  L3, the construction built rather than inferred")
    print("      %-42s %d" % ("cells of R", cc))
    print("      %-42s %d" % ("failures", cf))
    n, bad, mbad = lift_check()
    print("  L5, checked directly")
    print("      %-42s %d" % ("generated sublattices", n))
    print("      %-42s %d" % ("not 2-determined", bad))
    print("      %-42s %d" % ("majority-term failures", mbad))
    ch, cfl, gh, gf = convexity_check()
    print("  N1, over DECLARED boxes")
    print("      %-42s %d" % ("convex and holds", ch))
    print("      %-42s %d" % ("convex and FAILS", cfl))
    print("      %-42s %d" % ("gapped and holds", gh))
    print("      %-42s %d" % ("gapped and FAILS", gf))
    t, oa, inf = bridge()
    print("  section 6, the bridge to the running program")
    print("      %-42s %d" % ("indexes tested", t))
    print("      %-42s %d" % ("op_order and op_algebra agree", oa))
    print("      %-42s %d" % ("op_information == join-closure", inf))
    print()
    X = set(INFO_WITNESS)
    b = box_of(X, 3)
    J = joinclose(X)
    pr = {T: {tuple(x[i] for i in T) for x in J} for T in itertools.combinations(range(3), 2)}
    reb = sorted(x for x in itertools.product(*b)
                 if all(tuple(x[i] for i in T) in pr[T] for T in pr))
    print("  the information witness")
    print("      %-42s %s" % ("X", sorted(X)))
    print("      %-42s %s" % ("J(X)", sorted(J)))
    print("      %-42s %s" % ("invented by the pairwise rebuild", sorted(set(reb) - J)))
    for nm, op in (("order", lambda: stair(X, b)), ("algebra", lambda: gen(X))):
        print("      %-42s %s" % ("%s 2-determined on the same X" % nm, kdet(op(), b, 2)))
    print()
    print("=" * 79)
    print("VERDICT")
    print("=" * 79)
    print()
    print("  The formalization is ours and the theorem probably is not.  A 2008")
    print("  Discrete Mathematics paper asks this exact question in this exact")
    print("  setting, and it could not be opened.  PRIOR-ART-PROBABLE, UNREAD.")
    print()
    print("  What survives as ours: the four-witness construction, the")
    print("  order-convexity hypothesis that replaces this thread's mistaken")
    print("  necessity claim, the one-directional failure off the chains, the")
    print("  join-closure identity, and the bridge from the mathematics to the")
    print("  running program.  Nothing here is machine-checked.")
    print()


# ----------------------------------------------------------------- selftest

PINS = {"cases": 36252, "cells": 54392, "sublattices": 4128,
        "ch": 1853, "gh": 632, "gf": 1643, "bridge_n": 400}


def selftest(emit=False):
    fails = []

    def chk(label, got, want):
        if emit:
            print("  EMIT %-56s %r" % (label, got))
            return
        ok = got == want
        print("  [%s] %-58s %s" % ("ok" if ok else "XX", label, got))
        if not ok:
            fails.append((label, got, want))

    print("decomposable.py --selftest" if not emit else "decomposable.py --emit")
    print()

    c, f = exhaustive()
    chk("T1 exhaustive: cases", c, PINS.get("cases"))
    chk("T1 exhaustive: FAILURES", f, 0)
    cc, cf = witness_check()
    chk("L3 construction: cells built", cc, PINS.get("cells"))
    chk("L3 construction: FAILURES", cf, 0)
    n, bad, mbad = lift_check()
    chk("L5 direct: sublattices", n, PINS.get("sublattices"))
    chk("L5 direct: not 2-determined", bad, 0)
    chk("L5 direct: majority-term failures", mbad, 0)
    ch, cfl, gh, gf = convexity_check()
    chk("N1: convex and holds", ch, PINS.get("ch"))
    chk("N1: convex and FAILS -- must be 0", cfl, 0)
    chk("N1: gapped and holds", gh, PINS.get("gh"))
    chk("N1: gapped and FAILS", gf, PINS.get("gf"))
    chk("N1: so convexity is SUFFICIENT", cfl == 0, True)
    chk("N1: and NOT necessary", gh > 0, True)
    t, oa, inf = bridge()
    chk("bridge: indexes tested", t, PINS.get("bridge_n"))
    chk("bridge: order and algebra agree", oa, PINS.get("bridge_n"))
    chk("bridge: information == join-closure", inf, PINS.get("bridge_n"))

    X = set(INFO_WITNESS)
    b = box_of(X, 3)
    J = joinclose(X)
    chk("information witness: |J(X)|", len(J), 4)
    chk("information witness: NOT 2-determined", kdet(J, b, 2), False)
    chk("information witness: order IS", kdet(stair(X, b), b, 2), True)
    chk("information witness: algebra IS", kdet(gen(X), b, 2), True)
    chk("L7: J(X) subset <X>", J <= gen(X), True)

    chk("the core IS machine-checked (machinecheck.py, Z3)", MACHINE_CHECKED_CORE, True)
    chk("no novelty is claimed", NOVELTY_NOT_CLAIMED, True)
    chk("cypher.py is not touched", CYPHER_NOT_TOUCHED, True)
    chk("nothing is repaired", NOTHING_IS_REPAIRED, True)
    chk("provenance rows", len(PROVENANCE), 10)
    chk("and the first one says PRIOR ART, READ -- the paper was obtained",
        PROVENANCE[0][1].startswith("PRIOR ART, READ"), True)

    if emit:
        return 0
    print()
    if fails:
        for lab, g, w in fails:
            print("  FAIL %s: got %r want %r" % (lab, g, w))
        print("\nSELFTEST FAIL (%d)" % len(fails))
        return 1
    print("SELFTEST PASS")
    return 0


if __name__ == "__main__":
    if "--provenance" in sys.argv:
        for what, status, note in PROVENANCE:
            print("%-34s %-32s %s" % (what, status, note))
        sys.exit(0)
    sys.exit(selftest(emit="--emit" in sys.argv) if
             ("--selftest" in sys.argv or "--emit" in sys.argv) else (report() or 0))
