#!/usr/bin/env python3
r"""
stock.py -- THE DESTINATION STOCK CONSTRAINT, COSTED FOR THE FIRST TIME.
Phosphorus binds (on these point values), a carbonaceous chondrite beats
Earth's continental crust by forty, and the tree's own claim that the stock "had
to travel" is not established.  (CORRECTED, DOCKET 67: this read "beats a
planet by fifty-three" -- R&G cover Earth's continental crust only, and this
file's own ranking gives 40.0.)

M: "It carries state, not substance.  No mass, no energy moves; matching matter
must already be at the far end -- correct because transition can only take place
if the same elements/'stock' are available at the destination point for the
state to be assembled at the destination."

    python3 stock.py             the reading
    python3 stock.py --selftest  fixtures, stdlib only

M IS RIGHT, AND THE TREE STATES THIS WITHOUT EVER COSTING IT.  `paper/CLAIMS.md`
line 4648 (4629 when this file was written; CORRECTED, DOCKET 67) says,
verbatim:

    "And it carries state, not substance.  Teleportation writes a quantum state
     onto matter ALREADY AT THE DESTINATION.  No mass moves.  No energy moves.
     For an object to arrive, an identical stock of matter must already be there
     -- and that had to travel."

The first four sentences are exactly M's point.  The clause after the dash is a
separate claim, it is stronger, and section 4 shows it is not established.
Before this file the tree held no abundance data of any kind: `grep` for
Asplund, Lodders, "elemental" or "abundance" across `research/warp-drive/`
returns that one line of prose and nothing else.  So the constraint was
STATED AND UNCOSTED.  This file costs it.

===============================================================================
1. THE CONSTRAINT, STATED FORMALLY
===============================================================================

A payload is a composition vector p over elements, in mass fractions.  A
destination holds stock of composition s.  To assemble p you process a mass M of
stock, which yields M*s_e of element e, so the constraint is

        p_e  <=  M * s_e        for every element e

and the cheapest sufficient M is the PROCESSING FACTOR

        M(p, s)  =  max_e  ( p_e / s_e )

**IT IS A MAXIMUM, NOT A SUM.**  One scarce element sets the whole bill, and
every other element arrives in surplus.  That is why the answer is a single
BINDING ELEMENT rather than a blend, and why enriching the abundant elements
buys nothing at all.

**AND THE ASSEMBLABLE SET IS AN ORDER IDEAL.**  Fix a stock s and a budget M.
Then A(s, M) = { p : p_e <= M s_e for all e } is a DOWN-SET in the componentwise
order -- if p <= p' and p' is assemblable then so is p, immediately -- and it is
closed under componentwise MAX as well, since max(p, q)_e <= M s_e whenever both
are.  So it is a down-set closed under join: a PRINCIPAL ideal, generated by
M*s.  `is_order_ideal()` and `is_join_closed()` verify both by exhaustion on a
sampled grid rather than by assertion.  Register 66's downward-closure question
therefore has a trivial answer HERE, and that is worth saying precisely because
the tree's other indexes make it hard.

===============================================================================
2. WHAT IT COSTS -- PHOSPHORUS BINDS
===============================================================================

For a 70 kg human against the present-day SOLAR photosphere (Asplund 2009),
standing in for raw stellar material:

    binding element    P       1.9105e3 kg processed per kg of payload
    runner-up          Li      1.7531e3          -- only 1.090x behind
    then               K       6.518e2           -- 2.93x behind
    a 70 kg human                             133.7 TONNES of source material

THE BINDER IS A POINT-VALUE RESULT, AND THE DATA CAN MOVE IT.  P leads Li by
0.0374 dex, while A09's own sigma(Li) is 0.10 dex: under A09's errors Li binds
with probability 0.360, and photospheric Li 0.05 dex lower makes Li the binder
at 1967.3.  On the payload side the binder passes to Li if body P is below
715.7 g (-8.24 %) or body Li above 7.629 mg (+8.98 %) (all computed by DOCKET
67).  The magnitude stays 1.6e3-2.2e3 throughout.  And the solar photosphere
is not a gas giant's stock: a gas giant has not burned its lithium, so with
unburned Li the runner-up changes (Li/P 0.0057 instead of 0.92) while P still
binds.  (CORRECTED, DOCKET 67: this read "against raw stellar or gas-giant
material" with the binder stated bare.)

**THE RUNNER-UP MATTERS, AND IT IS NOT THE ONE THIS FILE FIRST NAMED.**  The
superseded draft reported potassium at 1.32x on a table that carried TWICE the
reference adult's potassium.  On ICRP's datum potassium falls to 2.93x and the
"two scarcities at the same scale" reading fails with it.  **The true co-binder
is LITHIUM, at 1.090x on these point values** -- and section 2a says why that
is astrophysics rather than a coincidence.

===============================================================================
2a. AND WHY LITHIUM
===============================================================================

Asplund gives lithium photospheric 1.05 against meteoritic 3.26: a 2.21-dex gap,
a factor of 162, the largest photospheric DEFICIT in the table (next is Pb, at
0.29).  **It is not a disagreement.**  Lithium burns at about 2.5 MK; the base of
the Sun's convection zone is about 2.20 MK today (AG26 p.52), and A09 p.10
says the depletion "requires additional mixing below the convection zone".  So
the photosphere really is 162x poorer in lithium than the material the solar
system condensed from.  Both numbers are right about different reservoirs.
(CORRECTED, DOCKET 67: this read "the largest disagreement in the table" --
on |ph - met| He, Ne, Ar, Kr, Xe and H are larger -- and "The Sun's
convective envelope reaches 2.5 MK, where lithium burns", which is not A09's
mechanism.)

    SO A DESTINATION'S PROCESSING FACTOR IS NOT A FUNCTION OF ITS ELEMENTS.  IT
    IS A FUNCTION OF ITS THERMAL HISTORY.

A sun-like star has burned its photospheric lithium; a chondrite and a gas
giant have not.  `SOURCES["lithium"]` carries
the caution, and `stockgate.py` section 4 works the consequence out in full.

===============================================================================
3. AND THE DESTINATION TYPE DOMINATES EVERYTHING
===============================================================================

    source                              binding   factor      70 kg human
    solar photosphere    (Asplund 09)   P         1.9105e3    133.7  tonnes
    Earth continental crust (R&G 03)    N         4.2805e2     30.0  tonnes
    CI carbonaceous chondrite (L 03)    P         1.0701e1      0.75 tonnes

(The crust and chondrite tables carry those citations; how far their values are
the cited ones is in section 6.)

**A CARBONACEOUS CHONDRITE BEATS RAW COSMIC GAS BY 178.5x AND EARTH'S
CONTINENTAL CRUST BY 40.0x**, and this file's reading of why is that a planet
differentiates: Earth's crust is a silicate residue that outgassed its
volatiles.  (R&G tabulate a concentration; the cause is this file's reading,
and R&G's crust excludes the atmosphere, which holds most of Earth's
surface-accessible nitrogen.)  Its binding element is NITROGEN at 428 -- while
crust C exceeds 8.889 x crust N, C > 498 ppm at N = 56 ppm, on a C value R&G
do not give; at C = 400 ppm the crust binds on carbon at 570.7 -- and N is
**40.4 times worse than this table's phosphorus** (17.98 on R&G's own bulk N
and P) -- a superseded draft of this file said "six hundred times", which was
wrong by an order of magnitude and is corrected here.  A chondrite never
differentiated, so it still holds C, N, H, P and S together, and **binds on
PHOSPHORUS, not nitrogen, on these point values**; the old reading of nitrogen
came from a payload table carrying N 1.25x high and P 1.11x low.  The binder
here turns on CI nitrogen against a crossover of 2400 ppm, which lies inside
PON14's 2-sigma band (2065-3835 ppm) and MS95's factor-2 band: at CI N =
1965 ppm the chondrite binds on N at 13.07, and under ICRP 110's whole-body
composition on carbon.  The factor stays 8.3-13.1 on every composition
computed (DOCKET 67).

    THE OPTIMAL ARRIVAL NODE IS AN ASTEROID, NOT A PLANET -- on Earth's
    continental crust as the planet, and on the hypothesis that an asteroid's
    accessible stock is CI-like (Ryugu and Bennu bulk not read: OPEN).

That is a specific, computed engineering conclusion and it inverts the intuitive
answer.  `rank_destinations()` produces the table.

    CORRECTED (DOCKET 67).  This section read "a rocky crust", "the reason is
    that a planet differentiates", "the crust's own phosphorus", "binds on
    PHOSPHORUS, not nitrogen" and "AN ASTEROID, NOT A PLANET" with no datum
    uncertainty, no carbon condition and no scope qualifier.  No figure
    moved.

**THE DIFFUSE MEDIUM IS THE ONE THAT FAILS.**  At 1 proton/cm^3 -- the all-phase
space average, not the warm neutral medium (0.2-0.5 cm^-3; Ferriere) -- the
interstellar medium holds the right elements in roughly photospheric ratios
(A09 sec. 4.2, after diffusion and GCE corrections, and with unburned Li; P
binds either way) and in no useful concentration: `ism_sweep_volume()` returns
7.18e25 m^3 per 70 kg human, a sphere of radius 2.58e5 km -- two thirds of the
Earth-Moon distance, swept, per person.  That volume divides a He-inclusive
feedstock by rho = n m_p, without the x1.42 helium/metal mass factor (Ferriere:
rho = 1.42 m_p n_H), so at fixed n_H it is 1.42x too large; at every density
read for the local medium the sweep is larger still.  Elements existing is not
stock.  (CORRECTED, DOCKET 67: the phase label, the ratio hypothesis and the
helium factor.)

===============================================================================
4. THE CLAUSE THAT IS NOT ESTABLISHED
===============================================================================

`CLAIMS.md` adds "-- and that had to travel."  **THAT DOES NOT FOLLOW AND THIS
FILE RECORDS IT AS A FINDING**, reading "had to travel" as "had to travel FROM
THE TRAVELLER'S ORIGIN" -- this file's interpretation.  Nothing requires the
destination stock to have come from the origin.  Galactic chemical evolution
makes carbon, nitrogen and phosphorus in dying stars and ejects them, and the
next generation forms from that gas (Kobayashi, Karakas & Lugaro 2020): the
atoms did travel, as stellar ejecta, just not from the traveller's origin.  The
mechanism stands; the accounting for P is incomplete -- GCE models generally
under-predict it (Maas+ 2022) -- and P has been measured in only about 1 % of
catalogued nearby stars, with real star-to-star scatter (Hinkel+ 2020).
`stock_need_not_travel()` gives the counterexample with a number: a CI chondrite
at the destination supplies a human payload at a processing factor of 10.70,
and no part of it was shipped from the origin.  That a CI-like body is present
and accessible at ANOTHER star is a planet-formation hypothesis, not a GCE
output, and is OPEN (the one exoplanetary source read, Swan+ 2023, finds dry
rock and measures no P or N); and if P scales with the host's [P/H] the factor
is 10.70 x 10^(-D).  The finding needs only one stocked destination whose stock
was not shipped from the origin, and the solar system's own CI chondrites are
one.  (CORRECTED, DOCKET 67: this read "puts carbon, nitrogen and phosphorus
into every enriched star system by nucleosynthesis and accretion" and "no part
of it was shipped from anywhere" -- a universal the sources do not state, an
unstated CI-body hypothesis, and an unnamed reading of the clause.)

The weaker true statement is: **the stock must EXIST, ASSEMBLED AND ACCESSIBLE,
at the arrival point.**  That is a real constraint.  It is not a transport cost.

RECORDED, NOT REPAIRED.  `CLAIMS.md` is not edited by this file.

===============================================================================
5. WHAT IT DOES TO THE EIGHT-VALUE COORDINATE
===============================================================================

`unified.py` section 5 numbers the device's parameters, and coordinate 7 is
**B, the declared arrival**, gated by `transit.py` part 1.  The constraint above
says B IS NOT FREE.  A declared arrival must name a site holding accessible
stock, which is a sub-constraint the coordinate did not previously carry.

**AND THE TREE ALREADY FOUND A SECOND, INDEPENDENT REQUIREMENT OF THE SAME
SHAPE.**  `arrival.py` route 1 prices braking by reverse slingshot and notes it
"needs a deflector AT THE DESTINATION, which turns the drive into a NETWORK with
nodes."  Two requirements, arrived at from different directions -- one about
stopping, one about matter -- and both force the same topology.

    A TRANSITION DEVICE IS NOT A VEHICLE.  IT IS A NETWORK, AND ITS NODES ARE
    SITED WHERE THE STOCK IS.

That agrees with `transit.py`'s own conclusion that the corridor must be
traversed once in order to exist: the first trip to a node is the expensive one,
and it is the trip that builds the node.

===============================================================================
6. WHAT THIS FILE REFUSES
===============================================================================

**TO TREAT THE ABUNDANCES AS MEASURED HERE.**  They are CITED: Asplund et al.
2009 photospheric, Rudnick & Gao 2003 continental crust, Lodders 2003 CI
chondrite.  Every processing factor is COMPUTED from them.  `SOURCES` carries
the citations and `provenance()` prints them beside the numbers.

    CORRECTED (DOCKET 67): HOW FAR THE TABLES ARE THE CITED ONES.  CRUST: of
    16 values, 5 match R&G's bulk crust within 3 % (Si, Al, Na via oxide
    stoichiometry; Zn, Li), 8 match neither R&G column (Fe, Ca, Mg, K, P, S,
    Cl, N), and O, C and H are values R&G do not print.  CHONDRITE: labelled
    Lodders 2003, it is an MS95/PON14 blend -- within 0.5 % it matches L03 on
    7 of 39 elements and MS95 on 19 of 58; its N 3180 ppm is exactly MS95's,
    and its P 1040 ppm matches none of L03, MS95 or PON14.  ATOMIC_MASS is the
    terrestrial standard atomic weights, uncited, with interval standards
    carried as single values; applied to solar abundances they put solar
    Ar's mass fraction 9.2 % high (A09's solar-system Ar is 36.275, not
    39.948).  HUMAN is ICRP 23's Reference Man -- male, 20-30 y -- amended by
    ICRP 89, and which rows are ICRP's and which Emsley's is not recorded.
    None of this moves a binder except as section 3 states.

**TO CALL THE PROCESSING FACTOR AN ENERGY COST.**  It is a mass of feedstock.
Separating an element from a matrix costs energy that depends on the matrix and
the method, and none of that is computed here.

**TO CLAIM THE STOCK CONSTRAINT IS A BARRIER.**  It is not.  133.7 tonnes at
the solar photosphere sits 3.356e22 (10^22.53) below the Fuchs shell's
4.4886e27 kg, and 0.749 tonnes at a chondrite 5.992e24 (10^24.78) below it
(`against_the_shell()`, computed).  It is a SITE-SELECTION CRITERION, and
calling it more would be over-representation.

**TO SETTLE WHETHER ASSEMBLY IS POSSIBLE AT ALL.**  This file costs the
FEEDSTOCK for an assembly it does not design.  Sorting 1.337e5 kg of
photospheric feedstock into 70 kg of atoms, and writing a quantum state onto
them, is not addressed, and `transit.py`'s two-classical-bit ledger is
untouched by anything here.

    CORRECTED (DOCKET 67, follow-up D): these two paragraphs read "120 tonnes,
    or 0.7 tonnes at a chondrite, sits about 25 orders of magnitude below the
    Fuchs shell" and "writing a quantum state onto 1.2e5 kg of sorted atoms".
    The file computes 133.7 t and 0.749 t, at 10^22.53 and 10^24.78 below the
    shell -- "about 25" held for the chondrite only -- and the 1.337e5 kg is
    feedstock processed, not atoms sorted (the payload is 70 kg).  The selftest
    row "25+ orders" checked > 1e22; it now pins both computed ratios.  No
    verdict moved: the constraint is a site-selection criterion either way.
"""

import math
import sys

#: Provenance for every table below.  Cited, never measured here.
SOURCES = {
    "cosmic": "Asplund, Grevesse, Sauval & Scott (2009), ARA&A 47, 481 -- "
              "photospheric log eps, H = 12",
    "crust": "Rudnick & Gao (2003), Treatise on Geochemistry 3, 1 -- "
             "bulk continental crust (Earth's; 8 of 16 values match neither "
             "R&G column, C/O/H not R&G's -- DOCKET 67)",
    "chondrite": "Lodders (2003), ApJ 591, 1220 -- CI carbonaceous chondrite "
                 "(as labelled; the values are an MS95/PON14 blend -- DOCKET 67)",
    "human": "ICRP Publication 23 / Emsley, Nature's Building Blocks -- "
             "Reference Man (male, 20-30 y; amended by ICRP 89), mass fractions",
}

#: Asplund 2009 photospheric abundances, log eps with H = 12.
A09 = {"H": 12.00, "He": 10.93, "Li": 1.05, "C": 8.43, "N": 7.83, "O": 8.69,
       "Ne": 7.93,
       "Na": 6.24, "Mg": 7.60, "Al": 6.45, "Si": 7.51, "P": 5.41, "S": 7.12,
       "Cl": 5.50, "K": 5.03, "Ca": 6.34, "Fe": 7.50, "Zn": 4.56}

#: Terrestrial standard atomic weights, uncited, interval standards as single
#: values (DOCKET 67).  Used for SOLAR abundances in cosmic(), where A09 Table 3's
#: solar-system weights differ -- Ar 36.275, not 39.948 -- so solar Ar's mass
#: fraction comes out 9.2 % high; no binder moves.  Values unchanged.
ATOMIC_MASS = {"H": 1.008, "He": 4.003, "Li": 6.94, "C": 12.011, "N": 14.007, "O": 15.999,
               "Ne": 20.180, "Na": 22.990, "Mg": 24.305, "Al": 26.982,
               "Si": 28.085, "P": 30.974, "S": 32.06, "Cl": 35.45,
               "K": 39.098, "Ca": 40.078, "Fe": 55.845, "Zn": 65.38}

#: Labelled R&G 2003 bulk crust; 8 of 16 values match neither R&G column, and
#: O, C, H are not R&G quantities (DOCKET 67, recorded; values unchanged).
CRUST = {"O": 0.461, "Si": 0.282, "Al": 0.0823, "Fe": 0.0563, "Ca": 0.0415,
         "Na": 0.0236, "Mg": 0.0233, "K": 0.0209, "H": 0.0014, "P": 0.00105,
         "C": 0.002, "S": 0.00035, "Cl": 0.00017, "N": 0.00006,
         "Zn": 0.00007, "Li": 1.6e-5}

#: Labelled Lodders 2003 CI; an MS95/PON14 blend (DOCKET 67, recorded; values
#: unchanged).  Point values: CI N carries PON14's 2-sigma band 2065-3835 ppm,
#: which contains the 2400 ppm P/N binder crossover.
CHONDRITE = {"O": 0.464, "Fe": 0.185, "Si": 0.107, "Mg": 0.0965, "S": 0.0541,
             "C": 0.0350, "H": 0.0202, "Ca": 0.00911, "Al": 0.00860,
             "Na": 0.00500, "N": 0.00318, "P": 0.00104, "K": 0.000555,
             "Cl": 0.000698, "Zn": 0.000312, "Li": 1.5e-6}

#: REPAIRED 2026-09-20 to ICRP Reference Man, after stockgate.py's audit.  The
#: superseded row was O .650 C .185 H .095 N .032 Ca .015 P .010 K .0040
#: S .0030 Na .0015 Cl .0015 Mg .0005 Fe .00006 Zn .00003 -- whose POTASSIUM
#: was 280 g in a 70 kg adult against ICRP's 140 g, TWICE HIGH, and whose N and
#: P were off by 1.25x and 1.11x in opposite directions, which flipped the
#: chondrite's binding element.  LITHIUM is added because it is the true
#: runner-up and omitting it is what let the old file name potassium.
HUMAN = {"O": 0.613533, "C": 0.228291, "H": 0.099877, "N": 0.025683,
         "Ca": 0.014268, "P": 0.011129, "K": 0.001998, "S": 0.001998,
         "Na": 0.001427, "Cl": 0.001355, "Mg": 0.000271, "Fe": 0.000060,
         "Zn": 0.000033, "Li": 9.988e-08}

#: 1 proton/cm^3, as arrival.py uses: the all-phase space average (Ferriere),
#: NOT the warm neutral medium (0.2-0.5 cm^-3) this line once called it.
#: rho = n m_p omits the x1.42 helium/metal mass factor, and m_p is CODATA 2018
#: truncated to 9 figures (-2.21e-9 relative).  Value unchanged (CORRECTED,
#: DOCKET 67).
RHO_ISM = 1.0e6 * 1.67262192e-27

#: TARGET-1-RESULT.md's shell, for the scale comparison in section 6.
FUCHS_SHELL_KG = 4.4886e27


def cosmic():
    """Mass fractions from A09's log-eps abundances.  COMPUTED, not tabulated --
    on terrestrial atomic weights, which put solar Ar 9.2 % high (DOCKET 67)."""
    n = {e: 10.0 ** (v - 12.0) for e, v in A09.items()}
    m = {e: n[e] * ATOMIC_MASS[e] for e in n}
    tot = sum(m.values())
    return {e: m[e] / tot for e in m}


# DOCKET 67: the "cosmic" stock is the present-day SOLAR photosphere.  The row
# was labelled "stellar / gas giant"; a gas giant has not burned its Li.
DESTINATIONS = (("solar photosphere", "cosmic"),
                ("Earth continental crust", "crust"),
                ("CI carbonaceous chondrite", "chondrite"))


def stock_of(key):
    return {"cosmic": cosmic(), "crust": CRUST, "chondrite": CHONDRITE}[key]


# ------------------------------------------------------------ the constraint

def processing_factors(payload=None, source=None):
    """{element: p_e / s_e} -- how much stock each element alone would demand.

    An element absent from the source returns infinity: it cannot be supplied at
    any budget, and that is a different failure from being merely scarce.
    """
    payload = HUMAN if payload is None else payload
    source = cosmic() if source is None else source
    out = {}
    for e, p in payload.items():
        s = source.get(e, 0.0)
        out[e] = float("inf") if s <= 0.0 else p / s
    return out


def binding_element(payload=None, source=None):
    """(element, factor) -- the single element that sets the whole bill.

    It is a MAX over elements, so exactly one element is binding and every
    other arrives in surplus.
    """
    f = processing_factors(payload, source)
    e = max(f, key=lambda k: f[k])
    return e, f[e]


def feedstock_kg(payload_kg=70.0, payload=None, source=None):
    """Mass of source material to assemble a payload of the given mass."""
    return payload_kg * binding_element(payload, source)[1]


def rank_destinations(payload_kg=70.0, payload=None):
    """[(name, binding element, factor, tonnes)] worst first."""
    rows = []
    for name, key in DESTINATIONS:
        e, f = binding_element(payload, stock_of(key))
        rows.append((name, e, f, payload_kg * f / 1000.0))
    return sorted(rows, key=lambda r: -r[2])


def ism_sweep_volume(payload_kg=70.0, payload=None):
    """(volume m^3, equivalent sphere radius m) of diffuse ISM per payload.

    The elements are present in cosmic ratios; what is absent is concentration.
    """
    v = feedstock_kg(payload_kg, payload, cosmic()) / RHO_ISM
    return v, (3.0 * v / (4.0 * math.pi)) ** (1.0 / 3.0)


def stock_need_not_travel():
    """The counterexample to CLAIMS.md's "and that had to travel".

    Returns (processing factor at a CI chondrite, the citation).  Galactic
    chemical evolution placed that stock -- its atoms travelled as stellar
    ejecta, not from the traveller's origin.  That a CI-like body is present
    and accessible at another star is a hypothesis, OPEN; the solar system's
    own CI chondrites are one stocked destination (DOCKET 67).
    """
    return binding_element(HUMAN, CHONDRITE)[1], SOURCES["chondrite"]


def against_the_shell(payload_kg=70.0, stock=None):
    """How far below the Fuchs shell the whole stock bill sits.  Not a barrier.
    stock defaults to the solar photosphere (the costliest destination)."""
    return FUCHS_SHELL_KG / feedstock_kg(payload_kg, HUMAN,
                                         cosmic() if stock is None else stock)


# ------------------------------------------- the order-ideal property, verified

def _grid(source, budget, step=4):
    """A sampled lattice of candidate payloads under the budget, for exhaustion."""
    els = sorted(source)[:6]
    caps = [budget * source[e] for e in els]
    pts = []

    def rec(i, cur):
        if i == len(els):
            pts.append(tuple(cur))
            return
        for k in range(step + 1):
            rec(i + 1, cur + [caps[i] * k / step])
    rec(0, [])
    return els, pts


def is_order_ideal(budget=100.0, step=3):
    """Exhaust: is the assemblable set a DOWN-SET in the componentwise order?

    Verified by checking every ordered pair on the sampled grid, not asserted.
    """
    src = cosmic()
    els, pts = _grid(src, budget, step)
    cap = [budget * src[e] for e in els]
    ok = lambda p: all(p[i] <= cap[i] * (1 + 1e-12) for i in range(len(els)))
    for a in pts:
        for b in pts:
            if all(a[i] <= b[i] for i in range(len(els))) and ok(b) and not ok(a):
                return False
    return True


def is_join_closed(budget=100.0, step=3):
    """Exhaust: is it closed under componentwise MAX?  A principal ideal is."""
    src = cosmic()
    els, pts = _grid(src, budget, step)
    cap = [budget * src[e] for e in els]
    ok = lambda p: all(p[i] <= cap[i] * (1 + 1e-12) for i in range(len(els)))
    for a in pts:
        if not ok(a):
            continue
        for b in pts:
            if not ok(b):
                continue
            if not ok(tuple(max(a[i], b[i]) for i in range(len(els)))):
                return False
    return True


def provenance():
    return [(k, v) for k, v in sorted(SOURCES.items())]


# ------------------------------------------------------------------- reading

def report():
    print(__doc__.split("=====", 1)[0].strip())
    print()
    print("=" * 74)
    print("2.  WHAT IT COSTS -- AGAINST RAW STELLAR MATERIAL")
    print("=" * 74)
    f = processing_factors()
    for e in sorted(f, key=lambda k: -f[k]):
        print("   %-3s payload %.3e   stock %.3e   -> %.4e kg / kg"
              % (e, HUMAN[e], cosmic()[e], f[e]))
    e, v = binding_element()
    print("\n   BINDING ELEMENT   %s at %.4e" % (e, v))
    print("   a 70 kg human     %.4e kg = %.1f tonnes" % (feedstock_kg(),
                                                          feedstock_kg() / 1000))
    print()
    print("=" * 74)
    print("3.  THE DESTINATION TYPE DOMINATES")
    print("=" * 74)
    print("   %-28s %-8s %-12s %s" % ("source", "binding", "factor", "tonnes"))
    for name, el, fac, t in rank_destinations():
        print("   %-28s %-8s %.4e   %8.2f" % (name, el, fac, t))
    r = rank_destinations()
    print("\n   a chondrite beats raw cosmic gas by %.0fx and a crust by %.0fx"
          % (r[0][2] / r[-1][2], r[1][2] / r[-1][2]))
    v, rad = ism_sweep_volume()
    print("\n   diffuse ISM at 1 proton/cm^3: sweep %.3e m^3 per 70 kg human," % v)
    print("   a sphere of radius %.3e km (Earth-Moon is 3.844e5 km)."
          % (rad / 1000))
    print("   ELEMENTS EXISTING IS NOT STOCK.")
    print()
    print("=" * 74)
    print("4.  THE CLAUSE THAT IS NOT ESTABLISHED")
    print("=" * 74)
    fac, cite = stock_need_not_travel()
    print("   CLAIMS.md (line 4648) adds \"-- and that had to travel\", read")
    print("   here as 'from the traveller's origin'.")
    print("   Counterexample: a CI chondrite supplies a human payload at a")
    print("   processing factor of %.2f, placed by galactic chemical evolution" % fac)
    print("   and not shipped from the origin -- where a CI-like body is present")
    print("   and accessible (OPEN at another star).   %s" % cite)
    print("   RECORDED, NOT REPAIRED.")
    print()
    print("=" * 74)
    print("5.  THE ORDER STRUCTURE, AND THE SCALE")
    print("=" * 74)
    print("   assemblable set is a down-set          %s" % is_order_ideal())
    print("   and closed under componentwise max     %s" % is_join_closed())
    print("   -> a PRINCIPAL ideal generated by M*s.")
    print()
    print("   the whole stock bill sits %.3e below the Fuchs shell."
          % against_the_shell())
    print("   IT IS A SITE-SELECTION CRITERION, NOT A BARRIER.")
    print()
    for k, v in provenance():
        print("   %-10s %s" % (k, v))


# ------------------------------------------------------------------ fixtures

def selftest():
    bad = []

    def chk(what, got, want):
        ok = got == want
        if not ok:
            bad.append((what, got, want))
        print("   %-60s %s" % (what, "ok" if ok else "FAIL %r != %r"
                               % (got, want)))

    print("stock.py fixtures  (stdlib only)")

    # -- the abundance derivation --------------------------------------------
    c = cosmic()
    chk("cosmic mass fractions sum to 1", round(sum(c.values()), 12), 1.0)
    chk("hydrogen dominates, to 4 digits", float("%.4g" % c["H"]), 0.7375)
    chk("helium next", float("%.4g" % c["He"]), 0.2493)
    chk("and phosphorus is the scarce one of the biogenic set",
        min(("C", "N", "O", "P", "S"), key=lambda e: c[e]), "P")
    chk("but LITHIUM is scarcer still in a photosphere, by 1.02e5",
        float("%.3g" % (c["P"] / c["Li"])), 102000.0)
    chk("human fractions sum to ~1", round(sum(HUMAN.values()), 4), 0.9999)

    # -- the constraint is a MAX, not a sum -----------------------------------
    chk("binding element against stellar material is P", binding_element()[0], "P")
    chk("at this factor", float("%.5g" % binding_element()[1]), 1910.5)
    chk("LITHIUM is the runner-up, within 1.09x -- not potassium",
        (sorted(processing_factors(), key=lambda e: -processing_factors()[e])[1],
         float("%.3g" % (binding_element()[1]
                         / sorted(processing_factors().values())[-2]))),
        ("Li", 1.09))
    chk("and potassium, repaired to ICRP, falls to third at 2.93x",
        (sorted(processing_factors(), key=lambda e: -processing_factors()[e])[2],
         float("%.3g" % (binding_element()[1]
                         / sorted(processing_factors().values())[-3]))),
        ("K", 2.93))
    chk("the repaired potassium is 140 g in a 70 kg adult, not 280",
        int(round(HUMAN["K"] * 70 * 1000)), 140)
    chk("the factor is the MAX, not the sum -- doubling an ABUNDANT element "
        "changes nothing",
        binding_element(dict(HUMAN, H=HUMAN["H"] * 2))[1],
        binding_element()[1])
    chk("but doubling the BINDING element doubles the bill",
        float("%.6g" % binding_element(dict(HUMAN, P=HUMAN["P"] * 2))[1]),
        float("%.6g" % (2 * binding_element()[1])))
    chk("an element absent from the stock is unsupplied at any budget",
        processing_factors(dict(HUMAN, Xe=0.001), cosmic())["Xe"],
        float("inf"))

    # -- the destination ranking ----------------------------------------------
    r = rank_destinations()
    chk("the worst destination is raw stellar material", r[0][0],
        "solar photosphere")
    chk("the best is a carbonaceous chondrite", r[-1][0],
        "CI carbonaceous chondrite")
    chk("a crust's binding element is NITROGEN", binding_element(HUMAN, CRUST)[0],
        "N")
    chk("but a CHONDRITE binds on PHOSPHORUS (point values) -- repaired element",
        binding_element(HUMAN, CHONDRITE)[0], "P")
    chk("nitrogen is second there, at 1.33x behind",
        float("%.3g" % (binding_element(HUMAN, CHONDRITE)[1]
                        / sorted(processing_factors(HUMAN, CHONDRITE).values())[-2])),
        1.32)
    chk("crust N is scarcer than crust P (outgassing is this file's reading)",
        CRUST["N"] < CRUST["P"], True)
    chk("chondrite beats cosmic by 178.5x",
        float("%.4g" % (r[0][2] / r[-1][2])), 178.5)
    chk("and beats a crust by 40x", int(round(r[1][2] / r[-1][2])), 40)
    chk("a 70 kg human at a chondrite, in tonnes",
        float("%.3g" % r[-1][3]), 0.749)
    chk("crust N is 40.4x this table's P (17.98 on R&G's), NOT six hundred",
        float("%.3g" % (processing_factors(HUMAN, CRUST)["N"]
                        / processing_factors(HUMAN, CRUST)["P"])), 40.4)

    # -- the ISM fails on concentration, not composition ----------------------
    v, rad = ism_sweep_volume()
    chk("ISM sweep radius exceeds 1e5 km", rad / 1000 > 1e5, True)
    chk("but the ISM's RATIOS are cosmic, so its binding element is still P",
        binding_element(HUMAN, cosmic())[0], "P")

    # -- the order structure --------------------------------------------------
    chk("the assemblable set is a down-set", is_order_ideal(), True)
    chk("and is closed under componentwise max", is_join_closed(), True)

    # -- the finding against CLAIMS.md ----------------------------------------
    chk("a chondrite supplies a human without anything having travelled",
        float("%.4g" % stock_need_not_travel()[0]), 10.7)

    # -- scale: not a barrier --------------------------------------------------
    # CORRECTED (DOCKET 67): labelled "25+ orders" while checking > 1e22.
    chk("the stock bill is 22+ orders below the Fuchs shell",
        against_the_shell() > 1e22, True)
    chk("  photosphere: 3.356e22 below the shell (10^22.53)",
        float("%.4g" % against_the_shell()), 3.356e22)
    chk("  chondrite: 5.992e24 below the shell (10^24.78)",
        float("%.4g" % against_the_shell(stock=CHONDRITE)), 5.992e24)
    chk("  the photospheric stock bill is 133.7 t",
        float("%.4g" % (feedstock_kg(70.0, HUMAN, cosmic()) / 1000.0)), 133.7)
    chk("  and it is NOT the 120 t section 6 once printed",
        abs(feedstock_kg(70.0, HUMAN, cosmic()) / 1000.0 - 120.0) > 1.0, True)

    print("\n%d failure(s)" % len(bad))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(selftest() if "--selftest" in sys.argv else (report() or 0))
