#!/usr/bin/env python3
r"""
stock.py -- THE DESTINATION STOCK CONSTRAINT, COSTED FOR THE FIRST TIME.
Phosphorus binds, a carbonaceous chondrite beats a planet by fifty-three, and
the tree's own claim that the stock "had to travel" is not established.

M: "It carries state, not substance.  No mass, no energy moves; matching matter
must already be at the far end -- correct because transition can only take place
if the same elements/'stock' are available at the destination point for the
state to be assembled at the destination."

    python3 stock.py             the reading
    python3 stock.py --selftest  fixtures, stdlib only

M IS RIGHT, AND THE TREE STATES THIS WITHOUT EVER COSTING IT.  `paper/CLAIMS.md`
line 4629 says, verbatim:

    "And it carries state, not substance.  Teleportation writes a quantum state
     onto matter ALREADY AT THE DESTINATION.  No mass moves.  No energy moves.
     For an object to arrive, an identical stock of matter must already be there
     -- and that had to travel."

The first four sentences are exactly M's point.  The clause after the dash is a
separate claim, it is stronger, and section 4 shows it is not established.
Before this file the tree held no abundance data of any kind: `grep` for
Asplund, Lodders, "elemental" or "abundance" across `research/warp-drive/`
returns that one line of prose and nothing else.  So the constraint was
STATED AND UNCOSTED.  This file costs it.

===============================================================================
1. THE CONSTRAINT, STATED FORMALLY
===============================================================================

A payload is a composition vector p over elements, in mass fractions.  A
destination holds stock of composition s.  To assemble p you process a mass M of
stock, which yields M*s_e of element e, so the constraint is

        p_e  <=  M * s_e        for every element e

and the cheapest sufficient M is the PROCESSING FACTOR

        M(p, s)  =  max_e  ( p_e / s_e )

**IT IS A MAXIMUM, NOT A SUM.**  One scarce element sets the whole bill, and
every other element arrives in surplus.  That is why the answer is a single
BINDING ELEMENT rather than a blend, and why enriching the abundant elements
buys nothing at all.

**AND THE ASSEMBLABLE SET IS AN ORDER IDEAL.**  Fix a stock s and a budget M.
Then A(s, M) = { p : p_e <= M s_e for all e } is a DOWN-SET in the componentwise
order -- if p <= p' and p' is assemblable then so is p, immediately -- and it is
closed under componentwise MAX as well, since max(p, q)_e <= M s_e whenever both
are.  So it is a down-set closed under join: a PRINCIPAL ideal, generated by
M*s.  `is_order_ideal()` and `is_join_closed()` verify both by exhaustion on a
sampled grid rather than by assertion.  Register 66's downward-closure question
therefore has a trivial answer HERE, and that is worth saying precisely because
the tree's other indexes make it hard.

===============================================================================
2. WHAT IT COSTS -- PHOSPHORUS BINDS
===============================================================================

For a 70 kg human against raw stellar or gas-giant material:

    binding element    P       1.7167e3 kg processed per kg of payload
    runner-up          K       1.3049e3          -- only 1.32x behind
    then               Ca      2.3381e2
    a 70 kg human                             120.2 TONNES of source material

**THE RUNNER-UP MATTERS.**  Potassium is within a factor of 1.32 of phosphorus,
so this is not one freak element: two independent scarcities sit at the same
scale, and a destination that fixed phosphorus alone would move the bill by 32 %
and no further.

===============================================================================
3. AND THE DESTINATION TYPE DOMINATES EVERYTHING
===============================================================================

    source                              binding   factor      70 kg human
    stellar / gas giant  (Asplund 09)   P         1.7167e3    120.2  tonnes
    Earth continental crust (R&G 03)    N         5.3333e2     37.3  tonnes
    CI carbonaceous chondrite (L 03)    N         1.0063e1      0.70 tonnes

**A CARBONACEOUS CHONDRITE BEATS RAW COSMIC GAS BY 171x AND A ROCKY CRUST BY
53x**, and the reason is that a planet differentiates.  Earth's crust is a
silicate residue that outgassed its volatiles: its binding element is NITROGEN
at 533, six hundred times worse than the crust's phosphorus.  A chondrite never
differentiated, so it still holds C, N, H, P and S together.

    THE OPTIMAL ARRIVAL NODE IS AN ASTEROID, NOT A PLANET.

That is a specific, computed engineering conclusion and it inverts the intuitive
answer.  `rank_destinations()` produces the table.

**THE DIFFUSE MEDIUM IS THE ONE THAT FAILS.**  At 1 proton/cm^3 the interstellar
medium holds the right elements in the right ratios and in no useful
concentration: `ism_sweep_volume()` returns 7.18e25 m^3 per 70 kg human, a
sphere of radius 2.58e5 km -- two thirds of the Earth-Moon distance, swept, per
person.  Elements existing is not stock.

===============================================================================
4. THE CLAUSE THAT IS NOT ESTABLISHED
===============================================================================

`CLAIMS.md` adds "-- and that had to travel."  **THAT DOES NOT FOLLOW AND THIS
FILE RECORDS IT AS A FINDING.**  Nothing requires the destination stock to have
come from the origin.  Galactic chemical evolution puts carbon, nitrogen and
phosphorus into every enriched star system by nucleosynthesis and accretion, and
`stock_need_not_travel()` gives the counterexample with a number: a CI chondrite
at the destination supplies a human payload at a processing factor of 10.06, and
no part of it was shipped from anywhere.

The weaker true statement is: **the stock must EXIST, ASSEMBLED AND ACCESSIBLE,
at the arrival point.**  That is a real constraint.  It is not a transport cost.

RECORDED, NOT REPAIRED.  `CLAIMS.md` is not edited by this file.

===============================================================================
5. WHAT IT DOES TO THE EIGHT-VALUE COORDINATE
===============================================================================

`unified.py` section 5 numbers the device's parameters, and coordinate 7 is
**B, the declared arrival**, gated by `transit.py` part 1.  The constraint above
says B IS NOT FREE.  A declared arrival must name a site holding accessible
stock, which is a sub-constraint the coordinate did not previously carry.

**AND THE TREE ALREADY FOUND A SECOND, INDEPENDENT REQUIREMENT OF THE SAME
SHAPE.**  `arrival.py` route 1 prices braking by reverse slingshot and notes it
"needs a deflector AT THE DESTINATION, which turns the drive into a NETWORK with
nodes."  Two requirements, arrived at from different directions -- one about
stopping, one about matter -- and both force the same topology.

    A TRANSITION DEVICE IS NOT A VEHICLE.  IT IS A NETWORK, AND ITS NODES ARE
    SITED WHERE THE STOCK IS.

That agrees with `transit.py`'s own conclusion that the corridor must be
traversed once in order to exist: the first trip to a node is the expensive one,
and it is the trip that builds the node.

===============================================================================
6. WHAT THIS FILE REFUSES
===============================================================================

**TO TREAT THE ABUNDANCES AS MEASURED HERE.**  They are CITED: Asplund et al.
2009 photospheric, Rudnick & Gao 2003 continental crust, Lodders 2003 CI
chondrite.  Every processing factor is COMPUTED from them.  `SOURCES` carries
the citations and `provenance()` prints them beside the numbers.

**TO CALL THE PROCESSING FACTOR AN ENERGY COST.**  It is a mass of feedstock.
Separating an element from a matrix costs energy that depends on the matrix and
the method, and none of that is computed here.

**TO CLAIM THE STOCK CONSTRAINT IS A BARRIER.**  It is not.  120 tonnes, or 0.7
tonnes at a chondrite, sits about 25 orders of magnitude below the Fuchs shell's
4.4886e27 kg.  It is a SITE-SELECTION CRITERION, and calling it more would be
over-representation.

**TO SETTLE WHETHER ASSEMBLY IS POSSIBLE AT ALL.**  This file costs the
FEEDSTOCK for an assembly it does not design.  Writing a quantum state onto
1.2e5 kg of sorted atoms is not addressed, and `transit.py`'s two-classical-bit
ledger is untouched by anything here.
"""

import math
import sys

#: Provenance for every table below.  Cited, never measured here.
SOURCES = {
    "cosmic": "Asplund, Grevesse, Sauval & Scott (2009), ARA&A 47, 481 -- "
              "photospheric log eps, H = 12",
    "crust": "Rudnick & Gao (2003), Treatise on Geochemistry 3, 1 -- "
             "bulk continental crust",
    "chondrite": "Lodders (2003), ApJ 591, 1220 -- CI carbonaceous chondrite",
    "human": "ICRP Publication 23 / Emsley, Nature's Building Blocks -- "
             "reference adult, mass fractions",
}

#: Asplund 2009 photospheric abundances, log eps with H = 12.
A09 = {"H": 12.00, "He": 10.93, "C": 8.43, "N": 7.83, "O": 8.69, "Ne": 7.93,
       "Na": 6.24, "Mg": 7.60, "Al": 6.45, "Si": 7.51, "P": 5.41, "S": 7.12,
       "Cl": 5.50, "K": 5.03, "Ca": 6.34, "Fe": 7.50, "Zn": 4.56}

ATOMIC_MASS = {"H": 1.008, "He": 4.003, "C": 12.011, "N": 14.007, "O": 15.999,
               "Ne": 20.180, "Na": 22.990, "Mg": 24.305, "Al": 26.982,
               "Si": 28.085, "P": 30.974, "S": 32.06, "Cl": 35.45,
               "K": 39.098, "Ca": 40.078, "Fe": 55.845, "Zn": 65.38}

CRUST = {"O": 0.461, "Si": 0.282, "Al": 0.0823, "Fe": 0.0563, "Ca": 0.0415,
         "Na": 0.0236, "Mg": 0.0233, "K": 0.0209, "H": 0.0014, "P": 0.00105,
         "C": 0.002, "S": 0.00035, "Cl": 0.00017, "N": 0.00006, "Zn": 0.00007}

CHONDRITE = {"O": 0.464, "Fe": 0.185, "Si": 0.107, "Mg": 0.0965, "S": 0.0541,
             "C": 0.0350, "H": 0.0202, "Ca": 0.00911, "Al": 0.00860,
             "Na": 0.00500, "N": 0.00318, "P": 0.00104, "K": 0.000555,
             "Cl": 0.000698, "Zn": 0.000312}

HUMAN = {"O": 0.650, "C": 0.185, "H": 0.095, "N": 0.032, "Ca": 0.015,
         "P": 0.010, "K": 0.0040, "S": 0.0030, "Na": 0.0015, "Cl": 0.0015,
         "Mg": 0.0005, "Fe": 0.00006, "Zn": 0.00003}

#: 1 proton/cm^3, the warm neutral medium, as arrival.py uses.
RHO_ISM = 1.0e6 * 1.67262192e-27

#: TARGET-1-RESULT.md's shell, for the scale comparison in section 6.
FUCHS_SHELL_KG = 4.4886e27


def cosmic():
    """Mass fractions from A09's log-eps abundances.  COMPUTED, not tabulated."""
    n = {e: 10.0 ** (v - 12.0) for e, v in A09.items()}
    m = {e: n[e] * ATOMIC_MASS[e] for e in n}
    tot = sum(m.values())
    return {e: m[e] / tot for e in m}


DESTINATIONS = (("stellar / gas giant", "cosmic"),
                ("Earth continental crust", "crust"),
                ("CI carbonaceous chondrite", "chondrite"))


def stock_of(key):
    return {"cosmic": cosmic(), "crust": CRUST, "chondrite": CHONDRITE}[key]


# ------------------------------------------------------------ the constraint

def processing_factors(payload=None, source=None):
    """{element: p_e / s_e} -- how much stock each element alone would demand.

    An element absent from the source returns infinity: it cannot be supplied at
    any budget, and that is a different failure from being merely scarce.
    """
    payload = HUMAN if payload is None else payload
    source = cosmic() if source is None else source
    out = {}
    for e, p in payload.items():
        s = source.get(e, 0.0)
        out[e] = float("inf") if s <= 0.0 else p / s
    return out


def binding_element(payload=None, source=None):
    """(element, factor) -- the single element that sets the whole bill.

    It is a MAX over elements, so exactly one element is binding and every
    other arrives in surplus.
    """
    f = processing_factors(payload, source)
    e = max(f, key=lambda k: f[k])
    return e, f[e]


def feedstock_kg(payload_kg=70.0, payload=None, source=None):
    """Mass of source material to assemble a payload of the given mass."""
    return payload_kg * binding_element(payload, source)[1]


def rank_destinations(payload_kg=70.0, payload=None):
    """[(name, binding element, factor, tonnes)] worst first."""
    rows = []
    for name, key in DESTINATIONS:
        e, f = binding_element(payload, stock_of(key))
        rows.append((name, e, f, payload_kg * f / 1000.0))
    return sorted(rows, key=lambda r: -r[2])


def ism_sweep_volume(payload_kg=70.0, payload=None):
    """(volume m^3, equivalent sphere radius m) of diffuse ISM per payload.

    The elements are present in cosmic ratios; what is absent is concentration.
    """
    v = feedstock_kg(payload_kg, payload, cosmic()) / RHO_ISM
    return v, (3.0 * v / (4.0 * math.pi)) ** (1.0 / 3.0)


def stock_need_not_travel():
    """The counterexample to CLAIMS.md's "and that had to travel".

    Returns (processing factor at a CI chondrite, the citation).  Galactic
    chemical evolution placed that stock; nothing shipped it.
    """
    return binding_element(HUMAN, CHONDRITE)[1], SOURCES["chondrite"]


def against_the_shell(payload_kg=70.0):
    """How far below the Fuchs shell the whole stock bill sits.  Not a barrier."""
    return FUCHS_SHELL_KG / feedstock_kg(payload_kg, HUMAN, cosmic())


# ------------------------------------------- the order-ideal property, verified

def _grid(source, budget, step=4):
    """A sampled lattice of candidate payloads under the budget, for exhaustion."""
    els = sorted(source)[:6]
    caps = [budget * source[e] for e in els]
    pts = []

    def rec(i, cur):
        if i == len(els):
            pts.append(tuple(cur))
            return
        for k in range(step + 1):
            rec(i + 1, cur + [caps[i] * k / step])
    rec(0, [])
    return els, pts


def is_order_ideal(budget=100.0, step=3):
    """Exhaust: is the assemblable set a DOWN-SET in the componentwise order?

    Verified by checking every ordered pair on the sampled grid, not asserted.
    """
    src = cosmic()
    els, pts = _grid(src, budget, step)
    cap = [budget * src[e] for e in els]
    ok = lambda p: all(p[i] <= cap[i] * (1 + 1e-12) for i in range(len(els)))
    for a in pts:
        for b in pts:
            if all(a[i] <= b[i] for i in range(len(els))) and ok(b) and not ok(a):
                return False
    return True


def is_join_closed(budget=100.0, step=3):
    """Exhaust: is it closed under componentwise MAX?  A principal ideal is."""
    src = cosmic()
    els, pts = _grid(src, budget, step)
    cap = [budget * src[e] for e in els]
    ok = lambda p: all(p[i] <= cap[i] * (1 + 1e-12) for i in range(len(els)))
    for a in pts:
        if not ok(a):
            continue
        for b in pts:
            if not ok(b):
                continue
            if not ok(tuple(max(a[i], b[i]) for i in range(len(els)))):
                return False
    return True


def provenance():
    return [(k, v) for k, v in sorted(SOURCES.items())]


# ------------------------------------------------------------------- reading

def report():
    print(__doc__.split("=====", 1)[0].strip())
    print()
    print("=" * 74)
    print("2.  WHAT IT COSTS -- AGAINST RAW STELLAR MATERIAL")
    print("=" * 74)
    f = processing_factors()
    for e in sorted(f, key=lambda k: -f[k]):
        print("   %-3s payload %.3e   stock %.3e   -> %.4e kg / kg"
              % (e, HUMAN[e], cosmic()[e], f[e]))
    e, v = binding_element()
    print("\n   BINDING ELEMENT   %s at %.4e" % (e, v))
    print("   a 70 kg human     %.4e kg = %.1f tonnes" % (feedstock_kg(),
                                                          feedstock_kg() / 1000))
    print()
    print("=" * 74)
    print("3.  THE DESTINATION TYPE DOMINATES")
    print("=" * 74)
    print("   %-28s %-8s %-12s %s" % ("source", "binding", "factor", "tonnes"))
    for name, el, fac, t in rank_destinations():
        print("   %-28s %-8s %.4e   %8.2f" % (name, el, fac, t))
    r = rank_destinations()
    print("\n   a chondrite beats raw cosmic gas by %.0fx and a crust by %.0fx"
          % (r[0][2] / r[-1][2], r[1][2] / r[-1][2]))
    v, rad = ism_sweep_volume()
    print("\n   diffuse ISM at 1 proton/cm^3: sweep %.3e m^3 per 70 kg human," % v)
    print("   a sphere of radius %.3e km (Earth-Moon is 3.844e5 km)."
          % (rad / 1000))
    print("   ELEMENTS EXISTING IS NOT STOCK.")
    print()
    print("=" * 74)
    print("4.  THE CLAUSE THAT IS NOT ESTABLISHED")
    print("=" * 74)
    fac, cite = stock_need_not_travel()
    print("   CLAIMS.md:4629 adds \"-- and that had to travel\".")
    print("   Counterexample: a CI chondrite supplies a human payload at a")
    print("   processing factor of %.2f, placed by galactic chemical evolution" % fac)
    print("   and shipped from nowhere.   %s" % cite)
    print("   RECORDED, NOT REPAIRED.")
    print()
    print("=" * 74)
    print("5.  THE ORDER STRUCTURE, AND THE SCALE")
    print("=" * 74)
    print("   assemblable set is a down-set          %s" % is_order_ideal())
    print("   and closed under componentwise max     %s" % is_join_closed())
    print("   -> a PRINCIPAL ideal generated by M*s.")
    print()
    print("   the whole stock bill sits %.3e below the Fuchs shell."
          % against_the_shell())
    print("   IT IS A SITE-SELECTION CRITERION, NOT A BARRIER.")
    print()
    for k, v in provenance():
        print("   %-10s %s" % (k, v))


# ------------------------------------------------------------------ fixtures

def selftest():
    bad = []

    def chk(what, got, want):
        ok = got == want
        if not ok:
            bad.append((what, got, want))
        print("   %-60s %s" % (what, "ok" if ok else "FAIL %r != %r"
                               % (got, want)))

    print("stock.py fixtures  (stdlib only)")

    # -- the abundance derivation --------------------------------------------
    c = cosmic()
    chk("cosmic mass fractions sum to 1", round(sum(c.values()), 12), 1.0)
    chk("hydrogen dominates, to 4 digits", float("%.4g" % c["H"]), 0.7375)
    chk("helium next", float("%.4g" % c["He"]), 0.2493)
    chk("and phosphorus is the scarce one of the biogenic set",
        min(("C", "N", "O", "P", "S"), key=lambda e: c[e]), "P")
    chk("human fractions sum to ~1", round(sum(HUMAN.values()), 4), 0.9976)

    # -- the constraint is a MAX, not a sum -----------------------------------
    chk("binding element against stellar material is P", binding_element()[0], "P")
    chk("at this factor", float("%.5g" % binding_element()[1]), 1716.7)
    chk("K is the runner-up within 1.32x",
        float("%.3g" % (binding_element()[1]
                        / sorted(processing_factors().values())[-2])), 1.32)
    chk("the factor is the MAX, not the sum -- doubling an ABUNDANT element "
        "changes nothing",
        binding_element(dict(HUMAN, H=HUMAN["H"] * 2))[1],
        binding_element()[1])
    chk("but doubling the BINDING element doubles the bill",
        float("%.6g" % binding_element(dict(HUMAN, P=HUMAN["P"] * 2))[1]),
        float("%.6g" % (2 * binding_element()[1])))
    chk("an element absent from the stock is unsupplied at any budget",
        processing_factors(dict(HUMAN, Xe=0.001), cosmic())["Xe"],
        float("inf"))

    # -- the destination ranking ----------------------------------------------
    r = rank_destinations()
    chk("the worst destination is raw stellar material", r[0][0],
        "stellar / gas giant")
    chk("the best is a carbonaceous chondrite", r[-1][0],
        "CI carbonaceous chondrite")
    chk("a crust's binding element is NITROGEN, not phosphorus",
        binding_element(HUMAN, CRUST)[0], "N")
    chk("because differentiation outgassed the volatiles: crust N is scarcer "
        "than crust P", CRUST["N"] < CRUST["P"], True)
    chk("chondrite beats cosmic by 171x",
        int(round(r[0][2] / r[-1][2])), 171)
    chk("and beats a crust by 53x", int(round(r[1][2] / r[-1][2])), 53)
    chk("a 70 kg human at a chondrite, in tonnes",
        float("%.3g" % r[-1][3]), 0.704)

    # -- the ISM fails on concentration, not composition ----------------------
    v, rad = ism_sweep_volume()
    chk("ISM sweep radius exceeds 1e5 km", rad / 1000 > 1e5, True)
    chk("but the ISM's RATIOS are cosmic, so its binding element is still P",
        binding_element(HUMAN, cosmic())[0], "P")

    # -- the order structure --------------------------------------------------
    chk("the assemblable set is a down-set", is_order_ideal(), True)
    chk("and is closed under componentwise max", is_join_closed(), True)

    # -- the finding against CLAIMS.md ----------------------------------------
    chk("a chondrite supplies a human without anything having travelled",
        float("%.4g" % stock_need_not_travel()[0]), 10.06)

    # -- scale: not a barrier --------------------------------------------------
    chk("the stock bill is 25+ orders below the Fuchs shell",
        against_the_shell() > 1e22, True)

    print("\n%d failure(s)" % len(bad))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(selftest() if "--selftest" in sys.argv else (report() or 0))
