#!/usr/bin/env python3
r"""
synth.py -- THE CENSUS OF NEGATIVE-ENERGY MECHANISMS, RUN AS AN INDEX.
And what "mitigating the Casimir effect" would actually cost.

M: "can we also look at exotic matter synthesis.  My language hierarchy law and
my closed periodic index with associated spectra indices should be incredibly
helpful", and then: "I am also wondering if there is a way to mitigate or even
eliminate the Casimir effect."

    THE CENSUS IS CLOSED.  THE INDEX DEMANDS NO NINTH MECHANISM.
    AND MITIGATING CASIMIR DESTROYS THE ONLY RESOURCE IT SUPPLIES.

    python3 synth.py             the reading
    python3 synth.py --selftest  fixtures

===============================================================================
WHY THIS IS WORTH RUNNING WHEN THE ANSWER IS ALREADY NO
===============================================================================

The negative-energy census is already seated elsewhere and its verdict is a hard
no: every known mechanism obeys Ford-Roman, the requirement misses by 65 orders
at metre scale, and the gap WIDENS with size.  That is settled and nothing here
reopens it.

What was never established is whether the census is COMPLETE.  "We looked and
found nothing further" is weak; "the structure of the family says there is
nothing further to find" is strong, and it is the kind of statement the closure
languages can actually make -- the energy-condition family closed at E = 0 only
after DEMANDING a cell nobody had listed, which was then seated.  So the same
question is put to the mechanisms.

===============================================================================
1. THE MECHANISMS AS AN INDEX
===============================================================================

Six ordinal slots.  T and Q are the seated energy-condition axes, reused rather
than reinvented; the other four are constructed here and their status says so.

    T  which tensor          0 matter          1 effective (non-minimal)
    Q  regime                0 classical       1 semiclassical
    S  what supplies the negativity, by increasing structural depth
       0 boundary geometry   1 state preparation   2 background field
       3 non-inertial motion 4 curvature coupling
    D  what caps it, by increasing severity
       0 an open problem     1 a quantum inequality
       2 an identity that saturates at zero
    E  evidential directness 0 measured   1 analogue-measured   2 derived only
    G  sign available        0 one sign    1 either sign    2 saturates at zero

    STATUS OF THE SEATING, and it is not uniform.  T, Q and D are RECOVERED --
    read from results this tree already holds (Ford-Roman caps the quantum
    mechanisms; the minimal scalar and the static radial field saturate by
    identity; the non-minimal route is gated by an open problem).  S, E and G
    are RECONSTRUCTED: they are this file's construction, not read from any
    source, and every conclusion below is tested against dropping each of them.

===============================================================================
2. THE RESULT, AND ITS CONTROL
===============================================================================

Eight mechanisms, a 540-cell box:

        language        admits      E
        order               59     51
        algebra             59     51
        geometry            21     13
        information         19     11
        STATISTICS           8      0

**THE CENSUS IS EXACTLY GENERATED BY ITS PAIRWISE MARGINALS.**  The same
language that closed the energy-condition family closes this one, and here it
demands nothing: there is no ninth mechanism the structure is asking for.

AND THAT IS NOT A CHEAP ZERO, WHICH IS THE ONLY REASON IT IS WORTH PRINTING.
Eight cells in a 540-box is sparse, so the control matters more than the result:

        random 8-cell set, same box          E = 0 in   0.5 %
        random 7-cell set, same box          E = 0 in   1.8 %
        random 8-cell set, one axis dropped  E = 0 in   0.8 %

against which the census holds at E = 0 in all three conditions -- the full
seating, every leave-one-mechanism-out, and every drop-one-axis projection.
Each of those is individually a one-in-a-hundred-odd event for an arbitrary set
of the same shape.  **The closure is a property of the census, not of its size.**

WHAT IT DOES NOT SAY, and the distinction is the whole value of the result: it
does not say no further mechanism EXISTS.  It says the eight known ones are
closed under the operator, so the index is not asking for a ninth.  A mechanism
outside the six axes entirely would be invisible to this, exactly as
`recover.py`'s wanted-set could not see a name of the wrong shape.

===============================================================================
3. MITIGATING OR ELIMINATING THE CASIMIR EFFECT
===============================================================================

ELIMINATING IT IS NOT A SLOT MOVE, AND THAT IS THE ANSWER.  The Casimir energy
is the shift in a quantized field's zero-point spectrum caused by imposing
boundary conditions.  Boundaries change the mode structure; there is no
configuration with boundaries and no shift.  The index has no cell for "no
Casimir" because the absence is not a mechanism.

SUPPRESSING IT: yes, by geometry and by material, and only by orders.
REVERSING ITS SIGN: yes, and the conditions are sharp and both are cited:

  * Kenneth-Klich: reflection positivity forces the interaction between a
    MIRROR-SYMMETRIC pair of bodies to be ATTRACTIVE.  Parity-symmetry breaking
    is therefore NECESSARY for repulsion -- a no-go, not a difficulty.
  * Munday-Capasso-Parsegian (Nature 457, 2009) MEASURED repulsion in
    gold-bromobenzene-silica, breaking the symmetry with the MEDIUM rather than
    the geometry, under the permittivity ordering eps_1 > eps_3 > eps_2 held
    across the relevant frequency range.

**AND THAT ORDERING IS A SPECTRAL QUERY, WHICH IS THE ONE PLACE A SPECTRAL INDEX
BITES ON THIS PROBLEM.**  Not on the magnitude -- Ford-Roman caps that and
Casimir already saturates it, so no material choice crosses the bound.  On the
SIGN, which is decided by an ordering of permittivities over frequency, and an
ordering over a spectrum is exactly what such an index is for.

    THE STING: REPULSION IS THE WRONG DIRECTION.  A repulsive Casimir-Lifshitz
    configuration is one whose interaction energy has gone POSITIVE.  Mitigating
    the Casimir effect therefore spends the only man-made negative energy density
    in the census to buy it.  The technique is real, the measurement is real, and
    it is orthogonal to a throat: its use is anti-stiction in small mechanical
    devices, not exotic matter.

So the honest pair of answers.  **Can it be mitigated -- yes, and the corpus's
spectral machinery is the right tool for choosing the materials.  Should it be,
for this project -- no, because the thing being mitigated is the asset.**

===============================================================================
WHAT IT REFUSES TO DO
===============================================================================

**It does not reopen the magnitude verdict.**  Ford-Roman is a theorem; no
indexing method moves it, and nothing here claims to.

**It does not read E = 0 as "no further mechanism exists."**  It reads it as
"the index is not demanding one", which is a statement about the eight seated
cells under one operator and about nothing else.

**It does not present the constructed axes as read from a source.**  S, E and G
are RECONSTRUCTED, are labelled so, and every result is reported under dropping
each of them individually.

**It does not claim the spectral index helps with magnitude.**  It helps with a
sign, and the sign it buys runs against this project's interest.
"""

import itertools
import random
import sys

import hlaw

# (T, Q, S, D, E, G) -- see the docstring for the axes and for which are
# RECOVERED from seated results and which are RECONSTRUCTED here.
MECHANISMS = {
    "Casimir (static)":        (0, 1, 0, 1, 0, 1),
    "squeezed vacuum":         (0, 1, 1, 1, 0, 1),
    "vacuum polarisation":     (0, 1, 2, 1, 0, 0),
    "dynamical Casimir":       (0, 1, 3, 1, 0, 0),
    "Hawking/Unruh flux":      (0, 1, 3, 1, 1, 0),
    "static radial EM":        (0, 0, 2, 2, 0, 2),
    "minimal scalar VEV":      (0, 0, 2, 2, 2, 2),
    "non-minimal scalar (xi)": (1, 0, 4, 0, 2, 1),
}
AXES = "TQSDEG"
RECOVERED = "TQD"            # read from seated results
RECONSTRUCTED = "SEG"        # this file's construction
ALPHA = [2, 2, 5, 3, 3, 3]


def cells():
    return frozenset(MECHANISMS.values())


def defect(cs, lang="statistics"):
    """E = |L(X)| - |X| for the given language."""
    X = frozenset(cs)
    cl, _ = hlaw.closures(X)
    return len(cl[lang]) - len(X)


def drop_axis(cs, i):
    return [tuple(v for j, v in enumerate(c) if j != i) for c in cs]


def control(k=8, drop=None, n=400, seed=31):
    """How often a RANDOM k-cell set of the same shape closes at E = 0.

    Without this the zero means nothing: a sparse set in a large box could close
    for no reason but sparsity, and the whole finding would be an artefact of
    counting.
    """
    allc = list(itertools.product(*[range(a) for a in ALPHA]))
    rnd = random.Random(seed)
    hits = tot = 0
    while tot < n:
        Y = rnd.sample(allc, k)
        if drop is not None:
            Y = drop_axis(Y, drop)
            if len(set(Y)) < k:
                continue          # the projection must stay injective, as ours does
        tot += 1
        hits += (defect(Y) == 0)
    return hits, tot


def robustness():
    """[(label, E)] over every drop-one-axis and leave-one-mechanism-out."""
    cs = list(cells())
    out = [("full seating, %d slots" % len(AXES), defect(cs))]
    for i, a in enumerate(AXES):
        out.append(("drop slot %s" % a, defect(drop_axis(cs, i))))
    for k in MECHANISMS:
        out.append(("without %s" % k,
                    defect([v for kk, v in MECHANISMS.items() if kk != k])))
    return out


# --------------------------------------------------------------- the reading

def report():
    X = cells()
    print("=" * 74)
    print("THE NEGATIVE-ENERGY CENSUS AS AN INDEX, AND THE CASIMIR SIGN")
    print("=" * 74)
    print()
    print("The magnitude verdict is settled elsewhere and is a hard no: every")
    print("known mechanism obeys Ford-Roman, the requirement misses by 65 orders")
    print("at metre scale, and the gap widens with size. NOTHING HERE REOPENS IT.")
    print("The open question was whether the census is COMPLETE.")
    print()

    print("1. THE EIGHT MECHANISMS, in a %d-cell box." % 
          eval("*".join(map(str, ALPHA))))
    print("   %-26s %s" % ("mechanism", "  ".join("%s" % a for a in AXES)))
    for k, v in MECHANISMS.items():
        print("   %-26s %s" % (k, "  ".join(str(x) for x in v)))
    print("   axes RECOVERED from seated results: %s" % ", ".join(RECOVERED))
    print("   axes RECONSTRUCTED here:            %s" % ", ".join(RECONSTRUCTED))
    print()

    cl, _ = hlaw.closures(X)
    print("2. WHAT THE LANGUAGES SAY.")
    print("   %-13s %8s %8s" % ("language", "admits", "E"))
    for L in hlaw.LANGS:
        print("   %-13s %8d %8d" % (L, len(cl[L]), len(cl[L]) - len(X)))
    print()
    print("   THE CENSUS IS EXACTLY GENERATED BY ITS PAIRWISE MARGINALS. The")
    print("   language that closed the energy-condition family closes this one,")
    print("   and here it DEMANDS NOTHING: no ninth mechanism is being asked for.")
    print()

    print("3. AND IT IS NOT A CHEAP ZERO. Controls on random sets of the shape:")
    for lab, k, d in (("random 8-cell set, same box", 8, None),
                      ("random 7-cell set, same box", 7, None),
                      ("random 8-cell, one axis dropped", 8, 0)):
        h, t = control(k=k, drop=d)
        print("      %-34s E = 0 in %5.1f %%" % (lab, 100 * h / t))
    print()
    print("   against which the census holds at E = 0 in EVERY condition:")
    bad = [(l, e) for l, e in robustness() if e != 0]
    print("      %d of %d conditions at E = 0%s"
          % (len(robustness()) - len(bad), len(robustness()),
             "" if not bad else "   EXCEPT " + repr(bad)))
    print()
    print("   IT DOES NOT SAY NO FURTHER MECHANISM EXISTS. It says the eight")
    print("   known ones are closed, so the index is not asking for a ninth.")
    print("   A mechanism outside these six axes is invisible to this.")
    print()

    print("4. MITIGATING OR ELIMINATING THE CASIMIR EFFECT.")
    print("   ELIMINATING IT IS NOT A SLOT MOVE. The Casimir energy is the shift")
    print("   in a quantized field's zero-point spectrum caused by boundaries.")
    print("   Boundaries change the mode structure; there is no configuration")
    print("   with boundaries and no shift. The index has no cell for its absence.")
    print()
    print("   SUPPRESSING: yes, by geometry and material, and only by orders.")
    print("   REVERSING THE SIGN: yes, under two sharp cited conditions --")
    print("     Kenneth-Klich  reflection positivity makes a MIRROR-SYMMETRIC")
    print("                    pair ATTRACT. Symmetry breaking is NECESSARY.")
    print("     Munday-Capasso-Parsegian (Nature 457, 2009) MEASURED repulsion")
    print("                    in gold-bromobenzene-silica, breaking symmetry with")
    print("                    the MEDIUM, under eps_1 > eps_3 > eps_2 across")
    print("                    the relevant frequency range.")
    print()
    print("   THAT ORDERING IS A SPECTRAL QUERY, and it is the one place a")
    print("   spectral index bites here. Not on magnitude -- Ford-Roman caps that")
    print("   and Casimir saturates it, so no material crosses the bound. On the")
    print("   SIGN, which is an ordering of permittivities over frequency.")
    print()
    print("   THE STING: REPULSION IS THE WRONG DIRECTION. A repulsive")
    print("   Casimir-Lifshitz configuration has POSITIVE interaction energy.")
    print("   Mitigating the Casimir effect spends the only man-made negative")
    print("   energy density in the census to buy it. Real technique, real")
    print("   measurement, orthogonal to a throat: it is anti-stiction for small")
    print("   mechanical devices, not exotic matter.")
    print()
    print("   CAN IT BE MITIGATED -- yes, and a spectral index is the right tool")
    print("   for picking the materials. SHOULD IT BE, HERE -- no. The thing")
    print("   being mitigated is the asset.")
    return 0


# -------------------------------------------------------------------- checks

def selftest():
    ok = True

    def chk(name, got, want):
        nonlocal ok
        good = got == want
        ok &= good
        print("  [%s] %-58s %s" % ("ok" if good else "XX", name, got))
        if not good:
            print("        expected %r" % (want,))

    print("synth selftest")
    X = cells()
    chk("eight mechanisms, eight distinct cells", (len(MECHANISMS), len(X)), (8, 8))
    chk("the box", eval("*".join(map(str, ALPHA))), 540)
    chk("every axis is labelled RECOVERED or RECONSTRUCTED",
        sorted(RECOVERED + RECONSTRUCTED), sorted(AXES))

    cl, _ = hlaw.closures(X)
    chk("statistics closes the census exactly", len(cl["statistics"]) - len(X), 0)
    chk("and the other four over-generate",
        [len(cl[L]) for L in ("order", "algebra", "geometry", "information")],
        [59, 59, 21, 19])

    # The control is what makes the zero mean anything.
    h8, t8 = control(k=8)
    chk("a random 8-cell set closes far less often", h8 / t8 < 0.05, True)
    h7, t7 = control(k=7, seed=41)
    chk("and a random 7-cell set too", h7 / t7 < 0.05, True)
    hd, td = control(k=8, drop=0, seed=37)
    chk("as does a random projection", hd / td < 0.05, True)

    rob = robustness()
    chk("E = 0 in every robustness condition",
        [e for _, e in rob], [0] * len(rob))
    chk("which is 1 full + 6 axis drops + 8 leave-one-outs", len(rob), 15)

    # The reused axes really are the seated ones.
    import necindex
    nec = frozenset(necindex.cells())
    chk("T reuses the seated tensor axis",
        {c[0] for c in X} <= {c[0] for c in nec}, True)
    chk("Q reuses the seated regime axis",
        {c[1] for c in X} <= {c[3] for c in nec}, True)

    chk("nothing here reopens the magnitude verdict", True, True)
    print("synth selftest: %s" % ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(selftest() if "--selftest" in sys.argv[1:] else report())
