import json, copy
D='/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/reaudit/'
def load(k): return json.load(open(D+'old_'+k+'.json'))
def save(k,d):
    fn=D+k.replace('/','_').replace('#','_')+'.json'; d['report_path']=fn
    json.dump(d,open(fn,'w'),indent=1,ensure_ascii=False); print('wrote',fn)

# ---------------------------------------------------------------- 1 PENDRY
k='single-mode-capacity-ceiling-pendry-1983'; o=load(k); d=copy.deepcopy(o)
d['source']={
 "located": "J. B. Pendry, 'Quantum limits to the flow of information and entropy', J. Phys. A: Math. Gen. 16 (1983) 2161-2171. Google Drive fileId 1agL2n-mWVdWzk_3vNNbWM5imgH9nmM58 (title 'Quantum Limits to the flow of information and entropy.pdf'), supplied by M. Identity confirmed from the file's own pages: 'J. Phys. A: Math. Gen. 16 (1983) 2161-2171. Printed in Great Britain'; 'Quantum limits to the flow of information and entropy'; 'J B Pendry The Blackett Laboratory, Imperial College, Prince Consort Road, London'; 'Received 15 October 1982'; running pages 2161-2171; '@ 1983 The Institute of Physics 2161'.",
 "read_status": "READ (primary, whole paper pp. 2161-2171, OCR text via Google Drive read_file_content). Most displayed equations are lost or garbled by the OCR (eqs. 11-15, 18-31, 38-44 absent; eq. 16 survives as 'i', s (r/31n2 2)E+h-', (16)'). The barred h cannot be told from h in the text layer; it is resolved as hbar by re-derivation (reaudit script (c),(e)), not by reading. Bekenstein & Schiffer (the tree's second name) was NOT read in this stage.",
 "via": "mcp__Google_Drive__read_file_content(fileId=1agL2n-mWVdWzk_3vNNbWM5imgH9nmM58). Supersedes the first audit's NAMED-NOT-READ."
}
d['pages_read']=["Pendry J. Phys. A 16: pp. 2161-2171 (whole paper incl. abstract, sections 1-4, acknowledgments, references), OCR text layer"]
d['published_statement']=("READ. Abstract: 'In each channel there is an inequality between information flow i and energy flow E  i2\\<E'rr/(3h\\~n22)  a relationship which, though speculated on before or derived for only a restricted class of systems, is proven here for a wide range of systems.' "
 "Eq. (16), p. 2166 (fermions): 'i', s (r/31n2 2)E+h-', (16) a relationship which is completely independent of the form of w(k) or any other physical parameter of the specific system.' "
 "Bosons, p. 2168: 'which is, remarkably, the same inequality obtained for fermions: the equality is not attainable with massive bosons, but only with massless objects such as photons or phonons.' "
 "Read through the OCR (and forced by reaudit (a)-(e)) this is I_dot^2 <= (pi/(3 ln^2 2)) E_dot_+ / hbar per channel, i.e. I_dot <= sqrt(pi E_dot/(3 hbar))/ln 2 -- IDENTICAL to branelink.py:38-39 and to S5 N(A) at branelink.py:350 (reaudit (a),(h)). "
 "Eq. (36), p. 2169, at optimum: 'S + - -1 6Irk;Tch-l E + - 1 2 k2 BT: \\~ h-'.' = S_+ = pi k^2 T_c/(6 hbar), E_+ = pi k^2 T_c^2/(12 hbar), which saturates the bound (reaudit (b),(c)). "
 "Scope of the generality claim, p. 2164: 'Thus within the confines of the model it is, I believe, rigorous. Since the same law emerges under a wide range of circumstances it is tempting to speculate that it is a law of quantum thermodynamics, the ‘fourth law’, unproven in the general case but universally obeyed.' Conclusions p. 2171: 'I suspect that the inequality as applied to a single channel holds completely generally.'")
d['published_hypotheses']=[
 "S1 SINGLE CHANNEL (p. 2162-2163): 'It leaves us with no alternative but to concentrate on a single channel if we are to establish equation (5) on a sound footing.' 'Thus we define a single channel as corresponding to one of the variables needed to specify the flow of the medium into the receiver.' Parallel channels break it: 'By placing as many channels in parallel as we wish, we can arbitrarily reduce the energy expenditure for information transfer.'",
 "S2 GAS OF INDEPENDENT PARTICLES (p. 2164): 'In most common systems in which information or entropy flows, the active medium is a gas of independent particles.' Interacting media are covered only by the conjecture quoted in published_statement.",
 "S3 BALLISTIC CHANNEL WITH A GROUP VELOCITY (p. 2164): 'We further assume that a quantum number k can be found such that the particle velocity in the channel is U (w) = dw/dk. (10)' ... 'the assumption that k exists is not a trivial one and implies a symmetry to the transporting medium.' Disorder is argued, not proved: 'A rigorous quantum mechanical treatment of diffusion is beyond present techniques'.",
 "S4 STATISTICS AND DISPERSION FREE -- this is Pendry's 'field-blind' clause (p. 2164): 'The important result of this section is that neither the statistics nor the dispersion relationship affects the inequality, though certain forms of w (k) may render the optimum case unattainable.' Gaps and band edges only lower the ratio ('Hence the enetgy flow is inevitably greater'; bosons: 'In the case that the spectrum does not extend to w = 0, the system is less efficient').",
 "S5 INFORMATION = ENTROPY, NOISELESS, ISOLATED MEDIUM (pp. 2161, 2165): 'Identifying information with entropy (Shannon 1948, Brillouin 1956)'; 'In the case of information flow, T, is the information temperature and we shall assume that the medium is isolated from its surroundings. Thus we do not consider the case of classical information theory where the information competes with entropy from thermal excitations.'",
 "S6 ONE-SOURCE FLUX, STEADY FLOW (pp. 2164-2165): 'The proof ... instead considers a steady flow of information'; flows labelled 'S, and E+ where the subscript '+' denotes that the flux originates from the '+' source'; 'Thus our work does not imply an inevitable energy expenditure, a conclusion which would require a detailed analysis of transmitter and receiver and which will not be attempted here.'",
 "NOT IN THE SOURCE: no moving frame, no relativistic carrier, no bulk/brane geometry, no massive-carrier boost. The receiver is not analysed (S6)."
]
d['hypothesis_drift']=[
 "SUPERSEDED STATUS (branelink.py:39, :162-163 CLOSING_PREMISE_STATUS = 'NOT-FOUND', 'Pendry 1983, Bekenstein & Schiffer not read'): the FUNCTIONAL FORM is now READ at source (abstract; eq. 16) and matches the tree's sqrt(pi P/(3 hbar))/ln 2 exactly (reaudit (a)). 'NOT-FOUND' is stale for the form; it remains accurate for universal field-blindness, which Pendry calls 'unproven in the general case'. Recorded, not repaired.",
 "'FIELD-BLIND' NARROWED (branelink.py:39-40): Pendry proves independence of statistics and dispersion (S4) only for a gas of independent particles in a ballistic channel with a group velocity (S2, S3), isolated and noiseless (S5). Beyond that it is his conjecture ('tempting to speculate', 'I suspect'). The tree carries none of S2-S5; it carries only 'single mode' and marks field-blindness 'not established' -- which is the correct reading.",
 "THE REFUSED USE IS SUPPORTED BY THE SOURCE (branelink.py:40-42, failure mode (4)): Pendry's own parallelism argument (eqs. 6-7, p. 2162) is that N channels sharing E carry sqrt(N) times one channel (reaudit (g); first audit check 6). A carrier in a 5D bulk is not shown to be one channel, and Pendry treats no moving frame, so applying the single-channel form to 'a carrier with gamma > 1 on a moving brane in a 5D bulk' is not licensed by the paper. The first audit's massless-Doppler invariance (checks 5a-5c) is outside Pendry and remains the auditor's computation; the massive-carrier boost is still uncomputed.",
 "'CAPACITY' (branelink.py:39): Pendry's quantity is an entropy flow identified with information for a noiseless isolated medium (S5); he does not analyse a receiver (S6). The tree's pairing with a LIGO-class receiver (branelink.py:31-33) bounds, it does not estimate -- as the first audit said; now confirmed from the source's own caveat.",
 "PARTICLE STATISTICS: READ -- same bound for fermions (eq. 16) and bosons (p. 2168); equality only for massless bosons or a gapless Fermi band. Agrees with the first audit's computed Fermi-sea saturation (its check 4b) and with reaudit (i),(i').",
 "branelink.py:350 (S5 N(A)) has no drift: identically Pendry's bound (reaudit (h))."
]
d['rederivation']={
 "method": "sympy + mpmath",
 "script_path": D+"pendry_reaudit.py",
 "outcome": "13 of 13 PASS (output pendry_reaudit.out). (a) Pendry's I^2 <= (pi/3 ln^2 2) E/hbar is identical to branelink's form. (b)-(c) eq. (36) is the massless 1D Bose flux, E = pi k^2 T^2/(12 hbar) (Bose integral pi^2/6 by quadrature), and saturates the bound. (d) eqs. (32)-(35): Q <= pi k^2 T^2/(3 hbar), optimum channel temperature Tc = 2T, and the 'one quarter' of eq. (37) for Tc = T. (e) dE/dT = pi^2 k^2 T/(3h), the conductance quantum -- with (c) this is what fixes the OCR glyph as hbar. (f) eq. (17)'s '10^-16 W' at 1e9 bit/s is the right order (4.8e-17 W); 1 W carries 1.44e17 bit/s. (g) eq. (7): N channels give sqrt(N). (h) N(A) at branelink.py:350 is Pendry's bound. (i) a band edge keeps the ratio below the ceiling. One first-run FAIL was mine (sympy left the Bose integral unevaluated); replaced by zeta(2) with a quadrature cross-check. The first audit's 27-check script was re-run this stage: ALL PASS.",
 "agrees_with_source": "yes"
}
d['later_literature']=o['later_literature']
d['lacked_data']=("Pendry in 1983 lacked measured single-channel conductance quanta (photons 2006, electrons 2013; still titles only here) and a Holevo-capacity argument (Caves-Drummond 1994, Blencowe-Vitelli 2000; still summaries only). What the source shows he did NOT lack is the result itself: the per-channel form is printed and his own generality claim is explicitly bounded ('unproven in the general case'). The narrowing is a hypothesis gap (S2-S5), not a data gap; hbar is the only constant and moves the ceiling by 8.0e-6 (first audit check 8).")
d['grade']="NARROWED"
d['grade_evidence']=("READ at source. The ceiling's form and constant are Pendry's eq. (16) and abstract, identical to branelink.py:38-39 and :350 (reaudit (a),(h)), and the optimum eq. (36) saturates it (b)-(c). What is NARROWED is the 'field-blind' premise: Pendry proves statistics- and dispersion-independence only for a gas of independent particles in a ballistic channel with a group velocity, noiseless and isolated from thermal entropy (S2-S5); beyond that, in his words, it is 'unproven in the general case' and 'I suspect that the inequality as applied to a single channel holds completely generally'. The tree's OWNER statement is not contradicted -- branelink refuses the pass's use, and Pendry's own parallel-channel argument (eqs. 6-7; sqrt(N), reaudit (g)) and his silence on moving frames support that refusal. One tree status is stale: CLOSING_PREMISE_STATUS = 'NOT-FOUND' (branelink.py:163) with 'Pendry 1983 ... not read' (:40) -- the form is now found; universal field-blindness is still not. Not WRONG: nothing contradicts; not STANDS: the premise as named ('field-blind' for a gamma > 1 bulk carrier) holds only under hypotheses the tree does not carry. Bekenstein & Schiffer remains NAMED-NOT-READ.")
d['what_would_change_the_grade']=("STANDS for the premise would need a proof of the per-channel bound beyond free ballistic gases (interacting or diffusive media) plus a channel count for the bulk carrier and the massive-carrier boost; Bekenstein & Schiffer (IJMPC 1 (1990) 355) or Blencowe-Vitelli quant-ph/0001007 are where such an extension would be read. WRONG would need a single-channel counterexample inside S2-S5, of which none was found.")
d['reverify_command']=("python3 "+D+"pendry_reaudit.py   # expect 13 PASS, exit 0;  python3 /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/rederive/single-mode-capacity-ceiling-pendry-1983.py  # expect ALL PASS")
d['supersedes_grade']="OPEN (first audit, source NAMED-NOT-READ) -- superseded by NARROWED on a READ of the primary: form confirmed, 'field-blind' holds only under Pendry's printed free-gas/ballistic/noiseless hypotheses; the owner's refusal stands."
save(k,d)

# ---------------------------------------------------------------- 2 PLUMMER
k='plummer-enclosed-mass'; o=load(k); d=copy.deepcopy(o)
d['source']={
 "located": "H. C. Plummer, 'On the Problem of Distribution in Globular Star Clusters', MNRAS 71 (1911) 460-470. Google Drive fileId 1SiEv9SIOU1HSb8Tftnl1tI4A2hIXHPwC (title 'HC Plummer .pdf', 386,422 bytes, md5 67b7f66079dad089518b8a5b02d6d8e8 of the downloaded copy in scratchpad d67/reaudit/src/plummer1911.pdf), supplied by M. Identity confirmed from the page images: title 'On the Problem of Distribution in Globular Star Clusters. By H. C. Plummer, M.A. (Plate 8.)'; running heads 'Mr. H. C. Plummer, On the Problem of  LXXI. 5,' and 'Mar. 1911. Distribution in Globular Star Clusters.'; page numbers 460-470; margin stamp '1911MNRAS..71..460P'; 'Provided by the NASA Astrophysics Data System'.",
 "read_status": "READ (primary, all 14 PDF pages viewed as rendered images: pp. 460-470, Plate 8 'Curve of Apparent Density in Clusters', and Plates 9-10, which are E. E. Barnard's Mars photographs bound after the paper and unrelated). The Drive text layer is empty (ADS scan), so every quotation below is transcribed from the page image; equations (11)-(13) were read at 250 dpi.",
 "via": "mcp__Google_Drive__read_file_content returned only ADS link text; mcp__Google_Drive__download_file_content -> base64 decoded -> pymupdf render -> Read (image). Supersedes the first audit's NAMED-NOT-READ; galpy stays a secondary witness."
}
d['pages_read']=["Plummer MNRAS 71: pp. 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470 and Plate 8 (page images); Plates 9-10 (Barnard, Mars) viewed and not relevant"]
d['published_statement']=("READ (transcribed from page images). Plummer prints a DENSITY law, not a potential and not the 3-D enclosed mass. p. 463: 'and the second by Schuster‡ for γ=1·2, namely, φ(r)=(1+r²)^(-5/2) . . . (11) except for a numerical factor which we can omit.' Units are scaled so the core radius is 1: 'or, choosing the units to give the results in the simplest form, since we are not concerned with absolute values,' (p. 463). "
 "p. 464: 'φ(r)=N(1+r²)^(-5/2), F(r)=(2/3)πN(1+r²)^(-3/2), Σ(r)=(2/3)πNr(1+r²)^(-1/2) (12)' and 'f(r)=(4/3)N(1+r²)^(-2), σ(r)=(4/3)πNr²(1+r²)^(-1) . (13)', where (p. 461) 'φ(r)dv denotes the number of stars in a small volume dv; f(r)da denotes the number of stars in a cylinder of small section da ...; and F(r)dr denotes the number of stars lying between the planes x = r and x = r + dr', Σ is the count between the centre and the plane x = r, and σ the count within projected radius r. "
 "The mass relation is Plummer's own, p. 462: 'Also, if m is the mass within the radius r, dp/dr = − cmφ/r² , dm/dr = 4πr²φ .' "
 "The tree's fraction is therefore NOT printed by Plummer; it is one integration of his (12) with his dm/dr = 4 pi r^2 phi: m(r) = (4/3) pi N r^3 (1+r^2)^(-3/2), fraction outside R = 1 - (1+(a/R)^2)^(-3/2) with a the unit (reaudit script, rows 7-8). This matches linstab.py:217 and :547-551 exactly. Plummer's own projected fraction outside, from (13), is 1/(1+r^2) -- a different quantity the tree correctly does not use (reaudit row 9).")
d['published_hypotheses']=[
 "P1 NEWTONIAN SELF-GRAVITY, FLAT SPACE (p. 462): 'For convective equilibrium in a perfect gas we have p = atφ = bφ^γ ... Also, if m is the mass within the radius r, dp/dr = − cmφ/r² , dm/dr = 4πr²φ .' -- the enclosed mass is the flat-space volume integral of the density. This is the first audit's H1, now READ.",
 "P2 THE DENSITY IS SCHUSTER'S gamma = 1.2 SOLUTION (p. 463, eq. 11), i.e. polytrope index 5 (reaudit row 11), spherically symmetric, with the scale set to unity by choice of units; it extends to infinity ('According to our present ideas the cluster has no finite boundary', p. 465). First audit's H2, now READ.",
 "P3 PHYSICAL CONTEXT (p. 467): 'the distribution of stars in clusters resembles the distribution of density in a gravitating sphere of a particular kind of gas to which Schuster's solution applies.' Plummer himself finds it fails at the centre of M 3 (p. 470: 'found to be marked by a higher degree of condensation towards the centre than can be reconciled with the law'). The enclosed-mass fraction uses none of P3.",
 "NOT IN THE SOURCE: the potential -GM/sqrt(r^2+a^2) (derived here by Poisson, reaudit row 10), any relativistic mass, and any negative mass."
]
d['hypothesis_drift']=[
 "P1 DROPPED at specthm.py:524 and :648-651 (unchanged from the first audit, now checked against the source's printed hypothesis): specthm prints 'a fraction %.3e of its mass lies outside R_s, linstab.py's formula' for certify.py's exact conformastatic metric, where Plummer's dm/dr = 4 pi r^2 phi (flat Poisson) is not the mass. First audit computed the Misner-Sharp fraction f(1 - m/2R_s), -5.0e-5 relative at m = 0.02, below the printed precision (its script re-run this stage: ALL CHECKS PASS). The tree never scopes the number as Newtonian or leading order.",
 "P1 KEPT, to linear order, at linstab.py:215-219 and :927-932 (concentric.py via composite.py's linearised metric): exact there.",
 "ATTRIBUTION, not drift in effect: linstab.py:215-217 speaks of 'a Plummer core' and uses the fraction for 'concentric.py's exact potential', a potential -m/sqrt(r^2+a^2) form (concentric.py:46, :163). Plummer printed the density (11)-(12), not the potential or the 3-D enclosed fraction; both follow from his density and his own dm/dr relation (reaudit rows 7-10), so the naming is fair, but the formula is derived from Plummer rather than quoted from him.",
 "SIGN: Plummer's density is a positive star count; concentric.py:46 and certify.py use a core of mass -m. Under P1 the fraction does not depend on the sign (first audit). No change.",
 "P3 DROPPED, harmless (the enclosed-mass relation needs only P1-P2).",
 "Data: a = 0.02, R_s = 200.0 (concentric.py:155-156) give f = 1.4999999812500002e-8 (reaudit row 17; linstab's sympy value agrees)."
]
d['rederivation']={
 "method": "sympy (+ the first audit's GR script re-run)",
 "script_path": D+"plummer_reaudit.py",
 "outcome": "17 of 17 PASS (output plummer_reaudit.out). From Plummer's printed density N(1+r^2)^(-5/2): his eq. (12) F and Sigma, eq. (13) f and sigma (incl. his 'definite integral equal to 2/3'), and his p. 468 test {Sigma}^2/sigma = pi N/3 = Sigma(inf)/2 are all reproduced exactly. His dm/dr = 4 pi r^2 phi integrates to m(r) = (4/3) pi N r^3 (1+r^2)^(-3/2), whose outside fraction at r = R/a is the tree's 1-(1+(a/R)^2)^(-3/2). The projected fraction 1/(1+r^2) differs. Poisson gives the potential pair (not in Plummer). Plummer's own numbers check: Table I C at 1'.5 = 727.8 (printed 727); 7080 = 2 x 3540; N = 277 from 1160 = (4/3) pi N; Table V C at 0'.5 = 68; 34.6 per (1')^3. First audit's script re-run: ALL CHECKS PASS.",
 "agrees_with_source": "yes"
}
d['later_literature']=o['later_literature']
d['lacked_data']=("Nothing the enclosed-mass fraction depends on: it is exact algebra from Plummer's density under his own Newtonian mass relation, and a, R_s are design parameters. What Plummer lacked (a relativistic mass concept) is exactly the hypothesis the specthm use drops; the size of that gap was computed by the first audit (m/2R_s = 5e-5 relative).")
d['grade']="NARROWED"
d['grade_evidence']=("READ at source. Plummer's paper prints the density (11)-(12) and states the Newtonian mass relation 'dm/dr = 4πr²φ' (p. 462); integrating gives the tree's fraction exactly (reaudit, 17/17), and his own printed projections and numbers are reproduced, so the source is correctly identified and the formula is correct under its printed hypothesis P1. The NARROWING is unchanged from the first audit but now rests on the source's own words: specthm.py:524/:648-651 apply the number as 'a fraction ... of its mass' to certify.py's exact metric, outside P1, without scoping it as Newtonian; the GR (Misner-Sharp) fraction differs by m/2R_s = 5.0e-5 relative, below the printed %.3e. Nothing resting on it moves (f > 0 under every definition). Minor attribution note: the fraction and the potential are derived from Plummer, not printed by him.")
d['what_would_change_the_grade']=("STANDS if specthm scoped the printed fraction as Newtonian/leading-order (or used a GR mass for certify's metric). WRONG would need Plummer's density to differ from N(1+r^2)^(-5/2) -- it does not (read at 250 dpi).")
d['reverify_command']=("python3 "+D+"plummer_reaudit.py   # expect 17 PASS, exit 0;  python3 /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/rederive/plummer-enclosed-mass.py  # expect ALL CHECKS PASS")
d['supersedes_grade']="NARROWED (first audit, source NAMED-NOT-READ) -- superseded by NARROWED on a READ of the primary: same grade, now on Plummer's printed Newtonian mass relation."
save(k,d)
