import json, copy
D='/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/reaudit/'
RD='/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/rederive/'
def load(k): return json.load(open(D+'old_'+k+'.json'))
def save(k,d):
    fn=D+k.replace('/','_').replace('#','_')+'.json'; d['report_path']=fn
    json.dump(d,open(fn,'w'),indent=1,ensure_ascii=False); print('wrote',fn)

# ---------------------------------------------------------------- 3 WHITEHEAD
k='whitehead-convex-normal-neighbourhoods'; o=load(k); d=copy.deepcopy(o)
d['source']={
 "located": "J. H. C. Whitehead, 'Convex regions in the geometry of paths', Quart. J. Math. (Oxford) 3 (1932) 33-42. Google Drive fileId 1LY79WDjcfFwDTSwgu5Qt6DtZ8PBgVXkD (title 'convex regions in the geometry of paths.pdf'), supplied by M. Identity from the file's own pages: 'CONVEX REGIONS IN THE GEOMETRY OF PATHS By J. H. C. WHITEHEAD (Princeton) [Received 15 August 1931]'; running heads '34 J. H. C. WHITEHEAD' ... '42 J. H. C. WH1TEHEAD'; sections 1-4 end on p. 42 with the theorem. The journal title and volume are NOT printed in the text layer that was read, so 'Quart. J. Math. 3' rests on the citation plus the matching page run 33-42, title, author and 1931 receipt date.",
 "read_status": "READ (primary, pp. 33-42 in full, OCR text via Google Drive read_file_content). Several displayed formulas are garbled (e.g. the Lipschitz inequality (2.3) reads ')-n\\*(\\*o)| \\< A £ \\\\x\\\\-x\\\\\\\\'); the symbol Gamma is rendered 'T' or 'r j t'. Where a formula is garbled the prose around it is quoted instead.",
 "via": "mcp__Google_Drive__read_file_content(fileId=1LY79WDjcfFwDTSwgu5Qt6DtZ8PBgVXkD). Supersedes the first audit's NAMED-NOT-READ."
}
d['pages_read']=["Whitehead Quart. J. Math. 3: pp. 33-42 (whole paper incl. footnotes), OCR text layer"]
d['published_statement']=("READ. Aim, p. 33: 'We shall show that any non-singular point in an affine, or projective, space of paths is contained in a simple, convex region which can be made as small as we please.' Definitions: 'Such a region will be called simple, because not more than one, and convex, because at least one path joins any two points.' "
 "Theorem, p. 42: 'If U is any open region in an affine apace of paths, and if P is any point in U, there is a simple and completely convex closed region con- taining P and contained in U. Another statement of this theorem is: an affine space of paths has a set of convex regions for a fundamental set of neighbourhoods.' Corollary: 'In particular the theorem'applies to the geodesies in a Riemannian space. A Riemannian space with a positive ds2 has a set of convex spheres for a fundamental set of neighbourhoods.' "
 "The word 'normal' enters only through the classical single-point theorem Whitehead cites (p. 33): 'A classical theorem ... asserts the existence of a region Cq containing a given point q in a Riemannian space, such that any point in Gq can be joined to q by one and only one geodetic segment which does not leave Cg. A similar theorem holds for the geometry of paths, and is equivalent to the statement that a normal coordinate-system exists having q as origin.'")
d['published_hypotheses']=[
 "W1 AN AFFINE (OR PROJECTIVE) SPACE OF PATHS, direction-independent connection (p. 34 footnote): 'This note only applies to the restricted geometry of paths as apart from more general theories in which r j t [Gamma^i_jk] depend on the direction dx.' The main theorem makes no use of a metric or its signature; only the corollary is stated for 'a Riemannian space with a positive ds2'. The Levi-Civita connection of a Lorentzian metric is such a connection, so the theorem (not the corollary) covers it.",
 "W2 REGULARITY = LIPSCHITZ CONNECTION ON A CELL (p. 34): 'We assume T to be defined in the region |xf| \\< 2, (2.2) to be bounded, continuous, and to satisfy a Lipschitz condition' [(2.3), OCR-garbled]. p. 37: 'We shall only need their continuity, and this follows from the Lipschitz condition, without assuming the existence* of dV/dx' [dGamma/dx]. For a Levi-Civita connection this is: metric C^{1,1} and non-degenerate on an open neighbourhood of the point. CORRECTION to the first audit, which called C^2 classical and C^{1,1} a later extension: Whitehead's own printed hypothesis is already Lipschitz Gamma.",
 "W3 'NON-SINGULAR POINT' (p. 33): in context a point with a coordinate cell on which W2 holds.",
 "W4 LOCAL AND SIZELESS: the region 'can be made as small as we please' (p. 33); no lower bound on its size is asserted anywhere.",
 "NOT IN THE SOURCE: global hyperbolicity, causal structure, a hyperbolic chart, or 'normal neighbourhood of each of its points' as a stated conclusion (Whitehead proves 'simple' -- at most one path in the region joins two points -- and 'completely convex', with continuous dependence of the path on its end-points, p. 37)."
]
d['hypothesis_drift']=[
 "WEAKENED -- W2 DROPPED (qeihps.py:103-105, :436-439): the 'MET LOCALLY' verdict at qeihps.py:439 is computed from (f0 > 0 and r0 > 0), non-degeneracy at ONE point. Whitehead's printed hypothesis is a bounded, continuous, LIPSCHITZ connection on a whole coordinate cell (p. 34). The Christoffels of metric (2) are f'/2f, f'/2, -r r', r'/r (reaudit row 1), so W2 needs f, r in C^{1,1} and positive on a neighbourhood. The point test does not give it: f = 1/(1+|l|^{3/2}) passes the point test (f(0) = 1) but Gamma^l_tt is not Lipschitz at 0 (difference quotient 7.5e3 at h = 1e-8 and growing) and l = 0 and l = s^4/256 are two geodesics with the same initial data (reaudit rows 3-4; first audit rederive B). The tree itself records TAYLOR_RADIUS_OF_CONVERGENCE_PROVED = False (qeihps.py:338): off the throat HPS's metric is a jet plus a numerical solution. Plausible for a smooth ODE solution; not established in the tree.",
 "ADDED BY FOLDING (qeihps.py:101-105): FFKP's requirement ('M globally hyperbolic, f supported in a SMALL SAMPLING DOMAIN: an open set inside a globally hyperbolic convex normal neighbourhood, one hyperbolic chart') is met by citing Whitehead alone. Whitehead supplies a simple, completely convex region and nothing causal (see NOT IN THE SOURCE). Global hyperbolicity of a small convex region and the hyperbolic chart come from elsewhere (Fewster-Smith 0702056 p. 7, asserted there without citation; READ by the first audit).",
 "NAMING, minor: the tree says 'convex normal neighbourhood'. Whitehead's printed conclusion is 'simple and completely convex'; 'normal' appears only in the single-point classical theorem he cites (p. 33). The modern term (a region that is a normal neighbourhood of each of its points) is the textbook reading of Whitehead and is not quoted from him; with W2 it is not needed for the FFKP use beyond what 'simple, convex' gives. Recorded, not repaired.",
 "'LORENTZIAN' (qeihps.py:103, canonical hypothesis): harmless. READ: the main theorem is about any affine space of paths (W1); signature enters only the Riemannian corollary.",
 "SIZE (qeihps.py:114-117): READ -- Whitehead asserts no size ('can be made as small as we please', W4), and the tree labels its sub-Planckian remark a CAVEAT, which is correct. The first audit's scope note stands: that remark is bounded by computation in the angular directions only (pi r0 = 0.0763 l_P); on the throat worldline the tidal tensor vanishes."
]
d['rederivation']={
 "method": "sympy + numeric (plus the first audit's 17-check script re-run)",
 "script_path": D+"whitehead_reaudit.py",
 "outcome": "5 of 5 PASS (output whitehead_reaudit.out). Christoffels of -f dt^2 + dl^2 + r^2 dOmega^2 computed symbolically: all built from f'/f, f', r r', r'/r, so Whitehead's Lipschitz-Gamma hypothesis is C^{1,1} (and positivity) of f and r on a cell. The C^1-not-C^{1,1} metric f = 1/(1+|l|^{1.5}) passes the tree's point test yet violates Whitehead's (2.3) and has two geodesics l = 0, l = s^4/256 from the same data. One first-run FAIL was mine (I wrote s^4/144; 12c = (3/4)sqrt(c) gives c = 1/256), corrected; it matches the first audit. First audit's script re-run: ALL 17 CHECKS PASS.",
 "agrees_with_source": "yes"
}
ll=[x for x in o['later_literature']]
for x in ll:
    if 'Hartman' in x['ref']:
        x['what']=x.get('what','')+" NOTE (re-audit): Whitehead's own hypothesis (p. 34) is already a Lipschitz connection, so the C^{1,1} threshold is not a later narrowing of Whitehead but his printed condition; below it (Hartman-Wintner type) is outside the theorem."
d['later_literature']=ll
d['lacked_data']=o['lacked_data'] if isinstance(o['lacked_data'],str) else o['lacked_data']
d['grade']="NARROWED"
d['grade_evidence']=("READ at source. Whitehead proves that every point of an affine space of paths whose connection is bounded, continuous and Lipschitz on a coordinate cell lies in arbitrarily small simple, completely convex regions (pp. 33-34, 42). The theorem is true and applies to a Lorentzian Levi-Civita connection. The tree's use is NARROWED on the source's printed hypotheses: (1) qeihps.py:439 infers 'MET LOCALLY' from non-degeneracy at one point, while Whitehead requires a Lipschitz connection on a neighbourhood (metric C^{1,1}); the point test is shown insufficient (reaudit rows 3-4) and the tree records its Taylor radius as unproved (qeihps.py:338). (2) Whitehead supplies nothing causal, so the 'globally hyperbolic' and 'hyperbolic chart' parts of FFKP's domain hypothesis are not delivered by the citation. (3) Minor: 'convex normal' is the modern name, Whitehead's words are 'simple and completely convex'. The size caveat is consistent with Whitehead ('as small as we please'). Correction to the first audit recorded: C^{1,1} is Whitehead's own condition, not a later extension. Not WRONG: nothing contradicts, and the downstream FFKP status is OPEN, not claimed MET.")
d['what_would_change_the_grade']=("STANDS if the tree (a) establishes that HPS's metric functions f, r are C^{1,1} and positive on an open neighbourhood of the throat (a proved Taylor radius, TAYLOR_RADIUS_OF_CONVERGENCE_PROVED = True, or an ODE regularity argument) -- which is exactly Whitehead's printed hypothesis (2.2)-(2.3) -- and (b) cites a READ source for the globally hyperbolic small neighbourhood and hyperbolic chart instead of Whitehead alone. WRONG is not foreseeable: the theorem has no data input.")
d['reverify_command']=("python3 "+D+"whitehead_reaudit.py   # expect 5 PASS, exit 0;  python3 "+RD+"whitehead-convex-normal-neighbourhoods.py  # expect ALL 17 CHECKS PASS")
d['supersedes_grade']="NARROWED (first audit, source NAMED-NOT-READ) -- superseded by NARROWED on a READ of the primary: same grade, now on Whitehead's printed Lipschitz-connection hypothesis (which also corrects the first audit's 'C^2 classical, C^{1,1} later' remark)."
save(k,d)

# ---------------------------------------------------------------- 4 EARNSHAW
k='earnshaw-1842-theorem'; o=load(k); d=copy.deepcopy(o)
d['source']={
 "located": "S. Earnshaw, 'On the Nature of the Molecular Forces which regulate the Constitution of the Luminiferous Ether', Trans. Camb. Phil. Soc. 7 (1842) 97-112. Google Drive fileId 12iiWL9w9aYRRJBskU60Lo0nEDN3e4hOS (title 'EarnshawPaper.pdf'), supplied by M. Identity from the file's own pages: 'Transactions of the Cambridge Philosophical Society'; 'V. On the Nature of the Molecular Forces which regulate the Constitu- tion of the Luminiferous Ether. By S. EARNSHAW, M. A. of St. John's College, Cambridge. [Read March 18, 1839.]'; 'VOL. VII. PART I.'; running heads 'MR EARNSHAW, ON THE NATURE' / 'OF MOLECULAR FORCES.' with page numbers 98-112; signed 'S. EARNSHAW.'; Google digitisation marks. The printed year 1842 does not appear in the text read (only the reading date 1839); vol. VII and the page run 97-112 match the citation.",
 "read_status": "READ (primary, pp. 97-112 in full, OCR text via Google Drive read_file_content). Second-derivative symbols are badly garbled (d²V/dx² appears as 'd,V', 'd;V', 'dV', 'd¡V'); the structure (three second derivatives summing to zero) is unambiguous from the prose. Where a formula is lost, the prose is quoted.",
 "via": "mcp__Google_Drive__read_file_content(fileId=12iiWL9w9aYRRJBskU60Lo0nEDN3e4hOS). Supersedes the first audit's NAMED-NOT-READ."
}
d['pages_read']=["Earnshaw Trans. Camb. Phil. Soc. VII: pp. 97-112 (whole memoir, Arts. 1-22), OCR text layer"]
d['published_statement']=("READ. Art. 3 (p. 101): the second derivatives of V at a point of neutral attraction 'are subject to the condition, 0 = dV + dV + dᏤ ; and because at least one of these coefficients will be negative, and one positive, the equation is that of an hyperboloid.' "
 "Art. 11 (p. 104): 'Hence, if the system consisted of fixed particles, the particle P only being moveable, the equations for P's motion would be ... very nearly.' Art. 12 (p. 105): 'Since one at least of the quantities dV, dV, dV is negative, and one at least positive, there will be at least one principal axis parallel to which a disturbed particle can vibrate, and at least one parallel to which a disturbed particle cannot vibrate.' ... 'C'e¹+C\" e-al; a result which shews that a must increase continually with t The motion in this direction will therefore be one of translation.' "
 "Art. 15 (p. 106): 'It appears then that at the most, the equilibrium can only be stable in one plane' ... 'cannot be removed by supposing the particles to repel each other with forces varying ac- cording to the same law. The equation dV+V+ dV = 0, from which the instability arises, holds equally for attraction and repulsion.' 'It may be observed also that the instability cannot be removed by arrangement; ... there will always exist a direction of instability.' "
 "The degenerate case, Art. 8 (pp. 102-103): 'If the position of equilibrium be such, that dV = 0, d; V = 0, and dV 0, then ... the particle is unattracted in every direction, at least for small displacements from the position of equilibrium. An example of this is afforded in the case of a particle placed within a spherical or ellipsoidal surface, composed of attracting or repelling par- ticles.' followed by 'we shall, in what follows, always suppose that none of the quantities dV, dV, dV are evanescent'. "
 "Beyond 1/D^2, Art. 16 (p. 106-107): 'd; V + d¿V + d¡ V = (n − 2) (). . (1).' ... 'But when n is less than 2 the right-hand member of (1) is negative, in which case it is possible that all the equations (2) may denote vibration.'")
d['published_hypotheses']=[
 "E1 INVERSE-SQUARE FORCE EXACTLY (Intro I and Art. 16): 'a force, whether attractive or repulsive, varying according to this law, is the only one which cannot possibly actuate the particles of a vibrating medium'; for 1/D^n the sum is (n-2)(...), zero only at n = 2 (reaudit row 2).",
 "E2 ONE MOVEABLE PARTICLE AMONG FIXED ONES, LINEARISED (Art. 11): 'if the system consisted of fixed particles, the particle P only being moveable, the equations for P's motion would be ... very nearly.'",
 "E3 SIGNS: attraction, repulsion, and mixtures. Art. 2: 'The proposition is true of re- pulsive forces, or if some of the particles exert repulsive and some attractive forces'; Art. 7: 'If the molecular forces are all repulsive, then the sign of V will be changed: but the parametric surfaces will be hyperboloids, as before'; Art. 15 quoted above. The moveable particle's own inertia is taken positive implicitly (acceleration = force).",
 "E4 NON-EVANESCENT SECOND DERIVATIVES (Art. 8): the case where they vanish is set aside as 'unattracted ... at least for small displacements' (no restoring force at linear order), with the shell as example; its stability beyond linear order is not decided.",
 "E5 ANY ARRANGEMENT (Art. 15): 'the instability cannot be removed by arrangement'. Generality of setting (p. 98): 'I think it probable, that most terrestrial bodies possess in a greater or less degree of per- fection the properties here assumed'."
]
new_drift=[
 "CONFIRMED AT SOURCE (stability.py:115-117): 'the Hessian of 1/r is traceless' is Earnshaw's Art. 3 condition (sum of the three second derivatives = 0); 'for any signs' is Art. 2/7/15 (attraction, repulsion, mixed); 'any placement' is Art. 15 ('cannot be removed by arrangement'). The degenerate escape and the shell are Earnshaw's own Art. 8 example ('a particle placed within a spherical or ellipsoidal surface ... unattracted in every direction'), so 'Newton's shell theorem hands the device exactly that' (stability.py:118-119) is what Earnshaw printed.",
 "SCOPE BEYOND THE PRINTED THEOREM, conclusion intact (stability.py:116-117 'NO static configuration is stably in equilibrium'): Earnshaw proves it for one moveable particle with the rest fixed, at linear order (E2). The extension to a configuration whose particles all move follows for positive inertia (a strict minimum of the full U would restrict to a strict minimum for each particle with the others held), and for the tree's negative-mass case by the first audit's traceless-K computation (its S4). Neither step is in Earnshaw.",
 "ESCAPE SHARPER THAN EARNSHAW'S (stability.py:118 'The one escape Earnshaw permits is the DEGENERATE case, constant potential'): Earnshaw's set-aside class is wider -- ALL second derivatives evanescent at the point (E4) -- and he calls it neutral at linear order without deciding it. The tree's narrowing to 'constant potential' is TRUE (a non-constant harmonic function has no local minimum, first audit S2; zero-Hessian non-constant points are unstable, S5 numerics, Chetaev-Kozlov NAMED-NOT-READ) but it is not Earnshaw's statement. Attribution recorded, not repaired.",
 "INERTIA SIGN not in Earnshaw (E3): his equation of motion takes the moveable particle's response as positive. The tree's 'for any signs' includes negative (Bondi) masses; covered by the first audit's S4, not by the source."
]
d['hypothesis_drift']=new_drift+o['hypothesis_drift']
d['rederivation']={
 "method": "sympy + numpy (plus the first audit's script re-run)",
 "script_path": D+"earnshaw_reaudit.py",
 "outcome": "6 of 6 PASS (output earnshaw_reaudit.out). Art. 3/15: Lap(1/D) = 0 for either sign. Art. 16: for force ~ 1/D^n, Lap(D^-(n-1)/(n-1)) = (n-2) D^-(n+1). Art. 11-12/15: 400 equilibria of a moveable particle among four fixed mixed-sign sources, every one with a traceless Hessian of mixed signature; x'' = a^2 x gives C'e^{at} + C''e^{-at}. Art. 8: V inside a uniform spherical shell is constant (4 pi R). Art. 20: Newtonian attraction plus repulsion ~1/D^n gives Lap V = -(n-2) m D^-(n+1), independent of the attraction. First audit's script re-run: ALL PASS.",
 "agrees_with_source": "yes"
}
d['later_literature']=o['later_literature']
d['data_at_publication']=o['data_at_publication']
d['lacked_data']=o['lacked_data']
d['grade']="STANDS"
d['grade_evidence']=("READ at source; the first audit's re-derivation-based STANDS is now confirmed against Earnshaw's printed text. Earnshaw's Arts. 3, 11-12 and 15 give exactly the tree's mechanism: the three second derivatives of an inverse-square potential sum to zero, so at any equilibrium at least one direction is exponentially unstable ('a result which shews that a must increase continually'), for attraction, repulsion or mixtures and for any arrangement. His Art. 8 sets aside the evanescent case as neutral with the shell as the example -- the tree's 'one escape ... Newton's shell theorem hands the device exactly that' (stability.py:118-119), on which 'neutral ... is the Newtonian CEILING' rests. What the tree adds beyond the printed theorem is true and was re-derived (all-particles-free extension, negative inertia, and the sharpening of the escape to 'constant potential'), so these are attribution notes, not a narrowing of the claim. Earlier caveats remain as recorded (Chetaev-Kozlov NAMED-NOT-READ for the zero-Hessian step; 'Newtonian' must mean an exactly 1/r kernel).")
d['what_would_change_the_grade']=("NARROWED if the tree's claim were read strictly as Earnshaw's own theorem: the printed result is single-moveable-particle, linear-order, non-evanescent; the zero-Hessian and all-free/negative-inertia parts rest on steps outside Earnshaw (first audit S2, S4, S5; Chetaev-Kozlov not read). WRONG would need a stable static equilibrium under an exactly 1/r kernel, which contradicts Earnshaw Art. 3/12 and the re-derivation.")
d['reverify_command']=("python3 "+D+"earnshaw_reaudit.py   # expect 6 PASS, exit 0;  python3 "+RD+"earnshaw-1842-theorem.py  # expect ALL PASS")
d['supersedes_grade']="STANDS (first audit, by re-derivation, source NAMED-NOT-READ) -- superseded by STANDS on a READ of the primary, with attribution notes on what the tree adds beyond Earnshaw's printed single-particle, non-evanescent theorem."
save(k,d)

# ---------------------------------------------------------------- 5 MATERIALS
k='material-strength-t1000-becu'; o=load(k); d=copy.deepcopy(o)
d['source']={
 "located": "Maker data sheets: Toray 'TORAYCA T1000G' data sheet (toraycma.com/wp-content/uploads/T1000G-Data-Sheet_02.16.2024.pdf); Materion 'Alloy 25 (C17200)' strip / rod-and-bar data sheets. M could not obtain them. This stage searched for sources that CITE them and read three arXiv papers that tabulate the materials, none of which cites either data sheet.",
 "read_status": "NAMED-NOT-READ at source (maker sheets). NOT READ-VIA-RESTATEMENT: no source restating the data-sheet figures was found. READ (secondary, independent of the sheets): arXiv:2202.09783 Table I (T1000 composite row, citing Bolund et al. 2007); arXiv:2005.04976 Table 2 and Sec. 1 (measured Cu-2wt%Be strengths; ASM citation); arXiv:2410.14855 Table 2 (BeCu yield); arXiv:2403.13955 (C17200 TF00 temper named, no strength); arXiv:2508.02730 p. 1 (C17200 TH04 named as candidate).",
 "via": "WebFetch https://www.toraycma.com/wp-content/uploads/T1000G-Data-Sheet_02.16.2024.pdf -> EGRESS_BLOCKED (www.toraycma.com); WebFetch https://www.cf-composites.toray/resources/data_sheets/ -> EGRESS_BLOCKED; WebFetch https://materion.com/-/media/files/alloy/datasheets/copper-beryllium/alloy-25-strip-datasheet.pdf -> EGRESS_BLOCKED (materion.com); WebFetch https://www.materion.com/en/products/alloys/copper-beryllium-alloys/alloy-25 -> EGRESS_BLOCKED. Not routed around (maker URLs were NOT passed to alphaXiv or any other fetcher). alphaXiv discover_papers x9 (T1000G; C17200; flywheel; CNT fibre vs T1000; space elevator; BeCu tables) and answer_pdf_queries on 2202.09783, 2508.02730, 2410.14855, 2403.11316 (a T700G paper, no T1000 data), 2403.13955, 2005.04976, 2004.13352 (plots T1100G, prints no T1000G value), 2302.10358 (no T1000G value), 1501.07100 (no BeCu table), 1908.09339 ('Carbon fibre 1750 4.3e9', grade unnamed, 'Values taken straight from Wikipedia'), 1609.00709 (no carbon-fibre value)."
}
d['pages_read']=["arXiv:2202.09783 pp. 1-20 (Table I p. 3)","arXiv:2005.04976 pp. 1-35 (Sec. 1 p. 4, Table 2 p. 24)","arXiv:2410.14855 pp. 1, 4, 7-9, 15-17, 19-23 (Table 2 p. 16)","arXiv:2403.13955 pp. 1, 3, 11-12, 14, 18","arXiv:2508.02730 p. 1","arXiv:2004.13352 pp. 1, 8-16, 28-30, 33, 35, 45-46, 52, 62, 67-72","arXiv:2302.10358 pp. 1, 5-6, 12, 21-23","arXiv:1908.09339 pp. 1-4, 6-8, 10, 15-16","arXiv:2403.11316 pp. 1-10","arXiv:1501.07100 pp. 1, 14, 19","arXiv:1609.00709 pp. 1-11"]
d['published_statement']=("The data-sheet values themselves are NOT READ (egress-blocked; no citing source found). What was READ, verbatim: "
 "(1) arXiv:2202.09783 p. 3, 'Table I Comparison of different rotor materials [13]' with rows 'Materials Density (kg/m3) Tensile strength (MPa) ...' and 'Carbon T1000 1520 1950 350 101.8 3.47', [13] = 'B. Bolund, H. Bernhoff, M. Leijon, Flywheel energy and power storage systems, Renewable and Sustainable Energy Reviews. 11 (2007) 235-258' -- a rotor-material (composite) row, not the fibre data sheet; the same paper writes 'E/m = K sigma/rho (2) where K is the shape factor'. "
 "(2) arXiv:2005.04976 Table 2 (measured, Cu-2 wt.% Be): 'CG ... 325oC for 10 hours 1170 1280 6' (sigma0.2, UTS in MPa, elongation %) and 'HPT ... 275oC 10 hours 1300 1375 4'; Sec. 1 p. 4 citing ASM (Davis 2001): 'a material with a hardness up to 400 HV, which corresponds to a 1100 MPa yield stress'. "
 "(3) arXiv:2410.14855 Table 2: 'BeCu 129 1000' (Young's modulus GPa, yield stress MPa), no source given. "
 "No read source states a BeCu density. The tree's use (warpfolder.py:224-227): ('carbon fibre T1000', 6.4e9 Pa, 1800 kg/m^3) and ('beryllium-copper', 1.4e9 Pa, 8250 kg/m^3), status ORDER, feeding burst_speed_m_s = sqrt(sigma/rho) (warpfolder.py:328-330) and the selftest's rounded factors [4.2, 19.4] (warpfolder.py:566-567).")
d['hypothesis_drift']=o['hypothesis_drift']+[
 "RE-AUDIT, fibre vs composite (READ): the only T1000 figure read this stage is a rotor-composite row, 1950 MPa at 1520 kg/m^3 (2202.09783 Table I via Bolund 2007). It gives a ring factor 7.07 against the tree's 4.25 (reaudit), confirming from a read source the first audit's computed direction: the tree's fibre figure favours the rotor.",
 "RE-AUDIT, BeCu temper (READ): measured peak-aged coarse-grained Cu-2Be UTS 1280 MPa (325 C / 10 h) and nanostructured 1375 MPa give ring factors 20.3 and 19.6 at the tree's 8250 kg/m^3, 1-5% above the tree's 19.4; the tree's 1.4e9 Pa sits at or above the read peak-aged UTS, so it is conservative. Density remains unread."
]
d['data_at_publication']=o['data_at_publication']+[
 {"quantity":"T1000 composite (rotor material) strength and density","value_then":"not used by the tree (fibre value 6.4e9 Pa, 1800 kg/m^3)","value_now":"1950 MPa, 1520 kg/m^3","source_now":"arXiv:2202.09783 Table I, citing Bolund et al., RSER 11 (2007) 235 -- READ (restatement of Bolund, not of the Toray sheet)","moves_conclusion":"No; ring factor 4.25 -> 7.07 (over the limit by more)."},
 {"quantity":"Cu-2Be (C17200-class) UTS, peak-aged, measured","value_then":"1.4e9 Pa (ORDER, temper unnamed)","value_now":"1280 MPa (CG, 325 C 10 h); 1375 MPa (HPT + 275 C 10 h); yield 1170 MPa (CG)","source_now":"arXiv:2005.04976 Table 2 -- READ (a measurement, not the Materion sheet)","moves_conclusion":"No; ring factor 19.4 -> 19.6-20.3."}
]
d['rederivation']={
 "method": "python (imports warpfolder.py; first audit's 15-check script re-run)",
 "script_path": D+"materials_reaudit.py",
 "outcome": "5 of 5 PASS (output materials_reaudit.out). Tip speed 8011.06 m/s; tree factors 4.2485 and 19.4470 (round to [4.2, 19.4]). On the READ values: T1000 composite row ring 7.07 / disc 4.54; Cu-2Be UTS 1280 MPa ring 20.34 / disc 13.06; 1375 MPa ring 19.62 / disc 12.60; BeCu yield 1000 MPa ring 23.01. Every read value leaves the rotor over its limit as a ring and as a uniform disc. The first audit's script re-run: FAILURES: 0.",
 "agrees_with_source": "partly (maker sheets not read; independent secondary values agree in direction)"
}
ll=[x for x in o['later_literature'] if '2005.04976' not in x['ref']]
ll+= [
 {"ref":"arXiv:2005.04976, Lomakin, Castillo-Rodriguez, Sauvage, 'Microstructure, mechanical properties and aging behaviour of nanocrystalline copper-beryllium alloy' (2020)","effect":"confirms","what":"Measured Cu-2wt%Be: Table 2 'CG ... 325oC for 10 hours 1170 1280 6' and 'HPT ... 275oC 10 hours 1300 1375 4'; Sec. 1 citing ASM: 'hardness up to 400 HV, which corresponds to a 1100 MPa yield stress'. Peak-aged UTS 1.28-1.38 GPa, at or just below the tree's 1.4 GPa. No density.","read_status":"READ (alphaXiv answer_pdf_queries, pp. 1-35)"},
 {"ref":"arXiv:2202.09783, Li & Palazzolo, 'Analysis and optimization of a novel energy storage flywheel for improved energy capacity' (2022)","effect":"confirms","what":"Table I (from Bolund et al. 2007): 'Carbon T1000 1520 1950' kg/m^3, MPa -- a rotor-composite row; also E/m = K sigma/rho with shape factor K, and the solid-disc peak stress (3+nu)/8 rho omega^2 b^2 at the centre (p. 10), which is the first audit's geometry narrowing stated in print.","read_status":"READ (alphaXiv answer_pdf_queries, pp. 1-20)"},
 {"ref":"arXiv:2410.14855, Li et al., 'Pivot Bearings for Efficient Torsional Magneto-Mechanical Resonators' (2024)","effect":"confirms","what":"Table 2: 'BeCu 129 1000' (E in GPa, yield in MPa), unsourced.","read_status":"READ (alphaXiv answer_pdf_queries)"}
]
d['later_literature']=ll
d['lacked_data']=("The exact maker figures (Toray T1000G strength/density/test basis; Materion C17200 temper-by-temper UTS and density) remain unread: every maker host is egress-blocked and no read paper restates them with a citation. The read secondary values (a T1000 composite row; measured peak-aged Cu-2Be UTS) bound the answer on the side that matters: both leave the rotor further over its limit than the tree's ORDER inputs, so the conclusion ROTOR_IS_WITHIN_MATERIAL_LIMITS = False does not depend on the missing sheets. Only the pinned digit (4.2 vs 4.3 at 6,370 MPa, first audit R5b) would need the Toray sheet.")
d['grade']="NARROWED"
d['grade_evidence']=("Unchanged grade, same basis as the first audit: sqrt(sigma/rho) is the thin-ring limit, called 'the classical rotor limit' and applied to 'the rotor' (warpfolder.py:117-118, :328-330); a uniform disc allows sqrt(8/(3+nu)) = 1.557x more and a Stodola profile has no fixed multiple (first audit R2-R4, re-run: 0 failures) -- the solid-disc centre stress (3+nu)/8 rho omega^2 b^2 is also printed in the READ 2202.09783 (p. 10). ROTOR_IS_WITHIN_MATERIAL_LIMITS = False survives on every geometry for BeCu and on ring and disc for T1000. On the data: the maker sheets are still NOT READ (egress-blocked, not routed around) and no citing restatement was found, so the exact published figures stay OPEN; the secondary values that WERE read (T1000 composite 1950 MPa / 1520 kg/m^3; measured peak-aged Cu-2Be 1280-1375 MPa) move the factors to 7.07 and 19.6-20.3, i.e. further over the limit, so the tree's ORDER inputs are conservative.")
d['what_would_change_the_grade']=o['what_would_change_the_grade']+" RE-AUDIT: reading the Toray and Materion sheets (or a paper that quotes them with citation) would settle the pinned digit and the density; it cannot rescue the rotor, since every read value is less favourable than the tree's."
d['reverify_command']=("python3 "+D+"materials_reaudit.py   # expect 5 PASS, exit 0;  python3 "+RD+"material-strength-t1000-becu.py  # expect FAILURES: 0")
d['supersedes_grade']="NARROWED (first audit; sheets NAMED-NOT-READ) -- superseded by NARROWED: same grade and basis; maker sheets still NAMED-NOT-READ (egress-blocked, no citing restatement found); independent secondary values READ and all less favourable to the rotor."
save(k,d)
