#!/usr/bin/env python3
"""Writes the re-audit JSONs for cosmic-string-deficit-angle-8pigmu and elementary-flatness-regular-axis."""
import json, os
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/reaudit"
SRC = D + "/src"

cs = {
 "key": "cosmic-string-deficit-angle-8pigmu",
 "name": "Cosmic string conical deficit angle = 8 pi G mu, mu positive linear mass density (axial.py O4 closure: 'an angle excess is the deficit of a negative mu')",
 "source": {
  "located": "A. Vilenkin, 'Gravitational field of vacuum domain walls and strings', Phys. Rev. D 23, 852-857 (1981). Google Drive fileId 1FCKbK8Bl_Kgs07W4-6dM4jHS7NK2VCah (PDF, 6 pages, 407,488 bytes, md5 a8bd04e219b2eb47db837478f0775f88; copy at " + SRC + "/vilenkin1981.pdf). Identity confirmed from its own first page: running head 'PHYSICAL REVIEW D  VOLUME 23, NUMBER 4  15 FEBRUARY 1981', title 'Gravitational field of vacuum domain walls and strings', 'Alexander Vilenkin, Department of Physics, Tufts University ... (Received 10 October 1980)', folio '23 852 (c) 1981 The American Physical Society'. (Drive's own text layer misprints the volume as '28'; the page image reads 23.) Also READ, as a later restatement: Hindmarsh & Kibble, 'Cosmic strings', hep-ph/9411342 (Rep. Prog. Phys.), pp. 16, 53, 54, 85 via alphaXiv; its ref. [160] is 'Vilenkin A 1981 Phys. Rev. D 23 852'.",
  "read_status": "READ",
  "via": "Google Drive read_file_content (text layer, scrambled column order) and download_file_content; the PDF was decoded and pages 852-857 rendered to PNG and read as images, so every equation quoted below was checked against the page image, not the OCR. Hindmarsh-Kibble read through alphaXiv answer_pdf_queries (extracted text; some Greek glyphs are dropped by the extractor, noted where quoted)."
 },
 "published_statement": "Vilenkin, verbatim. Scope, abstract p.852: 'The gravitational properties of vacuum domain walls and strings are studied in the linear approximation of general relativity. These properties are shown to be very different from those of regular massive planes and rods.' The string source, p.853: 'Consider a static string parallel to the z axis. ... and assuming that all the fields phi^(i) are functions only of x and y, we find that T~^0_0 = T~^3_3 (9) and that all other components are equal to zero ... Thus, the energy-momentum tensor of the string is given by T~^nu_mu(x,y) = mu delta(x-a) delta(y-b) x diag(1, 0, 0, 1), (11) where mu is the linear energy density.' Linearised equations, p.853 eq.(14): '(nabla^2 - d_t^2) h_mu nu = 16 pi G (T_mu nu - 1/2 eta_mu nu T)'. The general massive string, p.854 eq.(20): 'h_00 = h_33 = 4G(mu + p) ln(r/r_0), h_11 = h_22 = 4G(mu - p) ln(r/r_0). Here p is the pressure in the z direction ... For a vacuum string, p = -mu and h_00 = h_33 = 0, h_11 = h_22 = 8 G mu ln(r/r_0). (21)'. The cone, p.854 eqs.(27)-(33): 'ds^2 = dt^2 - dz^2 - (1 - lambda)(dr^2 + r^2 dphi^2), (27) where lambda = 8 G mu ln(r/r_0). (28) Introducing a new radial coordinate r' as (1 - lambda) r^2 = (1 - 8 G mu) r'^2, (29) (1 - lambda) dr^2 = dr'^2, (30) we get ds^2 = dt^2 - dz^2 - dr'^2 - (1 - 8 G mu) r'^2 dphi^2. (31) With a new angular coordinate phi' = (1 - 4 G mu) phi, (32) the metric takes a Galilean form ... (33) This metric, however, does not describe a Euclidean space, since phi' changes from 0 to (1 - 4 G mu) 2 pi. Such space can be called conical.' and eq.(34): 'Thus the light deflection is delta phi = 4 pi G mu and is independent of the impact parameter rho.' Exact solution, p.856: 'there exists an exact static solution which matches with the weak-field approximation (33). It is just the locally flat \"conical\" space (33) with 0 < phi' < (1 - 4 G mu) 2 pi.' ... 'The metric (41) can be matched with the weak-field approximation (33) only if K - 1 = O(G^2 mu^2). Inside the string (r <~ r_0), T^nu_mu != 0 and the metric is different from (33) or (41). If we assume that gravitation does not break the Lorentz invariance of the string in the z direction, then the only allowed values of K in Eq. (41) are K = 1 and K = -3. ... K = 1 corresponds to a conical space.' The number '8 pi G mu' is not printed by Vilenkin as a deficit; it is the arithmetic 2 pi - (1 - 4 G mu) 2 pi of his eq.(33) range (reaudit V3). Hindmarsh & Kibble (READ, hep-ph/9411342 p.53) print it: 'the angular coordinate running from 0 to 2 pi - delta, with delta = 8 pi G mu', and p.85 eq.(6.1) 'delta = 8 pi G mu'.",
 "published_hypotheses": [
  "READ (Vilenkin abstract, p.852): the LINEAR approximation of GR ('studied in the linear approximation of general relativity'); p.853: '|h_mu nu| << 1'; harmonic gauge eq.(15).",
  "READ (p.852-853): infinitely thin, static, straight string along z ('approximate them by infinitely thin surfaces and curves'; 'Consider a static string parallel to the z axis').",
  "READ (p.853 eqs.9-11): for a VACUUM string T^0_0 = T^3_3 is DERIVED from 'all the fields phi^(i) are functions only of x and y' plus conservation; it is not an extra assumption for a field-theory string, but it is specific to that source. Eq.(20) is stated for a general 'massive string' with pressure p along z, and 8 G mu (hence the 8 pi G mu deficit) is obtained only at 'p = -mu' (eq.21).",
  "READ (p.852 abstract, p.855 eq.26 context): the paper contrasts vacuum strings with 'regular massive planes and rods'; for a regular rod (p = 0) eq.(20) gives h_11 = 4 G mu ln(r/r_0), i.e. a deficit 4 pi G mu (computed, reaudit V4), not 8 pi G mu.",
  "READ (p.856): the exact exterior is conical (K = 1) only if 'gravitation does not break the Lorentz invariance of the string in the z direction'; the string interior is not solved ('Inside the string (r <~ r_0), T^nu_mu != 0 and the metric is different'). The exact interior-exterior relation between mu and the deficit is NOT derived in this paper.",
  "READ (Hindmarsh-Kibble p.53): 'It can be shown that the solution inside the string can be matched on to the asymptotic conical metric [161-163]. In the resulting metric, the angle deficit is no longer quite proportional to the mass per unit length, there being O(G^2 mu^2) corrections [164,165].' Refs [161-165] (Gott, Hiscock, Linet, Futamase-Garfinkle, Hindmarsh-Wray) NAMED-NOT-READ; which definition of mu carries the corrections is not settled here.",
  "READ (Hindmarsh-Kibble p.54, eqs.4.5-4.7): for T = diag(mu,0,0,-T) delta^2 with T the tension, 'It is conical perpendicular to the string, with angle deficit 4 pi G (mu + T), but there is also a non-zero Newtonian potential' (extractor dropped the pi and mu glyphs: printed as 'angle de cit 4G ( + T )'; restored from eq.(4.6) '[1 - 2G(mu + T)]^2 R^2 dphi^2' and checked by reaudit V4)."
 ],
 "hypothesis_drift": [
  "CONFIRMED FROM THE SOURCE (was computed only in the first audit): axial.py:130-133 'An angle DEFICIT, W'(0) < 1, is what ordinary matter makes -- that is a cosmic string, and its deficit is 8 pi G mu'. Vilenkin's eq.(20) gives the linear deficit 4 pi G (mu - p), p the axial pressure (reaudit V4, 18/18 PASS). 8 pi G mu requires p = -mu, which Vilenkin derives for the VACUUM string (eqs.9-11, 21). His 'regular massive rods' (p = 0), which is what 'ordinary matter' names, give 4 pi G mu. The owner's sentence joins 'ordinary matter' and 'cosmic string' as one thing and gives the vacuum-string coefficient to both. The coefficient is wrong for ordinary matter; the SIGN (a deficit for mu > 0) survives for any p <= mu.",
  "CONFIRMED FROM THE SOURCE: axial.py:133 'AN ANGLE EXCESS IS THE DEFICIT OF A NEGATIVE mu' is unconditional. From Vilenkin eq.(20) an excess needs mu - p < 0: mu < 0 when p <= 0 (rod or tension), but ALSO mu > 0 with p > mu (reaudit V5: mu = 0.01, p = 0.02 gives deficit -0.1257). This is the first audit's hypothesis H2, now read at eq.(20) rather than recalled; the first audit's '4 pi G (mu + tau)' is Vilenkin's 4 pi G (mu - p) with tau = -p, and Hindmarsh-Kibble p.54 prints the same form.",
  "UNCHANGED from the first audit, and not touched by the source: the tree's WITH_CONICAL_DEFECT (axial.py:182-183) drops the axis boundary term [W Psi'] at r = 0. Vilenkin eq.(20) gives h_33 = 4G(mu + p) ln r, so a thin string with p != -mu has Psi' ~ 2G(mu+p)/r and W Psi' -> 2G(mu + p) != 0 at the axis: the p > mu counterexample lies OUTSIDE the tree's class, exactly as the first audit computed (its D/E). Inside the class the first audit's C (deficit >= 8 pi G mu) stands; nothing read contradicts it.",
  "SCOPE (read): Vilenkin's 8 pi G mu is a LINEARISED result with only a weak-field matching to the exact cone (p.856 'only if K - 1 = O(G^2 mu^2)'). axial.py applies it to an exact identity. The sign statement the owner draws is linear in mu at this order, so the scope difference does not flip it; the first audit's exact 8 pi G mu for uniform boost-invariant cores (its B+/B-) is a computation with mu the proper integral of u and is not contradicted by anything read, but Hindmarsh-Kibble p.53 records O(G^2 mu^2) corrections for some definition of mu (refs NAMED-NOT-READ). Recorded, not adjudicated.",
  "DISCREPANCY IN THE CANONICAL PARAPHRASE (not the owner file), now READ: canonical.json gives W'(0) - 1 as '-8 pi G mu up to normalisation'. Vilenkin eq.(32) phi' = (1 - 4 G mu) phi gives W'(0) = 1 - 4 G mu, so W'(0) - 1 = -4 G mu (reaudit V6).",
  "WITHDRAWN from the first audit's list: none. The first audit's IMPLICIT H3 ('mu defined through a thin limit') is confirmed as the source's own framing ('approximate them by infinitely thin ... curves', eq.8 integrates T over the cross-section)."
 ],
 "data_at_publication": [
  {"quantity": "Newton's constant G and string tension G mu", "value_then": "Vilenkin p.853 eq.(12) estimates mu ~ 1e-4 g/cm (electroweak) and 1e22 g/cm (GUT) READ; not inputs of the deficit formula", "value_now": "not read this pass", "source_now": "not read", "moves_conclusion": "No. The owner's conclusion is a sign; the deficit is linear in G mu (reaudit V4, V5), so no value of G or mu can change which side of zero it is on."},
  {"quantity": "axial.py CONICAL_TERM (axial.py:213-214)", "value_then": "W'(0)-1 = -0.4, 0.0, 0.7, 2.0", "value_now": "with Vilenkin's W'(0) = 1 - 4 G mu (eq.32) these are G mu = +0.100, 0, -0.175, -0.500 for a vacuum string; for a general string W'(0) - 1 = -2G(mu - p), so the two excess rows mean mu - p = -0.35 and -1.0 (G = 1)", "source_now": "Vilenkin eq.(20),(32) READ; reaudit V4, V6", "moves_conclusion": "No, inside the tree's class (W Psi' -> 0 at the axis, i.e. p = -mu at first order). Outside it the excess rows admit mu > 0 with p > mu."}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/cosmic-string-deficit-angle-8pigmu.py",
  "outcome": "18/18 PASS (output " + D + "/cosmic-string-deficit-angle-8pigmu.out). V1: Vilenkin's eq.(14) with T^nu_mu = delta^2 diag(mu,0,0,-p) gives exactly his eq.(20): h00 = h33 = 4G(mu+p) ln r, h11 = h22 = 4G(mu-p) ln r. V2: p = -mu gives his eq.(21). V3: his (29)-(30) agree to first order in G mu; the range (1 - 4G mu) 2 pi is a deficit 8 pi G mu and his eq.(34) deflection 4 pi G mu is half of it. V4: a transverse factor (1 - A ln r) is an exact cone of deficit pi A, so the general deficit is 4 pi G (mu - p): 4 pi G mu for a regular rod, 8 pi G mu for the vacuum string, 4 pi G (mu + tau) with tension tau (= Hindmarsh-Kibble eq.4.6). V5: an excess with mu > 0 occurs only for p > mu; for p <= 0 an excess occurs iff mu < 0. V6: W'(0) - 1 = -4 G mu. V7: U = 2G(mu+p) ln r, which is 2 G mu ln r for a rod and 0 for a vacuum string. The first audit's script was re-run: 10/10 PASS.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "M. B. Hindmarsh & T. W. B. Kibble, 'Cosmic strings', hep-ph/9411342 (Rep. Prog. Phys. 58 (1995) 477)", "effect": "confirms", "what": "READ p.53: 'The string is a line source with equal tension and mass density, a result which can be derived purely from Lorentz invariance along the string'; eq.(4.3)-(4.4) and 'angular coordinate running from 0 to 2 pi - delta, with delta = 8 pi G mu'. p.54: for superconducting or wiggly strings, T = diag(mu,0,0,-T), 'angle deficit 4 pi G (mu + T), but there is also a non-zero Newtonian potential' (eq.4.6-4.7). So the 8 pi G mu is tied to mu = T, and the general-stress deficit is the one the first audit re-derived.", "read_status": "READ (alphaXiv answer_pdf_queries, pp. 16, 53, 54, 85; glyph loss noted)"},
  {"ref": "Hindmarsh & Kibble p.53 on exact matching: refs [161-165] Gott ApJ 288 422 (1985), Hiscock PRD 31 3288 (1985), Linet GRG 17 1109 (1985), Futamase & Garfinkle PRD 37 2086 (1988), Hindmarsh & Wray PLB 251 498 (1990)", "effect": "narrows", "what": "READ in the restatement only: 'the angle deficit is no longer quite proportional to the mass per unit length, there being O(G^2 mu^2) corrections'. The cited papers were not read, so which mu this refers to is OPEN; it does not reach the sign the owner uses.", "read_status": "restatement READ; primary papers NAMED-NOT-READ"},
  {"ref": "Geroch & Traschen PRD 36, 1017 (1987); Cramer et al. PRD 51, 3117 (1995)", "effect": "contested", "what": "Carried from the first audit; not read this pass.", "read_status": "NAMED-NOT-READ"}
 ],
 "lacked_data": "Now read, not recalled: nothing in Vilenkin's deficit depends on a datum (eq.20 is kinematic linear GR; eq.12's tension estimates are orders of magnitude and do not enter). M's hypothesis (a data gap) does not apply to this result. What the source shows is a HYPOTHESIS the owner drops: the coefficient 8 pi G mu belongs to the vacuum string, p = -mu, which Vilenkin derives from the field configuration (eq.9-11) and explicitly contrasts with 'regular massive ... rods'. The owner's 'ordinary matter ... that is a cosmic string ... 8 pi G mu' merges the two cases.",
 "grade": "NARROWED",
 "supersedes_grade": "NARROWED (first audit, source NAMED-NOT-READ) -> NARROWED, now on a READ source. The grade is unchanged; its basis moves from computation to the source's own eq.(20).",
 "grade_evidence": "READ, Vilenkin PRD 23 (1981) p.854 eq.(20): 'h_00 = h_33 = 4G(mu + p) ln(r/r_0), h_11 = h_22 = 4G(mu - p) ln(r/r_0). Here p is the pressure in the z direction ... For a vacuum string, p = -mu'. The 8 pi G mu deficit (the arithmetic of his p.854 'phi' changes from 0 to (1 - 4G mu) 2 pi') holds for the vacuum string only; a regular rod has 4 pi G mu, and an axial pressure p > mu gives an excess with mu > 0 (reaudit V4-V5, 18/18 PASS). axial.py:130-135 states 8 pi G mu for 'ordinary matter' and 'AN ANGLE EXCESS IS THE DEFICIT OF A NEGATIVE mu' with neither condition, so the physics sentence is true only on a smaller class than it claims. It is not WRONG where it does work: the O4 closure (AXIS_ESCAPES_THE_SIGN = False, axial.py:193) rests on the identity with the axis term W Psi' dropped, which at first order is p = -mu (Vilenkin's h_33 ~ (mu + p) ln r), and inside that class the first audit's C (deficit >= 8 pi G mu) is not contradicted by anything read. STANDS is not available because the source attaches p = -mu to the formula and the owner does not.",
 "what_would_change_the_grade": "To STANDS: axial.py:130-135 says 'vacuum (boost-invariant, T^z_z = T^t_t) string' instead of 'ordinary matter', or names W Psi' -> 0 at r = 0 as the hypothesis of the conical case; the source is already read. To WRONG for the O4 closure: an explicit static cylindrical solution inside the tree's stated class with W'(0) > 1 and INT u W dr >= 0; the tree's identity forbids it. To OPEN on the exact-regime aside only: a read of Futamase-Garfinkle 1988 showing that the proper-integral mu the tree uses carries the O(G^2 mu^2) corrections Hindmarsh-Kibble mention (this would not reach the sign).",
 "reverify_command": "python3 " + D + "/cosmic-string-deficit-angle-8pigmu.py  # expect 18/18 PASS; page images of Vilenkin eqs.(11),(20),(27)-(34): " + SRC + "/vilenkin_p2.png, vilenkin_p3.png, vilenkin_p5.png (from Drive fileId 1FCKbK8Bl_Kgs07W4-6dM4jHS7NK2VCah); sed -n 121,135p /home/user/Claude-Method-Works/research/warp-drive/axial.py",
 "report_path": D + "/cosmic-string-deficit-angle-8pigmu.json",
 "pages_read": "Vilenkin PRD 23: all six pages, 852-857 (page images of 852, 853, 854, 856 inspected directly; 855 and 857 via Drive text layer). Hindmarsh-Kibble hep-ph/9411342: pp. 1-2, 16, 28, 36, 53, 54, 63, 68, 85, 107-120 as returned by alphaXiv."
}

ef = {
 "key": "elementary-flatness-regular-axis",
 "name": "Regular-axis (elementary flatness) condition W(0) = 0, W'(0) = 1",
 "source": {
  "located": "M. Mars & J. M. M. Senovilla, 'Axial symmetry and conformal Killing vectors'. Google Drive fileId 1CFItRZZqax3vPrn6R1PM3fb4_P2MPmY1. Identity from its own pages: header 'arXiv:gr-qc/0201045v1 14 Jan 2002', title 'Axial symmetry and conformal Killing vectors', 'Marc Mars and Jose M.M. Senovilla, Departament de Fisica Fonamental, Universitat de Barcelona', dated '23 October 1992', 18 numbered pages. The file is the author preprint; its pages do NOT print the journal reference, so the identification with Class. Quantum Grav. 10 (1993) 1633 rests on title, authors and date (the first audit's ADS confirmation), not on the file. Pagination below is the preprint's.",
  "read_status": "READ",
  "via": "Google Drive read_file_content, full text (the preprint has a text layer; some formula glyphs are garbled, noted where quoted). All 18 pages read."
 },
 "published_statement": "Mars-Senovilla, verbatim (preprint pp.3, 7-9). Definition, p.3: 'A space-time, V4, has axial symmetry if there is an effective realization of the one-dimensional torus T into V4 that is an isometry and such that its set of fixed points constitutes a two-dimensional surface.' Property 3, p.7-8: 'But if we now choose the standard parametrization for the torus such that phi goes from 0 to 2 pi, then we have that d tau_2pi |_Q = Id |_Q. In consequence, and given that the realization is effective, we have a = 1 as required.' Property 5, p.8: 'At the axis of symmetry we have [grad_rho(sigma^2) grad^rho(sigma^2)] / (4 sigma^2) --> 1. This is the popular regularity condition of the axis of symmetry, which usually is assumed to assure the standard 2 pi-periodicity of phi. We will prove this result by using the projector H_ab constructed above.' (the text layer prints the fraction as 'grad_rho(~sigma2) grad 4~sigma2 rho(~sigma2) --> 1'; restored to the standard form, which reaudit M1 evaluates.) End of Sec. 2, p.8-9: 'The last expression shows that the norm ~sigma2 |x coincides, at first non-trivial order, with this distance from x to the axis of symmetry. If we now consider the orbit of the axial symmetry which passes through x we have that its length is 2 pi ~sigma2 |x, because the norm of a Killing vector field remains constant alongs its orbits. Then we have found that the length of the axial orbit is, at first relevant order, 2 pi times the distance from x to the axis of symmetry, which states what is ususally called elementary flatness.' Scope, abstract p.1: 'The results are completely general and do not depend on Einstein's equations or any particular matter content.'",
 "published_hypotheses": [
  "READ (p.3): an EFFECTIVE isometric action of the 1-torus whose fixed-point set is a 2-surface (the axis), inside a spacetime V4 that is a manifold with a metric at the axis (the proof expands sigma and H_ab in a coordinate system at axis points, p.8: 'sigma_mu(x) = (x^nu - Q^nu) grad_nu sigma_mu |_Q + o(2)').",
  "READ (p.7-8): the torus is given 'the standard parametrization ... such that phi goes from 0 to 2 pi'; with effectiveness this forces the tangent-space rotation rate a = 1.",
  "READ (p.8): the condition is proved as a PROPERTY of such a spacetime ('We will prove this result'), and named 'the popular regularity condition of the axis of symmetry'. The direction is regular axis => elementary flatness; M&S do not claim the converse.",
  "READ (abstract p.1): no field equations and no matter content are used."
 ],
 "hypothesis_drift": [
  "CONFIRMED FROM THE SOURCE (was computed only in the first audit): the 2 pi period. M&S p.7-8 obtain the condition only after choosing 'the standard parametrization for the torus such that phi goes from 0 to 2 pi', and p.8 says the condition 'usually is assumed to assure the standard 2 pi-periodicity of phi'. axial.py:33 writes 'W^2 dphi^2' and axial.py:186 'regular axis: W(0) = 0 and W'(0) = 1' with no period. Under period 2 pi k the normalised condition is k W'(0) = 1 (reaudit M2). This is a convention a reader will almost always supply, but the source states it and the tree does not.",
  "SHARPENED BY THE SOURCE: the axis end of the boundary term. axial.py:43-45 'A REGULAR AXIS gives W(0) = 0 and W'(0) = 1 ... Both boundary terms vanish' needs W Psi' -> 0 at r = 0, which elementary flatness does not control. What M&S call a regular axis is more than elementary flatness: a smooth effective torus action with a 2-surface of fixed points in a manifold. COMPUTED here (reaudit M4; this is NOT a statement in M&S): under that smoothness every axially invariant metric function, g_zz = e^{2 Psi} included, is a smooth function of r^2, so Psi' = O(r) and W Psi' -> 0. So the owner's prose ('A REGULAR AXIS gives ... Both boundary terms vanish') is RIGHT if 'regular axis' is read as M&S's regular axis. But the owner's HYPOTHESES[0] (axial.py:186), which specthm.py:606-608 carries as H_axial, reduces regularity to W(0) = 0 and W'(0) = 1, and that alone does not give the axis term: Psi = a log(r/(1+r)) keeps W'(0) = 1 with W Psi' -> a (M4). The narrowing is between the owner's prose and the owner's hypothesis tuple, and the source supplies the stronger reading.",
  "WITHDRAWN (first audit's 'WEAKENED NAME'): the first audit said the tree's label 'regular axis' claims too much because elementary flatness is necessary but not sufficient for regularity. M&S themselves name the condition 'the popular regularity condition of the axis of symmetry' (p.8) and prove it as a consequence of regularity. The tree's name follows the source's usage. The logical point (necessary, not sufficient) stands and agrees with M&S's direction of proof, but it is not a drift from the source and should not be counted as one.",
  "ORIENTATION (unchanged): Property 5 gives W'(0)^2 = 1 (reaudit M1); W'(0) = +1 follows from W > 0 off the axis."
 ],
 "data_at_publication": [
  {"quantity": "W'(0) (Lambda = 0 gauge, phi of period 2 pi)", "value_then": "1 exactly: M&S p.8 Property 5 'grad(sigma^2).grad(sigma^2)/(4 sigma^2) --> 1' READ; for sigma^2 = W^2 and g^rr = 1 this is W'(0)^2 = 1 (reaudit M1)", "value_now": "1 exactly (a geometric identity, not a measurement)", "source_now": "M&S p.7-8 READ; reaudit M1-M3", "moves_conclusion": "No. No measured datum enters; only the period convention can move it (k W'(0) = 1)."}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/elementary-flatness-regular-axis.py",
  "outcome": "15/15 PASS (output " + D + "/elementary-flatness-regular-axis.out). M1: M&S's Property 5 quantity for the owner's metric is e^{-2 Lambda} W'^2, so with Lambda = 0 it is W'(0)^2 -> 1. M2: in the local Cartesian chart of dr^2 + W1^2 r^2 dphi^2 the flow of d/dphi is a rotation at rate a = W1; d tau_2pi = Id with effectiveness forces a = 1 (W1 = 1/2 fails d tau_2pi = Id; W1 = 2 passes it but is not effective), which is M&S's 'a = 1'; with period 2 pi k the condition is k W'(0) = 1. M3: orbit length / (2 pi distance) -> W'(0); W = 0.9 r gives 0.9. M4 (computed, not in M&S): smooth invariant g_zz = f(r^2) gives Psi' = O(r) and W Psi' -> 0; Psi = 0.3 log(r/(1+r)) keeps W'(0) = 1 but W Psi' -> 0.3 and is not smooth at the axis. M5: sigma^2 = W^2 = r^2 + O(r^3) >= 0 near the axis (Property 4). The first audit's script was re-launched for its 14 checks.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "none searched this pass", "effect": "confirms", "what": "The primary source is now read and states the condition, its 2 pi normalisation and its status as a consequence of regular axial symmetry. No later-literature search was made; the first audit's WebSearch titles (arXiv 1303.1919, gr-qc/0202036) remain NAMED-NOT-READ. The effect field is set to 'confirms' only for the primary read; nothing later was consulted.", "read_status": "NOT SEARCHED"}
 ],
 "lacked_data": "M's hypothesis does not bite: M&S (READ, abstract) derive the condition without field equations or matter content, and the owner's use carries no datum. What is missing is on the tree's side: the 2 pi period (stated by M&S p.7-8, absent from axial.py:33, 186) and the axis-end condition W Psi' -> 0 (supplied by M&S's smooth-axis hypotheses, per reaudit M4, but not by the owner's HYPOTHESES[0]). Neither changes O4's sign: the conical term is period-invariant and, without the axis condition, the weighted energy goes to -inf rather than turning positive (first audit D2, E1).",
 "grade": "NARROWED",
 "supersedes_grade": "NARROWED (first audit, source NAMED-NOT-READ) -> NARROWED, now on a READ source. Unchanged grade; one of the first audit's three drifts (the 'regular axis' name) is withdrawn because the source uses the same name.",
 "grade_evidence": "READ, Mars-Senovilla (gr-qc/0201045v1) p.8: 'At the axis of symmetry we have [grad(sigma^2)]^2/(4 sigma^2) --> 1. This is the popular regularity condition of the axis of symmetry, which usually is assumed to assure the standard 2 pi-periodicity of phi', proved from 'the standard parametrization for the torus such that phi goes from 0 to 2 pi' and effectiveness (p.7-8: 'we have a = 1 as required'). For the owner's metric this is exactly W(0) = 0, W'(0) = 1 in the Lambda = 0 gauge (reaudit M1-M3, 15/15 PASS), so the owner's condition agrees with the source. The grade stays NARROWED, not STANDS, because the tree uses the condition on a larger class than the source proves it for. (i) The period 2 pi, a stated hypothesis of the source, is absent from axial.py:33 and 186. (ii) axial.py:43-45 infers from 'a regular axis' that the axis boundary term W Psi' vanishes. That holds for M&S's smooth axis (reaudit M4, my derivation, not M&S's text), but the tree's operative HYPOTHESES[0] (axial.py:186, carried into specthm H_axial at specthm.py:606-608) keeps only W(0) = 0 and W'(0) = 1, which does not imply it. Neither gap changes a downstream verdict (first audit D2, E1/E2): O4, R2 and K4 stand as far as this item goes.",
 "what_would_change_the_grade": "To STANDS: axial.HYPOTHESES[0] reads 'regular axis (smooth axial symmetry, phi of period 2 pi): W(0) = 0, W'(0) = 1, and W Psi' -> 0 at r = 0', or 'Psi' bounded at the axis'. To OPEN: a showing that the preprint differs from the CQG 10 (1993) 1633 version in Property 5 (the file does not print the journal reference). To WRONG: a counterexample to Property 5 for a smooth effective torus action; M&S prove it and reaudit M1-M2 reproduce it.",
 "reverify_command": "python3 " + D + "/elementary-flatness-regular-axis.py  # expect 15/15 PASS; source text: Drive fileId 1CFItRZZqax3vPrn6R1PM3fb4_P2MPmY1, preprint pp.3 and 7-9 (Property 3, Property 5, 'elementary flatness'); sed -n 43,45p /home/user/Claude-Method-Works/research/warp-drive/axial.py; sed -n 186,187p same file",
 "report_path": D + "/elementary-flatness-regular-axis.json",
 "pages_read": "All 18 pages of the preprint (gr-qc/0201045v1), text layer. The 1993 CQG typeset version itself was not seen."
}

for obj in (cs, ef):
    path = os.path.join(D, obj["key"].replace("/", "_").replace("#", "_") + ".json")
    with open(path, "w") as fh:
        json.dump(obj, fh, indent=1, ensure_ascii=False)
    json.load(open(path))
    print("wrote", path)
