import json, copy
R = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/reaudit/"
old = json.load(open("/home/user/Claude-Method-Works/research/warp-drive/docket67-raw/round2_collected.json"))["audits"]["klinkhamer-manton-1984"]
a = copy.deepcopy(old)
a["source"] = {
 "located": "Primary: F.R. Klinkhamer & N.S. Manton, 'A Saddle Point Solution in the Weinberg-Salam Theory', Phys. Rev. D 30 (1984) 2212 (full title as printed in Tye-Wong 1505.03690 ref [10] and Matchev-Verner 2505.05607 ref [6]). NOT OBTAINED (M could not; pre-arXiv). Per M's instruction, read through papers that cite it and restate its content, each read this stage via alphaXiv.",
 "read_status": "READ-VIA-RESTATEMENT. Which citing paper states which part: (1) the formula E_sph = (2 m_W/alpha_W) B(m_H/m_W) and the range 'from 1.56 to 2.72': Rubakov & Shaposhnikov hep-ph/9603208 eq. (2.11), printed p.7 (PDF p.8), ref [32] = KM (re-read verbatim this stage; the tree's RS96-esph capture is confirmed). (2) KM's theta_W = 0 ansatz, field equations and energy functional: Quiros hep-ph/9901312 eqs. (257)-(261), PDF p.56 (printed 55), citing ref. 47 = 'N.S. Manton, Phys. Rev. D 28 (1983) 2019; F.R. Klinkhamer and N.S. Manton, Phys. Rev. D 30 (1984) 2212'; eq. (262) E_sph = (2 m_W/alpha_W) B(lambda/g^2) with 'B(0) = 1.5 to B(inf) = 2.7', PDF p.57 (printed 56). Independently, Hindmarsh & James hep-ph/9307205 eqs. (6)-(7a),(7c), PDF pp.4-5 (printed 3-4), which states 'Klinkhamer and Manton [1] studied the sphaleron setting the Weinberg angle, Θ_W, to zero, and then for small Θ_W by performing a perturbation expansion to first order in tan Θ_W' (PDF p.2, printed 1). (3) KM's two-parameter TRIAL ansatz and KM's tabulated variational parameters: Zhang & Young hep-ph/9312345 eqs. (5a)-(5d) (PDF p.4-5) and Table I (PDF p.5), 'To estimate E_spha, let us use the Ansatz of Klinkhamer and Manton [1] ... where Ξ and Ω are determined by minimizing the energy functional for a given values of λ/g^2_W. Some of these values given in Klinkhamer and Manton [1] are listed in table I'. (4) Energy in TeV, SU(2)+Higgs setting: Trodden hep-ph/9803479 eq. (46), PDF p.20. (5) Bisphaleron onset: Spannowsky & Tamarit 1611.05466 PDF p.3; Brihaye & Kunz hep-ph/9304256 PDF p.8. KM's own page and equation numbers are unknown here.",
 "via": "mcp__alphaXiv__answer_pdf_queries on hep-ph/9603208, hep-ph/9901312, hep-ph/9307205, hep-ph/9312345, hep-ph/9803479, 1206.2942, 1611.05466, 1505.03690, hep-ph/9304256, 2505.05607; discover_papers and one WebSearch (identity/leads only, not relied on). No KM page was seen; nothing is attributed to KM that a citing paper does not state."
}
a["pages_read"] = [
 "Rubakov & Shaposhnikov hep-ph/9603208: PDF pp. 5-10 (printed 4-9; eqs. (2.1)-(2.11), footnote 5, U(1)_Y paragraph), PDF pp. 76-77 (refs [32],[49],[54],[55],[68])",
 "Quiros hep-ph/9901312: PDF pp. 53-59 (Sec. 5.2, eqs. (252)-(266)), refs 45-48 (PDF p.73)",
 "Hindmarsh & James hep-ph/9307205: PDF pp. 2-5 (Sec. 1-2, eqs. (1)-(8)), refs (PDF p.14)",
 "Zhang & Young hep-ph/9312345: PDF pp. 2-5 (Sec. 1-2, eqs. (2)-(5), Table I), footnotes and refs (PDF pp. 9-10)",
 "Trodden hep-ph/9803479: PDF pp. 9-10, 16, 19-21",
 "Morrissey & Ramsey-Musolf 1206.2942: PDF p. 9 (eq. (20)), refs p. 37",
 "Spannowsky & Tamarit 1611.05466: PDF pp. 2-3, 5-8 (Sec. III, eq. (III.21))",
 "Tye & Wong 1505.03690: PDF pp. 3-5, 9-10",
 "Brihaye & Kunz hep-ph/9304256: PDF p. 8",
 "Matchev & Verner 2505.05607: PDF pp. 1-2, 6"
]
a["published_statement"] = (
 "As restated (verbatim, alphaXiv text):\n"
 "- RS96 eq. (2.11), PDF p.8: 'By simple scaling one obtains that the static energy of the sphaleron solution in our simplified model, which is equal to the height of the barrier at zero temperature, is E_sph = (2m_W/α_W) B(m_H/m_W), (2.11) where m_H is the mass of the Higgs boson. The function B(m_H/m_W) has been evaluated numerically [32]; it varies from 1.56 to 2.72 as m_H/m_W varies from zero to infinity 5. So, the height of the barrier in the electroweak theory is of order 10 TeV.' Footnote 5: 'At very large m_H/m_W the situation is more complicated [54,55], but the estimate (2.11) remains valid.' [32] = 'F.R. Klinkhamer and N.S. Manton. Phys. Rev., D 30:2212, 1984.' This matches the tree's RS96-esph capture (massform.py:1104-1107).\n"
 "- Quiros eq. (261)-(262), PDF pp.56-57: 'E = 4πv/g ∫_0^∞ { 4 (df/dξ)^2 + 8/ξ^2 [f(1−f)]^2 + 1/2 ξ^2 (dh/dξ)^2 + [h(1−f)]^2 + 1/4 (λ/g^2) ξ^2 (h^2−1)^2 } dξ (261)'; 'It is customary to write the solution as, E_sph = (2m_W/α_W) B(λ/g^2) (262) where B is the constant which requires numerical evaluation. For the standard model with a single Higgs doublet this parameter ranges from B(0) = 1.5 to B(∞) = 2.7.' and fit '(263) B(x) = 1.58 + 0.32x − 0.05x^2 where x = m_h/m_W', valid 'for values of the Higgs mass 25 GeV ≤ m_h ≤ 250 GeV'.\n"
 "- Zhang & Young PDF p.2: 'The energy of the sphaleron in the standard model (SM), calculated first by Manton and Klinkhamer in a spontaneously broken SU(2) theory [1], then improved in [2], is given by E_spha = (2M_W/α_W) B(λ/g^2_W) ... Numerical evaluation gives 1.5 ≤ B ≤ 2.7 when the bare Higgs boson mass, m^2_H = 2λv^2, varies from zero to infinity' ([2] = Akiba-Kikuchi-Yanagida 1988; Yaffe 1989; Kunz-Brihaye 1989).\n"
 "- Trodden PDF p.20: 'the original calculation of Klinkhamer and Manton (1984) was performed in the SU(2)+Higgs theory, and identified a sphaleron with energy in the range 8TeV < E_sph < 14TeV ; (46) depending on the Higgs mass.'\n"
 "The tree (canonical): 'the sphaleron is \"the static saddle point solution to the Yang-Mills-Higgs equations\" (READ), with E_sph = (2 m_W/alpha_W) B(m_H/m_W) = (4 pi v/g) B, set by the vev' (massform.py:521-523); 'E_sph = 4.740 TeV x B, with B between 1.56 and 2.72 (READ)' (:537-538); B_KM_RANGE = (1.56, 2.72) (:1472); selftest 'implied B = 1.91 lies inside KM's range' (:5203-5204).")
a["published_hypotheses"] = [
 "READ-VIA-RESTATEMENT:",
 "H-THETA0: Hindmarsh-James PDF p.2: 'Klinkhamer and Manton [1] studied the sphaleron setting the Weinberg angle, Θ_W, to zero, and then for small Θ_W by performing a perturbation expansion to first order in tan Θ_W.' Quiros PDF p.55-56: 'The sphaleron solution has been explicitly computed in Ref. 47 for the case of zero Weinberg angle, (i.e. neglecting terms O(g')), and for an arbitrary value of sin^2θ_W in Ref. 48.' RS96 PDF p.5: 'One may regard the simplified theory as the standard model in the approximation where sin θ_W and all fermion masses are set to zero'.",
 "H-CLASS (classical static saddle): RS96 PDF p.8 'the static saddle point solution to the Yang–Mills–Higgs equations, the sphaleron'; Quiros 'a static unstable solution to the classic equations of motion 47'.",
 "H-HEDGEHOG: Quiros eqs. (257)-(259): W^a_i σ^a dx^i = −(2i/g) f(ξ) dU U^−1, Φ = (v/√2) h(ξ) U (0,1)^T, 'we have introduced the dimensionless radial distance ξ = gvr', boundary conditions 'f(0) = h(0) = 0 and f(∞) = h(∞) = 1'. Same ansatz: Hindmarsh-James eq. (6) at g' = 0; Zhang-Young eqs. (2a)-(2b) 'Using the spherical symmetric ansatz[1]'.",
 "H-POT: Zhang-Young eq. (3): potential λ(|φ|^2 − v^2/2)^2, with 'm^2_H = 2λv^2'; so lambda/g^2 = (m_H/m_W)^2/8.",
 "H-TRIAL (NEW, the load-bearing one): KM's numbers are variational, from a two-parameter trial family. Zhang-Young PDF p.4-5: 'let us use the Ansatz of Klinkhamer and Manton [1], f(ξ) = ξ^2/(Ξ(Ξ+4)) for ξ ≤ Ξ; (5.a) f(ξ) = 1 − 4/(Ξ+4) exp[½(Ξ − ξ)], for ξ ≥ Ξ; (5.b)' and 'h(ξ) = (σΩ+1)/(σΩ+2) ξ/Ω, for ξ ≤ Ω; (5.c) h(ξ) = 1 − Ω/(σΩ+2) (1/ξ) exp[σ(Ω − ξ)], for ξ ≥ Ω, (5.d) where Ξ and Ω are determined by minimizing the energy functional for a given values of λ/g^2_W. Some of these values given in Klinkhamer and Manton [1] are listed in table I', Table I rows '0 2.600 2.660' ... '∞ 0 0.728' (λ/g^2, Ω, Ξ). [Fractions de-linearised from the alphaXiv text 'ξ^2 Ξ Ξ+4' etc.; the reading is fixed by continuity of f, f', h at the joins, checked.] A trial-function minimum is an UPPER BOUND on the true minimum of the functional.",
 "H-LOWEST: Spannowsky-Tamarit PDF p.3: 'In the SM, for m_h < 12 m_W, there is a single branch ... For m_h ≥ 12 m_W, a new branch of sphalerons appears [58, 59] ... known as bisphalerons.' Brihaye-Kunz PDF p.8: the negative mode 'is unique for M_H < 12M_W [16,17], while new directions of instability develop for M_H ≥ 12M_W.'"
]
a["hypothesis_drift"] = [
 "NEW, load-bearing: DROPPED (H-TRIAL). The tree holds B_KM_RANGE = (1.56, 2.72) as READ 'B between 1.56 and 2.72' (massform.py:537-538, 1472), i.e. as the range of the sphaleron's B. Via Zhang-Young's restatement of KM's trial ansatz and Table I, these are KM's variational values: at KM's own Table I parameters the read functional (Quiros 261) gives B_trial = 2.7220 at λ/g^2 = ∞ (Ξ = 0.728) and 1.5662 at λ = 0 (Ω, Ξ = 2.600, 2.660), and re-minimising the trial family returns KM's parameters (2.612, 2.658; 0.7294). The exact minimum of the same functional is 1.5202 and 2.7061, 3.02% and 0.59% below. So '1.56 to 2.72' is an upper-bound bracket from a trial family, and its lower end is not a lower bound on the true B: true B < 1.56 for m_H/m_W < 0.079 (first audit). This RESOLVES the first audit's DISCREPANCY: neither an RS96 misquote nor a KM numerical error, but a variational estimate the tree reads as exact. Residual, recorded: the trial optimum at λ = 0 is 1.5662, which truncates (does not round) to RS96's 1.56; the 0.40% is unexplained from what was read.",
 "WEAKENED, now READ: theta_W = 0. KM set Θ_W = 0 and then went to first order in tan Θ_W (Hindmarsh-James); massform.py:521-523 and :537 apply (2 m_W/alpha_W) B with the physical m_W and g = 2 m_W/v without naming theta_W = 0; the tree holds the READ 'with U(1)' 9.0 TeV separately (:539; Tye-Wong PDF p.4: turning on U(1) 'will lower the sphaleron energy by about a percent'; RS96 PDF p.8: 'For the actual value sin^2θ_W = 0.23, the deviation of B from its SU(2) values is numerically small').",
 "DROPPED at the sites, not load-bearing: classical/static (H-CLASS). Nothing at massform.py:521-543 says tree-level classical, though the READ phrase 'static saddle point solution to the Yang-Mills-Higgs equations' (:522) carries it implicitly.",
 "DROPPED, not load-bearing: H-LOWEST. 'from zero to infinity' (:1106-1107, :1472) carries no bisphaleron caveat; RS96's own footnote 5 says the estimate 'remains valid' at very large m_H/m_W, and the onset is m_h >= 12 m_W, far above the measured 1.558.",
 "ADDED and named by the tree (unchanged): the alpha_W scheme, g = 2 m_W/v (:528), 1/29.49 vs RS96's 1/29; prefactor moves +/-1.7% over 1/29-1/30.",
 "CONFIRMED, no drift: the reduced functional the first audit RECONSTRUCTED is term-for-term Quiros eq. (261), and its Euler-Lagrange equations are Quiros eq. (260) and Hindmarsh-James eqs. (7a),(7c): 'ξ^2 d^2f/dξ^2 = 2f(1−f)(1−2f) − ξ^2/4 h^2(1−f)', 'd/dξ(ξ^2 dh/dξ) = 2h(1−f)^2 + λ/g^2 ξ^2 (h^2−1)h'. The first audit's computed B(0) = 1.5202, B(∞) = 2.7061, B(1.558) = 1.9163 therefore stand on a READ functional."
]
a["data_at_publication"] = old["data_at_publication"]
a["rederivation"] = {
 "method": "numeric (scipy quad/solve_bvp/Nelder-Mead)",
 "script_path": R + "klinkhamer-manton-1984.py",
 "outcome": "Exit 0, ALL PASS (output klinkhamer-manton-1984.out). KM trial ansatz (Zhang-Young 5a-5d) on the read functional (Quiros 261), at KM's Table I parameters: λ/g^2 = 0 -> 1.5662; 1e-3 -> 1.6060; 1e-2 -> 1.6750; 0.1 -> 1.8304; 1 -> 2.0994; 10 -> 2.4064; 100 -> 2.6068; 1000 -> 2.6849; ∞ -> 2.7220 (monotone, 1.57 to 2.72). Re-minimised trial: λ=0 at (Ω, Ξ) = (2.612, 2.658), B = 1.5662; λ=∞ at Ξ = 0.7294, B = 2.7220 -- KM's tabulated parameters are the trial optimum. Exact minimum of the same functional: B(0) = 1.5202, B(∞) = 2.7061 (solve_bvp status 0); trial excess +3.02% / +0.59% (variational bound respected). At the measured m_H/m_W = 1.558 (λ/g^2 = 0.3034): trial optimum 1.9472 vs exact 1.9163 (+1.61%); the exact value reproduces FFS 9.08/4.740 = 1.916. Quiros's fit (263) gives 1.9572 there (closer to the trial value than to the exact). Trodden's 8-14 TeV corresponds to a prefactor 5.13/5.15 TeV on (1.56, 2.72).",
 "agrees_with_source": "yes (with the restatements; KM itself not read)"
}
a["later_literature"] = [
 {"ref": "Zhang & Young hep-ph/9312345 eqs. (5a)-(5d), Table I, PDF pp.4-5", "effect": "narrows",
  "what": "Restates KM's trial ansatz and KM's variational parameters; computed here, they reproduce 2.72 and ~1.56, so the bracket is a trial-function upper bound.", "read_status": "READ"},
 {"ref": "Quiros hep-ph/9901312 eqs. (257)-(263), PDF pp.55-57", "effect": "confirms",
  "what": "KM functional and field equations at theta_W = 0; 'B(0) = 1.5 to B(∞) = 2.7' (consistent at one decimal with both 1.52/2.71 and 1.56/2.72).", "read_status": "READ"},
 {"ref": "Hindmarsh & James hep-ph/9307205 eqs. (6)-(7), PDF pp.2-5", "effect": "confirms",
  "what": "Same field equations; KM worked at Θ_W = 0 then first order in tan Θ_W.", "read_status": "READ"},
 {"ref": "Spannowsky & Tamarit 1611.05466 eq. (III.21), PDF p.8", "effect": "confirms",
  "what": "'fixing m_h = 125.09 GeV and m_W = 80.398 GeV [67] we recover in all cases the known value of the SM sphaleron barrier, E^SM_sph = 9.11 TeV'; U(1)_Y ignored as 'less than 1%'.", "read_status": "READ"},
 {"ref": "Matchev & Verner 2505.05607 eq. (47), PDF p.6", "effect": "confirms",
  "what": "'We find the sphaleron energy to be E_sph ≃ 9.08 TeV' at m_H/m_W ≃ 1.556, theta_W -> 0 -- matches the exact 1.9163 x 4.740 = 9.083 TeV.", "read_status": "READ"},
 {"ref": "Trodden hep-ph/9803479 eq. (46), PDF p.20", "effect": "confirms",
  "what": "KM in 'the SU(2)+Higgs theory', '8TeV < E_sph < 14TeV'.", "read_status": "READ"},
 {"ref": "Tye & Wong 1505.03690 eq. (1.2), PDF p.3-4 (tree-held)", "effect": "confirms",
  "what": "E_sph = 9.11 TeV; U(1) lowers it 'by about a percent'; their eq. (2.9) uses a different ('constant mass') gauge construction, not KM's equations.", "read_status": "READ"},
 {"ref": "Akiba-Kikuchi-Yanagida PRD 38 (1988) 1937; Yaffe PRD 40 (1989) 3463; Kunz-Brihaye PLB 216 (1989) 353 (Zhang-Young ref [2], 'then improved in [2]')", "effect": "narrows",
  "what": "The 'improved' (non-variational) evaluations; not read, so their B values are not quoted.", "read_status": "NAMED-NOT-READ"}
]
a["lacked_data"] = ("KM lacked m_H (absorbed by giving B as a function) and a precise m_W; they set theta_W = 0. None moves S11: the exact B at the measured mass gives 9.083 TeV, matching the READ 9.08 (FFS) and Matchev-Verner's 9.08 (READ), with <= 0.30% spread over current m_W/m_H. What the re-audit adds is not a data gap but a METHOD limit KM had in 1984: a two-parameter trial ansatz, whose optimum overestimates B by 0.6-3.0% over the range (1.6% at the measured mass). Later non-variational work (Zhang-Young's 'then improved in [2]') removes it; the tree kept the variational bracket as if exact. M's hypothesis (a lacked datum moves the result) is not borne out; a lacked computation moves the bracket's endpoints, not the conclusion.")
a["grade"] = "NARROWED"
a["supersedes_grade"] = "NARROWED (first audit, NAMED-NOT-READ; endpoint DISCREPANCY of unknown cause) -- superseded by this grade on a READ-VIA-RESTATEMENT; same grade, cause of the discrepancy now identified."
a["grade_evidence"] = ("Read via restatement (no KM page seen). The formula and the functional are confirmed by two independent citing papers (Quiros eqs. (260)-(262); Hindmarsh-James eqs. (6)-(7)), matching the first audit's reconstruction term for term, so the computed exact B(0) = 1.520, B(∞) = 2.706 and B(1.558) = 1.916 now stand on a read functional. Zhang-Young restate KM's trial ansatz and KM's Table I; evaluated here, KM's parameters are the trial optimum and give 2.7220 and 1.5662 -- i.e. RS96's 'from 1.56 to 2.72' is KM's variational bracket, an upper bound. The tree uses it as the range of B (massform.py:537-538, 1472), which is true only under that unstated hypothesis (and at the lower end only for m_H/m_W >= 0.079). Also unnamed at the sites: theta_W = 0, classical level. Nothing S11 rests on moves: S11 uses the READ 9.08 TeV, which the exact solution reproduces, and the tree's range check (1.56 < 1.91 < 2.72) stays true. Residual recorded: 1.5662 vs 1.56 (0.40%).")
a["what_would_change_the_grade"] = ("To STANDS: the tree labels B_KM_RANGE as KM's variational (trial-ansatz) bracket, or replaces it with a non-variational range (e.g. a read of AKY 1988 / Yaffe 1989 / Kunz-Brihaye 1989, or the computed 1.520-2.706), and names theta_W = 0 at :521-543. To OPEN: a read of KM shows its numbers are not from the trial family Zhang-Young restate (unlikely: the Table I parameters are reproduced as the optimum). WRONG: only an exact E_sph at the measured masses contradicting 9.08 TeV; the computation and two read papers agree with it.")
a["reverify_command"] = ("python3 " + R + "klinkhamer-manton-1984.py  # expect ALL PASS (~minutes); alphaXiv answer_pdf_queries: hep-ph/9312345 ['Ansatz of Klinkhamer and Manton, eqs (5a)-(5d)', 'Table I'], hep-ph/9901312 ['eqs (260)-(263)'], hep-ph/9307205 ['eqs (6)-(7)'], hep-ph/9603208 ['eq (2.11) and footnote 5']; sed -n '521,543p;1101,1108p;1472,1477p;5203,5204p' /home/user/Claude-Method-Works/research/warp-drive/massform.py")
a["report_path"] = R + "klinkhamer-manton-1984.json"
json.dump(a, open(R + "klinkhamer-manton-1984.json", "w"), indent=1, ensure_ascii=False)
print("ok")
