#!/usr/bin/env python3
"""sim2_passage.py -- B4d simulation, phase 2, second instrument (M-RULINGS items 168, 173, 174, 176, 177): E-PASS,
the passage through the corridor object's own horizon to the far end of our own plane, within one universe.
Computed, READ and deduced; not verified; not seated.  First headed "... not verified; not seated" (2026-10-09).

M's words (verbatim in the rulings file; quoted in SIM2-PASSAGE.md, never paraphrased as M's): 173 "Go ahead with
E-PASS next"; 172 (1) "Yes, it may" and (2) "Yes, that is coinciding"; 174 "For the math" (three times); 177 "Yes, that
is the appearance"; 170 (the clocks); 132 and 143 A (one way; what can cross); 117/120 (the NEC "appears broken, but is
not"); 155 (2) "Yes, in bits"; 139 (2) and (4); 101 (7).  176's H-PAIRING-IS-ENTANGLEMENT is the board's.

THE SETUP.  Units m = 1, e = m/ell.  Over the throat r = 2m the static bulk grown from eq. (17) on our plane is SIM2's
throat bulk (sim2_facing S6-S7; Kaus-Reall's ODEs at Q = 0, READ in the ground stage):
    ds^2 = dy^2 + alpha(y)^2 [-(x/2) dt^2 + dx^2/x^2] + 4 beta(y)^2 dOmega^2,   x = r - 2m,
alpha = beta = 1, p = q = -e at the plane y = 0, alpha -> 0 at y_s^th (a curvature singularity).  It is an exact 5D
vacuum solution in its own right (the near-horizon limit), and the owner's bulk tends to it as x -> 0 at O(x)
(sim2_facing S8, x_valid).  The README's crossing is the event P_c where the plane (y = 0) meets the object's horizon,
at advanced coordinate v_c.  Owners imported by path, never copied: sim2_facing.py (throat_bulk, throat_rhs,
kret_throat, x_valid, _ystar, wec_window, _ricci_diag, S5.k_bs, B4._eq17, B4._schwarzschild), o3_write.py (the write's
floor, t_min(3) at the example README: 2.0e5 clocks).

  X1  THE CHART (computed, sympy).  x = u^2, t = v + 2 sqrt2/u turns the throat metric into
      dy^2 + alpha^2 [-(u^2/2) dv^2 + 2 sqrt2 dv du] + 4 beta^2 dOmega^2 (AdS2's ingoing Eddington-Finkelstein form),
      regular through u = 0; u < 0 is end 2 (r = 2m + u^2 has its minimum on the throat).  In this chart the 5D vacuum
      equations depend on y only and reproduce sim2_facing's P, Q and constraint exactly.
  X2  THE HORIZON (computed).  xi = d_v has norm -alpha^2 u^2/2; g^uu = u^2/(4 alpha^2), g^yu = 0; so u = 0 is a null
      hypersurface generated by d_v at every depth, and kappa^2 = -(1/2) (nabla xi)^2 = u^2 (4 alpha'^2 + 1)/8 vanishes
      on it at every y < y_s^th: a Killing horizon, VERTICAL and DEGENERATE at every depth (Racz-Wald's constancy met
      with kappa = 0; the theorem standard-not-READ, cited through Karasik et al., READ in the ground stage).
      Control: the non-degenerate g_vv = -alpha^2 (u^2 - h^2)/2 gives kappa != 0 on its horizon u = h.
  X3  ONE WAY (deduced from the computed null directions).  The radial null directions are dv = 0 (ingoing; -d_u is
      future-directed since g(d_v, d_u) = sqrt2 alpha^2 > 0) and du/dv = u^2/(4 sqrt2) >= 0; on u < 0 the second
      reaches u = 0 only as v -> infinity.  So the horizon is crossed only from end 1 into end 2 (plane.py P1; 132).
  X4  THE SINGULAR END IS KASNER (deduced, then computed).  Near y_s the leading balance of the throat ODEs gives
      alpha ~ delta^a, beta ~ delta^b (delta = y_s - y) with a + b = 1/2, ab = -1/8: a, b = (1 +- sqrt3)/4 =
      0.6830, -0.1830; the exponents (a, a, b, b) sum to 1 and their squares to 1.  Computed by fitting at the nine
      ell.  Control: a mutated ODE (2pq -> 3pq) gives other exponents.
  X5  THE SINGULAR SURFACE IS TIMELIKE AND AT FINITE CONFORMAL DEPTH (deduced, computed).  The radial metric is
      alpha^2 (d eta^2 + g_AdS2(radius 2)), eta = int dy/alpha; since a < 1, eta_s = eta(y_s) is finite, so the
      singular surface is the boundary {eta_s} x AdS2 of a product with a line: timelike, and reachable by causal
      curves.  Control: alpha ~ delta^1 makes eta diverge logarithmically.
  X6  THE CAUSAL PAST OF THE CROSSING (deduced; checked by integrating null geodesics).  In the conformal frame
      d eta^2 + 4(-dt^2 + d zeta^2)/zeta^2 (zeta = 2 sqrt2/u, v = t - zeta), a point q = (eta, zeta_q, v_q) lies in
      J^-(P_c) iff  v_c - v_q >= zeta_q * 2 sin^2(eta/4)  (eta < 2 pi), the S2 being no help to a radial curve.  Points
      of end 2 and of the horizon at depth > 0 are never in it.  Checked: along past-directed null geodesics from P_c
      the equality holds to the integrator's tolerance; the control sin^2(eta/2) fails.
  X7  THE CONE BUDGET (deduced, computed).  A causal curve from the singular layer to P_c that stays where the throat
      geometry holds (x <= x_lim, zeta >= zeta_lim = 2 sqrt2/sqrt(x_lim)) needs an advanced-coordinate hold of at least
      zeta_lim 2 sin^2(eta/4) and at most zeta_lim eta/2 (an explicit curve at fixed zeta, then the plane's ingoing
      null leg, which costs no advanced coordinate).  For a layer of curvature F K_bs, x_lim is the least x_valid over
      the layer's depth range (O(x) kept below 0.1).  Every budget lies far below the write's floor (2.0e5 clocks,
      o3_write, kept by 163): the singular layer is in the crossing's causal past.
  X8  WITHOUT A SECOND SHEET (deduced).  So stage 6's cone premise refutes E-PASS on its own, on the conjunction:
      static bulk through the hold; eq. (17) on our plane at our tension; vacuum Lambda_5; the throat ODE and its O(x)
      correction as evidence; the hold measured in advanced coordinate (H-HOLD-IN-ADVANCED-TIME, the board's: on the
      plane's static clock the crossing lies at t = +infinity, outside every finite hold); a write of >= 2.0e5 clocks.
  X9  WITH POSITION 2'S PIECE AT DEPTH d < y_s (computed, deduced).  With P2 (H-README-ON-P2, M's 172 (1)) mirrored,
      the bulk beyond d is cut away, so J^-(P_c) near the throat holds slab points only, at eta <= eta(d) < eta_s: no
      singular layer.  P2's own points with u > 0 enter J^-(P_c) down to u_min = 4 sqrt2 sin^2(eta(d)/4)/Delta_v.  In
      the coinciding limit d -> 0 (M's 172 (2)) K -> 2(80 e^4 + 3)/(160 e^4 + 3) K_bs, the slab pinches exactly at the
      crossing, and the README's crossing event is the coincidence event: reached at finite advanced coordinate (and
      finite proper time of the README), never on any static slice (the world's clock), as EHM READ say of such
      horizons.  The board decides, under 149, that this is what 172 (2)'s "never a reached point" means
      (H-REACHED-ONLY-BY-THE-CROSSER, the board's).  At every finite ell exact coincidence costs P2 rho_m -> -2 sigma_RS
      (sim2_facing S15); held at d >= d_+ (ell > 27.07m) the slab is still regular.
  X10 E-Q, ITEM 177 (computed, deduced).  (a) The 5D bulk is vacuum with Lambda_5, so R_kk = 0 for every 5D null k:
      any negative null energy read on the plane is the projected Weyl term (Maldacena-Milekhin, READ: "a classical
      effect in five dimensions").  (b) Computed: eq. (17)'s own plane already reads negative integrated null energy
      along the ingoing radial null ray from far out to the throat (finite; Schwarzschild's is exactly zero, the
      control).  (c) The static throat bulk is fixed by the plane's data (an initial-value problem in y, Picard-
      Lindelof): a static coupling that leaves the plane's data unchanged changes nothing, and a change of the plane's
      data is a sheet or matter (computed: a perturbed p(0) moves y_s).  So E-Q, realised classically in five
      dimensions, is a change of the bulk, and the change E-PASS needs is position 2's sheet: the coupled ends are the
      slab, whose coincident pair carries zero net surface stress (sim2_facing S15), the +sigma/-sigma pairing of 176.
      (d) Maldacena-Qi's horizonless link (global AdS2, READ) would remove the degenerate horizon: a two-way passage,
      against clause (O) and 132; it needs r0 > 2m (Bronnikov-Kim's wormhole branch, READ), against clause (G).  So the
      coupling the corridor admits keeps the horizon (deduced; Gao-Jafferis-Wall's protocol NOT READ).
      (e) At coincidence P2's matter obeys the NEC only marginally (rho_m + p_m -> 0) and its energy density is
      negative: 177 speaks of negative NULL energy, so as worded it does not reach this negative density -- put to M.
  It is necessary, not sufficient, and never B4d green.  No value here is a length (155 (2): bits), a distance, a
  speed (139 (4)) or anything the device sees (101 (7)); the budgets are holds for the cone premise, as stage 5 F3's.

python3 sim2_passage.py [--selftest] [--json PATH]   (needs sympy, numpy, scipy, mpmath, python-flint; about a minute)
"""
import contextlib
import importlib.util
import io
import json
import math
import os
import sys
import time
import warnings
from fractions import Fraction as Fr

import numpy as np
import sympy as sp
from scipy.integrate import IntegrationWarning, quad, solve_ivp

HERE = os.path.dirname(os.path.abspath(__file__))
F_LAYERS = (1e2, 1e4, 1e6, 1e10)            # layers K = F K_bs
X_LIMS = (1e-2, 1e-4, 1e-6, 1e-8)          # throat-region bounds for X7's exact-throat rows
ELL_SHOW = (Fr(0), Fr(1, 8), Fr(1))        # ell = inf, 8m, m: the ground stage's three columns
GROUND_ETA = {"0": 5.726, "1/32": 5.466, "1/16": 5.242, "1/8": 4.876, "1/4": 4.344, "1/2": 3.680, "1": 2.969,
              "2": 2.302, "4": 1.733}      # the ground stage's eta_s (scratch, not board evidence): a cross-check only
ETA_ERR = [0.0]                            # the largest quadrature error estimate met in eta_of
BANNED_KEYS = ("dist", "separation", "time", "redshift", "speed", "velocity", "length", "clock", "arrival")


def _load(path, key):
    spec = importlib.util.spec_from_file_location(key, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[key] = mod
    with contextlib.redirect_stdout(io.StringIO()):
        spec.loader.exec_module(mod)
    return mod


SF = _load(os.path.join(HERE, "sim2_facing.py"), "passage_sim2facing")
OW = _load(os.path.join(HERE, "o3_write.py"), "passage_o3write")
ES2 = SF.ES2


def write_floor():
    """o3_write's least write at the example README (Z = 108.75), in clocks: the hold E-PASS's cone premise must cover."""
    return float(OW._num(OW.t_min(3)))


# ------------------------------------------------------------------------------------------------------- X1-X3 chart
def _christoffel(g, X):
    n = len(X)
    gi = g.inv()
    return gi, [[[sp.simplify(sum(gi[a, d] * (sp.diff(g[d, b], X[c]) + sp.diff(g[d, c], X[b]) - sp.diff(g[b, c], X[d]))
                                  for d in range(n)) / 2) for c in range(n)] for b in range(n)] for a in range(n)]


def _ricci(G, X):
    n = len(X)
    return lambda b, c: sp.simplify(sum(sp.diff(G[a][b][c], X[a]) - sp.diff(G[a][b][a], X[c])
                                        + sum(G[a][a][d] * G[d][b][c] - G[a][c][d] * G[d][b][a] for d in range(n))
                                        for a in range(n)))


def ef_metric(hh=0, shift=2):
    """The throat metric in the (y, v, u) chart; hh != 0 gives the non-degenerate control g_vv = -alpha^2 (u^2 - hh^2)/2."""
    y, v, u, th, ph = sp.symbols("y v u theta phi", real=True)
    al, be = sp.Function("alpha")(y), sp.Function("beta")(y)
    g = sp.zeros(5)
    g[0, 0] = 1
    g[1, 1] = -al**2 * (u**2 - hh**2) / 2
    g[1, 2] = g[2, 1] = sp.sqrt(2) * al**2
    g[3, 3] = 4 * be**2
    g[4, 4] = 4 * be**2 * sp.sin(th)**2
    return g, [y, v, u, th, ph], al, be


def chart_identity(shift=2):
    """X1: x = u^2, t = v + shift sqrt2/u in -(x/2) dt^2 + dx^2/x^2, minus the EF form; 0 at shift = 2."""
    u = sp.Symbol("u", positive=True)
    dv, du = sp.symbols("dv du")
    dt = dv - shift * sp.sqrt(2) / u**2 * du
    dx = 2 * u * du
    return sp.simplify(sp.expand(-(u**2 / 2) * dt**2 + dx**2 / u**4) - (-(u**2 / 2) * dv**2 + 2 * sp.sqrt(2) * dv * du))


def chart_equations(s2=1):
    """X1: the 5D vacuum equations R_ab + (4/ell^2) g_ab = 0 in the EF chart, reduced against sim2_facing's coded P, Q and
    constraint (s2 = -1 compares against the S2-flipped coded system: the control)."""
    g, X, al, be = ef_metric()
    e = sp.Symbol("e", nonnegative=True)
    gi, G = _christoffel(g, X)
    R = _ricci(G, X)
    E = {(i, j): sp.simplify(R(i, j) + 4 * e**2 * g[i, j]) for i in range(5) for j in range(i, 5)}
    nonzero = sorted(k for k, v in E.items() if v != 0)
    p, q, P, Q, a, b = sp.symbols("p q P Q a b")
    sub = {sp.Derivative(al, (X[0], 2)): (P + p**2) * a, sp.Derivative(be, (X[0], 2)): (Q + q**2) * b,
           sp.Derivative(al, X[0]): p * a, sp.Derivative(be, X[0]): q * b}
    Es = {k: sp.simplify(E[k].subs(sub).subs({al: a, be: b})) for k in nonzero}
    sol = sp.solve([Es[(1, 2)], Es[(3, 3)]], [P, Q], dict=True)[0]
    coded_P = 4 * e**2 - 2 * p**2 - 2 * p * q - 1 / (4 * a**2)
    coded_Q = 4 * e**2 - 2 * q**2 - 2 * p * q + s2 / (4 * b**2)
    coded_c = p**2 + q**2 + 4 * p * q - 6 * e**2 - 1 / (4 * b**2) + 1 / (4 * a**2)
    cons = sp.simplify(sp.expand(Es[(0, 0)].subs(sol)) / coded_c)
    u = X[2]
    return {"nonzero": [list(k) for k in nonzero], "P": sp.simplify(sol[P] - coded_P), "Q": sp.simplify(sol[Q] - coded_Q),
            "vv_over_vu": sp.simplify(Es[(1, 1)] / Es[(1, 2)] + u**2 / (2 * sp.sqrt(2))) if (1, 1) in Es else None,
            "uu": Es.get((2, 2), 0), "constraint_ratio": cons}


def horizon(hh=0):
    """X2: xi = d_v, its norm, g^uu, g^yu and kappa^2 = -(1/2) nabla_a xi_b nabla^a xi^b (Killing: nabla_a xi_b =
    d_[a xi_b]); evaluated on u = hh (the horizon of the metric)."""
    g, X, al, be = ef_metric(hh)
    gi = g.inv()
    xi = [g[i, 1] for i in range(5)]
    F = sp.Matrix(5, 5, lambda i, j: (sp.diff(xi[j], X[i]) - sp.diff(xi[i], X[j])) / 2)
    k2 = sp.factor(sp.simplify(-sp.Rational(1, 2) * sum(F[i, j] * sum(gi[i, k] * gi[j, l] * F[k, l] for k in range(5)
                                                                         for l in range(5))
                                                         for i in range(5) for j in range(5))))
    u = X[2]
    return {"norm": sp.factor(g[1, 1]), "g_uu_inv": sp.simplify(gi[2, 2]), "g_yu_inv": sp.simplify(gi[0, 2]),
            "kappa2": k2, "kappa2_on": sp.simplify(k2.subs(u, hh)), "norm_on": sp.simplify(g[1, 1].subs(u, hh)),
            "g_uu_inv_on": sp.simplify(gi[2, 2].subs(u, hh))}


def one_way():
    """X3: the radial null directions of -(u^2/2) dv^2 + 2 sqrt2 dv du (per alpha^2): du/dv for the non-ingoing family,
    and the sign of g(d_v, d_u)."""
    u, w = sp.symbols("u w", real=True)                                   # w = du/dv
    roots = sp.solve(sp.Eq(-(u**2 / 2) + 2 * sp.sqrt(2) * w, 0), w)
    return {"dudv": roots, "g_v_u": sp.sqrt(2)}


# -------------------------------------------------------------------------------------------------- X4-X5 the throat
_TB = {}


def tb(e):
    k = str(Fr(e))
    if k not in _TB:
        _TB[k] = SF.throat_bulk(e)
    return _TB[k]


def kasner_deduced():
    a, b = sp.symbols("a b")
    sols = sp.solve([sp.Eq(a + b, sp.Rational(1, 2)), sp.Eq(a * b, -sp.Rational(1, 8))], [a, b], dict=True)
    s = max(sols, key=lambda d: d[a])
    return {"a": s[a], "b": s[b], "sum": sp.simplify(2 * s[a] + 2 * s[b]), "squares": sp.simplify(2 * s[a]**2 + 2 * s[b]**2)}


def _zeroth(e, mutate=0.0):
    """The zeroth-order throat system to alpha = 1e-12 (X4's fit); mutate adds mutate*p*q to p' (the control)."""
    ef = float(e)

    def rhs(y, u):
        al, be, p, q = u
        return [p * al, q * be, 4 * ef * ef - 2 * p * p - (2 + mutate) * p * q - 1 / (4 * al * al),
                4 * ef * ef - 2 * q * q - 2 * p * q + 1 / (4 * be * be)]

    def end(y, u):
        return u[0] - 1e-12
    end.terminal = True
    return solve_ivp(rhs, [0, 12], [1.0, 1.0, -ef, -ef], method="DOP853", rtol=1e-13, atol=1e-16, events=[end],
                     dense_output=True, max_step=0.005)


def kasner_fit(e, mutate=0.0):
    """X4: the exponents d ln alpha / d ln delta and d ln beta / d ln delta at the end, delta = y_s - y, from -p delta and
    -q delta (p = alpha'/alpha), with y_s taken where alpha = 1e-12."""
    s = _zeroth(e, mutate)
    ys = float(s.t[-1])
    out = []
    for dl in (1e-6, 1e-7):
        u = s.sol(ys - dl)
        out.append((-float(u[2]) * dl, -float(u[3]) * dl))
    return {"y_s": ys, "a": out[-1][0], "b": out[-1][1], "drift": abs(out[0][0] - out[1][0])}


def eta_of(e, y):
    """eta(y) = int_0^y dy/alpha on the zeroth-order throat bulk; past alpha = 1e-9 the Kasner tail is added."""
    s = tb(e)
    s0, ys = s["sol0"], s["y_s"]
    yt = min(y, ys)
    f = lambda z: 1.0 / float(s0.sol(z)[0])
    pts = [0.0] + [ys * c for c in (0.5, 0.9, 0.99, 0.999, 0.9999, 0.99999) if ys * c < yt] + [yt]
    val = 0.0
    for i in range(len(pts) - 1):
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", IntegrationWarning)     # the estimate is recorded instead (ETA_ERR)
            v_, err = quad(f, pts[i], pts[i + 1], limit=800, epsabs=1e-12, epsrel=1e-11)
        ETA_ERR[0] = max(ETA_ERR[0], err)
        val += v_
    if y >= ys:                                    # tail beyond alpha = 1e-9: alpha = c delta^a over (0, delta_end)
        a = float(kasner_deduced()["a"])
        al_end = float(s0.sol(ys)[0])
        # delta_end from the local slope: alpha'/alpha = -a/delta  ->  delta = -a/p
        p_end = float(s0.sol(ys)[2])
        d_end = -a / p_end
        val += d_end / (al_end * (1 - a))
    return val


def eta_control():
    """X5's control: alpha = delta (exponent 1) at the same y_s: eta to delta diverges like -ln delta."""
    return [(dl, math.log(1.0 / dl)) for dl in (1e-2, 1e-4, 1e-6, 1e-8)]


# ---------------------------------------------------------------------------------------------- X6 the causal past
def _conformal_geodesics():
    """Christoffels of d eta^2 - 4 w^2 dv^2 + 8 dv dw (w = 1/zeta; regular through the horizon w = 0), lambdified."""
    et, v, w = sp.symbols("eta v w", real=True)
    g = sp.Matrix([[1, 0, 0], [0, -4 * w**2, 4], [0, 4, 0]])
    X = [et, v, w]
    _, G = _christoffel(g, X)
    f = sp.lambdify((et, v, w), [[[G[a][b][c] for c in range(3)] for b in range(3)] for a in range(3)], "numpy")
    return f


def jminus_check(n_rays=8, eta_to=6.0, wrong=False):
    """X6: past-directed null geodesics from P_c = (eta 0, v 0, w 0); along each, the criterion's equality
    (-v) w = 2 sin^2(eta/4) (wrong=True: 2 sin^2(eta/2), the control).  Returns the worst relative residual."""
    G = _conformal_geodesics()

    def rhs(lam, s):
        x, d = s[:3], s[3:]
        Ga = np.array(G(*x), dtype=float)
        acc = [-sum(Ga[a][b][c] * d[b] * d[c] for b in range(3) for c in range(3)) for a in range(3)]
        return list(d) + acc

    def stop(lam, s):
        return s[0] - eta_to
    stop.terminal = True
    worst = 0.0
    for k in range(n_rays):
        c1 = 0.3 + 2.7 * k / max(1, n_rays - 1)                     # d eta/d lambda
        vd = -1.0                                                     # past-directed
        wd = c1 * c1 / 8.0                                            # null at w = 0: c1^2 + 8 vd wd = 0
        sol = solve_ivp(rhs, [0, 1e4], [0.0, 0.0, 0.0, c1, vd, wd], method="DOP853", rtol=1e-12, atol=1e-14,
                        events=[stop], dense_output=True)
        for lam in np.linspace(sol.t[-1] * 0.05, sol.t[-1], 40):
            et, v, w = sol.sol(lam)[:3]
            rhs_v = 2 * math.sin(et / (2 if wrong else 4))**2
            lhs = -v * w
            worst = max(worst, abs(lhs - rhs_v) / max(rhs_v, 1e-12))
    return worst


def budget(eta, x_lim):
    """X7: the advanced-coordinate hold (clocks) a causal curve from a point at conformal depth eta, kept at x <= x_lim,
    needs to reach P_c: [lower, upper] = zeta_lim [2 sin^2(eta/4), eta/2]."""
    z = 2 * math.sqrt(2) / math.sqrt(x_lim)
    return z * 2 * math.sin(eta / 4)**2, z * eta / 2


def layer(e, F):
    """X7: the layer K_th = F K_bs: its depth, eta there, x_lim = min x_valid over [0, y_K] (O(x) <= 0.1), and its budget."""
    s = tb(e)
    yK = SF._yK(s, F)
    if yK is None:
        return None
    ys = np.linspace(1e-6, yK, 400)
    xl = min(SF.x_valid(s, z) for z in ys)
    et = eta_of(e, yK)
    lo, hi = budget(et, xl)
    return {"F": F, "y_K": yK, "eta": et, "x_lim": xl, "lower": lo, "upper": hi}


# ------------------------------------------------------------------------------------------ X9 position 2's piece
def k_ratio(e, y):
    s = tb(e)
    return SF.kret_throat(s["sol"].sol(y), float(e)) / SF.S5.k_bs(float(e), 2.0, y)


def k_ratio_zero_deduced(e):
    ef = float(e)
    return 2 * (80 * ef**4 + 3) / (160 * ef**4 + 3)


def slab_rows(e, dv):
    """X9: depths of P2 -- y*, the band's midpoint, 0.1 y_s, d_+ where it exists -- with eta(d), K/K_bs at d, and
    u_min = 4 sqrt2 sin^2(eta(d)/4)/Delta_v at Delta_v = the write's floor."""
    s = tb(e)
    yst, _ = SF._ystar(s)
    rows = {}
    cand = {"y_star": yst, "band_mid": None if yst is None else (yst + s["y_end"]) / 2, "tenth": 0.1 * s["y_s"]}
    w = SF.wec_window(s)
    if w["d_plus"]:
        cand["d_plus"] = w["d_plus"]
    for k, d in cand.items():
        if d is None:
            continue
        et = eta_of(e, d)
        rows[k] = {"depth": d, "eta": et, "eta_over_eta_s": et / eta_of(e, s["y_s"] * 1.0001),
                   "K_ratio": k_ratio(e, d), "u_min": 4 * math.sqrt(2) * math.sin(et / 4)**2 / dv}
    return rows


# ----------------------------------------------------------------------------------------------------- X10 E-Q
def plane_null_energy(data="eq17"):
    """X10 (b): on the plane's metric -F dt^2 + dr^2/H + r^2 dOmega^2, rho + p_r = (G^r_r - G^t_t)/(8 pi) and the
    integrated null energy along the ingoing radial null ray (energy 1), int (rho + p_r)/sqrt(F H) dr, from r = 2m to
    infinity.  eq17: Bronnikov-Kim's eq. (17) at r0 = 2m; schw: Schwarzschild (the control, exactly zero)."""
    r = sp.Symbol("r", positive=True)
    t, th, ph = sp.symbols("t theta phi", real=True)
    F, H = (SF.B4._eq17 if data == "eq17" else SF.B4._schwarzschild)(r)
    g = [-F, 1 / H, r**2, r**2 * sp.sin(th)**2]
    R, gi, _ = SF._ricci_diag(g, [t, r, th, ph])
    Rt, Rr = sp.simplify(gi[0] * R(0, 0)), sp.simplify(gi[1] * R(1, 1))
    Rs = sp.simplify(sum(gi[i] * R(i, i) for i in range(4)))
    nec = sp.factor(sp.simplify((Rr - Rt) / (8 * sp.pi)))               # G^r_r - G^t_t = R^r_r - R^t_t
    bk18 = -(r - 2) * (2 - sp.Rational(3, 2)) / (r**2 * (r - sp.Rational(3, 2))**2)
    integrand = sp.lambdify(r, sp.simplify(nec / sp.sqrt(F * H)), "mpmath")
    import mpmath as mp
    mp.mp.dps = 30
    val = mp.quad(integrand, [2, 2.001, 2.1, 3, 10, mp.inf]) if data == "eq17" else mp.quad(integrand, [2.5, 10, mp.inf])
    return {"R": Rs, "nec": nec, "bk18_ratio": sp.simplify(nec * 8 * sp.pi / bk18) if data == "eq17" else None,
            "anec": float(val)}


def data_fixes_bulk(dp=1e-3):
    """X10 (c): the throat bulk is the solution of an initial-value problem in y from the plane's data; a change of
    p(0) (matter on the plane) moves y_s.  Returns y_s at the vacuum data and at p(0) = -e +- dp, ell = 8m."""
    ef = 1 / 8

    def run(p0):
        def rhs(y, u):
            al, be, p, q = u
            return [p * al, q * be, 4 * ef * ef - 2 * p * p - 2 * p * q - 1 / (4 * al * al),
                    4 * ef * ef - 2 * q * q - 2 * p * q + 1 / (4 * be * be)]

        def end(y, u):
            return u[0] - 1e-9
        end.terminal = True
        return float(solve_ivp(rhs, [0, 12], [1.0, 1.0, p0, -ef], method="DOP853", rtol=1e-12, atol=1e-15,
                               events=[end], max_step=0.005).t[-1])
    return {"vacuum": run(-ef), "minus": run(-ef - dp), "plus": run(-ef + dp)}


# ------------------------------------------------------------------------------------------------------- compute
def compute():
    t0 = time.time()
    dv = write_floor()
    out = {"write_floor": dv}
    out["chart"] = {"identity": str(chart_identity()), "identity_control": str(chart_identity(shift=1))}
    ce = chart_equations()
    out["chart"]["equations"] = {k: str(v) for k, v in ce.items()}
    out["chart"]["equations_control_Q"] = str(chart_equations(s2=-1)["Q"])
    hz, hc = horizon(), horizon(hh=sp.Rational(1, 3))
    out["horizon"] = {k: str(v) for k, v in hz.items()}
    out["horizon_control_kappa2_on"] = str(hc["kappa2_on"])
    out["one_way"] = {k: str(v) for k, v in one_way().items()}
    kd = kasner_deduced()
    out["kasner"] = {"deduced": {k: str(v) for k, v in kd.items()}, "a_num": float(kd["a"]), "b_num": float(kd["b"]),
                     "fits": {str(e): kasner_fit(e) for e in ES2}, "control": kasner_fit(Fr(1, 8), mutate=1.0)}
    out["eta_s"] = {str(e): eta_of(e, tb(e)["y_s"] * 1.0001) for e in ES2}
    out["eta_control"] = eta_control()
    out["eta_quad_err"] = ETA_ERR[0]
    out["jminus"] = {"worst": jminus_check(), "control": jminus_check(n_rays=4, wrong=True)}
    rows = {}
    for e in ES2:
        es = out["eta_s"][str(e)]
        rows[str(e)] = {"exact_throat": {str(x): budget(es, x) for x in X_LIMS},
                        "layers": [layer(e, F) for F in F_LAYERS]}
    out["budgets"] = rows
    out["slab"] = {str(e): slab_rows(e, dv) for e in ES2}
    out["coincide_K"] = {str(e): {"computed": k_ratio(e, 0.0), "deduced": k_ratio_zero_deduced(e)} for e in ES2}
    out["eq"] = {"eq17": {k: str(v) if k != "anec" else v for k, v in plane_null_energy("eq17").items()},
                 "schw": {k: str(v) if k != "anec" else v for k, v in plane_null_energy("schw").items()},
                 "data": data_fixes_bulk()}
    out["seconds"] = time.time() - t0
    return out


def _keys(o, path=""):
    if isinstance(o, dict):
        for k, v in o.items():
            yield str(k)
            yield from _keys(v)
    elif isinstance(o, (list, tuple)):
        for v in o:
            yield from _keys(v)


def address_guard(out):
    """No key of the output names a length, distance, time, speed, redshift, clock or arrival (155 (2), 139 (4), 101 (7));
    write_floor and the budgets are holds for the cone premise."""
    bad = [k for k in _keys(out) if any(b in k.lower() for b in BANNED_KEYS)]
    return bad


def _ell(k):
    e = Fr(k)
    return "inf" if e == 0 else (f"{1/e}m" if (1 / e).denominator == 1 else f"{float(1/e)}m")


def report(out):
    P = print
    P("sim2_passage.py -- E-PASS, the passage through the corridor object's own horizon (not verified; not seated)")
    P(f"write floor (o3_write, example README): {out['write_floor']:.4g} clocks")
    P("X1 chart identity:", out["chart"]["identity"], "| control (shift 1):", out["chart"]["identity_control"][:40], "...")
    P("X1 EF vacuum equations vs coded: P", out["chart"]["equations"]["P"], "Q", out["chart"]["equations"]["Q"],
      "constraint ratio", out["chart"]["equations"]["constraint_ratio"], "| control Q (S2 flipped):",
      out["chart"]["equations_control_Q"])
    h = out["horizon"]
    P("X2 horizon: xi^2 =", h["norm"], " g^uu =", h["g_uu_inv"], " g^yu =", h["g_yu_inv"], " kappa^2 =", h["kappa2"],
      " on u=0:", h["kappa2_on"], "| control (u^2 - 1/9) on its horizon:", out["horizon_control_kappa2_on"])
    P("X3 null directions: du/dv =", out["one_way"]["dudv"], "(and dv = 0); g(d_v, d_u) =", out["one_way"]["g_v_u"])
    k = out["kasner"]
    P(f"X4 Kasner deduced a = {k['deduced']['a']} = {k['a_num']:.6f}, b = {k['b_num']:.6f}; 2a+2b = "
      f"{k['deduced']['sum']}, 2a^2+2b^2 = {k['deduced']['squares']}")
    for e, f in k["fits"].items():
        P(f"    ell = {_ell(e):>6}: a = {f['a']:.6f}, b = {f['b']:.6f}")
    P(f"    control (2pq -> 3pq): a = {k['control']['a']:.4f}, b = {k['control']['b']:.4f}")
    P("X5 eta_s (conformal depth of the singular surface; ground stage's value in brackets):")
    for e, v in out["eta_s"].items():
        P(f"    ell = {_ell(e):>6}: eta_s = {v:.4f} [{GROUND_ETA[e]}]  eta_s/pi = {v/math.pi:.3f}")
    P(f"    largest quadrature error estimate in eta: {out['eta_quad_err']:.1e}")
    P("    control alpha ~ delta: eta grows as ln(1/delta):", [round(v, 1) for _, v in out["eta_control"]])
    P(f"X6 J^-(P_c) criterion along null geodesics: worst relative residual {out['jminus']['worst']:.2e}; "
      f"control sin^2(eta/2): {out['jminus']['control']:.2e}")
    P("X7 cone budgets [lower, upper], clocks (advanced coordinate):")
    for e in ELL_SHOW:
        r = out["budgets"][str(e)]
        P(f"  ell = {_ell(str(e))}:")
        for x, (lo, hi) in r["exact_throat"].items():
            P(f"    singular surface, exact throat, x_lim = {x}: [{lo:.4g}, {hi:.4g}]")
        for L in r["layers"]:
            if L:
                P(f"    layer K = {L['F']:.0e} K_bs at y = {L['y_K']:.4f}m: x_lim {L['x_lim']:.2e}, eta {L['eta']:.3f}, "
                  f"[{L['lower']:.4g}, {L['upper']:.4g}]")
    mx = max(L["upper"] for r in out["budgets"].values() for L in r["layers"] if L)
    P(f"    largest layer budget over all nine ell and layers: {mx:.4g} clocks, against the write's "
      f"{out['write_floor']:.4g}")
    P("X9 position 2's piece at depth d (eta(d)/eta_s; K/K_bs; u_min at the write's floor):")
    for e in ELL_SHOW + (Fr(1, 32),):
        for k2, v in out["slab"][str(e)].items():
            P(f"    ell = {_ell(str(e)):>6} {k2:>8}: d = {v['depth']:.4f}m, eta = {v['eta']:.4f} "
              f"({v['eta_over_eta_s']:.3f}), K/K_bs = {v['K_ratio']:.4g}, u_min = {v['u_min']:.2e}")
    P("    coinciding limit d -> 0, K/K_bs computed vs 2(80e^4+3)/(160e^4+3):",
      [(_ell(e), round(v["computed"], 6), round(v["deduced"], 6)) for e, v in out["coincide_K"].items()])
    q = out["eq"]
    P("X10 (a) 5D vacuum: R_kk = 0 for every null k (Lambda_5 g_kk = 0)")
    P(f"X10 (b) eq. (17) on the plane: R = {q['eq17']['R']}; rho + p_r = {q['eq17']['nec']} (ratio to BK eq. (18) x "
      f"1/(8 pi): {q['eq17']['bk18_ratio']}); integrated null energy along the ingoing ray {q['eq17']['anec']:.6f}; "
      f"Schwarzschild control {q['schw']['anec']:.1e}")
    d = q["data"]
    P(f"X10 (c) y_s at ell = 8m: vacuum data {d['vacuum']:.6f}; p(0) -+ 1e-3: {d['minus']:.6f}, {d['plus']:.6f}")
    P(f"(computed in {out['seconds']:.1f} s)")


# ------------------------------------------------------------------------------------------------------ selftest
def selftest():
    res = []

    def ok(name, cond, note=""):
        res.append((name, bool(cond)))
        print(f"  {'PASS' if cond else 'FAIL'}  {name}  {note}")

    out = compute()
    c = out["chart"]
    ok("C1 chart identity; control shift 1 non-zero", c["identity"] == "0" and c["identity_control"] != "0")
    eq = c["equations"]
    ok("C2 EF equations = coded P, Q, constraint; uu = 0; control (S2 flipped) differs",
       eq["P"] == "0" and eq["Q"] == "0" and sp.sympify(eq["constraint_ratio"]).is_number
       and sp.sympify(eq["constraint_ratio"]) != 0 and eq["uu"] == "0"
       and eq["vv_over_vu"] == "0" and c["equations_control_Q"] != "0")
    h = out["horizon"]
    ok("C3 horizon at u = 0 null, kappa = 0 at every depth; control kappa != 0",
       h["kappa2_on"] == "0" and h["norm_on"] == "0" and h["g_uu_inv_on"] == "0" and h["g_yu_inv"] == "0"
       and out["horizon_control_kappa2_on"] != "0")
    ow = one_way()
    uu = sp.Symbol("u", real=True)
    ok("C4 one way: du/dv = u^2/(4 sqrt2) >= 0, g(d_v,d_u) > 0",
       len(ow["dudv"]) == 1 and sp.simplify(ow["dudv"][0] - uu**2 / (4 * sp.sqrt(2))) == 0 and float(ow["g_v_u"]) > 0)
    k = out["kasner"]
    good = all(abs(f["a"] - k["a_num"]) < 2e-4 and abs(f["b"] - k["b_num"]) < 2e-4 for f in k["fits"].values())
    ok("C5 Kasner exponents at nine ell; sums 1; control differs",
       good and k["deduced"]["sum"] == "1" and k["deduced"]["squares"] == "1"
       and abs(k["control"]["a"] - k["a_num"]) > 1e-2)
    ge = all(abs(out["eta_s"][e] - GROUND_ETA[e]) < 5e-3 for e in GROUND_ETA)
    mono = all(out["eta_s"][str(ES2[i])] > out["eta_s"][str(ES2[i + 1])] for i in range(len(ES2) - 1))
    ok("C6 eta_s finite, below 2 pi, falls with 1/ell, matches the ground stage to 5e-3; control diverges",
       ge and mono and all(v < 2 * math.pi for v in out["eta_s"].values())
       and out["eta_control"][-1][1] > 3 * out["eta_control"][0][1] and out["eta_quad_err"] < 1e-4)
    ok("C7 J^- criterion holds along null geodesics; control fails",
       out["jminus"]["worst"] < 1e-6 and out["jminus"]["control"] > 1e-2)
    wf = out["write_floor"]
    allb = [L for r in out["budgets"].values() for L in r["layers"] if L]
    ok("C8 budgets: lower <= upper; every layer and exact-throat row (x_lim >= 1e-8) below the write's floor",
       all(L["lower"] <= L["upper"] < wf for L in allb)
       and all(lo <= hi < wf for r in out["budgets"].values() for lo, hi in r["exact_throat"].values())
       and 1.9e5 < wf < 2.1e5)
    sc = out["budgets"]["0"]["exact_throat"]
    ok("C9 exact-throat budget scales as x_lim^(-1/2)", abs(sc["1e-08"][1] / sc["0.01"][1] - 1e3) < 1e-6)
    ck = out["coincide_K"]
    ok("C10 coinciding limit K/K_bs = 2(80e^4+3)/(160e^4+3) at nine ell",
       all(abs(v["computed"] - v["deduced"]) < 1e-9 for v in ck.values()))
    sl = [v for r in out["slab"].values() for v in r.values()]
    ok("C11 every P2 depth tried leaves the slab short of the singular surface (eta(d) < eta_s)",
       len(sl) >= 20 and all(v["eta_over_eta_s"] < 1 for v in sl))
    q = out["eq"]
    ok("C12 eq. (17)'s plane: R = 0, rho + p_r = BK (18)/(8 pi), integrated null energy < 0 and finite; Schwarzschild 0",
       q["eq17"]["R"] == "0" and q["eq17"]["bk18_ratio"] == "1" and -10 < q["eq17"]["anec"] < 0
       and abs(q["schw"]["anec"]) < 1e-20)
    d = q["data"]
    ok("C13 the plane's data fix the throat bulk: p(0) moved, y_s moves both ways",
       d["minus"] < d["vacuum"] < d["plus"] or d["plus"] < d["vacuum"] < d["minus"])
    ok("C14 address guard: no key names a length, distance, time, speed, clock or arrival", not address_guard(out),
       str(address_guard(out)))
    n = sum(r for _, r in res)
    print(f"selftest {n}/{len(res)}")
    return n == len(res)


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(0 if selftest() else 1)
    o = compute()
    report(o)
    if "--json" in sys.argv:
        with open(sys.argv[sys.argv.index("--json") + 1], "w") as fh:
            json.dump(o, fh, indent=1, default=str)
