import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
r = {
"key": "1808.08677",
"name": "chiQCD lattice proton mass decomposition (Yang, Liang, Bi, Chen, Draper, Liu, Liu, arXiv:1808.08677, PRL 121, 212001 (2018)): u,d,s scalar condensates 9(2)(1)% and a quarter of the trace anomaly 23(1)(1)% of the proton mass",
"source": {
 "located": "Y.-B. Yang, J. Liang, Y.-J. Bi, Y. Chen, T. Draper, K.-F. Liu, Z. Liu, 'Proton Mass Decomposition from the QCD Energy Momentum Tensor', arXiv:1808.08677 (MSUHEP-18-017), Phys. Rev. Lett. 121, 212001 (2018), doi:10.1103/PhysRevLett.121.212001 -- located by WebSearch (arxiv.org/pdf/1808.08677, journals.aps.org, osti.gov 1482763, PubMed 30517795).",
 "read_status": "NAMED-NOT-READ",
 "via": "NOT READ this pass. alphaXiv get_paper_content and answer_pdf_queries (x2) and discover_papers all returned 'alphaXiv assistant quota exceeded'. arxiv.org, export.arxiv.org, inspirehep.net, api.semanticscholar.org, osti.gov, pubmed.ncbi.nlm.nih.gov, pith.science, r.jina.ai were refused by the egress policy (403 connect_rejected, recorded in the agent-proxy status); per the proxy README these are policy denials and were not routed around. The only text obtained is a WebSearch index summary, which restates the abstract sentence 'A quarter of the trace anomaly gives a 23(1)(1)% contribution to the proton mass based on the sum rule, given 9(2)(1)% contribution from the u, d, and s quark scalar condensates' (verbatim identical to the tree's held quote at massform.py:1381-1383) and 'quark energy and glue field energy contribute 33(4)(4)% and 37(5)(4)% ... in the MS-bar scheme at mu = 2 GeV'. A search-engine summary is a restatement by no arXiv paper and is NOT counted as a read; it corroborates, it does not verify. No text of p.5, the ensembles, or the sigma-term inputs was obtained."
},
"published_statement": "NOT READ AT SOURCE this pass. As held by the tree (massform.py:1378-1383, status READ there, claiming arXiv:1808.08677v2 abstract p.1 and p.5): 'A quarter of the trace anomaly gives a 23(1)(1)% contribution to the proton mass based on the sum rule, given 9(2)(1)% contribution from the u, d, and s quark scalar condensates.' The same sentence, and quark energy 33(4)(4)% / glue energy 37(5)(4)% in MS-bar at mu = 2 GeV, appear in the WebSearch index restatement of the abstract. The tree records that p.5 prints 32 % / 36 % for quark / glue energy against the abstract's 33 % / 37 % (massform.py:905, :1379-1380) -- unverifiable here.",
"published_hypotheses": [
 "Target is the PROTON (held quote: 'contribution to the proton mass').",
 "Lattice QCD with the chiQCD setup (overlap valence fermions, per the WebSearch summary 'lattice QCD calculations with overlap valence fermions'); ensembles, pion masses, lattice spacings, volumes and the continuum/chiral extrapolation NOT READ here.",
 "Quark and glue energies are scheme- and scale-dependent and are quoted in MS-bar at mu = 2 GeV (abstract, via search restatement).",
 "The 23 % is obtained 'based on the sum rule, given' the 9 % condensate (held quote) -- i.e. it is inferred from the trace sum rule, not an independent measurement of the anomaly matrix element; the exact form of the sum rule (anomalous-dimension terms) NOT READ here.",
 "Errors quoted as (statistical)(systematic): 9(2)(1)%, 23(1)(1)%, 33(4)(4)%, 37(5)(4)% -- the reading of the two brackets as stat/sys is the conventional one, NOT READ here."
],
"hypothesis_drift": [
 "ADDED (proton -> nucleons): massform.py:1854-1855 applies CHIQCD_QUARK_CONDENSATE/100 to the total nucleon mass 'nuc' (protons and neutrons) while labelling the row 'lattice, proton'; the canonical entry names this hypothesis ('proton value applied to nucleons'). The source value is for the proton only. The mass-normalisation part of the drift is computed negligible: m_p = 938.272089 vs M_N_MEV = 938.918756 MeV (tree's PDG 2026 capture), 0.069 %, i.e. 0.06 MeV at 9 %. The isospin difference of the condensate matrix elements themselves is NOT computed and NOT read here (the tree names the hypothesis; it is not silent).",
 "DROPPED (scheme and scale): massform.py:360-362 names chiQCD's 'quark energy, glue energy' as READ without the MS-bar, mu = 2 GeV qualifier the abstract carries. No number from those two terms is used in the tree (only the 9 % and 23 % are pinned, massform.py:1434, :1464-1465), so nothing turns on it; the 9 % and 23 % terms are the ones not tied to a scheme in the abstract.",
 "DROPPED (uncertainties): massform.py:1464 and :1855 carry the central 9.0 only, dropping (2)(1). This is the file's declared policy for C2 ('It is a largest central value, not a bound: uncertainties are dropped', massform.py:369-371), so it is disclosed, not silent.",
 "NOT DRIFT, recorded: massform.py:338 sets the chiQCD 9 % beside the FLAG sigma-term fractions as a measure of the quark-mass (first-order, H-LINEAR) part of the nucleon mass. The identification of the condensate share <m psibar psi> with the sigma-term/Feynman-Hellmann response is the tree's (named under H-LINEAR at massform.py:325-328) and is consistent with the source's wording 'u, d, and s quark scalar condensates'; the source's own identification was NOT READ here.",
 "STATUS DRIFT RISK, recorded: the tree marks chiQCD READ at v2 abstract p.1 and p.5 (massform.py:1378-1380). This pass could corroborate the abstract sentence only through a search-index restatement and could not see p.5; the tree's p.5 reading (32 %/36 %) is neither confirmed nor contradicted here."
],
"data_at_publication": [
 {"quantity": "u,d,s scalar-condensate share of the proton mass (the value the tree uses)", "value_then": "9(2)(1) % (held quote, abstract)", "value_now": "no later value READ this pass; chiQCD's own inputs (sigma_piN, sigma_s used by the paper) NOT READ. Tree-held comparators, READ in massform from FLAG 2024 (arXiv:2411.04268v3): (sigma_piN+sigma_s)/m_N = 9.28 % (N_f=2+1: 42.2+44.9 MeV) and 10.85 % (N_f=2+1+1: 60.9+41.0 MeV); Roy-Steiner 59.1 MeV (Hoferichter et al., READ in massform) with FLAG 2+1+1 sigma_s gives 10.66 %.", "source_now": "FLAG 2024 and Hoferichter et al. as held READ in research/warp-drive/massform.py:1314-1356 (not re-read this pass); computed in rederive/1808.08677.py (D).", "moves_conclusion": "No for the tree. The 9 % sits within 0.13 of its combined error of FLAG 2+1 and 0.83 of its combined error below FLAG 2+1+1; the sigma-term tension (FLAG's 2.7 sigma between averages, held in the tree) is the live contested datum, and it moves the condensate share by at most ~1.9 points. The tree's C2 takes the LARGEST READ central row, which is Ji's 17.04 %; chiQCD's row would have to exceed 17.04 % (3.6 of its combined error above 9 %) to move C2 (rederive E1)."},
 {"quantity": "quarter of the trace anomaly (derived from the sum rule given the condensate)", "value_then": "23(1)(1) %", "value_now": "under the NAMED hypothesis H-TRACE-SR (M = <H_m> + <H_a>, quarter anomaly = (M - <H_m>)/4; form NOT READ from the source): 22.75 % from 9 %; 22.68 % (FLAG 2+1), 22.29 % (FLAG 2+1+1), 22.33 % (Roy-Steiner) from the tree-held sigma terms", "source_now": "computed, rederive/1808.08677.py (B, D)", "moves_conclusion": "No: the largest shift is 0.42 points, inside the printed (1)(1). The value is not used numerically in the tree (CHIQCD_QUARTER_ANOMALY is defined at massform.py:1465 and pinned at :1434, but no row consumes it)."},
 {"quantity": "proton / nucleon mass (normaliser)", "value_then": "not read (the paper's normaliser was not seen)", "value_now": "m_p = 938.272089 MeV, m_n = 939.565422 MeV, M_N = 938.918756 MeV (PDG 2026 capture in research/warp-drive/captures/PDG-2026.tsv via massform.MASS_MEV)", "source_now": "PDG, Takahashi et al., IJMPA 41, 2630011 (2026), tree capture", "moves_conclusion": "No: proton vs nucleon normalisation differs by 0.069 %."},
 {"quantity": "quark energy / glue energy shares (READ in the tree, not used numerically)", "value_then": "abstract 33(4)(4) % / 37(5)(4) % (search restatement); p.5 32 % / 36 % per the tree's note", "value_now": "no later value READ", "source_now": "-", "moves_conclusion": "No: nothing in the tree consumes them. Additivity computed: abstract components sum to 102 %, the tree's p.5 reading to 100 %; the 2-point excess is inside the quadrature of the printed errors (8.9) -- a rounding discrepancy between two printings, not a contradiction."}
],
"rederivation": {
 "method": "by-hand-checked-numerically",
 "script_path": D + "/rederive/1808.08677.py",
 "outcome": "OVERALL PASS (output in rederive/1808.08677.out). (A) the tree's held quote contains '9(2)(1)%' and '23(1)(1)%' and names the proton; CHIQCD_QUARK_CONDENSATE = 9.0 and CHIQCD_QUARTER_ANOMALY = 23.0 match it. (B) under the NAMED, not-read hypothesis H-TRACE-SR the quarter anomaly is (100-9)/4 = 91/4 = 22.75 % -> 23 % at printed precision, with propagated errors (0.50)(0.25) no larger than the printed (1)(1): the two abstract numbers are mutually consistent. (C) the four components sum to 102 % (abstract) vs 100 % (tree's p.5 reading): the tree's recorded divergence is arithmetically a rounding difference, and the p.5 figures are the ones that close. (D) the condensate share from the tree's own READ sigma terms is 9.28 % / 10.85 % / 10.66 %, the implied quarter anomaly 22.3-22.7 %. (E) chiQCD is not the largest READ row (Ji m_s->0, 17.04 %, is), so C2 is independent of this entry. What is NOT checked: the lattice computation itself (not reproducible here), and whether the source's values are as the tree holds them beyond the abstract sentence's search-index restatement.",
 "agrees_with_source": "partly"
},
"later_literature": [
 {"ref": "B. Wang, F. He, G. Wang, T. Draper, J. Liang, K.-F. Liu, Y.-B. Yang, 'Trace anomaly form factors from lattice QCD', Phys. Rev. D (2024) (osti.gov 2349181; arXiv id not obtained)", "effect": "extends", "what": "Same collaboration computes the trace-anomaly form factors (the forward value is what 1808.08677 infers from the sum rule). Named by WebSearch only; its numbers and any comparison with the 2018 value NOT READ.", "read_status": "NAMED-NOT-READ (alphaXiv quota exhausted; osti.gov and arxiv.org egress-blocked)"},
 {"ref": "arXiv:2411.18402, 'Unveiling the Strong Interaction origin of Baryon Masses with Lattice QCD'", "effect": "extends", "what": "Search-index summary: 'the gluon trace anomaly contributes a nearly constant 0.8-1.2 GeV to every baryon' -- a direct lattice calculation of the anomaly term rather than the sum-rule inference 1808.08677 used. Whether its proton number agrees with 23(1)(1) % NOT READ.", "read_status": "NAMED-NOT-READ (search snippet only)"},
 {"ref": "arXiv:2601.13070, 'Lattice-QCD validation of hadron mass and trace-anomaly decomposition sum rules' (PRL accepted, doi 10.1103/5n46-717z)", "effect": "extends", "what": "Search-index summary: all tensor components of the quark and gluon EMT computed with non-perturbative gradient-flow renormalisation, testing the sum rules that 1808.08677 relied on. Results NOT READ.", "read_status": "NAMED-NOT-READ (search snippet only)"},
 {"ref": "arXiv:2607.07969, 'Experimental Access to the Gluonic Origin of the Proton Mass'", "effect": "confirms", "what": "Search-index summary: 'At the scale mu^2 = 4 GeV^2, the QCD trace anomaly contributes 22.5% to the proton mass, consistent with lattice QCD findings.' Which quantity (full vs quarter anomaly, which normalisation) and which lattice finding NOT READ; the effect word is the snippet's, not verified.", "read_status": "NAMED-NOT-READ (search snippet only; not evidence)"},
 {"ref": "K.-F. Liu, 'Proton mass decomposition: naturalness and interpretations', arXiv:2102.07830, Front. Phys. (2021)", "effect": "extends", "what": "Review by a co-author discussing interpretation of the decomposition. NOT READ.", "read_status": "NAMED-NOT-READ"},
 {"ref": "FLAG Review 2024, arXiv:2411.04268v3 (as held READ in massform.py:1314-1320)", "effect": "contested", "what": "The sigma-term inputs to any condensate share are themselves contested: FLAG's N_f=2+1 and 2+1+1 averages differ by 2.7 sigma (tree-held READ). The chiQCD 9 % sits with the 2+1 average (9.28 %) and 1.85 points below the 2+1+1 one (10.85 %).", "read_status": "READ by the tree (massform.py), not re-read this pass"}
],
"lacked_data": "M's hypothesis tested for this result, as far as is possible without reading it. What the authors had in 2018: their own lattice ensembles and a trace sum rule from which the anomaly term was INFERRED from the condensate, not measured directly (held quote: 'based on the sum rule, given 9(2)(1)% ...'). What came later (named, NOT READ): direct lattice computations of the anomaly term and its form factors (Wang et al. 2024; arXiv:2411.18402) and a gradient-flow validation of the sum rules (arXiv:2601.13070); and the continuing sigma-term tension (FLAG 2024, 2.7 sigma, held READ in the tree). Evidence either way: (i) the one later datum the tree holds, the sigma terms, moves the condensate share between 9.28 % and 10.85 % and the sum-rule quarter anomaly by at most 0.42 points -- inside the printed errors (computed); (ii) the only later number seen, a search snippet's 22.5 %, is consistent with 23(1)(1) %, but it was not read and is not counted. (iii) For the tree the question is moot: the chiQCD row is not the largest READ reading and C2 does not move unless it rises above 17.04 %. Conclusion: no evidence here that the authors lacked data that changes their conclusion, and no evidence that they did not; the later direct computations that would test it were not readable. Nothing is presumed.",
"grade": "OPEN",
"grade_evidence": "OPEN because the source was not readable here: alphaXiv (all three tools) returned quota-exceeded, and every other host carrying the paper or its abstract was refused by the egress policy (arxiv.org, export.arxiv.org, inspirehep.net, osti.gov, pubmed, semanticscholar); the statement is corroborated only by a search-index restatement of the abstract, which is not a READ. What WAS checked is all consistent with the tree: the held quote parses to the values used (A1-A4); the 23 % follows from the 9 % under the named trace sum rule, 91/4 = 22.75 % (B1-B2); the abstract/p.5 difference the tree records is a 2-point rounding excess inside the errors (C1-C2) -- a discrepancy, not an error; the tree-held sigma terms move the condensate share by <= 1.9 points and the anomaly by <= 0.42 (D1-D2); and the row cannot move C2 (E1). Hypothesis drift: proton -> nucleons is ADDED but named in the tree and computed negligible in normalisation (0.069 %); the scheme qualifier on quark/glue energy is dropped for numbers the tree never uses. Not STANDS (the source was not read and its lattice computation is not checkable here); not NARROWED on evidence (the only added hypothesis is named by the tree and its measurable part is negligible, its isospin part unmeasured); not WRONG (nothing refutes it); not DATA-DEPENDENT for the tree's conclusion (the contested sigma-term datum does not move C2).",
"what_would_change_the_grade": "Reading arXiv:1808.08677v2 at source (abstract, p.5 and the methods): confirming the 9(2)(1)% and 23(1)(1)% as held, the proton-only scope, the sum-rule form, and the sigma-term / condensate inputs (to settle whether the 9 % rests on a sigma_piN on the low side of the FLAG tension). If they read as held, the grade would be STANDS for the tree's use (with the proton->nucleon hypothesis named) -- or NARROWED if a proton/neutron difference in the condensate is printed and is not negligible. Reading the later direct anomaly computations (Wang et al. 2024; arXiv:2411.18402; arXiv:2601.13070) could move it to DATA-DEPENDENT only if they put the proton's quarter anomaly or condensate share outside 23(1)(1)% / 9(2)(1)% by more than the errors -- and even then C2 would not move unless the condensate share exceeded 17.04 %.",
"reverify_command": "python3 " + D + "/rederive/1808.08677.py  # then read the source: alphaXiv answer_pdf_queries(paper='1808.08677', queries=['abstract percentages','p.5 quark and glue energy','sum rule form','sigma terms used','proton or nucleon'])",
"report_path": D + "/audits/1808.08677.json"
}
json.dump(r, open(D + "/audits/1808.08677.json", "w"), indent=1)
print("ok")
