import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/"
R={
"key":"fewster-teo-3.5-qn",
"name":"Fewster & Teo (3.5): Q_n spectral weight, at n = 3",
"source":{
 "located":"C. J. Fewster & E. Teo, 'Bounds on negative energy densities in static space-times', arXiv:gr-qc/9812032v2 (16 Feb 1999; DAMTP-1998-160; Phys. Rev. D 59 (1999) 104016). Eq. (3.5) p.7 (Sec. 3, Minkowski, massive field); eqs. (3.2)-(3.4) pp.6-7; Sec. 5 eqs. (5.1)-(5.7) pp.9-10 (static open Robertson-Walker, where (5.6) uses Q_3(u/C)); field equation (2.2) p.3.",
 "read_status":"READ",
 "via":"alphaXiv page text of gr-qc/9812032v2 as returned VERBATIM by alphaXiv answer_pdf_queries in an earlier workflow run of this same session (transcript subagents/workflows/wf_2008cce3-a18/agent-af3fbf232d06d747c.jsonl line 81), recovered into scratchpad/d67/src/gr-qc_9812032.cached.txt (same precedent as the sibling audits fewster-teo-3.2-minkowski and 1404.3565). At THIS stage answer_pdf_queries, get_paper_content and discover_papers all returned 'alphaXiv assistant quota exceeded', and arxiv.org is refused at the egress proxy (CONNECT 403; not routed around). The text layer drops every pi glyph; the one place that matters here (the (3.4) prefactor) is restored by argument and machine-checked (rederive check 5b). Q_n was introduced in Fewster-Eveson [14] (gr-qc/9805024), to which F&T refer for Q_3's explicit expression: NAMED-NOT-READ; Q_3's closed form is instead READ in Fewster math-ph/0501073v1 eq. (8) (cached verbatim, src/fewster-teo-later-restatements.cached.txt)."},
"published_statement":"(3.5): 'the functions Q_n(x) are defined by Q_n(x) = (n+1) x^{-(n+1)} INT_1^x dy y^2 (y^2-1)^{n/2-1}', entering (3.4): bound = -(C_n/(2 pi (n+1))) INT_mu^oo du |f^_{1/2}(u)|^2 u^{n+1} Q_n(u/mu) [text layer: '2(n+1)', pi dropped], C_n = area(S^{n-1})/(2 pi)^n (3.3). Sec. 5: 'Both (3.2) and (5.5) can, in fact, be written as -(1/4 pi^3) INT_0^oo dw INT_C^oo dw' w'^2 sqrt(w'^2 - C^2) |f^_{1/2}(w+w')|^2 = -(1/16 pi^3) INT_C^oo du |f^_{1/2}(u)|^2 u^4 Q_3(u/C) (5.6), where C = sqrt(kappa/a^2 + mu^2), kappa = 0 Minkowski space, 1 open universe (5.7) ... The Minkowski space result is obviously recovered in the limit of infinite a. Furthermore, since Q_3(x) is an increasing function on [1, oo), the bound for general a is tighter than that in Minkowski space for all sampling functions f(t).'",
"published_hypotheses":[
 "Globally static spacetime, ds^2 = -|g_tt(x)| dt^2 + g_ij dx^i dx^j (2.1), static observer, sampling function f with f^{1/2} used in the transform",
 "Free real scalar field of mass mu >= 0, MINIMALLY coupled: (2.2) (1/|g_tt|) d_t^2 phi - grad_i grad^i phi + mu^2 phi = 0 carries no xi R term (Sec. 4 adds xi only for the 3D closed universe)",
 "Complete orthonormal set of positive-frequency modes; the bound is on the energy density normal-ordered relative to the static vacuum |0>",
 "(3.5) is stated for n+1-dimensional Minkowski space with argument u/mu; Q_n is evaluated only for x >= 1 (the integral in (3.4) starts at u = mu)",
 "(5.6) at n = 3 holds only for kappa in {0, 1}: Minkowski and the ULTRASTATIC, HOMOGENEOUS static open RW universe (5.1) with slices H^3 of scale a, whose mode sum rule (5.4) is position-independent; C = sqrt(kappa/a^2 + mu^2) is the minimum mode frequency w_min"],
"hypothesis_drift":[
 "DROPPED (unnamed): MINIMAL COUPLING. F&T (2.2) is minimally coupled, and (5.2)'s w_q = sqrt((q^2+1)/a^2 + mu^2) gives C = 1/a (massless) only for xi = 0. The tree's hypothesis list for this use (fewsterteo.py:79-84, 293-298; the canonical entry: 'n = 3 (ultrastatic H^3 slices)') does not name it, though fewsterteo.py:178-181 names minimal coupling for Fewster & Smith. Computed (rederive 11a/11b): R = -6/a^2 on the static open universe, C^2 = (1 - 6 xi)/a^2 + mu^2, so conformal coupling closes the witness's gap (C = mu = 0) and the witness ratio would be 1. Direction: this can only REMOVE the refused 72.599 tightening, never create one; it does not move 71.256.",
 "DROPPED (unnamed, consistent): MASS mu = 0. F&T's C = sqrt(kappa/a^2 + mu^2) (5.7); the tree's witness_gap() sets C = b/a_c (fewsterteo.py:202-211), i.e. mu = 0. Consistent with the massless C_F = mu_1^4/(16 pi^2) the flat figure uses; recorded so the massless restriction is named.",
 "ADDED (harmless convention): 'Q_3(x) = 0 for x <= 1' (fewsterteo.py:296-297; canonical hypothesis 2). (3.5) defines Q_n only on [1, oo) (Fewster math-ph/0501073 eq. (8): 'Q_3 : [1, oo) -> R+'). Extending by 0 reproduces (5.6)'s lower limit u = C exactly, and ratio() (fewsterteo.py:318-332) integrates u < C with weight 1 - 0 = 1: equivalent, checked (rederive 9b, 8).",
 "WIDENED CLASS: '(5.6) returns the flat bound exactly' applied to the CORRIDOR through GAP_HYPOTHESIS (fewsterteo.py:98-101 'so w_min = 0, C = 0, ratio = 1, and (5.6) returns the flat bound exactly'; fewsterteo.py:173-177; specthm.py:954-955 'at spectral gap %g the Fewster-Teo form returns the flat bound'). F&T derive (5.6) only for kappa in {0,1} -- ultrastatic, homogeneous slices with a position-independent sum rule (5.4); for a non-homogeneous, non-ultrastatic static spacetime the left side of (2.12) is a local mode sum not expressible as (5.6) in one number C, and the relevant spectrum is that of |g_tt|(-grad^2 + mu^2)-type operator, not the Laplacian the GAP_HYPOTHESIS names. The statement 'the F&T FORM at C = 0 is the flat bound' is TRUE (Q_3 -> 1, rederive 4b; fewsterteo's own C = 0 control); 'the corridor's F&T bound is the flat bound' is NOT implied by (3.5)/(5.6). The tree does not assert the latter as closed (O2 stays OPEN, mode functions NOT-FOUND, fewsterteo.py:108-111, 4 'IT DOES NOT CLOSE O2'), and the REFUSAL of 72.599 needs only that the witness's tightening is a function of C within the (5.6) class and that the corridor supplies no such C -- so the widening affects the sentence at fewsterteo.py:100-101, not the refusal."],
"data_at_publication":[
 {"quantity":"Q_3 closed form / antiderivative (the tree's only datum)","value_then":"F&T refer to [14] (Fewster-Eveson) for 'an explicit expression (and graph) for Q_3(x)'","value_now":"(y(2y^2-1)sqrt(y^2-1) - acosh y)/8 (tree); Fewster 2005 eq. (8): Q_3 = (1-1/x^2)^{1/2}(1-1/(2x^2)) - ln(x+sqrt(x^2-1))/(2x^4)","source_now":"math-ph/0501073v1 eq. (8) (READ, cached); sympy residual 0 (rederive 3)","moves_conclusion":"No: identical functions, symbolic residual 0, max numeric |diff| 2.8e-15."},
 {"quantity":"C = sqrt(kappa/a^2 + mu^2) (5.7): the only parameter","value_then":"kappa in {0,1}, a, mu free","value_now":"unchanged; the tree's values (witness C = 35.3553 in units of c/b from achievable.required_density; corridor C = 0 under GAP_HYPOTHESIS) are the tree's own constructs, not external data","source_now":"fewsterteo.py:202-211, 173-177","moves_conclusion":"No external measured datum enters (3.5) or (5.6): the result is a mathematical identity."}],
"rederivation":{
 "method":"sympy",
 "script_path":D+"rederive/fewster-teo-3.5-qn.py",
 "outcome":"26 checks, 0 failed (~90 s). (1) (3.5) at n=3 is identically the tree's 4x^-4 INT_1^x y^2 sqrt(y^2-1) dy. (2) the tree's antiderivative differentiates to the integrand and vanishes at 1. (3) tree closed form == Fewster 2005 eq.(8), symbolic residual 0. (4) Q_3(1)=0, Q_3->1, Q_3' = 4h/x^5 with h(1)=0, h' = x^2/sqrt(x^2-1) > 0, so Q_3 strictly increasing on (1,oo) -- F&T's p.10 claim PROVED; 0<=Q_3<=1. (5) C_3 = 1/(2pi^2); (3.4)'s prefactor C_n/(2pi(n+1)) gives (5.6)'s 1/(16pi^3); the text-layer reading C_n/(2(n+1)) would give 1/(16pi^2) -- a dropped-pi TEXT-LAYER discrepancy, not a paper error. (6) INT_C^u v^2 sqrt(v^2-C^2) dv = u^4 Q_3(u/C)/4, so (5.6)'s two forms agree symbolically. (7) (5.5)->(5.6): with w_q = sqrt((q^2+1)/a^2+mu^2), (1/a^3) w_q q^2 dq = w'^2 sqrt(w'^2-C^2) dw', C = sqrt(1/a^2+mu^2). (8) both sides of (5.6) agree to 1e-15 for a Gaussian test spectrum at C = 0.3, 1, 2.5; CONTROL: a wrong exponent in (3.5) breaks it at each C. (9) fewsterteo.Q3 (lifted by ast, exec'd alone; nothing in research/ imported or written) matches direct quadrature of (3.5) to 1.6e-14 over 8 points to 1e5. (10) INDEPENDENT spot check: ratio(C=1) with an independent sampler transform and t-space Parseval total = 0.9743214583 vs the tree's GAP_SWEEP 0.974321. (11) static open RW R = -6/a^2 computed from the metric; C^2(xi) = (1-6xi)/a^2 + mu^2, so conformal coupling closes the gap.",
 "agrees_with_source":"yes"},
"later_literature":[
 {"ref":"C. J. Fewster, 'Energy inequalities in quantum field theory', arXiv:math-ph/0501073v1 (2005), eqs. (7)-(8)","effect":"confirms","what":"Restates the Minkowski QEI for mass m >= 0 as -(1/16pi^3) INT_m^oo du |g^(u)|^2 u^4 Q_3(u/m) with Q_3 : [1,oo) -> R+ in closed form, 0 <= Q_3 <= 1, Q_3 -> 1; 'not sharp', 3/2 off Flanagan in d = 2. The closed form equals the tree's (rederive 3).","read_status":"READ (p.4, verbatim alphaXiv page text from an earlier run of this session, cached at src/fewster-teo-later-restatements.cached.txt)"},
 {"ref":"C. J. Fewster & C. J. Smith, 'Absolute quantum energy inequalities in curved spacetime', arXiv:gr-qc/0702056v3, eq. (88)","effect":"extends","what":"The absolute QEI's flat massless limit is -(1/16pi^3) INT d eta |f^|^2 eta^4 -- (5.6) at C = 0, i.e. Q_3 -> 1 -- on any 4D globally hyperbolic spacetime, minimally coupled, mass >= 0: the tree's RIGHT_INSTRUMENT, which does not rest on (5.6)'s homogeneity.","read_status":"READ (p.24, verbatim alphaXiv page text, cached)"},
 {"ref":"C. J. Fewster & S. P. Eveson, Bounds on negative energy densities in flat spacetime, ref. [14] of F&T (arXiv id gr-qc/9805024 from background knowledge, not verified here), where Q_n originates","effect":"confirms","what":"NAMED ONLY: F&T cite it for Q_3's explicit expression and graph; not read here.","read_status":"NAMED-NOT-READ"},
 {"ref":"discover_papers for later work narrowing/contradicting F&T (3.5)/(5.6)","effect":"contested","what":"NOT RUN: the single discover_papers call returned 'alphaXiv assistant quota exceeded'. No erratum to gr-qc/9812032 was searched for, and none is claimed absent; the entries above are what the session already held, not a survey.","read_status":"NAMED-NOT-READ (search refused by quota)"}],
"lacked_data":"M's hypothesis tested for (3.5): Q_n is a DEFINITION (an integral of y^2 (y^2-1)^{n/2-1}), and its use in (5.6) is a change of variables in a mode sum; no measured quantity enters, so there is no datum the 1998 authors could have lacked that bears on it. Evidence: every step from (5.5) to (5.6) and the closed form of Q_3 re-derived symbolically (26/26), the closed form independently restated in 2005 with the same function. What the authors did not have (Fewster-Smith's absolute QEI, 2007; Hadamard-state extensions, Kontou-Sanders 2020) EXTENDS the class but does not revise (3.5). The only moving inputs are the tree's own: the coupling (unnamed; conformal coupling would remove the refused tightening) and whether the corridor is in (5.6)'s class at all (it is not homogeneous) -- neither is an external datum, and neither moves 71.256.",
"grade":"NARROWED",
"grade_evidence":"The published (3.5) at n = 3 is IDENTICAL to the tree's Q_3 (rederive 1), its closed form is correct (2, 3; independent 2005 restatement agrees), F&T's monotonicity claim is proved (4c-4d), the (5.5)->(5.6) chain and the 1/(16 pi^3) normalisation re-derive (5-8, controls fire), and one tree figure is reproduced by independent code (10: 0.9743214583 vs 0.974321). No datum moves. It is graded NARROWED, not STANDS, only because the tree's use drops two hypotheses of the source: (i) MINIMAL COUPLING, which fixes C = 1/a on the witness (rederive 11: conformal coupling gives C = 0), and (ii) the (5.6) CLASS -- kappa in {0,1}, ultrastatic homogeneous slices -- widened at fewsterteo.py:98-101 to 'the corridor's (5.6) returns the flat bound exactly'. Both narrowings leave the tree's operative conclusions where they are: 72.599 stays REFUSED (each dropped hypothesis can only remove the tightening, never supply one), 71.256 is unmoved, and O2 stays OPEN as the tree already says. Not WRONG: nothing in (3.5) or the tree's arithmetic is contradicted. The text-layer '2(n+1)' in (3.4) is a dropped-pi discrepancy of the extraction, not an error of the paper.",
"what_would_change_the_grade":"To STANDS: the tree names minimal coupling and 'kappa in {0,1}, ultrastatic homogeneous slices' as hypotheses of its (5.6)/Q_3 use, and rewords fewsterteo.py:100-101 to 'the F&T (5.6) form at C = 0 is the flat bound' (true) rather than attributing (5.6) to the corridor. To WRONG: a counterexample to (3.5)'s closed form or to (5.5)->(5.6) -- none found; the symbolic residuals are 0. To OPEN: none (the source was read and every claim here is finite and checked). A located erratum to gr-qc/9812032 (not searched, quota) would be read before any change.",
"reverify_command":"python3 "+D+"rederive/fewster-teo-3.5-qn.py   # 26 checks, exit 0; source text: grep -n '(3.5)\\|(5.6)\\|(5.7)' "+D+"src/gr-qc_9812032.cached.txt",
"report_path":D+"audits/fewster-teo-3.5-qn.json"}
json.dump(R,open(D+"audits/fewster-teo-3.5-qn.json","w"),indent=1)
print("ok")
