import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
W = "/home/user/Claude-Method-Works/research/warp-drive"
r = {
 "key": "implicit-function-theorem",
 "name": "Implicit function theorem (local existence/sign of the branch root through gamma = 0)",
 "source": {
  "located": "Classical theorem: Cauchy (analytic case, first rigorous proof) and U. Dini (real variables, 1876; Lezioni di Analisi Infinitesimale vol. 1, Pisa 1907, pp. 197-241); no arXiv copy of either. Exact modern statement read in O. R. B. de Oliveira, 'The implicit and the inverse function theorems: easy proofs', arXiv:1212.2066v1 (2012), Theorem 1 (one equation, p. 5) and Theorem 2 (system, pp. 6-7). The tree's application (the function F_S it is applied to) was read at source in Galanda-Meda-Murro-Pinamonti-Schmid arXiv:2604.01047v1 (GMMPS), (4.17)-(4.18) p. 48, Thm 4.16 p. 58, (5.1)-(5.3) pp. 59-60, 5.3 p. 62.",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "alphaXiv answer_pdf_queries page text: 1212.2066 pp. 1-10 in full (Theorem 1 with its proof by IVT/MVT, Theorem 2, Lemma 4, history p. 1-2); 2604.01047 pp. 1, 33, 40, 48-52, 58-60, 62. Cauchy and Dini are NAMED-NOT-READ (restated in 1212.2066). Krantz-Parks (2002) is NAMED-NOT-READ; 1212.2066 p. 2 restates that the Krantz-Parks induction proof 'does not establish the local uniqueness of the implicit solution'."
 },
 "published_statement": "de Oliveira 1212.2066 Theorem 1 (p. 5): 'Let F : Omega -> R be of class C^1 in an open set Omega inside R^n x R and (a, b) be a point in Omega such that F(a, b) = 0 and dF/dy(a, b) > 0. Then, there exist an open set X, inside R^n and containing a, and an open set Y, inside R and containing b, satisfying the following. For each x in X there is a unique y = f(x) in Y such that F(x, f(x)) = 0. We have f(a) = b. Moreover, f : X -> Y is of class C^1 and df/dx_j(x) = -F_{x_j}(x, f(x)) / F_y(x, f(x)).' Theorem 2 (pp. 6-7) is the same with F in C^1(Omega; R^m) and dF/dy(a, b) invertible (the sign condition > 0 in Theorem 1 is WLOG for m = 1: replace F by -F).",
 "published_hypotheses": [
  "H1 Omega open in R^n x R (here n = 1: x = alpha~^S_1, y = gamma)",
  "H2 F of class C^1 on Omega (F and its first partials continuous)",
  "H3 F(a, b) = 0 at the base point",
  "H4 dF/dy(a, b) != 0 (stated as > 0 in Theorem 1; invertible in Theorem 2)",
  "CONCLUSION IS LOCAL: X and Y exist but are not quantified; uniqueness holds only inside Y; nothing is asserted about zeros outside Y or about complex zeros"
 ],
 "hypothesis_drift": [
  "H2 STRENGTHENED, SATISFIED (linstab.py:959-960 lists 'F_S smooth in (gamma, alpha~^S_1) near (0, 0)'): smooth implies C^1. Checked, not assumed: F_S is affine in alpha (R4) and J is real-analytic on (-inf, 4m^2) (GMMPS (4.17)-(4.18) domain D excludes only [4m^2, inf)); J(0), J'(0), J''(0) are finite, 1/(96 pi^2 m^2), 1/(960 pi^2 m^4), 1/(3360 pi^2 m^6) (R1). No effective drift.",
  "H4 KEPT, WITH UNSTATED CONDITIONS OF THE APPLICATION (linstab.py:959-960): F_S'(0) (1-6xi)^2 kappa = 12 + kappa m^2/(24 pi^2) is re-derived (R2); F_S'(0) > 0 then needs kappa = 8 pi G > 0, m > 0 and xi != 1/6. z3 proves positivity under exactly these (R2) and a control shows kappa < 0 can flip the sign. m > 0 is stated in the tree's GMMPS setting (linstab.py:122); kappa > 0 and xi != 1/6 are implicit (F_S is undefined at xi = 1/6: a, b_0, b_1 diverge). NAMED here, not a drop: all three hold in GMMPS's setting.",
  "CONCLUSION WORDING -- DISCREPANCY, NOT REFUTATION (linstab.py:165-166 'THAT zero ... exists iff alpha~^S_1 != 0'; also linstab.py:345-346 LITERATURE_SPLIT_IS_ONE_CONSTANT and linstab.py:367-369 D26_CLAIM / LEDGER.md:49): the IFT gives existence of the branch zero f(alpha) for EVERY alpha in X, alpha = 0 included, where f(0) = 0. What the IFT plus F_S(alpha, 0) = -b_0 gives is 'the branch zero is NONZERO iff alpha != 0' (R4, R5: at alpha = 0 the root exists and equals 0 to 1e-30). The tree itself records that gamma = 0 is an exact root at alpha = 0 (linstab.py:168-169, 961), so its intended meaning is the accurate one; the literal word 'exists' is not.",
  "LOCALITY KEPT (linstab.py:164 'LOCALLY', 346-347 '(locally, implicit function theorem)', 367 'locally'): the source's X is unquantified and the tree never claims more. The tree bridges from 'alpha near 0' to GMMPS's physical alpha = 1/(64 pi^2) not by the IFT but by an explicit IVT bracket at |b_2| <= 1e100 (s_root_bracket, linstab.py:636-661, 973-976). Measured here (R8): at GMMPS's point (m = 1, kappa = eps = 1.048e-59) the IFT branch reaches the physical alpha iff b_2 >= -B*, B* = F_1^2/(4 F_0) = 8.62e120 (xi = 0 and xi = 1/3, which coincide because B* scales as 1/(6 (1/6 - xi)^2)); every b_2 > 0 is covered. The tree's 1e100 bracket lies inside B*.",
  "SCOPE OF 'grows' -- ADDED DEPENDENCE, NAMED (linstab.py:166, 963): the IFT yields the SIGN of the root: f'(0) = -2 kappa m^4/(1 + kappa m^2/(288 pi^2)) < 0 (R3), and because F_S is affine in alpha, f(alpha) != 0 on X minus {0}, so the sign is constant on each side of 0 throughout X, not only at first order (R4). That a negative F_S root is a GROWING mode is GMMPS's pole term in (4.31) / Thm 4.16 (p. 58), a separate result; the simple-zero condition Q'(-gamma_0) != 0 that the pole term needs is supplied by F_gamma != 0 on the branch.",
  "UNIQUENESS SCOPE KEPT (linstab.py:173-180): IFT uniqueness is only inside Y; the tree explicitly does NOT claim the 'only if' for growth in general ('OTHER GROWING ROOTS ARE NOT SET BY alpha~^S_1'). Extension computed here (R6): F_S is holomorphic in gamma near 0, and the winding number of F_S on |gamma| = 0.2 (m = 1, kappa = 0.3, xi = 0, b_2 = -1, alpha = 1e-3) is 1 -- exactly one zero in the complex disk, so no complex-conjugate pair hides near the branch.",
  "ADJACENT, NOT THIS KEY (recorded for the GMMPS Thm 4.16 entry): linstab.py:136 and 190 paraphrase Thm 4.16's growth clause as '(for Z strictly inside (-4m^2, 0))'. Source p. 58: the DECAY clause is 'Z subset (-4m^2, 0)'; the GROWTH clause is 'Z subset (-4m^2, inf), with some gamma in Z, gamma > 0' (in Q's variable w^2 = -gamma_F). The tree's conclusion that the alpha = 0 root gamma = 0 lies outside Thm 4.16 survives under the source's wording (0 is not in the open (-4m^2, 0), and 0 is not > 0)."
 ],
 "data_at_publication": [
  {"quantity": "alpha~^S_1 (the parameter the IFT branch is taken in)", "value_then": "1/(64 pi^2) = 1.583e-3 (GMMPS Thm 3.6 p. 33 and p. 40); 5.1 p. 59 prints (64 pi)^-1 (a misprint the tree already records)", "value_now": "unchanged; GMMPS v1 is the only version read; AMM's k^2 = 0 subtraction corresponds to alpha~^S_1 = 0 -- contested between the two papers, not adjudicated here or in the tree (linstab.py:350 SPLIT_ADJUDICATED_HERE = False)", "source_now": "arXiv:2604.01047v1 pp. 33, 40, 59 (READ)", "moves_conclusion": "NO for the IFT result: the conclusion is stated as a function of alpha (nonzero iff alpha != 0, growing side iff alpha > 0). Which alpha is correct decides which side of that statement applies, which is the split the tree leaves open."},
  {"quantity": "Lambda / M_P^2 (sets eps = (m/M_P)^2 at GMMPS's physical point, hence the size B* of the IFT neighbourhood)", "value_then": "7.15e-121 (GMMPS 5.3 p. 62, READ); reproduced here from H0 = 67.4 km/s/Mpc, Omega_Lambda = 0.6847 as 7.161e-121 (R9)", "value_now": "with H0 = 73.04 km/s/Mpc (distance-ladder value) 8.41e-121; the H0 tension is contested. The H0 and Omega_Lambda values were entered as inputs for a sensitivity computation and were NOT read at source in this stage (alphaXiv quota exhausted)", "source_now": "computed in rederive R9; Planck 2018 (arXiv:1807.06209) and SH0ES (arXiv:2112.04510) NAMED-NOT-READ here", "moves_conclusion": "NO: eps moves from 1.048e-59; B*(xi = 0) moves 8.61e120 -> 7.33e120, still >> the tree's 1e100 bracket; the qualitative IFT conclusion does not involve Lambda at all (R3, R4 are symbolic in kappa, m, alpha)."},
  {"quantity": "Omega_Lambda", "value_then": "0.685 (GMMPS 5.3, READ; linstab.py:319)", "value_now": "0.6847 used here; DESI-era evidence for evolving dark energy exists but was NOT read in this stage", "source_now": "NAMED-NOT-READ here", "moves_conclusion": "NO: enters only eps through Lambda^(1/2) and hence B*; not the IFT statement."}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/implicit-function-theorem.py",
  "outcome": "27 PASS, 0 FAIL, ~8 s, exit 0 (sympy 1.14.0, mpmath 1.3.0, z3 5.1.0). R1 J(0) = 1/(96 pi^2 m^2) from the (4.5) integral; J'(0), J''(0) finite (J analytic at 0). R2 F_S(0,0) = 0; F_gamma(0,0) (1-6xi)^2 kappa = 12 + kappa m^2/(24 pi^2), independent of b_2 and alpha; z3 unsat of its negation under kappa > 0, m > 0, xi != 1/6; control: kappa < 0 can flip it. R3 f'(0) = -F_alpha/F_gamma = -2 kappa m^4/(1 + kappa m^2/(288 pi^2)), the tree's formula, xi-independent, negative; GMMPS -b_0/b_1 = -16 pi G alpha m^4. R4 F_S affine in alpha, F_S(alpha,0) = 0 only at alpha = 0: the branch zero is nonzero iff alpha != 0 on all of X, with constant sign on each side. R5 numeric (full J by quadrature): root < 0 iff alpha > 0 at alpha = +-1e-3, +-1e-4; remainder O(alpha^2); at alpha = 0 the root is 0. R6 winding number 1 on |gamma| = 0.2 (one zero, real). R7 control gamma^2 - alpha: F_gamma = 0 and no real root for alpha < 0 (the hypothesis bites). R8 at GMMPS's point: B* = 8.62e120 for xi = 0 and 1/3; root exists at b_2 = -0.9 B*, none on [4 g_fold, 0] at -1.1 B*; 1e100 < B*. R9 Lambda reproduced from Planck-2018 inputs to 0.2 %; B* stays > 1e100 under the H0 move. The tree's own selftest (python3 linstab.py --selftest) was also run read-only: 72 checks, 0 failed, including its IFT lines (46, 48-50, 53-55 of its output).",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "de Oliveira, arXiv:1212.2066v1 (2012)", "effect": "confirms", "what": "Exact statement and elementary proof (IVT + MVT, Dini's route) of the one-equation IFT with local uniqueness; the tree's use matches its hypotheses.", "read_status": "READ (pp. 1-10)"},
  {"ref": "Galanda, Meda, Murro, Pinamonti, Schmid, arXiv:2604.01047v1 (2026)", "effect": "narrows", "what": "The function the IFT is applied to. Confirms F_S (5.3), b_0, b_1, a (5.2) and gamma_0 ~ -b_0/b_1 = -16 pi G alpha m^4 (p. 62, J dropped; the IFT slope with J included reduces to it as kappa m^2 -> 0). GMMPS p. 60 states that 'in all these cases' (b_2 < 0 regimes) there is a real zero slightly below 0; R8 here shows that at their physical point the branch zero leaves the real axis for b_2 < -B* = -8.6e120 (m = 1 units). Recorded as a narrowing of their qualitative sentence at extreme b_2, NOT as an error: their b_2 range is not quantified.", "read_status": "READ (pp. 1, 33, 40, 48-52, 58-60, 62)"},
  {"ref": "Krantz & Parks, The Implicit Function Theorem: History, Theory, and Applications (Birkhauser 2002)", "effect": "confirms", "what": "Standard history/theory reference; per 1212.2066 p. 2 its induction proof does not itself establish local uniqueness (uniqueness is supplied by other proofs, e.g. 1212.2066's Lemma 4 route).", "read_status": "NAMED-NOT-READ (restated in 1212.2066)"},
  {"ref": "Hurwicz & Richter, Implicit functions and diffeomorphisms without C^1, Adv. Math. Econ. 5 (2006) 65-96", "effect": "extends", "what": "Versions of the IFT with C^1 weakened; not needed here since F_S is real-analytic at the base point.", "read_status": "NAMED-NOT-READ (cited in 1212.2066; alphaXiv quota exhausted before it could be read)"},
  {"ref": "discover_papers search for later IFT work (quantitative neighbourhood, weakened hypotheses)", "effect": "contested", "what": "NOT RUN TO COMPLETION: alphaXiv returned 'assistant quota exceeded' and the arXiv API is refused by the egress proxy (403). No later literature beyond the rows above was located; this is a gap in this audit, not evidence either way.", "read_status": "NOT READ (tool quota)"}
 ],
 "lacked_data": "The IFT is a theorem of analysis (Cauchy; Dini 1876); its conclusion rests on no measured input, so there is no datum its authors could have lacked that bears on it -- evidence: every check of the theorem's application here (R2-R4, R6) is symbolic in kappa, m, xi, alpha and exact. What the classical statement genuinely lacks is QUANTIFICATION: X and Y are not sized. For this application that missing piece is computed here rather than presumed: at GMMPS's physical point the neighbourhood reaches alpha = 1/(64 pi^2) iff b_2 >= -8.6e120 (m = 1 units), and the tree's bracket (|b_2| <= 1e100) sits inside it. The data the APPLICATION uses -- alpha~^S_1 (contested between GMMPS Thm 3.6 and AMM's subtraction), Lambda and H0 (tension between Planck and distance ladder) -- were moved and do not move the IFT's conclusion (R9); alpha~^S_1 decides which side of the conditional applies, which the tree leaves unadjudicated. M's hypothesis therefore finds nothing here: no missing datum changes this result.",
 "grade": "STANDS",
 "grade_evidence": "Statement and hypotheses as the tree uses them match de Oliveira 1212.2066 Theorem 1 (READ-VIA-RESTATEMENT of Cauchy/Dini): C^1 (tree: smooth, verified: affine in alpha, J analytic at 0), F(0,0) = 0 (verified), F_gamma(0,0) != 0 (re-derived: (12 + kappa m^2/(24 pi^2))/(kappa (1-6xi)^2) > 0, z3-proved for kappa > 0, m > 0, xi != 1/6, conditions of GMMPS's setting). The tree keeps 'LOCALLY' at every use and does not claim the 'only if' for growth in general. The IFT slope reproduces the tree's first-order formula exactly and xi-independently; the sign statement holds on all of X, not only at first order, because F_S is affine in alpha. Numerics with the full J agree (27/27 PASS). No moved datum moves it. Recorded, not repaired: (i) a WORDING discrepancy -- 'exists iff alpha != 0' should read 'is nonzero iff alpha != 0' (the root exists at alpha = 0 as gamma = 0, which the tree itself records at linstab.py:168-169, 961); (ii) kappa > 0 and xi != 1/6 are used but unstated at linstab.py:959-960; (iii) the neighbourhood, measured: b_2 >= -8.6e120 at GMMPS's point; (iv) adjacent paraphrase of GMMPS Thm 4.16 at linstab.py:136, 190 (belongs to that entry). None is a counterexample or a hypothesis the tree's claims need beyond what holds.",
 "what_would_change_the_grade": "NARROWED if a rests_on_it claim (LITERATURE_SPLIT_IS_ONE_CONSTANT, D26, specthm R8) were read as holding at GMMPS's physical alpha for b_2 < -8.6e120 (m = 1 units), or at xi = 1/6, or with kappa <= 0 -- there the branch zero does not reach the physical alpha or F_S is undefined. WRONG only if a point with F_S C^1 and F_gamma(0,0) != 0 were exhibited where the branch zero is zero for some alpha != 0 or has the opposite sign to -alpha near 0 (R4 shows this cannot happen since F_S is affine in alpha). OPEN would apply only if GMMPS (5.2)-(5.3) or (4.17) were found misread; they were read at source here. A completed later-literature search (blocked by quota here) could add, but not remove, context.",
 "reverify_command": "python3 " + D + "/rederive/implicit-function-theorem.py && (cd " + W + " && python3 linstab.py --selftest | grep -E 'IFT|BRANCH|F_S\\(0\\)|checks that can fail') && sed -n '164,169p;343,349p;365,370p;959,965p' " + W + "/linstab.py",
 "report_path": D + "/audits/implicit-function-theorem.json"
}
json.dump(r, open(D + "/audits/implicit-function-theorem.json", "w"), indent=1)
print("ok")
