import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S=D+"/rederive/2604.05980-fig1-growth-rate.py"
R=D+"/audits/2604.05980-fig1-growth-rate.json"
src=D+"/src/casmag/all/2604.05980v1.txt"
rep={
"key":"2604.05980-fig1-growth-rate",
"name":"Pitre et al. Fig. 1: Im{omega}(R^3/M)^{1/2} ~= 0.6 (0.52-0.66), roughly flat over M/R in [0,0.3], Gamma in [1.8,2.4]",
"source":{
 "located":"arXiv:2604.05980v1 [gr-qc] (dated 8 Apr 2026), T. Pitre, B. Schneider, E. Poisson (Guelph), 'Self-gravitating thin shells are dynamically unstable on all angular scales'. Fig. 1 is on p.3. No journal reference appears on the pages read, so the tree's 'Phys. Rev. D' (wall.py:110) is not verified here.",
 "read_status":"READ",
 "via":"alphaXiv was over quota for this stage: answer_pdf_queries, get_paper_content and discover_papers were all refused, and direct arxiv.org returned a proxy 403. I read the alphaXiv <page> text cached earlier in this workflow instead: "+src+" (md5 9916ebc75c7859da12c37c59acc4458f). It holds p.3 in full (Fig. 1's axes, tick labels and caption), p.4 (Sec I D text on Fig. 1), p.41 (Eqs 10.52b-10.57) and pp. 1-2, 6-7, 9, 23, 37 and 47. NOT read: the dot values themselves, which are graphics and are not in the text layer; p.40 (the printed general-l Newtonian eigenvalues); and Sec VII's post-Newtonian expansion of the unstable frequency."
},
"published_statement":"Fig. 1 caption (p.3), verbatim: 'Unstable even-parity matter mode: Mode frequency omega(R^3/M)^{1/2} for l = 2. Left: Imaginary part of the frequency in relation to M/R for Gamma = 2. Right: Imaginary part of the frequency in relation to Gamma for M/R = 0.2. The real part of the frequency vanishes for this mode. The dots represent our numerical data, and they are linked by guiding lines.' The left panel's x-axis runs 0.00-0.30 with y-ticks 0.52, 0.54, ..., 0.66. The right panel's x-axis runs 1.8-2.4 with y-ticks 0.56, ..., 0.64. Sec I D (p.4): 'The mode frequency is shown in Fig. 1 as a function of the compactness M/R and the adiabatic index Gamma, for the specific case of l = 2. An unstable mode exists also for l = 3 ... and for all other values of l that we could sample.' No numerical value of Im omega is printed in the text read.",
"published_hypotheses":[
 "l = 2 only (caption)",
 "Left panel: Gamma = 2 fixed, M/R sampled on [0, 0.30]. Right panel: M/R = 0.2 fixed, Gamma sampled on [1.8, 2.4]. Two 1-D cuts, not a 2-D box",
 "Values are numerical dots joined by guiding lines. Between dots the curve is an interpolation, and no dot value is printed",
 "Model (abstract, Secs I-III): an infinitesimally thin, static, spherically symmetric shell of barotropic perfect fluid, p = K sigma^Gamma, with Gamma = d ln p/d ln sigma in the rest-mass density. Minkowski inside, Schwarzschild outside, vacuum on both sides, linear even-parity perturbations, outgoing-wave boundary conditions",
 "Frequency conjugate to retarded time u at infinity, geometric units G = c = 1. So omega(R^3/M)^{1/2} -> Im omega sqrt(R^3/(GM)) in SI"
],
"hypothesis_drift":[
 "DROPPED: l = 2 only -> 'l >= 2'. wall.py:454 ('Growth rate of the l >= 2 even-parity matter mode') and wall.py:440 apply PSP_K = 0.6 to every l >= 2, and the density ceiling (wall.py:138-143, 465-467) is written as the l >= 2 ceiling. Fig. 1 is l = 2 only. Re-derived here in the Newtonian limit at Gamma = 2: kappa_l = 0.515, 1.090, 1.630, 2.154 and 4.702 for l = 2, 3, 4, 5 and 10, with kappa_l -> l/2. So k = 0.6 understates every l >= 3, by a factor of at least 1.82.",
 "ADDED: '0.52-0.66' is presented as the range of the value (wall.py:440 'Im{omega}(R^3/M)^{1/2}, 0.52-0.66'). That span is the left panel's y-TICK range, not a stated data range. The right panel's ticks are 0.56-0.64.",
 "ADDED: 'roughly flat over M/R in [0, 0.3] and Gamma in [1.8, 2.4]' (wall.py:131-133). The text layer does not give the dot values, so flatness is not readable. A y-axis spanning 0.52-0.66 is compatible with a variation of up to ~25% across M/R. In the Newtonian limit the l = 2 rate varies by 15.9% over Gamma in [1.8, 2.4] (0.548 -> 0.473, computed here). 'Flat' is the tree's reading, not the paper's word.",
 "WIDENED: two 1-D cuts become a box. The tree's 'over M/R in [0,0.3] and Gamma in [1.8,2.4]' (wall.py:132-133) implies coverage of the product. The figure samples Gamma only at M/R = 0.2, and M/R only at Gamma = 2.",
 "STATUS WORD: 'PINNED' (wall.py:440) for a value read off a plotted dot curve with no printed number. The canonical entry already lists 'value read off a figure' as a hypothesis. PINNED is stronger than the source supports; READ-OFF-FIGURE would match it.",
 "REGIME (not drift in the canonical's sense, but misdescribed): the canonical hypothesis 'extrapolated in M/R beyond the plotted [0, 0.3] to x ~ 1e-24' is imprecise. The tree's x = 2GM/(Rc^2) = 2C (wall.py:160), so x ~ 1e-24 is M/R ~ 5e-25. That is INSIDE [0, 0.3], at its left edge, not beyond it. At that edge the value is the Newtonian limit, which is 0.5147 at Gamma = 2 by the re-derivation here, not 0.6. That endpoint is inferred, not printed (p.40 and the post-Newtonian varsigma_0 of Sec VII were not read). Le's x = 0.3 (wall.py:172) is M/R = 0.15, which is inside the plotted range.",
 "NOT DRIFT: 'extrapolated to masses/radii far from the paper's samples' (canonical hypothesis 3). The model has no scale besides M and R: vacuum, a thin shell, and a polytrope whose K is fixed by equilibrium. So omega sqrt(R^3/GM) depends only on (M/R, Gamma, l). Checked: the Newtonian restoring matrix has free symbols {l, Gamma} only. Using the figure at 1e6 kg and km radii is therefore no extrapolation at all, given M/R.",
 "NOT DRIFT: the Gamma = 2 cut matches the tree's own wall. Converting the tree's counter-rotating Vlasov beta^2 through PSP Eq (2.7) gives Gamma = 2.000000 at x = 1e-9 (4/3 x 3/2), computed by importing wall.py read-only. So the left panel's Gamma is the right cut for the tree's model in the radial sense. A collisionless shell is still not a barotropic fluid under non-radial perturbation: the barotropic-perfect-fluid hypothesis is dropped, as the sibling audit 2604.05980-nonradial-instability records."
],
"data_at_publication":[
 {"quantity":"k = Im omega sqrt(R^3/GM), l = 2, at the tree's operating regime M/R -> 0 (x ~ 1e-24 to 1e-20)","value_then":"Fig. 1 left panel, Gamma = 2: plotted dots, y-axis ticks 0.52-0.66, no printed value. The tree reads 0.6.","value_now":"0.51470 (Newtonian l = 2, Gamma = 2), re-derived here. That is 14% below 0.6 and 0.0053 below the lowest y-tick 0.52, which is consistent only if the axis floor sits below the tick. Over the radially stable class Gamma >= 3/2 the l = 2 Newtonian value ranges over (0.3464, 0.6273]. It equals 0.6 at Gamma = 1.584.","source_now":"rederive/2604.05980-fig1-growth-rate.py (sympy): Newtonian membrane equations re-implemented and checked against printed Eqs (10.52b), (10.53a,b) forcing structure, (10.57) and the l = 0 eigenvalue on p.41","moves_conclusion":"Moves numbers, not the verdict. rho_max scales as 1/k^2: 2.658e-4 -> 3.612e-4 kg/m^3. R_min(1e6 kg, N<1): 964.8 -> 871.1 m. N<0.1: 4478 -> 4043 m. 1% binding: 2.075e9 Msun at 1034 AU -> 1.78e9 Msun at 887 AU. x = 0.3: 4.327e10 -> 3.71e10 Msun (though x = 0.3 is M/R = 0.15, where the GR value is not the Newtonian one and is not readable). 'Two billion solar masses over a thousand AU' holds as an order of magnitude."},
 {"quantity":"k for l >= 3 (the tree applies 0.6 to 'l >= 2')","value_then":"Not in Fig. 1. Sec I D says an unstable mode exists for l = 3 and all sampled l; the l = 3 values (Fig. 7) were not read.","value_now":"Newtonian, Gamma = 2: 1.0901 (l=3), 1.6298 (l=4), 2.1539 (l=5), 4.7020 (l=10), 49.745 (l=100); kappa_l/(l/2) -> 1","source_now":"rederive/2604.05980-fig1-growth-rate.py","moves_conclusion":"Yes, in the direction that TIGHTENS the tree's ceiling. l = 3 gives rho_max = 8.05e-5 kg/m^3, R_min = 1437 m, and a 1% binding object of 3.77e9 Msun at 1880 AU. l = 10 gives 4.33e-6 kg/m^3 and 1.63e10 Msun at 8107 AU. For an infinitely thin shell no l_max exists, so no finite ceiling follows from the model alone. The tree's withdrawal of the diffuse corner is strengthened, not weakened."},
 {"quantity":"Gamma dependence of k (tree: 'roughly flat ... Gamma in [1.8, 2.4]')","value_then":"Right panel at M/R = 0.2, ticks 0.56-0.64, dots not printed","value_now":"Newtonian l = 2: 0.5477 (1.8), 0.5147 (2.0), 0.4907 (2.2), 0.4726 (2.4), a 15.9% spread. As Gamma -> infinity: sqrt(0.12) = 0.3464","source_now":"rederive script","moves_conclusion":"No, for the tree's verdicts. typefour.py:290 (N > 100 for 1e6 kg at 10 m) holds for any k >= 0.0633. The smallest l = 2 value on Gamma >= 3/2 is 0.3464, giving N = 547."},
 {"quantity":"R_min for 1e6 kg, N < 1 (canonical data_used: 964.4 m)","value_then":"964.4 m (wall.py:631, and wall.py:632's check tolerance 0.5)","value_now":"964.8 m at k = 0.6. wall.py:140's prose says 965 m, which is correct.","source_now":"rederive script, same formula as wall.py min_radius","moves_conclusion":"No. The check constant 964.4 is 0.4 m off the computed value but inside its own 0.5 tolerance. A discrepancy, recorded."},
 {"quantity":"G, c (used to convert k to SI)","value_then":"G = 6.67430e-11, c = 299792458 (wall.py:441)","value_now":"CODATA 2022 G = 6.67430(15)e-11 (unchanged); c exact","source_now":"CODATA 2022 (per the sibling audit's cached scipy constants)","moves_conclusion":"No."}
],
"rederivation":{
 "method":"sympy",
 "script_path":S,
 "outcome":"ALL PASS (exit 0; output in rederive/2604.05980-fig1-growth-rate.out). I re-implemented the Newtonian even-parity membrane equations of a thin barotropic self-gravitating shell, with G = M = R = 1. The restoring matrix has trace (Gamma(l^2+l+4) - (l^2+l+6))/4 and det -l(l-1)(l+1)(2Gamma l^2 + Gamma l - 6Gamma - 4l + 8)/(16(2l+1)). It reproduces these printed items: l = 0 lambda = Gamma - 3/2; l = 1 eigenvalues {0, (3Gamma-4)/2} with the translation zero mode j = h (10.57); the h-row combination and denominator of (10.52b); and, new to this audit, the tidal-forcing structure of (10.53a,b), where (L F)_h/F_h = -(l-1)(2Gamma+l-2)/4 for F ~ (l, 1) gives exactly the printed coefficients 2Gamma - 4kappa^2/(l-1) + l - 2 and 2Gamma + 4omega^2/(l-1) + l - 2. LIMIT: the tangential (j) row is validated only at l = 0 and 1 and by the eikonal membrane limit omega^2 = -(p/sigma)k^2. The printed general-l eigenvalues (p.40) were not read. Results: at Gamma = 2, l = 2, the Newtonian coefficient is 0.51470. Over Gamma in [1.8, 2.4] it runs 0.548-0.473, and it grows with l toward l/2. The tree's arithmetic at k = 0.6 is reproduced to its stated digits (2.657927437e-4 kg/m^3, 4.478398718 km, 1034.4 AU, 2.075e9 and 4.327e10 Msun, N = 947.7 at 10 m). What the figure plots in GR at M/R > 0 cannot be checked here: the dot values are not in the text layer, and the relativistic quasinormal problem was not rebuilt.",
 "agrees_with_source":"partly"
},
"later_literature":[
 {"ref":"A. T. Le, 'Radiative steering of warp shells', arXiv:2606.22531v4 (Sep 2026), p.2 line 88 and ref [19]","effect":"narrows","what":"Restates PSP as 'the fully coupled study [19] finds growing even-parity modes at all sampled multipoles l >= 2 and parameter values', and says its 'constitutive assumptions differ from those of the radiating shell considered here'. It quotes no growth-rate number, so it neither confirms nor moves the 0.6 reading. It limits the use to barotropic fluid thin shells.","read_status":"READ (cached alphaXiv page text d67/src/casmag/all/2606.22531v4.txt, md5 5a693452d50444f5188264f046e56c17, lines 86-90, 1951)"},
 {"ref":"H. Yang, B. Bonga, Z. Pan/Pen, PRL 130, 011402 (2023), arXiv:2207.13754 (eikonal membrane instability)","effect":"confirms","what":"This is the l >> 1 antecedent. The re-derived kappa_l -> l/2 is the eikonal membrane-with-pressure rate. It confirms that the l = 2 value is the SLOWEST of the l >= 2 branch at fixed Gamma, not a representative one.","read_status":"NAMED-NOT-READ (restated in 2604.05980v1 abstract p.1)"},
 {"ref":"discover_papers for later work (finite thickness, elasticity, higher-l rates)","effect":"extends","what":"Not run: the alphaXiv quota was exceeded for discover_papers at this stage. No later literature on the growth-rate value was found by search, and none is claimed.","read_status":"NOT RUN (tool refused: quota)"}
],
"lacked_data":"M's hypothesis tested for this result. Fig. 1 is a numerical computation inside a stated model, and it rests on no measured datum, so no later measurement can move it. What the authors did not supply, and the tree then needed, is coverage: (a) l = 2 only in Fig. 1; (b) two 1-D cuts, not the (M/R, Gamma) box; (c) no printed numbers. Evidence either way: the Newtonian limit, re-derived here and checked against four printed Newtonian results, gives 0.5147 at the tree's operating point (Gamma = 2, M/R -> 0). That is 14% below the tree's 0.6, and the move makes the tree's l = 2 ceiling 36% too STRICT. But the rate grows with l (kappa_3 = 1.09, kappa_l ~ l/2), and the tree applies the l = 2 number to all l >= 2, so the true l >= 2 constraint is TIGHTER than the tree's, without bound for an infinitely thin shell. The paper's authors did not lack data. The tree used their l = 2 number beyond its l. Having the l >= 3 rates does not reverse any tree verdict: it strengthens 'not escapable while self-gravitating' within the fluid-thin-shell model, and it removes any claim that 'rho_mean < 2.658e-4 kg/m^3' is THE ceiling.",
"grade":"NARROWED",
"grade_evidence":"The figure is READ at source (cached alphaXiv p.3 text, md5 9916ebc7...). It is l = 2 only, two cuts (Gamma = 2 over M/R in [0, 0.3]; M/R = 0.2 over Gamma in [1.8, 2.4]), with dots and no printed values. The tree's '~0.6, 0.52-0.66' falls inside the plotted axes, and nothing SHOWN here makes it wrong as a reading of an l = 2 GR curve at M/R > 0. It holds on a smaller class than the tree uses: (1) wall.py:440/454 applies it to 'l >= 2', but at Gamma = 2 the re-derived Newtonian rates are 1.090, 1.630 and 4.702 for l = 3, 4 and 10, so the density ceiling (wall.py:138-143) is an l = 2 ceiling only; (2) at the tree's regime M/R ~ 5e-25 (the plotted left edge, not an extrapolation) the l = 2 value is 0.5147 by the Newtonian re-derivation, not 0.6; (3) 'roughly flat' and the '0.52-0.66' range are tick-range readings, and 'PINNED' overstates a figure reading. No verdict resting on it moves: typefour.py:290 holds for k >= 0.063, and 'two billion Msun over a thousand AU' becomes 1.78e9 Msun over 887 AU at l = 2 and grows for l >= 3. Not WRONG: the 0.6-vs-0.5147 gap is a figure reading at the wrong end of the curve, a discrepancy and not a refutation. It is not DATA-DEPENDENT, since no measured datum enters.",
"what_would_change_the_grade":"-> STANDS for the tree's use: the tree restricts PSP_K to l = 2 (or takes k = max over the l its model admits), labels it READ-OFF-FIGURE, and uses the M/R -> 0 endpoint value. -> OPEN: if the Newtonian endpoint value 0.5147 could not be tied to the paper, for example if p.40's printed lambda_+- or Sec VII's post-Newtonian varsigma_0 disagreed with the re-derived matrix. Reading p.40 and Sec VII (Fig. 7's l = 3 values) at source would settle this. -> WRONG would need the digitised Fig. 1 dots to lie outside any reading consistent with ~0.6 over the GR range the tree cites. The text layer does not allow digitising, so that is not shown.",
"reverify_command":"cd /tmp && python3 "+S+" ; md5sum "+src+" ; sed -n 152,200p "+src+" ; sed -n 370,378p "+src+" ; sed -n 1155,1200p "+src+" ; grep -n 'PSP_K\\|l >= 2 even-parity\\|roughly flat' /home/user/Claude-Method-Works/research/warp-drive/wall.py ; sed -n 288,291p /home/user/Claude-Method-Works/research/warp-drive/typefour.py",
"report_path":R
}
json.dump(rep,open(R,"w"),indent=1,ensure_ascii=False)
print("written",R)
