import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R={
"key":"2405.05963-sec3.2",
"name":"Kontou 2024 Sec. 3.2: absolute / state-independent QEIs do not reach T_split of the non-minimally coupled field; only state-dependent bounds exist",
"source":{
 "located":"arXiv:2405.05963, E.-A. Kontou, 'Wormhole restrictions from quantum energy inequalities', Universe 10 (2024) 291, Sec. 3.2 -- LOCATED BY ID ONLY IN THIS STAGE. The sentence the tree quotes could not be re-read: all four alphaXiv calls (answer_pdf_queries x3, get_paper_content x1) and the discover_papers call returned 'alphaXiv assistant quota exceeded', and direct arxiv.org / export.arxiv.org / www.alphaxiv.org / api.semanticscholar.org / inspirehep.net are refused by the egress proxy (403, organization policy; not routed around). No cached copy of 2405.05963 exists in scratchpad/d67/src. The CONTENT of the sentence was instead checked against the primary sources it rests on, READ from cached arXiv extractions: Fewster & Osterbrink arXiv:0708.2450v2 (Kontou's [30]) -- abstract, Sec. 1, eq. (7), Sec. 5 opening, Sec. 6 conclusion (src/0708.2450.txt lines 16-125, 255-300, 2425-2450, 3808-3850); Fliss-Freivogel-Kontou-Pardo Santos arXiv:2309.10848 (Kontou's [17]) -- Sec. IV opening, eqs. (54)-(59) incl. the NMC point-split operator (55) (src/2309.10848.txt lines 2320-2660); Fewster & Smith gr-qc/0702056v3 -- Sec. 2.2 on NMC and eq. (80) for the minimally coupled T_split (src/0702056.pages.txt lines 125-200, 990-1026, 2415-2440). Kontou's [29] is not identified here.",
 "read_status":"NAMED-NOT-READ",
 "via":"Kontou's own wording is known here only through the tree's quotation (qeihps.py:318-322, recorded READ by DOCKET 64); this stage could not re-read it (alphaXiv quota exhausted; arXiv host blocked by egress policy). What was READ this stage are the cited primary sources [30] (FO 0708.2450) and [17] (FFKP 2309.10848), and Fewster-Smith gr-qc/0702056, from cached arXiv text extractions of earlier runs in this session. They are earlier works, not restatements of Kontou, so the Kontou passage is marked NAMED-NOT-READ, not READ-VIA-RESTATEMENT."
},
"published_statement":"NOT RE-READ THIS STAGE. As the tree quotes it (qeihps.py:319-322, KONTOU_ON_ABSOLUTE_FOR_NMC): 'This is not true, for example, for the T_split operator of nonminimally coupled fields, so these inequalities cannot be used in this case. State-dependent bounds have been derived for the nonminimally coupled field [17,29,30].' The antecedent of 'This' is not quoted in the tree. From the primary sources READ, the property that fails is the one Fewster-Smith's absolute QEI rests on: FS eq. (80) writes the minimally coupled point-split energy density as a symmetric sum of squares, T_split = 1/2 sum_alpha e_alpha^a nabla_a (x) e_alpha^b nabla_b (+ 1/2 mu^2), and FS Sec. 2.2 say 'our argument relies crucially on being able to write T_split in a symmetric form ... A similar problem arises for the non-minimally coupled scalar field. In this case one must smear the stress-energy tensor even to obtain an inequality on the classical field [21], which necessitates a more complicated analysis at the quantum level [22].' FO 0708.2450 abstract: 'By an explicit example, we show that such averages are unbounded from below on the class of Hadamard states ... Nonetheless, we derive a generalised QEI for the non-minimally coupled scalar field, in which the lower bound is permitted to be state-dependent. This result applies to general globally hyperbolic curved spacetimes for coupling constants in the range 0 < xi <= 1/4.' FO Sec. 6: '(at least for massless fields in four-dimensional Minkowski space) ... with xi > 0 admits states with arbitrarily large negative energy density over arbitrarily large bounded spacetime regions. Thus the non-minimally coupled field cannot obey QEIs of the type previously studied in the literature, in which there is a state-independent lower bound' and '... our general QEI is of the so-called difference type ... This restriction has recently been removed for the minimally coupled field in [31] to obtain an absolute QEI; one would expect that this can also be adapted to the non-minimally coupled field.' FFKP Sec. IV: 'the derivation is for a difference QEIs unlike the absolute one that was possible for the minimally coupled field. Importantly, the strongest bound we will be able to derive is state-dependent'.",
"published_hypotheses":[
 "(Kontou, as quoted) the operator is T_split of a NON-MINIMALLY coupled scalar (xi != 0); the failing property is the one 'these inequalities' (the preceding QEI derivations of Sec. 3.2) require -- antecedent not quoted in the tree and not re-read here",
 "(FS gr-qc/0702056, READ) the absolute QEI needs T_split in a symmetric sum-of-squares (positive-type) form; minimal coupling, (nabla^2+mu^2)phi=0, 4D globally hyperbolic, Hadamard states",
 "(FO 0708.2450 Sec. 3/6, READ) the no-go for ANY state-independent bound: xi > 0, massless, four-dimensional Minkowski space ('at least for massless fields in four-dimensional Minkowski space'); not proved for xi < 0, m > 0, or curved backgrounds",
 "(FO Thm 4.2, READ) state-dependent DIFFERENCE QEI: 0 < xi <= 1/4, timelike geodesic, globally hyperbolic curved spacetime, Hadamard states, normal ordering against a reference Hadamard state",
 "(FFKP Thm IV.1, READ) state-dependent DIFFERENCE null QEI, any xi, curved globally hyperbolic, small sampling domain, Hadamard states",
 "(FO Sec. 6, READ) an ABSOLUTE (Hadamard-parametrix) version for NMC is expected ('can also be adapted') -- i.e. absoluteness is not excluded, only not yet done; absolute and state-independent are different properties"
],
"hypothesis_drift":[
 "qeihps.py:46-47 paraphrases Kontou as saying 'no absolute or state-independent inequality reaches this field'. The quoted sentence says 'these inequalities cannot be used' -- the positive-type (FS-class) derivations. FO Sec. 6 (READ) expects an ABSOLUTE but state-dependent QEI for NMC to be adaptable, so 'no absolute inequality' is broader than the source: DROPPED QUALIFIER 'of the Fewster-Smith sum-of-squares class'. The tree's own record at qeihps.py:90 and 511 (ABSOLUTE_QEI_FOR_NMC = 'NOT-FOUND ... can also be adapted (expected, not done)') carries the correct scope, so this drift is in one prose line and does not reach a value.",
 "canonical.json name for this key: 'only state-dependent bounds exist'. Kontou (as quoted) says state-dependent bounds 'have been derived', not that only such bounds can exist. The non-existence of any state-independent bound is FO Sec. 3's result, with hypotheses xi > 0, massless, 4D Minkowski (READ); the canonical hypothesis list ('xi != 0', 'T_split') DROPS 'xi > 0', 'm = 0' and 'Minkowski' for the non-existence reading. The owner file keeps them (qeihps.py:86-90: 'FOR THE MASSLESS FIELD IN 4D MINKOWSKI SPACE ... it is NOT proved on HPS's curved background'), so the drift is in the canonical summary, not in qeihps.py's values.",
 "status_word 'READ' at qeihps.py:318-322: consistent with DOCKET 64's record, but NOT re-verified in this stage (source unreachable). Not a drift; an unverified attribution.",
 "No drift found in the rests_on_it values: FEWSTER_SMITH_ON_HPS (qeihps.py:500) refuses FS on the minimal-coupling hypothesis FS state themselves (READ), and ABSOLUTE_QEI_FOR_NMC (qeihps.py:511) -> specthm.py:1043-1044 (R6) says NOT-FOUND/expected, which matches FO Sec. 6."
],
"data_at_publication":[
 {"quantity":"none -- the result is a structural statement about the form of the point-split stress operator and about which QEI derivations apply; no measured or fitted number enters its conclusion","value_then":"n/a","value_now":"n/a","source_now":"n/a","moves_conclusion":"no -- the coupling xi enters only through its sign / non-vanishing (re-derivation C, D'), and HPS's xi = 1/6 is a model choice (gr-qc/9701064, conformal coupling), not a measurement"}
],
"rederivation":{
 "method":"z3",
 "script_path":D+"/rederive/2405.05963-sec3.2.py",
 "outcome":"ALL PASS (9/9), sympy 1.14.0 + z3 5.1.0. A: for xi = 0 the classical T_00 equals FS eq. (80)'s sum of squares 1/2 sum_a (e_a phi)^2 + 1/2 m^2 phi^2 exactly (sympy). B: from FO eq. (7), T_00 = 1/2 phidot^2 + (1/2 - 2xi)|grad phi|^2 - 2 xi phi Lap(phi) + m^2 phi^2/2 in flat coordinates (sympy; at a point in Riemann normal coordinates every curvature term multiplies phi^2 and is carried as a free K). C1: z3 proves UNSAT that some (xi != 0, K) makes rho >= 0 for every jet -- i.e. for every xi != 0 and every curvature/mass value there is Cauchy data with classical rho < 0 at the point; C1' explicit witness L = (K+1)/(2 xi) gives rho = -1 exactly (anti-vacuity); C2: z3 proves xi = 0, K >= 0 imply rho >= 0 (the positive side holds, so the check is not vacuous); C3: the (phi, Lap phi) block has eigenvalues +-xi, indefinite for xi != 0. D: at HPS's xi = 1/6 the datum phi = A(1 + c r^2) (times a bump) gives rho(0) = -2 c A^2 < 0; D': for general xi, rho(0) = -12 xi c A^2. Since a sum-of-squares T_split forces classical rho >= 0 (by hand: rho = sum_i (P_i phi)^2), C is the contrapositive: the NMC T_split is NOT of the positive-type form the FS / Fewster-type derivations use, for EVERY xi != 0 (both signs) and in any spacetime -- which is what the quoted sentence asserts. NOT re-run: FO Sec. 3's quantum no-go (a Hadamard-state construction; READ, not re-derived) and the exact wording of Kontou Sec. 3.2.",
 "agrees_with_source":"partly"
},
"later_literature":[
 {"ref":"C. J. Fewster & L. W. Osterbrink, arXiv:0708.2450 (J. Phys. A 41 (2008) 025402) -- Kontou's [30]","effect":"confirms","what":"Primary source of the claim: no state-independent bound for xi > 0, massless, 4D Minkowski (explicit Hadamard-state family); state-dependent difference QEI for 0 < xi <= 1/4 on globally hyperbolic curved spacetimes; an absolute version 'can also be adapted' (expected, not done). Earlier than Kontou; read as a primary source, not as later literature.","read_status":"READ (cached arXiv extraction src/0708.2450.txt, abstract, Secs. 1, 2, 5, 6)"},
 {"ref":"J. R. Fliss, B. Freivogel, E.-A. Kontou, D. Pardo Santos, arXiv:2309.10848 -- Kontou's [17]","effect":"confirms","what":"Writes the NMC T_split explicitly (eq. 55): the xi terms include -2 xi 1 (x)_s (nabla nabla + 1/2 R) and a (1-4xi) g (m^2 + xi R) 1(x)1 term, not a sum of squares; derives a DIFFERENCE, state-dependent null QEI for any xi, noting 'unlike the absolute one that was possible for the minimally coupled field'.","read_status":"READ (cached arXiv extraction src/2309.10848.txt lines 2320-2660)"},
 {"ref":"C. J. Fewster & C. J. Smith, gr-qc/0702056 (Ann. Henri Poincare 9 (2008) 425)","effect":"confirms","what":"The absolute QEI rests on writing T_split in symmetric sum-of-squares form (eq. 80); Sec. 2.2 says the NMC field needs smearing even classically and 'a more complicated analysis at the quantum level'.","read_status":"READ (cached alphaXiv page text src/0702056.pages.txt)"},
 {"ref":"discover_papers search for post-2024 absolute or state-independent QEIs for the NMC field","effect":"contested","what":"NOT PERFORMED: the discover_papers call returned 'alphaXiv assistant quota exceeded'. Whether an absolute (state-dependent) NMC QEI has since been published -- which would narrow qeihps.py:46-47's 'no absolute inequality' further and could change ABSOLUTE_QEI_FOR_NMC = NOT-FOUND -- is unknown here. Recorded as a gap, not as evidence either way.","read_status":"NAMED-NOT-READ (search not run; quota)"}
],
"lacked_data":"M's hypothesis tested for this result. The result contains no measured datum: it is a statement about the algebraic form of the point-split stress operator (whether it is a sum of squares) and about which proof techniques apply. EVIDENCE AGAINST a missing-data defect: the failure of positivity is re-derived here from the classical stress tensor alone (z3, for every xi != 0 and every value of the curvature/mass coefficient K), so no future measurement of xi, m or the background could restore the sum-of-squares form -- only xi = 0 exactly does. EVIDENCE FOR M's direction (incompleteness, not error): what the literature lacks is a THEOREM, not data -- FO (2007/8) state an absolute NMC QEI 'can also be adapted' but do not do it; the FO no-go for state-independent bounds is proved only for xi > 0, massless, 4D Minkowski, so for xi < 0, massive fields and curved backgrounds (HPS's) the non-existence of a state-independent bound is not established, only the non-applicability of the positive-type method. That incompleteness is already carried by the tree (qeihps.py:86-90, 511) and the specthm R6 text; it does not change FEWSTER_SMITH_ON_HPS (FS is refused on minimal coupling, independent of this sentence) nor ABSOLUTE_QEI_FOR_NMC (NOT-FOUND). EFFECT ON THE TREE'S CONCLUSIONS: none in either direction.",
"grade":"NARROWED",
"grade_evidence":"The mathematical content of the quoted sentence STANDS and is machine-checked: the NMC point-split energy density is not of the sum-of-squares form (z3 C1/C1', for every xi != 0 and any curvature/mass coefficient; sympy D gives rho(0) = -2cA^2 < 0 at HPS's xi = 1/6), while at xi = 0 it is exactly FS eq. (80) (sympy A, z3 C2); FO and FFKP (READ) do derive state-dependent bounds. It is NARROWED as the tree phrases it in two places: (i) qeihps.py:46-47 'no absolute or state-independent inequality reaches this field' drops the qualifier that it is the FS positive-type class that fails -- FO Sec. 6 (READ) expects an absolute, state-dependent NMC QEI to be adaptable; (ii) the canonical key name 'only state-dependent bounds exist' for xi != 0 is broader than what is proved -- non-existence of any state-independent bound is FO's theorem for xi > 0, massless, 4D Minkowski only. Neither narrowing reaches a value the tree uses: qeihps.py:86-90 and 511 carry FO's scope, FEWSTER_SMITH_ON_HPS rests on FS's own minimal-coupling hypothesis, and specthm R6 quotes ABSOLUTE_QEI_FOR_NMC = NOT-FOUND. Not WRONG: nothing is contradicted. Caveat on the attribution: the verbatim Kontou wording and the antecedent of 'This' were NOT re-read this stage (alphaXiv quota exhausted, arXiv hosts refused by egress policy), so the attribution rests on DOCKET 64's recorded reading; any wording difference found on re-read is a discrepancy to record, not a refutation.",
"what_would_change_the_grade":"To STANDS: qeihps.py:46-47 reading 'no absolute QEI of the Fewster-Smith (sum-of-squares) type and no state-independent QEI is known to reach this field', and the canonical summary carrying FO's 'xi > 0, massless, 4D Minkowski' for the non-existence reading -- plus a re-read of Kontou Sec. 3.2 confirming the quotation and its antecedent. To OPEN: a re-read showing Kontou's 'This' refers to something other than the positivity / symmetric form of T_split (then the attribution is unsupported, though the physics checked here still holds). Further NARROWED (still not WRONG): a post-2024 paper deriving an absolute or state-independent QEI for NMC fields on a class containing HPS -- that would also flip ABSOLUTE_QEI_FOR_NMC from NOT-FOUND and would need its own audit. To WRONG: a sum-of-squares decomposition of the xi != 0 T_split, which re-derivation C shows cannot exist.",
"reverify_command":"python3 /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/rederive/2405.05963-sec3.2.py && grep -n 'at least for massless\\|can also be adapted\\|unbounded from below' /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/src/0708.2450.txt && grep -n 'difference QEIs unlike the absolute' /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/src/2309.10848.txt && sed -n 46,50p /home/user/Claude-Method-Works/research/warp-drive/qeihps.py && sed -n 86,90p /home/user/Claude-Method-Works/research/warp-drive/qeihps.py && sed -n 511,512p /home/user/Claude-Method-Works/research/warp-drive/qeihps.py  # and, when alphaXiv quota returns: answer_pdf_queries(paper='2405.05963', queries=['Sec. 3.2 paragraph with T_split of nonminimally coupled fields and the sentence before it','refs [17],[29],[30]'])",
"report_path":D+"/audits/2405.05963-sec3.2.json"
}
json.dump(R,open(R["report_path"],"w"),indent=1,ensure_ascii=False)
print("ok")
