import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R=D+"/rederive/gr-qc_0209075_flat-exterior-scope.py"
rep={
"key":"gr-qc/0209075#flat-exterior-scope",
"name":"AMM flat-space analysis Fourier-transforms over all of Minkowski space (IV,(4.2)-(4.5)) -- used to decline transfer to a shell-bounded flat exterior",
"source":{
 "located":"arXiv:gr-qc/0209075 v1 (21 Sep 2002), Anderson, Molina-Paris & Mottola, 'Linear Response, Validity of Semi-Classical Gravity, and the Stability of Flat Space' (LA-UR-02-5809); PRD 67, 024026 (2003) per the owner. Sec. IV 'Stability of Flat Spacetime' pp.10-13: eq. (4.1), the Fourier sentence between (4.3) and (4.4), (4.2)-(4.5b), (4.6), p.12 k=0 global-mode paragraph; abstract p.1; Sec. V p.13-14.",
 "read_status":"READ",
 "via":"alphaXiv full-text layer of v1, saved earlier in this pass (13:38 today) by the sibling stage gr-qc_0209075_flat-scalar-and-conclusion to d67/amm_0209075.txt; Sec. IV, Sec. V and the abstract were read from it in THIS stage, and the load-bearing sentences are asserted verbatim by the re-derivation script. In this stage alphaXiv answer_pdf_queries, get_paper_content and discover_papers each returned 'alphaXiv assistant quota exceeded', and arxiv.org is refused at the egress proxy (CONNECT 403), so no fresh page-image read was possible. The text layer maps Greek letters to control characters and drops some minus signs; no conclusion here depends on a sign or a Greek letter."
},
"published_statement":"Sec. IV p.10: 'Flat spacetime is a solution of the semi-classical Einstein equations for vanishing expectation value of T_ab and cosmological term, with the quantum matter field in its Lorentz invariant vacuum ground state.' 'The linear response equation (3.4) around a Minkowski background, eta_ab, can be decomposed ...' giving (4.1), whose right side is the retarded non-local term (1/2) Int d^4x' Pi^(ret)cd_ab(x;x') h_cd(x'). (4.2): Kallen-Lehmann spectral representation of the Fourier transform Pi^(i)(ret)(k^0, vec k) = Int dw rho^(i)(w, vec k)/(w - k^0 - i eps), i = T,S. Between (4.3) and (4.4): 'In Fourier space the non-local real convolution in eq.(4.1) becomes a simple multiplication with h_cd(k).' (4.4): three subtractions at k^2 = 0. (4.5a)/(4.5b): the tensor and scalar dispersion formulae in k^2. p.12: 'The possibility of a finite number of non-propagating (global) modes in the scalar sector at k = 0 cannot be excluded by this argument, and must be investigated by imposing appropriate boundary conditions at spatial infinity. We do not treat this possibility in this paper.' Abstract: 'the flat space solution to the semi-classical Einstein equations for n = 4 is stable to all perturbations on distance scales much larger than the Planck length.' Sec. V p.14: '... a completely satisfactory stability of flat space for all local perturbations obeying the inequality (4.6).' Nothing in the paper treats a bounded, shell-bounded, or partially flat region (the words 'shell', 'cavity', 'bounded region', 'finite region', 'Dirichlet', 'Robin' do not occur; checked).",
"published_hypotheses":[
 "S1 background: Minkowski spacetime eta_ab, a solution of (2.9) with <T_ab> = 0 and Lambda = 0 (p.10)",
 "S2 state: the quantum matter field in its Lorentz (Poincare) invariant vacuum ground state (p.10; abstract 'vacuum state of Minkowski spacetime') -- this is what makes Pi^(ret)(x;x') depend on x - x' only and admit the Kallen-Lehmann form (4.2)",
 "S3 the response integral in (4.1) runs over all x' with retarded (causal) support (theta(t - t'), p.9) -- in Fourier space over (k^0, vec k) in R^4, where convolution becomes multiplication (p.10)",
 "S4 large-N free scalar field(s), arbitrary m > 0 and xi; for the tensor positivity step only positivity of rho^(T) is used ('causality, a bounded Hamiltonian, and a well-defined positive Hilbert space norm', p.11) -- generality over MATTER, not over domain",
 "S5 renormalised Lambda, 1/G_N, alpha, beta fixed by subtraction at k^2 = 0 (4.4)",
 "S6 O(1) fourth-order coefficients for the 'Planck-scale only' conclusion (p.12, V p.14)",
 "S7 k = 0 global scalar modes excluded from the analysis; they would need boundary conditions at spatial infinity (p.12)"
],
"hypothesis_drift":[
 "DROPPED (not load-bearing for the tree's use): S2, the Poincare-invariant vacuum. linstab.py:87-91 names 'the global Poincare vacuum' for GMMPS but, for AMM, cites only the Fourier transform over all Minkowski. S2 is a second, independent reason AMM does not transfer to a shell exterior (the state outside a shell is not in general the Minkowski vacuum). Omitting it understates the decline; it does not enlarge any use of AMM.",
 "DROPPED (not load-bearing): S3's retarded support. At an exterior event the integral over x' in (4.1) runs over the causal past, which meets the shell world-tube (script check E). A third independent reason for the decline, not named at linstab.py:86-92.",
 "DROPPED (not load-bearing): S7. AMM's own global-mode caveat needs boundary conditions at spatial infinity; a shell exterior adds an inner boundary at R_s that AMM do not treat. Again this supports the decline.",
 "CITATION SCOPE (discrepancy, not an error): linstab.py:88 cites '(IV, (4.2)-(4.5))'. The x-space convolution is (4.1), and the sentence that performs the Fourier step is unnumbered and sits between (4.3) and (4.4). (4.2)-(4.5b) are the Fourier-space formulae, so the citation is accurate for what it names; '(4.1)-(4.5)' would be complete.",
 "WORDING, read carefully against over-reading in M's favour: linstab.py:91-92 'neither \"stable\" nor \"unstable\" transfers to it' is supported only as 'is not inherited from AMM's proof' (the pin's own name, FLAT_EXTERIOR_INHERITS_AMM = False, linstab.py:341, printed as a record pin at 1049-1050). It is NOT supported as 'the verdict is false there'. Script control D3 shows a toy instability surviving on an unbounded exterior with a wall. The tree does not assert the stronger reading, so this is not drift, but it must not be quoted that way.",
 "NOT DRIFT: AMM's abstract ('stable to all perturbations on distance scales much larger than the Planck length') and V p.14 ('all local perturbations obeying (4.6)') are worded more broadly than the domain of the proof. There 'local' qualifies the k-space inequality (4.6), not a spatial region. The tree follows the proof's domain, not the gloss."
],
"data_at_publication":[],
"rederivation":{
 "method":"sympy",
 "script_path":R,
 "outcome":"36 checks, 0 failed. A (19): the load-bearing sentences are verbatim in AMM's text layer: the Lorentz-invariant vacuum, 'around a Minkowski background', (4.1) as a retarded convolution over x', 'In Fourier space the non-local real convolution in eq.(4.1) becomes a simple multiplication', the labels (4.2), (4.5a), (4.5b), 'boundary conditions at spatial infinity ... We do not treat this possibility', the abstract and V gloss, and the p.11 matter-generality clause. No bounded-region, shell, cavity, Dirichlet or Robin treatment occurs. B (4): the owner's statement is at linstab.py:86-92, the pin at :341, and it is a record() at :1049, not a chk(). C (3, numpy): a translation-invariant retarded kernel on a translation-invariant (periodic) lattice is diagonalised EXACTLY by plane waves (max residual 3e-13, eigenvalue = Fourier symbol). The same kernel on a region bounded at one end (Toeplitz block) leaves a plane-wave residual of 4.14 and its spectrum collapses to kern[0], not the symbol. So AMM's 'convolution -> multiplication' step needs S2+S3 and fails on a bounded region. D (exact, sympy): D1, the full-line wave equation is Fourier-stable, yet on the half-line exterior x > R with a wall condition u_x(R) = -kappa u(R), the L^2 mode e^{kappa(t-(x-R))} grows at rate kappa, so 'stable' is not inherited. D2, the full-line tachyonic equation is Fourier-unstable, yet on an interval of length pi/(2 mu) with Dirichlet walls every mode is stable, so 'unstable' is not inherited on a bounded region. D3 CONTROL, on an unbounded half-line exterior with Dirichlet at R the tachyonic instability SURVIVES, so the decline means 'must be computed afresh', not 'fails'. E: the causal past of every exterior event meets the shell world-tube, so (4.1)'s retarded integral at an exterior point runs over the non-flat region. The toys are illustrations of the logic, not models of the semiclassical device.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"arXiv:2604.01047 v1, Galanda, Meda, Murro, Pinamonti & Schmid (GMMPS), 'The semiclassical Einstein-Klein-Gordon system: asymptotic analysis of Minkowski spacetime'",
  "effect":"extends",
  "what":"A rigorous treatment of the same question (AMM's successor in the tree). Per the owner's READ at linstab.py:87-91 and 130-135 it is posed on (R^4, eta) with the global Poincare vacuum and past-compact perturbations of all of R^4 (their 1.2, Thm 1.2). So the one later rigorous result the tree holds is also global, which confirms rather than narrows the scope point.",
  "read_status":"NOT re-read in this stage (alphaXiv quota exceeded). Setting taken from the owner linstab.py:87-91 and 130-135 and from sibling audits d67/audits/2604.01047_*.json, one of which (2604.01047_thm3.6) read pp.1,7,9,22,23,31-33,35,37,40,62 at alphaXiv in this pass. Tracked under its own keys."},
 {"ref":"Mazur & Mottola, Nucl. Phys. B 341, 187 (1990) -- AMM ref. [54]",
  "effect":"confirms",
  "what":"Per AMM p.12, the source of the conformal (xi = 1/6) scalar-sector flat-space stability result (their eq. (4.13)), which AMM reproduce via (4.12). It is the same global-Minkowski, Fourier-space setting and gives no bounded-region analysis, as AMM describe it.",
  "read_status":"NAMED-NOT-READ; restated by AMM p.12 (READ-VIA-RESTATEMENT of what AMM say it contains)"},
 {"ref":"discover_papers search for later work on local or bounded-region semiclassical stability of flat space",
  "effect":"contested",
  "what":"NOT RUN TO COMPLETION: the call returned 'alphaXiv assistant quota exceeded'. No later paper that transfers AMM's verdict to a bounded or shell-exterior flat region has been found OR excluded in this stage. This row records the gap and makes no claim about the literature.",
  "read_status":"search refused (quota)"}
],
"lacked_data":"M's hypothesis asked of this result: what did AMM lack, and would having it change the conclusion? The result audited here is a SCOPE fact about AMM's proof (the domain, state and kernel it assumes), not a numerical conclusion. No datum enters it: no measured constant, no fitted value. What AMM lacked for the tree's case is not data but a PROBLEM they did not pose: a flat region bounded by a shell, in the state the shell induces, with the retarded kernel reaching into the shell's world-tube. The paper says as much. It treats the Minkowski vacuum on eta_ab (p.10), leaves global k = 0 modes to 'boundary conditions at spatial infinity' (p.12), and lists curved and horizon backgrounds as future applications (V, pp.13-14). Evidence either way: (i) AMM make no bounded-region claim that could be wrong, so the conclusion is not moved by anything learned since. (ii) The later rigorous work the tree holds (GMMPS 2604.01047) is again posed on all of R^4, so the gap is still unfilled, not filled against AMM. (iii) The toy controls show that the missing computation could come out either way (D1 stable->unstable, D2 unstable->stable, D3 unstable survives). So nothing here is a defect in AMM. It is an absent calculation, and M's 'lacked certain data' does not apply to this item: its conclusion carries no datum that could have moved.",
"grade":"STANDS",
"grade_evidence":"The published statement and hypotheses support the tree's use. AMM's flat-space analysis is posed around a Minkowski background eta_ab with the matter field in its Lorentz-invariant vacuum (p.10). Its (4.1) response is a retarded convolution over x', which 'In Fourier space ... becomes a simple multiplication' (p.10), and (4.2)-(4.5b) are Fourier-space formulae in (k^0, vec k) and k^2. No bounded or shell-bounded region is treated anywhere, and the global k = 0 modes are left to boundary conditions at spatial infinity (p.12). All of this is asserted verbatim by the script. The re-derivation agrees: plane waves diagonalise a translation-invariant kernel exactly on a translation-invariant domain and fail on a region bounded at one end (residual 3e-13 vs 4.14). Exact toy models show that both 'stable' and 'unstable' can fail to be inherited when a wall is added. The tree uses the result only NEGATIVELY: FLAT_EXTERIOR_INHERITS_AMM = False, a record pin, not a check that can fail. The hypotheses it omits (Poincare vacuum, retarded past support, global-mode boundary condition) are further reasons for the same decline, so none narrows it. No datum is involved, so none can have moved. Recorded, not repaired: (a) the citation '(IV, (4.2)-(4.5))' leaves out (4.1) and the unnumbered Fourier sentence, which is a completeness note, not an error. (b) 'neither stable nor unstable transfers' holds only as 'not inherited from the proof'. Control D3 shows an instability can survive on an unbounded exterior, so the line must not be quoted as 'the flat exterior is known to be unstable' or 'known not to be stable'.",
"what_would_change_the_grade":"NARROWED or WRONG would need a published result that establishes AMM's (or GMMPS's) verdict for a flat region bounded by a shell, or more generally for a locally flat region in a non-Minkowski state. Examples: a local or microlocal stability theorem for semiclassical gravity whose hypotheses a shell exterior meets, or a proof that AMM's Fourier-space dispersion relation governs perturbations supported away from the shell up to controlled errors. Such a result would make 'does not inherit' stale for that class. The later-literature search that could find one was refused here (alphaXiv quota), so a completed discover_papers run over 'local stability semiclassical gravity / bounded region / Hadamard state perturbation' is the open item. A fresh page-image read of AMM pp.10-14 contradicting the text layer's sentences would also reopen it. No datum can change it.",
"reverify_command":"python3 "+R+" && cd /home/user/Claude-Method-Works/research/warp-drive && python3 linstab.py --selftest | grep -n 'FLAT_EXTERIOR_INHERITS_AMM\\|checks that can fail' && sed -n 86,92p linstab.py",
"report_path":D+"/audits/gr-qc_0209075_flat-exterior-scope.json"
}
json.dump(rep,open(rep["report_path"],"w"),indent=1,ensure_ascii=False)
print("ok")
