import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S=D+"/rederive/static-spherical-radial-metric.py"
rep={
"key":"static-spherical-radial-metric",
"name":"Radial metric of a static spherically symmetric spacetime, g_rr = 1/(1-2m(r)/r)",
"source":{
 "located":"Classic textbook form, no single originating paper. Read at source in two arXiv papers that state it exactly: (a) S. A. Hayward, 'Gravitational energy in spherical symmetry', PRD 53, 1938 (1996), arXiv gr-qc/9408002v2, p.4 eq.(4): 'The Misner-Sharp spherically symmetric gravitational energy ... may be defined in units G = 1 by E = (1/2) r (1 - g^{-1}(dr,dr))' ... 'Note that E is an invariant'; p.3: 'The area of a symmetric sphere is 4 pi r^2, so that r is the areal radius'; p.12 eq.(27): '1 - 2E/r = e^{-lambda}(r')^2 - rdot^2, which is the form actually given by Misner & Sharp [4]'. (b) M. Visser, 'Dirty black holes: Entropy versus area', PRD 48, 583 (1993), arXiv hep-th/9303029v2, p.3 eq.(3): 'In any static spherically symmetric asymptotically flat spacetime the metric g_L may without loss of generality be cast into the form ds^2 = -e^{-2phi(r)}(1 - b(r)/r) dt^2 + dr^2/(1 - b(r)/r) + r^2(dtheta^2 + sin^2 theta dphi^2)', with b(infinity) = 2GM and eq.(5) b' = 8 pi G rho r^2.",
 "read_status":"READ",
 "via":"alphaXiv answer_pdf_queries on gr-qc/9408002v2 (pp.1-4, 7-10, 12-13, 16-17, 19, 21) and hep-th/9303029v2 (pp.1-17, full). Misner & Sharp, Phys. Rev. 136, B571 (1964) is NAMED-NOT-READ (no arXiv copy; its form is quoted by Hayward eq.27). Combining (a) with the static diagonal form (b): g^{rr} = 1/g_rr and E = (r/2)(1 - g^{rr}) give g_rr = 1/(1 - 2m/r) with m = E, re-derived symbolically (C1a)."
},
"published_statement":"Hayward gr-qc/9408002 eq.(4): 'E = (1/2) r (1 - g^{-1}(dr,dr))' in units G = 1, 'an invariant', r the areal radius (area 4 pi r^2); Prop.1: 'A metric sphere is trapped iff E > r/2, marginal iff E = r/2, and untrapped iff E < r/2'; p.8: 'E may be negative, as in the negative-energy Schwarzschild solution'; Prop.6: 'If the dominant energy condition holds on an untrapped spatial hypersurface with regular centre, then E >= 0'. Visser hep-th/9303029 eq.(3): 'In any static spherically symmetric asymptotically flat spacetime the metric may without loss of generality be cast into the form ds^2 = -e^{-2phi}(1 - b/r)dt^2 + dr^2/(1 - b/r) + r^2 dOmega^2'; eq.(5) 'b' = 8 pi G rho r^2'; 'This metric has putative horizons at values of r satisfying b(r_H) = r_H.' With b = 2m (G = 1) this is the tree's radial part dr^2/(1 - 2m(r)/r), and proper radial length on a t = const slice dl = dr/sqrt(1 - 2m/r).",
"published_hypotheses":[
 "spherical symmetry (warped product, round spheres of area 4 pi r^2; r = areal radius) -- Hayward p.2-3",
 "static: a hypersurface-orthogonal timelike Killing vector, so the metric is diagonal in (t, r) and t = const slices are Killing-orthogonal -- Visser eq.(3)",
 "r usable as a coordinate: dr != 0 (g^{-1}(dr,dr) != 0), i.e. away from marginal spheres 2m = r (Visser: 'putative horizons at b(r_H) = r_H'); in the static region 1 - 2m/r > 0",
 "asymptotic flatness -- Visser eq.(3); used only to normalise phi(infinity) = 0 and identify b(infinity) = 2GM, not for the local form of g_rr",
 "units G = 1 (Hayward), c = 1 (Visser keeps G explicit: b = 2Gm)",
 "no energy condition is needed for the DEFINITION; E < 0 is explicitly allowed (negative-energy Schwarzschild), and E >= 0 follows only under DEC + untrapped + regular centre (Hayward Prop.6)"
],
"hypothesis_drift":[
 "ADDED, UNNAMED (wording discrepancy, not a narrowing): overturn.py:79 and 92-94 (and the L3 header at :401) call the L3 measurement 'ansatz-free: no Phi, no Plummer, no shell, just the areal radius and the Misner-Sharp mass', but deficit(m, r1, r2) at overturn.py:413-423 and rate_ratio at :431-433 take a single CONSTANT m on [r1, r2]. By Visser eq.(5) / C1b (m' = 4 pi r^2 rho) a constant m means rho = 0 on [r1, r2]: a vacuum region, by Birkhoff (Hayward Prop.4) the negative-mass Schwarzschild exterior. That is an ansatz. It does not narrow the conclusion: C3 proves Delta d <= int_r1^r2 max(0, -m(r))/r dr for EVERY profile m(r) with 1 - 2m/r > 0 (equality only for m = 0), C4 proves the per-unit-|m| return strictly decreasing for any fixed-shape profile m = lambda mu(r), and C7 checks 250 random (including sign-changing) profiles with 0 violations. So the tree's L3 verdict ('the weak-field logarithm is the best case', overturn.py:110-111) holds on the wider class it claims, with |m| ln(r2/r1) generalised to int |m(r)|/r dr.",
 "IMPLICIT, NOT LISTED (load-bearing): the proper length is taken on the Killing-orthogonal slice t = const (overturn.py:403-406 'ds^2 radial part = dr^2/(1 - 2m(r)/r)'). The canonical hypothesis list says 'static' but a static spacetime admits other slices. On a slice t = T(r) the radial length is sqrt(B - A T'^2) dr (C6); Hayward eq.(27) gives dl = dr/sqrt(1 - 2E/r + rdot^2) in general. In FLAT space (m = 0) the slice t = r/2 already gives a 'deficit' of 199(1 - sqrt(3)/2) = 26.66 over [1, 200] against a log bound of 0. The L3 bound is therefore a statement about the static slice only -- consistent with the tree's formula, which presupposes it, but the hypothesis should be named.",
 "DROPPED, HARMLESS: Visser's 'asymptotically flat' (hep-th/9303029 eq.3). The g_rr form is local (Hayward eq.4 is a definition on each sphere), and asymptotic flatness enters only phi(infinity) = 0 and b(infinity) = 2GM, neither used by overturn.py L3.",
 "DROPPED, HARMLESS: 'r is a good coordinate (dr != 0)'. For m < 0, g^{-1}(dr,dr) = 1 - 2m/r > 1, so dr is spacelike and non-zero automatically; the canonical note '2m/r < 1 automatic for m < 0' (overturn.py usage) is correct.",
 "CONTEXT, NOT DRIFT IN THIS RESULT: Hayward Prop.6 -- m < 0 on an untrapped slice with a regular centre requires the dominant energy condition to fail somewhere inside r1 (or the centre to be singular: 'temporal and untrapped if E < 0', abstract). That is the business of overturn.py's L2 link and other audited results, not of the radial-metric identity."
],
"data_at_publication":[
 {"quantity":"G, c (geometric units, m = G M / c^2)","value_then":"not used: the result and the L3 ratio are stated in G = c = 1; the ratio depends only on |m|/r1 and r2/r1","value_now":"not read here (CODATA value of G not needed)","source_now":"n/a -- the conclusion is dimensionless","moves_conclusion":"no: the identity g_rr = 1/(1 - 2m/r) and every L3 ratio are independent of the numerical values of G and c; only the translation of |m| = 1 (length units) into kilograms uses them"},
 {"quantity":"r1 = 1, r2 = 200 (overturn.py:83, 571) -- tree choices, not external data","value_then":"r1 = 1, r2 = 200","value_now":"same","source_now":"overturn.py (read-only import, C8)","moves_conclusion":"no: C3/C4/C5 hold for every 0 < r1 < r2; the numbers only set the table"},
 {"quantity":"the tree's nine measured ratios (overturn.py:87-102), computed by Simpson quadrature","value_then":"1.000000, 1.000000, 0.999972, 0.997206, 0.833100, 0.504993, 0.174544, 0.029831, 0.003505; Dd/(r2-r1) 0.0222, 0.1345, 0.4647, 0.7942, 0.9332","value_now":"closed form (C2, 40 digits): 0.9999999972, 0.9999997183, 0.999971833, 0.9972063882, 0.8330996585, 0.5049932665, 0.1745442344, 0.02983068767, 0.003505097088; Dd/(r2-r1) 0.022181, 0.134453, 0.464719, 0.794233, 0.933222","source_now":"rederive/static-spherical-radial-metric.py C2 (closed-form antiderivative r - sqrt(r(r+2a)) + 2a ln(sqrt r + sqrt(r+2a)), cross-checked by tanh-sinh quadrature to <1e-31)","moves_conclusion":"no: all agree to the printed digits (the |m| = 1e-6 row 0.99999972 prints as 1.000000); tree's 'already 0.28% short' at |m| = 1e-2 is 0.2794%"}
],
"rederivation":{
 "method":"sympy",
 "script_path":S,
 "outcome":"ALL PASS (exit 0). C1a sympy: for diag(-e^{2Phi}, 1/(1-2m(r)/r), r^2, r^2 sin^2) Hayward's invariant E = (r/2)(1 - g^{rr}) = m(r) identically. C1b: from a fresh Einstein tensor, G^t_t = -8 pi rho gives rho = m'/(4 pi r^2) (Visser eq.5, b = 2m; also Choi-Grady 2608.09963 Prop.2.2). C1c: constant m <=> rho = 0 (vacuum). C2: closed-form deficit verified by differentiation; all nine tree ratios and five saturation fractions reproduced (worst relative deviation 2.8e-5, from the tree's 6-digit rounding). C3 z3 (unsat) + sympy: f(x) = 1 - (1+2x)^{-1/2} <= x for all x > -1/2, since with s = sqrt(1+2x) it is s^3 - 3s + 2 = (s-1)^2 (s+2) >= 0; strict for x != 0; vacuity guard sat. Hence Delta d <= int max(0,-m(r))/r dr for ANY profile. C4: f(x)/x = 2/(s(s+1)), strictly decreasing, so the return per unit |m| falls strictly and monotonically (tree's L3 monotonicity, now a proof rather than five sampled points). C5 z3: 0 < f < 1, Delta d < r2 - r1 (saturation). C6: a boosted slice in flat space gives deficit 26.661 > 0 -- the bound needs the Killing-orthogonal slice. C7: 250 random profiles, 0 violations. C8: the tree's own Simpson rate_ratio (imported read-only by path) agrees with the closed form to 2.1e-7.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"C. Choi & R. E. Grady, 'Sharp Tangential NEC Minimization and Israel Surface Layers in Schwarzschild Mass Interpolations', arXiv 2608.09963 (2026)","effect":"confirms","what":"Uses exactly g = -F dt^2 + F^{-1} dr^2 + r^2 dOmega^2, F = 1 - 2m(r)/r, G = c = 1 (p.1-2); Prop.2.2 rho = m'/(4 pi r^2), p_r = -rho (for g_tt g_rr = -1), p_t = -m''/(8 pi r); 'On a static slice, the proper spatial volume element is dV = 4 pi r^2 dr / sqrt(F)' (p.6) -- the same static-slice proper measure the tree uses. Section 8 names its own restriction (g_tt g_rr = -1 forces p_r = -rho) and proposes the e^{2Phi} lapse -- the tree's form already carries that freedom since g_rr does not involve the lapse.","read_status":"READ (alphaXiv, pp.1-3, 5-7, 11, 20-31)"},
 {"ref":"P. Jai-akson & Y. Yokokura, 'Revisiting Spherically Symmetric Spacetime I: Geometro-Hydrodynamics', arXiv 2601.03077 (2026)","effect":"confirms","what":"Eq.(8) Misner-Sharp energy M = ((d-2)/(16 pi G)) A_unit r^{d-3} (1 - (Dr)^2), eq.(9) (Dr)^2 = 1 + 2Phi with Phi = -G M/r in d = 4, eq.(44) 2 rho = (Dr)^2 = 1 - 2GM/r: the same invariant identity in covariant form, valid in dynamical spacetimes; 'for the vacuum and static case, the Misner-Sharp energy reduces to the Schwarzschild mass' (p.10); Birkhoff re-derived (eq.61). Extends to d dimensions and Lovelock gravity (Sec.6), where the MS energy is generalised -- outside the tree's GR, d = 4 use.","read_status":"READ (alphaXiv, pp.1, 4, 8-12, 20-25, 34, 43, 48)"},
 {"ref":"S. A. Hayward, arXiv gr-qc/9408002 (1996)","effect":"confirms","what":"The invariant definition eq.(4) and the general-slice form eq.(27) -- the latter is the source of the named slicing hypothesis (rdot = 0 on the Killing-orthogonal slice).","read_status":"READ (alphaXiv)"}
],
"lacked_data":"This result is a definition plus an exact identity (Hayward eq.4 evaluated on Visser's static diagonal form), not a measurement or an extrapolation, so there is no datum the authors could have lacked: C1a is an identity in m(r) and Phi(r), holding for every profile, and no physical constant enters the L3 ratio (it depends only on |m|/r1 and r2/r1). Evidence against M's hypothesis for THIS result: the 2026 papers (2608.09963, 2601.03077), written with thirty more years of data and formalism, use the same form unchanged, and nothing measured since 1964 bears on it. Evidence that something was incomplete: not in the external result but in the tree's statement of it -- the slicing hypothesis (C6) and the constant-m ansatz (drift 1) were unnamed. Neither changes the conclusion: the static-slice bound is proved for arbitrary m(r) (C3, C4, C7). What would be genuinely new data-dependence is only outside the result's hypotheses: a theory other than GR (where g^{rr} = 1 - 2m/r still defines m geometrically but m is no longer the gravitational energy, cf. 2601.03077 Sec.6 Lovelock), or a non-static configuration, where Hayward eq.(27) adds rdot^2.",
"grade":"STANDS",
"grade_evidence":"The published statement (Hayward eq.4, invariant, G = 1; Visser eq.3, static spherical, 'without loss of generality') gives g_rr = 1/(1 - 2m/r) with m the Misner-Sharp mass on the static region, and C1a re-derives it symbolically as an identity; C1b re-derives m' = 4 pi r^2 rho from a fresh Einstein tensor. The tree's three listed hypotheses (static, spherical, areal r; G = c = 1; 2m/r < 1, automatic for m < 0) are exactly the source's, less asymptotic flatness, which the local identity does not use. The tree's numbers are reproduced to every printed digit by a closed form (C2) and its own routine agrees (C8). The tree's L3 conclusions, which rest on this result, are strengthened rather than weakened: 'the logarithm is the best case' and 'the return falls monotonically' are PROVED here (z3 + sympy: (s-1)^2 (s+2) >= 0 and f(x)/x = 2/(s(s+1))) for arbitrary profiles m(r), not only the constant-m sample. No datum enters. Two things are recorded, not repaired: (i) a wording discrepancy -- 'ansatz-free ... no shell' (overturn.py:92-94, 401) while the code fixes m constant on [r1, r2], i.e. vacuum there (drift 1); (ii) an unnamed but load-bearing hypothesis -- the length is measured on the Killing-orthogonal slice; on a boosted slice even flat space shows a 'deficit' (C6: 26.66 over [1, 200]). Neither is a narrowing of the external result, whose statement already specifies the static t = const radial part; neither moves the tree's conclusion.",
"what_would_change_the_grade":"NARROWED if the tree used the length on a non-Killing-orthogonal slice (dl = dr/sqrt(1 - 2m/r + U^2), Hayward eq.27) or in a region where r is not a coordinate (dr = 0, possible only for m = r/2 > 0), or used the MS identity outside GR / d = 4 while calling m the gravitational energy. WRONG only if C1a failed, i.e. a static spherical metric whose g^{rr} is not 1 - 2E/r -- impossible by Hayward's definition, so this would take an error in the definition itself. The tree's L3 verdict would change only if 'distance bought' were redefined (e.g. against a different comparator than the areal-radius difference r2 - r1, or on a different slice), which is a change of question, not of this result.",
"reverify_command":"python3 "+S,
"report_path":D+"/audits/static-spherical-radial-metric.json"
}
json.dump(rep,open(rep["report_path"],"w"),indent=1)
print("ok", len(json.dumps(rep)))
