import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S = D + "/rederive/expansion-scalar-3h-flrw.py"
r = {
 "key": "expansion-scalar-3h-flrw",
 "name": "Expansion scalar theta = nabla_mu u^mu = 3H for the comoving congruence in FLRW; zero for any volume-preserving flow; coordinate-invariant",
 "source": {
  "located": "Textbook identity (Raychaudhuri 1955 / Ehlers-Ellis 1+3 kinematics). Read at: G.F.R. Ellis & H. van Elst, 'Cosmological models (Cargese lectures 1998)', arXiv:gr-qc/9812046v5 (2 Sep 2008), sec.2.1.2 eq.(11), eq.(25), sec.4.1 eq.(104). Corroborating restatement: S. Kar & S. SenGupta, 'The Raychaudhuri equations: a brief review', arXiv:gr-qc/0611123, eq.(10). The tree itself cites no source for this identity.",
  "read_status": "READ",
  "via": "alphaXiv answer_pdf_queries page text for gr-qc/9812046v5 and gr-qc/0611123, returned in earlier stages of this workflow session and recovered verbatim from the session transcripts into scratchpad/d67/src/casmag/all/ (allpages.py; also src/gr-qc_9812046.harvest.txt). A fresh alphaXiv call this stage returned 'assistant quota exceeded' and arxiv.org is refused by the egress proxy (403), so no new page was fetched; the pages used are verbatim tool output, not a paraphrase."
 },
 "published_statement": "Ellis & van Elst eq.(11): 'nabla_a u_b = - u_a udot_b + (1/3) Theta h_ab + sigma_ab + omega_ab, where the trace Theta = tilde-nabla_a u^a is the rate of volume expansion scalar of the fluid (with H = Theta/3 the Hubble scalar)'. Eq.(25): 'the average length scale S determined by Sdot/S = (1/3) Theta, so the volume of a fluid element varies as S^3.' Sec.4.1, eq.(104), FLRW: 'Matter-comoving local coordinates can be found so that the metric takes the form ds^2 = -dt^2 + S^2(t)(dr^2 + f^2(r) dOmega^2), u^a = delta^a_0 ... Sdot/S = (1/3) Theta, characterising S(t) as the scale factor for distances between any pair of fundamental observers.' Kar-SenGupta eq.(10): for u = d/dt in FLRW 'the shear and rotation are identically zero. The expansion is given as Theta = 3 adot/a = (1/sqrt(a^6)) d/dt sqrt(a^6)'.",
 "published_hypotheses": [
  "H1: u^a is a unit timelike vector field (u^a u_a = -1, eq.(4)) -- the 4-velocity of a chosen congruence; Theta is defined relative to that u^a ('of the fluid'; 'fundamental observers').",
  "H2: Theta = 3H with H = Sdot/S requires the FLRW (Robertson-Walker) geometry, i.e. perfect fluid with udot = sigma = omega = 0 everywhere (eq.(103)), and u^a the matter-comoving congruence u^a = delta^a_0 (eq.(104)).",
  "H3: Theta is the fractional rate of change of the volume of a fluid element along u (eq.(25)); Theta = 0 iff that volume is constant along the flow.",
  "H4 (implicit, 3+1): three spatial dimensions -- the 1/3 in eq.(11) is 1/dim of the rest space (h^a_a = 3, eq.(5)).",
  "H5 (application, not in the identity): the real universe is described by FLRW only on large (homogeneity) scales; the lectures' sec.4 and sec.8 ('almost-FLRW') treat this as an assumption to be justified."
 ],
 "hypothesis_drift": [
  "DROPPED at obstruct.py:270-277 (row EXPANSION-IS-A-RELABELLING): 'the universe has theta = 3 H_0 = 6.549e-18 /s, and theta is coordinate-invariant, so no relabelling moves it' -- drops the congruence qualifier that permute.py:26 carries ('3H for a comoving congruence') and the FLRW qualifier. Theta is a scalar of the PAIR (g, u): SHOWN in rederive E, the static-patch Killing congruence of de Sitter (which IS flat FLRW with a = e^{Ht}, pullback verified) has Theta = 0 exactly at events where the comoving congruence has Theta = 3H, and a tilted congruence in matter-FLRW has Theta != 3H. This does NOT refute 'no relabelling moves it' (a coordinate change / diffeomorphism carries (g,u) and Theta as a scalar -- rederive C(i)-(iii)); it means 'the universe has theta = 3H_0' is a statement about the fundamental-observer (matter/CMB) congruence, a physical choice that permute.py's own hypothesis list admits is 'not itself argued'.",
  "DROPPED at permute.py:26-33 and permute.py:504-506 (scorecard 'the expansion is a permutation: FALSIFIED'): the scale-of-validity hypothesis H5. theta = 3H is the exact-FLRW value; the matter congruence of the real universe has theta ~ 0 inside bound, virialised structures (sibling audit audits/bound-systems-do-not-expand.json; Le Delliou-Mena-Mimoso arXiv:0911.0241, READ: shells separating inner collapsing from outer expanding regions exist where 'the combination of expansion scalar and shear theta + 3a' vanishes). So the falsification holds for the large-scale fundamental-observer flow, not for every sub-volume; the tree states it unqualified as 'THE UNIVERSE IS NOT A PERMUTATION OF A CLOSED INDEX'.",
  "ADDED (tree-internal modelling, not from the source) at permute.py:200-202: 'a permutation of a closed index' is modelled as a measure-preserving flow and its theta is HARDCODED 0.0 (permutation_expansion_scalar returns 0.0). The external identity supports only the conditional 'volume-preserving flow => theta = 0' (eq.(25); rederive D); that a Rubik-type rearrangement IS such a flow is the tree's own declaration, not a computation. Recorded, not repaired.",
  "WEAKENED/implicit at permute.py:196 ('Three, exactly -- one for each spatial direction'): correct for isotropic expansion in 3 spatial dimensions (rederive F: theta = nH in n dimensions); for anisotropic flows theta = H1+H2+H3 and 'one each' describes only the isotropic FLRW case. Not load-bearing.",
  "permute.py:29 labels theta = 3H_0 'Measured, Planck 2018'. H_0 from Planck is a LCDM-FLRW FIT parameter (arXiv:1807.06209), so theta is inferred under H2/H5, not measured independently of them. Recorded as a status-word discrepancy."
 ],
 "data_at_publication": [
  {"quantity": "H_0 (sets the printed theta = 3H_0)", "value_then": "tree: 67.36 km/s/Mpc (Planck 2018, cosmo.py:34) -> theta = 6.549e-18 /s (reproduced 6.548967e-18). Ellis-van Elst (1998/2008) quoted '45 <= H0 <= 80 km/sec/Mpc'.", "value_now": "Planck 2018 67.36 +- 0.54 (6.549e-18 /s); Planck+BAO 67.66 +- 0.42 (6.578e-18); DESI DR2 BAO+BBN 68.51 +- 0.58 (6.661e-18); SH0ES R22 73.04 +- 1.04 (7.101e-18). Values read in cached alphaXiv page text of 1807.06209v4 (lines 1253,1420), 2503.14738v3 (lines 1079,1374), 2112.04510v3 (line 102).", "source_now": "arXiv:1807.06209v4 Table 2/eq.(14); arXiv:2503.14738v3; arXiv:2112.04510v3", "moves_conclusion": "NO for the conclusion (theta != 0): every quoted H0 is >= 70 sigma from zero and the whole 1998 range 45-80 is nonzero. YES for the printed number: it moves by 8.4% across the Hubble tension (6.549e-18 -> 7.101e-18 /s), which is a contested datum, so 6.549e-18 should carry its Planck-LCDM provenance rather than 'Measured'."},
  {"quantity": "spatial dimension (the '3' in 3H)", "value_then": "3", "value_now": "3", "source_now": "identity (h^a_a = 3, Ellis-van Elst eq.(5))", "moves_conclusion": "no"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": S,
  "outcome": "ALL CHECKS PASS (exit 0). A: nabla_mu u^mu = 3 adot/a for u = d/dt in FLRW, k = +1, 0, -1. B: full 1+3 split of nabla_mu u_nu from Christoffels -- acceleration, shear, vorticity identically zero, trace h^mn nabla_m u_n = 3H (k = 0, +1). C: coordinate invariance -- same Theta in conformal time, in proper-radius coordinates R = a r (u^R = HR), and under a generic nonlinear (t,r)->(tau,rho) map with a = t^(2/3) (numeric, rel. err 0; vacuity guard: using the untransformed u gives 1.1007 vs 1.0023, so the check discriminates). D: Theta = d ln sqrt(h)/dt, volume ~ a^3, so Theta = 0 iff volume-preserving. E: congruence dependence -- de Sitter static patch pulls back exactly to flat FLRW a = e^{Ht}; its Killing congruence has Theta = 0 (in static and in FLRW coordinates) while the comoving congruence has 3H; a tilted congruence in matter-FLRW gives Theta - 3H = 0.1897 at a test event. F: Theta = nH for n = 1..5 spatial dimensions. G: 3H0 = 6.549e-18 (tree), 6.578e-18, 6.661e-18, 7.101e-18 /s.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Kar & SenGupta, arXiv:gr-qc/0611123 (2006), eq.(10)", "effect": "confirms", "what": "Theta = 3 adot/a for u = d/dt in FLRW, shear and rotation identically zero; Theta is the volume expansion. The text reads 'a^6 is the volume of the expanding 3-space' where the formula uses sqrt(a^6) = a^3 -- a wording discrepancy in the restatement (formula correct), recorded, not a refutation.", "read_status": "READ (cached alphaXiv page text)"},
  {"ref": "Le Delliou, Mena & Mimoso, arXiv:0911.0241 (2009)", "effect": "narrows", "what": "In spherically symmetric perfect-fluid/LTB-Lambda models matched to FLRW, shells separating an inner collapsing region from an outer expanding one exist where theta + 3a (expansion + shear combination) vanishes; the matter congruence's expansion is not 3H inside such regions. Narrows the SCOPE of 'the universe has theta = 3H' to the homogeneity scale; the identity is untouched.", "read_status": "READ (cached alphaXiv page text, abstract + conclusions)"},
  {"ref": "sibling audit audits/bound-systems-do-not-expand.json (DOCKET 67)", "effect": "narrows", "what": "Bound systems do not partake of the expansion (tidal a''/a effect only, ~1e-69 for atoms), graded STANDS; corroborates that theta_matter ~ 0 in bound structures.", "read_status": "READ (this workflow's own output)"},
  {"ref": "Bolejko, Celerier & Krasinski, arXiv:1102.1449 (inhomogeneous cosmological models review) -- backreaction/averaging", "effect": "contested", "what": "Averaging/backreaction literature questions whether the FLRW H of fits equals the average expansion of the inhomogeneous matter flow; located in cache only by keyword hit, NOT read for a specific claim here. discover_papers returned 'quota exceeded', so no new later-literature search was possible this stage.", "read_status": "NAMED-NOT-READ"}
 ],
 "lacked_data": "The identity Theta = nabla.u = 3H is kinematic (pure differential geometry of a chosen congruence on an FLRW metric); it uses no measured input, so no missing datum can falsify it -- re-derived here in sympy for all three k, in four coordinate systems, with the full shear/vorticity/acceleration split. What 1998-era authors lacked was the value of H0 (Ellis-van Elst give 45-80 km/s/Mpc and a text passage quoting H0 ~ 50) and the Hubble tension; the current values (67.36 Planck, 68.51 DESI DR2+BBN, 73.04 SH0ES) move the printed theta by up to 8.4% but never toward zero, so the tree's conclusion (theta != 0 for the cosmic matter flow) is unaffected. Evidence against M's hypothesis for this result: none of the moved data reaches the conclusion. Where 'incomplete' does apply, it is not missing data but missing scope in the TREE's use: the identity holds for the fundamental-observer congruence of an exact FLRW metric, and the real matter congruence departs from it in bound structures (theta ~ 0) -- known since structure-formation work, READ here in 0911.0241. Discrepancy recorded, not load-bearing: the cached page text of gr-qc/9812046v5 p.23 reads 'globular clusters to about 1.2 x 10^9 years' and 'Hubble time 1/H0 of about 1.8 x 10^9' for H0 ~ 50, whereas 1/(50 km/s/Mpc) = 19.56 Gyr; this may be an extraction artefact of a superscript and MUST NOT be quoted as an error in the lectures until the typeset PDF is read.",
 "grade": "NARROWED",
 "grade_evidence": "The external identity STANDS exactly: Ellis-van Elst eq.(11),(25),(104) re-derived in sympy (A-D, F) -- Theta = 3H for the comoving FLRW congruence for k = 0, +-1, invariant under every coordinate change tried including a generic nonlinear one, and Theta = 0 iff the flow preserves volume; no moved datum (H0 across the tension) moves theta off nonzero. The grade is NARROWED because the tree's use drops two hypotheses the result needs: (1) obstruct.py:270-277 drops 'comoving congruence' -- Theta is a scalar of (g,u), and rederive E SHOWS a congruence in flat-FLRW de Sitter with Theta = 0 exactly (the static Killing observers) at the same events where the comoving one has 3H; (2) permute.py:26-33/504-506 state 'the universe has theta = 3H_0' and 'THE UNIVERSE IS NOT A PERMUTATION' without the homogeneity-scale hypothesis, while the matter congruence has theta ~ 0 in bound structures (sibling audit; arXiv:0911.0241). Neither drop reverses the tree's verdict as a statement about the large-scale fundamental-observer flow: no RELABELLING (coordinate change) moves theta (rederive C), and a change of congruence is a change of physical observer family, not a relabelling. The permutation = measure-preserving-flow step (hardcoded 0.0, permute.py:200-202) is the tree's own modelling declaration, not part of the external result, and is recorded as such.",
 "what_would_change_the_grade": "To STANDS: obstruct.py's row carries 'for the comoving (fundamental-observer) congruence of FLRW' and permute.py names the homogeneity-scale hypothesis (theta = 3H for the cosmic-scale matter flow; ~0 inside bound structures), with 'Measured' replaced by 'Planck-LCDM fit'. To WRONG: a computed coordinate transformation under which the comoving congruence's nabla.u changes value at a fixed event (none exists -- divergence of a vector field is a scalar; rederive C finds none), or an FLRW solution whose comoving congruence has Theta != 3 adot/a. To DATA-DEPENDENT: only if the verdict rested on the numerical value of theta rather than on theta != 0; it does not. OPEN would apply only if the source could not be read; it was read (cached alphaXiv pages).",
 "reverify_command": "python3 " + S + "  # expect 'ALL CHECKS PASS'; source lines: grep -n 'rate of volume expansion scalar\\|S/S = \\|u a = δ' " + D + "/src/casmag/all/gr-qc_9812046v5.txt; tree sites: sed -n 20,35p;190,206p /home/user/Claude-Method-Works/research/warp-drive/permute.py; sed -n 270,280p /home/user/Claude-Method-Works/research/warp-drive/obstruct.py",
 "report_path": D + "/audits/expansion-scalar-3h-flrw.json"
}
json.dump(r, open(r["report_path"], "w"), indent=1, ensure_ascii=False)
print("written", r["report_path"])
