import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R = {
"key": "jacobi-raychaudhuri-ricci-focusing",
"name": "Jacobi / Raychaudhuri (null, Sachs) focusing with the Einstein equation: R_kk = (8 pi G/c^4) T_kk, Ricci-only Jacobi potential q = (4 pi G/c^4) T_kk, conjugate length pi/sqrt(q); 'a conjugate point needs T_kk > 0' (merged: raychaudhuri-ricci-focusing-needs-positive-energy)",
"source": {
 "located": "Classics: Raychaudhuri, Phys. Rev. 98, 1123 (1955) (timelike, dust); Sachs, Proc. R. Soc. A 264, 309 (1961) (null optical scalars); Jacobi (geodesic-deviation) equation; Hawking-Ellis (1973) Prop. 4.4.5 (null conjugate points under NEC + generic condition) -- no arXiv copies, all NAMED-NOT-READ. Restatement used: Gao & Wald, gr-qc/0007021 (CQG 17, 4999, 2000), eq.(11) d^2A/dlambda^2 = -R_{alpha beta sigma}^mu k^alpha k^sigma A^beta_nu with A|p = 0, dA/dlambda|p = delta; eq.(12) G = sqrt(det A); eq.(13) 'the Raychaudhuri equation yields (see e.g. [10]) G''/G = -(1/2)[sigma_ab sigma^ab + R_ab k^a k^b]'; Lemma 1 / Theorem 1 hypotheses NEC R_ab k^a k^b >= 0 (eq.2) and null generic condition (eq.9). Supporting restatements read in this stage from full texts cached in the docket scratchpad: Lobo arXiv:0909.5539v2 p.3 ('the energy conditions arise when one refers back to the Raychaudhuri equation for the expansion where a term R_mu nu k^mu k^nu appears ... The positivity of this quantity ensures that geodesic congruences focus within a finite value of the parameter ... in general relativity, through the Einstein field equation one can write the above condition in terms of the stress-energy tensor'; in f(R) it becomes T^eff_mu nu k^mu k^nu >= 0); Wall arXiv:1007.1493v2 p.11 eq.(29) ('The linearized Raychaudhuri equation, together with the Einstein equation, says that dtheta/dv = -8 pi G T_ab k^a k^b').",
 "read_status": "READ-VIA-RESTATEMENT",
 "via": "Gao-Wald eqs.(11)-(13) and Lemma 1 hypotheses were READ VERBATIM AT SOURCE within this docket by the sibling audit audits/gr-qc_0007021.json (alphaXiv get_paper_content fullText=true on gr-qc/0007021v2, all 15 pages); this stage re-quotes that record. THIS STAGE'S OWN alphaXiv calls (answer_pdf_queries on gr-qc/0007021 and gr-qc/0611123 [Kar-Sengupta review] x3, get_paper_content x2, discover_papers x1) were all refused with 'alphaXiv assistant quota exceeded', and arxiv.org, export.arxiv.org, www.ias.ac.in and link.springer.com are refused by the egress proxy (curl CONNECT 403; WebFetch EGRESS_BLOCKED). Lobo 0909.5539 and Wall 1007.1493 were read from full texts already cached at scratchpad/d67/src/casmag/all/. The null Raychaudhuri equation's shear/twist form and the Einstein reduction were in addition re-derived symbolically here (R1, R2), so no step of the audit rests on an unread statement."
},
"published_statement": "Gao & Wald (2000), restating Raychaudhuri-Sachs through Flanagan-Marolf-Wald: for the null geodesic congruence from a point p with affine parameter lambda, the Jacobi matrix A obeys d^2A/dlambda^2 = -R_{alpha beta sigma}^mu k^alpha k^sigma A^beta_nu, A|p = 0, dA/dlambda|p = delta (eq.11); with G = sqrt(det A) (eq.12) 'the Raychaudhuri equation yields G''/G = -(1/2)[sigma_ab sigma^ab + R_ab k^a k^b]' (eq.13); conjugate points are the zeros of G, and Lemma 1/Theorem 1 obtain them from the NEC R_ab k^a k^b >= 0 together with the null generic condition k_[a R_b]cd[e k_f] k^c k^d != 0 (a condition the Weyl tensor alone can satisfy). The general null Raychaudhuri equation, re-derived here and consistent with Freivogel-Krommydas 1807.03808 eq.(39) up to normalisation: dtheta/dlambda = -theta^2/2 - sigma_ab sigma^ab + omega_ab omega^ab - R_ab k^a k^b. In GR (Lobo 0909.5539 p.3; Wall 1007.1493 eq.29) R_ab k^a k^b = 8 pi G T_ab k^a k^b, and positivity of R_kk ensures focusing within finite affine parameter. The published results give SUFFICIENT conditions for focusing/conjugate points; none of the restatements read asserts that a conjugate point REQUIRES R_kk > 0.",
"published_hypotheses": [
 "H1 null geodesic congruence, affinely parametrised (eq.11 in lambda; the ODE coefficient 1/2 is 1/(n-2) with n = 4 -- see gr-qc_0007021 audit rederive A1-A3)",
 "H2 twist-free (hypersurface-orthogonal) congruence, e.g. the congruence from a point (A|p = 0): omega_ab = 0, otherwise +omega^2 enters with DEfocusing sign",
 "H3 four spacetime dimensions for the coefficient 1/2 in eq.(13) and the 1/2 in theta^2/2",
 "H4 Einstein's equation (classical, GR) to convert R_kk into 8 pi G T_kk / c^4; the trace term and any cosmological constant drop because g_ab k^a k^b = 0 (R1). In modified gravity the condition is on an effective T (Lobo 0909.5539 p.3)",
 "H5 for a conjugate-point EXISTENCE theorem: NEC R_kk >= 0 PLUS either initial convergence or the null generic condition, and sufficient affine extent (Gao-Wald Lemma 1 / Theorem 1; Hawking-Ellis 4.4.5 named-not-read)",
 "H6 the shear term sigma_ab sigma^ab >= 0 is sourced by the Weyl tensor through the Sachs/Jacobi equation and can by itself produce a conjugate point (the null generic condition is satisfiable in vacuum)"
],
"hypothesis_drift": [
 "ADDED NECESSITY (not in any source) -- spec.py:27-28 'PART 2 TURN a conjugate point. Needs T_kk > 0'. The published results are sufficiency statements. Necessity holds only in the shear-free, twist-free reduction u'' = -(R_kk/2)u (rederive R6: q <= 0 everywhere, sigma = 0 => G >= lambda > 0, no zero), and there only as 'T_kk > 0 SOMEWHERE on the segment', not pointwise and not integrated (R6: q > 0 on [0,1.6] only, int q = -914 < 0, still focuses at pi/2). In the full Jacobi equation it is refuted: R7/R7b give an exact GR plane wave, ds^2 = 2du dv + [-(w-e)x^2 + (w+e)y^2]du^2 + dx^2 + dy^2, with R_uu = -2e < 0 (T_kk < 0) and a conjugate point at pi/sqrt(w-e), eq.(13) holding along it to 1e-123. spec.py's OWN lower section (spec.py:56-70, 'WHAT ACTUALLY SEATS, AND IT IS ORDINARY LENSING', conjugate points by cumulative Weyl focusing through vacuum) and specthm SR1 ('through vacuum, NEC, WEC and DEC satisfied everywhere', specthm.py:1315-1327) already contradict the necessity reading, and composite.py:12-16 names the dropped shear term. The canonical entry's hypothesis 'focusing along T_kk (Ricci term) only' is the condition under which the necessity holds; it is not written at spec.py:27-28.",
 "DROPPED 'point initial data' -- spec.py:173-175 'pi/sqrt(q) -- the independent route to the same range'. pi/sqrt(q) is the point-to-point conjugate length (G(0)=0, G'(0)=1); for an initially parallel congruence the focal length is pi/(2 sqrt q) (R4). The owner's other hypothesis 'constant q over the stretch' is named in the canonical entry; with q >= q0 > 0 and sigma^2 >= 0 the figure is an UPPER bound, sharp at q = q0, sigma = 0 (R5, 60 random profiles + equality case).",
 "ADDED IDENTIFICATION T_kk = u (energy density) -- spec.py:168-175 names q_of's argument u and its docstring T_kk; spec.py:303-304 compares seatindex.tkk_required(l) (seatindex.py:209-211, 'T_kk >= pi c^4/(4 G l^2)') with energy_density(B) = B^2/(2 mu0). T_kk = energy density only for dust with k^0 = 1 in the rest frame; a perfect fluid gives rho c^2 + p, and a pure magnetic field gives T_kk = 2u sin^2(alpha) (R8): 2u for rays perpendicular to B, 0 along B. Scope, not over-represented: q_of and conjugate_length_from_q are called by neither selftest nor report (canonical entry); the B*l figure they feed is already WITHDRAWN (spec.py:36-49); and at perpendicular incidence the withdrawn ratio u_seat/u_collapse = 2 pi^2/3 = 6.58 becomes pi^2/3 = 3.29 (R8) -- still > 1, so the withdrawal's conclusion ('inside its own Schwarzschild radius') is unchanged. Recorded as a discrepancy, nothing repaired.",
 "HELD (no drift) -- composite.py:12-27: 'RICCI FOCUSING NEEDS POSITIVE ENERGY' read as 'the Ricci term focuses only where T_kk > 0' is exact given H4 (R1: R_kk = kappa T_kk, trace and Lambda terms drop identically); composite.py quotes eq.(13) verbatim with the correct number and itself identifies the Ricci-only reduction as dropping sigma^2. 'WEYL FOCUSING IS SIGN-BLIND ... exactly as hard' is the owner's reading, not the source's, and holds at first order in M (already recorded in audits/gr-qc_0007021.json drift 6).",
 "HELD (no drift) -- specthm.py:1326-1327 'Ricci focusing needs T_kk > 0, which ordinary matter has': the sign statement is exact under H4; 'ordinary matter has' holds for classical dust, fluids with rho c^2 + p > 0 and EM fields (T_kk = 2u sin^2 alpha >= 0, R8); it is not a theorem for quantum states (pointwise NEC is violated by Casimir/squeezed states -- a premise about matter, not about this result).",
 "UNNAMED BY OWNERS -- H2 (twist-free), H3 (4 dimensions) and H4 (Einstein equation, classical) are used and named at no owner line; all three hold in the tree's settings (congruences from a point, 4D GR), so this moves no conclusion."
],
"data_at_publication": [
 {"quantity": "Newton's constant G (sets the scale of q and pi/sqrt(q); not the sign condition)", "value_then": "tree: G_SI = 6.67430e-11 m^3 kg^-1 s^-2 (CODATA 2018)", "value_now": "6.67430(15)e-11 (CODATA 2022, unchanged)", "source_now": "CODATA 2022, arXiv:2409.03787, as read at source in this docket by audits/einstein-field-equations.json ('G unmoved (CODATA 2022 = 2018)'); not re-read in this stage (alphaXiv quota)", "moves_conclusion": "No. Relative uncertainty 2.2e-5 moves pi/sqrt(q) by 1.1e-5 relative (R9); the sign statement 'Ricci focusing needs T_kk > 0' is G-independent."},
 {"quantity": "speed of light c", "value_then": "299792458.0 m/s", "value_now": "299792458 m/s (exact by SI definition)", "source_now": "SI definition (1983); unchanged", "moves_conclusion": "No."},
 {"quantity": "coupling 8 pi G/c^4 in R_kk = (8 pi G/c^4) T_kk (i.e. GR itself)", "value_then": "Einstein 1915 coupling", "value_now": "no deviation from GR found", "source_now": "Will arXiv:1403.7377 and LVK GWTC-5.0 TGR arXiv:2607.19293, as read at source in this docket by audits/einstein-field-equations.json; not re-read here", "moves_conclusion": "No."}
],
"rederivation": {
 "method": "sympy",
 "script_path": D + "/rederive/jacobi-raychaudhuri-ricci-focusing.py",
 "outcome": "10/10 PASS, exit 0 (output rederive/jacobi-raychaudhuri-ricci-focusing.out). R1 Einstein eq with trace term and Lambda contracted on a null k gives R_kk - kappa T_kk = 0 identically. R2 null Raychaudhuri with theta = 2G'/G is exactly G''/G = -(sigma^2 - omega^2 + R_kk)/2; omega = 0 is Gao-Wald eq.(13). R3 R_kk/2 = (4 pi G/c^4) T_kk; units of q are m^-2 -- the tree's q_of is right. R4 constant q: point data first zero pi/sqrt(q) (the tree's figure), parallel data pi/(2 sqrt q). R5 Sturm sufficiency: 60 random profiles q >= q0 = 1 with sigma^2 >= 0 all focus by pi/sqrt(q0) (max 2.151 < 3.1416), equality case exactly pi. R6 necessity in the Ricci-only reduction: q <= 0 never focuses; q > 0 only on [0,1.6] with integral -914 still focuses at pi/2 -- 'somewhere', not 'integrated'. R7 full 2x2 Jacobi: tidal diag(0.9, -1.1), R_kk = -0.2 < 0, det J = 0 at 3.311529, eq.(13) residual 7.6e-124. R7b the same tidal matrix is the exact curvature of a GR plane wave (R_uu = -1/5, R^i_uju = diag(9/10, -11/10)) -- a spacetime with T_kk < 0 and a conjugate point. R8 T_kk: dust rho c^2, fluid rho c^2 + p, magnetic 2u sin^2(alpha); spec.py's withdrawn ratio 6.58 -> 3.29 at perpendicular incidence, still > 1. R9 water: q = 9.332e-24 m^-2, pi/sqrt(q) = 1.028e12 m = 6.87 AU.",
 "agrees_with_source": "yes"
},
"later_literature": [
 {"ref": "Gao & Wald, gr-qc/0007021 (2000), eqs.(11)-(13), Lemma 1, Theorem 1", "effect": "confirms", "what": "Restates the Jacobi matrix equation and the shear-plus-Ricci area equation; conjugate points from NEC + null generic condition, the latter satisfiable by Weyl alone -- the sufficiency form, and the Weyl route the necessity reading omits.", "read_status": "READ at source in this docket by audits/gr-qc_0007021.json (alphaXiv full text); re-quoted, not re-read, in this stage"},
 {"ref": "Lobo, arXiv:0909.5539 (2009), p.3", "effect": "narrows", "what": "Positivity of R_kk ensures focusing; the translation to T_kk >= 0 is a GR step -- in f(R) gravity it becomes T^eff_kk >= 0, so the Ricci-focusing-needs-positive-energy statement is conditional on Einstein's equation (H4).", "read_status": "READ (full text cached at scratchpad/d67/src/casmag/all/0909.5539v2.txt)"},
 {"ref": "Wall, arXiv:1007.1493 (2010), p.11 eq.(29)", "effect": "confirms", "what": "Linearised Raychaudhuri + Einstein: dtheta/dv = -8 pi G T_kk, the linear-in-source Ricci term the tree calls Ricci focusing.", "read_status": "READ (full text cached at scratchpad/d67/src/casmag/all/1007.1493v2.txt)"},
 {"ref": "Gao, Jafferis & Wall, arXiv:1608.05687 (2016/2019), p.1-2", "effect": "extends", "what": "'by Raychaudhuri's equation for null geodesic congruence, light rays will defocus only when ANEC is violated' -- the integrated (achronal, complete-geodesic) converse; consistent with R6's finding that pointwise sign is not what governs.", "read_status": "READ (full text cached at scratchpad/d67/src/1608.05687.txt)"},
 {"ref": "Freivogel & Krommydas, arXiv:1807.03808 (SNEC), eqs.(39)-(41)", "effect": "extends", "what": "Null Raychaudhuri with omega, sigma, theta^2/2 terms; SNEC bounds how much negative T_kk can DEfocus a congruence (Delta A/A >= -B). Normalisation of the T_kk term as extracted is G_N rather than 8 pi G -- a convention/extraction difference, not relied on.", "read_status": "READ (full text cached at scratchpad/d67/src/1807.03808.txt)"},
 {"ref": "discover_papers search for later work on Weyl/shear focusing and conjugate points without NEC", "effect": "contested", "what": "Not performed: refused by 'alphaXiv assistant quota exceeded'. The plane-wave counterexample R7b is computed here independently (Penrose 1965 on plane waves, NAMED-NOT-READ).", "read_status": "NOT-RUN (quota)"}
],
"lacked_data": "M's hypothesis tested for this result. The result is a geometric identity (Jacobi/Raychaudhuri, re-derived here exactly, R2) plus Einstein's equation contracted on a null vector (R1). Its only empirical inputs are the coupling 8 pi G/c^4 and G's value; neither has moved (CODATA 2022 = 2018; no GR deviation in GWTC-5.0, both as read in this docket). Raychaudhuri (1955) worked with timelike dust congruences; the null version with shear (Sachs 1961) already carried the sigma^2 term, so no datum was missing that would change the identity. What came later and matters is not a datum about the theorem but about matter: pointwise T_kk < 0 is realised by quantum states (Casimir, squeezed vacuum), which bears on the tree's premise 'ordinary matter has T_kk > 0' (true classically, R8) and not on the focusing result. Evidence against M's hypothesis here: the conclusion that rests on the result (spec PART 2 'ACHIEVABLE') needs only sufficiency, which stands (R5) and is exceeded by vacuum Weyl lensing. Evidence for an inaccuracy -- but in the TREE's gloss, not in the outside physics: the necessity reading 'a conjugate point needs T_kk > 0' is refuted in full GR by an exact plane wave (R7b). No external result is shown wrong.",
"grade": "NARROWED",
"grade_evidence": "The external result STANDS as published: the null Raychaudhuri/area equation and its Einstein reduction are re-derived symbolically (R1, R2), the tree's q = (4 pi G/c^4) T_kk and pi/sqrt(q) are exact under their conditions (R3, R4), Sturm sufficiency is checked (R5), and no datum has moved (G, c, the GR coupling). The TREE's use is NARROWED, shown and not presumed: (1) spec.py:27-28 states 'a conjugate point ... Needs T_kk > 0' as a requirement; that necessity holds only in the shear-free, twist-free reduction and only as 'somewhere' (R6), and fails in full GR -- an exact plane wave with R_kk = -0.2 < 0 has a conjugate point at pi/sqrt(0.9) (R7, R7b) -- which the tree's own composite.py:12-16, spec.py:56-70 and specthm SR1 (vacuum lensing) already contradict; (2) pi/sqrt(q) is point-to-point with constant q and zero shear (parallel data give half; with q >= q0 and shear it is an upper bound, R4-R5); (3) T_kk is identified with energy density u at spec.py:168-175 and 303-304, whereas a magnetic field gives 2u sin^2(alpha) (R8) -- in an uncalled function and a withdrawn figure, and the withdrawal's conclusion survives (ratio 3.29 > 1). Not WRONG: no published statement is contradicted. Not DATA-DEPENDENT: no moved datum moves the conclusion. The downstream uses -- spec PART 2 'ACHIEVABLE' and SR1's sign statement -- survive, since achievability needs only sufficiency (and Weyl focusing through vacuum supplies it) and the Ricci sign statement is exact given Einstein's equation.",
"what_would_change_the_grade": "To STANDS: an owner line naming the Ricci-only (shear-free, twist-free) reduction and point initial data at spec.py:27-28 and 168-175, or rewording 'Needs T_kk > 0' as the sufficiency 'T_kk > 0 suffices' -- a wording change for the owner, not made here (nothing repaired). To OPEN or lower: a direct read of Raychaudhuri 1955/Sachs 1961 or Hawking-Ellis 4.4.5 showing a necessity statement (none is expected; the plane-wave computation R7b would then be a counterexample to it). To DATA-DEPENDENT: a measured departure from GR's null-null coupling 8 pi G/c^4 (none in GWTC-5.0 as read in this docket). A later-literature pass (discover_papers, refused here by quota) could add work on shear-driven conjugate points; it cannot move the grade above NARROWED while spec.py:27-28 reads as necessity.",
"reverify_command": "python3 " + D + "/rederive/jacobi-raychaudhuri-ricci-focusing.py && sed -n 24,31p /home/user/Claude-Method-Works/research/warp-drive/spec.py && sed -n 56,62p /home/user/Claude-Method-Works/research/warp-drive/spec.py && sed -n 166,180p /home/user/Claude-Method-Works/research/warp-drive/spec.py && sed -n 300,305p /home/user/Claude-Method-Works/research/warp-drive/spec.py && sed -n 12,28p /home/user/Claude-Method-Works/research/warp-drive/composite.py && sed -n 1315,1327p /home/user/Claude-Method-Works/research/warp-drive/specthm.py && grep -n 'positivity of this quantity' -i " + D + "/src/casmag/all/0909.5539v2.txt && grep -n 'says that' " + D + "/src/casmag/all/1007.1493v2.txt",
"report_path": D + "/audits/jacobi-raychaudhuri-ricci-focusing.json"
}
json.dump(R, open(R["report_path"], "w"), indent=1)
print("wrote", R["report_path"])
