import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
SRC = D + "/src/casmag/all/gr-qc_9304008v1.txt"
R = {
 "key": "gr-qc/9304008",
 "name": "Kuo & Ford fluctuation criterion Delta (KF eq. 3.2): the semiclassical equation holds only where Delta << 1",
 "source": {
  "located": "C.-I. Kuo & L. H. Ford, 'Semiclassical gravity theory and quantum fluctuations', arXiv gr-qc/9304008 v1 (6 Apr 1993; TUTP-93-1, Feb 1993). p.5: eqs (3.1)-(3.2) and the criterion sentence; p.6: (3.7)-(3.8) and the negativity sentence; p.9: squeezed-state numerics; p.11-12: (3.41)-(3.45); Sec. V (p.15-16): quartic-renormalisation and averaging sentences. Journal version Phys. Rev. D 47, 4510 (1993) NAMED-NOT-READ.",
  "read_status": "READ",
  "via": "arXiv v1 PDF TEXT LAYER as returned by alphaXiv in earlier stages of this docket, harvested verbatim to " + SRC + " (md5 f1a6628604751cf61b2a4bd411b00153, 39,849 bytes, 19 pages, by d67/src/casmag/allpages.py from the alphaXiv <paper><page> tool results), plus d67/src/gr-qc_9304008.note (Sec. V quotes from a get_paper_content fullText read earlier on 2026-09-26). A fresh fetch in THIS stage failed: answer_pdf_queries, get_paper_content and discover_papers all returned 'alphaXiv assistant quota exceeded'. Page image not viewed; journal version not read."
 },
 "published_statement": "v1 p.5, verbatim from the text layer: 'We propose that the extent to which the semiclassical approximation is violated can be measured by the dimensionless quantity Delta_{abmn}(x,y) = | (<:T_ab(x) T_mn(y):> - <:T_ab(x):><:T_mn(y):>) / <:T_ab(x) T_mn(y):> |. (3.1) This quantity is a dimensionless measure of the stress tensor fluctuations. (Note that it is not a tensor, but rather the ratio of tensor components.) If its components are always small compared to unity, then these fluctuations are small and we expect the semiclassical theory to hold. ... For simplicity, we will concentrate upon the coincidence limit, x -> y, of the purely temporal component of the above quantity, that is Delta(x) = | (<:T00^2(x):> - <:T00(x):>^2) / <:T00^2(x):> |. (3.2) The local energy density fluctuations are small when Delta << 1, which we take to be a measure of the validity of the semiclassical theory. Note that we have used normal ordering with respect to the Minkowski vacuum state to define the various operators.' p.11-12: 'Delta' = (<:T00^2(x):> - rho^2)/rho^2 = (1/8)[(rho + xi1 + xi2 + xi3)^2 + ...] (3.43) ... Delta' = Delta/(1-Delta), Delta = Delta'/(1+Delta') (3.44)'. Sec. V: 'The generalization of this analysis to curved spacetime backgrounds will require a renormalization procedure for quartic operator products in such spacetimes, which has not yet been developed. ... If we were to average fields over finite space or time intervals, then we could define a quantity similar to Delta without invoking normal ordering ... this procedure suffers from the defect that it introduces an arbitrary length or time scale into the problem.'",
 "published_hypotheses": [
  "H1 PROPOSAL, not derivation: 'We propose that the extent to which the semiclassical approximation is violated can be measured by' Delta; motivated by Ford (1982) graviton emission, where semiclassical and linearised-quantum fluxes agree for a single-mode coherent state (p.5). No theorem bounds the error of G = 8 pi G <T> by Delta.",
  "H2 the full measure is (3.1): ALL components, TWO points x, y; the semiclassical theory is expected to hold 'if its components are always small' -- a sufficiency-type expectation, stated for the whole object.",
  "H3 Delta(x) of (3.2) is a reduction of (3.1) 'for simplicity': coincidence limit x -> y AND the purely temporal (00) component only.",
  "H4 normal ordering with respect to the Minkowski vacuum defines every operator, including the quartic :T00^2: (p.5); flat spacetime (Sec. V: 'restricted to a flat spacetime background').",
  "H5 the absolute value in (3.2): Delta is |<:T^2:> - rho^2| / <:T^2:>; (3.44) Delta = Delta'/(1+Delta') tacitly assumes <:T00^2:> >= rho^2 (and <:T00^2:> > 0).",
  "H6 examples only: massless (minimally coupled) scalar in flat spacetime, single-mode number-state superpositions, squeezed coherent/vacuum states, Casimir (periodic) vacuum; the Casimir bound (3.45) via (3.41)-(3.42) assumes a diagonal <:d_A phi d_B phi:> and the Wick condition 'phi+|psi> = <psi|phi- = 0' ('Both the Minkowski and Casimir vacua satisfy this condition').",
  "H7 Sec. V scope limits: curved space needs a quartic-product renormalisation 'which has not yet been developed' (1993); a smeared Delta would need a length/time scale they call 'arbitrary'."
 ],
 "hypothesis_drift": [
  "DROPPED (the |.| of (3.2), H5): the tree's computational form is unsigned -- fluctuation.py:237 'delta=sp.simplify(1 - rho**2 / T2)', fluctuation.py:230 and :39 'Delta = 1 - (2eps - sqrt2 cos2th)^2/(3(1+eps^2))' stated without restriction, and fluctuation.py:281 'Delta=Dp/(1+Dp)'. This is KF's Delta only where <:T00^2:> >= rho^2 (re-derivation C1a-c). In the very state the tree re-derives (KF 2.15) that fails: at eps = 1, cos 2theta = -1, rho = (2+sqrt2)K > 0 and rho^2/<:T^2:> = 1 + 2sqrt2/3 = 1.9428, so KF's Delta = +0.9428 and the tree's closed form gives -0.9428 (C2d-e; reachable set SAT, C3c). HARMLESS FOR EVERY TREE CONCLUSION: on rho < 0 in that state the |.| is inactive (C3a, C3b: <:T^2:> > (3/2) rho^2), and on every zero-mean Gaussian state <:T^2:> >= (3/2) rho^2 (C5c), which covers T1, Casimir and thermal (fluctuation.py:268-281). The unrestricted docstring formula at fluctuation.py:38-39 is the only site where the drop is visible, and it is a statement about rho > 0 points the tree never uses.",
  "WEAKENED-TO-STRONGER (H1/H2 upgraded): fluctuation.py:101-102 'semiclassical gravity's error term is Delta' and fluctuation.py:9-12 ('the error term of that equation ... Kuo & Ford ... turns \"good approximation\" into a computed quantity'), and ledger.py:751-752 D22_DOCKET62 'Kuo & Ford's measure of that equation's error, Delta'. KF PROPOSE Delta as 'a measure' ('which we take to be a measure of the validity'); it is not derived as the error term of G = 8 pi G <T>, and later literature calls it a criterion to be refined (Hu-Roura-Verdaguer 2004, citing Hu-Phillips; Anderson-Molina-Paris-Mottola 2002 propose a different, linear-response criterion). The tree's own wording at fluctuation.py:17-18 ('Delta << 1 is their criterion for the semiclassical equation to hold') is faithful; 'error term' is not.",
  "DROPPED (H2/H3 reduction): the tree lists 'coincidence limit' (canonical hypotheses; fluctuation.py:16) but not that Delta(x) is ONLY the 00 component of the multi-component, two-point (3.1), and that KF's validity expectation is stated for ALL components of (3.1) being small. The tree's statement is about the reduced object; no tree conclusion claims the full (3.1). Harmless for T1/T2, but relevant to reading Delta as 'the' error.",
  "HARNESS NAME vs SOURCE: the canonical name 'the semiclassical equation holds ONLY where Delta << 1' is a necessity reading; KF's text is sufficiency-type at (3.1) ('if ... small ... we expect the semiclassical theory to hold') and argue failure when fluctuations are large (the 1000 kg superposition, p.5). The tree's files do not use 'only where'; recorded as a drift of the name, not of the tree.",
  "NARROWED BY THE TREE (correctly, kept): massless minimally coupled scalar (fluctuation.py:17) is a hypothesis of KF's EXAMPLES (H6), not of the definition (3.2); attaching it to Delta restricts rather than widens -- no drift against the source.",
  "ADDED BY THE TREE (its own, labelled as its own): the Wick step for ANY zero-mean quasifree state including mixed (thermal) ones (fluctuation.py:70-79) goes beyond KF's stated Wick condition 'phi+|psi> = <psi|phi- = 0' (vacua). Standard for quasifree states and re-derived here (C5a, numeric Isserlis control C5b); it belongs to T1 (rests_on_it), not to KF.",
  "SCOPE (kept, correct): discrepancies scoped to arXiv v1; journal version NAMED-NOT-READ (fluctuation.py:122-126, 134-135; ledger.py:863-865 cites fluctuation.JOURNAL_VERSION_READ). PAGE_IMAGE_VIEWED = False (fluctuation.py:136)."
 ],
 "data_at_publication": [
  {
   "quantity": "empirical inputs to Delta (3.2) or to the criterion Delta << 1",
   "value_then": "none: (3.2) is a definition; every Delta KF compute is a closed-form Fock-space or image-sum expectation value in hbar = c = 1 units with no measured constant",
   "value_now": "none",
   "source_now": "the definition as READ (p.5) and re-derivation C1-C7",
   "moves_conclusion": "No -- nothing measurable enters. The '1' in 'Delta << 1' is the only scale, and it is a convention of the proposed criterion, not a datum."
  },
  {
   "quantity": "vacuum+2 state: rho^2/<:T00^2:> (decides whether the |.| in (3.2) is active)",
   "value_then": "not computed by KF in this form; KF's printed (2.16) final line and (3.7) are discrepant (other keys)",
   "value_now": "(2eps - sqrt2 cos2th)^2/(3(1+eps^2)) exactly; 1.942809 at eps = 1, cos2th = -1 (rho > 0); < 2/3 everywhere rho < 0",
   "source_now": "rederive/gr-qc_9304008.py C2c-C2e, C3a-C3b (exact Fock matrices, z3)",
   "moves_conclusion": "Moves the tree's unsigned closed form (fluctuation.py:39, 230, 237) at rho > 0 points (sign flip, -0.9428 vs KF +0.9428); moves no tree conclusion, all of which live at rho < 0 or on Gaussian states where the |.| is inactive."
  },
  {
   "quantity": "Casimir (3.43) bracket: leading term",
   "value_then": "printed '(rho + xi1 + xi2 + xi3)^2 ...' with xi_i = p_i/rho (text layer)",
   "value_now": "must be (1 + xi1 + xi2 + xi3)^2 ...: with 1 it equals the exact Delta' for diagonal G and yields KF's own printed min 1/2 and value 6 at xi = (-1,-1,3); with rho it is dimensionally inhomogeneous",
   "source_now": "rederive/gr-qc_9304008.py C6c-C6f",
   "moves_conclusion": "No. A discrepancy (typographical, or a text-layer artefact -- page image not viewed), not a refutation: KF's (3.45) numbers follow from the corrected bracket, as fluctuation.py records (KF_345_IS_EXACT = True). NOT recorded in fluctuation.py, which flags (3.41)-(3.42)'s 1/2 but not this."
  }
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/gr-qc_9304008.py",
  "outcome": "24/24 checks pass (output rederive/gr-qc_9304008.out; script md5 4ac3831199d84b66e56e506ce4923086; sympy 1.14.0, z3 4.x/5.1.0 build). Independent of fluctuation.py (no import, no shared code). C1 (z3): KF (3.44) Delta = Delta'/(1+Delta') and Delta' = Delta/(1-Delta) hold IFF the |.| of (3.2) is inactive (<:T^2:> >= rho^2); without it a counterexample exists (<:T^2:> = 1/2, rho = -1: Delta = 1, Delta'/(1+Delta') = -1). C2 (exact Fock matrices, N = 12): vac+2 rho = 2K eps(2eps - sqrt2 cos2th)/(1+eps^2), <:T00^2:> = 12K^2 eps^2/(1+eps^2), ratio rho^2/<:T^2:> = (2eps - sqrt2 cos2th)^2/(3(1+eps^2)); witness eps = 1, cos2th = -1: rho > 0, ratio 1.942809, KF Delta +0.942809 vs unsigned -0.942809. C3 (z3, guard SAT): on rho < 0 the ratio lies in (0, 2/3), so 1/3 < Delta < 1 with KF's own |.| -- the |.| is inactive there, and KF's printed 'rho < 0 => Delta > 1' fails for the exact moments (agrees with fluctuation.KF_CLAIM_NEGATIVE_MEANS_DELTA_GT_1 = False). C4: coherent state Delta = 0 identically (KF 3.21). C5: Wick, <:T00^2:> - rho^2 = (1/2) sum G_AB^2, symbolic and by a numeric Isserlis control; z3: <:T^2:> >= (3/2) rho^2 on every zero-mean Gaussian (|.| inactive, (3.44) valid; stronger 2 rho^2 refutable -- vacuity guard). C6: for diagonal G, G00 = (rho+p1+p2+p3)/2 and G11 = (rho+p1-p2-p3)/2, so (3.41)-(3.42)'s coefficient is 1/4 (printed 1/2 -- agrees with fluctuation.KF_341_HALF_IS_TYPOGRAPHICAL); (3.43) is exact with leading 1, gives min 1/2 at xi = 0 (PD quadratic, unique stationary point) and 6 at xi = (-1,-1,3); with the printed leading rho it is not. C7: isotropic thermal radiation, p = rho/3, Delta' = 2/3, Delta = 2/5 (agrees with the tree's thermal control).",
  "agrees_with_source": "partly"
 },
 "later_literature": [
  {
   "ref": "B. L. Hu, A. Roura & E. Verdaguer, 'Induced quantum metric fluctuations and the validity of semiclassical gravity', arXiv:gr-qc/0402029 (PRD 70, 044002, 2004)",
   "effect": "narrows",
   "what": "p.2: 'An earlier criterion put forth by Kuo and Ford [5] used the variance of the fluctuations of the stress tensor operator compared to the mean value as a measure of the validity of SCG. As pointed out by Hu and Phillips [27, 28] (see reply by Ford and Wu [7]) such a criterion should be refined by considering the back reaction of those fluctuations on the metric.' They propose instead a stability criterion (metric fluctuations must not grow without bound) and find Minkowski stable. This is a narrowing of Delta's status as THE validity criterion (the tree's 'error term'), not a refutation of the definition. Hu-Phillips and Ford-Wu themselves not read here.",
   "read_status": "READ from cached text d67/src/casmag/all/gr-qc_0402029v1.txt (lines 11-33, 105-108), harvested from alphaXiv in an earlier stage; reference list not in the cache"
  },
  {
   "ref": "P. R. Anderson, C. Molina-Paris & E. Mottola, 'Linear response, validity of semi-classical gravity, and the stability of flat space', arXiv:gr-qc/0209075 (PRD 67, 024026, 2003)",
   "effect": "contested",
   "what": "Abstract: 'A quantitative test for the validity of the semi-classical approximation in gravity is given. The criterion proposed is that solutions to the semi-classical Einstein equations should be stable to linearized perturbations', bringing in the stress-tensor two-point function through linear response 'with no state dependent divergences and requires no new renormalization counterterms'. Cites Kuo & Ford [15]. A competing criterion; flat space found stable at scales >> Planck length, whereas the pointwise KF Delta is O(1) for the Minkowski-adjacent Gaussian states the tree studies -- the two criteria disagree in status, which is why Delta is 'contested' as a validity criterion.",
   "read_status": "READ (abstract and introduction) from cached text d67/src/casmag/all/gr-qc_0209075v1.txt, earlier stage; OCR-degraded layer"
  },
  {
   "ref": "A. Perez & D. Sudarsky, 'Renormalization of the Quantum Stress Tensor Fluctuations and the Limits of Semiclassical Gravity', arXiv:2512.17789 v2 (Jan 2026)",
   "effect": "extends",
   "what": "Supplies the curved-space renormalisation KF said 'has not yet been developed': <T_ab(x) T_cd(x)>_ren for Hadamard states via the operator product expansion, free scalar on a fixed curved background; 'states (usually referred to as squeezed vacua) ... fail to satisfy the natural semiclassicality criterion'; 'our results agree in general lines with these earlier works [Ford; Kuo & Ford] and in the specific settings they considered'. Extends KF's qualitative conclusion to curved space; it also dates the tree's quoted 1993 limitation (fluctuation.py:114-116 'Their words, 1993' and ledger.py:760-761 'curved-space renormalisation of quartic operator products Kuo & Ford said did not exist') -- the tree attributes it correctly to 1993, but the gap is no longer open in the literature in the form KF stated.",
   "read_status": "READ (abstract, introduction p.1-2) from cached text d67/src/casmag/all/2512.17789v2.txt, earlier stage"
  },
  {
   "ref": "L. H. Ford & T. A. Roman, 'Averaged energy conditions and quantum inequalities', arXiv:gr-qc/9410043 (1994)",
   "effect": "confirms",
   "what": "Same group, context only: 'recent work of Kuo and Ford [42, 43] indicates that in flat spacetime, negative energy densities are subject to large fluctuations. This suggests that the naive use of the semiclassical theory of gravity may be suspect, at least in some situations involving negative energy.' Hedged ('suggests', 'may be') -- the authors' own later weight is a heuristic, not an error term.",
   "read_status": "READ from cached text d67/src/casmag/all/gr-qc_9410043v1.txt (lines 2362-2368)"
  }
 ],
 "lacked_data": "M's hypothesis, tested for this result: the result is a DEFINITION plus a PROPOSED criterion, with no empirical input (data_at_publication row 1), so no measured datum was lacking and none has moved. What KF lacked in 1993 was THEORY, and they said so: (a) the renormalisation of quartic operator products in curved spacetime ('has not yet been developed') -- now supplied via the OPE by Perez & Sudarsky (arXiv:2512.17789, 2026), whose result 'agree[s] in general lines' with KF and finds squeezed vacua fail the criterion: evidence that having it does NOT overturn KF's qualitative conclusion; (b) a principled choice of averaging scale -- the tree's own position (fluctuation.py:110-113) is that for the corridor the scale is not arbitrary; (c) a derivation of Delta as the actual error of G = 8 pi G <T> -- later work (Hu-Phillips via Hu-Roura-Verdaguer 2004; Anderson-Molina-Paris-Mottola 2002) did not supply one but replaced or refined the criterion by back-reaction / linear-response stability, under which flat space is stable although pointwise Delta = O(1) for its Gaussian states. That is evidence FOR M's suspicion in one narrow sense: the validity criterion is incomplete (it ignores back reaction and is sign-blind, condemning thermal radiation at Delta = 2/5, C7) -- but it is not evidence that the definition or any flat-space value was wrong. Evidence against over-reading: every internal identity of the definition checks exactly (C1, C4, C5), and the printed discrepancies ((3.41)-(3.43) coefficients, the 'rho<0 => Delta>1' sentence) are algebra/typography against v1, not missing data.",
 "grade": "NARROWED",
 "grade_evidence": "The DEFINITION stands exactly as READ: (3.2), its normal ordering against the Minkowski vacuum, its coincidence-limit 00 reduction, (3.44), the coherent-state zero and the Gaussian/Casimir/thermal values all re-derive (C1a-b, C4, C5, C6c-f, C7; 24/24). It is NARROWED against the tree's use on two counts, each shown here: (1) a hypothesis the tree drops -- the absolute value of (3.2): the tree's closed form 1 - rho^2/<:T^2:> (fluctuation.py:39, 230, 237, 281) equals KF's Delta only where <:T00^2:> >= rho^2, and in KF's own vac+2 state that fails at rho > 0 (eps = 1, cos2th = -1: +0.9428 vs -0.9428, C2d-e; reachable, C3c); it is inactive on rho < 0 (C3a-b) and on every zero-mean Gaussian state (C5c), so T1, T2, the Casimir 6/7, the thermal 2/5 and fluctuation.KF_CLAIM_NEGATIVE_MEANS_DELTA_GT_1 = False all stand (C3d); (2) a weaker status than the tree states -- KF PROPOSE Delta as 'a measure' of validity for the reduced 00 coincidence component of (3.1); fluctuation.py:101-102 'semiclassical gravity's error term is Delta' and ledger.py:751-752 'Kuo & Ford's measure of that equation's error' upgrade it, and the later literature narrows or contests it as the validity criterion (Hu-Roura-Verdaguer 2004 'should be refined by considering the back reaction'; Anderson et al. 2002 linear-response criterion). Nothing is WRONG: no counterexample to anything KF define; the discrepancies are recorded, not refuted, and against v1 only. No ledger verdict moves: the tree already refuses the pointwise Delta as a demand row (fluctuation.py:105-120, PRICES_THE_CORRIDOR = False, LEDGER_ROW_MOVES = False). NEW DISCREPANCY recorded, not repaired: (3.43)'s leading 'rho' must read '1' (C6c-e) -- unflagged in fluctuation.py; possibly a text-layer artefact (page image not viewed). Residual named hypotheses bounding this grade: v1 text layer faithful; journal version NAMED-NOT-READ; no fresh alphaXiv read or discover_papers in this stage (quota), later literature from cached texts of earlier stages.",
 "what_would_change_the_grade": "To STANDS: the tree restricting its closed form to <:T^2:> >= rho^2 (or restoring the |.|) and wording Delta as KF's proposed measure rather than 'the error term' -- i.e. a narrowing on the tree's side, not new physics. To OPEN: none foreseeable for the definition; the text layer is corroborated by the tree's independent reads. To WRONG: only a demonstration that KF's (3.2) as printed differs from what is quoted (page image / journal version) or a state where their stated identity (3.44) is asserted with <:T^2:> < rho^2 -- neither is shown. Reading Hu-Phillips (gr-qc/0004006 area) and Ford-Wu's reply could sharpen 'contested' into a specific counter-claim; reading PRD 47, 4510 could remove the (3.41)-(3.43) discrepancies from the journal version.",
 "reverify_command": "python3 " + D + "/rederive/gr-qc_9304008.py && grep -n 'propose\\|which we take to be a measure\\|(3.2)' " + SRC + " && sed -n 99,103p /home/user/Claude-Method-Works/research/warp-drive/fluctuation.py && sed -n 230,238p /home/user/Claude-Method-Works/research/warp-drive/fluctuation.py",
 "report_path": D + "/audits/gr-qc_9304008.json"
}
json.dump(R, open(D + "/audits/gr-qc_9304008.json", "w"), indent=1)
print("ok", len(json.dumps(R)))
