import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/"
r = {
"key": "hyperfine-optical-scaling",
"name": "Atomic scaling laws: nu_opt/(c R_inf) = F(alpha); nu_hf/(c R_inf) ~ alpha^2 g_I (m_e/m_p) F_rel(Z alpha); R_inf proportional to m_e",
"source": {
 "located": "No single paper: textbook atomic-structure scaling (Bohr/Dirac levels; Fermi contact hyperfine with a Casimir-type relativistic factor) as used in the variation-of-constants literature (Prestage-Tjoelker-Maleki PRL 74, 3511 (1995); Karshenboim, Can. J. Phys. 78, 639 (2000) = physics/0008051; Dzuba-Flambaum-Webb PRA 59, 230 (1999); Flambaum-Tedesco PRC 73, 055501 (2006) = nucl-th/0601050). The one source READ is the restatement the tree itself cites: Godun et al., PRL 113, 210801 (2014) = arXiv:1407.0164v2 p.4, which prints the coefficients the laws imply (B_E3 = B_E2 = 0, B_Cs = -1, A_Cs = 2.83) and the condition for B_Cs = -1, but NOT the formulae themselves.",
 "read_status": "READ-VIA-RESTATEMENT",
 "via": "arXiv:1407.0164v2 page text cached verbatim at scratchpad/d67/src/1407.0164.cached.txt (lines 535-570, refs 865-878), from an earlier D67 run. In THIS run alphaXiv answer_pdf_queries (nucl-th/0601050, physics/0008051), get_paper_content and discover_papers all returned 'alphaXiv assistant quota exceeded'; arxiv.org / export.arxiv.org / alphaxiv.org are refused by the egress proxy (CONNECT 403). Prestage 1995, Karshenboim 2000, Dzuba-Flambaum-Webb 1999, Flambaum-Tedesco 2006, Berengut-Flambaum-Kava 2011, Casimir's relativistic hyperfine factor and the Barker-Glover recoil formula are NAMED-NOT-READ. Because the laws are derivable, they were RE-DERIVED here from first principles (sympy) rather than taken from any unread paper."
},
"published_statement": "arXiv:1407.0164v2 p.4 (READ): 'Time variation of alpha and mu is measured via the frequency ratio of two clock transitions r = nu_1/nu_2 using the relation r-dot/r = (A_1 - A_2) alpha-dot/alpha + (B_1 - B_2) mu-dot/mu. The sensitivity coefficients A_i of the relevant atomic transitions are: A_E3 = -5.95 [34], A_E2 = 0.88 [35], and A_Cs = 2.83 [36]. Dependence on mu-dot arises through the nuclear magnetic moment and is negligible for optical transitions (the sensitivity coefficient B_E3 = B_E2 = 0). As the 133Cs nuclear g-factor has negligible sensitivity to changes in the strong interaction [37, 38], an AFM history can also be interpreted to set constraints on mu-dot/mu (B_Cs = -1).' The formula form nu_hf/(c R_inf) ~ alpha^2 g_I (m_e/m_p) F_rel(Z alpha) is the tree's (address.py:62) and was re-derived here (Fermi contact: nu_hf/(c R_inf) = (2/3) alpha^2 g_I g_e (m_e/m_p)(2I+1) Z^3/n^3 for a hydrogen-like s state, sympy). Tree's use: address.py:35-36 'nu_opt / c R_inf = F(alpha). The electron mass CANCELS.'; address.py:60-67 'nu_hf / c R_inf ~ alpha^2 * g_I * (m_e/m_p) * F_rel(Z alpha) ... exponent exactly +1 in mu = m_p/m_e and exactly 2 (plus relativistic corrections) in alpha'; address.py:249-252 'nu_opt is proportional to c R_inf, R_inf to m_e, m_e to the LOCAL v ... d ln(nu_in/nu_out) / d eps = +1 EXACTLY'.",
"published_hypotheses": [
 "P1 (Godun p.4) linear response: r-dot/r = (A_1-A_2) alpha-dot/alpha + (B_1-B_2) mu-dot/mu, i.e. power-law dependence nu ~ alpha^A mu^B at fixed everything else, mu = m_p/m_e.",
 "P2 (Godun p.4) B_opt = 0 is 'negligible', not zero: mu enters optical transitions only through the nuclear magnetic moment (and, not mentioned by Godun, through nuclear mass/recoil and nuclear size -- see rederive B, D).",
 "P3 (Godun p.4) B_Cs = -1 holds 'As the 133Cs nuclear g-factor has negligible sensitivity to changes in the strong interaction [37, 38]' -- g_I fixed is a stated CONDITION.",
 "P4 (Godun p.4, refs [34]-[36]) A_i, including A_Cs = 2.83 (= 2 + K_rel 0.83), are many-body atomic calculations, not measurements.",
 "P5 (physics, re-derived here, rederive A) nu/(c R_inf) depends on m_e only through the dimensionless groups alpha, m_e/M and r_N m_e c/hbar (sympy nullspace, nullity 3); F(alpha) alone requires M -> infinity and r_N -> 0 (point nucleus, infinite mass); QED loops add only alpha and lepton/hadron mass ratios.",
 "P6 (physics, re-derived here, rederive E) the alpha^2 (m_e/m_p)^1 g_I^1 form is the non-relativistic Fermi contact term at first order in the nuclear dipole, g_e and infinite nuclear mass; reduced mass adds (1+m_e/M)^-3; F_rel carries the Z alpha dependence (and, in full, finite-size Breit-Rosenthal / Bohr-Weisskopf terms)."
],
"hypothesis_drift": [
 "NAMED CORRECTLY (no drift): address.py:38-40 carries the optical blindness 'AT TREE LEVEL, FOR A POINT NUCLEUS OF INFINITE MASS'; address.py:41-44 records that Godun calls B_E3 = B_E2 = 0 'negligible', not zero; address.py:47-53 (W10) withdraws 'EXACTLY BLIND' for finite nuclear size; address.py:53-58 names the same-place hypothesis. These match P2 and P5.",
 "DROPPED -- g_I fixed (P3): 'g_I' appears in address.py only inside the formula (lines 62, 615, 1243); nowhere is 'g_I fixed' stated as a hypothesis, and the Godun quote at address.py:434-438 elides with '...' exactly the conditioning sentence 'As the 133Cs nuclear g-factor has negligible sensitivity to changes in the strong interaction [37, 38]' before '(B_Cs = -1)' (same finding as sibling audit 1407.0164). The drop bites in the tree's own setting: a displaced vev moves X_q = m_q/Lambda_QCD by d ln X_q/d ln v = 7/9 (H1) or 1 (H2), which is the strong-interaction change P3 assumes negligible. COMPUTED (rederive G): the optical/Cs coefficient moves by 1.06% per 0.01 of kappa_Cs = d ln g_I(Cs)/d ln X_q (5.3% at |kappa| = 0.05) under both H1 and H2 at S = 0.06; kappa_Cs itself is Flambaum-Tedesco's number and was NOT read here.",
 "WEAKENED -- '+1 EXACTLY' for the transported clock (address.py:249-252, docstring address.py:736-742 'EXACTLY +1'): the site states R_inf ~ m_e, dropping the alpha^2 in R_inf = m_e c alpha^2/(2h) and the tree-level alpha-fixed hypothesis that section 1 (address.py:28-31) names. Under H1 the tree itself seats K_alpha(H1) = 43 alpha/(54 pi) = 1.849653e-3 (address.py:883), and then the coefficient is 1 + (2 + A_opt) K_alpha: COMPUTED 1.00370 (A_opt = 0), 1.00533 (Yb+ E2, A = 0.88 READ), 0.99269 (Yb+ E3, A = -5.95 READ). '+1 EXACTLY' holds under H2 (alpha fixed) and the infinite-mass hypothesis only; with reduced mass alone (hydrogen, H2, S = 0.06) it is 0.999488. The infinite-nuclear-mass hypothesis named at line 39 for same-place blindness is not repeated at the transported site.",
 "DISCREPANCY (tree-internal, conditional on a RECALLED formula) -- recoil vs finite size: finite_size_K_sympy's docstring (address.py:850) says 'recoil (m_e/M) omitted, which only adds' and address.py:50-52 says finite size is 'under H2 ... the LEADING same-place sensitivity'. The non-relativistic reduced mass cancels EXACTLY in a same-atom ratio (rederive B, sympy), but the leading relativistic recoil term -m_r^2 c^2 (f-1)^2/(2M) (Barker-Glover / CODATA form, RECALLED, NAMED-NOT-READ) does not: COMPUTED K_recoil(H2, S = 0.06) = +6.05e-9 for nu(1S-2S)/nu(2P-3D) (either j pair), 7.7 x |K_fs| = 7.87e-10 and of OPPOSITE sign. Independently of the coefficient, the scale alpha^2 m_e/m_p = 2.9e-8 already exceeds |K_fs| by 37x. If the recalled formula is right, recoil, not finite size, is the leading same-place mu-sensitivity of that hydrogen ratio under H2, and it does not 'only add' (it has the opposite sign). Recorded, not repaired; it moves no downstream threshold (both are ~1e-9, far below the optical/Cs channel).",
 "OBSERVATION -- CONTROL 1 (address.py:1255-1256) 'the relativistic remainder is the published 0.83' compares GODUN['A_Cs'] - 2 with 0.83, i.e. Godun's number with itself; it is not a derivation of F_rel. The one-electron point-nucleus Casimir factor 3/(gamma(4 gamma^2 - 1)) (RECALLED, NAMED-NOT-READ) gives K_rel(Cs, Z = 55) = 0.739, not 0.83 (rederive F); the 0.83 is Dzuba-Flambaum-Webb's many-body value as cited by Godun. The tree uses only the integer 2 in A_hyperfine_nonrelativistic() and Godun's 2.83 as data, so nothing downstream rests on the remainder."
],
"data_at_publication": [
 {"quantity": "alpha", "value_then": "1/137.035999084 (address.py:429, CODATA 2018, NAMED-NOT-READ)", "value_now": "7.2973525643e-3 = 1/137.035999177 (CODATA 2022)", "source_now": "scipy.constants 1.17.1 (CODATA 2022), read locally", "moves_conclusion": "No: relative change -6.9e-10; exponents are integers and K_alpha = 43 alpha/(54 pi) moves at 1e-9 relative."},
 {"quantity": "proton rms charge radius r_p (enters K_fs = 28x^2/(14x^2-9), x = r_p/a_0)", "value_then": "0.8414e-15 m (address.py:427, CODATA 2018); pre-2018 CODATA 2014 was 0.8751e-15 (proton-radius puzzle, recalled)", "value_now": "0.84075e-15 m (CODATA 2022)", "source_now": "scipy.constants 1.17.1 (CODATA 2022)", "moves_conclusion": "No: COMPUTED K_fs -7.8654e-10 -> -7.8532e-10 (-0.154%); even the 2014 radius would change it by ~8%; sign and order unchanged."},
 {"quantity": "m_e/m_p (enters B_single = 1/(mu+1), B_hf reduced-mass term, recoil)", "value_then": "M_E_MEV/M_P_MEV = 0.51099895000/938.27208816 (address.py:424-425)", "value_now": "5.446170214889e-4 (CODATA 2022)", "source_now": "scipy.constants 1.17.1", "moves_conclusion": "No: change at 1e-10 relative."},
 {"quantity": "A_Cs = 2 + K_rel", "value_then": "2.83 (Godun p.4 citing Dzuba-Flambaum-Webb 1999; READ via 1407.0164v2)", "value_now": "No newer value read in this run (literature search blocked by quota). One-electron Casimir estimate COMPUTED here: 2.739.", "source_now": "rederive F (formula RECALLED)", "moves_conclusion": "No for the tree: it uses only the integer exponent 2 and cites 2.83 as data; the 0.09 spread is a model difference (point-nucleus single-electron vs many-body), a discrepancy between approximations, not a refutation."},
 {"quantity": "kappa_Cs = d ln g_I(133Cs)/d ln (m_q/Lambda_QCD)", "value_then": "'negligible' (Godun p.4, citing Flambaum-Tedesco 2006, Berengut-Flambaum-Kava 2011)", "value_now": "NOT READ (both papers NAMED-NOT-READ; alphaXiv quota exceeded)", "source_now": "none read", "moves_conclusion": "Conditional, COMPUTED: 1.06% change in the optical/Cs coefficient per 0.01 of kappa_Cs, under H1 and H2 alike; the tree's thresholds are quoted to 2-3 significant figures, so kappa_Cs ~ 0.01 would move the third figure, not the conclusion."},
 {"quantity": "H 1S hyperfine (numerical check of the Fermi form)", "value_then": "n/a (tree does not use it)", "value_now": "1420.405751768 MHz (RECALLED, NAMED-NOT-READ)", "source_now": "recalled hydrogen-maser value", "moves_conclusion": "No: COMPUTED Fermi nu_F = 1418.840091 MHz from CODATA 2022; measured/Fermi - 1 = 1.1035e-3 against a_e = 1.1597e-3, the expected size -- confirms the alpha^2 (m_e/m_p) g_I form numerically."}
],
"rederivation": {
 "method": "sympy",
 "script_path": D + "rederive/hyperfine-optical-scaling.py",
 "outcome": "All 16 checks PASS (exit 0; output in rederive/hyperfine-optical-scaling.out). A: dimensional analysis over (m_e, c, hbar, e^2/4pi eps0, M, r_N) has nullity 3 -> nu/(c R_inf) = F(alpha, Z; m_e/M, r_N m_e c/hbar); F(alpha) alone exactly when M -> inf, r_N -> 0. B: Schrodinger with reduced mass, d ln(nu/cR)/d ln(M/m_e) = 1/(mu+1) = 5.443e-4 for H, cancels exactly in a same-atom ratio (sympy diff = 0). C: sympy.physics.hydrogen.E_nl_dirac for five levels gives nu/(c R_inf) a function of alpha alone with the Bohr NR limit. D (RECALLED recoil formula): K_recoil(H2, S=0.06) = +6.05e-9 for H(1S-2S)/(2P-3D), 7.7x |K_fs| = 7.87e-10 and opposite sign; tree's K_fs closed form reproduced in sympy. E: Fermi contact from SI constants gives nu_hf/(c R_inf) = 2 alpha^2 g_I g_e m_e (2I+1)/(3 m_p) -- exponents alpha 2, m_p -1, m_e +1, g_I 1 EXACT; reduced mass gives B_hf(H) = (2-mu)/(mu+1) = -0.99837; numeric Fermi 1418.840 MHz vs 1420.406 measured, residual 1.10e-3 ~ a_e. F: Casimir K_rel(Cs) = 0.739 vs Godun 0.83. G: g_I variation moves the optical/Cs coefficient 1.06% per 0.01 kappa_Cs. H: transported-clock coefficient 1 + (2+A_opt) K_alpha(H1) = 1.0037 / 1.0053 / 0.9927 (A = 0 / 0.88 / -5.95) vs the tree's +1 EXACTLY; 0.99949 with hydrogen reduced mass under H2.",
 "agrees_with_source": "yes"
},
"later_literature": [
 {"ref": "Flambaum & Tedesco, PRC 73, 055501 (2006), arXiv:nucl-th/0601050", "effect": "extends", "what": "Godun's ref [37] for 'Cs nuclear g-factor has negligible sensitivity to the strong interaction' -- the source of kappa_Cs, i.e. of the hypothesis the tree drops. Content NOT read; its numbers are not used here.", "read_status": "NAMED-NOT-READ (alphaXiv quota exceeded in this run; egress to arxiv.org refused)"},
 {"ref": "Berengut, Flambaum & Kava, PRA 84, 042510 (2011)", "effect": "extends", "what": "Godun's ref [38], the second citation behind B_Cs = -1. NOT read.", "read_status": "NAMED-NOT-READ"},
 {"ref": "Dzuba, Flambaum & Webb, PRA 59, 230 (1999)", "effect": "extends", "what": "Godun's ref [36] for A_Cs = 2.83 (K_rel = 0.83, many-body). Its difference from the one-electron Casimir 0.739 computed here is recorded as a model discrepancy. NOT read.", "read_status": "NAMED-NOT-READ"},
 {"ref": "Barker & Glover (1955) / CODATA adjustments (Mohr, Taylor, Newell et al.), relativistic recoil in hydrogen", "effect": "narrows", "what": "The recoil term used in rederive D is recalled from this line of work; if correct it makes finite nuclear mass, not finite size, the leading H2 same-place sensitivity of the tree's hydrogen ratio. NOT read; the D result is therefore carried as CONDITIONAL.", "read_status": "NAMED-NOT-READ"},
 {"ref": "Godun et al., PRL 113, 210801 (2014), arXiv:1407.0164v2", "effect": "confirms", "what": "Prints B_E3 = B_E2 = 0 ('negligible'), B_Cs = -1 (conditional on g_I), A_Cs = 2.83 -- the coefficients the scaling laws imply; re-derived exponents agree.", "read_status": "READ (cached verbatim page text, src/1407.0164.cached.txt)"}
],
"lacked_data": "M's hypothesis tested. The laws are theorems of atomic structure under named approximations, not fits to data, so no datum the originators lacked can overturn the integer exponents: the dimensional-analysis and Fermi-contact derivations (rederive A, E) hold for any values of the constants. What data CAN move are the non-integer pieces, and each was checked: (i) the proton radius moved 4% (0.8751 -> 0.8414 -> 0.84075 fm) after 2010 muonic-hydrogen data -- COMPUTED effect on the tree's finite-size K is -0.154% (2018 -> 2022), ~8% from the 2014 value, sign and order unchanged; (ii) CODATA 2018 -> 2022 alpha and m_e/m_p move at 1e-9 -- no effect; (iii) the Cs relativistic factor is a calculation, and the spread between approximations (0.739 Casimir vs 0.83 many-body) is 0.09 -- no effect on the tree, which uses only the integer 2; (iv) kappa_Cs, the one number that would enter the tree's own displaced-vev scenario, was not read here -- COMPUTED sensitivity 1.06% per 0.01, so a kappa of the order Godun calls 'negligible' does not move the tree's conclusions. Evidence against M's hypothesis for this result: every re-derived exponent agrees with Godun's published coefficients; evidence for incompleteness: the laws' own hypotheses (infinite nuclear mass, fixed g_I, tree-level alpha) are exactly where the tree's use goes beyond them, and those are narrowings of use, not errors in the physics.",
"grade": "NARROWED",
"grade_evidence": "The external statements are correct under their hypotheses and re-derive exactly (sympy, 16/16 PASS): nu/(c R_inf) is a function of alpha alone iff M -> inf and r_N -> 0 (nullity-3 dimensional analysis; Dirac levels from sympy.physics.hydrogen); nu_hf/(c R_inf) = (2/3) alpha^2 g_I g_e (m_e/m_p)(2I+1) at Fermi-contact order, exponents 2, +1, 1 exact; numeric Fermi 1418.84 MHz vs 1420.41 measured (residual ~ a_e). Godun's published B/A coefficients (READ) agree. The tree's use is narrower-hypothesis than it states in three places: (1) g_I fixed is a condition in the source (Godun p.4) and is never named in address.py -- the quote at 434-438 elides it -- while the tree's displaced vev moves m_q/Lambda_QCD, the variable it concerns (effect 1.06% per 0.01 kappa_Cs, COMPUTED; kappa_Cs NOT read); (2) '+1 EXACTLY' for the transported clock (address.py:249-252, 736-742) holds only with alpha fixed and infinite nuclear mass; under the tree's own H1 K_alpha it is 1.0037 / 1.0053 / 0.9927 (COMPUTED); (3) conditional on a recalled recoil formula, the claim that finite size is the leading H2 same-place sensitivity and that recoil 'only adds' (address.py:50-52, 850) is contradicted by K_recoil = +6.05e-9 vs K_fs = -7.87e-10. No moved datum moves a conclusion (largest: r_p, -0.154% in K_fs). Not WRONG: nothing in the external result is refuted; the drift is in the tree's statement of scope.",
"what_would_change_the_grade": "To STANDS: the tree names 'g_I fixed' (with kappa_Cs read from Flambaum-Tedesco and shown negligible under a displaced vev) and scopes '+1 EXACTLY' to alpha fixed / infinite nuclear mass (or H2). To DATA-DEPENDENT: a read kappa_Cs large enough (|kappa| >~ 0.05) that the optical/Cs threshold moves at the precision the tree quotes. To OPEN on item (3): reading the Barker-Glover / CODATA recoil formula and finding the recalled term wrong -- that would remove the recoil discrepancy but not items (1)-(2). Nothing identified would make the external result WRONG.",
"reverify_command": "python3 " + D + "rederive/hyperfine-optical-scaling.py  # exits 0 on 16/16 PASS; sed -n 535,570p " + D + "src/1407.0164.cached.txt  # Godun p.4 coefficients and g-factor condition; grep -n 'g_I\\|EXACTLY\\|only adds\\|LEADING' /home/user/Claude-Method-Works/research/warp-drive/address.py",
"report_path": D + "audits/hyperfine-optical-scaling.json"
}
json.dump(r, open(D + "audits/hyperfine-optical-scaling.json", "w"), indent=1)
print("ok")
