import json
S="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R=S+"/rederive/relativistic-causality-signals-at-most-c.py"
d={
"key":"relativistic-causality-signals-at-most-c",
"name":"Special-relativistic causality: classical signals travel at <= c",
"source":{
 "located":"No single paper. This is the textbook principle (Einstein 1905; Sommerfeld 1907 and Brillouin 1914 on the front velocity), and none of those three is on arXiv. READ at source instead, in two arXiv papers that state the principle and its hypotheses exactly. (a) Liberati, Sonego, Visser, 'Faster-than-c signals, special relativity, and causality', gr-qc/0107091 (Ann. Phys. 298, 2002): p.1 abstract; p.2 fn 1-2; p.3-4 sec.2; p.10-12 sec.3.1 incl. fn 13; p.16 eq.3.12; p.18 conclusion. (b) Geroch, 'Faster Than Light?', arXiv:1005.1614 (2010): p.1-2, p.6-7 (causal cones), p.8 (initial-value formulation), p.9-10 (sec.3). Also READ: Scharnhorst hep-th/9810221 (1998) p.2-6, eq.(3) front velocity and eq.(10) n_perp(0).",
 "read_status":"READ-VIA-RESTATEMENT",
 "via":"gr-qc/0107091 and arXiv:1005.1614, both READ in full on the pages cited. Einstein 1905, Sommerfeld 1907 (Phys. Z. 8, 841) and Brillouin (Wave Propagation and Group Velocity, 1960) are NAMED-NOT-READ; they are cited through LSV refs [6],[8]-[12] and Fearn 0706.0553 p.2."},
"published_statement":"LSV 2002 abstract (p.1): 'special relativity can easily accommodate -- indeed, does not exclude -- faster-than-c signalling at the kinematical level. As far as causality is concerned, it is impossible to make statements of general validity, without specifying at least some features of the tachyonic propagation.' p.3-4: 'There is a logical distinction between the concept of an invariant speed, and that of a maximum speed. Contrary to widespread belief, special relativity only requires, for its kinematical consistency, that there be an invariant speed.' p.2: superluminal group velocities 'do not create any problem of principle, because the signal velocity still has c as an upper bound'. fn 2: signal velocity = phase velocity at infinite frequency = front velocity. fn 13 (p.11): with canonical kinetic terms 'the characteristics are the usual ones, and the signal speed is c, regardless of whether the proper mass is positive, zero, or imaginary ... quantum mechanically the signal speed is also limited to c'. p.12: the tachyonic anti-telephone paradox requires 'that, given an arbitrary reference frame, it is always possible to send a tachyon backward in time in that frame'. Geroch 2010 p.6-7: 'For many examples -- Maxwell's equations, the Klein-Gordon equation, the neutrino or Dirac equations, the spin-s field equation and Einstein's equation -- the causal cone is precisely the future light cone'; p.8: 'solutions of Eqn. (1) send signals that always lie within the causal cones'; p.10: the cones of other systems 'could very well lie outside the null cones of special relativity ... None of this would contradict our fundamental ideas about how physics is structured.'",
"published_hypotheses":[
 "H_SR (LSV p.4): (i) in an inertial frame space is homogeneous, isotropic and Euclidean, and time is homogeneous; (ii) the principle of relativity; (iii) pre-causality. These give the Lorentz group with an INVARIANT speed C, whose value is fixed by experiment (p.10: 'We know that C coincides, to a very good accuracy, with ... c ... tiny deviations from this empirically established equality are logically possible'). They do NOT give a MAXIMUM speed.",
 "H_cone (Geroch p.6-8; LSV fn 13): a field sends signals only inside the causal cone of its (hyperbolizable, first-order quasilinear) field equations. 'Signals <= c' holds exactly when every available channel's causal cone lies inside the light cone. This is shown for Maxwell, Klein-Gordon (either sign of m^2), Dirac, spin-s and Einstein. It is a property of each matter equation, not of SR: a fluid with dp/drho > 1 has a superluminal sound cone and still a well-posed initial-value problem (Geroch p.7).",
 "H_front (LSV fn 2; Scharnhorst eq.3; de Rham-Tolley 2007.01847 eq.2.1): 'signal speed' means the front velocity c/n(infinity), i.e. the support of the retarded propagator. It does not mean the phase or group velocity, and those can exceed c without any conflict (LSV p.2).",
 "H_vac (LSV fn 1; Scharnhorst p.6): 'c' is the speed of light 'in unbounded empty space'. A modified QED vacuum (Casimir plates, background fields, curvature) is a dispersive medium whose front velocity must be computed. For the Casimir vacuum, Kramers-Kronig plus passivity (Im n >= 0) give front velocity > c ('alternative A'). This is contested: Fearn 0706.0553 disputes the dispersion relation; Milonni-Svozil and Ben-Menahem (1990, restated by Fearn p.6-7) show it is unmeasurable.",
 "H_caus (LSV p.12-18): paradoxes need superluminal signals that can be sent backwards in time in EVERY frame. If the superluminal speed is fixed in one preferred frame (for example the Casimir plates' rest frame), the causal structure can be stably causal (LSV p.16 theorem, citing Hawking-Ellis p.198-199)."],
"hypothesis_drift":[
 "OVERSTATED (wording, not numbers) at transit.py:44 'IDENTICAL, and provably so.' and transit.py:249 'ZERO, and provably.' What the tree proves is the identity advantage_over_light(D) = D/c - D/c (transit.py:145-146). It is 0 for every c > 0 (sympy, rederive check 1a) and bit-exact 0.0 at all four DISTANCES (check 1b). The physical content, that no available channel is faster than D/c, is H_cone+H_vac. The tree neither proves that nor names it, and it is not a theorem of SR (LSV p.3-4, p.10; Geroch p.2, p.10). The tree's own ledger states it correctly: ledger.py:602-603 D23 'ZERO BY CONSTRUCTION, not by measurement'. The drift is transit.py's 'provably' against its own ledger row.",
 "DROPPED H_cone / H_vac. The canonical hypothesis list (owner transit.py) names 'flat spacetime, straight-line distance D, no metric engineering on the classical path'. Flat spacetime is weaker than 'unbounded empty space': the Scharnhorst Casimir vacuum is flat, has no metric engineering, and is the one QED case where the front velocity is argued to exceed c (hep-th/9810221 p.6, alternative A). transit.py:37-38 ('two classical bits arrive through ordinary space at <= c') comes closer to H_vac but does not name it. Effect on the tree's numbers, COMPUTED (rederive 5a-5d): along the plates the group velocity is kpar/omega <= c exactly (sympy), so a Casimir channel gains NOTHING over any D much larger than L. Perpendicular to the plates the gain is bounded by one gap: dc/c = 11 pi^2/90^2 alpha^2 (lambda_C/L)^4 = 1.59e-32 at L = 1 um, so at most L/c x dc/c = 5.3e-47 s. That rests on the ASSUMPTION that conducting plates cannot be stacked and crossed; the assumption is named, not read. The printed 0.000 at transit.py:42 and the selftest tol 1e-9 at transit.py:346 are unaffected by 38+ orders of magnitude.",
 "DECLARED, NOT COMPUTED: transit.py:153 'BEATS_LIGHT = False' is a constant (check 1d). The selftest row transit.py:347-348 checks the flag against itself, and transit.py:345-346 checks an identity that cannot fail for any c. Neither tests H_cone. That is appropriate once the channel is defined at c, but the flag's truth rests on H_cone+H_vac, not on the selftest.",
 "NO DRIFT on H_front. The tree's channel speed is exactly c (transit.py:145), which is the upper bound the front velocity allows. A real channel (radio through interstellar plasma, cold-plasma group delay) is only slower, so the idealisation errs TOWARD the channel and cannot move 'advantage <= 0' (sibling audit si-speed-of-light records the same).",
 "NO DRIFT at specthm.py:1184-1212 (R11). 'it does not beat light (BEATS_LIGHT = %s)' is stated under H_tele and inherits exactly the transit.py flag, so it carries the same unnamed H_cone+H_vac and nothing more.",
 "NO DRIFT on curvature. 'Flat spacetime' is NAMED in the canonical hypotheses. In curved spacetime, low-energy superluminality (Drummond-Hathrell) exists but is unresolvable within the EFT (de Rham-Tolley 2007.01847 p.4-7, eq.1.4, sec.6). Macroscopic metric shortcuts are the warp board's other refusals and are not audited here.",
 "OUT OF SCOPE here: the canonical hypothesis 'no-signalling (entry above) forbids any faster readout' is a separate key and is not audited in this entry."],
"data_at_publication":[
 {"quantity":"c (SI), the only constant in advantage_over_light","value_then":"2.99792458e8 m/s (transit.py:142)","value_now":"299 792 458 m/s exact (CODATA 2022, arXiv:2409.03787 Table XXXII, per sibling audit si-speed-of-light)","source_now":"arXiv:2409.03787","moves_conclusion":"No. c is defined, and it cancels identically in D/c - D/c (rederive 1a, 1c)."},
 {"quantity":"four distances D (Earth-Moon 3.844e8 m, Earth-Mars min 5.46e10 m, Earth-Proxima 4.0175e16 m, Milky Way crossing 9.46e20 m)","value_then":"tree literals (transit.py:143-144)","value_now":"not re-read at source here. Computed light times are 1.282 s, 182.1 s, 4.2465 yr and 99,992 yr.","source_now":"rederive check 1 printout","moves_conclusion":"No. The advantage is 0 for every D, so no distance datum can move it. The distances matter only to D23's setup time (4.2465 yr at Proxima), which is owned by a different key."},
 {"quantity":"gravity-sector signal speed (tests H_cone for gravity)","value_then":"not available to Einstein 1905 or Sommerfeld/Brillouin; only indirect bounds before 2017","value_now":"-3e-15 <= (v_GW - v_EM)/v_EM <= +7e-16. This assumes emission offsets of 0 to 10 s over D = 26 Mpc; a (-100 s, 1000 s) window broadens it by 2 orders.","source_now":"arXiv:1710.05834 eq.(1), p.6. Recomputed as 6.50e-16 and -3.09e-15 (rederive 6).","moves_conclusion":"No. It CONFIRMS that gravity's cone coincides with light's to 1e-15, within the stated emission-time assumption."},
 {"quantity":"neutrino signal speed (tests H_cone for the neutrino sector)","value_then":"2011 OPERA v1 anomaly (value NAMED-NOT-READ); earlier MINOS (v-c)/c = (5.1 +- 2.9)e-5 and SN1987A |v-c|/c < 2e-9 (both restated in 1109.4897v4 p.2)","value_now":"(v-c)/c = (2.7 +- 3.1 stat +3.4/-3.3 sys) x 1e-6, consistent with 0. The anomaly was traced to instrumental causes: fibre-delay recalibration and a 0.124 ppm master-clock oscillator offset (v4 sec.6.1, p.13-17).","source_now":"arXiv:1109.4897v4 abstract and p.24-25. Recomputed 2.67e-6 (rederive 7).","moves_conclusion":"No. The one widely reported apparent datum against the principle was instrumental. Named hypothesis: the corrected analysis is taken as READ."},
 {"quantity":"Scharnhorst speed excess in a Casimir vacuum (the one QED-predicted front-velocity excess in flat spacetime)","value_then":"none before 1990","value_now":"n_perp(0) = 1 - 11 pi^2/90^2 alpha^2/(mL)^4 (hep-th/9810221 eq.10), so dc/c = 1.59e-32 at L = 1 um and 1.59e-36 at L = 10 um. Unmeasurable per Milonni-Svozil 1990 and Ben-Menahem 1990 (restated in Fearn 0706.0553 p.6-7; NAMED-NOT-READ). The front-velocity status rests on KK + passivity and is contested (Fearn).","source_now":"hep-th/9810221 p.5-6. Computed in rederive 5a.","moves_conclusion":"No, not for the tree's channel. The along-plate gain is exactly 0 (5c), and the perpendicular gain is at most about 5e-47 s per micron gap (5d plus the one-gap bound). It DOES narrow the universal wording 'signals travel at <= c' to unbounded vacuum."}],
"rederivation":{"method":"sympy","script_path":R,
 "outcome":"20/20 PASS (exit 0). (1) advantage_over_light is the identity D/c - D/c = 0 (sympy); bit-exact 0.0 at all four transit.DISTANCES; C_SI = 299792458 exactly; BEATS_LIGHT is a declared constant. (2) With channel speed v = c*lam, delay = D(1-lam)/(c*lam): advantage <= 0 iff lam <= 1, so the conclusion is exactly as strong as the hypothesis v <= c and no stronger. (3) Klein-Gordon front velocity lim omega/k = 1 for m^2 > 0, = 0 and < 0. The tachyonic group velocity is 1.1547 at k = 2|m|. The principal symbol is independent of m^2, which reproduces LSV fn 13 and Geroch p.7. (4) The fluid sound cone has boundary speed^2 = dp/drho, and a spacelike direction lies in it iff dp/drho > 1, so H_cone is an equation-of-state condition, not SR. (5) Scharnhorst dc/c = 1.587e-32 at 1 um. The along-plate group velocity kpar/omega <= 1 exactly; the perpendicular group velocity is sqrt(1+xi). Fearn's '1.6e-36 at 1 um' equals eq.(10) at 10 um. (6) GW170817 bounds reproduced: 6.50e-16 and -3.09e-15. (7) OPERA 2.67e-6 reproduced. transit.py --selftest also PASSES at HEAD 4fb7bc3 (the file is imported read-only).",
 "agrees_with_source":"yes"},
"later_literature":[
 {"ref":"Liberati, Sonego, Visser, gr-qc/0107091 (2002)","effect":"narrows","what":"SR requires an invariant speed, not a maximum one, and faster-than-c signalling is kinematically compatible with it. Paradoxes need signals sent backwards in time in every frame. Scharnhorst photons have a preferred-frame speed and a stably causal effective metric.","read_status":"READ (p.1-4, 10-13, 16-18, 21)"},
 {"ref":"Geroch, arXiv:1005.1614 (2010)","effect":"narrows","what":"Each hyperbolizable system carries its own causal cones, and signals stay inside them. Maxwell, KG (either sign of m^2), Dirac, spin-s and Einstein have the light cone as causal cone; a superluminal fluid is equally well posed. The universal c limit is a commonality of cones, not a principle of SR.","read_status":"READ (full, p.1-13)"},
 {"ref":"Scharnhorst, hep-th/9810221 (1998)","effect":"contested","what":"In the Casimir vacuum n_perp(0) < 1. Kramers-Kronig plus passivity gives front velocity > c (alternative A). The alternatives are a failure of KK (B) or an active vacuum (C). The effect is unmeasurably small.","read_status":"READ (p.1-7)"},
 {"ref":"Fearn, arXiv:0706.0553 (2007)","effect":"contested","what":"Argues that the Barton-Scharnhorst dispersion relation is approximate, that the effect cannot be measured (restating Milonni-Svozil and Ben-Menahem), and that it would conflict with SR without an invariant length. DISCREPANCY recorded, not repaired: p.9 gives dc/c = 1.6e-36 'at micron length scale (1 um)', but eq.(10) gives 1.59e-32 at 1 um and 1.59e-36 at 10 um (rederive 5b). Likewise '1 fm -> 1.6', where eq.(10) gives about 1.6e4 at 1 fm, which is also outside the formula's validity mL >> 1. This is a misprint-class discrepancy in a later paper. It must not be quoted as an error until the journal version is read.","read_status":"READ (p.1-10)"},
 {"ref":"de Rham, Tolley, arXiv:2007.01847 (2020)","effect":"extends","what":"Relativistic causality means front velocity v_f <= 1 and a retarded propagator supported inside the cone (eq.2.1-2.2). Low-energy superluminality in curved backgrounds (Drummond-Hathrell for QED, EFT of gravity for GWs) gives time advances that are unresolvable (|dT| << 1/omega) inside the EFT's validity. In flat Minkowski space any homogeneous superluminality would integrate up to a macroscopic violation, hence c_s <= 1 there (eq.3.4).","read_status":"READ (p.1-10, 13, 30-38)"},
 {"ref":"LIGO/Virgo/Fermi/INTEGRAL, arXiv:1710.05834 (2017)","effect":"confirms","what":"The gravity-sector speed equals the speed of light to within -3e-15 and +7e-16, under an assumed emission offset of 0 to 10 s.","read_status":"READ (p.1-7)"},
 {"ref":"OPERA, arXiv:1109.4897v4 (2012)","effect":"confirms","what":"Neutrino (v-c)/c = (2.7 +- 3.1 +3.4/-3.3)e-6. The 2011 anomaly was traced to instrumental sources.","read_status":"READ (abstract, p.2, 13-17, 19-30)"},
 {"ref":"arXiv:2609.14155 'Phonon Scharnhorst effect' (2026)","effect":"extends","what":"Acoustic analogue of the Scharnhorst shift (from the title and abstract in the discover_papers listing only).","read_status":"NAMED-NOT-READ"}],
"lacked_data":"The founders of the principle (Einstein 1905, Sommerfeld 1907, Brillouin 1914) had no QED vacuum polarization, no neutrino or gravitational-wave timing, and no fast-light media. Later data narrowed what the principle MEANS without producing a counter-instance. (a) Measured superluminal group velocities (Wang-Kuzmich-Dogariu 2000, cited in LSV ref [1]; NAMED-NOT-READ) leave the front velocity <= c (LSV p.2). The data confirmed Sommerfeld-Brillouin's front/group distinction rather than refuting it. (b) QED since 1990 predicts a front velocity above c in a bounded (Casimir) vacuum, and in curved backgrounds a low-energy one (Scharnhorst 1998; Drummond-Hathrell via de Rham-Tolley). This narrows the principle to 'unbounded vacuum' and to 'front velocity'. It is theoretical, contested (Fearn 2007), unmeasurable (Milonni-Svozil), and COMPUTED here to give zero advantage along the plates and at most about 5e-47 s across a micron gap. (c) The one apparent measured counter-instance, OPERA 2011, was instrumental (1109.4897v4 sec.6.1). (d) GW170817 (2017) and OPERA 2012 extend H_cone to gravity (1e-15) and to neutrinos (few e-6). Verdict on M's hypothesis for THIS result: the new data sharpened the hypotheses (H_front, H_vac, H_cone). No datum has moved the conclusion the tree draws, advantage <= 0 for a classical channel over flat unbounded vacuum. Evidence against M's suspicion: every measurement since 1905 that could have shown a faster channel either agrees with c or was instrumental. Evidence for it, in a narrowed sense: the textbook wording 'SR forbids faster-than-c signals' is inaccurate as a statement about SR (LSV, Geroch). The limit lives in the field equations' cones, not in relativity's kinematics.",
"grade":"NARROWED",
"grade_evidence":"The published principle, READ via LSV 2002 and Geroch 2010, holds under hypotheses the tree does not name. H_cone: every channel's characteristic cone lies inside the light cone, shown for Maxwell, KG (either sign of m^2), Dirac, spin-s and Einstein, but not a theorem of SR. H_vac: unbounded vacuum; flat spacetime is not enough, since the Casimir vacuum is flat and is argued to have front velocity > c. H_front: the signal speed is the front velocity. transit.py:44 and :249 call the zero advantage 'provably so', and the only proof in the tree is the identity D/c - D/c (rederive 1a/1b). The tree's own ledger row D23 (ledger.py:602-603) says correctly 'ZERO BY CONSTRUCTION, not by measurement'. So the tree uses the principle on the wider class 'flat spacetime', and the source supports it on the narrower class 'unbounded vacuum, canonical-cone fields, front velocity'. That is a dropped hypothesis, which is the NARROWED criterion. NOT WRONG: no counterexample to the tree's conclusion exists. The one flat-spacetime exception gives exactly zero along-plate advantage and at most about 5.3e-47 s per 1 um gap (rederive 5). No measured datum moves the conclusion: GW170817 and OPERA 2012 confirm it. NOT DATA-DEPENDENT: c is exact and cancels identically. Over-representation checked both ways: the narrowing is in the WORDING 'provably', not in any number the tree prints. BEATS_LIGHT = False and D23's 0.000 stand for the tree's EM channel in unbounded vacuum, where Maxwell's causal cone is the light cone (Geroch p.6).",
"what_would_change_the_grade":"To STANDS: transit.py's 'provably' carries its conditional, 'given H_cone and H_vac: every available channel's causal cone inside the light cone, in unbounded vacuum', as ledger D23 already does ('by construction'). The same result follows if the canonical hypothesis 'flat spacetime' is widened to 'unbounded (unmodified) vacuum, fields with canonical kinetic terms'. To WRONG for the tree's use: a measured, resolvable front velocity above c in unbounded flat vacuum for any field that can carry 2 bits. None is known; GW170817 bounds gravity at +7e-16 and OPERA bounds neutrinos at about 1e-5. A macroscopic Scharnhorst channel would do it too. Along the plates one is excluded by the COMPUTED group velocity kpar/omega <= c; across stacked plates it is excluded only by the NAMED assumption that the conducting plates are opaque, which was not read here. To DATA-DEPENDENT: a positive, confirmed deviation of any sector's signal speed from c (for example a future multi-messenger lag that scales with distance).",
"reverify_command":"python3 "+R+" && python3 /home/user/Claude-Method-Works/research/warp-drive/transit.py --selftest",
"report_path":S+"/audits/relativistic-causality-signals-at-most-c.json"}
json.dump(d,open(d["report_path"],"w"),indent=1,ensure_ascii=False)
print("ok", len(json.dumps(d)))
