import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
r = {
"key": "gr-qc/0209075#renorm-4.4",
"name": "AMM renormalisation: three subtractions at k^2 = 0; scalar sector (4.5b) carries overall k^2, no k-independent term",
"source": {
  "located": "arXiv gr-qc/0209075 v1 (21 Sep 2002), Anderson, Molina-Paris, Mottola, 'Linear Response, Validity of Semi-Classical Gravity, and the Stability of Flat Space', PRD 67, 024026 (2003); Sec. IV pp. 10-13 (eqs. 4.1-4.12), App. B pp. 17-21 (B37-B47)",
  "read_status": "READ",
  "via": "alphaXiv answer_pdf_queries (pages 1, 8, 10, 11, 12, 13, 17, 19, 21 returned) plus the full text layer banked at d67/amm_0209075.txt (lines 1760-2330, 4540-4760). The text layer drops minus signs (c_AB printed 'diag(1; 1)'); no conclusion here rests on an unrestored sign."
},
"published_statement": "p. 11, verbatim: 'this is easily accomplished by subtracting the first three terms in its Taylor series expansion around k^2 = 0, and defining the renormalized real part of the retarded correlation function by Re[Pi^(i)(ret)(k^2)]_R = Re{Pi(k^2) - Pi(0) - k^2 dPi/dk^2|_0 - (k^2)^2/2 d^2Pi/d(k^2)^2|_0} = -(k^2)^3 P int_0^oo ds rho^(i)(s)/(s^3 (s+k^2)) (4.4) ... The three subtractions in (4.4) correspond physically to renormalizing the coefficients of the cosmological constant (Lambda), Newton's constant (1/G_N), and the coefficients of the fourth order terms (alpha and beta). These are of order (k^2)^0, k^2 and (k^2)^2 respectively. The renormalized values of these parameters at k^2 = 0 are what appear then on the left hand side of (2.9). The singular local term M in (4.1) is effectively removed by these subtractions in flat space as well, so that the entire linear response eq. becomes well-defined and covariant.' Then (4.5a) k^2[2 alpha k^2 + 1/(8 pi G_N) + (k^2)^2 int ds rho^(T)/(s^3(s+k^2-i eps sgn k^0))] = 0 and (4.5b) k^2[12 beta k^2 - 1/(4 pi G_N) + (k^2)^2 int ds rho^(S)/(s^3(s+k^2-i eps sgn k^0))] = 0.",
"published_hypotheses": [
  "A1 flat background: 'Flat spacetime is a solution of the semi-classical Einstein equations for vanishing expectation value of T_ab and cosmological term, with the quantum matter field in its Lorentz invariant vacuum ground state' (p. 10)",
  "A2 large-N free scalar fields, arbitrary mass m > 0 and curvature coupling xi, CTP in-in effective action (abstract, Sec. II-III)",
  "A3 Kallen-Lehmann representation (4.2) with positive Lorentz-invariant spectral functions rho^(i)(s), support s > 4m^2 for the scalar example (p. 11, B37a,b)",
  "A4 renormalisation by subtraction of the allowed covariant counterterms up to dimension four, realised as three Taylor subtractions at k^2 = 0 (p. 11); requires m > 0: 'This definition is no longer tenable in the zero mass limit' -- then renormalise at k^2 = mu^2 != 0, (4.10) (p. 12)",
  "A5 at xi = 1/6 only two subtractions are needed in the scalar sector, (4.12) (p. 13)",
  "A6 the scalar-sector overall k^2 = 0 solution is removed as non-dynamical by the constraints; 'a finite number of non-propagating (global) modes in the scalar sector at k = 0 ... We do not treat this possibility' (p. 12)"
],
"hypothesis_drift": [
  "NONE on the quoted text: linstab.py:106-110 reproduces AMM p. 11 verbatim ('three subtractions at k^2 = 0 -- cosmological constant, 1/G_N, and (alpha, beta)'; 'the renormalized values of these parameters at k^2 = 0 are what appear then on the left hand side of (2.9)') and the overall-k^2 structure of (4.5b). linstab.py names only (4.5b); (4.5a) carries the same overall k^2 -- a narrower statement than the source, not a drift.",
  "WEAKENED (framing), linstab.py:166-168 and the H4 wording in canonical: 'AMM's k^2 = 0 subtraction is the choice that leaves no k-independent term'. In AMM the absence of a k^0 term is the conjunction of the (k^2)^0 subtraction WITH hypothesis A1 (Lambda_R = 0, <T> = 0 on the flat background) and AMM's identification of the k^0 coefficient of the linear response with the Lambda of (2.9). That identification is exactly what GMMPS (2604.01047, Thm 3.6, pp. 32-33) do NOT make: they fix alpha_1 (their cosmological-constant role, p. 22) by the background condition and separately fix alpha~^S_1 = 1/(64 pi^2) by general local covariance + perturbative agreement. The subtraction POINT (k^2 = 0 vs mu^2) is not what decides the k^0 term. linstab.py:181-183 already records that which condition is right is 'not adjudicated here'; the drift is in the word 'choice' standing alone, not in the conclusion.",
  "DROPPED, H4 as carried in canonical: m > 0 is a hypothesis of the k^2 = 0 scheme (AMM p. 12, (4.10)); linstab.py:99 carries 'arbitrary mass m > 0' in the SETTING, so the tree holds it one level up, not in H4.",
  "SCOPE, linstab.py:167-168 'i.e. the alpha~^S_1 = 0 case': computed here (C7) the identification holds at order k^0 ONLY. AMM's thrice-subtracted polarization and GMMPS's gamma (a-gamma)^2 J(gamma) differ by a polynomial c1 gamma + c2 gamma^2 with zero constant term, so AMM's scheme also differs from GMMPS at alpha~^S_1 = 0 by finite renormalisations of 1/G and beta. The tree's dependents (LITERATURE_SPLIT_IS_ONE_CONSTANT, linstab.py:344-349) use only the k^0 term (F_S(0) = -b_0), so this does not move them.",
  "CONTEXT, linstab.py:168 'where gamma = 0 is an exact root': gamma = 0 is a root of GMMPS's F_S at alpha~^S_1 = 0; AMM (A6, p. 12) remove the corresponding scalar k^2 = 0 solution as non-dynamical and do not treat k = 0 global modes. The tree records this as NOT TREATED (linstab.py:122-124) and ALPHA_ZERO_ROOT_GROWTH = 'OPEN' (linstab.py:352-353), so no over-claim results."
],
"data_at_publication": [
  {"quantity": "numerical inputs to the conclusion 'no k-independent term survives in (4.5a)/(4.5b)'",
   "value_then": "none -- the statement is structural (renormalisation scheme plus spectral representation); m, xi, G_N, alpha, beta enter as symbols",
   "value_now": "none",
   "source_now": "n/a (canonical data_used = [])",
   "moves_conclusion": "no -- C2/C3 hold for every m > 0 and xi tested (xi = 0, 0.3), and E(0) = 0 identically in G, alpha, beta"}
],
"rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/gr-qc_0209075_renorm-4.4.py",
  "outcome": "ALL 20 CHECKS PASS (output banked at rederive/gr-qc_0209075_renorm-4.4.out). C1 (4.4) kernel identity 1/(s+x) - [1/s - x/s^2 + x^2/s^3] = -x^3/(s^3(s+x)) exact. C2 F^(T), F^(S) (xi = 0, 0.3) -> 0 linearly as k^2 -> 0 (F/k^2 -> int rho/s^4 to 1e-7). C3 E_T(0) = E_S(0) = 0 exactly; dE/dk^2(0) = +1/(8 pi G) (T), -1/(4 pi G) (S): k^2 = 0 is a simple root and nothing k-independent survives. C4 B44 closed form (signs restored by the k^2 -> 0 limit) equals the numerical integral to 1.8e-14; bracket -> 2/(7z^2). C5 log slopes 1/(960 pi^2) (4.9) and (1-6xi)^2/(96 pi^2) (4.11) to 1e-6; (4.10) coefficient 1/(1920 pi^2) consistent. C6 rho^S ~ (s-a)^2 with a = 2m^2/(6xi-1) and rho^T ~ (s-4m^2)^2 -- the same a as GMMPS (5.1), (5.2). C7 AMM's and a GMMPS-type polarization differ by gamma*a^2 int w/s^2 + gamma^2 * (...) with NO gamma^0 term: the k-independent term in GMMPS's F_S is b_0 (alpha~^S_1) alone.",
  "agrees_with_source": "yes"
},
"later_literature": [
  {"ref": "arXiv:2604.01047 v1 (Galanda, Meda, Murro, Pinamonti, Schmid 2026, GMMPS)",
   "effect": "contested",
   "what": "Same system (one massive KG field, Minkowski vacuum), past-compact forcing problem, de Donder gauge. (3.16): the S equation carries a local k-independent term alpha~^S_1 m^4 h^S; Thm 3.6 fixes alpha~^S_1 = 1/(64 pi^2), alpha~^TT_1 = 0 by general local covariance and perturbative agreement, after alpha_1 ('plays the role of a cosmological constant', p. 22) is fixed by the background. Remark 3.5 and 5.2.1: 'This behaviour differs in a significant way from the analysis presented in Anderson et al. ... originated by the choice of the renormalisation parameters done in Theorem 3.6'. This contests AMM's renormalisation CONDITION, not AMM's algebra: with AMM's condition the k^0 term vanishes (C3, C7). Which condition is physically right is not adjudicated here.",
   "read_status": "READ at alphaXiv pp. 1, 2, 9, 22, 32, 33, 37, 40, 59, 60, 62"},
  {"ref": "arXiv:2512.00503 v2 (Ishibashi, Maeda, Okamura 2025)",
   "effect": "extends",
   "what": "Holographic semiclassical gravity (strongly coupled CFT). Cites AMM as ref. [9]. Renormalisation by absorbing the non-negative powers of m^2 into alpha_i (pp. 10-11); the perturbed Minkowski equations are proportional to m^2 on both sides ((4.25); p. 12 'both sides of the perturbed equations are proportional to m^2' for d = 5), i.e. no k-independent term, the same structure as AMM (4.5). d = 4 Minkowski is unstable for gamma_4 >= gamma_4* (Table 1, p. 3). Different matter; does not test AMM's scalar result, and whether its instability sits at a sub-Planckian scale was not read.",
   "read_status": "READ at alphaXiv pp. 1-5, 8, 9, 11-14, 16, 17, 24, 25"}
],
"lacked_data": "M's hypothesis tested for THIS result. What AMM had (2002): the Kallen-Lehmann representation, the explicit rho^(T), rho^(S) of a free massive scalar (B37, agreeing with their refs [28],[29]), dimensional regularisation, and Lambda > 0 already known (p. 2: Lambda 'may be taken to be zero in some applications'). The result uses NO measured datum: it is a renormalisation scheme plus an identity, re-derived exactly here (C1-C3). What came later is not data but a THEORETICAL principle applied to this question: GMMPS 2026 use general local covariance + perturbative agreement to fix the k^0 coefficient differently (alpha~^S_1 = 1/(64 pi^2)), which AMM's k^2 = 0 identification sets to zero. Evidence against M's hypothesis for this key: no datum enters, so none can move it. Evidence for a later-knowledge effect: the renormalisation CONDITION AMM impose is contested by a later framework (2604.01047), and the split is exactly the k^0 term this key describes (C7). That is a dispute over renormalisation conditions, not missing data, and it is not adjudicated here. AMM's statement of what THEIR scheme does is correct.",
"grade": "STANDS",
"grade_evidence": "READ at source (alphaXiv p. 11): the tree's quotation at linstab.py:106-110 is verbatim, and (4.5a)/(4.5b) carry an overall k^2. Re-derived (20/20 PASS): the (4.4) subtraction identity is exact; F^(T), F^(S) vanish as k^2 -> 0, so E(0) = 0 identically and no k-independent term survives, for every m > 0 and xi tested; B44, (4.9), (4.10), (4.11) are reproduced. No numerical datum enters. The tree's further step, 'AMM's scheme = the alpha~^S_1 = 0 case' (linstab.py:166-168), is corroborated at order k^0 (C7), which is the only order its dependents use. The recorded drifts are framing and scope: 'choice' leaves out that the absence of a k^0 term also needs A1 plus AMM's identification of the k^0 response coefficient with Lambda of (2.9); m > 0 sits in the SETTING, not in H4; the equivalence holds at k^0 only. None of them changes a conclusion the tree draws. GMMPS 2026 contest AMM's renormalisation CONDITION. That is a later theoretical dispute the tree already marks not adjudicated (linstab.py:181-183, linstab.py:353 SPLIT_ADJUDICATED_HERE = False). It is not a refutation of what AMM's scheme does. The grade is for AMM's description of its own scheme; which scheme is right is OPEN and not graded here.",
"what_would_change_the_grade": "NARROWED if a dependent is found that uses 'AMM's scheme = alpha~^S_1 = 0' beyond order k^0 (C7: AMM also differs at order gamma and gamma^2), or that treats the absence of a k^0 term as independent of AMM's flat-background identification (A1). OPEN or DATA-DEPENDENT at the level of the SPLIT, not of this key, if a demonstration (for example an independent perturbative-agreement computation) shows that covariance forces a nonzero k^0 coefficient in the gauge-invariant scalar response. That would make AMM's condition inconsistent rather than merely different; it is not shown by any source read here. WRONG only if the (4.4) identity or the O(k^2) vanishing of F^(i) failed, which C1-C3 exclude.",
"reverify_command": "python3 " + D + "/rederive/gr-qc_0209075_renorm-4.4.py && sed -n 1820,1990p " + D + "/amm_0209075.txt && sed -n 100,110p /home/user/Claude-Method-Works/research/warp-drive/linstab.py && sed -n 160,185p /home/user/Claude-Method-Works/research/warp-drive/linstab.py",
"report_path": D + "/audits/gr-qc_0209075_renorm-4.4.json"
}
json.dump(r, open(r["report_path"], "w"), indent=1)
print("written", r["report_path"])
