import json
SP = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
r = {
 "key": "cmb-dipole-370kms",
 "name": "CMB dipole velocity 3.7e5 m/s (370 km/s); Gamma - 1 = 7.6161e-07",
 "source": {
  "located": "Planck Collaboration, 'Planck 2018 results. I. Overview and the cosmological legacy of Planck', arXiv:1807.06205 (A&A 641, A1, 2020), solar-dipole section; companion 'Planck 2018 results. III. HFI data processing', arXiv:1807.06207 (the HFI dipole). The tree names NO source at branelink.py:150 ('V_CMB = 3.7e5  # m/s, CMB dipole (READ)') and no capture of any dipole paper exists under research/warp-drive/captures or in the scratchpad; the identification of Planck 2018 as the governing measurement is this audit's, not the tree's.",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "Every live alphaXiv call in this stage (answer_pdf_queries on 1807.06205 and 1303.5087, get_paper_content 1807.06205, discover_papers, and a retry of answer_pdf_queries) returned 'alphaXiv assistant quota exceeded'. arxiv.org, www.aanda.org, export.arxiv.org, inspirehep.net, api.semanticscholar.org, pdg.lbl.gov and en.wikipedia.org are refused by the egress proxy (CONNECT 403 / WebFetch EGRESS_BLOCKED; organization policy, not retried around). Two independent restatements WERE obtained: (a) a WebSearch engine summary of 1807.06205 quoting 'The dipole amplitude corresponds to beta = v/c = (1.23357 +/- 0.00036)x10^-3 or v = (369.82 +/- 0.11) km s^-1', 'combined measurement of the solar dipole amplitude is 3362.08 +/- 0.99 uK', and 'The \"Solar dipole\" is induced by the motion of the Solar System barycentre with respect to the CMB, while the \"orbital dipole\" is the modulation of the Solar dipole induced by the orbital motion of the satellite around the Solar System barycentre' -- a search-engine rendering, not page text; (b) litebird_sim 0.17.0 from pypi (wheel md5 1affa3e4aa9ae16ae7e23c62f23db217, saved at " + SP + "/src/pkgs/), litebird_sim/constants.py lines 18-23: 'T_CMB_K = 2.72548  # Fixsen 2009', '# Dipole parameters from https://arxiv.org/abs/1807.06207', 'SOLAR_VELOCITY_KM_S = 369.8160', 'SOLAR_VELOCITY_GAL_LAT_RAD = 0.842_173_724', 'SOLAR_VELOCITY_GAL_LON_RAD = 4.608_035_744_4' (= b 48.2530 deg, l 264.0210 deg). The two restatements agree with each other and with the internal chain A/T0 = beta (computed, rederive script). The Planck pages themselves are NAMED-NOT-READ in this stage; a fresh answer_pdf_queries on 1807.06205 is the outstanding read."
 },
 "published_statement": "As restated (see source.via): Planck 2018 I -- solar dipole amplitude 3362.08 +/- 0.99 uK, corresponding to beta = v/c = (1.23357 +/- 0.00036)e-3, v = 369.82 +/- 0.11 km/s, towards galactic (l, b) = (264.021, 48.253) deg [direction from litebird_sim's 1807.06207 constants; the search summary gave the amplitude and velocity]. The Solar dipole is 'induced by the motion of the Solar System barycentre with respect to the CMB'; the orbital dipole (satellite motion about the barycentre) is a separate, modulating term. HFI (1807.06207) value as restated: 369.8160 km/s.",
 "published_hypotheses": [
  "H1 (kinematic interpretation): the whole temperature dipole is Doppler, i.e. v/c = A/T0 to O(beta^3); an intrinsic (primordial or large-scale-structure) dipole is assumed negligible. The conversion amplitude -> velocity IS this hypothesis (rederive part 2: the boosted-blackbody dipole coefficient is beta + beta^3/10, so beta is read off A/T0 only if all of A is kinematic).",
  "H2 (reference point): the velocity is that of the Solar System BARYCENTRE relative to the CMB rest frame; the observer's orbital motion is removed as a separate 'orbital dipole'.",
  "H3 (monopole): T0 = 2.7255 K (Fixsen 2009) converts uK to beta; with T0 = 2.72548 the chain gives 369.816 km/s, with 2.7255 gives 369.813 km/s, both inside +/- 0.11 km/s (computed).",
  "H4 (frame): 'the CMB rest frame' is the frame in which the dipole vanishes -- a cosmological reference frame; Planck makes no claim that it is a preferred frame of any Lorentz-violating or brane dynamics."
 ],
 "hypothesis_drift": [
  "DROPPED H1 (kinematic interpretation) at branelink.py:150 ('V_CMB = 3.7e5  # m/s, CMB dipole (READ)') and branelink.py:270-272 (Gamma - 1 computed from V_CMB): the dipole is carried as a measured VELOCITY with no statement that the velocity reading presumes a purely kinematic dipole. The interpretation is contested in later literature (matter-dipole excess, see later_literature). Does NOT move the O7 conclusion (see lacked_data).",
  "DROPPED/SHIFTED H2 (barycentre -> Earth/receiver) at branelink.py:73-75 ('the dipole's Gamma - 1 = 7.6161e-07 is the RECEIVER's B') and ledger.py:1878-1881 (answering condition 'a measurement of Earth's velocity relative to the preferred brane frame' followed by 'the CMB dipole at 370 km/s'): 369.82 km/s is the barycentre's speed; Earth's speed relative to the CMB frame runs 340.65 .. 399.08 km/s over a year (circular orbit, u = 2 pi AU/yr = 29.785 km/s, apex at ecliptic latitude -11.152 deg; COMPUTED), so the receiver's Gamma - 1 runs 6.4556e-07 .. 8.8605e-07, -15.2 % .. +16.5 % of the barycentre value. A single five-figure 7.6161e-07 for 'the receiver' over-represents precision by ~3 figures. Discrepancy of reference point, not a refutation.",
  "ADDED (by the tree, and NAMED by it): 'CMB rest frame as candidate preferred brane frame' -- branelink.py:73-75 and ledger.py:1791-1792 ('a candidate for B ... B IS UNMEASURED'). Correctly hedged in the live row. The SUPERSEDED row ledger.py:1879-1881 ('The only preferred-frame velocity ever measured is the CMB dipole') over-states H4: Planck measured a velocity relative to the CMB frame, not a velocity relative to any preferred frame of the dynamics. The tree already retired that row (WRONG PROVENANCE, ledger.py:1882-1883), for a different reason.",
  "PRECISION: 3.7e5 m/s is the two-figure rounding of 369.82 km/s (dv = +0.18 km/s, +4.87e-4 rel); Gamma - 1 printed to five figures (7.6161e-07, branelink.py:74; selftest pin branelink.py:463-464) inherits the rounding: at the Planck value it is 7.6087e-07 (+9.74e-4 rel, outside Planck's 1-sigma band [7.6042e-07, 7.6132e-07]). A rounding discrepancy, recorded, not an error; the superseded ledger.py:1880 '7.6e-7' is the precision the input supports.",
  "PROVENANCE GAP: the status word READ at branelink.py:150 names no document; nothing in the tree records which dipole measurement was read."
 ],
 "data_at_publication": [
  {"quantity": "Solar (barycentre) velocity relative to CMB frame", "value_then": "3.7e5 m/s as typed by the tree (branelink.py:150; no source named)", "value_now": "369.82 +/- 0.11 km/s (Planck 2018 I, restated); 369.8160 km/s (Planck 2018 III HFI, restated by litebird_sim constants.py)", "source_now": "arXiv:1807.06205 / 1807.06207 via restatement (see source.via)", "moves_conclusion": "No. Relative move -4.87e-4; the tree uses the figure only as an order-of-magnitude candidate for B."},
  {"quantity": "Gamma - 1 at the dipole velocity", "value_then": "7.6161e-07 (exact at 3.7e5: 7.616098334421e-07, COMPUTED, 50 digits; the tree's expm1/log1p route agrees to 1e-12 rel)", "value_now": "7.608689871e-07 at 369.82 km/s; band 7.6041642e-07 .. 7.6132168e-07 at +/- 1 sigma; 7.608525279e-07 at 369.8160 km/s", "source_now": "COMPUTED in rederive/cmb-dipole-370kms.py from the restated Planck values", "moves_conclusion": "No. -9.7e-4 relative; O7's statement is qualitative ('a candidate for B ... enters only through the anisotropy')."},
  {"quantity": "Earth (receiver) velocity relative to CMB frame, annual range", "value_then": "not distinguished (the tree uses the barycentre figure for 'the receiver' / 'Earth')", "value_now": "340.65 .. 399.08 km/s; Gamma - 1 = 6.4556e-07 .. 8.8605e-07", "source_now": "COMPUTED: Planck apex (l,b) = (264.021, 48.253) -> RA 167.942 Dec -6.944 -> ecliptic lat -11.152 deg; u = 2 pi AU / Julian yr = 29.785 km/s (circular-orbit hypothesis; eccentricity adds ~+/-0.5 km/s)", "moves_conclusion": "No for O7 (B_Earth,max = 1.331e-3, still ~750x below the B >= 0.999387630 the tree prices for one second). Yes for any claim quoting the receiver's Gamma - 1 to more than one figure."},
  {"quantity": "monopole temperature T0 used in amplitude -> velocity", "value_then": "not used by the tree", "value_now": "2.7255 K / 2.72548 K (Fixsen 2009, audited separately as 0911.1955)", "source_now": "litebird_sim constants.py line 18 restating 0911.1955", "moves_conclusion": "No: both roundings reproduce v within 0.11 km/s (369.813 and 369.816 km/s, computed)."},
  {"quantity": "tree-model saving at B = dipole (branelink.b_for_saving inverted: T d ((1+B)/(1-B))^2; GKLP eq. (22) as the pass read it -- the model itself is NOT audited here)", "value_then": "93.8065 ns at B = 0 (GW170817 provenance, correctly attributed by the tree)", "value_now": "94.2706 ns at B = 1.233587e-3 (barycentre); 94.3074 ns at Earth's annual maximum", "source_now": "COMPUTED in rederive script", "moves_conclusion": "No: +0.5 % of 94 ns against a priced one-second escape; the dipole 'enters only through the anisotropy' at the sub-ns level, as the tree states."}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": SP + "/rederive/cmb-dipole-370kms.py",
  "outcome": "ALL PASS (16 checks, exit 0; output at rederive/cmb-dipole-370kms.out; script md5 ef503488ea74e782c5468af62693bd3d). (1) Gamma - 1 at 3.7e5 m/s = 7.6160983344212586841e-07 exactly (sympy, 50 digits): the tree's float route, its selftest pin 7.6161e-07 (1e-4) and canonical 7.616098e-07 all reproduce; three-term series b^2/2 + 3b^4/8 + 5b^6/16 agrees to 1e-15. (2) The published chain A/T0 = beta reproduces the restated beta and v within their sigmas for T0 = 2.7255 and 2.72548; the boosted-blackbody dipole coefficient is beta + beta^3/10 (sympy), so the chain is exact to 1e-7 GIVEN the kinematic hypothesis. (3) Gamma - 1 at 369.82 km/s = 7.6087e-07; the tree's figure is +9.74e-4 high, outside the 1-sigma band -- rounding of a two-figure input. (4) Apex galactic -> ICRS reproduces RA 167.942 Dec -6.944 (the known dipole apex); Earth's annual speed 340.65 .. 399.08 km/s, Gamma - 1 -15.2 % .. +16.5 %. (5) B_cmb = 1.233587e-3 is 810x below B = 0.999387630; tree-model saving moves 93.81 -> 94.27 ns.",
  "agrees_with_source": "partly"
 },
 "later_literature": [
  {"ref": "Secrest et al. 2021, ApJ 908 L51, 'A Test of the Cosmological Principle with Quasars' (CatWISE2020, 1.36 M quasars)", "effect": "contested", "what": "Per a search-engine summary: number-count dipole direction ~27 deg from the CMB dipole with amplitude over twice the kinematic expectation, 'rejecting the canonical, exclusively kinematic interpretation of the CMB dipole' at p = 5e-7 (4.9 sigma one-sided). Bears on H1, not on the temperature-dipole measurement.", "read_status": "NAMED-NOT-READ (WebSearch summary only; alphaXiv quota exceeded, arxiv.org egress-blocked)"},
  {"ref": "arXiv:2511.00822, 'The CatWISE2020 Quasar dipole: A Reassessment of the Cosmic Dipole Anomaly'", "effect": "contested", "what": "Title only: a reassessment of the Secrest anomaly; direction of its verdict not read.", "read_status": "NAMED-NOT-READ (search result title only)"},
  {"ref": "arXiv:2405.09762, 'Reassessment of the dipole in the distribution of quasars on the sky'", "effect": "contested", "what": "Title only: bears on the matter-dipole test of H1; verdict not read.", "read_status": "NAMED-NOT-READ (search result title only)"},
  {"ref": "arXiv:2311.14938, 'The Cosmic Dipole in the Quaia Sample of Quasars: A Bayesian Analysis'", "effect": "contested", "what": "Title only: independent quasar sample for the same test; verdict not read.", "read_status": "NAMED-NOT-READ (search result title only)"},
  {"ref": "Planck 2013 XXVII, arXiv:1303.5087, 'Doppler boosting of the CMB: Eppur si muove'", "effect": "confirms", "what": "Named because it is the one test of H1 that does not use the temperature dipole (aberration + Doppler modulation of small-scale anisotropies). Its figures are NOT quoted here: answer_pdf_queries on it returned quota exceeded, and no restatement was obtained.", "read_status": "NAMED-NOT-READ (effect 'confirms' is the paper's known thrust, unverified here -- treat as unread)"}
 ],
 "lacked_data": "What the measurement lacks is not precision -- the temperature dipole is known to ~3e-4 (0.99 uK in 3362 uK, restated) -- but a separation of the dipole into kinematic and intrinsic parts: converting uK to km/s presumes the whole dipole is Doppler (H1). The data that would test that -- the aberration/Doppler modulation of small-scale CMB anisotropy (Planck 2013 XXVII, not read here) and the matter number-count dipole (Secrest 2021 and successors, read only as search summaries) -- came later or remain contested: the quasar dipole is reported at ~2x the kinematic expectation (4.9 sigma, per summary), and reassessments exist whose verdicts were not read. EVIDENCE EITHER WAY for THIS result as the tree uses it: none of it moves O7. If the dipole were, say, half intrinsic, B_cmb would halve; if the matter dipole's ~2x amplitude were read as velocity, B would double to ~2.5e-3 -- either way still ~400x or more below the B >= 0.999387630 the tree prices for a one-second saving, and the tree already states B IS UNMEASURED and the CMB frame is only a candidate. The moved datum that does matter at the tree's printed precision is not new data but a dropped reference point: 'the receiver' is Earth, whose Gamma - 1 swings +/-16 % annually, so the five-figure 7.6161e-07 carries three figures neither the rounded input nor the barycentre/Earth distinction supports. M's hypothesis is therefore partly borne out for the INTERPRETATION of the measurement (contested, data-dependent) and not borne out for the measurement itself or for the conclusion the tree draws from it.",
 "grade": "NARROWED",
 "grade_evidence": "The number stands: 3.7e5 m/s is the two-figure rounding of Planck 2018's 369.82 +/- 0.11 km/s (two independent restatements agree; A/T0 reproduces beta and v within sigma, computed), and Gamma - 1 = 7.6161e-07 is exact arithmetic on 3.7e5 (sympy, 50 digits; tree route agrees to 1e-12). But the tree drops two published hypotheses: (i) H1, the kinematic interpretation that turns a temperature dipole into a velocity, which later matter-dipole work contests (NAMED-NOT-READ, 4.9 sigma per summary); (ii) H2, that the velocity is the Solar System barycentre's -- the tree assigns it to 'the RECEIVER' / 'Earth' (branelink.py:73-75, ledger.py:1878-1881), whose Gamma - 1 ranges 6.46e-07 .. 8.86e-07 over a year (computed). Per the rubric a dropped hypothesis is NARROWED. Neither drift moves the O7 conclusion (B unmeasured; dipole a candidate entering only through the anisotropy; B_Earth,max = 1.33e-3 vs priced 0.9994; tree-model saving 93.81 -> 94.31 ns at most). The +9.7e-4 offset of the five-figure Gamma - 1 from the Planck value is a rounding DISCREPANCY, recorded, not an error. Caveat on the grade's footing: Planck 2018 was read only via restatement (alphaXiv quota exhausted, arxiv.org egress-blocked).",
 "what_would_change_the_grade": "To STANDS: the tree restating V_CMB as the barycentre velocity with its kinematic hypothesis named and Gamma - 1 carried at the precision its input supports (7.6e-7, or an annual 6.5-8.9e-7 range for Earth) -- a wording change, not new data. To OPEN: a fresh read of 1807.06205 contradicting the restated 369.82 +/- 0.11 km/s or the barycentre attribution (not expected: two independent restatements and the internal A/T0 chain agree). To DATA-DEPENDENT: only if the tree began to use the dipole's magnitude quantitatively (e.g. a saving or bound that depends on B at the percent level), since the kinematic share of the dipole is contested; as used (a qualitative candidate far below the priced escape) the contested datum does not move the conclusion. Never WRONG on present evidence: no counterexample or computed contradiction exists.",
 "reverify_command": "python3 " + SP + "/rederive/cmb-dipole-370kms.py  # expect 'ALL PASS', exit 0; then, when quota allows: alphaXiv answer_pdf_queries(paper='1807.06205', queries=['solar dipole amplitude uK, beta, v, (l,b)', 'barycentre vs orbital dipole', 'kinematic assumption'])",
 "report_path": SP + "/audits/cmb-dipole-370kms.json"
}
json.dump(r, open(SP + "/audits/cmb-dipole-370kms.json", "w"), indent=1)
print("ok")
