import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R={
"key":"cmb-temperature-scales-as-1-over-a",
"name":"CMB temperature scales as T proportional to 1/a (adiabatic blackbody redshifting), so T_rec/T_0 = 1+z",
"source":{
 "located":"The law is textbook (Tolman-era; no single originating paper). Its governing modern statement and tests: Chluba 2014, MNRAS 443, 1881, arXiv:1405.1277; Avgoustidis et al. 2016, PRD 93, 043521, arXiv:1511.04335; Riechers et al. 2022, Nature 602, 58, arXiv:2202.00693. The two data the tree uses: T_0 from Fixsen 2009, ApJ 707, 916, arXiv:0911.1955; z* = 1089.92 from Planck 2018 VI, arXiv:1807.06209 (A&A 641, A6).",
 "read_status":"READ-VIA-RESTATEMENT",
 "via":"READ at page text: Planck 2018 VI, cached full text scratchpad/d67/src/casmag/all/1807.06209v4.txt (md5 520b9b5e0258d40eddee9e463c1577c3), lines 1045-1046 ('We take T0 = 2.7255K (Fixsen 2009), with the +/-0.0006K error having negligible impact on results'), 1193-1217 (Table 2 caption: 'Parameter 68 % intervals for the base-LCDM model ... The middle group lists derived parameters'; column order TT+lowE | TE+lowE | EE+lowE | TT,TE,EE+lowE | TT,TE,EE+lowE+lensing | +BAO), 1333-1336 (row z*: 1090.30+/-0.41, 1089.57+/-0.42, 1087.8(+1.6/-1.7), 1089.95+/-0.27, 1089.92+/-0.25, 1089.80+/-0.21). The definition of z* (optical depth unity) was NOT located in the cached extraction and is not quoted. NOT read at page text: every alphaXiv call in this stage (answer_pdf_queries on 0911.1955, 1807.06209, 1112.1862, 1405.1277; get_paper_content 0911.1955; discover_papers) returned 'alphaXiv assistant quota exceeded'; ar5iv.labs.arxiv.org, academic.oup.com and pith.science are refused by the egress proxy (EGRESS_BLOCKED). The following are SEARCH-ENGINE RESTATEMENTS (WebSearch summaries, weaker than page text): Fixsen 2009 'T_0 = 2.72548 +/- 0.00057 K', FIRAS-recalibrated 2.7260 +/- 0.0013; Chluba 2014 abstract ('the average temperature of the CMB is expected to depend like T_CMB proportional to (1+z) ... Adiabatic photon production (or destruction) or deviations from isotropy and homogeneity could modify this scaling ... instead of leading to a simple rescaling of the CMB temperature, a spectral distortion should be produced, which can be constrained using COBE/FIRAS'); Avgoustidis 2016 beta = (7.6 +/- 8.0)e-3 for T(z)=T0(1+z)^(1-beta); Riechers 2022 T_CMB(z=6.34) = 16.4-30.2 K (1 sigma), expected 20.0 K; Ivanov, Ali-Haimoud & Lesgourgues 2020 (arXiv:2005.10656, PRD 102, 063515): 'CMB anisotropies alone can only weakly constrain T0 ... near-perfect degeneracy' via the angular diameter distance to last scattering; arXiv:2607.23535 (July 2026): 63 public T_CMB(z) measurements over 0<=z<=6.34 constrain violations to the percent level. The LAW itself is not taken from any unread text: it is re-derived from first principles here (rederive A1-A4, B1-B2), so the grade does not rest on the restatements; the restatements bear only on the observational range and on the model-dependence of T_0/z*."
},
"published_statement":"Law (as restated, Chluba 2014 abstract via search): 'In the expanding Universe, the average temperature of the cosmic microwave background (CMB) is expected to depend like T_CMB proportional to (1+z) on redshift z. Adiabatic photon production (or destruction) or deviations from isotropy and homogeneity could modify this scaling.' Data as READ (Planck 2018 VI): 'We take T0 = 2.7255K (Fixsen 2009)' (l.1045) and z* = 1089.92 +/- 0.25 as a DERIVED parameter of the base-LCDM fit to TT,TE,EE+lowE+lensing (Table 2, l.1193-1217, 1336). Re-derived here: a Planck occupation set at a_e and free-streaming in FLRW is at every later a EXACTLY a Planck occupation with T = T_e a_e/a.",
"published_hypotheses":[
 "FLRW (homogeneous, isotropic) background; photon momentum p proportional to 1/a along null geodesics",
 "photons collisionless after decoupling (occupation number conserved along the ray, Liouville)",
 "no photon production or destruction and no energy injection after the spectrum was thermalised (else a mu/y spectral distortion, not a rescaled T -- Chluba 2014, restated)",
 "the spectrum was a blackbody when set (FIRAS; the T_0 measurement assumes and fits a blackbody)",
 "for the numerical value z* = 1089.92: the base-LCDM model with T_0 FIXED at 2.7255 K (Planck 2018 VI l.1045, Table 2); z* is a derived, not a directly measured, parameter",
 "for the tree's 'cosmic/atomic ratio' reading: atomic constants (alpha, m_e, hbar) not varying between z* and today -- a hypothesis of the reading, not of the photon law"
],
"hypothesis_drift":[
 "ADDED -- permute.py:239 docstring 'Measured independently of any model of a(t): T scales as 1/a' and permute.py:66-68 'Measured, from the CMB temperature alone: T_rec / T_0 = 2973.3 K / 2.7255 K = 1090.92 = 1 + z'. Neither holds as worded: (i) permute.py:234-240 computes T_rec = T_0(1+z) and then divides by T_0, so ratio_from_temperature is identically 1+z for every T_0 (sympy C1-C2: d/dT_0 = 0; live import C4-C5: the near-check at permute.py:428-429 passes with T_0 = 1e6 K); (ii) the one datum, z* = 1089.92, is a base-LCDM derived parameter computed with T_0 fixed (Planck 2018 VI l.1045, 1193-1217) -- a model of a(t) is inside it. 2973.3 K is a label T_0(1+z*), not a separately measured temperature.",
 "ADDED -- obstruct.py:278 'grew by 1090.92 since recombination, read off T_rec/T_0': same drift carried into the obstruct row EXPANSION-IS-A-RELABELLING (obstruct.py:270-282). The row's first and independent ground, theta = 3 H_0 != 0 (obstruct.py:273-276), does not use this result.",
 "DROPPED -- permute.py:179 'Z_REC = 1089.92  # Planck 2018' names the source but not that the value is a DERIVED base-LCDM parameter from one data combination; across Planck's six Table-2 columns z* runs 1087.8 to 1090.30 (spread 2.3e-3 of 1+z*, computed D3).",
 "DROPPED -- permute.py:62-66 and permute.py:243-245 (bohr_radius_contains_a returns a hard-coded False): the ratio (cosmic scale)/(atomic scale) = 1+z needs alpha, m_e, hbar constant since z*. That is a named hypothesis (constrained by CMB/BBN analyses, not read here), not something the tree measures.",
 "DROPPED -- observational reach: direct T_CMB(z) tests span 0 <= z <= 6.34 (restated: Riechers 2022; 2607.23535); at z* the scaling is the theorem plus the LCDM fit, not a measurement. The tree's 'measured' wording at permute.py:66 and :239 elides this.",
 "LABEL DISCREPANCY (not a refutation) -- permute.py:179 names the constant Z_REC and the prose says 'since recombination' (permute.py:67-70, obstruct.py:278), but the value is z* (Planck's last-scattering row, distinct from z_drag = 1059.94 in the same table). Hydrogen Saha half-ionisation with eta = 6.13e-10 is at T = 3762 K (z = 1379 if T proportional to 1/a; computed E1); at T = 2973.3 K Saha gives x_e = 3.2e-3. Recorded as a naming discrepancy; it does not move the ratio's order of magnitude.",
 "NONE on the core law -- the canonical entry's hypotheses 'free-streaming blackbody photons after decoupling in FLRW' and 'no photon injection or non-adiabatic heating' (canonical.json statements_as_used) match the published and re-derived hypotheses exactly."
],
"data_at_publication":[
 {"quantity":"T_0, CMB monopole temperature","value_then":"2.7255 K (permute.py:178, 'Fixsen 2009'; the value Planck 2018 VI fixes, l.1045)","value_now":"2.72548 +/- 0.00057 K (Fixsen 2009, restated by search; no later superseding absolute measurement found in this stage)","source_now":"arXiv:0911.1955 via WebSearch restatement; Planck 2018 VI l.1045 READ","moves_conclusion":"No. It cannot: T_0 cancels identically in ratio_from_temperature (C2). T_rec label moves 2973.30246 -> 2973.2806 K, -7.3e-6 relative (D2)."},
 {"quantity":"z*, redshift used as 'recombination'","value_then":"1089.92 (permute.py:179), = Planck 2018 VI TT,TE,EE+lowE+lensing column","value_now":"1089.92 +/- 0.25 (same; READ, l.1336); other Planck 2018 columns 1087.8-1090.30; +BAO 1089.80 +/- 0.21","source_now":"arXiv:1807.06209 Table 2, cached text l.1333-1336","moves_conclusion":"No. 1+z* = 1088.8 .. 1091.3 across all columns (D3); the tree's statement 'changed by a factor of 1,091' holds to 0.23%. The value is model-derived (base LCDM), which is a status point, not a numerical move."},
 {"quantity":"deviation parameter beta in T(z) = T0(1+z)^(1-beta)","value_then":"0 implicitly (the tree assumes exact 1/a)","value_now":"(7.6 +/- 8.0)e-3 at z <~ 3 (Avgoustidis 2016, restated); consistent with 0 at 1 sigma","source_now":"arXiv:1511.04335 via WebSearch restatement","moves_conclusion":"No at the measured redshifts. Extrapolated to z* (unwarranted -- adiabatic photon production would instead leave a FIRAS-limited distortion, Chluba 2014 restated) the +/-1 sigma band would change T(z*) by factor 0.897..1.003 (F), still a ratio ~1000, so the qualitative conclusion is not moved even then."},
 {"quantity":"T_CMB at z = 6.34","value_then":"not used","value_now":"16.4-30.2 K (1 sigma), vs T_0(1+z) = 20.0 K","source_now":"Riechers 2022, arXiv:2202.00693, via WebSearch restatement","moves_conclusion":"No; corroborates the law at the highest directly measured redshift."}
],
"rederivation":{
 "method":"sympy",
 "script_path":D+"/rederive/cmb-temperature-scales-as-1-over-a.py",
 "outcome":"ALL PASS, 19 checks, exit 0 (output "+D+"/rederive/cmb-temperature-scales-as-1-over-a.out). A1: Planck occupation at a_e, free-streaming (f conserved, p ~ 1/a), equals Planck with T = T_e a_e/a identically. A2/A3: 40-digit quadrature of the Bose integrals (2 zeta(3), pi^4/15) so n ~ a^-3 (photon number conserved) and rho ~ a^-4. A4: a mu-distortion is NOT absorbed into a rescaled T -- the reason photon injection shows up as distortion. B1/B2: adiabatic continuity with p = rho/3 forces rho ~ a^-4, i.e. T ~ 1/a. C1-C5: the tree's 'measured' ratio is a tautology -- d/dT_0 = 0 symbolically, and the live permute.ratio_from_temperature equals scale_ratio_since for T_0 in {1e-3, 2.7255, 3, 1e6} K. D1: 2.7255 x 1090.92 = 2973.30246 K exactly (prints 2973.3, tree agrees). D2: Fixsen unrounded 2.72548 moves it -7.3e-6. D3/D4: Planck z* spread 2.3e-3 of 1+z*. E1: Saha half-ionisation 3762 K (independent route; shows 2973 K is a label). F: beta extrapolation band 0.897..1.003.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"Chluba 2014, MNRAS 443, 1881, arXiv:1405.1277","effect":"narrows","what":"Adiabatic photon production that would rescale T without distortion is 'extremely difficult to establish'; late photon production instead produces a spectral distortion bounded by COBE/FIRAS, so T(z) tests are reinterpreted as weak distortion limits. Narrows the space of deviations; confirms the law's hypotheses are the operative ones.","read_status":"search-engine restatement of the abstract only (alphaXiv quota exceeded; academic.oup.com EGRESS_BLOCKED)"},
 {"ref":"Avgoustidis et al. 2016, PRD 93, 043521, arXiv:1511.04335","effect":"confirms","what":"beta = (7.6 +/- 8.0)e-3, first sub-percent constraint, SZ + molecular/atomic absorption up to z ~ 3","read_status":"search-engine restatement"},
 {"ref":"Riechers et al. 2022, Nature 602, 58, arXiv:2202.00693","effect":"confirms","what":"T_CMB(z=6.34) = 16.4-30.2 K, consistent with 20.0 K","read_status":"search-engine restatement"},
 {"ref":"Ivanov, Ali-Haimoud & Lesgourgues 2020, PRD 102, 063515, arXiv:2005.10656","effect":"narrows","what":"CMB anisotropies alone only weakly constrain T_0 (near-perfect degeneracy through the distance to last scattering); T_0 is customarily FIXED to FIRAS in CMB analyses -- so z* is not a T_0-independent measurement, bearing directly on the tree's 'measured independently' wording.","read_status":"search-engine restatement"},
 {"ref":"arXiv:2607.23535 (July 2026), 'Cosmic microwave background temperature cosmography'","effect":"confirms","what":"63 public T_CMB(z) measurements over 0 <= z <= 6.34 constrain violations of T = T_0(1+z) to the percent level","read_status":"search-engine restatement (pith.science EGRESS_BLOCKED; alphaXiv quota exceeded)"}
],
"lacked_data":"The law dates from before any T(z) measurement existed; the authors of the standard statement lacked (a) direct high-z temperatures and (b) FIRAS-precision spectra. Both have since arrived and move nothing: SZ and molecular/atomic absorption tests over 0 <= z <= 6.34 give beta = (7.6 +/- 8.0)e-3 (restated) and T(6.34) = 16.4-30.2 K against 20.0 K expected (restated), and FIRAS-class distortion limits close the 'adiabatic injection' loophole (Chluba 2014, restated). Evidence the other way: nothing found here contradicts the law, and none of the later data reach z*. What the TREE lacks is different and is not a physics datum: it treats z* as a model-free measurement, but Planck's 1089.92 is a base-LCDM derived parameter with T_0 fixed (READ), and CMB anisotropies alone barely constrain T_0 (Ivanov et al. 2020, restated). Having that datum does not change the tree's conclusion -- 1+z* is 1088.8-1091.3 in every Planck column (computed), a ratio of ~1,091 either way -- it changes only the status word ('measured independently' -> 'theorem + LCDM-derived z*'). M's hypothesis is NOT supported for this result: no lacked datum moves it.",
"grade":"NARROWED",
"grade_evidence":"The physics law STANDS: re-derived symbolically (A1: free-streaming Planck occupation stays Planck with T = T_e a_e/a; B1-B2: adiabatic radiation forces rho ~ a^-4) under exactly the hypotheses the canonical entry names, and corroborated observationally to z = 6.34 (restated). The grade is NARROWED because the tree uses it more widely than it holds: permute.py:239 and :66-68 (and obstruct.py:278) claim T_rec/T_0 = 1+z is 'measured independently of any model of a(t)' / 'from the CMB temperature alone'. SHOWN here: the code's ratio is identically 1+z for every T_0 (sympy d/dT_0 = 0; live near-check passes at T_0 = 1e6 K), so it measures nothing, and the one input z* = 1089.92 is a base-LCDM derived parameter computed with T_0 fixed at 2.7255 K (Planck 2018 VI l.1045, Table 2 caption l.1193-1217, READ). Also dropped: constant atomic constants for the cosmic/atomic ratio reading, and the z <= 6.34 reach of direct tests. Not WRONG: no counterexample exists and no number moves -- 1+z* = 1088.8-1091.3 across Planck columns, 2973.30246 K reproduces the tree's 2973.3, and obstruct.py's row stands on its independent theta = 3H_0 != 0 ground regardless. Z_REC labelled 'recombination' while holding z* (last scattering) is recorded as a discrepancy, not a refutation.",
"what_would_change_the_grade":"To STANDS: the tree rewording permute.py:66-68/:239 and obstruct.py:278 to 'theorem (free-streaming blackbody in FLRW, no injection, constant atomic constants) with z* a Planck base-LCDM derived value' and replacing the tautological near-check with a genuinely independent datum (e.g. a measured T_CMB(z) point). To WRONG: a measured T_CMB(z) inconsistent with T_0(1+z) beyond errors, or a FIRAS-class spectrum showing the blackbody was not preserved -- none known. To DATA-DEPENDENT: a model change moving z* by more than a few tenths of a percent would still not move 'factor ~1,091' qualitatively, so this is not in reach. Reading the primary pages (0911.1955, 1405.1277, 1511.04335) at alphaXiv when quota allows would upgrade the restated data rows to READ; it would not by itself change the grade.",
"reverify_command":"python3 "+D+"/rederive/cmb-temperature-scales-as-1-over-a.py  # expect 19 PASS, 'ALL PASS', exit 0; then: sed -n 1045,1046p "+D+"/src/casmag/all/1807.06209v4.txt; sed -n 1193,1217p "+D+"/src/casmag/all/1807.06209v4.txt; sed -n 1333,1336p "+D+"/src/casmag/all/1807.06209v4.txt; sed -n 234,240p /home/user/Claude-Method-Works/research/warp-drive/permute.py; sed -n 276,279p /home/user/Claude-Method-Works/research/warp-drive/obstruct.py; when quota allows: alphaXiv answer_pdf_queries(paper='1405.1277', ...), (paper='0911.1955', ...), (paper='1511.04335', ...)",
"report_path":D+"/audits/cmb-temperature-scales-as-1-over-a.json"
}
json.dump(R,open(R["report_path"],"w"),indent=1,ensure_ascii=False)
print("ok")
