import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S = D + "/rederive/asymptotically-flat-laplace-spectrum-to-zero.py"
rep = {
 "key": "asymptotically-flat-laplace-spectrum-to-zero",
 "name": "Spectral theory: an asymptotically flat complete spatial slice has Laplace spectrum continuous down to zero (w_min = 0)",
 "source": {
  "located": "The tree cites no source for the theorem itself (fewsterteo.py:95-97 states it as 'HYPOTHESIS, named'). Standard literature for it: Weyl's criterion (a textbook result); H. Donnelly, 'Spectrum of the Laplacian on asymptotically Euclidean spaces', Michigan Math. J. 46 (1999) 101-111; Charalambous & Lu, 'The essential spectrum of the Laplacian', arXiv:1211.3225. The equation it feeds, Fewster & Teo (5.6)/(5.7), gr-qc/9812032v2 p.10, WAS READ from the alphaXiv page text cached by this docket (scratchpad d67/src/gr-qc_9812032.pages.txt lines 1230-1420).",
  "read_status": "NAMED-NOT-READ",
  "via": "This pass could not read the spectral-theory literature: alphaXiv returned 'assistant quota exceeded' on answer_pdf_queries, get_paper_content and discover_papers, and the egress proxy refused arxiv.org, export.arxiv.org, api.semanticscholar.org, projecteuclid.org and lu.math.uci.edu (all EGRESS_BLOCKED / 403). Only web-search result snippets were seen, and they are not treated as reads. So the theorem is NAMED-NOT-READ. What the tree actually uses from it (inf spec = 0 and no gap, i.e. [0,oo) contained in sigma_ess) is instead RE-DERIVED here as a complete elementary proof (nonnegativity plus Weyl sequences supported in the flat end) and checked numerically on the corridor. The downstream equation F&T (5.6)/(5.7) is READ via the cached alphaXiv text."
 },
 "published_statement": "No single published statement exists for the tree's wording. What is READ is F&T gr-qc/9812032 p.10: for the open RW universe the QEI (2.12) becomes (5.5), 'identical in form to that in (four-dimensional) Minkowski space. Both (3.2) and (5.5) can, in fact, be written as -(1/4pi^3) INT_0^oo dw INT_C^oo dw' w'^2 sqrt(w'^2-C^2) |fhat_{1/2}(w+w')|^2 = -(1/16pi^3) INT_C^oo du |fhat_{1/2}(u)|^2 u^4 Q_3(u/C)  (5.6), where C = sqrt(kappa/a^2 + mu^2), kappa = 0 Minkowski space, 1 open universe (5.7) ... The Minkowski space result is obviously recovered in the limit of infinite a.' The standard theorem in the form this audit re-derives: for a complete Riemannian 3-manifold with an end on which the metric tends to the Euclidean one, -Delta >= 0 and every lambda >= 0 has a Weyl sequence supported far out in the end, so sigma(-Delta) = sigma_ess(-Delta) = [0,oo) and inf sigma = 0. That spectrum is also purely (absolutely) continuous only under extra decay hypotheses (Donnelly 1999; Kato-type theorems), NAMED-NOT-READ here.",
 "published_hypotheses": [
  "F&T (5.6)/(5.7) READ: derived for exactly two ultrastatic spacetimes, 4D Minkowski (kappa = 0) and the open RW universe with H^3 slices of radius a (kappa = 1). The derivation uses the H^3 mode sum rule (5.4), sum |Pi_ql Y_lm|^2 = q^2/2pi^2, and a scalar field of mass mu.",
  "F&T: C is not defined as a spectral gap of a general manifold. It is the specific combination sqrt(kappa/a^2 + mu^2), which equals sqrt(inf spec(-Delta_{H^3_a} + mu^2)) (sympy check S1 here).",
  "Theorem, used part (re-derived): the spatial manifold is complete, or the chosen self-adjoint extension is nonnegative; it has an asymptotically Euclidean end; the operator is -Delta (minimal coupling, no potential, mass 0).",
  "Theorem, the 'continuously' clause (NAMED-NOT-READ): needs a decay rate on the metric or curvature at infinity. Without one, complete asymptotically flat manifolds can carry eigenvalues embedded in [0,oo) (Jitomirskaya & Liu, GAFA 29 (2019) 238-257, arXiv:1805.01072, per search snippet only)."
 ],
 "hypothesis_drift": [
  "ADDED SCOPE (fewsterteo.py:95-97, 609-610; specthm.py:2838 V2): '(5.6) returns the flat bound exactly' at C = 0 is true of the FORMULA (5.6), whose kappa = 0 row is Minkowski (READ). But (5.6) is derived only for Minkowski and open RW (READ, p.10), and C is not a free parameter of a general static spacetime. F&T's general static bound (2.12) on the corridor depends on the corridor's local mode sums, not on C alone. So 'ratio() takes C and nothing else' (fewsterteo.py:101-102) is true of the function ratio(), which is the H^3-family formula, and not of F&T's bound on the corridor. The tree carries this elsewhere: H_flat is ASSUMED (specthm.py:113, 1903), O2 stays OPEN (fewsterteo.py:148), and the docket 'evaluated on a third spacetime' (fewsterteo.py:107). This is recorded as drift in how the sentence reads, not as an error in any seated conclusion.",
  "OPERATOR (fewsterteo.py:95-96, 175-176; canonical hypothesis 'gap in (5.6) identified with Laplace spectrum bottom'): the corridor is static but NOT ultrastatic (N^2 = 1+2Phi, or F = 1-2m(r)/r). The frequencies w^2 are the spectrum of K = -(N/sqrt h) d_i(N sqrt h h^ij d_j) on L^2(sqrt h/N), not of the Laplace-Beltrami operator of the slice. The conclusion survives this drift: S3 finds Rayleigh quotients of both K and Delta_h tending to 0 like 1/w^2, matching flat space to 1e-9, and K's Weyl residual at w^2 = 1 falling like sqrt(2)/L. The drift is harmless but real.",
  "DROPPED (fewsterteo.py:96 'so w_min = 0'): massless field. With mass mu, w_min >= mu*inf N = mu (S4), and the (5.7) C becomes mu, not 0. The tree's field is massless throughout (F&T flat massless bound, C_F = mu_1^4/16pi^2, fewsterteo.py:33-45 (C_F at line 41)), so this hypothesis is satisfied but not stated in GAP_HYPOTHESIS.",
  "DROPPED (fewsterteo.py:175-176): minimal coupling / no potential. A xi R term puts xi R N^2 into K. With rho < 0 in the core, R can be negative, and a xi > 0 well could bind a state with w^2 < 0. The tree's right-instrument row is minimally coupled KG (fewsterteo.py:116, 181-182), so the hypothesis is satisfied but not stated.",
  "NAMED, and satisfied on the corridor (fewsterteo.py:95): completeness. It is load-bearing only for 'spectrum >= 0'. A Robin boundary on an incomplete slice gives eigenvalue -alpha^2 (S4, sympy), while the Weyl sequences in the flat end still give [0,oo) in sigma_ess. The corridor slice is smooth with conformal factor 1-2Phi in (0.99995, 1.0001), so it is complete.",
  "STRONGER THAN NEEDED (fewsterteo.py:96 'running continuously'): the tree's wording asserts continuous spectrum, which needs a decay hypothesis the tree does not state. It uses only inf spec = 0. The clause is unverified here (NAMED-NOT-READ). The corridor decays fast (Phi ~ m a^2/r^3 outside R_s, non-oscillatory), so it is in the class where Kato-type results are expected to apply, but this pass neither READ nor checked that."
 ],
 "data_at_publication": [
  {"quantity": "field mass mu entering C = sqrt(kappa/a^2+mu^2) (F&T (5.7))",
   "value_then": "F&T 1999 keep mu general; the tree takes mu = 0 (massless scalar)",
   "value_now": "Not read here: the PDG photon-mass limit could not be fetched (egress blocked). Computed threshold instead: a mass gap stays at or below the tree's own 'generous' C = 0.005 c/b iff m c^2 <= 0.005 hbar c / b = 9.87e-10 eV x (1 m / b).",
   "source_now": "computed in the rederive script (S5) with hbar c = 197.3269804 MeV fm",
   "moves_conclusion": "No for a massless field, which is the tree's model. For a massive scalar, w_min = mu, not 0, which is a hypothesis rather than a datum."},
  {"quantity": "CORRIDOR_SPECTRAL_GAP (fewsterteo.py:174)",
   "value_then": "0.0 (asserted from the hypothesis)",
   "value_now": "Computed on concentric.py's corridor (m = 5e-3, a = 0.02, R_s = 200, b = 1; two RECONSTRUCTED metric forms). Rayleigh quotient of K and of Delta_h is 3.08e-10 at test width 1e5, scaling exactly as 3.08/w^2, the flat value to 1e-9. Weyl residual at w^2 = 1 falls like 1.414/L.",
   "source_now": "rederive/asymptotically-flat-laplace-spectrum-to-zero.py S3",
   "moves_conclusion": "No. inf spec = 0 is confirmed for both operators."},
  {"quantity": "cavity_gap(), the 'most generous gap the corridor's own geometry could supply' (fewsterteo.py:98-100, 214-217)",
   "value_then": "C = b/R_s = 0.005 -> ratio 0.999999 (0.999999386)",
   "value_now": "A Dirichlet ball of radius R_s has gap pi/R_s = 0.01571, which is pi times larger, giving ratio 0.999993935 (2.6e-6 orders). A Neumann cavity has gap 0. So 0.005 is not the most generous cavity gap. It is a scale estimate between the Neumann and Dirichlet values.",
   "source_now": "rederive script S5, through the tree's own ratio() imported read-only",
   "moves_conclusion": "No. The ratio stays > 0.99999 and 71.256 is unmoved. This is a DISCREPANCY in the word 'most generous' and the printed '0.999999', not an error in the refusal."}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": S,
  "outcome": "ALL CHECKS PASS (sympy + scipy numeric). S1: F&T (5.7) C^2 = 1/a^2 + mu^2 equals inf spec(-Delta_{H^3_a}+mu^2), via psi = u/sinh chi turning -Delta into -(1/a^2)(d^2-1). C -> mu as a -> oo. S2: on flat R^3 the Rayleigh quotient of exp(-r^2/R^2) is exactly 3/R^2 (so inf spec = 0), and the Weyl residual^2 is 2k^2/L^2 -> 0 (so every k^2 >= 0 is in sigma_ess). S3: on the corridor (concentric.py Phi, two reconstructed metric forms), quotients of K and Delta_h are 3.08/w^2 -> 0, equal to flat to 1e-9 at w >= 100, and positive everywhere including across core and shell. K's Weyl residual at w^2 = 1 is 1.414/L. S4 controls: H^3 quotients >= 1 (the instrument can see a gap). Mass mu gives gap >= mu. A Robin extension on an incomplete slice gives -alpha^2. A Wigner-von Neumann potential of order 1/r carries an L^2 eigenvalue at E = 1 (a 1D Schrodinger illustration that 'continuously' needs a decay hypothesis; not a manifold counterexample). S5: the tree's cavity gap is 0.005 against Dirichlet pi/200 = 0.0157, ratio 0.999999386 vs 0.999993935, and the corridor's gap 0 gives ratio 1 to 1e-8.",
  "agrees_with_source": "partly"
 },
 "later_literature": [
  {"ref": "S. Jitomirskaya & W. Liu, 'Noncompact complete Riemannian manifolds with dense eigenvalues embedded in the essential spectrum of the Laplacian', GAFA 29 (2019) 238-257, arXiv:1805.01072",
   "effect": "narrows",
   "what": "Per search snippet: sharp radial-curvature criteria for asymptotically flat (curvature -> 0) complete manifolds whose Laplacian has dense eigenvalues embedded in [0,oo). The 'continuously' clause therefore needs a decay rate. inf spec = 0 is untouched.",
   "read_status": "NAMED-NOT-READ (web-search snippet only; alphaXiv quota exceeded, arxiv.org egress-blocked)"},
  {"ref": "H. Donnelly, 'Spectrum of the Laplacian on asymptotically Euclidean spaces', Michigan Math. J. 46 (1999) 101-111",
   "effect": "confirms",
   "what": "The standard reference for the AE spectrum. Its exact hypotheses and statement were not seen.",
   "read_status": "NAMED-NOT-READ (projecteuclid.org egress-blocked)"},
  {"ref": "Charalambous & Lu, 'The essential spectrum of the Laplacian', arXiv:1211.3225; W. Liu, arXiv:1908.03808 (singular continuous spectrum embedded, hyperbolic case)",
   "effect": "extends",
   "what": "Conditions for sigma_ess = [0,oo) on complete manifolds, and the finer structure (embedded point and singular continuous spectrum) beyond the essential spectrum.",
   "read_status": "NAMED-NOT-READ (search result titles only)"}
 ],
 "lacked_data": "M's hypothesis does not bite here, in either direction. The result is a theorem about a mathematical class (complete Riemannian manifolds with a Euclidean end), and no measured input enters it. inf spec = 0 follows from test functions supported arbitrarily far out, where the metric is Euclidean to any precision, so no datum about the interior (rho, m(R), the core) can move it. S3 confirms numerically that the corridor's quotients equal the flat ones to 1e-9. The only physics inputs that could change w_min are hypotheses, not data: a field mass (w_min = mu), a non-minimal coupling with a negative-R well (possible w^2 < 0), or a non-asymptotically-flat slice (a gap, as H^3's 1/a in the control). None is a datum the 1999 authors or the textbook theorem lacked. For the photon, any mass below 9.9e-10 eV x (1 m/b) keeps the gap inside the tree's own negligible C = 0.005 (computed), but the current PDG bound was not READ in this pass. What later work did add is mathematical: embedded-eigenvalue constructions on asymptotically flat manifolds (NAMED-NOT-READ). They affect only the 'continuously' wording, which the tree does not use.",
 "grade": "NARROWED",
 "grade_evidence": "The load-bearing clause, w_min = 0 on the corridor, is RE-DERIVED here. The proof is -Delta >= 0 plus Weyl sequences in the flat end, and it is measured on concentric.py's corridor: quotients of K and Delta_h equal 3.08/w^2 -> 0, flat to 1e-9, and K's Weyl residual at w^2 = 1 goes as 1.414/L. It holds for the static operator K as well as the Laplacian. Every conclusion the tree draws from it is unmoved: the H^3 tightening does not transfer, 72.599 and 72.247 stay REFUSED, 71.256 STANDS, O2 stays OPEN. The grade is NARROWED, not STANDS, because the statement as written is wider than what is shown. (i) 'so w_min = 0' drops two hypotheses, massless field and minimal coupling. A mass gives w_min = mu (S4). The tree's model satisfies both, but GAP_HYPOTHESIS does not state them. (ii) '(5.6) returns the flat bound exactly' holds for the formula (5.6), which F&T derive only for Minkowski and open RW (READ, gr-qc/9812032 p.10). It is not F&T's bound on the corridor, which the tree itself keeps under H_flat ASSUMED. (iii) 'running continuously' needs a decay hypothesis that is neither stated nor checked here. (iv) The theorem's literature could not be READ in this pass (alphaXiv quota exhausted, arxiv.org egress-blocked), so the grade rests on the computed proof, not on a read source. Separately, 'most generous' cavity gap 0.005 vs Dirichlet pi/200 = 0.0157 is a DISCREPANCY that moves nothing (ratio 0.999994 vs 0.999999).",
 "what_would_change_the_grade": "To STANDS: GAP_HYPOTHESIS names 'massless, minimally coupled' and 'inf spec' instead of 'continuously', and the (5.6) sentence is scoped to the formula (the tree already carries H_flat ASSUMED). A read of Donnelly 1999 or 1211.3225 would then confirm the literature side. To WRONG: only a complete, asymptotically Euclidean, massless minimally coupled static slice with inf spec(K) > 0, which the Weyl-sequence argument excludes, or a demonstration that the corridor is not asymptotically flat (concentric.py gives M_ADM = 0 and Phi ~ r^-3). The instrument can show a gap: the H^3 control does. To OPEN: none, because the used clause is computed. The literature half is already NAMED-NOT-READ and is flagged as such.",
 "reverify_command": "PYTHONDONTWRITEBYTECODE=1 python3 " + S + "   # exits 0 with 'ALL CHECKS: PASS'; also: sed -n 1230,1420p " + D + "/src/gr-qc_9812032.pages.txt  (F&T (5.6)/(5.7) as READ)",
 "report_path": D + "/audits/asymptotically-flat-laplace-spectrum-to-zero.json"
}
json.dump(rep, open(rep["report_path"], "w"), indent=1)
print("ok")
