import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
r={
"key":"2309.10848-frame-map",
"name":"FFKP (Fliss, Freivogel, Kontou, Pardo Santos 2023) Sec. I eq.(3), Sec. II.C eqs.(21)-(24), Sec. V.A eqs.(98)-(103): Jordan-to-Einstein frame map; NEC obeyed classically in the Einstein frame; g~ = Omega^2 g with Omega^2 ~ exp(-2(8 pi G xi phi^2)/(n-2)), close to one under the EFT assumption",
"source":{
 "located":"J.R. Fliss, B. Freivogel, E.-A. Kontou, D. Pardo Santos, 'Non-minimal coupling, negative null energy, and effective field theory', arXiv:2309.10848v1 [hep-th] (dated 21 Sep 2023); journal version SciPost Phys. 16, 119 (2024) NOT read. Frame-map passages: Sec. I p.3-4 eq.(3); Sec. II.B eqs.(17)-(20); Sec. II.C eqs.(21)-(24) pp.7-9; Sec. V intro and V.A eqs.(98)-(103) pp.23-25; Sec. VI (conclusion).",
 "read_status":"READ",
 "via":"Full v1 text as returned by alphaXiv get_paper_content(fullText=true) earlier in this DOCKET 67 workflow (stage for key 2309.10848), saved at scratchpad/d67/src/2309.10848.txt (84,715 bytes, md5 4f31876842f625e48506444afd216ee0) and .flat; every quotation below was read from that file in this stage. A fresh alphaXiv call in THIS stage (answer_pdf_queries and get_paper_content) was refused with 'alphaXiv assistant quota exceeded', so no second retrieval was possible; the text read is the alphaXiv extraction, not a re-fetch. Barcelo-Visser 2000 (gr-qc/0003025, FFKP ref.[2], whose Sec. II FFKP says it 'roughly follow[s]') was read from scratchpad/d67/src/gr-qc_0003025.txt for its eq.(3.17). Only v1 read: per the tree's fluctuation.py precedent, discrepancies below are not to be quoted against the SciPost version until it is read."
},
"published_statement":"(a) Sec. I: 'classically, non-minimal coupling can be eliminated by a combined conformal transformation and field redefinition, as we review in Sec. II, roughly following [2]. The results of this section are not new. This field redefinition mixes the gravitational field and the scalar field and it takes us to the Einstein frame, where the NEC is obeyed. However, if the scalar field was initially free ... the field redefinition introduces a self-interaction.' 'In general, both descriptions are equally valid, and the question of which metric is the physical one depends on the probe ... A key point, however, is that our EFT assumption enforces that the two metrics differ by a small amount. In particular, they are related by g~_mn ≈ e^{-(2/(n-2))(8 pi G_N xi) phi^2} g_mn. (3) Within the EFT framework, when M^2_cutoff is Planckian or sub-Planckian, the quantity in the exponent is small and the two metrics are close.' (b) Sec. II.C: g~ = Omega^2 g, phi~ = F(phi) (21); Einstein-frame action with V~ = Omega^-n (Lambda/(8 pi G_N) + V) (22); T~_mn = d~phi~ d~phi~ - (1/2) g~ (2V~ + (d~phi~)^2) (23); 'Then the null energy is rho~_n = (l.d~phi~)^2 (24) thus always obeying the NEC classically. The two frames are evidently not equivalent in terms of classical energy conditions as the NEC in the Einstein frame is obeyed while in the Jordan frame there are violations. Extending this argument from classical to quantum field theory is not straightforward.' ... 'While there is no relevant theorem ... This point requires further consideration, but so far it seems that it is impossible to construct traversable wormholes in the Jordan frame without unphysical field values. In that sense the two frames can be considered equivalent.' (c) Sec. V.A: Omega(phi) = (1 - 8 pi G_N xi phi^2)^{1/(n-2)} (99); F'(phi) = (1 - 8 pi G_N xi phi^2)^{-1} sqrt(1 - 8 pi G_N xi (1 - xi/xi_c) phi^2) (100); at xi = xi_c F = arctanh(sqrt(8 pi G_N xi_c) phi)/sqrt(8 pi G_N xi_c) (103). 'Calculating J [the Jacobian] explicitly is sensitive to the regulation scheme ... beyond the scope of this work.' 'the more conservative conclusion: when viewed as an EFT with field values bounded by |8 pi G_N xi phi^2| << 1, the mapping from Jordan frame to Einstein frame can also be done in the quantum theory.' (d) Sec. VI: 'the transformation between the two frames leaves the Einstein frame theory as an interacting QFT, for which there are no known state-independent bounds in n > 2.' (e) Sec. II.B eq.(18): 'For xi < 0 any local maximum of phi^2 violates the NEC. For xi > 0 and small field values 8 pi xi G_N phi^2 < 1 any local minimum of phi^2 is a violation' [of the effective NEC, Jordan frame].",
"published_hypotheses":[
 "P1 scalar phi non-minimally coupled, action R/(16 pi G_N) - (1/2)(d phi)^2 - V(phi) - (xi/2) R phi^2 (eq. 7/109), any potential V (incl. Lambda); signature (-,+,...,+), hbar = c = 1",
 "P2 the map g~ = Omega^2 g, Omega^(n-2) = 1 - 8 pi G_N xi phi^2 (99), exists only where 1 - 8 pi G_N xi phi^2 > 0: for xi > 0 it requires phi^2 < (8 pi G_N xi)^-1 (Barcelo-Visser eq. 3.17 and text: solutions at Phi = 1/sqrt(6 xi) 'cannot be obtained by means of the conformal transformation', and among them are traversable wormholes); for xi < 0 it exists at every phi",
 "P3 'NEC obeyed' is CLASSICAL and in the Einstein frame (eq. 24); the Einstein-frame theory is interacting even if phi was free; 'Extending this argument from classical to quantum field theory is not straightforward'",
 "P4 eq. (3) is an APPROXIMATION ('≈'); the exact factor is (1 - 8 pi G_N xi phi^2)^{2/(n-2)} (from 99)",
 "P5 'the two metrics are close' rests on the EFT assumption of a single cutoff (eq. 2) with phi^2_max ~ M_cutoff^(n-2), stated as holding 'when M^2_cutoff is Planckian or sub-Planckian'",
 "P6 quantum map: argued (not proved) for |8 pi G_N xi phi^2| << 1; path-integral Jacobian not computed; for xi < 0 'there is no natural reason to associate this field cutoff with the Planck scale'",
 "P7 frame 'equivalence' is claimed only 'in that sense' -- no traversable wormhole without unphysical field values -- on the basis of the effective ANEC, with 'no relevant theorem' for long wormholes and the point 'requires further consideration'; the frames are 'evidently not equivalent in terms of classical energy conditions'"
],
"hypothesis_drift":[
 "OVERSTATED (factor), candidates.py:235-236 'the two metrics differ by a factor exp(-2 (8 pi G xi phi^2)/(n-2))': the source prints this with '≈' (eq. 3); the exact factor is (1 - x)^{2/(n-2)}, x = 8 pi G xi phi^2 (eq. 99). Rederive K4: they agree to O(x) and differ by -x^2/(n-2) at O(x^2); at n = 4 the relative gap is 0.53% at x = 0.1, 17.6% at x = 0.5, and at x -> 1 (xi > 0) the exact factor -> 0 while the exponential -> e^{-2/(n-2)}. A DISCREPANCY of presentation, immaterial where the tree's own hypothesis (small x) holds.",
 "ADDED/STRENGTHENED (interpretation), candidates.py:236-237 'The exotic behaviour is a frame artefact everywhere the EFT is valid.': not a statement of the source. FFKP say the frames are 'evidently not equivalent in terms of classical energy conditions', that in the Jordan frame the effective NEC is violated at SMALL field values (eq. 18: xi > 0, 8 pi xi G phi^2 < 1, any local minimum of phi^2), and that the frames are equivalent only 'in that sense' that traversable wormholes appear to need unphysical field values ('there is no relevant theorem', 'requires further consideration'). Rederive K6 exhibits a Jordan-frame effective-NEC violation rho_eff = -40/1197 at kappa xi phi^2 <= 0.003 (EFT-valid), with effective ANEC +5.51e-3 >= 0; K8 shows the local violation tends to -xi (phi^2)'' = -1/30 as kappa -> 0, i.e. it does NOT shrink as the metric factor -> 1. Closeness of the metrics is a C^0 statement; the effective null energy depends on second derivatives of phi^2. What survives in the source is narrower: the AVERAGED (effective ANEC) obstruction to wormholes at bounded field, classically.",
 "DROPPED (quantum qualifier on the 'artefact' sentence), candidates.py:237: the tree qualifies 'NEC is obeyed classically' (line 235) correctly, but the 'frame artefact' sentence carries no classical/quantum qualifier; the source says the quantum map is argued only for |8 pi G xi phi^2| << 1 with the Jacobian uncomputed (Sec. V.A) and that the Einstein-frame theory is interacting with 'no known state-independent bounds in n > 2' (Sec. VI). So in the quantum theory the Einstein frame is not known to obey any NEC-type bound; 'artefact' is not established there.",
 "DROPPED (domain of the map), candidates.py:233-235: the map exists for xi > 0 only where 8 pi G xi phi^2 < 1 (rederive K2 domain note; Barcelo-Visser 3.17: the x = 1 solutions, which include traversable wormholes, 'cannot be obtained by means of the conformal transformation'). The tree's hypothesis 'EFT assumption (small 8 pi G xi phi^2)' implies this, so the drop is covered by the named hypothesis -- recorded for completeness, not as a defect.",
 "NOT INHERITED (a source discrepancy the tree avoids), FFKP Sec. I after eq.(3) 'when M^2_cutoff is Planckian or sub-Planckian, the quantity in the exponent is small': with phi^2_max ~ M_c^(n-2) (eq. 2) and non-reduced M_P, x = 8 pi xi (M_c/M_P)^(n-2) = 4.19 at M_c = M_P, xi = 1/6 (n = 4) -- not small and > 1, where Omega^2 < 0 (rederive K5); with the reduced Planck mass x = xi (M_c/Mbar_P)^(n-2) = 0.167. The sentence holds only for strictly sub-Planckian cutoff or |xi| << 1, depending on which Planck mass is meant (the paper does not say). The tree states its hypothesis as 'small 8 pi G xi phi^2' directly (candidates.py:235 'under the EFT assumption'), so it does not rely on the Planckian gloss. Recorded as a discrepancy in the source, not a refutation.",
 "CONTEXT (consistency with the tree's own numbers), candidates.py 4c (NMC crossover 3.159514 l_P): at l_UV = 3.159514 l_P, x = 8 pi xi (l_P/l_UV)^2 = 2.5177 xi (rederive K5) -- 0.42 at xi = 1/6 (exact factor 0.58, not 'close to one'), > 1 for |xi| >= 0.397. So the frame factor is close to one only well away from the tree's crossover; this is consistent with the tree's own line 'THE CUTOFF THAT WOULD WORK IS THE ONE THE EFT EXCLUDES' (candidates.py:219-225) and does not contradict line 236, which is scoped 'under the EFT assumption'."
],
"data_at_publication":[
 {"quantity":"G_N (enters only through x = 8 pi G xi phi^2, dimensionless in Planck units)","value_then":"not quoted numerically in the frame-map passages (symbolic G_N)","value_now":"CODATA 2022 G = 6.67430(15)e-11 m^3 kg^-1 s^-2, unchanged from CODATA 2018","source_now":"CODATA 2022 (scratchpad/d67/src/codata as used by other DOCKET 67 stages)","moves_conclusion":"No: the conclusion is algebraic in x; G cancels when phi is expressed in Planck units."},
 {"quantity":"xi (non-minimal coupling of any physical scalar)","value_then":"free parameter; xi_c = (n-2)/(4(n-1)) used as the worked example","value_now":"still unmeasured for any fundamental scalar (the tree carries it as a parameter)","source_now":"no measurement exists; not a datum","moves_conclusion":"Not a datum: 'close to one' needs |xi| (M_c/Mbar_P)^(n-2) << 1, so a large xi (e.g. O(10^4) as in Higgs-inflation models, not read here) would shrink the validity window; this is carried by the tree's named EFT hypothesis."},
 {"quantity":"M_cutoff / phi_max","value_then":"EFT assumption phi^2_max ~ M_c^(n-2) (eq. 2); Sec. V bound phi^2_max <~ (8 pi G |xi|)^-1","value_now":"unchanged; no measurement","source_now":"not a datum","moves_conclusion":"Not a datum; it is the named hypothesis."}
],
"rederivation":{
 "method":"sympy",
 "script_path":D+"/rederive/2309.10848-frame-map.py",
 "outcome":"ALL PASS (exit 0). K1: the n-dimensional conformal transformation R = Omega^2[R~ + 2(n-1) box~ lnOmega - (n-2)(n-1)(d~lnOmega)^2] verified on explicit metrics at n = 3 and 4 (|diff| < 4e-15). K2: from K1 with Omega^(n-2) = 1 - kappa xi phi^2, F'^2 = [1 - kappa xi (1 - xi/xi_c) phi^2]/(1 - kappa xi phi^2)^2 == FFKP (100) squared exactly; Omega^(2-n) A = 1 (canonical Einstein-frame Planck mass); FFKP (103) arctanh form reproduced at xi = xi_c; agrees with Barcelo-Visser (3.17) at n = 4. K3: a g-null vector is g~-null and T~_ll = (l.d phi~)^2 >= 0 for any V~ (FFKP 24). K4: exact (1-x)^{2/(n-2)} - exp(-2x/(n-2)) = -x^2/(n-2) + O(x^3) for n = 3..6; measured gaps 0.53% (x = 0.1), 17.6% (x = 0.5), 97% (x = 0.99). K5: x = 8 pi xi at M_c = M_P (4.19 at xi = 1/6), x = xi at reduced Planck; at the tree's crossover x = 2.5177 xi. K6: Jordan-frame effective NEC (FFKP 18) violated, rho_eff(0) = -40/1197, for a smooth profile with max kappa xi phi^2 = 0.00288; its effective ANEC = +5.508e-3 (eq. 19 and 20 agree). K7: FFKP (20) follows from (19) by parts, coefficient (1 - 4 xi) exact for this rho_eff. K8: the K6 violation -> -1/30 as kappa -> 0: metric closeness does not control local effective null energy.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"discover_papers (this stage)","effect":"contested","what":"The one allowed discover_papers call was REFUSED ('alphaXiv assistant quota exceeded'); an arXiv API fallback was blocked by the egress proxy (403). No later-literature search was completed in this stage; nothing is claimed from absence.","read_status":"NOT RUN (quota / proxy refusal)"},
 {"ref":"DOCKET 67 stage 2309.10848 (same paper, earlier in this workflow): discover_papers 2023-09 onward on NMC / SNEC / QEI","effect":"confirms","what":"Returned no paper that narrows, contradicts or supersedes FFKP (hits 2606.08003, 2512.04934, 2601.18860, 2510.26247, 2608.01814, 2608.11817; the search was on the null-energy bound, not the frame map). One search, titles only: NOT-FOUND, not confirmation.","read_status":"search results only, carried from audits/2309.10848.json"},
 {"ref":"C. Barcelo & M. Visser, gr-qc/0003025, CQG 17 (2000) 3843 (FFKP ref.[2], the classical source FFKP Sec. II follows)","effect":"confirms","what":"Eq. (3.17): Omega^2 = 1/(1 - 6 xi Phi^2), dPhi_m/dPhi_xi = sqrt(1 - 6 xi(1 - 6 xi) Phi^2)/(1 - 6 xi Phi^2), Phi = phi/sqrt(6 kappa): identical to FFKP (99)-(100) at n = 4 (rederive K2). Also: solutions at Phi = 1/sqrt(6 xi) 'cannot be obtained by means of the conformal transformation procedure' and include traversable wormholes -- the map's domain restriction (P2). Precedes FFKP; not later literature, read as the origin of the map.","read_status":"READ (text at scratchpad/d67/src/gr-qc_0003025.txt, Sec. 3 around eq. 3.17)"},
 {"ref":"V. Faraoni, E. Gunzig, P. Nardone, gr-qc/9811047 (FFKP ref.[12]); G. Magnano & L.M. Sokolowski, gr-qc/9312008 (FFKP ref.[11])","effect":"contested","what":"Cited by FFKP as questioning the physical equivalence of the two frames ([12]) and as arguing the Einstein frame is the physical one ([11]). Both PRECEDE FFKP; they show the frame question is contested in the literature, which bears on the tree's 'frame artefact' reading. Contents not read here.","read_status":"NAMED-NOT-READ (known only from FFKP's text and reference list)"}
],
"lacked_data":"M's hypothesis tested for this result. The frame map is a classical identity (a change of variables in the action), not an extrapolation from measurement: rederive K1-K3 reproduce it from first principles with no numerical input, and it agrees with its 2000 source (Barcelo-Visser 3.17). The only constant, G, enters through the dimensionless x = 8 pi G xi phi^2 and cancels in Planck units; CODATA 2022 G equals CODATA 2018. What the authors lacked is not data but two unfixed parameters -- xi for any physical scalar and the field cutoff phi_max -- and a quantum computation (the path-integral Jacobian, 'beyond the scope of this work'; Einstein-frame QEIs for interacting fields, 'no known state-independent bounds in n > 2'). Having xi and phi_max would decide WHERE x << 1 holds (e.g. the tree's crossover gives x = 2.52 xi), not whether the map is right. The quantum gaps are gaps of derivation, and they bear on the tree's 'frame artefact' sentence, which the source does not make. No evidence found that any datum the authors lacked changes the conclusion; evidence the other way is the exact classical re-derivation.",
"grade":"NARROWED",
"grade_evidence":"The mathematics the tree quotes STANDS as re-derived: the conformal map and field redefinition (FFKP 21, 98-103) follow from the n-dimensional curvature transformation (K1, K2, exact), the Einstein-frame null energy is (l.d phi~)^2 >= 0 for any potential (K3), and exp(-2x/(n-2)) is the O(x) form of the exact (1-x)^{2/(n-2)} (K4). But the tree's use is broader than the source in two named ways: (i) candidates.py:236-237 'The exotic behaviour is a frame artefact everywhere the EFT is valid' is not the source's claim -- FFKP say the frames are 'evidently not equivalent in terms of classical energy conditions', exhibit Jordan-frame effective-NEC violations at small field values (eq. 18; K6 at kappa xi phi^2 <= 0.003), and claim equivalence only 'in that sense' of no traversable wormholes without unphysical field values, argued from the effective ANEC with 'no relevant theorem'; K8 shows the local violation does not vanish as the metric factor -> 1; (ii) the sentence carries no classical qualifier, while the source's quantum map is argued (Jacobian uncomputed) and the Einstein frame has 'no known state-independent bounds in n > 2'. The factor is printed '≈' in the source and stated exactly in the tree (candidates.py:235-236) -- a discrepancy, not WRONG. The tree's downstream verdict (candidates 'non-minimal coupling' fails) does not rest on the artefact sentence alone: the magnitude gate is separate (audits/2309.10848.json), and the tree's own crossover lies where x = 2.52 xi, outside the regime in which the frame factor is close to one, which is consistent with its 'cutoff the EFT excludes' line. Grade NARROWED: the result holds for the averaged (effective-ANEC) obstruction, classically, on 8 pi G xi phi^2 < 1 -- a smaller class than 'the exotic behaviour ... everywhere the EFT is valid'.",
"what_would_change_the_grade":"To STANDS: the tree rescopes line 236-237 to the source's claim (classical; effective ANEC / traversable-wormhole obstruction at bounded field; frames 'equivalent in that sense'), and writes the factor as (1 - 8 pi G xi phi^2)^{2/(n-2)} or marks the exponential '≈'. Or a later paper (not found here; the search was refused by quota) proves an Einstein-frame QEI for the interacting theory and a theorem that no Jordan-frame local NEC violation at bounded field produces an exotic geometry. To WRONG: only a computed contradiction to K1-K3 (none found; all exact). Reading the SciPost version (16, 119 (2024)) could change the quoted wording; until read, the v1 wording governs.",
"reverify_command":"python3 /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/rederive/2309.10848-frame-map.py && grep -n -E 'frame artefact|CLOSE TO ONE|NEC is obeyed classically' /home/user/Claude-Method-Works/research/warp-drive/candidates.py && python3 -c \"t=open('/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/src/2309.10848.flat').read(); [print(t[t.find(k)-200:t.find(k)+300],'\\n') for k in ['evidently not equivalent','any local minimum of','In that sense the two frames','no known state-independent']]\"",
"report_path":D+"/audits/2309.10848-frame-map.json"
}
json.dump(r,open(D+"/audits/2309.10848-frame-map.json","w"),indent=1,ensure_ascii=False)
print("ok")
