import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "birkhoff-einstein-maxwell",
 "name": "Birkhoff's theorem for Einstein-Maxwell (spherical electrovac is Reissner-Nordstrom; mass function frozen)",
 "source": {
  "located": "Classics, no arXiv copy: Jebsen, Ark. Mat. Astr. Fys. 15 (1921); Birkhoff & Langer, Relativity and Modern Physics (1923); Einstein-Maxwell extension B. Hoffmann, Quart. J. Math. 3, 226 (1932) and 4, 179 (1933) (attribution per Schleich & Witt 0908.4110 ref [10]); Bertotti, Phys. Rev. 116, 1331 (1959); Robinson (1959); Tariq & Tupper, J. Math. Phys. 15, 2232 (1974); Frolov & Zelnikov, Introduction to Black Hole Physics (OUP 2011) p.166 'Generalized Birkhoff theorem'. Read via: D. Kubiznak, O. Svitek, T. Tahamtan, arXiv:2605.01811v1 (2026) pp.1-7, which restates the Frolov-Zelnikov theorem verbatim (Theorem 1, eqs 14-15) and the Maxwell/Bertotti-Robinson case (eqs 16-17, 21-22, 50-54, 62-64); K. Schleich & D. M. Witt, arXiv:0908.4110 (J. Math. Phys. 51, 112502, 2010) pp.1-6 (local-uniqueness form, Lambda, Nariai exception, 'staticity' folklore); R. Ghosh, A. K. Mishra, A. Chowdhury, arXiv:2411.09193v2 pp.1-2 (history, 'Reissner-Nordstrom is the unique spherically symmetric solution of the Einstein-Maxwell equations [16 = d'Inverno 1992]').",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "alphaXiv answer_pdf_queries on 2605.01811 (pp.1-8,17), 0908.4110 (pp.1-10), 2411.09193 (pp.1-8). Hoffmann 1932/33, Jebsen 1921, Birkhoff 1923, Frolov-Zelnikov 2011, Bertotti 1959, Tariq-Tupper 1974 are NAMED-NOT-READ (only restated). Owner re-read: research/warp-drive/drivensource.py (md5 5c67a71c9750390fbc83a03de745b236) lines 40-57, 91-110, 250-263, 283-343, 446-460, 515-523, 600-625; specthm.py:873-898 (R3 cites EM_CLOSED_BY). The owner's own selftest section 2 was run read-only: both MS residuals 0, exit 0."
 },
 "published_statement": "Frolov & Zelnikov (2011) p.166, restated verbatim in 2605.01811 p.3 as Theorem 1 (Generalized Birkhoff's theorem): 'If the energy-momentum tensor generating a spherically symmetric gravitational field of the form ds^2 = gamma_AB dx^A dx^B + R(x)^2 dOmega^2, where ... R(x) is a non-constant function, obeys the following condition: T_AB = (1/2) T^C_C gamma_AB, then the corresponding solution of the Einstein equations possesses an additional Killing vector field.' With the Maxwell ansatz A = phi(t,r) dt + p cos(theta) dphi (electric AND magnetic charge) the condition holds and the unique solution with R non-constant is f = 1 - 2M/r + (Q_e^2 + Q_m^2)/r^2 (2605.01811 eqs 16-18, 62). 'A generalization of this theorem to the electro-vacuum case of the Einstein-Maxwell theory gives Reissner-Nordstrom metric as a unique asymptotically flat solution. However, in such a case, there also exists a spherically symmetric but not asymptotically flat solution - the so called Bertotti-Robinson universe' (2605.01811 p.1); BR = AdS2 x S2 with R0 = sqrt(e^2 + p^2) (eq 21). Schleich & Witt 0908.4110 p.1: generalized Birkhoff theorems 'are local uniqueness theorems ... their corollary is that locally spherically symmetric solutions exhibit an additional local Killing vector field; however this field is not necessarily timelike', and 'the common belief that Birkhoff's theorem implies staticity is false' (interior regions; Lambda > 0).",
 "published_hypotheses": [
  "4-dimensional general relativity, Einstein equations G_ab = 8 pi T_ab (with Lambda in the Schleich-Witt / Kubiznak et al. generalizations)",
  "local spherical symmetry: SO(3) acting with 2-dimensional spacelike orbits (Schleich-Witt Definition 2); metric gamma_AB dx^A dx^B + R^2 dOmega^2",
  "R(x) NON-CONSTANT (grad R != 0): 'The assumption that the radial function R(t,r) is non-constant is crucial' (2605.01811 p.3); R = const gives Bertotti-Robinson (Lambda = 0) or Plebanski-Hacyan / charged Nariai (Lambda != 0)",
  "source obeys T_AB = (1/2) T^C_C gamma_AB (satisfied by source-free Maxwell, and by any L(S,P) nonlinear electrodynamics, with the spherically symmetric field A = phi dt + p cos(theta) dphi)",
  "source-free Maxwell (no charged matter in the region); electric and magnetic charge both allowed",
  "the conclusion is LOCAL (locally isometric to a region of RN or of BR); the extra Killing vector is timelike only where grad R is spacelike -- staticity is not implied inside horizons",
  "metric regularity: C^2 in the classical proof; C^0 piecewise-C^1 suffices per Bergmann-Cahen-Komar 1965 (restated in 2411.09193 p.1-2; NAMED-NOT-READ)",
  "asymptotic flatness is NOT a hypothesis of the local theorem; it is used only to exclude BR in the 'unique asymptotically flat solution' phrasing"
 ],
 "hypothesis_drift": [
  "DROPPED: 'R non-constant'. The canonical name and drivensource.py:101-102 ('That is Birkhoff's theorem for Einstein-Maxwell') identify the frozen mass with Birkhoff, whose RN-uniqueness half fails at grad R = 0: Bertotti-Robinson is spherically symmetric electrovac and not locally RN (re-derivation E5: G = 8 pi T iff R0^2 = q_e^2 + q_m^2; Weyl^2 = 0 vs RN Weyl^2 = 48 (Mr - Q^2)^2/r^8). The owner's OPERATIVE claim survives: BR's Misner-Sharp mass is R0/2 = M - Q^2/(2 R0) with the constant M = R0, so m is still frozen (E5). Discrepancy in the statement, not in the conclusion drawn.",
  "FALSE AUXILIARY STATEMENT: drivensource.py:286 ('the ONLY spherically symmetric field') and :302 ('Spherical symmetry admits only F_{tr} (radial electric)'). The magnetic monopole F_{theta phi} = P sin(theta) is also spherically symmetric and is in the published ansatz (2605.01811 eq 16, 21). Re-derivation E2-E3: with P, Maxwell holds for arbitrary Phi, Lambda, R; rho = (Q^2+P^2)/(8 pi R^4), j = 0, p_r = -rho, p_T = rho; m = M - (Q^2+P^2)/(2R) frozen. The tree's conclusion (EM cannot evolve m) survives with Q^2 -> Q^2 + P^2; its scope sentence 'pure electrovac' (line 459) is therefore right, its uniqueness sentence (286, 302) is not.",
  "UNSTATED: Lambda = 0. Inherited from nonstatic.py:66-67 (MS-r, MS-t carry no Lambda). With Lambda the frozen form is m = M - Q^2/(2R) + Lambda R^3/6 (E6; the tree's m does NOT solve the Lambda-equations), and the exception set gains the charged Nariai / Plebanski-Hacyan product spaces (2605.01811 sec IV.C). The freezing (m a fixed function of R, no dynamical freedom) survives; the formula at drivensource.py:98 is the Lambda = 0 case. Numerically the Lambda term is 4.1e-23 of G M_sun/c^2 at 1 AU (E9).",
  "WEAKENED (scope of the equivalence): drivensource.py:98-102 checks only MS-r and MS-t (the G_uu, G_un, G_nn content, E1). That is the Kodama/Misner-Sharp half of Birkhoff. The full theorem additionally needs the trace-free orbit-space Einstein equation, which forces Hess(R) proportional to gamma_AB and makes the Kodama vector Killing (E4, checked as an identity). The tree's claim 'That is Birkhoff's theorem' is thus stronger than what its code checks; the missing half is checked here and holds, so nothing the tree concludes is lost.",
  "NOT A DRIFT, RECORDED: the tree does not claim staticity (the Schleich-Witt caution), and it excludes charged fluids, non-spherical fields and nonlinear electrodynamics (drivensource.py:109-110, 259-263, 459-460). The NLED exclusion is conservative: 2605.01811 sec III extends the Birkhoff condition to any L(S,P) spherically symmetric field.",
  "USE NOTE on rests_on_it (EM_CAN_SOURCE_DRIVEN_CONTRACTION = False, drivensource.py:454; 'the driven branch has no electromagnetic degree of freedom to drive it', :619-620): Birkhoff fixes the GEOMETRY (locally RN or BR) and freezes m; it does not make the driven condition 2m/R < e^{-2Phi} Rdot^2 (nonstatic.py:34) false in electrovac. W^2 - U^2 = 1 - 2m/R is slice-invariant and a boosted slice-normal in the RN exterior satisfies the driven condition (E7, z3 SAT, witness M = 9/32, Q = 1/4, R = 1, v = 3/4), exactly as Milne slicing of Minkowski does at m = 0. The flag is true in the sense the owner words it (EM supplies no degree of freedom; any contraction in electrovac is a slicing of fixed RN), not in the sense 'the condition cannot hold'. Recorded for the owner; not a defect of the external theorem."
 ],
 "data_at_publication": [
  {"quantity": "numerical inputs to Birkhoff's conclusion", "value_then": "none (1932 theorem; symbolic Q, P, M)", "value_now": "none", "source_now": "2605.01811 eq 18 and 0908.4110 Thm 1: purely structural", "moves_conclusion": "no -- no datum enters"},
  {"quantity": "cosmological constant Lambda (a hypothesis, set to 0 at the owner)", "value_then": "Lambda = 0 assumed (Hoffmann 1932; nonstatic.py MS equations)", "value_now": "Lambda = 3 Omega_L H0^2/c^2 = 1.089e-52 m^-2 from Omega_L = 0.6847 +- 0.0073, H0 = 67.36 +- 0.54 km/s/Mpc; Planck quotes Lambda = (4.24 +- 0.11)e-66 eV^2", "source_now": "Planck 2018 VI, arXiv:1807.06209 Table 2 and eqs (14)-(15), READ", "moves_conclusion": "formula yes (m gains Lambda R^3/6), conclusion no: m remains a fixed function of R; term is 4.1e-23 of G M_sun/c^2 at 1 AU and equals it only at ~140 pc (E9; M_sun mass value used there is the nominal 1.98840987e30 kg, not read in this audit, illustrative only)"},
  {"quantity": "EPS0, G in drivensource.py:278-280 (CODATA 2018)", "value_then": "8.8541878128e-12 F/m; 6.67430e-11", "value_now": "not re-read in this audit (used only by section 4 X_of_Q, not by the Birkhoff step)", "source_now": "see sibling audit si-astro-constants-c-g-msun-ly", "moves_conclusion": "no -- the Birkhoff statement and birkhoff_residuals() are symbolic"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/birkhoff-einstein-maxwell.py",
  "outcome": "28 PASS, 0 FAIL, exit 0, ~10 s (script md5 8e3d426a444d454158b1f4dadbad99dd; sympy 1.14.0, z3 4.x/5.1.0). Independent of the board (nothing imported; Einstein tensor built from the metric). E1: the tree's MS-r and MS-t are identities D_r m = (R^2/2)(G_uu W - G_un U), D_t m = -(R^2/2)(G_nn U - G_un W) for arbitrary Phi(t,r), Lambda(t,r), R(t,r). E2: dyonic field F_tr = Q e^{Phi+Lam}/R^2, F_thph = P sin(th) solves dF = 0 and d*F = 0 in the full dynamical metric; rho = (Q^2+P^2)/(8 pi R^4), j = 0, p_r = -rho, p_T = rho. E3: m = M - (Q^2+P^2)/(2R) solves MS-r and MS-t for arbitrary Phi, Lam, R, and any solution differs from it by a constant (agrees with the owner's birkhoff_residuals at P = 0). E4: identity G_AB - gamma_AB G/2 = -(2/R)(Hess R - gamma tr Hess R/2); electrovac T_AB = -rho gamma_AB; 2 nabla_(A K_B) equals the eps-contraction of the trace-free Hessian, so the Kodama vector is Killing; K.K = -|grad R|^2 (static only where grad R spacelike). E5: Bertotti-Robinson AdS2 x S2 solves Einstein-Maxwell iff R0^2 = q_e^2 + q_m^2, is conformally flat, RN is not (Weyl^2 = 48 (Mr - Q^2)^2/r^8): the grad R = 0 exception is real; BR's MS mass R0/2 fits m = M - Q^2/2R with M = R0. E6: with Lambda, m = M - Q^2/2R + Lambda R^3/6; the tree's Lambda-free m fails there. E7: z3 SAT for the driven condition in an RN-exterior boosted slicing; UNSAT in the static slicing with m > 0. E8: RN satisfies G = 8 pi T in static gauge. E9: Lambda from Planck 2018 = 1.089e-52 m^-2, negligible at solar-system scale.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "D. Kubiznak, O. Svitek, T. Tahamtan, arXiv:2605.01811 (2026)", "effect": "extends", "what": "Birkhoff condition T_AB = (1/2) T gamma_AB holds for ANY L(S,P) nonlinear electrodynamics with a spherically symmetric electric+magnetic field, so the generalized theorem (static f(r), unique for R non-constant) covers NLED; the R = const branch gives generalized Bertotti-Robinson with unequal AdS2/S2 radii. The tree's NLED exclusion (drivensource.py:262) is therefore conservative, not a gap in its argument.", "read_status": "READ (alphaXiv pp.1-8, 17)"},
  {"ref": "K. Schleich & D. M. Witt, arXiv:0908.4110, J. Math. Phys. 51, 112502 (2010)", "effect": "narrows", "what": "Generalized Birkhoff theorems are LOCAL uniqueness theorems; the extra Killing vector need not be timelike; staticity folklore is false (interiors; no static region at all for extremal/over-extremal SdS). Narrows the common 'static' phrasing (including the wording in 2605.01811 p.1 and 2411.09193 abstract), not the tree, which never claims staticity.", "read_status": "READ (alphaXiv pp.1-10)"},
  {"ref": "R. Ghosh, A. K. Mishra, A. Chowdhury, arXiv:2411.09193v2 (2024/2025)", "effect": "extends", "what": "Birkhoff in the Einstein branch of quadratic and higher-curvature gravity (vacuum); history: Einstein-Maxwell extension cited to d'Inverno; C^0 piecewise-C^1 regularity suffices (Bergmann-Cahen-Komar 1965). Does not touch the electrovac statement.", "read_status": "READ (alphaXiv pp.1-8)"},
  {"ref": "R. Goswami & G. F. R. Ellis, arXiv:1101.4520 (Almost Birkhoff theorem, 2011)", "effect": "extends", "what": "Rigidity of spherical vacuum persists under small perturbations of LRS-II; surfaced by discover_papers, abstract only.", "read_status": "abstract only (discover_papers listing); NOT read"},
  {"ref": "arXiv:2402.16484 (Geometrical origin of the Kodama vector, 2024)", "effect": "confirms", "what": "Kodama-vector conserved current in warped products, the structure used in E4; surfaced by discover_papers.", "read_status": "abstract only; NOT read"}
 ],
 "lacked_data": "M's hypothesis tested for this result. Birkhoff for Einstein-Maxwell (Hoffmann 1932-33) is a theorem of classical GR + linear Maxwell; its conclusion takes no measured input, so no later datum can move it (re-derivation E1-E4 holds for arbitrary metric functions and symbolic charges). What the 1932 authors lacked, and whether it matters: (1) magnetic monopoles were only proposed by Dirac in 1931 -- the dyonic case is now standard in the restatements (2605.01811 eq 16) and moves nothing but Q^2 -> Q^2 + P^2 (E2-E3); (2) a measured Lambda (1998 onward; Planck 2018 gives 1.089e-52 m^-2) -- it changes the frozen FORM (m + Lambda R^3/6) and adds Nariai-type exceptions, not the freezing, and is numerically negligible below ~100 pc (E6, E9); (3) Bertotti-Robinson (1959) -- a solution the 1932 uniqueness phrasing did not list; it is the grad R = 0 exception, real (E5), but it too has frozen m; (4) strong-field QED (Euler-Heisenberg nonlinear electrodynamics, 1936) -- 2605.01811 shows the Birkhoff condition holds for any L(S,P), so the structural conclusion survives, with a different m(R). Evidence either way: every piece of later data examined leaves 'the Misner-Sharp mass of spherical source-free electromagnetism is a fixed function of R' standing; what later knowledge corrects is the completeness of the statement (the exception set and the field ansatz), which is where the tree's wording drifts.",
 "grade": "NARROWED",
 "grade_evidence": "The external result STANDS at source: the generalized Birkhoff theorem for Einstein-Maxwell (local; R non-constant; T_AB = T gamma_AB/2) is read via exact restatement and re-derived here independently (sympy, 28/28 PASS, including the full Kodama-Killing step the owner's code does not run). The grade is NARROWED because the tree states it on a larger class than it holds on and drops hypotheses at three owner sites: (i) R non-constant is dropped -- 'spherical electrovac is RN' / 'That is Birkhoff's theorem' (drivensource.py:101-102) fails on Bertotti-Robinson, shown as an explicit electrovac counterexample to RN-uniqueness (E5); (ii) drivensource.py:286 and :302 assert F_tr is the ONLY spherically symmetric field, false by the magnetic monopole (E2); (iii) Lambda = 0 is unstated (nonstatic.py:66-67 inherited), and the frozen formula m = M - Q^2/2R is its Lambda = 0 case (E6). None of the three moves the operative conclusion EM_CLOSED_BY / 'the mass function is frozen': m is frozen on BR (M = R0), for dyons (Q^2 + P^2) and with Lambda (+ Lambda R^3/6). Separately recorded, not graded against the source: the flag EM_CAN_SOURCE_DRIVEN_CONTRACTION = False is true only as 'EM adds no degree of freedom' -- the driven condition itself is satisfiable inside fixed RN by a boosted slicing (E7, z3 SAT). No datum enters; nothing is DATA-DEPENDENT. Nothing is WRONG: no statement of the source is contradicted, and the tree's discrepancies are wording/scope, not a refuted conclusion.",
 "what_would_change_the_grade": "To STANDS: the owner restating the result with its published hypotheses -- 'for grad R != 0, locally RN; grad R = 0 gives Bertotti-Robinson (also frozen m)', 'F_tr and F_thph = P sin(theta) are the spherically symmetric fields (Q^2 -> Q^2 + P^2)', and 'Lambda = 0 (with Lambda, m = M - Q^2/2R + Lambda R^3/6)'. To WRONG: a spherically symmetric source-free Einstein-Maxwell solution whose Misner-Sharp mass is not a fixed function of R -- E3/E4 show none exists for C^2 metrics, so this would require failing a hypothesis (non-C^2 metric beyond Bergmann-Cahen-Komar, charged matter, non-spherical field). To OPEN: nothing here; reading Hoffmann 1932-33 directly would upgrade the source from READ-VIA-RESTATEMENT but cannot move the grade, since the modern restatements are what the re-derivation checks.",
 "reverify_command": "python3 " + D + "/rederive/birkhoff-einstein-maxwell.py  # expect '28 PASS, 0 FAIL', exit 0; and (read-only) cd /home/user/Claude-Method-Works/research/warp-drive && python3 drivensource.py --selftest | sed -n '/^2\\./,/^3\\./p'; sed -n '98,110p;283,305p;452,460p' drivensource.py",
 "report_path": D + "/audits/birkhoff-einstein-maxwell.json"
}
json.dump(rep, open(rep["report_path"], "w"), indent=1)
print("ok")
