import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/"
r = {
 "key": "1710.05834",
 "name": "GW170817/GRB170817A: (v_gw - c)/c <= 7e-16 (two-sided -3e-15 .. +7e-16)",
 "source": {
  "located": "LIGO Scientific Collaboration, Virgo Collaboration, Fermi GBM and INTEGRAL, 'Gravitational Waves and Gamma-Rays from a Binary Neutron Star Merger: GW170817 and GRB 170817A', arXiv:1710.05834v2 = ApJL 848:L13 (2017 Oct 20); abstract p.1 and sec 4 / 4.1 eq. (1), p.6.",
  "read_status": "READ",
  "via": "alphaXiv page text of 1710.05834v2 (pages 1, 6, 7, 23, 24, 26), fetched earlier in this workflow run and held at scratchpad/d67/src/1710.05834.cached.txt; the abstract and all of sec 4.1 were read there verbatim. In THIS stage every live alphaXiv call (answer_pdf_queries, get_paper_content, discover_papers) returned 'quota exceeded' and arxiv.org / ADS are refused by the egress proxy (403 / EGRESS_BLOCKED), so no re-read was possible; the cached text is the v2 = journal text (it carries the ApJL 848:L13 header). Later work READ from the same cache: Greene, Kabat, Levin, Menon arXiv:2206.13590v2 (GKLM) p.12-13 eqs (38)-(39); Polychronakos arXiv:2210.11497v3 sec 5 end."
 },
 "published_statement": "Abstract: 'We use the observed time delay of (+1.74 +/- 0.05) s between GRB 170817A and GW170817 to: (i) constrain the difference between the speed of gravity and the speed of light to be between -3e-15 and +7e-16 times the speed of light'. Sec 4.1: 'Assuming a small difference in travel time Delta t between photons and GWs, and the known travel distance D, the fractional speed difference during the trip can be written Delta v/v_EM ~ v_EM Delta t / D, where Delta v = v_GW - v_EM ... we conservatively use here D = 26 Mpc, the lower bound of the 90% credible interval on luminosity distance derived from the GW signal ... If we conservatively assume that the peak of the GW signal and the first photons were emitted simultaneously, attributing the entire (+1.74 +/- 0.05) s lag to faster travel by the GW signal, this time difference provides an upper bound on Delta v. To obtain a lower bound ... we assume the SGRB signal was emitted 10 s after the GW signal. The resulting constraint ... -3e-15 <= Delta v/v_EM <= +7e-16 (1)'. Then: 'Lags much longer than 10 s are proposed in alternative models ... and emission of photons before the merger is also possible (Tsang et al. 2012). Hence, certain exotic scenarios can extend this time difference window to (-100 s, 1000 s), yielding a 2 orders of magnitude broadening of the allowed velocity range on either side. While the emission times of the two messengers are inherently model dependent, conservative assumptions yield dramatic improvements...'",
 "published_hypotheses": [
  "H1 distance: D = 26 Mpc, the LOWER end of the 90% credible interval on the GW luminosity distance (smaller D = weaker bound, so conservative)",
  "H2 emission ordering (upper bound): the GW peak and the first photons were emitted simultaneously, i.e. photons were NOT emitted before the GW peak; the source itself names photon emission before merger as possible and gives an exotic window (-100 s, 1000 s) that broadens the range ~2 orders on either side",
  "H3 emission lag (lower bound): the SGRB was emitted no more than 10 s after the GW",
  "H4 v_EM is the photon speed; IGM dispersion of gamma rays negligible (stated); the bound is on v_GW relative to v_EM, not relative to an abstract c",
  "H5 both messengers are affected by background gravitational potentials in the same way (sec 4 intro: 'both waves are expected to be affected ... in the same way'); the Shapiro difference is treated separately in sec 4.3",
  "H6 small travel-time difference, a constant fractional speed difference 'during the trip', Delta v/v_EM ~ v_EM Delta t/D (no cosmological distance measure distinguished; luminosity distance used)",
  "H7 one event, one line of sight (NGC 4993), GW band of the LIGO/Virgo detection; the source says future joint detections are needed to separate emission delay from propagation delay"
 ],
 "hypothesis_drift": [
  "DROPPED H2 (emission ordering) -- branelink.py:61 'd = gamma - 1 <= 7.0e-16 (GW170817, manyc.py's seated bound ...)', branelink.py:132 'D_GW = manyc.GW170817_BOUND_HI  # (v_gw - c)/c <= 7e-16, READ there', ledger.py:1787-1790 'GW170817 bounds ... beta <= %.6e, CONDITIONAL on %s' (conditional only on the bulk graviton), manyc.py:32 and :68-69 'published, two-sided': the upper bound +7e-16 is used as unconditional, but the source derives it ONLY under 'peak of the GW signal and the first photons were emitted simultaneously' and itself names pre-merger photon emission as possible. Under the source's own exotic window (-100 s) the fast edge is +3.80e-14 (computed), beta <= 2.76e-7 and the B = 0 saving is 5.10 us rather than 93.81 ns. grep over branelink.py and ledger.py finds no occurrence of 'simultan', 'emitted' or 'intrinsic'.",
  "WEAKENED H4 (reference speed) -- branelink.py:132 and manyc.py:32/162 write (v_gw - c)/c; the source bounds Delta v / v_EM with Delta v = v_GW - v_EM. The identification v_EM = c is an added (standard, and on the brane exactly GKLM's 'light travels on the brane with speed c', 2206.13590 p.12) hypothesis; numerically immaterial.",
  "ADDED by the tree, outside the source's scope -- branelink.py:61 cites 'GKLM eq. (38) identifies Delta c/c = gamma - 1' and ledger.py:1787 says the bound applies to beta, not B. The source says nothing about branes; the mapping is GKLM's (2206.13590 p.12, READ: 'Assuming that light travels on the brane with speed c while a bulk field propagates with speed c+Delta c ... Delta c/c = gamma - 1 (38) ... If we entertain the possibility that these are bulk degrees of freedom, the bounds on brane velocity become very strict'). The tree NAMES the bulk-graviton condition (branelink.py:84-86, :172 BETA_BOUND_CONDITIONAL_ON; ledger.py:1788) -- correctly carried.",
  "PARTLY CARRIED H7 (single line of sight) -- for a moving/tilted brane the bulk speed is anisotropic (Polychronakos 2210.11497v3 sec 5, READ: the bound applies 'unless we happen to live in a tiltlike braneworld and the relative position of the binary star happened to be quite close to the direction phi_o'). The tree carries a directional caveat for B (branelink.py:94-95 'a DIRECTIONAL multi-messenger GW/EM arrival-time survey, which has N = 1 event'; ledger.py W7 row 'sky-fraction coincidence of prior 2.6e-7') but branelink.py:61/:132 and ledger.py:1787 state the beta bound itself without the one-direction qualifier. Not checked here whether GKLM's beta-only (B = 0) configuration is isotropic on the brane; recorded as a named hypothesis, not a fault.",
  "RE-FRAMED (tree prose, manyc.py:28-30, :157-160, :232-233, index3.py:1398) -- '|c_gw - c_gamma| / c ~ 4.226e-16 AGREEING TO ONE PART IN 2.4e15' is the tree's own ratio 1.74 s / (40 Mpc / c) (reproduced: 4.2263e-16). The source does not state it and it is not a measurement of |c_gw - c_gamma|: the lag is attributed to propagation only under H2, and the published SLOW side is 3e-15, 7x looser than 'one part in 2.4e15'. A discrepancy in the tree's framing, not in the source.",
  "WRONG EDGE (tree prose/arithmetic, manyc.py:33-34, :167-172, :235, :284, index3.py:1398) -- 'a field running 3e-15 FAST saves 4.02e-07 s to Proxima ... 0.24 SECONDS ON A CROSSING OF ANDROMEDA': 3e-15 is the magnitude of the SLOW-side bound (v_GW < v_EM); the published fast edge is +7e-16, 4.29x smaller (Proxima 9.38e-8 s, Andromeda 0.0552 s). The error is in the direction of OVERSTATING the saving, so the tree's conclusion 'it buys nothing' is strengthened, not weakened. branelink.py uses the correct fast edge (+7e-16)."
 ],
 "data_at_publication": [
  {"quantity": "GW-GRB arrival lag Delta t", "value_then": "+1.74 +/- 0.05 s (source abstract, sec 4)", "value_now": "unchanged in the texts read here; no later re-measurement was readable in this stage (alphaXiv quota exhausted, arXiv/ADS blocked)", "source_now": "1710.05834v2 abstract (READ); no later measurement READ", "moves_conclusion": "no -- not moved"},
  {"quantity": "distance D used for the bound", "value_then": "26 Mpc = lower end of the GW 90% credible interval on D_L (sec 4.1)", "value_now": "EM distance to NGC 4993 by surface-brightness fluctuations 40.7 +/- 1.4 (stat) +/- 1.9 (sys) Mpc (Cantiello et al. 2018, ApJL 854 L31) -- value taken from a web-search summary; the paper itself is NAMED-NOT-READ (arXiv:1801.06080 and ADS both blocked in this stage)", "source_now": "Cantiello et al. 2018 (NAMED-NOT-READ; search-engine abstract summary only)", "moves_conclusion": "no, only tightens: the bound is monotone in 1/D (computed); at 40.7 Mpc the fast edge is 4.27e-16 (38.3 Mpc: 4.54e-16), beta <= 2.92e-8 and the B = 0 saving 57.26 ns instead of 93.81 ns. 7e-16 remains a valid, conservative upper bound."},
  {"quantity": "distance measure (luminosity vs comoving)", "value_then": "luminosity distance D_L used as travel distance", "value_now": "for a constant fractional offset the delay accrues over comoving distance D_C = D_L/(1+z); z(26 Mpc, H0 = 67.4) = 0.00582 (computed)", "source_now": "computed here (rederive script, section B)", "moves_conclusion": "no: the unrounded upper bound moves 6.689e-16 -> 6.728e-16, still below the published 7e-16 (the 1-s.f. rounding absorbs it)"},
  {"quantity": "emission-time window (the hypothesis, not a datum)", "value_then": "simultaneous (upper) / GRB <= 10 s after GW (lower); exotic window (-100 s, 1000 s) named by the source", "value_now": "no model-independent emission delay available; the source says only future joint detections can separate emission from propagation delay (N = 1 event still, per branelink.py:95)", "source_now": "1710.05834v2 sec 4.1 (READ)", "moves_conclusion": "yes IF the hypothesis fails: the fast edge becomes +3.80e-14 under the -100 s exotic case (computed), a factor 57"},
  {"quantity": "unit constants", "value_then": "Mpc, c", "value_now": "c = 299792458 m/s exact; Mpc = 3.0856775814913673e22 m (IAU 2015); the tree's manyc.MPC = 3.0857e22 differs by 7e-6 relative", "source_now": "SI / IAU definitions", "moves_conclusion": "no"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "rederive/1710.05834.py",
  "outcome": "ALL PASS. (A) From the source's inputs (D = 26 Mpc, Delta t = 1.74 + 0.05 s, 10 s emission lag): upper = +6.6888e-16 (published +7e-16: rounded UP, conservative); lower = -3.1053e-15 with 1.69 s (-3.0866e-15 with 1.74 s), published -3e-15: the published slow-side magnitude is rounded DOWN by ~3.5% -- a rounding discrepancy, recorded, not a refutation, and irrelevant to the tree's use of the fast edge. (B) Comoving-distance correction (1+z) = 1.0058 leaves the fast edge 6.728e-16 <= 7e-16. (C) EM distance 40.7 Mpc tightens it to 4.273e-16. (D) The source's exotic window (-100 s, 1000 s) gives -3.73e-13 .. +3.80e-14, factors 121 and 57 -- the source's '2 orders of magnitude' reproduced. (E) The tree's arithmetic at 50 digits: beta = 3.741657386774e-8, 1/beta = 26726124.1912, T(4.2465 ly) = 134009348.4 s, Delta_tau = 93.80654388 ns -- branelink.py:61-66 reproduced to every printed digit; identity sqrt(1-1/(1+d)^2) = sqrt(d(2+d))/(1+d) proved symbolically. With the unrounded 6.689e-16 the saving is 89.64 ns. (F) manyc.py's 4.226e-16 reproduces as 1.74 s / (40 Mpc/c); its '3e-15 fast' is the slow-side magnitude (4.29x the fast edge).",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Greene, Kabat, Levin, Menon, 'Superluminal Propagation on a Moving Braneworld', arXiv:2206.13590v2, p.12-13 eqs (38)-(39)", "effect": "extends", "what": "Quotes the bound as -3e-15 <= Delta c/c <= +7e-16 and maps it to brane speed via Delta c/c = gamma - 1, 'assuming that light travels on the brane with speed c', hedged 'if we entertain the possibility that these are bulk degrees of freedom'. Carries neither H2 nor H7. This is the link the tree uses (branelink.py:61).", "read_status": "READ (scratchpad cache src/2206.13590.cached.txt, fetched earlier in this workflow)"},
  {"ref": "Polychronakos, 'Superluminal anisotropic propagation and wavefront splitting on tilted and boosted braneworlds', arXiv:2210.11497v3, sec 5 end", "effect": "narrows", "what": "For tilted/boosted branes the bulk speed is anisotropic; the GW170817 bound 'puts strict bounds to the tilt and boost of any braneworld scenario, unless we happen to live in a tiltlike braneworld and the relative position of the binary star happened to be quite close to the direction phi_o' -- the single-line-of-sight hypothesis H7 named in the literature.", "read_status": "READ (scratchpad cache src/2210.11497.cached.txt)"},
  {"ref": "Cantiello et al. 2018, 'A Precise Distance to the Host Galaxy of the Binary Neutron Star Merger GW170817 Using Surface Brightness Fluctuations', ApJL 854 L31 (arXiv:1801.06080)", "effect": "narrows", "what": "d = 40.7 +/- 1.4 +/- 1.9 Mpc (per search summary): a larger D than the 26 Mpc used, so it tightens the fast edge to ~4.3e-16 under the same H2; it does not loosen anything.", "read_status": "NAMED-NOT-READ (arXiv and ADS blocked; value from a web-search result summary only)"},
  {"ref": "LVC, 'Properties of the Binary Neutron Star Merger GW170817', PRX 9 011001 (2019), arXiv:1805.11579", "effect": "confirms", "what": "Refined GW-only parameter estimation; its distance interval was not readable here.", "read_status": "NAMED-NOT-READ (arXiv blocked)"},
  {"ref": "discover_papers for later work (the stage's one literature search)", "effect": "contested", "what": "Not run to completion: 'alphaXiv assistant quota exceeded'. No later paper that contradicts eq. (1) was found in this stage, which is absence of a search result, NOT evidence of absence.", "read_status": "NOT-RUN (quota)"}
 ],
 "lacked_data": "What the authors lacked in Oct 2017: (a) a precise EM distance to NGC 4993 -- they used the GW-only 90% lower limit 26 Mpc; later SBF work (NAMED-NOT-READ, ~40.7 Mpc) supplies it, and having it TIGHTENS the fast edge from 6.69e-16 to 4.27e-16 (computed), so M's hypothesis runs AGAINST M's favour here: the missing datum would have made the published bound stricter, not wrong. (b) Any model-independent knowledge of the intrinsic GW-to-gamma emission delay -- they lacked it and said so ('inherently model dependent'), bracketed it by an assumption (simultaneous emission for the fast edge) and named the exotic window (-100 s, 1000 s) that widens the range ~2 orders (computed factor 57 on the fast side). That datum is still lacking (still N = 1 joint event with a GRB at known distance, per the tree's own branelink.py:95), so this is not a case of physicists lacking data that has since arrived; it is a stated hypothesis which the tree drops. (c) Nothing about braneworlds: the bulk/brane mapping and its directional dependence are later (GKLM 2022, Polychronakos 2022-23) and are the tree's added hypotheses, not the authors'. Evidence either way: no moved datum weakens eq. (1); the only route by which the tree's 7e-16 could be too tight is the emission-ordering hypothesis (or a line-of-sight coincidence for an anisotropic bulk speed), and neither is a datum that has moved.",
 "grade": "NARROWED",
 "grade_evidence": "The measurement itself STANDS as published: eq. (1) re-derived from the source's own inputs (fast edge +6.689e-16, rounded up to +7e-16; comoving correction 6.728e-16; every later distance only tightens it), and the tree's arithmetic on it (beta = 3.74165738677e-8, Delta_tau = 93.80654 ns) reproduces to every digit. The grade is NARROWED, not STANDS, because the tree uses +7e-16 as an unconditional bound (branelink.py:61, :132; ledger.py:1787-1790; manyc.py:32, :68-69) while the source derives it ONLY under the hypothesis that the GW peak and the first photons were emitted simultaneously, and itself names pre-merger photon emission as possible, with an exotic window that loosens the fast edge to +3.80e-14 (beta <= 2.76e-7, B = 0 saving 5.10 us). The tree names the bulk-graviton condition correctly but not the emission-ordering one, and carries the single-line-of-sight caveat for B but not for the beta bound itself (Polychronakos 2210.11497 names it). The tree's qualitative conclusion (the B = 0 saving is negligible against a 4.2465-yr light time; O7 open on B) survives even the exotic window (5.1 us / 134009348 s = 3.8e-14). Two tree-prose discrepancies are recorded, not repaired: manyc.py:28-30 '4.226e-16 ... one part in 2.4e15' is the tree's own lag ratio at 40 Mpc, not a published figure; manyc.py:33-34/167-172 and index3.py:1398 use the slow-side magnitude 3e-15 as a FAST speed (4.29x the published fast edge), which overstates the saving and so only strengthens 'it buys nothing'. The source's slow-side rounding (-3.105e-15 printed as -3e-15) is a rounding discrepancy in the source, recorded, not a refutation, and not used by the tree's O7.",
 "what_would_change_the_grade": "To STANDS: the tree names the emission-ordering hypothesis beside the bulk-graviton one wherever +7e-16 is used (branelink.py:61/:132/:172, ledger.py:1787-1790, manyc.py:32/:68-69), and the one-line-of-sight qualifier on the beta bound. To DATA-DEPENDENT: a later multi-event GW/GRB analysis, or a GRB emission model accepted as measured, that places the intrinsic emission delay negative (photons first) for GW170817. To WRONG: only a computed contradiction of eq. (1) from the source's own inputs -- none exists (re-derived here). A re-read of 1710.05834 live at alphaXiv and a read of Cantiello 2018 at source (both blocked in this stage) would upgrade the distance row from NAMED-NOT-READ; neither can loosen the bound.",
 "reverify_command": "python3 " + D + "rederive/1710.05834.py   # expect ALL PASS; and: sed -n 128,195p " + D + "src/1710.05834.cached.txt   # sec 4.1 verbatim; grep -n -i 'simultan\\|emitted\\|intrinsic' /home/user/Claude-Method-Works/research/warp-drive/branelink.py /home/user/Claude-Method-Works/research/warp-drive/ledger.py   # expect no hit on the emission hypothesis",
 "report_path": D + "audits/1710.05834.json"
}
json.dump(r, open(D + "audits/1710.05834.json", "w"), indent=1, ensure_ascii=True)
print("ok")
