import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "magnetic-dipole-r-cubed",
 "name": "Magnetic dipole field falls as r^-3 (as applied by spec.py WITHDRAWN 2 to a magnetar at r = 1.5456e8 m)",
 "source": {
  "located": "Classical result (multipole expansion of a localised current distribution; textbook form B = (mu0/4pi)(3(m.rhat)rhat - m)/r^3, e.g. Jackson ch.5) -- no arXiv copy: the classic is NAMED-NOT-READ. Restated-by-use and its hypotheses named in two arXiv papers READ from alphaXiv page text cached earlier in this session (scratchpad/d67/src/casmag/all/): arXiv:1309.4167v3 (Olausen & Kaspi 2014, McGill Magnetar Catalog) sec 2.2 and Table 2 p.18; arXiv:2405.15484v2 (Huang et al. 2024) sec II.A eq (1) (vacuum spin-down with R^6 B^2 = mu^2, i.e. mu = B R^3, the r^-3 normalisation); arXiv:1308.4987v1 (Tiengo et al. 2013) pp.1-2, 13 on surface multipoles. Thompson, Lyutikov & Kulkarni 2002 (astro-ph/0110677, twisted self-similar magnetosphere B ~ r^-(2+p)) and Swift J1818.0-1607 (P = 1.36 s, 2020) are NAMED-NOT-READ.",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "The alphaXiv assistant quota was exhausted at this stage (answer_pdf_queries, get_paper_content and discover_papers all returned 'quota exceeded', three attempts) and arxiv.org is refused by the egress proxy (403 CONNECT, recorded in the agent-proxy status). The pages used are verbatim alphaXiv page text harvested from this session's transcripts into scratchpad/d67/src/casmag/all/ by casmag/allpages.py; nothing was paraphrased or reconstructed. The r^-3 law itself was not read in any source's words -- it was RE-DERIVED symbolically here (sympy), which for a closed-form theorem is stronger evidence than a restatement."
 },
 "published_statement": "Textbook (NAMED-NOT-READ): the field of a point magnetic dipole m in vacuum is B(r) = (mu0/4pi) [3 (m.rhat) rhat - m] / r^3 for r != 0, the leading term of the multipole expansion of a localised, current-free-outside source; an l-pole falls as r^-(l+2). As restated-by-use: 1309.4167 sec 2.2 'the surface dipolar magnetic field strength B, defined as B = 3.2 x 10^19 (P Pdot)^1/2 G ... Note that the expression for B assumes simple vacuum dipole radiation and ignores the potentially important torques due to magnetospheric variability and the internal superfluid'; 2405.15484 eq (1) Omega_dot_vac = -(2 R^6/3 I c^3) B^2 sin^2 chi Omega^3, 'B is the surface magnetic field at the dipole cap'; 1308.4987 p.1 'The measured spin-down rate ... translates (under the assumption of rotating magnetic dipole in vacuo) into a magnetic field B = 6 x 10^12 G at the magnetic equator'.",
 "published_hypotheses": [
  "H1 VACUUM / CURRENT-FREE outside the source: curl B = 0 in the region considered (the dipole is the exterior solution of Laplace's equation; 1309.4167 sec 2.2 and 1308.4987 p.1 say 'vacuum dipole' / 'dipole in vacuo' explicitly)",
  "H2 QUASI-STATIC NEAR ZONE: r << c/Omega = R_L (light-cylinder radius cP/2pi) for a rotating star; beyond R_L field lines open and the field is not dipolar (2405.15484 names R_L = c/Omega, eq (19); the far-zone 1/r behaviour is textbook, NAMED-NOT-READ)",
  "H3 LEADING MULTIPOLE: the dipole term dominates at the radius considered; higher l-poles fall as r^-(l+2) (derived here), so a surface value that includes multipoles is not the dipole amplitude (1308.4987: SGR 0418+5729 has a 6e12 G equatorial dipole but a local 2.5e14-5e15 G small-scale field)",
  "H4 FIXED ANGLE: B(r) = B(R)(R/r)^3 holds along a fixed direction; pole field = 2 x equatorial field at equal r (derived here); the catalogued spin-down B is the EQUATORIAL vacuum-dipole value for R = 10 km, I = 1e45 g cm^2 (1309.4167 sec 2.2; 1308.4987 p.1)",
  "H5 the magnetar's B is INFERRED from P and Pdot under H1 (spin-down), not measured at the surface (1309.4167 sec 2.2)"
 ],
 "hypothesis_drift": [
  "DROPPED H1 (vacuum): spec.py:51 and spec.py:225-226 state 'A dipole falls as r^-3' unconditionally for a magnetar; the canonical entry's hypothesis 'pure dipole outside the star' (spec.py:270) is not stated in the file. A magnetar magnetosphere is current-carrying (1309.4167 sec 2.2 cites Thompson et al. 2002; Beloborodov 2009 as the reason the vacuum formula may fail). Computed: a self-similar twisted field B ~ r^-(2+p) (TLK 2002, NAMED-NOT-READ) with p < ~0.5 gives a shortfall below twenty orders (p=0.5: 10^19.95; p=0: 10^15.84) -- the spec.py:275 selftest threshold '< 1e-20' is dipole-specific. 'Does not seat' survives every p.",
  "DROPPED H2 (near zone): spec.py:268-276 evaluates at r = 1.5456e8 m with no light-cylinder condition. P_crit = 2 pi r/c = 3.239 s; in the McGill catalog (1309.4167 Table 2) 3 of 21 timed magnetars -- 1E 1547.0-5408 (P = 2.072 s, R_L = 9.89e7 m), SGR 1627-41 (2.595 s), Swift J1834.9-0846 (2.482 s) -- have r OUTSIDE R_L, where the dipole law does not hold. Computed with a 1/r continuation beyond R_L: 1E 1547.0-5408 is short by 10^25.35 (vs 10^26.12 under pure r^-3 from its own B: the 1/r continuation RAISES the field at r, by 10^0.77 in u), i.e. the number moves by under one order. The tree's own magnetar (1e11 T, no P) is unspecified in P, so H2 is unverifiable for it as stated.",
  "WEAKENED H4/H5 (which field): spec.py:52 calls 1e11 T 'a magnetar's ... surface field'; it is the order of the equatorial spin-down vacuum-dipole estimate (catalog maximum SGR 1806-20: 2.0e15 G = 2.0e11 T, 1309.4167 Table 2). Pole = 2x. spec.py:270 is internally consistent (B_surface and B(r) at the same angle), so this is an unnamed hypothesis, not an error. Computed: pole x catalog-max x R = 1.2e4 m moves the shortfall 10^25.13 -> 10^24.06.",
  "UNSTATED H3 (multipoles): spec.py does not say whether 1e11 T is the dipole amplitude or a total surface field. If it includes higher multipoles, the far field is SMALLER than B_s(R/r)^3 would give (l-poles fall faster) -- the direction that favours the tree's conclusion; if the surface field is a weak dipole under strong multipoles (1308.4987, SGR 0418+5729), the 'surface field' overstates the dipole by up to ~10^3.",
  "MINOR (geometry): spec.py:270 takes the contiguous length's far end at r = 1.5456e8 m from the centre rather than R + l; the difference is 1e4/1.5e8 = 6e-5, immaterial."
 ],
 "data_at_publication": [
  {"quantity": "magnetar surface dipole field B_s", "value_then": "1e11 T (spec.py:52, 144, 270), no source, no angle", "value_now": "0.061-20 x 10^14 G = 6.1e8 to 2.0e11 T equatorial spin-down estimates, SGR 1806-20 maximum 2.0e11 T (1309.4167v3 Table 2, READ from cache); spec.py:145 lists 1e12 T as an interior estimate", "source_now": "arXiv:1309.4167v3 Table 2 p.18 (Olausen & Kaspi 2014)", "moves_conclusion": "No. Shortfall at r = 1.5456e8 m spans 10^24.53 (SGR 1806-20) to 10^29.56 (SGR 0418+5729) under r^-3; 'does not seat' and 'more than twenty orders' both hold across the catalog."},
  {"quantity": "neutron-star radius R", "value_then": "1.0e4 m (spec.py:270)", "value_now": "10 km is the catalog's convention (1309.4167 sec 2.2 via 3.2e19 coefficient, I = 1e45; 1308.4987 p.13 R_NS = 10 km); 12 km used here as a generous alternative (NOT read from a measurement paper)", "source_now": "1309.4167 sec 2.2; 1308.4987 p.13; 12 km is an illustrative value, NAMED not READ", "moves_conclusion": "No. u ~ R^6: 1.2^6 = 2.99, i.e. -0.48 in the order count."},
  {"quantity": "spin period P (sets R_L = cP/2pi against r = 1.5456e8 m)", "value_then": "not used (spec.py assumes the near zone)", "value_now": "2.07-11.78 s for the 21 timed catalog magnetars; three have P < P_crit = 3.239 s (1309.4167 Table 2); Swift J1818.0-1607 P = 1.36 s (2020) NAMED-NOT-READ", "source_now": "arXiv:1309.4167v3 Table 2", "moves_conclusion": "Moves the validity of the r^-3 law at r for 3 of 21 catalogued magnetars; does not move the conclusion (1E 1547.0-5408: 10^25.35 short with a 1/r continuation)."},
  {"quantity": "radial falloff exponent n in B ~ r^-n", "value_then": "3 (spec.py:227)", "value_now": "3 for a vacuum dipole in the near zone (derived here); 2 < n <= 3 for a twisted self-similar magnetosphere (TLK 2002, NAMED-NOT-READ); 1 for the toroidal field beyond R_L (textbook, NAMED-NOT-READ)", "source_now": "sympy derivation here; astro-ph/0110677 not read (alphaXiv quota)", "moves_conclusion": "Moves the ORDER COUNT (10^25.13 -> as low as 10^15.0 in the most generous bound computed: split monopole n = 2 from a 2e11 T, 12 km surface plus a toroidal field beyond R_L at P = 1.36 s); does NOT move 'does not seat'. It does move the selftest's 'more than twenty orders' (spec.py:275) for n < ~2.5."},
  {"quantity": "mu0, G, c (u = B^2/2mu0; requirement pi c^4/(4 G l^2))", "value_then": "mu0 = 1.25663706212e-6, G = 6.67430e-11, c = 299792458 (spec.py:135-137; seatindex.py:128-129)", "value_now": "CODATA 2018 values as used; no move that matters at 10^-10 relative", "source_now": "values as in spec.py; not re-read this stage", "moves_conclusion": "No."}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/magnetic-dipole-r-cubed.py",
  "outcome": "ALL OK (exit 0). (A) sympy: curl(k m x r/r^3) = k(3(m.r)r/r^5 - m/r^3); div B = 0 and curl B = 0 for r != 0; B(lam r) = lam^-3 B(r) EXACTLY, so B(r) = B(R)(R/r)^3 at fixed angle is exact for a pure vacuum dipole; |B_pole|/|B_eq| = 2; l-poles give B_r ~ r^-(l+2) for l = 1..4. (B) spec.py's numbers reproduced with its own constants: invariant 1.54562e19 T m; B(1.5456e8 m) = 2.7084e-2 T; u = 291.86 Pa; requirement 3.9790e27 Pa; short by 10^25.13 ('twenty-five orders' correct). (C) sensitivity: all 32 computed cases (11 sensitivity rows: catalog B range, pole, R = 12 km, twisted n = 2+p for p = 1, 0.5, 0.2, 0, split-monopole+toroidal bound at P = 2.07 s and 1.36 s; plus the 21 catalog light-cylinder cases) are short -- 'does not seat' survives all; minimum shortfall 10^15.01; five cases fall below the selftest's twenty-order threshold. (D) falloff-independent bound (sympy): for any B(r) <= B_s(R/r)^2 outside the star, B(l) l <= B_s R; with a toroidal zone beyond R_L, |B| l <= 2 B_s R; 2 B_s R = 2.4e16 T m even for the 1e12 T interior estimate at 12 km, against the invariant 1.5456e19 T m (10^2.8 short in B l, 10^5.6 in u).",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "arXiv:1309.4167v3 (Olausen & Kaspi 2014, McGill Magnetar Catalog)", "effect": "narrows", "what": "Supplies the data the tree lacked: the catalogued B is an equatorial vacuum-dipole spin-down estimate (H1, H4, H5 named explicitly), 6.1e8-2.0e11 T, and periods 2.07-11.78 s -- three below P_crit = 3.239 s, placing r = 1.5456e8 m outside their light cylinders.", "read_status": "READ (alphaXiv page text, session cache src/casmag/all/1309.4167v3.txt, sec 2.2 and Table 2)"},
  {"ref": "arXiv:1308.4987v1 (Tiengo et al. 2013, Nature 500, 312)", "effect": "narrows", "what": "Surface field is not the dipole amplitude: SGR 0418+5729 has a 6e12 G equatorial vacuum-dipole spin-down field but a local 2.5e14-5e15 G small-scale (multipolar) field in a proton-cyclotron loop model. Bears on H3; in the direction that makes the far field smaller than a total-surface-field scaling.", "read_status": "READ (session cache src/casmag/all/1308.4987v1.txt, pp.1-2, 13)"},
  {"ref": "arXiv:2405.15484v2 (Huang, Lu, Rice, Liang 2024)", "effect": "confirms", "what": "Uses the vacuum-dipole normalisation mu = B R^3 in eq (1) and contrasts vacuum with plasma-filled (current-carrying) magnetospheres whose spin-down differs -- confirming H1 is a model choice for magnetars, not a given.", "read_status": "READ (session cache src/casmag/all/2405.15484v2.txt, secs II.A-B)"},
  {"ref": "Thompson, Lyutikov & Kulkarni 2002, ApJ 574, 332 (astro-ph/0110677) -- twisted self-similar magnetospheres, B ~ r^-(2+p)", "effect": "narrows", "what": "Named as the current-carrying alternative to H1 (cited as such in 1309.4167 sec 2.2). The falloff law used in the sensitivity rows is the commonly quoted form and was NOT read at source here.", "read_status": "NAMED-NOT-READ (alphaXiv quota exhausted; arxiv.org refused by proxy)"},
  {"ref": "discover_papers for later work", "effect": "contested", "what": "The mandated discover_papers call could not be made: alphaXiv returned 'quota exceeded' on two attempts. No later-literature search beyond the session cache was possible at this stage.", "read_status": "NOT RUN (quota)"}
 ],
 "lacked_data": "What the tree (not the physicists) lacked, and what the classical result's authors did not need: the dipole law is a theorem of vacuum magnetostatics (re-derived exactly here), and no datum can move it inside its hypotheses. What spec.py lacked when applying it: (i) spin periods -- with the catalog (1309.4167 Table 2) three of 21 timed magnetars place r = 1.5456e8 m outside the light cylinder, where r^-3 does not apply; (ii) the magnetospheric current structure -- magnetars are modelled as twisted, current-carrying (H1 dropped), which softens the falloff toward r^-2; (iii) which field 1e11 T is -- an equatorial vacuum-dipole spin-down estimate, not a measured surface field. Having all three changes the ORDER COUNT (10^25.13 can fall to ~10^15 in the most generous bound computed, and the selftest's 'more than twenty orders' fails for n < ~2.5) but does NOT change the conclusion: every computed case is short, and the falloff-independent bound (D) shows B(l) l <= 2 B_s R, three-plus orders below the invariant, for ANY field no slower than r^-2 plus a toroidal zone. Evidence against M's hypothesis for this result: the external math is exact and the conclusion rests on it only weakly; evidence for a narrowing: the tree used the theorem outside two of its hypotheses without naming them.",
 "grade": "NARROWED",
 "grade_evidence": "The theorem STANDS as mathematics: sympy shows B = curl(mu0/4pi m x r/r^3) is divergence- and curl-free and exactly homogeneous of degree -3, and spec.py's numbers (2.7084e-2 T, 291.9 Pa, 3.979e27 Pa, 10^25.13) reproduce. It is NARROWED as the tree uses it: spec.py:51 and :225-226 apply 'a dipole falls as r^-3' to 'a magnetar' at 1.5456e8 m with the vacuum (H1) and near-zone (H2) hypotheses unstated; the catalog (1309.4167) shows 3 of 21 timed magnetars have that radius outside R_L, and a current-carrying twisted field with n < ~2.5 takes the shortfall below the selftest's twenty orders (spec.py:275), to 10^15.0 in the most generous bound. The downstream verdict (WITHDRAWN 2: the magnetar does not seat) is NOT moved: every one of 32 computed cases is short, and the falloff-independent sympy bound gives B l <= 2 B_s R < invariant by >= 10^2.8 (10^5.6 in u). Not WRONG (no counterexample to the use's conclusion); not DATA-DEPENDENT (no moved datum moves 'does not seat'); the quantitative 'twenty-five orders' holds on the vacuum-dipole near-zone class only.",
 "what_would_change_the_grade": "To STANDS: spec.py naming H1 (vacuum dipole) and H2 (r < cP/2pi) at :51/:226, or restating the conclusion as the falloff-independent bound B(l) l <= 2 B_s R (which needs neither). To WRONG: a field configuration outside the star with B(r) l >= 1.5456e19 T m at l >= R -- impossible for any B <= B_s(R/r)^2 with B_s R < 1.5e19 T m, i.e. it would need a surface field above ~1.5e15 T at 10 km (four orders above the catalog maximum). To OPEN-on-the-exponent: reading TLK 2002 (astro-ph/0110677) could show the twisted zone is confined well inside 1.5e8 m, which would restore n = 3 there and remove the twisted-field rows; it cannot move 'does not seat'.",
 "reverify_command": "python3 " + D + "/rederive/magnetic-dipole-r-cubed.py && cd /home/user/Claude-Method-Works/research/warp-drive && python3 -c \"import spec,sys; sys.exit(spec.selftest())\" | sed -n '/WITHDRAWN 2/,/WHAT ACTUALLY/p' && tr '\\n' ' ' < " + D + "/src/casmag/all/1309.4167v3.txt | grep -o 'surface dipolar magnetic field.\\{400\\}'",
 "report_path": D + "/audits/magnetic-dipole-r-cubed.json"
}
json.dump(rep, open(D + "/audits/magnetic-dipole-r-cubed.json", "w"), indent=1)
print("written")
