import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S = D + "/src/casmag/all/"
rep = {
 "key": "positive-mass-theorem-rigidity",
 "name": "Positive mass theorem, rigidity clause (M_ADM = 0 under DEC implies Minkowski)",
 "source": {
  "located": "Originals: R. Schoen & S.-T. Yau, Comm. Math. Phys. 65, 45 (1979) and 79, 231 (1981) (time-symmetric E >= 0 and the equality case E = 0 => Euclidean); Schoen-Yau CMP 79, 231 (1981) via Jang's equation and M. Eichmair (k != 0: E = 0 => embeds in Minkowski); E. Witten CMP 80, 381 (1981) (sketch of equality for vacuum); R. Beig & P. Chrusciel 1996 (E = |P| in 3D, spin). None has an arXiv copy read here. Read at source in their exact arXiv restatements: L.-H. Huang & D. A. Lee, 'Equality in the spacetime positive mass theorem', arXiv:1706.03732v3 (26 Nov 2019; CMP 2020) -- abstract, Theorem 1, Theorem 3, history p.2, Corollary 4 pp.2-3, DEC (2.1) p.4, Definition 2.5 (asymptotic flatness, 'connected smooth manifold without boundary') p.5, Remark 2.7 (multiple ends), Definition 2.8 (ADM E, P), Remark 2.11 p.7; M. Eichmair, L.-H. Huang, D. A. Lee, R. Schoen, arXiv:1110.2087v2 (23 Dec 2015; JEMS 2016) -- Theorem 1 p.1, history pp.2-3 (time-symmetric case: DEC becomes R_g >= 0; equality case 'derived from the nonnegativity of mass' but by a separate proof), Definition 3 ('complete C^2_loc Riemannian metric', mu, J), Remark on multiple ends; Y. Shi & L.-F. Tam, arXiv:math/0301047v1 (2003) p.1 restatement ('(M, g) is actually flat if the ADM mass of one of the ends is zero') and Section 3, Theorem 3.1 (Lipschitz metrics with EQUAL mean curvatures across the corner: m_E >= 0, and m = 0 on one end => one end and flat).",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "Full arXiv text banked in this docket at " + S + "{1706.03732v3,1110.2087v2,math_0301047v1,2605.27600v1,2509.05244v1,2507.16588v2}.txt (arXiv PDF extractions carrying the arXiv stamp lines), read directly with sed/grep in this stage. This stage's own alphaXiv calls (answer_pdf_queries on 1706.03732 and 1110.2087, get_paper_content, discover_papers) all returned 'alphaXiv assistant quota exceeded', and arxiv.org / export.arxiv.org / alphaxiv.org are refused by the egress proxy (403), so the banked extractions are the read path. Schoen-Yau 1979/1981, Witten 1981, Beig-Chrusciel 1996, Eichmair 2013 and Miao 2002 (corners with H_- >= H_+) are NAMED-NOT-READ; the first four are restated in the papers above."
 },
 "published_statement": "Huang-Lee arXiv:1706.03732v3 p.2: 'The special case k = 0 is often called the Riemannian positive mass theorem. In this case, |P| = 0 and the dominant energy condition is reduced to the condition that the scalar curvature of g is nonnegative everywhere. R. Schoen and S.-T. Yau proved the Riemannian positive mass theorem E >= 0 in dimension less than eight using minimal surfaces [24] ... Since the proof of the inequality E >= 0 is by contradiction, a separate argument is used to give a characterization of the equality case that if E = 0, then (M, g) is isometric to Euclidean space. In the case k != 0, Schoen and Yau also proved that E >= 0 in dimension three using the Jang equation ... M. Eichmair generalized the Jang equation argument ... These results also show that if E = 0, then (M, g, k) can be isometrically embedded in Minkowski spacetime with the second fundamental form k.' Theorem 1 (p.1): 'Let 3 <= n <= 7. Let (M, g, k) be an n-dimensional asymptotically flat initial data set that satisfies the dominant energy condition and has E = |P| ... Then E = |P| = 0.' Corollary 4 (pp.2-3): '... If n = 3, further assume that tr_g k = O(|x|^-s) for some s > 2. If E = |P|, then (M, g, k) can be isometrically embedded into Minkowski spacetime with the induced second fundamental form k.' Shi-Tam math/0301047 p.1: 'Suppose (M, g) is an asymptotically flat manifold such that g behaves like Euclidean at infinity near each end, and suppose its scalar curvature is nonnegative, then (M, g) is actually flat if the ADM mass of one of the ends is zero.'",
 "published_hypotheses": [
  "an initial data set: M a CONNECTED smooth manifold WITHOUT BOUNDARY (Huang-Lee Def.2.5) carrying a COMPLETE C^2_loc RIEMANNIAN metric g and C^1_loc symmetric k (EHLS Def.3) -- in particular g must be positive definite everywhere",
  "asymptotic flatness: (g - g_E, k) in C^{2,alpha}_{-q} x C^{1,alpha}_{-1-q} (and W^{2,p}_{-q} x W^{1,p}_{-1-q}), q in ((n-2)/2, n-2), mu, J in C^{0,alpha}_{-n-q0} (Huang-Lee Def.2.5); multiple AF ends allowed (HL Remark 2.7; EHLS Remark)",
  "dominant energy condition on the slice: mu >= |J|_g (HL (2.1); EHLS Def.3); for k = 0 (time-symmetric, which a static slice is) this is R_g >= 0",
  "E is the ADM flux of the chosen end (HL Def.2.8)",
  "conclusion (time-symmetric): (M, g) isometric to Euclidean space; with several ends, one end of zero mass forces one end and flatness (Shi-Tam restatement p.1, Thm 3.1 for their Lipschitz class); conclusion (k != 0): E = 0 => (M, g, k) embeds in Minkowski spacetime (Schoen-Yau 1981, Eichmair, per HL p.2); E = |P| => E = |P| = 0 (HL Thm 1, n <= 7; Beig-Chrusciel 1996 spin, 3D), embedding for n = 3 needs tr k = O(r^-s), s > 2 (HL Cor.4)",
  "the conclusion is about the INITIAL DATA SET (slice isometric to Euclidean / embeds in Minkowski); 'the spacetime is Minkowski' needs a further step (a development, or for a static spacetime the observation that a K = 0 static slice of Minkowski is flat)",
  "low regularity: Shi-Tam Theorem 3.1 covers Lipschitz metrics only with EQUAL mean curvatures from both sides of the corner (their hypothesis (ii)); the H_- >= H_+ corner version (Miao 2002) is named, not read",
  "no empirical data: a mathematical implication"
 ],
 "hypothesis_drift": [
  "DROPPED, and FAILS on part of the tree's window: 'g is a Riemannian metric' (EHLS Def.3). concentric.py's slice is the linearised spatial metric g = (1 - 2 Phi) delta (composite.py:35), with Phi(0) = m/a - m/R_s. It is positive definite only for m < m* = a R_s / (2(R_s - a)) = 0.0100010 at the seated a = 0.02, R_s = 200 (rederive R3). The tree applies rigidity to 'the two-region device' whose window it gives as 5e-3 to 4e-2 (concentric.py:77-78, 360; VERDICT 353-355). At m = 2e-2 (the 'best relative lead', concentric.py:82) psi(0) = -0.9998, and at m = 4e-2 psi(0) = -2.9996. There the literal slice is not an initial data set, and neither the theorem nor its contrapositive says anything about it. The tree anticipates the cause but not this consequence: concentric.py:139-141 ('LINEARISED WEAK FIELD ... Phi_max ~ m/a = 0.25 at the design point, which is NOT small. The window's edges are INDICATIVE'). Recorded as a discrepancy, not a refutation. R10 shows that any positive, monotone conformally flat completion u = f(Phi) (for example u = exp(-Phi/2), RECONSTRUCTED here, not the tree's) keeps E = 0 exactly and R(0) < 0 at every m in the window. So the tree's CONCLUSION (the DEC fails) survives the completion ambiguity. The tree's METRIC does not carry the premise above m*.",
  "DROPPED, satisfied by the device (checked, harmless): asymptotic flatness, completeness, no boundary, one end. concentric.py states none of them ('asymptotic flatness / complete data (not stated in this file)', canonical entry); pair.py:308 carries 'asymptotically flat', 'nonsingular', 'dominant energy condition'. For m < m*, psi lies between positive constants ([0.50005, 1.0] at m = 5e-3), so g is uniformly equivalent to delta on R^3: complete, one end, no boundary. g - delta = -2 Phi delta with Phi = -m a^2/(2 r^3) + ..., which is inside the fall-off window q in (1/2, 1). R = O(r^-5) is in L^1 (R2, R3). These hypotheses are load-bearing. R8 exhibits u = 1 - c/r^3 on r > r0 > c^(1/3): R = 48 c r^-5 u^-5 > 0, E = 0 exactly, not flat, INCOMPLETE (inner boundary). z3 (R7) confirms that 'not-DEC' is not entailed once completeness or AF is removed from the device facts. Volkov arXiv:2605.27600 p.1/p.3 is a zero-mass, locally flat, NON-Minkowski geometry with two ends and a distributional ring 'viewed as a distributional matter source carrying negative energy'. It is consistent with the theorem, because the energy condition fails at the ring, and it shows that regularity and topology hypotheses are where rigidity is escaped.",
  "WEAKENED REGULARITY, closed for this device by derivation: psi' jumps by -2m/R_s^2 at r = R_s (R3), so g is only Lipschitz there, below the C^2_loc of EHLS Def.3 / C^{2,alpha} of HL Def.2.5. The one low-regularity rigidity theorem read, Shi-Tam Thm 3.1, needs EQUAL mean curvatures across the corner, and the device has H_+ - H_- = -2m/(R_s^2 psi^(3/2)) < 0 (a positive-energy corner), so Shi-Tam does not cover it. Miao 2002 is NAMED-NOT-READ. For the device's own class (conformally flat, u > 0 Lipschitz on R^3, Lap u a finite signed measure, u -> 1) rigidity is elementary. R >= 0 <=> Lap u <= 0 (u > 0). E = -(1/2 pi) Int d(Lap u) = 0 then forces Lap u = 0, so u is harmonic (Weyl's lemma), bounded and -> 1, hence u == 1 (Liouville): flat. The finite step is discharged by z3 (R6, 50 cells, UNSAT, with a vacuity guard SAT). Weyl and Liouville are standard lemmas, named not machine-checked. R5 evaluates the identity on the device: core -m, shell +m, outside O(1e-10), sum 3e-18.",
  "STRENGTHENED CONCLUSION, harmless: concentric.py:128-130 'the spacetime IS MINKOWSKI'. The published time-symmetric conclusion is that the SLICE is isometric to Euclidean space (HL p.2). The tree's contrapositive needs only 'the slice is not flat', and R9 computes that directly: R(0) = -2.9994e4 at the design point. A static K = 0 slice of Minkowski orthogonal to a timelike Killing field is flat, so a curved one also shows 'not Minkowski'. The tree's own witness, 'it seats a conjugate point' (concentric.py:129), is a linearised-optics measurement on rays whose lead the file's header WITHDRAWS as interior-only (concentric.py:11-35). The rigidity step does not need it.",
  "SHARPENED, not a drift against the tree: for static (k = 0) data the hypothesis is R_g >= 0 (EHLS p.2, HL p.2), so the contrapositive gives mu = R_g/2 < 0 somewhere: the energy density seen by static observers is negative, a WEC failure, stronger than 'the DEC fails' (concentric.py:51-53, 131). And it needs no theorem at all. R4 computes R(0) = -12 m/a^3/(1 - 2m/a + 2m/R_s)^2 < 0 for every m < m*. So on the tree's own metric, rigidity is a second route to a directly computable fact. That strengthens the tree's apply.py narrowing (concentric.py:134-138; pair.py:136-143), 'rigidity is a second proof of it rather than its source'.",
  "LINEARISATION does not touch E: E is the ADM flux of the metric as written. For g = u^4 delta, E = -2 lim r^2 u' = lim r^2 Phi' = 0 exactly (sympy, R2), not only at linear order, and E = 0 for every completion u = f(Phi) (R10).",
  "The general-data (k != 0) route is not used: the device is static. If a non-static version were ever built, the equality case would have to be taken from Schoen-Yau/Eichmair (E = 0 => embeds in Minkowski) or HL Cor.4, which for n = 3 adds tr_g k = O(|x|^-s), s > 2 -- a hypothesis the tree nowhere names."
 ],
 "data_at_publication": [
  {"quantity": "empirical inputs to the rigidity clause", "value_then": "none -- a mathematical implication (Schoen-Yau 1979/1981)", "value_now": "none", "source_now": "Huang-Lee 1706.03732v3 p.2; EHLS 1110.2087v2 pp.2-3", "moves_conclusion": "no"},
  {"quantity": "device parameters the application depends on (concentric.py:155-157)", "value_then": "a = 0.02, R_s = 200, window m = 5e-3 .. 4e-2, design m = 5e-3", "value_now": "same (no external datum); Riemannian threshold m* = a R_s/(2(R_s - a)) = 0.0100010", "source_now": "rederive R3", "moves_conclusion": "yes for the application above m*: the literal slice is not Riemannian at m = 2e-2 and 4e-2; no at m < m*"},
  {"quantity": "ADM energy of the device slice", "value_then": "M_ADM = 0 EXACTLY (concentric.py:48, 77)", "value_now": "E = lim r^2 Phi' = 0 exactly (sympy)", "source_now": "rederive R2", "moves_conclusion": "no -- agrees"},
  {"quantity": "scalar curvature at the core, design point m = 5e-3", "value_then": "not computed in concentric.py (non-flatness argued from the conjugate point)", "value_now": "R(0) = -2.9994e4 = -12m/a^3/(1-2m/a+2m/R_s)^2", "source_now": "rederive R4, agrees with sibling audit positive-mass-theorem.json C3", "moves_conclusion": "no -- confirms non-flat and mu < 0 directly"},
  {"quantity": "psi(0) = 1 - 2Phi(0) at m = 2e-2 and 4e-2", "value_then": "not computed; concentric.py:139-141 calls the window edges INDICATIVE", "value_now": "-0.9998 and -2.9996", "source_now": "rederive R3", "moves_conclusion": "yes -- takes those window points outside the theorem's hypotheses on the literal metric; the conclusion (DEC fails) is recovered under any positive monotone completion (R10), not under the tree's metric"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/positive-mass-theorem-rigidity.py",
  "outcome": "OVERALL OK, exit 0, 46 checks (sympy 1.14.0, z3 5.1.0, mpmath 1.3.0); output in rederive/positive-mass-theorem-rigidity.out. R1: R[psi delta] = -8 u^-5 (u'' + 2u'/r), from Christoffels. R2: the device slice has E = 0 exactly; controls give E = -m for the bare Plummer core and E = M for isotropic Schwarzschild. R3: the literal slice is Riemannian iff m < m* = 0.0100010, so it is Riemannian at 5e-3, 8e-3, 9.9e-3 and 1e-2 and NOT at 2e-2 or 4e-2. psi' jumps by -2m/R_s^2 and H_- > H_+ (positive-energy corner). R4: R(0) = -12m/a^3/(1-2m/a+2m/R_s)^2 < 0 for every Riemannian m (-2.9994e4 at design). R5: E = -(1/2pi) Int d(Lap u) splits as core -m, shell +m, sum 3e-18, and quadrature agrees with the flux. R6: the elementary rigidity for conformally flat data; its finite step is z3-UNSAT, the vacuity guard SAT. R7: z3 finds 'THM & device |= not-DEC' valid and not entailed once AF, completeness or regularity is dropped. R8: an incomplete E = 0, R > 0, non-flat counterexample (u = 1 - c/r^3), so completeness is load-bearing. R9: the curved K = 0 slice shows 'not Minkowski'. R10: E = 0 and R(0) < 0 at every m in the window for u = exp(-Phi/2) and u = 1 - Phi/2 (RECONSTRUCTED completions).",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Huang & Lee, arXiv:1706.03732 (CMP 2020)", "effect": "extends", "what": "general-data rigidity: DEC and E = |P| => E = |P| = 0 for 3 <= n <= 7 (any n where the inequality holds); embedding in Minkowski for n = 3 needs tr_g k = O(|x|^-s), s > 2 (Cor.4); corrects an inaccuracy in EHLS Lemma 20 (Remark 2.11: the W^{2,p} assumption 'does not seem sufficient', C^2_{-q} x C^1_{-1-q} needed). None of this touches the time-symmetric case the tree uses.", "read_status": "READ (banked arXiv full text, pp.1-7)"},
  {"ref": "Eichmair, Huang, Lee, Schoen, arXiv:1110.2087 (JEMS 2016)", "effect": "extends", "what": "E >= |P| without spin for n < 8. States that the equality case 'is derived from the nonnegativity of mass, but that its proof is unrelated' in the Riemannian case, and that for general data it 'will require a substantial new idea' (supplied by Huang-Lee)", "read_status": "READ (banked arXiv full text, pp.1-3 and Def.3)"},
  {"ref": "Shi & Tam, arXiv:math/0301047 (2003)", "effect": "narrows", "what": "PMT and rigidity for Lipschitz metrics across a hypersurface, but only with EQUAL mean curvatures from both sides (hypothesis (ii)). The device's shell has H_- > H_+, so this result does not cover it. The rigidity for the device is recovered here by the elementary conformally flat argument instead (R6).", "read_status": "READ (banked arXiv full text, p.1, pp.18-19 Thm 3.1)"},
  {"ref": "Volkov, arXiv:2605.27600 (May 2026)", "effect": "confirms", "what": "the ring wormhole: the zero-mass limit of Kerr, 'locally flat', two asymptotic regions, a 'distributional curvature singularity on the ring', 'viewed as a distributional matter source carrying negative energy'. It is a zero-mass, non-Minkowski geometry that escapes rigidity only through a regularity/topology failure, with negative energy at the defect: the theorem's hypotheses are load-bearing, and the negative energy is where the tree says it must be", "read_status": "READ (banked arXiv full text, pp.1,3-4)"},
  {"ref": "Raulot, arXiv:2509.05244 (2025)", "effect": "extends", "what": "restates 'equality occurs if and only if the data arise from Minkowski spacetime' (Schoen-Yau, Witten) and proves charged positive energy theorems for n >= 4; leaves the charged equality case to future work (p.1, line 154 'The equality case, however, requires ...')", "read_status": "READ (banked arXiv full text, p.1)"},
  {"ref": "Penuela Diaz, arXiv:2507.16588 (2025)", "effect": "extends", "what": "quasi-local analogue: Hawking energy on area-constrained critical surfaces is nonnegative and rigid ('if it vanishes, the region enclosed is flat') under the DEC", "read_status": "READ (banked arXiv full text, abstract only)"},
  {"ref": "discover_papers search for newer work on rigidity", "effect": "contested", "what": "NOT RUN: the alphaXiv discover_papers call returned 'quota exceeded' in this stage, so the later-literature list is limited to the banked texts above and is a floor, not a survey", "read_status": "NAMED-NOT-READ (tool unavailable)"}
 ],
 "lacked_data": "The rigidity clause takes no measured input. It is an implication from geometric hypotheses (a complete, boundaryless, C^2 Riemannian slice that is AF, with R_g >= 0 for k = 0) to 'E = 0 => flat'. What came later is mathematics, not data: the general-data equality case (Beig-Chrusciel 1996; Huang-Lee 2020, with an extra tr k decay hypothesis for n = 3), low-regularity versions (Shi-Tam 2003 with matched mean curvatures; Miao 2002 named not read), and a correction to the 2016 regularity class (HL Remark 2.11). None of it moves the static, conformally flat, 3+1 case the tree uses, and the recomputation here agrees with the source (R1-R9). The one thing the 1979-81 authors assumed rather than measured is the energy condition. It is known to fail for quantum fields, but that failure takes a configuration outside the theorem; it does not refute it. So M's hypothesis gets no support for THIS result. The theorem is not inaccurate or incomplete in any way that touches its use here, and the evidence runs the other way: an independent elementary proof for the device's class (R6) reproduces the conclusion without the Schoen-Yau machinery. What IS incomplete is on the tree's side. The data the TREE lacked is its own metric's range of validity. At a = 0.02 the linearised slice (1 - 2 Phi) delta stops being Riemannian at m* = 0.0100010, inside the window the tree applies rigidity to. That is a discrepancy in the application, recorded and not repaired. It does not change the tree's conclusion, which survives under any positive monotone completion (R10).",
 "grade": "NARROWED",
 "grade_evidence": "The external result STANDS as published. The time-symmetric equality case (E = 0 and R_g >= 0 on a complete AF slice => Euclidean) is read in Huang-Lee 1706.03732v3 p.2, EHLS 1110.2087v2 pp.2-3 and Shi-Tam math/0301047 p.1. An independent elementary proof for conformally flat data on R^3 reproduces it (R6, z3-discharged finite step), no datum enters, and nothing read contradicts it. The contrapositive the tree draws (concentric.py:51-53, 128-133, 274-275, 353-355; pair.py:124-129, 321-326) is valid when the device satisfies the hypotheses (z3 R7). At the design point m = 5e-3 it does: E = 0 exactly (R2), complete, one end and AF (R3), not flat (R(0) = -2.9994e4, R4/R9). The one regularity gap, a Lipschitz shell with H_- > H_+ that Shi-Tam does not cover, is closed by R5/R6. The grade is NARROWED for two reasons. (1) The tree drops the hypothesis 'g is a Riemannian (positive-definite, complete) metric'. It applies the clause to 'the two-region device' across the window 5e-3 to 4e-2 (concentric.py:77-78, 360), but its literal slice (1 - 2 Phi) delta (composite.py:35) is Riemannian only for m < m* = a R_s/(2(R_s - a)) = 0.0100010. At m = 2e-2 (the 'best relative lead') psi(0) = -0.9998, and at 4e-2 it is -2.9996. There the clause's premise fails and the rigidity derivation certifies nothing about the tree's metric. (2) Completeness, no boundary and AF are unstated in concentric.py, and they are load-bearing (R8 incomplete counterexample; z3 R7; Volkov 2605.27600). They are satisfied by the device for m < m*, so this is a scope statement, not a fault. Not WRONG: no counterexample to the theorem and no contradiction of the tree's conclusion. Under any positive monotone completion u = f(Phi) the DEC failure holds at every m in the window (R10), and the tree itself flags the window edges as INDICATIVE (concentric.py:139-141). Not DATA-DEPENDENT: no external datum enters. Not STANDS: the tree's use covers a larger class (the full window, on its own metric) than the theorem's hypotheses admit.",
 "what_would_change_the_grade": "To STANDS: concentric.py restricts the rigidity sentence to m < m* = a R_s/(2(R_s - a)) on its linearised slice, or states it for a positive completion (for example u = exp(-Phi/2)) and names completeness, one end and AF as the hypotheses the device meets. Or a strong-field solution of the two-region device is supplied whose slice is Riemannian across the window. To WRONG: only a complete, boundaryless, asymptotically flat C^2 (or matched-corner Lipschitz) Riemannian 3-manifold with R_g >= 0, E = 0 and not flat, which would contradict Schoen-Yau 1979. Nothing read suggests one exists, and R6 excludes it in the conformally flat class. To OPEN: if a non-static version of the device is ever the one rigidity is applied to, the equality case must come from Schoen-Yau/Eichmair or Huang-Lee Cor.4 (tr_g k = O(r^-s), s > 2 for n = 3), and that has to be re-posed, not assumed.",
 "reverify_command": "cd " + D + "/rederive && python3 positive-mass-theorem-rigidity.py",
 "report_path": D + "/audits/positive-mass-theorem-rigidity.json"
}
json.dump(rep, open(rep["report_path"], "w"), indent=1)
print("written", rep["report_path"])
