import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/"
rep = {
"key": "higgs-yukawa-static-sourcing",
"name": "Static linear Higgs response to a fermion scalar density: (nabla^2 - m_h^2) dphi = (m_psi/v) n, Yukawa falloff, ultralocal algebraic limit",
"source": {
 "located": "No single primary: this is the tree-level SM field equation for the radial Higgs mode with a Yukawa source. READ restatements: (1) P. Brax, C. Burrage, 'Screening the Higgs portal', arXiv:2101.10693v2 (2021), pp.5-7 eqs.(4),(6),(9)-(11) and footnote 2, pp.13-15 eqs.(54)-(58) (linear static spherical profiles, decaying exponentials outside a constant-density sphere); (2) Y. Shi, arXiv:1908.02159v2 p.1 ('In the perturbative regime, the minima are shifted to <phi> ~ +-v - f<psibar psi>/u^2, which is significant only when the mass density rho = f<phi><psibar psi> ~ v^2 u^2 ... ~10^29 kg/m^3'); (3) Y. Shi, arXiv:2107.04206v1 abstract and p.15 (static configuration not unique; 1010/1210 phase boundary M ~ 2.7e14 a_m^2 kg; 'all stable nuclei are well within the 1010 phase'); (4) the nucleon coupling f_N m_N/v and the SVZ heavy-quark relation, J.M. Cline, K. Kainulainen, P. Scott, C. Weniger, arXiv:1306.4710v5 sec.5.1 eqs.(10)-(13), p.8 (f_N = 0.30 +- 0.01 Gaussian, 0.30 +- 0.03 top-hat). SVZ 1978 (PLB 78, 443) itself: NAMED-NOT-READ (restated by Cline eq.(11)-(13)).",
 "read_status": "READ",
 "via": "Live alphaXiv calls in THIS stage (answer_pdf_queries x2, get_paper_content x1, discover_papers x1) all returned 'alphaXiv assistant quota exceeded'; arxiv.org is refused by the egress proxy (CONNECT 403, logged). The four texts above were READ from alphaXiv page captures made earlier in this docket and held on disk at d67/src/casmag/all/{2101.10693v2,1908.02159v2,2107.04206v1,1306.4710v5}.txt; the passages quoted here were read in this stage from those captures. SVZ 1978 is READ-VIA-RESTATEMENT only (Cline 1306.4710 eqs.(11)-(13); sibling audits svz-1978 and dlnlambdaqcd-dlnv-2-9 read Hill-Solon 1409.8290 for the beyond-LO series)."
},
"published_statement": "Brax-Burrage 2101.10693 eq.(4): L = -(1/2)(dphi)^2 - (1/2)(dh)^2 - V(phi) + mu^2(phi) h^2/2 - lambda h^4/4 - i psibar dslash psi - lambda_psi h psibar psi; 'we replace psibar psi -> <psibar psi> = n_psi where n_psi is the number density of the medium. After identifying the mass of the fermions as m_psi = lambda_psi v, the equations of motion ... become ... box h + mu^2(phi) h - lambda h^3 - rho/v = 0 (10)', with mu^2(phi_0) = lambda v^2 (eq.7). Linearised static (p.14-15, eqs.(56),(58)): outside a constant-density sphere the rotated perturbations are 'decreasing exponential functions' B/(sqrt(y) r) e^{-sqrt(y)(r-R_0)}. Footnote 2 (p.6): 'the Higgs field should couple to alpha rho in (10). We ignore this alpha coefficient.' Shi 1908.02159 p.1: '<phi> ~ +-v - f<psibar psi>/u^2' in the perturbative regime. Cline et al. 1306.4710 eq.(11): 'sum_{q=c,b,t} f_q = (2/9)(1 - sum_{q=u,d,s} f_q)' by the trace-anomaly argument of SVZ [90]; Higgs-nucleon coupling f_N m_N/v_0, f_N = 0.30 +- 0.01.",
"published_hypotheses": [
 "Tree-level classical field equation of a real scalar with quartic (Mexican-hat) self-coupling; one Dirac fermion as a stand-in for the SM (Brax-Burrage p.5: 'a simplified version of the Standard Model ... the Higgs field is real').",
 "psibar psi replaced by its medium expectation value, identified with the number density n (nonrelativistic matter; Brax-Burrage p.5).",
 "Linear perturbation theory about the vacuum: source density small ('the density of the source is not too high', Brax-Burrage p.14; Shi 1908.02159: significant only when rho ~ v^2 u^2).",
 "Static configuration, constant-density source, decay at infinity, continuity at the surface (Brax-Burrage eqs.(54)-(58)).",
 "Perturbative branch: Shi 2107.04206 shows the static solution is NOT unique beyond a size-dependent critical source (1210 phase), so the linear solution is the unique finite-energy one only below that boundary.",
 "For nucleons the coupling is alpha*rho (Brax-Burrage fn.2), i.e. f_N m_N/v; f_N from the SVZ heavy-quark relation at leading order in alpha_s (Cline eq.(11)) plus the light-quark sigma terms (u, d AND s)."
],
"hypothesis_drift": [
 "AGREES (no drift) on the field equation: address.py:138 '(nabla^2 - m_h^2) dphi = (m_psi/v) n' is exactly Brax-Burrage eq.(10) linearised (sympy R1, residual 0) and Shi's shift -f n/u^2; address.py:140 eps = -rho_H c^2/(v^2 m_h^2) re-derives; only the curvature m_h^2 enters, so the unmeasured trilinear does not (R2).",
 "WEAKENED QUALIFIER 'EXACT' (address.py:140, :145, source_to_field_ratio docstring :674-678): the law is exact only as the linear, tree-level, uniform statement. The exact SM-shape uniform solution is rho = 8|V_min| eps (1+eps)(1+eps/2) (sympy R2b), so the exact source/field ratio is 4(1+eps)/(eps(2+eps)), not 8/(eps(2+eps)^2): relative difference (1+eps)(2+eps)/2 - 1 = 1.3e-15 at eps_det, a factor 3 at the eps_0 = 1 of address.py:166. The canonical entry does carry 'linear regime, static'; the drift is the word EXACT on a mixed-order combination (linear source law x all-orders SM energy). Discrepancy, not refutation; also the O(eps^3) energy depends on the unmeasured kappa (R2). Tree-level qualifier also recorded by sibling pdg-higgs-mass-vev.",
 "DROPPED at the formula (named elsewhere in the file): psibar psi -> n, the nonrelativistic identification. address.py:137-142 states the law for 'scalar density' but uses mass density rho; the (m c^2/E)^2 lemma at address.py:244-250 is the relativistic generalisation, so the tree knows it. Size at n0: free Fermi gas rho_s/rho_B = 0.9774 (R4), a 2.3% overstatement of the source for nuclear matter; in-medium (M* < m_N) corrections are model-dependent and not computed here.",
 "COUPLING HYPOTHESIS: address.py:143 'rho_H the HIGGS-DERIVED part', f = d ln m_p/d ln v, carried under H1 (2/9 + 7S/9, = SVZ LO as restated by Cline eq.(11)) and H2 (f = S, address.py:104). For a Higgs FIELD displacement the READ literature supports H1 (Cline eqs.(11)-(13), f_N = 0.30); H2 is a varying-constants hypothesis (Flambaum 0705.3704, READ by the tree) with no READ support as a Higgs-nucleon coupling -- except Brax-Burrage fn.2, which asserts the gluon part 'is not coupled to the Higgs field', contrary to SVZ (a discrepancy in that reading source, recorded, not a refutation of either). The tree refuses to choose (H1_VS_H2_IS_REFUSED, address.py:460); for this result H2 is the conservative side for EPS_NUCLEAR and the refutation-favouring side for COURIER_SOURCE_KG_M3 (larger source).",
 "DROPPED (sibling sigma-term-scan): EPS_NUCLEAR (address.py:943) uses S = 0.06 = sigma_piN/m_p (u+d only); SVZ's sum is over u, d, s. With S = 0.09: eps = -3.55e-13, 433x eps_det(H1).",
 "WEAKENED (siblings dlnlambdaqcd-dlnv-2-9, svz-1978): the 2/9 is LO in alpha_s and heavy-quark limit; beyond LO f = 0.2818 at S = 0.06 (+4.8%).",
 "UNNAMED HYPOTHESIS: perturbative-branch uniqueness. The tree's linear-regime criterion is eps << 1 (address.py:166, 297-303); Shi 2107.04206 p.15 places the 1010/1210 boundary at M ~ 2.7e14 a_m^2 kg (valence coupling), i.e. rho_c ~ 8.8e11 kg/m^3 for a 1 m sphere with the tree's H1 f, where eps ~ 1e-18 << 1 (R6). Irrelevant to EPS_NUCLEAR (margin 4.7e8) and to the atom-scale courier (margin 4.5e9); relevant to the 1 m-sphere sources of sections 6 and 9 (rests_on_it: section 9 domination theorem), as the sibling address-domination-theorem records. Contested for the SM (real-scalar, fixed-source toy).",
 "WEAKENED (sibling yukawa-green-function, re-shown R7): address.py:181 '[1 + O((lambda_h/L)^2)]' as a multiplicative pointwise form fails where J = 0 but dphi != 0 (offset source); the absolute sup-norm form |dphi + J/m^2| <= |J''|/m^4 holds.",
 "DISCREPANCY (sibling address-domination-theorem, re-shown R3): address.py:164, 697-722 start the exterior tail at eps_0 at the surface; for a uniform sphere with R >> lambda_h the surface value is half the interior value (exact ratio (MR cosh MR - sinh MR) e^{-MR}/(MR) -> 1/2), so a tail started from the interior eps overstates the standoff by lambda_h ln 2 = 1.09e-18 m. Conservative; no verdict moves.",
 "DISCREPANCY (stale rounding, sibling pdg-higgs-mass-vev): address.py:163 prose 'lambda_h = 1.5761e-18 m' is the withdrawn 125.20 GeV value; the code computes 1.57698e-18 m at the READ 125.13 GeV (R5).",
 "AGREES: electrons neglected (canonical hypothesis): computed share 8e-4 to 1e-3 of the H1 nucleon Higgs part, 3.6e-3 to 4.5e-3 of H2's (R5); coarse-grained density (address.py:297-303) is STATED by the tree and matches Brax-Burrage's 'constant density' source hypothesis."
],
"data_at_publication": [
 {"quantity": "m_h (sets lambda_h and eps ~ 1/m_h^2)", "value_then": "Brax-Burrage 2021 / Shi 2019: ~125 GeV ('u ~ 125 GeV', 1908.02159 p.1); tree: 125.13 GeV READ (RPP 2026 capture)", "value_now": "125.13 +- 0.11 GeV (RPP 2026, READ by sibling pdg-higgs-mass-vev); 125.20 +- 0.11 (PDG 2024)", "source_now": "sibling audit pdg-higgs-mass-vev (RPP 2026 listing capture)", "moves_conclusion": "No: 125.13 -> 125.20 moves eps by -1.12e-3 relative, lambda_h by 5.6e-4 (R5)."},
 {"quantity": "v = (sqrt2 G_F)^(-1/2)", "value_then": "246 GeV (Shi); 246.21964 GeV (tree)", "value_now": "246.2196 GeV (G_F PDG 2024 Table 1.1, READ by sibling)", "source_now": "sibling pdg-higgs-mass-vev / fermi-constant audits", "moves_conclusion": "No: relative spread ~3e-7."},
 {"quantity": "Higgs-nucleon coupling f (rho_H = f rho)", "value_then": "tree: 0.26889 (H1, S = 0.06, LO SVZ, u+d only) or 0.06 (H2); Brax-Burrage: coefficient 'alpha' ignored (set to 1)", "value_now": "f_N = 0.30 +- 0.01 (Cline 1306.4710v5 p.8, READ); 0.305(9) (Hoferichter et al. 1506.04142 eq.(24), via sibling); beyond-LO 0.2818 at S = 0.06 (sibling, Hill-Solon); up to 0.35 quoted in later Higgs-portal NS papers (WebSearch snippet, NOT read)", "source_now": "1306.4710v5 sec.5.1 (READ from capture); sibling audits sigma-term-scan, svz-1978", "moves_conclusion": "No verdict moves. eps_nuclear/eps_det(H1) = 398 (tree) -> 444 (f_N = 0.30) -> 452 (0.305) -> 518 (0.35); courier source with f_N = 0.30: 7.34e11 kg/m^3 = 3.25e7 x osmium (tree 8.19e11 H1). Under H2 with strange S = 0.111: 211x eps_det(H2) (tree 114). Magnitudes move by up to +30% (H1) / +85% (H2 with strange)."},
 {"quantity": "n0 (nuclear saturation density), RHO_NUCLEAR = 2.676e17 kg/m^3", "value_then": "0.16 fm^-3 (tree, DERIVED-FROM-ORDER, no source)", "value_now": "0.15 +- 0.01 / 0.148 (snippet values via sibling nuclear-saturation-density; NOT READ)", "source_now": "sibling audit nuclear-saturation-density", "moves_conclusion": "No: at n0 = 0.15, in-hypothesis ratios are 373 (H1) and 107 (H2); eps is linear in n0."},
 {"quantity": "rho_s/rho_B (scalar vs number density) in nuclear matter", "value_then": "1 (implicit; Brax-Burrage psibar psi -> n)", "value_now": "0.9774 for a free Fermi gas at n0 = 0.16 fm^-3 (computed R4); in-medium value model-dependent (not computed)", "source_now": "rederive R4", "moves_conclusion": "No: -2.3% on eps_nuclear."},
 {"quantity": "Higgs self-coupling shape (kappa_lambda)", "value_then": "SM quartic assumed", "value_now": "unmeasured beyond a broad interval (sibling sm-higgs-potential-tree: 2503.11548, (-1.2, 7.5))", "source_now": "sibling sm-higgs-potential-tree", "moves_conclusion": "Not the linear law: eps = -rho/(v^2 m_h^2) and the O(eps^2) field energy are kappa-independent (sympy R2). Only the rewrite '8|V_min|' as a vacuum-depth and the O(eps^3) energy depend on it."}
],
"rederivation": {
 "method": "sympy",
 "script_path": D + "rederive/higgs-yukawa-static-sourcing.py",
 "outcome": "EXIT 0, 0 FAIL. R1: Euler-Lagrange of L = (1/2)(dh)^2 - (lambda/4)(h^2-v^2)^2 - (m/v) h n linearised static gives (lap - m_h^2) d = (m/v) n (residual 0), m_h^2 = 2 lambda v^2, uniform eps = -rho/(v^2 m_h^2); Brax-Burrage eq.(10) and Shi's shift reduce to the same. R2: v^2 m_h^2 = 8|V_min| and V(v(1+e)) - V_min = |V_min| e^2(2+e)^2 exact for the SM quartic; linear response and O(eps^2) energy kappa-independent; O(eps^3) energy = kappa m_h^2 v^2/2 eps^3. R2b: exact uniform source 8|V_min| eps(1+eps)(1+eps/2); exact source/field ratio 4(1+eps)/(eps(2+eps)) vs tree 8/(eps(2+eps)^2): factor (1+eps)(2+eps)/2, 1+1.3e-15 at eps_det. R3: Yukawa exterior residual 0; uniform-sphere surface/interior -> 1/2. R4: rho_s/rho_B = 0.9774 at n0. R5: EPS_NUCLEAR -3.267241e-13 (H1), -7.290537e-14 (H2) reproduced independently to 1e-12; all moved-coupling/n0 cases keep nuclear eps above eps_det (min in-hypothesis 107 under H2 at n0 = 0.15, 373 under H1); electrons < 0.5%; courier with f_N = 0.30 is 3.25e7 x osmium. R6: Shi's nonperturbative boundary is 4.7e8 above nuclear density at nuclear size and 4.5e9 above the courier density at atomic size, but ~8.8e11 kg/m^3 for a 1 m sphere (H1 f). R7: multiplicative ultralocal form fails at zeros of an offset source; absolute form holds.",
 "agrees_with_source": "yes"
},
"later_literature": [
 {"ref": "Y. Shi, arXiv:2107.04206 (2021; v dated 2024)", "effect": "narrows", "what": "Static Higgs configuration sourced by matter is not unique: beyond M ~ 2.7e14 a_m^2 kg (valence coupling) a 1210 phase with light horizons exists. Narrows 'linear, static' to the perturbative branch below that boundary; nuclei and atom-scale sources are far inside it (computed R6), metre-scale dense sources are not. Contested as SM physics (real-scalar, fixed-source toy).", "read_status": "READ (abstract, p.15, from on-disk alphaXiv capture)"},
 {"ref": "P. Brax, C. Burrage, arXiv:2101.10693 (2021)", "effect": "confirms", "what": "Eq.(10) is the tree's field equation; linear static spherical solutions decay exponentially outside a constant-density source (eqs.(56)-(58)). Its footnote 2 claims the nucleon's gluon mass is not coupled to the Higgs -- contrary to SVZ; recorded as a discrepancy in the reading source.", "read_status": "READ (pp.5-7, 13-15, from on-disk alphaXiv capture)"},
 {"ref": "Y. Shi, arXiv:1908.02159 (2019)", "effect": "confirms", "what": "Perturbative shift <phi> = v - f<psibar psi>/u^2, significant only at rho ~ v^2 u^2 ~ 1e29 kg/m^3 (tree: 8|V_min|/c^2 = 2.2e29 kg/m^3).", "read_status": "READ (p.1, from on-disk alphaXiv capture)"},
 {"ref": "J.M. Cline et al., arXiv:1306.4710v5 (2013)", "effect": "confirms", "what": "Higgs-nucleon coupling f_N m_N/v with the SVZ heavy-quark sum (2/9)(1 - sum f_q) -- the tree's H1 structure -- and f_N = 0.30 +- 0.01 (0.30 +- 0.03 top-hat).", "read_status": "READ (sec.5.1, p.8, from on-disk alphaXiv capture)"},
 {"ref": "'Higgs shifts from electron-positron annihilations near neutron stars', arXiv:1503.01738", "effect": "extends", "what": "Located by WebSearch as later work on Higgs vev shifts near compact objects; content not read, effect not assessed beyond its title.", "read_status": "NAMED-NOT-READ (discover_papers quota exceeded; arxiv.org egress-blocked)"},
 {"ref": "Higgs-portal neutron-star papers (e.g. arXiv:2412.04585) using nucleon-Higgs form factor f ~ 0.3-0.35", "effect": "confirms", "what": "WebSearch snippets only: nucleon-Higgs form factor ~0.3 (and 0.35 in one calculation) with v = 246.22 GeV in a scalar-density field equation.", "read_status": "NAMED-NOT-READ (search snippet, not counted as a read)"}
],
"lacked_data": "The law is a tree-level consequence of the SM Lagrangian; its form needs no datum. Its numbers need m_h, v, the nucleon coupling f and the density. Brax-Burrage (2021) and Shi (2019) had m_h and v at essentially today's values (the 125.13 vs 125.20 move is 1.1e-3 on eps). What earlier authors lacked, and what is still soft: (a) the nucleon coupling -- Brax-Burrage set it to 1 (fn.2) and mis-describe the gluon part as uncoupled; SVZ's 2/9 is LO; the sigma terms remain in ~3-sigma lattice/phenomenology tension. Computed: every value from 0.06 (H2) to 0.35 keeps nuclear matter 83x to 518x above eps_det in every hypothesis pairing, so the conclusion does not move. (b) The Higgs self-coupling shape is still unmeasured (kappa_lambda broad): it does NOT enter the linear law or the O(eps^2) energy (sympy), only O(eps^3) terms and the 'vacuum depth' reading of 8|V_min|. (c) The genuinely new information since the classical Yukawa picture is theoretical, not data: Shi 2021 shows the static solution is non-unique above a size-dependent source, which narrows 'the' linear response to the perturbative branch -- a hypothesis the tree does not name, harmless at nuclear/atomic scale (margins 4.7e8 / 4.5e9), not harmless for metre-scale dense sources. Evidence either way: nothing measured since publication moves any conclusion the tree draws from this result; M's hypothesis is not supported for THIS result on the data side, and is supported only in the weak sense that a later theoretical result (non-uniqueness) narrows the class on which the classical linear picture is the whole story.",
"grade": "NARROWED",
"grade_evidence": "Re-derivation agrees exactly: the static linear equation, its sign, the uniform solution eps = -rho_H c^2/(v^2 m_h^2), the identity v^2 m_h^2 = 8|V_min|, the Yukawa exterior and the ultralocal leading term all re-derive in sympy (R1-R3, R7; 0 FAIL) and match the READ restatements (Brax-Burrage 2101.10693 eq.(10), Shi 1908.02159 p.1). The owner's EPS_NUCLEAR (-3.267e-13 H1, -7.29e-14 H2) is reproduced to 1e-12. No moved or contested datum moves a conclusion (computed: m_h move 1.1e-3; f_N 0.06-0.35 and n0 0.15-0.16 keep in-hypothesis ratios >= 107; courier source stays > 3e7 x osmium; electrons < 0.5%). So not WRONG (no counterexample; the tree's numbers are the correct linear tree-level values) and not DATA-DEPENDENT. Not STANDS because the statement as used holds on a smaller class than written: (i) 'EXACT' on a linear, tree-level, uniform law, and the source/field ratio 'EXACTLY 8/(eps(2+eps)^2)' mixes a linear source law with an all-orders energy (exact SM-shape ratio 4(1+eps)/(eps(2+eps)); 1.3e-15 at eps_det, factor 3 at eps_0 = 1); (ii) psibar psi -> n (nonrelativistic) not named at the formula (-2.3% at n0); (iii) perturbative-branch uniqueness unnamed (Shi 2107.04206), harmless for EPS_NUCLEAR and the atom-scale courier, not for 1 m dense sources; (iv) the nucleon coupling is LO SVZ with strange dropped at the adopted S, and H2 has no READ support as a Higgs-nucleon coupling; (v) the multiplicative ultralocal error form and the eps_0-at-surface tail are discrepancies already recorded by siblings. Consistent with sibling grades yukawa-green-function, address-domination-theorem, svz-1978, sigma-term-scan, pdg-higgs-mass-vev (all NARROWED). Nothing repaired.",
"what_would_change_the_grade": "To STANDS: the owner naming the class (linear, tree-level, nonrelativistic psibar psi ~ n, perturbative branch, LO SVZ coupling with u,d,s) and dropping 'EXACT' / 'EXACTLY' where the combination is mixed-order. To WRONG: a READ SM calculation showing the static linear Higgs response to nuclear matter differs in sign or by orders of magnitude from -f rho c^2/(v^2 m_h^2) (e.g. an in-medium Higgs-nucleus coupling suppressed by >~100, which would bring EPS_NUCLEAR below eps_det under H2), or a demonstration that the Shi 1210 branch is realised in the SM at nuclear or atomic scale. To DATA-DEPENDENT: a nucleon Higgs coupling below ~0.0005 (H2; 0.06/114) or ~0.0007 (H1; 0.2689/398) -- 100x below any value in the literature. To OPEN: if the on-disk alphaXiv captures are held not to count as a read at source, the reading half would be OPEN pending a live re-read of 2101.10693, 1908.02159, 2107.04206 and 1306.4710; the re-derivation half is independent of it.",
"reverify_command": "python3 " + D + "rederive/higgs-yukawa-static-sourcing.py  # expect 'FAILS: none', exit 0; source text: grep -n 'We ignore this' " + D + "src/casmag/all/2101.10693v2.txt; grep -n '= 0.30 ± 0.01' " + D + "src/casmag/all/1306.4710v5.txt",
"report_path": D + "audits/higgs-yukawa-static-sourcing.json"
}
json.dump(rep, open(D + "audits/higgs-yukawa-static-sourcing.json", "w"), indent=1)
print("ok")
