import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S = D + "/rederive/planck-cosmological-parameters-via-2604.01047.py"
r = {
 "key": "planck-cosmological-parameters-via-2604.01047",
 "name": "Measured cosmological constant Lambda = 7.15e-121 M_P^2 and Omega_Lambda = 0.685 (as printed by GMMPS 5.3)",
 "source": {
  "located": "Primary: Planck Collaboration, 'Planck 2018 results. VI. Cosmological parameters', arXiv:1807.06209v4 (A&A 641 (2020) A6), Sec. 3.2 eqs (14)-(15) p.17 and Table 2 p.16. Intermediate (the tree's actual source): Galanda, Meda, Murro, Pinamonti, Schmid, arXiv:2604.01047v1 Sec. 5.3 pp.62-63, citing Planck 2018 VI as ref [1].",
  "read_status": "READ",
  "via": "alphaXiv answer_pdf_queries on 1807.06209 (pp.1-2, 15-17, 71 returned) and on 2604.01047 (pp.1, 7, 60, 62-63, 66-71 returned). The tree's owner had read only GMMPS; this audit read the primary."
 },
 "published_statement": "Planck 2018 VI p.17 eq.(15): 'Omega_Lambda = 0.6847 +- 0.0073 (68 %, TT,TE,EE+lowE+lensing). In terms of a physical density, this corresponds to Omega_Lambda h^2 = 0.3107 +- 0.0082, or cosmological constant Lambda = (4.24 +- 0.11) x 10^-66 eV^2 = (2.846 +- 0.076) x 10^-122 m_Pl^2 in natural units (where m_Pl is the Planck mass).' eq.(14): H0 = (67.36 +- 0.54) km/s/Mpc. GMMPS 5.3 p.63: 'Comparing this theoretical result with the experimental values of Omega_Lambda and Lambda inferred from the Planck measurements of the Cosmic Microwave Background [1], i.e., Omega_Lambda ~ 0.685 and Lambda ~ 7.15 x 10^-121 M_P^2, we obtain an approximated value of the mass of the field, that is m ~ 7.8 x 10^-3 eV', with p.62 'In Planck units, kappa^-1 is the squared value of the reduced Planck mass M_P' and Lambda = 3 Omega_Lambda H^2 = 6 Omega_Lambda alpha~^S_1 (m/M_P)^4 M_P^2.",
 "published_hypotheses": [
  "Planck: base-LCDM -- spatially flat, 6 parameters, power-law adiabatic scalar spectrum, w = -1 (p.1 abstract, p.2)",
  "Planck: a single minimal-mass neutrino eigenstate, Omega_m includes one neutrino of 0.06 eV (p.2; Table 1 caption)",
  "Planck: Omega_Lambda follows from Omega_m only 'since we are considering a flat universe' (p.17)",
  "Planck: late-Universe parameters are 'inferred (model-dependent)' and 'highly model dependent' (abstract; p.16 below eq.13)",
  "Planck: dataset TT,TE,EE+lowE+lensing, Plik likelihood; 'A total systematic uncertainty of around 0.5 sigma may be more realistic' (Table 1 caption)",
  "Planck: m_Pl is the (unreduced) Planck mass in the 2.846e-122 figure (p.17)",
  "Planck abstract: base-LCDM H0 is 'in significant, 3.6 sigma, tension with local measurements of the Hubble constant'",
  "GMMPS: M_P is the REDUCED Planck mass (p.62), so the Planck figure is multiplied by 8 pi",
  "GMMPS: values rounded to 3 significant figures (0.6847 -> 0.685; 7.1528e-121 -> 7.15e-121)",
  "GMMPS (modelling, not Planck's): the semiclassical de Sitter rate H = sqrt(-gamma~) is identified with the present Hubble rate through Lambda = 3 Omega_Lambda H^2 (p.63); J(gamma) dropped and gamma~ ~ -b0/b1 (p.62)"
 ],
 "hypothesis_drift": [
  "DROPPED (non-load-bearing for the tree's use): the base-LCDM model dependence (flat, w=-1, minimal neutrino mass) and the dataset label TT,TE,EE+lowE+lensing are not recorded at linstab.py:318-319; the tree's comment says only 'READ, 5.3'. The owner's hypothesis string does name the real limitation ('primary cosmological source not read by the owner'), which this audit discharges.",
  "DROPPED (non-load-bearing): the Planck 68% uncertainties (Omega_Lambda +-0.0073; Lambda +-2.7%, i.e. [6.962e-121, 7.344e-121] M_P^2) are not carried at linstab.py:318-319; the tree uses point values only.",
  "KEPT, correctly: M_P reduced -- linstab.py:625-628 reduced_planck_ev() = sqrt(hbar c/8 pi G) c^2, matching GMMPS p.62; the 8 pi conversion from Planck's m_Pl^2 is exact (C1).",
  "INHERITED, not endorsed: GMMPS's identification H_deSitter = H0 via Lambda = 3 Omega_Lambda H^2 is the formula inverted at linstab.py:630-633 (gmmps_mass_ev). The tree uses it only to reproduce GMMPS's own printed arithmetic, not as a physical claim; its physics is not in this entry's scope.",
  "NOTE (not drift): in the inversion Omega_Lambda cancels exactly (C3): m^4 = H0^2 M_P^2/(2 alpha), with H0 = sqrt(Lambda/(3 Omega)) -- the tree's m depends on the printed pair only through the implied H0 = 67.342 km/s/Mpc."
 ],
 "data_at_publication": [
  {"quantity": "Lambda", "value_then": "7.15e-121 M_P^2 (GMMPS 5.3, reduced M_P) = Planck 2018 (2.846 +- 0.076)e-122 m_Pl^2 x 8 pi = 7.1528e-121", "value_now": "Planck 2018 VI remains the final Planck release (READ: 'final full-mission Planck measurements'). Later combinations (ACT DR6 arXiv:2503.14452, DESI DR2 arXiv:2503.14738) NOT READ here -- alphaXiv quota exceeded and arxiv.org egress-blocked; no current value is asserted.", "source_now": "arXiv:1807.06209v4 p.17 (READ); later papers NAMED-NOT-READ", "moves_conclusion": "No, computed: the tree's conclusions are functions of GMMPS's PRINTED values (a control on GMMPS's arithmetic). The (64 pi)^-1 vs 1/(64 pi^2) discrimination is the data-free ratio pi^(1/4) = 1.3313 in m. Selftest brackets still fire with eps scaled 0.8..1.25 (H0 53.9..84.2 km/s/Mpc)."},
  {"quantity": "Omega_Lambda", "value_then": "0.685 (GMMPS, rounded from Planck 0.6847 +- 0.0073)", "value_now": "Planck 2018 +BAO 0.6889 +- 0.0056 (READ, Table 2); later values NOT READ", "source_now": "arXiv:1807.06209v4 Table 2 p.16", "moves_conclusion": "No: Omega_Lambda cancels identically in the GMMPS inversion (sympy, C3)."},
  {"quantity": "H0 implied by the printed pair, sqrt(Lambda/(3 Omega_Lambda))", "value_then": "67.342 km/s/Mpc (computed) vs Planck 67.36 +- 0.54", "value_now": "Planck+BAO 67.66 +- 0.42 (READ) -> m = 7.903e-3 eV (+1.33% vs printed 7.8e-3); Planck abstract records a 3.6 sigma tension with local H0 (READ); local-ladder values (SH0ES arXiv:2112.04510) NOT READ here", "source_now": "arXiv:1807.06209v4 abstract, Table 2", "moves_conclusion": "Not the tree's conclusion. m scales as H0^(1/2): the tree's 2% control band would hold for H0 in [63.29, 68.56] km/s/Mpc if the inputs were ever swapped, and the fixed-7.8e-3 >20% typo test would stop discriminating only at H0 >= 74.76; the tree does not swap inputs, and the alpha-to-alpha ratio is data-free. GMMPS's physical m ~ 7.8e-3 eV claim WOULD move by (H0'/67.34)^(1/2) -- that is GMMPS's claim, not the tree's."},
  {"quantity": "reduced Planck mass M_P", "value_then": "not printed by GMMPS", "value_now": "2.435323e27 eV from CODATA 2018 hbar, c, G (G = 6.67430e-11 unchanged in CODATA 2022)", "source_now": "achievable.py constants; audits/codata-2018-constants.json in this pass", "moves_conclusion": "No."}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": S,
  "outcome": "ALL PASS. C1: 2.846e-122 x 8 pi = 7.1528e-121 M_P^2 (rounds to 7.15e-121). C2: Lambda = 3 Omega_L H0^2 from Planck's H0 = 67.36, Omega_L = 0.6847 and CODATA gives 4.2409e-66 eV^2 (Planck 4.24), 2.8451e-122 m_Pl^2 (Planck 2.846), 7.1506e-121 M_P^2 (GMMPS 7.15); Omega_L h^2 = 0.3107. C3 (sympy): Omega cancels, m^4 = H^2 M_P^2/(2 alpha), equal to GMMPS's -b0/b1 = -16 pi G alpha m^4 with kappa = 1/M_P^2. C4: printed pair -> m = 7.8848e-3 eV with 1/(64 pi^2) (+1.09% vs printed 7.8e-3; a rounding discrepancy, recorded, not an error -- 7.885 would round to 7.9), m = 5.9225e-3 eV with (64 pi)^-1 (-24.1%), ratio exactly pi^(1/4); printed pair implies H0 = 67.342. C5: s_root_bracket (imported read-only from linstab) fires at xi = 0, 1/3, |b2| <= 1e100 for eps x 0.8, 0.9, 1.1, 1.25. git status of research/ clean after the run (bytecode writing disabled).",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "arXiv:1807.06209v4 Table 2 (Planck 2018 TT,TE,EE+lowE+lensing+BAO)", "effect": "confirms", "what": "H0 = 67.66 +- 0.42, Omega_Lambda = 0.6889 +- 0.0056; moves the GMMPS-formula m by +0.24% relative to the printed-pair value. Within-paper, not later, but the nearest combined value READ.", "read_status": "READ"},
  {"ref": "arXiv:1807.06209v4 abstract (Planck's own statement)", "effect": "narrows", "what": "base-LCDM H0 'in significant, 3.6 sigma, tension with local measurements of the Hubble constant'; late-Universe parameters are 'model-dependent'. Narrows the value's standing as a model-independent measurement; does not touch the tree's use.", "read_status": "READ"},
  {"ref": "ACT DR6 cosmological parameters, arXiv:2503.14452", "effect": "extends", "what": "Named as a post-GMMPS-data CMB update; content NOT asserted here. Effect label is a placeholder category, not a finding.", "read_status": "NAMED-NOT-READ (alphaXiv quota exceeded; arxiv.org egress-blocked)"},
  {"ref": "DESI DR2 BAO cosmological constraints, arXiv:2503.14738", "effect": "contested", "what": "Named as the later work bearing on w = -1 (the base-LCDM hypothesis behind 'cosmological constant'); content NOT asserted here. Effect label is a placeholder category, not a finding.", "read_status": "NAMED-NOT-READ (alphaXiv quota exceeded; arxiv.org egress-blocked)"},
  {"ref": "Riess et al. (SH0ES), arXiv:2112.04510", "effect": "contested", "what": "Named as the local-ladder H0 behind the tension Planck itself records (READ via Planck abstract); its value NOT asserted here.", "read_status": "NAMED-NOT-READ (alphaXiv quota exceeded; arxiv.org egress-blocked)"}
 ],
 "lacked_data": "M's hypothesis tested for this result. Data Planck 2018 lacked: later CMB (ACT DR6, SPT-3G), BAO (DESI) and the local-H0 resolution -- NOT READ here, so no later value is asserted. Evidence that it does NOT change the tree's conclusion, computed: (i) the tree uses Lambda and Omega_Lambda only as GMMPS's printed inputs, to test GMMPS's own arithmetic; (ii) Omega_Lambda cancels exactly (sympy), so only the implied H0 enters, as m ~ H0^(1/2); (iii) the typographical verdict rests on the data-free ratio pi^(1/4) = 1.331 between the two alpha readings; (iv) the selftest brackets fire for eps scaled 0.8..1.25, i.e. any H0 in 53.9..84.2 km/s/Mpc, which contains every value on either side of the recorded 3.6 sigma tension. Evidence that data DOES matter elsewhere: GMMPS's physical claim m ~ 7.8e-3 eV (and its neutrino/axion remark) moves with H0 as (H0/67.34)^(1/2) and rests on w = -1 and base-LCDM -- a GMMPS claim, not the tree's; the tree records none of it as its own.",
 "grade": "STANDS",
 "grade_evidence": "For the tree's use (linstab.py:318-319 values 'as printed in GMMPS 5.3'; 630-633 inversion; 966-977 selftest control and brackets): (1) READ at GMMPS pp.62-63: 0.685 and 7.15e-121 M_P^2 printed exactly, M_P reduced, source Planck 2018 VI; (2) READ at the primary, Planck 2018 VI p.17 eq.(15): Omega_Lambda = 0.6847 +- 0.0073, Lambda = (2.846 +- 0.076)e-122 m_Pl^2 (unreduced); (3) re-derived: x 8 pi = 7.1528e-121 M_P^2 and Lambda = 3 Omega_L H0^2 = 7.1506e-121 from H0 = 67.36 -- GMMPS's transcription is correct to its 3 significant figures; (4) no datum move moves the tree's conclusion, computed (Omega cancels; alpha ratio data-free; brackets robust over a 0.8-1.25 eps window). Recorded, not repaired: GMMPS's 7.8e-3 eV vs recomputed 7.885e-3 (+1.1%, inside the tree's 2% band; a rounding discrepancy, not an error); the tree omits the base-LCDM model dependence and the 68% bands, which do not bear on its use. The value AS A PHYSICAL MEASUREMENT is base-LCDM-conditional and sits under a Planck-recorded 3.6 sigma H0 tension -- that standing is not what the tree uses and is not graded here beyond being named.",
 "what_would_change_the_grade": "NARROWED or DATA-DEPENDENT if the tree ever uses Lambda / Omega_Lambda as a physical measurement (e.g. to claim m ~ 7.8e-3 eV is a real field mass, or to fix a Hubble scale in cosmo.py's style) rather than as GMMPS's printed input -- then base-LCDM, w = -1, and the H0 tension become load-bearing and the later papers named here (ACT DR6, DESI DR2, SH0ES) must be READ. WRONG only if a re-read of GMMPS v2+ prints different values and the tree keeps v1's. OPEN would apply if the Planck primary could not be read; it was.",
 "reverify_command": "cd /tmp && PYTHONDONTWRITEBYTECODE=1 python3 " + S + "  # expect ALL PASS, exit 0",
 "report_path": D + "/audits/planck-cosmological-parameters-via-2604.01047.json"
}
json.dump(r, open(r["report_path"], "w"), indent=1)
print("ok")
