import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R = {
 "key": "zeta-pi-enclosures",
 "name": "zeta(6) = pi^6/945; 333/106 < pi < 355/113; zeta(7) partial sum to 30 with tail <= 1/(6*30^6)",
 "source": {
  "located": "Three classical mathematical facts, none with an original on arXiv. (i) zeta(6) = pi^6/945: Euler's formula zeta(2k) = (-1)^{k-1} 2^{2k-1} pi^{2k} B_{2k}/(2k)!, READ at source in O. Ciaurri, L.M. Navas, F.J. Ruiz, J.L. Varona, 'The computation of zeta(2k), beta(2k+1) and beyond by using telescoping series', arXiv:2307.08063v1 [math.NT] (2023): p.2 eq (3), p.7 Theorem 3.3 (Euler, 1740) eq (17) with a complete proof pp.5-8, Bernoulli recurrence and B_0, B_1, B_2 on p.4, B_{2k+1} = 0 on p.5. The value pi^6/945 itself is not printed there; it follows from eq (3) at k = 3 with B_6 = 1/42, both re-derived exactly here. (ii) 333/106 < pi < 355/113: these are the 3rd and 4th convergents of the continued fraction pi = [3;7,15,1,292,...]; READ in C.H. Lopez Zapata, arXiv:2603.09719v5 [math.GM] (2026), p.5 eqs (11)-(12) (partial quotients 3,7,15,1,292,1,1,1,2,1,3,1,14,2,1 = A001203; convergent numerators 3, 22, 333, 355, 103993 = A002485; denominators named A002486 on p.7, not listed) and p.3 eq (7) (Khinchin's |alpha - p_k/q_k| bounds). That paper is math.GM and discloses Claude-assisted verification (p.9), so it is used only as a pointer; the enclosure is PROVED here from Machin's formula with exact rationals and does not rest on it. (iii) sum_{n>30} n^-7 <= INT_30^oo x^-7 dx = 1/(6*30^6): the integral comparison for a decreasing function -- elementary calculus, no paper; proved exactly here.",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "alphaXiv answer_pdf_queries on 2307.08063 (pp.1-12, 14-15, 17-19, 23-24 returned verbatim) and on 2603.09719 (pp.1-9 verbatim). Euler 1735/1740 (De summis serierum reciprocarum; Introductio 1748), Zu Chongzhi (355/113, 5th c.), Machin 1706 and Khinchin 'Continued Fractions' (1964) are NAMED-NOT-READ; the content each would supply is re-derived in rederive/zeta-pi-enclosures.py."
 },
 "published_statement": "arXiv:2307.08063 p.2 eq (3): 'zeta(2k) = (-1)^{k-1} 2^{2k-1} pi^{2k} B_{2k} / (2k)!, k = 1, 2, 3, ...'; p.7 'Theorem 3.3 (Euler, 1740). For every positive integer k we have zeta(2k) = sum_{n>=1} 1/n^{2k} = (-1)^{k-1} (2 pi)^{2k} B_{2k} / (2 (2k)!), where B_{2k} are the Bernoulli numbers of even index', with B_k := B_k(0) from z e^{xz}/(e^z - 1) = sum B_k(x) z^k/k! (p.1 eq (1)). At k = 3, B_6 = 1/42: zeta(6) = 2^5 pi^6 (1/42)/720 = pi^6/945. arXiv:2603.09719 p.5: 'pi = [3; 7, 15, 1, 292, ...]' and '(q_k) = 3, 22, 333, 355, 103993, 104348, 208341, ...' (the numerators of pi's convergents, A002485). Tree's use (noise.py:731-733): 'PROVE (beta/tau) coef (z6 pi^6 - z7)/(sqrt(2 pi) pi^7) < 1/2 from 333/106 < pi < 355/113, sum_{1}^{30} n^-7 <= z7 <= that + 1/(6*30^6), r^2 = 2 pi, r > 0.'",
 "published_hypotheses": [
  "P1 (2307.08063 Thm 3.3) k a positive integer; zeta(s) = sum n^{-s} for Re s > 1 (p.2), so zeta(6) is the convergent series, no continuation needed",
  "P2 (2307.08063 p.1, p.5) Bernoulli numbers in the convention B_k = B_k(0) of the generating function z e^{xz}/(e^z-1), B_1 = -1/2; B_{2k} = B_{2k}(1) so the even-index values (B_6 = 1/42) are convention-independent",
  "P3 (continued fractions, 2603.09719 p.3 eq (7), p.5) pi irrational; convergents alternate about the number, even-index below and odd-index above; 333/106 is convergent index 2 (below), 355/113 index 3 (above)",
  "P4 (integral comparison) x^-7 positive and decreasing on [N, oo), N = 30, so n^-7 <= INT_{n-1}^{n} x^-7 dx for n >= 31 and sum_{n>30} n^-7 < INT_30^oo x^-7 = 1/(6 N^6); the lower bound z7 >= partial sum needs only positivity of the terms",
  "P5 (tree-side, unstated) z3's nonlinear real arithmetic (nlsat) is trusted to be sound: an 'unsat' of H and not-goal is taken as proof; z3 emits no checkable certificate here. Removed by the exact-rational box proof E4b below"
 ],
 "hypothesis_drift": [
  "NO DROPPED, ADDED OR WEAKENED HYPOTHESIS of the three facts: the tree uses zeta(6) at k = 3 (P1), the even-index B_6 (P2, convention-free), the two convergents on the correct sides (P3), and the integral tail at N = 30 (P4), exactly as stated. All four are re-derived exactly (E1-E3).",
  "LABEL, NOT A DRIFT IN ANY NUMBER (noise.py:126-128, :263, :1063-1064): the tree calls the tau = beta/10 z3 query a 'vacuity guard'. It is a negative control: at tau = beta/10 the bound is B = 1.28300 > 1/2 (E4e), so the statement is FALSE there and could not be proved from any true hypotheses. The genuine vacuity guard is the satisfiability check (noise.py:745-747, :1062), which is correct and re-run here with an exact rational witness (r = 2.5066, p = r^2/2 = 3.14152178 in (333/106, 355/113)). Recorded, not repaired.",
  "IDLE HYPOTHESIS (noise.py:732, :741-742): the upper bound z7 <= sum + 1/(6*30^6) -- the only place the tail estimate enters -- is not used by the proof. The left side 2 coef (z6 p^6 - z7) DECREASES in z7, so only z7 >= partial sum matters; z3 proves the goal with the upper bound deleted (E4c) and the exact box proof never reads it (E4b). It serves only the satisfiability (vacuity) check. Even the crude lower bound z7 >= 1 (N = 1, no tail at all) with pi in (3, 22/7) still proves the claim at tau = beta (E4e). Not a defect; an over-provision.",
  "'DERIVED in sympy, not typed' (noise.py:123, :725): z6 = nsimplify(zeta(6)/pi^6). sympy.zeta(6) auto-evaluates through sympy's own implementation of Euler's formula (it is exactly pi^6/945 symbolically, so nsimplify is a no-op rather than a numeric rational recognition). So the value is Euler's theorem as implemented in the library, not derived from the thermal kernel; accurate as far as it goes, and confirmed independently from the Bernoulli recurrence (E1).",
  "SCOPE (not this entry): the conclusion 'Hoelder bound < 1/2 at tau = beta' also rests on 108000 = (2/3) x 900 x 180, i.e. on rho = pi^2/30 (Stefan-Boltzmann per scalar dof) and ||g^2||_1 = 180 (zeta6 - zeta7)/pi^3 (Parseval, exact), and on the Hoelder step itself; those are separate canonical entries (stefan-boltzmann, parseval-plancherel, hoelder-inequality). Only the arithmetic 108000 = (2/3)*180*900 is checked here (E4a), and the tree's hoelder_bound_constants reproduces (108000, 1/945) when imported read-only (E4d)."
 ],
 "data_at_publication": [
  {"quantity": "pi (enclosure used)", "value_then": "333/106 = 3.1415094... < pi < 355/113 = 3.14159292... (convergents of the continued fraction; 355/113 known since the 5th century)", "value_now": "pi = 3.14159265358979...; rigorous Machin enclosure of width 4.7e-56 computed here; pi - 333/106 = 8.322e-5, 355/113 - pi = 2.668e-7", "source_now": "exact-rational Machin series in rederive/zeta-pi-enclosures.py (E2); mpmath 60 digits", "moves_conclusion": "No. A mathematical constant; nothing moves. MEASURED margin: the crude box proof still succeeds with any upper bound on pi up to 3.15486 (lower 333/106) or 3.14542 (lower 3, z7 >= 1); 22/7 suffices."},
  {"quantity": "zeta(6)/pi^6", "value_then": "1/945 (Euler)", "value_now": "1/945; zeta(6) = 1.01734306198444913971...", "source_now": "Euler's formula with B_6 = 1/42 from the recurrence; mpmath and sympy cross-checks (E1)", "moves_conclusion": "No (exact identity)."},
  {"quantity": "zeta(7) enclosure", "value_then": "sum_{1}^{30} n^-7 <= zeta(7) <= that + 1/(6*30^6) = that + 2.286e-10", "value_now": "zeta(7) = 1.008349277381922826839798; true tail 2.0665e-10, between 1/(6*31^6) and 1/(6*30^6)", "source_now": "mpmath zeta(7), 60 digits (E3)", "moves_conclusion": "No; and the upper bound is not used by the proof at all."},
  {"quantity": "Hoelder bound B at tau = beta (the conclusion's number)", "value_then": "'< 1/2' (z3); mpmath row in noise.py", "value_now": "B(beta) = 0.128300159; crossing tau*/beta = 0.256600 where B = 1/2; B(beta/10) = 1.28300", "source_now": "rederive/zeta-pi-enclosures.py (E4e)", "moves_conclusion": "No; factor 3.9 of margin at tau = beta."}
 ],
 "rederivation": {
  "method": "z3",
  "script_path": D + "/rederive/zeta-pi-enclosures.py",
  "outcome": "35 PASS, 0 FAIL (output in rederive/zeta-pi-enclosures.out). E1: B_2, B_4, B_6 = 1/6, -1/30, 1/42 from the recurrence; Euler's eq (3) at k = 3 gives zeta(6)/pi^6 = 1/945 exactly (controls k = 1, 2 give 1/6, 1/90); mpmath agrees to 55 digits; sympy symbolic agrees; the tree's nsimplify route gives 1/945. E2: Machin's formula with alternating-series truncation gives an exact rational enclosure [PL, PU] of width 4.7e-56 with 333/106 < PL and PU < 355/113 -- a PROOF of the enclosure without floating point; the continued fraction computed from the enclosure is [3;7,15,1,292,1,1,1,2,1,3,1] and the convergents are 3, 22/7, 333/106, 355/113, 103993/33102, matching 2603.09719 eq (12). E3: INT_30^oo x^-7 = 1/(6*30^6) exactly (sympy); true tail 2.066e-10 lies in (1/(6*31^6), 1/(6*30^6)). E4: 108000 = (2/3)*180*900; an EXACT-RATIONAL BOX PROOF (no z3; monotonicity of each side in p and z7, rational lower bound on sqrt(2p)) proves the tree's claim at tau = beta, and fails at tau = beta/10 and with the coefficient x10 (controls); an independent z3 encoding proves it (hypotheses satisfiable) and cannot prove the beta/10 or x10 variants; z3 still proves it with the z7 upper bound deleted; the tree's own hoelder_bound_constants and hoelder_bound_proof, imported read-only, return (108000, 1/945), (True, True) at tau = beta and (False, True) at beta/10. B(beta) = 0.128300, tau* = 0.256600 beta.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "arXiv:1209.5030 (Ciaurri, Navas, Ruiz, Varona 2012; Amer. Math. Monthly 122 (2015) 444)", "effect": "confirms", "what": "An independent telescoping-series proof of Euler's zeta(2k) formula; the same proof is reproduced in full in 2307.08063 pp.5-8 (its ref [9]), which was read.", "read_status": "READ via its reproduction in 2307.08063 pp.5-8; the 1209.5030 PDF itself is abstract-only here (discover_papers)"},
  {"ref": "arXiv:2303.14532 (Stringent bounds for the non-zero Bernoulli numbers, 2025)", "effect": "extends", "what": "Uses Euler's formula for zeta(2k) as the starting point to bound |B_{2n}|; takes the formula as established.", "read_status": "abstract only (discover_papers)"},
  {"ref": "arXiv:1912.06345 (Zeilberger & Zudilin, irrationality measure of pi <= 7.1032...)", "effect": "extends", "what": "Concerns how well pi can be approximated by rationals in general; does not bear on the two specific convergents, whose sides are fixed by the continued fraction and proved here.", "read_status": "abstract only (discover_papers); restated at 2603.09719 p.2 (READ)"},
  {"ref": "arXiv:2606.20091 (certified arbitrary-precision evaluation of generalized multiple zeta functions, 2026)", "effect": "confirms", "what": "Certified numerics for zeta-type sums; nothing in it moves zeta(6) or zeta(7). No later work narrows or contradicts any of the three facts; none could, as each is a proved identity or inequality.", "read_status": "abstract only (discover_papers)"}
 ],
 "lacked_data": "M's hypothesis tested: nothing here is a measurement, so there is no datum the authors could have lacked. zeta(6) = pi^6/945 is an exact identity (Euler; the two arXiv restatements date the proof 1735 [2203.13930 abstract] and 1740 [2307.08063 p.2, p.7] -- a dating discrepancy in the secondary literature, recorded, not resolved; it moves no value). 333/106 and 355/113 are convergents of pi whose sides are fixed by the continued fraction; proved here from Machin's series with exact rationals. The tail bound is the integral test. Evidence against 'lacked data changes the conclusion': every input is re-derived exactly; the claim has a factor 3.9 of margin at tau = beta (B = 0.1283 vs 1/2) and survives far cruder inputs (pi < 22/7, z7 >= 1). Evidence for: none. The only live question is not data but trust in z3's nonlinear solver, and the exact box proof E4b removes it. Having more digits of pi or zeta(7) changes nothing.",
 "grade": "STANDS",
 "grade_evidence": "All three external facts are theorems and are re-derived exactly here: zeta(6)/pi^6 = 1/945 from Euler's formula (READ at 2307.08063 eq (3)/Thm 3.3) with B_6 = 1/42 from the recurrence; 333/106 < pi < 355/113 proved by an exact-rational Machin enclosure, and both are shown to be convergents on the correct sides; sum_{n>30} n^-7 <= 1/(6*30^6) by exact integral comparison. The tree's use carries every hypothesis; the z3 claim B(tau=beta) < 1/2 is re-proved independently by z3 and, without z3, by an exact box proof; the tree's own functions reproduce. No datum moves (pure mathematics). Recorded, not repaired: the beta/10 query labelled 'vacuity guard' (noise.py:128, :1063) is a negative control on a false statement (B = 1.283 there), while the real vacuity guard is the satisfiability check; the z7 upper bound (the tail) is idle in the proof. Neither is a hypothesis drift that narrows the result.",
 "what_would_change_the_grade": "Nothing about the three facts can change: they are proved. The downstream conclusion (Hoelder bound < 1/2 at tau = beta) would change only through the OTHER entries it rests on -- the coefficient 108000 (rho = pi^2/30 and ||g^2||_1 = 180 (zeta6 - zeta7)/pi^3) or the Hoelder step -- which are audited separately; a coefficient larger by a factor > 3.897 would break the tau = beta claim (the x10 control fails). A bug in z3's nlsat would not change it: the exact box proof stands independently.",
 "reverify_command": "PYTHONDONTWRITEBYTECODE=1 python3 " + D + "/rederive/zeta-pi-enclosures.py  # exit 0, 0 FAIL; needs sympy, mpmath, z3-solver (pip install z3-solver); imports research/warp-drive/noise.py read-only",
 "report_path": D + "/audits/zeta-pi-enclosures.json"
}
json.dump(R, open(R["report_path"], "w"), indent=1)
print("ok", sum(1 for l in open(D + "/rederive/zeta-pi-enclosures.out") if l.startswith("PASS")))
