import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/"
r = {
 "key": "o5-pass-literature-tally",
 "name": "DOCKET 62 O5 literature search: six self-consistent families, zero with m(r) < 0; no no-go theorem found",
 "source": {
  "located": "Not one paper: the DOCKET 62 O5 pass's 'SIX FAMILIES RETURNED' block (workflow journal, harvested at tasks/wq1u9n1d8.output, key 'known_self_consistent_solutions'), transcribed into throatmass.py SELF_CONSISTENT_FAMILIES (:122-160). Its six sources: Hochberg-Popov-Sushkov gr-qc/9701064 (PRL 78 2050, 1997); Khusnutdinov-Sushkov hep-th/0202068 (PRD 65 084028, 2002); Garattini gr-qc/0501105 (CQG 22 1105, 2005); Abdolrahimi-Page-Tzounis 1607.05280 (PRD 100 124038); Sanders 2007.14311 (AHP 23 1321, 2022); Pinamonti 2011 / Pinamonti-Siemssen 2015 / Meda-Pinamonti-Siemssen 2020 / Gottschalk-Siemssen 2021.",
  "read_status": "READ",
  "via": "The journal block READ verbatim (parsed in the rederive script, C1). HPS, KS and Garattini READ in the arXiv v1 text layers banked earlier in this docket at d67/src/casmag/all/{gr-qc_9701064v1,hep-th_0202068v1,gr-qc_0501105v1}.txt (KS eqs. (8)-(10), (59)-(65) and summary; Garattini eqs. (11)-(16), (40)-(41), (77)-(79), sec. VII; HPS pp. 7-8). APT 1607.05280 and Sanders 2007.14311 via this docket's own audits (audits/1607.05280.json, audits/2007.14311.json, both READ at source, both STANDS). Pinamonti et al.: NAMED-NOT-READ (the pass itself recovered them from bibliographies only). alphaXiv returned 'assistant quota exceeded' for answer_pdf_queries and discover_papers in this stage, and arxiv.org / nature.com / pmc / pith.science are EGRESS_BLOCKED, so no new paper was read at source this stage."
 },
 "published_statement": "The pass's tally, verbatim (journal): 'SIX FAMILIES RETURNED. THIS IS THE CONTROL (failure mode 1): the search apparatus returns positives, so the zero reported below is a measurement and not a dead search. ... THE NEGATIVE, AND IT IS THE ANSWER TO THE ROW: solutions found with m(r) < 0 anywhere : 0; solutions found with negative ADM mass : 0; no-go theorem forbidding either found : 0. Status NOT-FOUND, not NOT-SEARCHED, and not NO.' The pass itself qualifies the set: HPS is 'THE ONLY GENUINE NON-PERTURBATIVE SELF-CONSISTENT CONSTRUCTION IN THE SET'; APT is 'FIRST ORDER IN hbar ONLY ... not iterated to a fixed point'; Pinamonti et al. 'not read at source'. The sources' own words on the two estimate papers: KS (hep-th/0202068 p.10) 'the self-consistent semiclassical wormhole, if exists, should possess the throat of sub-Planckian radius', with eq. (62) 'E = -2c^4 a/G. Note that the total energy is negative.' and self-consistency imposed only as 'the total energy must coincide with the ground state energy' (eq. 63) on an assumed flat-space thin-shell background r = |rho| + a (eq. 8); Garattini (gr-qc/0501105, titled 'Self sustained traversable wormholes?') assumes the Ellis background phi = 0, b = r_t^2/r (eq. 14-16) and imposes only the integrated 'self-consistent equation for TT tensors' pi r_t/(2G) = -E_TT (eq. 41). Tree use: throatmass.py:40-42 'No self-consistent semiclassical solution with m(r) < 0 or negative ADM mass, and no theorem forbidding one. NOT-FOUND, not NO.'; ledger.py:1729 and specthm.py:1084 '0 of 6 (self-consistent) families in print REPORT m < 0 -- true of what was reported'.",
 "published_hypotheses": [
  "H1 (scope of the set): the six are what ONE search pass (DOCKET 62 O5) returned; not a census of print.",
  "H2 (reporting): 'm < 0 reported' is the pass's tally applied per family -- a statement about what each paper REPORTS, not about the solutions' m(r) profiles (HPS never print the flare profile; APT's read pages print no mass-function sign).",
  "H3 (self-consistency grade, per source): only HPS, Sanders and the Pinamonti line solve the semiclassical equations as a fixed point; KS and Garattini impose an INTEGRATED energy balance on an ASSUMED background (KS 'if exists'; Garattini's title a question); APT is a first-order linearised backreaction, not iterated.",
  "H4 (control scope, throatmass.py:57-60): the control shows the search returns SOLUTIONS; it is not shown able to surface a no-go theorem.",
  "H5 (per-family sign basis, throatmass.py:137-159): throats judged by m = r_0/2 at r' = 0 in the proper-distance gauge."
 ],
 "hypothesis_drift": [
  "DROPPED H1 at ledger.py:1729 and specthm.py:1084: '%d of %d (self-consistent) families IN PRINT REPORT m < 0' reads the pass's six as the population in print; throatmass.py:49-50 ('the same search returned self-consistent families') keeps H1. READ evidence the six are not the population: Arrechea-Breen-Ottewill-Pisani-Taylor arXiv:2607.07583v1 p.1 (banked text) cites vacuum-polarisation-supported horizonless configurations relaxing compactness bounds [18-20] (Arrechea-Barcelo 2305.07939; Arrechea-Barcelo-Carballo-Rubio-Garay PRD 109 104056 = 2310.12668; Reyes-Tomaselli 2301.00826), none among the six. Superseded wording ledger.py:1675-1678 ('%d self-consistent families are in print') has the same drift.",
  "WEAKENED H3 at throatmass.py:122-126 and ledger.py:1729 ('self-consistent families', counted as six): the journal's own qualifiers (HPS 'the only genuine non-perturbative self-consistent construction in the set'; APT 'not iterated to a fixed point') are not carried into the count. By the sources, three of the six (KS, Garattini, APT) are not fixed-point solutions of G = 8 pi <T>: KS and Garattini impose one integrated equality on an assumed metric (KS eq. 63, Garattini eq. 41), APT is linear backreaction.",
  "DISCREPANCY in H5 at throatmass.py:141-142 (KS row 'throat (short-throat flat-space wormhole): m = r_0/2 > 0 at the throat') and the selftest check throatmass.py:359-364 that applies m_throat = r_0/2 to a = 0.0141 l_P: KS's metric (eq. 8) is r = |rho| + a, flat on both sides, so m = (r/2)(1 - r'^2) = 0 wherever defined (computed, C2) and the ADM mass is 0; the throat is a distributional shell (R = -8 a^-1 delta(rho), eq. 10) where r' is undefined, not a smooth r' = 0 throat. KS PRINT a NEGATIVE total energy E = -2c^4 a/G (eq. 62, reproduced in C2). This does not move the tally -- E is a proper-volume integral, neither the Misner-Sharp m(r) nor the ADM mass -- but the family's basis is misstated, and 'zero negative mass' is not 'positive energy' for this family. Recorded as a discrepancy, not a refutation.",
  "WEAKENED H2 -> presented as control of the zero (throatmass.py:49-53, 'the zero is a measurement and not a dead search'): computed here (C2, C4) that in FIVE of the six families m >= 0 is fixed by the symmetry class or by the background the authors ASSUMED, before any semiclassical dynamics: flat FLRW m = R^3 H^2/2 >= 0 for every state; ESU m = (a/2) sin^3 chi >= 0; Garattini's Ellis m = r_t^2/(2r) > 0; KS m = 0; APT Schwarzschild M >> m_P at leading order. Only HPS could have returned m < 0 dynamically, and HPS do not print m beyond the throat. So the control shows the search returns solutions, not that it returns solutions from a class in which m < 0 is possible; the zero carries information about ONE family only.",
  "ADDED (none): the tree does not add a hypothesis the sources lack; its own later work (hpscentre.py:273, 288: M_NEGATIVE_FOUND_IN_HPS_SYSTEM = True, first at 0.0516 l_P, CONSERVED reading only) already demotes the tally to 'true of what was reported, and no longer the tree's finding' (ledger.py:1729-1731)."
 ],
 "data_at_publication": [
  {"quantity": "families returned by the pass", "value_then": "6 (journal block, numbered 1-6)", "value_now": "6 (re-parsed, C1; throatmass.SELF_CONSISTENT_FAMILIES_RETURNED = 6)", "source_now": "tasks/wq1u9n1d8.output journal block; throatmass.py:162", "moves_conclusion": "no -- the record reproduces exactly"},
  {"quantity": "families reporting m(r) < 0 / negative ADM mass", "value_then": "0 / 0", "value_now": "0 / 0 as REPORTED (C1); but the tree has since MEASURED m < 0 in HPS's own conserved system at 0.0516 l_P (hpscentre.py:273, 288)", "source_now": "throatmass.py:163; hpscentre.py", "moves_conclusion": "moves the reading, not the record: 'reported' stays 0; 'exists in a returned family's system' is now 1 (tree's measurement, CONSERVED reading, outside the AHS established domain per hpscentre M_NEGATIVE_FOUND_INSIDE_DOMAIN = False)"},
  {"quantity": "families in which m < 0 is possible at all (class/assumed background)", "value_then": "not assessed by the pass", "value_now": "1 of 6 (HPS) -- computed, C2/C4", "source_now": "rederive/o5-pass-literature-tally.py", "moves_conclusion": "yes, for the evidential weight: the zero is informative about one family, not six"},
  {"quantity": "throat families", "value_then": "3", "value_now": "3 (but KS's 'throat' is a distributional thin shell with m = 0 off it, not r_0/2)", "source_now": "throatmass.py:164; KS eq. (8), (10)", "moves_conclusion": "no for the count; discrepancy in the per-family basis"},
  {"quantity": "Planck length (for the scale rows beside the tally)", "value_then": "1.616255e-35 m (CODATA 2018)", "value_now": "1.616255e-35 m (CODATA 2022 leaves G = 6.67430e-11, hbar, c unchanged)", "source_now": "CODATA 2022 (not re-read this stage; achievable.L_PLANCK agrees to 1.5e-8)", "moves_conclusion": "no"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "rederive/o5-pass-literature-tally.py",
  "outcome": "ALL PASS (22 checks). C1: the journal block lists exactly six numbered families and the tally lines read 0 / 0; throatmass.py's derived counts (6, 0, 3) match. C2 (sympy, Misner-Sharp from each metric): flat FLRW m = R^3 H^2/2 >= 0 identically; ESU m = (a_0/2) sin^3 chi >= 0; Garattini's Ellis background m = r_t^2/(2 sqrt(l^2 + r_t^2)) > 0, -> 0 at infinity (ADM 0); KS r = |rho| + a gives m = 0 off the shell (ADM 0); KS eq. (62) E = -2a reproduced from eq. (61) with r'' = 2 delta(rho); HPS throat m(0) = r_0/2, m''(0) = aa(1 - 2 r_0 aa)/2 -> 0 at r''(0) = 0; and an illustrative (not HPS-data) check that the flare form HPS print, R ~ l plus a bounded wiggle, has m < 0 wherever the wiggle's slope is positive. C3 (banked source text): KS prints 'Note that the total energy is negative.' and 'if exists'; a = l_P sqrt(f/2) with f ~ 4e-4 gives 0.01414 l_P (printed 0.0141) and 0.16/0.0141 = 11.35 m_P (printed 11.35); Garattini's (78) x (79) arithmetic 1.158822606 x 0.3860531213 = 0.44736708408 (printed 0.4473670842). C4: m >= 0 is forced by class or assumed background in 5 of 6 families; the tree's own hpscentre flag M_NEGATIVE_FOUND_IN_HPS_SYSTEM = True. throatmass.py --selftest also re-run: SELFTEST OK.",
  "agrees_with_source": "partly"
 },
 "later_literature": [
  {"ref": "J. Arrechea, C. Breen, A. Ottewill, L. Pisani, P. Taylor, 'Vacuum polarization and renormalized stress-energy tensor of spherical thin shells', arXiv:2607.07583v1 (8 Jul 2026)", "effect": "extends", "what": "p.1: the Boulware vacuum is 'the natural vacuum state in horizonless equilibrium configurations like stars'; vacuum polarisation 'also seen to contribute to the relaxation of general-relativistic compactness bounds [18-20]'. Shows a body of semiclassical equilibrium solutions absent from the six. Also relevant to KS: sharp (thin-shell) boundaries 'generate contributions to the quantum stress-energy that diverge as the boundary is approached and that cannot be renormalized away' (p.2) -- a caution on KS's thin-shell model.", "read_status": "READ (pp.1-2 and reference list, banked text d67/src/casmag/all/2607.07583v1.txt)"},
  {"ref": "J. Arrechea, C. Barcelo, R. Carballo-Rubio, L. J. Garay, 'Schwarzschild geometry counterpart in semiclassical gravity', Phys. Rev. D 101, 064059 (2020)", "effect": "contested", "what": "Search-engine summary only (WebSearch, this stage): Boulware-state self-consistent solution with regularised Polyakov RSET; horizon replaced by a wormhole neck; 'a cloud of negative mass from the effective semiclassical fluid'; beyond the neck 'a runaway decrease of mass as the radius increases', null singularity at finite distance. If READ and confirmed as m(r) < 0, a self-consistent solution with m < 0 somewhere is in print and outside the six -- but singular and not regular-centre.", "read_status": "NAMED-NOT-READ (alphaXiv quota exceeded; journals.aps.org / arxiv.org not reachable)"},
  {"ref": "Arrechea, Barcelo, Carballo-Rubio, Garay, 'Semiclassical constant-density spheres in a regularized Polyakov approximation', arXiv:2105.11261, Phys. Rev. D 104, 084071 (2021)", "effect": "contested", "what": "Search-engine summary only: 'a complete catalogue of semiclassical self-consistent solutions'; 'for super-critical regimes, the Misner-Sharp mass is infinite and negative at r=0'. If confirmed, m < 0 in print at a singular centre -- the same regular-centre caveat as throatmass.py's computed RN control (:43-48).", "read_status": "NAMED-NOT-READ"},
  {"ref": "Arrechea, Barcelo, Carballo-Rubio, Garay, 'Semiclassical relativistic stars', arXiv:2110.15808, Sci. Rep. 12, 15958 (2022); and 'Ultracompact horizonless objects in order-reduced semiclassical gravity', arXiv:2310.12668, PRD 109 104056 (2024)", "effect": "extends", "what": "Self-consistent Boulware-state ultracompact stars beyond the Buchdahl limit (search summary; 2310.12668 cited in two banked READ texts). m(r) sign not read.", "read_status": "NAMED-NOT-READ (citations READ in 2607.07583v1 and 2606.01061v1 reference lists)"},
  {"ref": "discover_papers attempt", "effect": "contested", "what": "The one discover_papers call returned 'alphaXiv assistant quota exceeded'; WebSearch (two queries) substituted for discovery only. No claim above is taken from a search summary as READ.", "read_status": "NOT-RUN (quota)"}
 ],
 "lacked_data": "What the pass lacked, and whether it moves the tally. (1) THE FLARE PROFILE OF HPS: HPS never print m(l) beyond the throat (p.8 gives only R ~ l with 'Planck-scale wiggles' and F ~ (a ln l - b)^2); the pass therefore could only record 'not reported'. The tree later computed it: m < 0 in HPS's own conserved system at 0.0516 l_P (hpscentre.py). That is data the 1997 authors did not publish and the pass did not have; it does not change what HPS REPORT, but it changes the reading 'zero in the returned families' from 0 to 1 in the conserved reading (outside the AHS established domain). (2) THE BOULWARE-STATE SELF-CONSISTENT LITERATURE (Arrechea-Barcelo-Carballo-Rubio-Garay 2020-2024 and successors): absent from the six (READ evidence of the gap: 2607.07583v1 p.1). Per search summaries only -- NOT READ -- two of these report negative mass (a 'cloud of negative mass' and runaway mass decrease behind a wormhole neck; Misner-Sharp mass 'infinite and negative at r = 0' for super-critical stars). If confirmed at source, a literature-level 'no self-consistent semiclassical solution with m(r) < 0' is false for SINGULAR, non-regular-centre, regularised-Polyakov solutions -- the same exclusion the tree's RN control already names (D4 regular centre) -- and the tally survives only as 'what one pass returned'. Evidence against over-reading in M's favour: none of this is READ, none of it is regular-centre or inside a rigorously established RSET, and none has been shown asymptotically-flat-with-m<0-and-regular. (3) Nothing numerical moves: the tally is a count; l_P is unchanged between CODATA 2018 and 2022.",
 "grade": "NARROWED",
 "grade_evidence": "The record STANDS: the journal block lists six families and tallies 0 / 0, and throatmass.py derives exactly 6, 0, 3 (C1; selftest OK). It is NARROWED on three READ-or-computed grounds, none a refutation: (a) SCOPE -- ledger.py:1729 and specthm.py:1084 say 'in print'; the six are one pass's return and READ text (2607.07583v1 p.1) cites semiclassical equilibrium solutions outside them; (b) SELF-CONSISTENCY -- by the sources' own equations, KS (eq. 63, 'if exists') and Garattini (eq. 41, title with '?') impose one integrated energy balance on an assumed background and APT is first-order linear backreaction, so 'six self-consistent families' holds for three (HPS, Sanders, Pinamonti line); (c) CONTROL STRENGTH -- computed with sympy, m >= 0 is fixed by the symmetry class or assumed background in 5 of 6 families (flat FLRW m = R^3 H^2/2; ESU m = (a/2) sin^3 chi; Ellis m = r_t^2/2r; KS m = 0; APT Schwarzschild at leading order), so the zero is informative about HPS alone, and in HPS the tree has itself since measured m < 0 in the conserved reading. Discrepancy, not refutation: throatmass.py:141-142 gives KS m = r_0/2 > 0 at the throat, whereas KS's thin-shell metric gives m = 0 off the shell (ADM 0) and KS print a negative total energy E = -2c^4 a/G. Not WRONG: no READ counterexample -- the Boulware-state negative-mass reports are search-summary only (NAMED-NOT-READ). Not OPEN overall: the narrowing rests on READ text and sympy, independent of the unread papers.",
 "what_would_change_the_grade": "To WRONG (as a literature statement 'no self-consistent semiclassical solution with m(r) < 0 in print'): READ at source Arrechea-Barcelo-Carballo-Rubio-Garay PRD 101 064059 (2020) or arXiv:2105.11261 and confirm a self-consistent solution with m(r) < 0 -- the tally would remain accurate only as a record of the pass. If the negative mass there appears only at a singular centre or beyond a singular neck, NARROWED stands with the regular-centre / asymptotic-flatness hypothesis named. To STANDS: the owners restrict the wording to 'of the six families one pass returned' (ledger.py:1729, specthm.py:1084), carry the self-consistency grade per family, and correct the KS basis -- or an exhaustive later survey READ at source finds no m < 0 self-consistent solution in any class where m < 0 is kinematically possible.",
 "reverify_command": "python3 " + D + "rederive/o5-pass-literature-tally.py && (cd /home/user/Claude-Method-Works/research/warp-drive && python3 throatmass.py --selftest | tail -3) && grep -n 'Note that the total energy is negative\\|if exists' " + D + "src/casmag/all/hep-th_0202068v1.txt && grep -n 'self-consistent equation for TT\\|Self sustained traversable wormholes?' " + D + "src/casmag/all/gr-qc_0501105v1.txt && sed -n 60,80p " + D + "src/casmag/all/2607.07583v1.txt",
 "report_path": D + "audits/o5-pass-literature-tally.json"
}
json.dump(r, open(D + "audits/o5-pass-literature-tally.json", "w"), indent=1)
print("written")
