import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R = {
"key": "2604.01047#thm3.6",
"name": "GMMPS Thm 3.6 renormalisation constants alpha~^S_1 = 1/(64 pi^2), alpha~^TT_1 = 0 (general local covariance + perturbative agreement); alpha~^S_2 = alpha~^TT_2 = 0 assumed; Prop. 3.1 alpha_1",
"source": {
 "located": "arXiv:2604.01047 v1 [math-ph], 1 Apr 2026, Galanda, Meda, Murro, Pinamonti, Schmid, 'The Semiclassical Einstein-Klein-Gordon System: Asymptotic Analysis of Minkowski Spacetime': Prop. 3.1 and its proof (pp. 22-23, eqs (3.1)-(3.3)); Thm 3.6 and its proof (pp. 32-33, 35, 37, eqs (3.16), (3.17), (3.21), (3.23), (3.24)); recap p. 40 (4.1)-(4.2); 5.2-5.2.1 p. 62",
 "read_status": "READ",
 "via": "alphaXiv answer_pdf_queries on 2604.01047 (one call; pages 1, 7, 9, 22, 23, 31, 32, 33, 35, 37, 40, 62 returned verbatim). A second batched call and get_paper_content(fullText) were refused with 'alphaXiv assistant quota exceeded'; direct arxiv.org fetch is 403 at the proxy. NOT READ in this pass: p. 36 (the derivation of (3.22)), pp. 38-39 (end of the TT proof), eq. (1.1)-(1.2) (the form of :T_ab:), Prop. 3.3 in full, 5.1-5.2 assumptions (the sibling audit 2604.01047#sec5.3-mass READ 5.1 eq. (5.2) and 'alpha~^S_2 = 0, no renormalisation of the Newton constant')."
},
"published_statement": "Thm 3.6 (p. 33), verbatim: 'Consider the semiclassical Einstein equations given in (3.16). In the hypothesis of Proposition 3.1 and by the principle of general local covariance, the fixed value of alpha_1 gives that the values taken by alpha~^S_1 and alpha~^TT_1 are alpha~^S_1 = 1/(64 pi^2), alpha~^TT_1 = 0.' Prop. 3.1 (p. 23): with d_1 = -(1/16pi^2)(-1+2gamma+log(m^2/2mu^2)), c_1 = -(1/64pi^2)(-5/2+2gamma+log(m^2/2mu^2)), omega_0(:Phi:) = omega_0(:Phi_ab:) = 0, omega_0(:T^(0)_ab:) = 0, 'the renormalisation parameter alpha_1 ... is alpha_1 = (1/64pi^2)(-3/2 + 2gamma + log(m^2/2mu^2))'. Proof of Thm 3.6, S half (pp. 33-37): conformal perturbation g = Omega^2 eta, Omega^2 = (1 + W f_n(x) chi_nu(t))^2; state converges (nu -> inf) to 'the Poincare vacuum of the Klein-Gordon field of mass squared m^2 + dm^2', dm^2 = 2 m^2 W; '(3.21) lim lim <:T_ab:> = -(1/64pi^2)[log((m^2+dm^2)/2mu^2) - log(m^2/2mu^2)](m^2+dm^2)^2 eta_ab', computed 'using the explicit form of :T^(0)_ab: given in (3.3) with square mass equal to m^2 + dm^2 and alpha_1 as fixed in Proposition 3.1'; 'the value of alpha~^S_1 descends by this expression as a consequence of the principle of perturbative agreement'; comparison (p. 37): '-4/(64pi^2) m^2 dm^2 = -8 alpha~^S_1 m^4 W ... we get alpha~^S_1 = 1/(64pi^2)'. TT half (p. 37): plane-wave perturbation (3.23) h_ab = r_ab W f_k(t - x^3) chi_nu(t), r = (dx^1)^2 - (dx^2)^2; 'in the limit k -> 0 and nu -> inf ... this perturbation is a simple solution of the TT part of Eq. (3.16) with vanishing alpha~^TT_1'. p. 40 recap: 'the principle of general local covariance and the principle of perturbative agreement imply that some renormalisation constants are already fixed by their background value'. 5.2.1 (p. 62): 'This different behaviour [from Anderson et al. [2]] is originated by the choice of the renormalisation parameters done in Theorem 3.6'.",
"published_hypotheses": [
 "H1 (Prop. 3.1): one real Klein-Gordon field, mass m > 0, generic coupling xi, on Minkowski spacetime, in the Poincare vacuum omega_0 (Hadamard); Hadamard parametrix H = 1/(8pi^2 sigma) + v log(mu^2 sigma) with scale mu",
 "H2 (Prop. 3.1, p. 22): the residual freedom between :Phi: and :Phi_ab: fixed so that omega_0(:Phi:) = omega_0(:Phi_ab:) = 0 (d_1, c_1 as printed); alpha_1 then fixed by omega_0(:T^(0)_ab:) = 0",
 "H3 (Thm 3.6 statement): the principle of general local covariance (refs [12, 53]) -- alpha_1 fixed on Minkowski fixes the constants on every globally hyperbolic spacetime",
 "H4 (proof, pp. 35, 37; recap p. 40): the principle of perturbative agreement -- alpha~ fixed by equating the exact late-time <T> with the perturbative linear response (3.16)",
 "H5 (proof): the linearised equations (3.16), with alpha~^S_i, alpha~^TT_i independent (S/TT decoupling of Pi_abcd, Prop. 3.3)",
 "H6 (proof, S half): homogeneous switch-on, limits n -> inf (f_n -> 1) then nu -> inf; condition (3.17) |W chi''_nu (6 xi - 1)| < m^2; the state converges to the Poincare vacuum of mass^2 m^2 + dm^2 (appendix of ref [30])",
 "H7 (proof, S half, UNSTATED -- identified here): the late-time <T> (3.21) is evaluated with the Hadamard scale mu held fixed relative to the BACKGROUND metric eta (formula (3.3) with m -> sqrt(m^2+dm^2), mu unchanged), not relative to the perturbed metric g = Omega^2 eta",
 "H8 (proof, TT half): plane-wave TT perturbation (3.23) with k -> 0, nu -> inf; lim K_0(h^TT) = 0",
 "Not part of Thm 3.6 but bundled with it by the tree: alpha~^S_2 = alpha~^TT_2 = 0 assumed in 5.1, 5.2 (READ by the sibling audit for 5.1 only); alpha~^S_3, alpha~^TT_4 free in (3.16) (READ p. 32)"
],
"hypothesis_drift": [
 "ADDED (framing, not substantive): linstab.py:138-139 and :309-310 attribute Thm 3.6 to 'general local covariance and perturbative agreement'; the theorem STATEMENT (p. 33) names only Prop. 3.1's hypotheses and general local covariance -- perturbative agreement enters in the proof (pp. 35, 37) and in the p. 40 recap, so the tree's pairing is faithful to the paper as a whole.",
 "BUNDLED: linstab.py:139-141 puts 'alpha~^S_2 = alpha~^TT_2 = 0 is ASSUMED (5.1, 5.2)' and 'alpha~^S_3, alpha~^TT_4 FREE' in the same sentence as Thm 3.6; these are not part of Thm 3.6 (they are 5.1/5.2 choices and (3.16)'s free constants). Correctly labelled ASSUMED/FREE by the tree; the 5.2 TT assumption was not re-read in this pass (quota).",
 "DROPPED (harmless): the proof's own conditions H6 ((3.17), the order of limits, the state-convergence lemma of ref [30]) and H2 (the :Phi:/:Phi_ab: split) appear nowhere in linstab.py:136-141 or GMMPS_HYPOTHESES (linstab.py:304-312); alpha_1 does not depend on the H2 split and H6 holds for large nu, so neither moves a conclusion.",
 "HIDDEN IN THE SOURCE, INHERITED BY THE TREE: H7. The tree records the S value as resting on general local covariance (linstab.py:309-310, GMMPS_HYPOTHESES) exactly as the paper claims; the re-derivation here (C4) shows the printed (3.21) is the background-mu value, which general local covariance does not give. The drift is in the source's proof, not in the tree's quotation.",
 "SCOPE: linstab.py:137 writes alpha_1 exactly as Prop. 3.1 prints it; C2 shows that value follows from (3.3) only with [v_1] in the 1/(8pi^2)-stripped normalisation (v_1 = m^4/8), while p. 23 prints '[w_1] = m^4/(64pi^2)' in the other normalisation -- a notational discrepancy in the source, recorded, not a refutation; the tree's alpha_1 is unaffected."
],
"data_at_publication": [
 {"quantity": "empirical inputs to Thm 3.6 / Prop. 3.1", "value_then": "none: the result is a pure-number renormalisation identity (m, mu symbolic; Euler-Mascheroni gamma and pi only)", "value_now": "none", "source_now": "n/a (no measured quantity enters; the only numerical data in the paper, Lambda and Omega_Lambda of 5.3, belong to the sibling entry 2604.01047#sec5.3-mass)", "moves_conclusion": "no -- no datum can move it; the finding below is a derivation step, not a datum"}
],
"rederivation": {
 "method": "sympy",
 "script_path": D + "/rederive/2604.01047_thm3.6.py",
 "outcome": "19/19 checks behave as stated (exit 0; output in rederive/2604.01047_thm3.6.out). REPRODUCED: C1 the K_1 series of the printed vacuum two-point function gives (3.2)'s [w] and [d_a d_b w] exactly (sympy) and numerically (mpmath, residual O(sigma^2 log sigma)); C2 (3.3) gives Prop. 3.1's alpha_1 exactly when the v_1 term is m^4/(32 pi^2) (v_1 = m^4/8), and does NOT with the printed [w_1] = m^4/(64pi^2) inserted literally (difference (8pi^2 - 1)/(256 pi^4)): notational discrepancy; C3 the paper's own algebra -- first order of tr(3.21) = -4 m^2 dm^2/(64pi^2), and the p. 37 comparison gives alpha~^S_1 = 1/(64pi^2) (no arithmetic slip, no misprint). CONTRADICTED: C4 the late-time region of the S perturbation is (t > 0, Omega^2 eta) with constant Omega = 1+W, isometric to Minkowski by the dilation x -> Omega x with the SAME mass m; the locally covariant parametrix obeys Omega^2 H_g(m, mu) = H_eta(Omega m, Omega mu) (symbolic to O(sigma), and to all orders via the exact Bessel V = m I_1(m sqrt(2sigma))/(8pi^2 sqrt(2sigma))), so <T_g> = Omega^-2 T_eta(Omega m, Omega mu) = 0 EXACTLY at every order in W, by Prop. 3.1 itself; the printed (3.21) equals T_eta(Omega m, mu) exactly -- the value with mu held fixed relative to the background eta -- and is nonzero for Omega != 1. C5 inserting the covariant late-time value 0 into the paper's own comparison (p. 37) gives alpha~^S_1 = 0; the printed 1/(64pi^2) m^4 is exactly dT_vac/d log(mu^2), i.e. the one-loop running coefficient of the cosmological term, which is what a non-rescaled mu produces. TT half STANDS: C6 tr r = 0 and det(eta + W r) = -(1 - W^2), so there is no first-order volume/scale term and alpha~^TT_1 = 0 by either evaluation.",
 "agrees_with_source": "partly"
},
"later_literature": [
 {"ref": "gr-qc/0209075 (Anderson, Molina-Paris, Mottola 2003, AMM)", "effect": "contested", "what": "The rival result for the same system: the k^2 = 0 subtraction (4.4) leaves no k-independent term in the S sector ((4.5b) carries an overall k^2), i.e. the alpha~^S_1 = 0 case (sibling audit gr-qc_0209075_renorm-4.4: STANDS as a description of AMM's scheme, corroborated at order k^0). GMMPS 5.2.1 attribute the difference to Thm 3.6. C4-C5 here find that the general-local-covariance matching GMMPS invoke yields AMM's zero-momentum value, not 1/(64pi^2) -- a finding about Thm 3.6's derivation, not an independent reading of AMM.", "read_status": "READ in the sibling audit (alphaXiv, AMM p. 11); not re-read in this pass"},
 {"ref": "arXiv:2512.00503 v2 (Ishibashi, Maeda, Okamura 2025)", "effect": "extends", "what": "Holographic semiclassical gravity: renormalisation absorbs non-negative powers of m^2 into alpha_i and the perturbed Minkowski equations are proportional to m^2 on both sides (no k-independent term) -- the AMM structure, in different matter; does not test the scalar constant directly.", "read_status": "READ in the sibling audit gr-qc_0209075_renorm-4.4; not re-read here"},
 {"ref": "Hollands & Wald, local covariance and scaling of Wick products (gr-qc/0103074, gr-qc/0111108); Hollands-Wald 2005 perturbative agreement", "effect": "narrows", "what": "The framework whose scaling axiom says a constant rescaling g -> Omega^2 g with m fixed shifts the Hadamard scale mu -> Omega mu (the log Omega term). C4 uses only the paper's own parametrix (P2) and Prop. 3.1 to show this; the HW papers are the standard source of the principle and were NOT read in this pass.", "read_status": "NAMED-NOT-READ"},
 {"ref": "discover_papers for work after April 2026 narrowing or contesting GMMPS Thm 3.6", "effect": "contested", "what": "The single discover_papers call was refused ('alphaXiv assistant quota exceeded'); no later literature on Thm 3.6 itself was found or read in this pass. This row records the attempt, not a finding.", "read_status": "NOT RUN (quota)"}
],
"lacked_data": "M's hypothesis does not fit this result. Thm 3.6 uses no measured datum (data_at_publication: none), and the authors lacked nothing empirical: they cite and discuss AMM 2003 (Remark 3.5, 5.2.1) and the standard Hollands-Wald locally covariant framework (refs [12, 53, 55]). What C4 identifies is a derivation step, not a missing datum: (3.21) evaluates the late-time stress tensor with the Hadamard scale mu held fixed relative to the background metric, whereas the general local covariance the theorem invokes, applied to the late region (Omega^2 eta, mass m), which is isometric to Minkowski, gives exactly 0 by the paper's own Prop. 3.1. Evidence against the data hypothesis: every input to C1-C6 is printed in the paper itself. Evidence for it: none found. Having more data would not change the conclusion; re-evaluating (3.21) covariantly does (alpha~^S_1 -> 0 via the paper's own p. 37 comparison).",
"grade": "WRONG",
"grade_evidence": "SCOPE OF THE GRADE: the S half, alpha~^S_1 = 1/(64pi^2), as a consequence of the stated hypotheses (Prop. 3.1 + general local covariance, with perturbative agreement as the matching). The TT half, alpha~^TT_1 = 0, STANDS (C6). Prop. 3.1's alpha_1 STANDS (C1-C2), with a recorded [w_1]/[v_1] normalisation discrepancy that does not affect it. THE COMPUTED CONTRADICTION (C4-C5, from the paper's own printed formulas only): (i) in the S proof's late region the metric is Omega^2 eta with constant Omega = 1 + W and the field mass is m; the dilation x -> Omega x is an isometry onto Minkowski with the same m, and the paper's own state-convergence result puts the state in the vacuum there; (ii) general local covariance then gives <T_g> = pullback of omega_0(:T^(0):) = 0 by Prop. 3.1, exactly and at every order in W -- checked as Omega^2 H_g(m, mu) = H_eta(Omega m, Omega mu) symbolically and to all orders with the exact Bessel V, and T_eta(Omega m, Omega mu) = 0 identically; (iii) the printed (3.21) is identically T_eta(Omega m, mu), the value with mu frozen relative to the background, which is nonzero; (iv) with the covariant value 0 on the left of the paper's own comparison '-4/(64pi^2) m^2 dm^2 = -8 alpha~^S_1 m^4 W' (p. 37), alpha~^S_1 = 0; the printed 1/(64pi^2) m^4 equals dT_vac/d log mu^2 exactly, i.e. it is the log(Omega^2) that the frozen mu inserts. An independent consistency check points the same way: F_S(0) = -b_0 is proportional to alpha~^S_1 (linstab.py:158, READ from (5.2)-(5.3)), so a nonzero alpha~^S_1 makes the zero-momentum S response to a late-time constant rescaling nonzero, while the exact covariant response is zero. This is not a misprint (C3 reproduces 1/(64pi^2) from (3.21) exactly); the fault is in what (3.21) computes. LIMITS OF THE GRADE, stated so it is not over-read: p. 36 (the derivation of (3.22)) and Prop. 3.3 were NOT read (alphaXiv quota); the right-hand side of the comparison is taken as printed on p. 37. If (3.22) carried a compensating background-parametrix term, alpha~^S_1 = 1/(64pi^2) would be a non-covariant bookkeeping constant and the PHYSICAL zero-momentum coefficient would still vanish -- so the tree's use (the alpha~^S_1 that sets b_0 = -F_S(0) and GMMPS's reported mode) is contradicted under either reading. The grade does NOT say AMM is right in general, does NOT touch the roots near -b_1/b_2 set by the free alpha~^S_3, alpha~^TT_4 (linstab.py:170-180), and does NOT adjudicate which renormalisation condition is physical beyond what general local covariance, as GMMPS themselves invoke it, implies. Nothing in the tree is repaired by this audit; linstab.py:181-183's 'not adjudicated here' is the tree's standing record and is left to M.",
"what_would_change_the_grade": "To NARROWED or STANDS: a reading of p. 36/(3.22), Prop. 3.3 or eq. (1.1)-(1.2) showing that the :T_ab: of (3.16) is defined with a parametrix or renormalisation that is not locally covariant under constant rescalings (i.e. that the paper's 'general local covariance' is meant with mu referred to the background), in which case the value holds under that explicit, narrower renormalisation condition and the grade becomes NARROWED with that condition named; or an argument that the late-time state is NOT the vacuum of (Omega^2 eta, m) (contradicting the paper's own state-convergence step), or that (3.16)'s late-time zero-momentum response contains a further term besides -8 alpha~^S_1 m^4 W that is nonzero for a constant rescaling. To OPEN: none -- every step of C1-C6 runs here. To STANDS outright: a demonstration that general local covariance with mu fixed on every spacetime gives (3.21) for the late region (Omega^2 eta, m); C4 shows it gives 0.",
"reverify_command": "python3 " + D + "/rederive/2604.01047_thm3.6.py   # expect 19 PASS lines and exit 0; C3b reproduces 1/(64pi^2) from (3.21), C4e/C4f/C5a show the covariant late-time value 0 and alpha~^S_1 = 0",
"report_path": D + "/audits/2604.01047_thm3.6.json"
}
json.dump(R, open(R["report_path"], "w"), indent=1)
print("written", R["report_path"])
