import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
W="/home/user/Claude-Method-Works/research/warp-drive"
r = {
"key": "1608.05687",
"name": "Gao-Jafferis-Wall traversable wormhole via a double-trace deformation (as used: per-use coupling 'except with a time delay'; footnote 2; non-achronality by an external causal path; teleportation identification)",
"source": {
 "located": "P. Gao, D. L. Jafferis, A. C. Wall, 'Traversable Wormholes via a Double Trace Deformation', arXiv:1608.05687v3 [hep-th], 24 Sep 2019 (journal: JHEP 12 (2017) 151, as cited by 1908.03273). Sections 1-5 and Appendix A (eqs A.1-A.14); the quoted flat-space paragraph is in sec. 5 (Discussion), footnote 2 in sec. 1.",
 "read_status": "READ",
 "via": "alphaXiv get_paper_content(fullText=true) of v3; saved verbatim to " + D + "/src/1608.05687.txt (flattened copy src/1608.05687.flat.txt). Whole main text, footnotes and appendix read; reference list skimmed. v3 postdates the JHEP version, so no journal-vs-preprint gap is open here."
},
"published_statement": "Abstract: 'After turning on an interaction that couples the two boundaries of an eternal BTZ black hole, we find a quantum matter stress tensor with negative average null energy, whose gravitational backreaction renders the Einstein-Rosen bridge traversable. Such a traversable wormhole has an interesting interpretation in the context of ER=EPR, which we suggest might be related to quantum teleportation. However, it cannot be used to violate causality.' The computed result is eq. (3.18): int_{U0}^inf dU T_UU = - h Gamma(2D+1)^2 / (2^{4D} (2D+1) Gamma(D)^2 Gamma(D+1)^2 l) * 2F1(1/2+D, 1/2-D; 3/2+D; 1/(1+U0^2)) / (1+U0^2)^{D+1/2}, 'for all D values from 0 to 1, the integral of T_UU is always negative', zero at D = 0. Sec. 1: 'In our configuration, signals from early times on the horizon can intersect it again at late times, by passing through the directly coupled boundaries. The causal structure of the manifold is modified as a result, changing the commutation relations along null geodesics through the wormhole and making them no longer achronal ... Hence the above impossibility results do not apply.' Footnote 2 (sec. 1): 'We do not consider the case of a time-independent interaction, in order to prevent the quantum state from becoming non-regular on the past horizon.' Sec. 5, flat-space paragraph (prose, no computation): 'It is interesting to consider what would happen if the two black holes were in the same component of space ... The direct boundary interaction could then be produced by propagation through the ambient spacetime -- this would be the same as the interaction we studied, except with a time delay. A similar calculation would then lead to a traversable wormhole. The negative ANE could be understood as coming from the Casimir effect associated to the cycle in space ... No causal paradoxes would arise because the traversability depends on backreaction due to the existence of a casual path between the black holes in the ambient spacetime. Since any infinite null geodesic which makes it through a wormhole must be chronal ..., such wormholes do not enable one to travel faster than light over long distances through space. Hence traversable wormholes are like getting a bank loan: you can only get one if you are rich enough not to need it.' Sec. 5 teleportation: 'This situation is somewhat analogous to what occurs in quantum teleportation ... Unlike the usual description of quantum teleportation, in our example it is essential that the channel between the left CFT, A, and the right CFT, B, is a quantum one ... we propose that the gravitational dual description of quantum teleportation understood as a dynamical process is that the qubit passes through the ER=EPR wormhole ...'",
"published_hypotheses": [
 "H1 background: eternal (two-sided) BTZ black hole, AdS3, l = 1, beta = 2 pi l^2/r_h; bulk scalar in the Hartle-Hawking / thermofield-double state (secs. 1-2). D > 3 'expected' but not computed (sec. 5).",
 "H2 coupling: relevant double-trace deformation dS = int dt d^{d-1}x h(t,x) O_R(t,x) O_L(-t,x), Delta < d/2, bulk field with the alternative (minus-sign) quantisation, slightly tachyonic M^2 > -(d/2)^2 (eq. 1.2, footnote 4 on p.4).",
 "H3 time dependence: h(t,phi) = h (2pi/beta)^{2-2D} for t >= t0, 0 for t < t0, uniform in phi (eq. 3.3); the case 'turned on at U0 and never shut off' is computed (Fig. 3.1a, eq. 3.18) and the on-off case U0..Uf as a difference (Fig. 3.1b, 3.2). Footnote 2 excludes only a time-independent interaction (on for all t).",
 "H4 perturbative: first order in h, one loop, large-N factorisation (eq. 2.9); linearised Einstein equation (1.3)-(1.5), with T_UU decaying faster than U^-2 (checked at late times, U^{-2D-2}).",
 "H5 regularity: the modified two-point function is chosen regular on the horizon; the global-mode construction reproducing (2.9) 'is very tricky' and 'we do not include it' (footnote 4 on p.6).",
 "H6 point-splitting / Hadamard subtraction unchanged by the boundary-condition change, so no effect at order h (sec. 3).",
 "H7 the flat-space (same-asymptotic-region) case, the Casimir reading, the no-faster-than-light 'bank loan' and the teleportation interpretation are discussion-section claims in prose, not derived; teleportation is 'suggest', 'propose', 'somewhat analogous'."
],
"hypothesis_drift": [
 "phase1.py:137-140 (and :400-402 CANDIDATES row, :482-483, :544-546): 'GJW: PER USE. Their own sentence closes it -- in flat space the coupling is carried by ambient propagation \"EXCEPT WITH A TIME DELAY\", so it is a signal you send every time, not a thing you build once.' ADDED inference attributed to the source. The quoted words are verbatim (sec. 5), but the source sentence says only HOW the flat-space coupling would be realised (ambient propagation) and that it carries a delay; it says nothing about per-use versus build-once, and it is followed by 'A similar calculation would then lead to a traversable wormhole' -- a prose expectation, not a computation. The per-use reading is the owner's (the canonical entry itself lists 'the owner reads except with a time delay as meaning per-use signalling'). Upstream the same attribution is made in amortize.py:43-50 ('closed by the paper rather than by an argument of mine'). What IS in the source and supports a narrower per-opening reading: the wormhole 'is only open for a small proper time in the interior region' and admits signals sent before dt ~ R ln(R/h L_planck) prior to the coupling (sec. 5) -- i.e. each coupling pulse opens one window.",
 "amortize.py:55-66 (read by phase1.py:146-148): 'THEY DECLINED THE STANDING COUPLING ... A channel held open continuously pays its propagation delay to ESTABLISH the standing state'. BROADENED relative to the source: GJW DID compute a coupling switched on at t0 and held ('turned on at U = U0 = 1 and never shut off', Fig. 3.1a caption; eq. 3.18 is exactly that case, int_{U0}^inf with no turn-off). Footnote 2 declines only a time-INDEPENDENT interaction, on for all t including t -> -inf, for past-horizon regularity of the TFD state. 'Established once, then held' is inside GJW's computed class; 'eternal' is what was declined.",
 "phase1.py:146-148: 'THE PROPERTY GJW'S FOOTNOTE 2 DECLINED TO CONSIDER: A TIME-INDEPENDENT CONFIGURATION.' WORDING DRIFT: the source says 'time-independent interaction' (the coupling h), not 'configuration'. A time-independent coupling is not the same object as a time-independent spacetime; GJW's geometry is time-dependent in every case they computed.",
 "amortize.py:86-87 ('the STANDING-COUPLING case is untested by anyone'): OUT OF DATE against later literature, not a drift from 1608.05687 itself -- the time-independent coupling case was constructed by Maldacena-Qi 2018 (1804.00491, 'eternal traversable wormhole', static, ground state of the coupled system) and realised with an ambient-exchange coupling in 4D asymptotically flat space by Maldacena-Milekhin-Popov 2018 (1807.04726). Recorded here because phase1's Theorem 5 inherits it via amortize.py.",
 "transit.py:11-13 and :276-277: 'The mechanism has a name -- QUANTUM STATE TELEPORTATION, and in the gravitational setting the Gao-Jafferis-Wall protocol'. HEDGE DROPPED and a stated difference DROPPED: the source 'suggest[s]' and 'propose[s]' the teleportation interpretation, calls it 'somewhat analogous', and states explicitly 'Unlike the usual description of quantum teleportation, in our example it is essential that the channel between the left CFT, A, and the right CFT, B, is a quantum one'. transit.py's model (transit.py:37-39, 138-145: two CLASSICAL bits, 'One pair, one transit') is the usual classical-channel description that GJW distinguish their mechanism from. transit.py computes nothing about GJW, so this is an identification drift only.",
 "anecscope.py:109-113: 'GJW make their geodesics non-achronal with an EXTERNAL causal path' and 'the SAME escape Casimir uses'. NO DRIFT on the first clause (source sec. 1, 'by passing through the directly coupled boundaries ... making them no longer achronal'); the Casimir comparison is GJW's own ('similar to the Casimir effect, since the interaction between the boundaries implies that the radial direction is effectively a compact circle', sec. 1). The owner does not state H1-H2 (AdS boundaries, double-trace coupling); that is an omission of context, not a change of claim."
],
"data_at_publication": [
 {"quantity": "numerical physical inputs to GJW's conclusion (sign of int T_UU, eq. 3.18)", "value_then": "none: the result is a closed-form function of the operator dimension Delta in (0,1), the turn-on U0 and the dimensionless coupling h; no measured constant enters", "value_now": "none", "source_now": "n/a", "moves_conclusion": "no -- there is no datum to move; the conclusion is a computation under H1-H6"},
 {"quantity": "L_planck in the traversal window dt ~ R ln(R/(h L_planck)) (GJW sec. 5; used by amortize.py:26-31)", "value_then": "GJW give the formula symbolically; the tree uses 1.616255e-35 m (CODATA 2018)", "value_now": "1.616255(18)e-35 m (CODATA 2022, unchanged)", "source_now": "CODATA 2022 recommended values (Mohr et al., arXiv:2409.03787)", "moves_conclusion": "no -- recomputed 2.6722e-7 s (R = 1 m), 2.9026e-4 s (1 km), 3.1330e-1 s (1000 km), agreeing with amortize.py to 4 figures; the log makes the window insensitive to L_planck in any case"}
],
"rederivation": {
 "method": "sympy",
 "script_path": D + "/rederive/1608.05687.py",
 "outcome": "ALL PASS (run 2026-09-26, 26 s). (1) sympy: -4 h Delta C0 times the (A.10) prefactor equals the (3.18) prefactor identically (ratio 1; numeric ratios 1 to 6e-16 at Delta = 0.1, 0.37, 0.5, 0.83), with C0 = sin(pi Delta)/(2^{2Delta+1} pi^2) once beta = 2 pi/r_h -- the printed closed form follows from the appendix. (2) (A.14) is Gauss's second summation theorem; verified to 1e-12 at five Delta. (3) The closed form (A.10) was checked against an independent direct numerical evaluation of the triple integral in (A.9) (the step before all hypergeometric identities): Delta=0.2,U0=1: 0.66920355 vs 0.66920355 (rel -9e-13); Delta=0.4,U0=1: 0.51145883 both; Delta=0.6,U0=2: 0.19751668 both (rel -5e-10); Delta=0.8,U0=1: 0.8475805 both (rel +2e-10). The appendix's chain (A.9)->(A.10), including (A.11)-(A.13), is therefore numerically confirmed end to end. (4) (3.18) < 0 for h > 0 at every Delta in 0.01..0.99 and U0 in {0.1,1,2,10}; -> 0 as Delta -> 0 (-7.9e-17 at Delta = 1e-8), as the paper says; |ANE| larger for earlier turn-on (U0=1 vs 2), as the paper says; the on-off case U0=1,Uf=2 stays negative. (5) the tree's window table (amortize.py) reproduces. NOT checked (and not checkable here in finite form): the one-loop two-point function (2.9), the horizon-regular global-mode choice of footnote 4 (not published by the authors), the linearised Einstein step (1.3)-(1.5), and every sec. 5 flat-space / bank-loan / teleportation claim, which are prose.",
 "agrees_with_source": "yes"
},
"later_literature": [
 {"ref": "arXiv:1804.00491 Maldacena & Qi, 'Eternal traversable wormhole' (2018)", "effect": "extends", "what": "Constructs the case GJW's footnote 2 declined: a time-independent boundary coupling S_int = g sum int du O_L O_R in nearly-AdS2 gives 'a traversable wormhole that is static and time independent, an eternal traversable wormhole' (p.2), as the ground state of the coupled system (close to the TFD; sec. 4.3-4.4). Sec. 6 / Fig. 23 proposes the coupling 'can arise by integrating out the field modes' of the ambient space between two near-extremal black holes. Bears directly on the tree: the standing-coupling case is not 'untested by anyone' (amortize.py:86-87), and a coupling-supported wormhole is not intrinsically per-use.", "read_status": "READ (alphaXiv answer_pdf_queries: pp. 1-8, 14, 20, 22, 28, 52-54 returned)"},
 {"ref": "arXiv:1807.04726 Maldacena, Milekhin & Popov, 'Traversable wormholes in four dimensions' (2018)", "effect": "extends", "what": "A static, long-lived (metastable; lifetime ~ d^3/(q^2 l_p^2) from EM radiation of the orbiting mouths) traversable wormhole in 4D asymptotically flat Einstein-Maxwell plus massless charged fermions; negative Casimir-like energy of fermions on the cycle through the wormhole and ambient space; 'this interaction is generated automatically by the exchange of massless fields in the bulk' (p.4) -- GJW's sec. 5 flat-space remark realised as a STANDING coupling. It is 'a long wormhole that does not lead to causality violations': pi l > d in all cases, slope ~2.35 at large d (p.19, Fig. 7). So the reusable, time-independent GJW-class entry exists; and it is slower than the ambient path, consistent with GJW's bank loan.", "read_status": "READ (alphaXiv answer_pdf_queries: abstract, pp. 3-5, 13-25, 27)"},
 {"ref": "arXiv:1908.03273 Fu, Grado-White & Marolf, 'Traversable asymptotically flat wormholes with short transit times' (2019)", "effect": "narrows", "what": "Perturbative flat-space wormholes (Z2 quotient, cosmic strings, Hartle-Hawking state) with t_min transit = d + logs, so t/d -> 1: approaching but not beating the ambient path, consistent with GJW's no-faster-than-light statement. Footnote 8: in a 4D asymptotically flat spacetime of mass M > 0 the Shapiro delay has an IR log divergence, so 'it is difficult to use arguments about causal curves connecting distant points to rigorously bound wormhole transit times' -- GJW's 'bank loan' is a heuristic whose rigorous 4D form is itself open; also traversability there is 'exponentially fragile'.", "read_status": "READ (alphaXiv answer_pdf_queries: abstract, pp. 1-6, 13-18)"},
 {"ref": "discover_papers hits (2502.03531, 2304.07356, 2511.09815, 2605.05011, 2603.26051, 2606.12528)", "effect": "extends", "what": "Further GJW-type constructions (non-local double trace / Janus, Kerr, AdS5 black brane gravitational channels, fermionic double trace) and a 2026 quantum-channel-capacity formulation of the GJW protocol; none contradicts eq. (3.18).", "read_status": "NAMED-NOT-READ (abstracts only, from the discovery listing)"}
],
"lacked_data": "M's hypothesis tested for this result. What GJW had (2016): the BTZ two-point function with alternative quantisation, the KMS/TFD structure, the linearised Einstein equation; no measured constants enter. What came later: (a) the time-independent coupling analysis (Maldacena-Qi 2018) -- the case their footnote 2 set aside; (b) a concrete flat-space realisation with an ambient-exchange, standing coupling (MMP 2018); (c) flat-space perturbative transit times (FGWM 2019). Does having it change GJW's conclusion? NO, on the evidence: (3.18) is re-derived here from their own appendix and confirmed numerically; the eternal and flat-space cases EXTEND rather than contradict it; and the later explicit flat-space constructions obey GJW's no-shortcut claim (MMP pi l > d; FGWM t/d -> 1 from above up to logs), with FGWM noting the rigorous 4D bound is harder to state than GJW's sentence suggests (IR-divergent Shapiro delay). So the physicists here did not lack a datum that overturns their result. What the later data DO change is the TREE's reading, not GJW: the per-use/not-reusable status the tree attributes to 'their own sentence' is not in the sentence, and the standing-coupling case the tree calls 'untested by anyone' was tested in 2018 and gives a static, reusable (metastable) wormhole -- which still carries no speed advantage, so the tree's ultimate refusal (no lead through a GJW-class channel) is corroborated while its stated reason is narrowed.",
"grade": "NARROWED",
"grade_evidence": "The source result itself STANDS: eq. (3.18) follows from the appendix (sympy prefactor identity, ratio exactly 1), the appendix chain (A.9)->(A.10) agrees with direct triple-integral quadrature to <= 1e-9 at four (Delta,U0) points, the sign is negative on the whole grid 0<Delta<1 and zero at Delta=0, and no datum enters. The grade is NARROWED because the tree uses the paper on a larger or different class than the paper states: (i) phase1.py:137-140/400-402/544-546 (via amortize.py:43-50) attributes 'PER USE ... CLOSED by the source' to the sentence 'except with a time delay', which states only how a flat-space coupling would be realised -- the per-use reading holds for GJW's pulsed protocol as computed (one opening per coupling pulse, sec. 5) and is not a statement of the source; (ii) amortize.py:55-66, inherited by phase1.py:146-148, says GJW 'declined the standing coupling', whereas GJW computed the switched-on-and-held coupling (Fig. 3.1a, eq. 3.18) and declined only the eternal (time-independent) interaction, and wrote 'interaction' where phase1 writes 'configuration'; (iii) the declined case was later constructed (1804.00491, 1807.04726) and is static and reusable, so 'GJW double-trace coupling ... reusable False' (phase1.py:400-402) holds for the 2016 protocol, not for the GJW class; (iv) transit.py:11-13 identifies GJW with quantum-state teleportation, dropping GJW's hedge and their explicit statement that their channel, unlike usual teleportation, must be quantum. None of this is WRONG in the sense of a computed contradiction: the tree's bottom line (no lead) is corroborated by MMP (pi l > d) and FGWM (t/d -> 1). anecscope.py:109-113 matches the source.",
"what_would_change_the_grade": "To STANDS: the tree restricting its GJW statements to the protocol as computed (pulsed coupling, BTZ/AdS boundaries, first order in h) and marking 'per use' as its own inference from sec. 5 rather than the source's, with footnote 2 quoted as 'time-independent interaction' and the step-on-held case of Fig. 3.1a acknowledged; and transit.py carrying GJW's 'propose'/'quantum channel' qualifiers. To WRONG (for the tree's use): a construction in which a coupling-supported flat-space wormhole, once established, yields transits shorter than the ambient light time at long distance -- none is known; FGWM approach t/d -> 1 from above and MMP have t/d > 2. For the source result itself: an independent error in the one-loop two-point function (2.9) or in the unpublished horizon-regular mode choice of footnote 4, which this audit could not check.",
"reverify_command": "python3 " + D + "/rederive/1608.05687.py && grep -c -F -e 'except with a time delay' -e 'We do not consider the case of a time-independent interaction' -e 'never shut off' -e 'Unlike the usual description of quantum teleportation' " + D + "/src/1608.05687.flat.txt && sed -n '137,148p;400,402p' " + W + "/phase1.py && sed -n '52,66p;84,88p' " + W + "/amortize.py && sed -n '9,13p' " + W + "/transit.py",
"report_path": D + "/audits/1608.05687.json"
}
json.dump(r, open(D + "/audits/1608.05687.json", "w"), indent=1, ensure_ascii=False)
print("ok")
