import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "schwarzschild-radius",
 "name": "Schwarzschild radius r_s = 2GM/c^2",
 "source": {
  "located": "K. Schwarzschild, Sitzungsber. Preuss. Akad. Wiss. Berlin 1916, 189-196; English translation Antoci & Loinger, arXiv:physics/9905030 (posted 1999-05-12). The constant alpha of eq.(14) is identified with 2GM/c^2 through the Newtonian limit (Sec.6).",
  "read_status": "NAMED-NOT-READ",
  "via": "NOT READ IN THIS STAGE: every alphaXiv call (answer_pdf_queries x3, get_paper_content x1, discover_papers x1) returned 'alphaXiv assistant quota exceeded', and arxiv.org, ar5iv.labs.arxiv.org, export.arxiv.org, de.wikisource.org, semanticscholar and inspirehep are refused by the egress proxy (403 CONNECT). A sibling DOCKET 67 stage READ physics/9905030 pp.1-7 this pass (audits/schwarzschild-1916.json) and records eq.(14) 'contains only the constant alpha that depends on the value of the mass at the origin' and Sec.6 'alpha/r is nearly equal to twice the square of the velocity of the planet'; those quotes are carried here as that stage's reading, not this one's. The statement r_s = 2GM/c^2 is therefore rested here on COMPUTATION, not on the citation: it is re-derived from the vacuum Einstein equations and matched to Newton three independent ways (rederive R1-R2), including the exact identity C/r = 2v^2/c^2 that the sibling-quoted Sec.6 sentence states approximately. The G value rests on CODATA 2022 (arXiv:2409.03787), READ by the sibling stage audits/si-astro-constants-c-g-msun-ly.json, not re-read here."
 },
 "published_statement": "As recorded from physics/9905030 by the sibling stage (not re-read here): eq.(14) ds^2 = (1 - alpha/R) dt^2 - dR^2/(1 - alpha/R) - R^2 dOmega^2, 'the latter contains only the constant alpha that depends on the value of the mass at the origin'; Sec.6 'alpha/r is nearly equal to twice the square of the velocity of the planet' (units c = 1), which with v^2 = GM/r gives alpha = 2GM/c^2. Textbook form as the tree uses it: r_s = 2GM/c^2, the areal radius of the horizon of the Schwarzschild solution of mass M.",
 "published_hypotheses": [
  "classical general relativity (Einstein field equations) holds",
  "vacuum R_mn = 0 outside the origin (1916: 'everywhere, with the exception of the point x1 = x2 = x3 = 0'; horizon reading: the mass lies inside r_s)",
  "static (1916 condition 1) and no time-space cross terms (condition 2)",
  "spherical symmetry (condition 3) -- hence non-rotating; uncharged (no electromagnetic stress-energy)",
  "asymptotic flatness (condition 4)",
  "M is the mass seen in the far-field Newtonian limit (Kepler / free-fall), with alpha > 0 taken physically, not derived",
  "the horizon interpretation of r = alpha is post-1916 (Lemaitre 1933 and later; Schwarzschild's chart covers R > alpha only, per the sibling reading)"
 ],
 "hypothesis_drift": [
  "IMPLICIT, NOT DROPPED -- STATIC vs QUASI-STATIC (canonical entry hypothesis 'Schwarzschild (static, uncharged, non-rotating) black hole of the payload mass'; warpfolder.py:42-44, 297-298): a 100 kg hole is not static -- the tree's own hawking_lifetime_s gives 8.41e-11 s (warpfolder.py:305-307, pinned at :538). The formula survives as an ADIABATIC approximation: lifetime / light-crossing time r_s/c = 1.70e23 at 100 kg (rederive R7). The quasi-static hypothesis is carried silently by the entry; it holds by 23 decades and moves nothing, but it is a hypothesis and is named here.",
  "DROPPED, NOT LOAD-BEARING -- CLASSICAL GR AT r_s ~ 1e-25 m: at 100 kg the curvature scale hbar c/r_s = 1.33e9 GeV, five decades above any tested energy, and the mass is ~28 decades below the lightest observed black hole. Gravitational-EFT corrections scale as (l_P/r_s)^2 = 1.18e-20 (r_s = 9.19e9 l_P; rederive R7), so nothing inside GR+EFT moves r_s; but GR at this scale is an EXTRAPOLATION, and the entry states none of this. The tree uses r_s only to reproduce the document's arithmetic (warpfolder.py:42-44 'That is not where it fails'), so the dropped hypothesis bears no conclusion.",
  "SEMANTIC, NOT A DRIFT OF THE FORMULA -- 'radius' is AREAL: r_s is the r at which g_tt = 0 = g^rr, with proper circumference 2 pi r; proper radial distance is not r (r_s -> 2 r_s is 2.2956 r_s; rederive R3). warpfolder.py uses 'r_s/m' as a length (:375-379) for a table, correctly as an areal length; no conclusion uses a proper distance.",
  "HYPOTHESIS AS STATED IS NARROWER THAN NEEDED, NOT WIDER: the entry restricts to uncharged, non-rotating. Over the Kerr-Newman family the outer horizon r_+ and its areal radius sqrt(r_+^2 + a^2) = sqrt(2 m r_+ - q^2) are both <= 2GM/c^2 (equality iff a = q = 0), and r_+ is homogeneous of degree 1 in (M, a, q) (rederive R4). So the proportionality 'r proportional to M' that warpfolder.py:42 calls 'ARITHMETICALLY CORRECT' survives dropping 'static, uncharged' at fixed a/M, Q/M; only the coefficient 2 becomes an upper bound.",
  "DATA-LABEL CONFLATION IN THE CANONICAL ENTRY, NOT IN THE OWNER: data_used lists 'r_s(5000 kg) = 7.42e-24 m' and 'r_s(1e5 kg) = 1.48e-22 m'. Those are the DOCUMENT's printed values (warpfolder.py:495-500 'matches the document's ...'), not the formula's: 2GM/c^2 gives 7.42616e-24 and 1.48523e-22. The owner's prose value at warpfolder.py:43 ('1.485e-25 m at 100 kg') is the computed one, correct to 4 s.f."
 ],
 "data_at_publication": [
  {"quantity": "G (Newtonian constant)",
   "value_then": "1916: not used numerically in the 1916 derivation (alpha appears as a free constant fixed by the Newtonian limit); the tree uses 6.67430e-11 m^3 kg^-1 s^-2 (ladder.py:54, imported at warpfolder.py:187)",
   "value_now": "6.67430(15)e-11, u_r = 2.2e-5 (CODATA 2018 = CODATA 2022); CODATA 2014 6.67408e-11",
   "source_now": "CODATA 2022, arXiv:2409.03787 Table XXXII, READ by sibling stage audits/si-astro-constants-c-g-msun-ly.json; CODATA 2014 value as quoted in IAU 2015 Res. B3 (arXiv:1510.07674), same sibling reading",
   "moves_conclusion": "no -- r_s is linear in G: +-1 sigma shifts r_s(100 kg) by +-2.25e-5 relative, the 2014 value by -3.30e-5; the printed-vs-computed agreement (tolerance 5e-3, warpfolder.py:492-500) is unchanged under every move (rederive R6)"},
  {"quantity": "c",
   "value_then": "tree: 2.99792458e8 m/s (ladder.py:53)",
   "value_now": "299792458 m/s exact (SI 2019)",
   "source_now": "CODATA 2022 arXiv:2409.03787 Table XXXII (sibling reading)",
   "moves_conclusion": "no -- exact; identical"},
  {"quantity": "r_s at the document's three payloads (100, 5000, 1e5 kg; warpfolder.py:220)",
   "value_then": "document prints 1.48e-25, 7.42e-24, 1.48e-22 m",
   "value_now": "computed 1.485232e-25, 7.426160e-24, 1.485232e-22 m (rel. diff of printed: -3.52e-3, -8.30e-4, -3.52e-3)",
   "source_now": "computed in rederive/schwarzschild-radius.py R5",
   "moves_conclusion": "no -- all within the tree's 5e-3 tolerance, so PROPORTIONALITY_ARITHMETIC_IS_CORRECT stands. RECORDED DISCREPANCY (not an error, and not repaired): 3-s.f. ROUNDING would print 1.49e-25, 7.43e-24, 1.49e-22; the printed figures are 3-s.f. TRUNCATIONS with exact c, and so are the document's E = Mc^2 figures 8.98e18 and 4.49e20 (rounding would give 8.99e18). An alternative (G = 6.674e-11, c = 3e8, rounded) reproduces the printed r_s but gives E(100 kg) = 9.00e18, not 8.98e18, so truncation is the one rule consistent with all five printed cells; truncation also reproduces the mantissa 8.98 of the 1e5 kg E cell the tree flags (warpfolder.py:505-515), whose exponent is the slipped part. The 100 kg and 1e5 kg cells sit at 70% of the tolerance (3.52e-3 of 5e-3): a thin margin, not a failure."}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/schwarzschild-radius.py",
  "outcome": "ALL AS RECORDED, exit 0. R1: general static spherical metric -e^{2a}dt^2 + e^{2b}dr^2 + r^2 dOmega^2; G^t_t = 0 solved by dsolve gives e^{-2b} = 1 - C/r with C free; G_rr + (g_rr/g_tt)(-G_tt) = 2(a' + b')/r, so a = -b under asymptotic flatness; the resulting form is vacuum (G_ab = 0) for every real C. R2: C = 2GM/c^2 three independent ways -- (i) far-field slow-particle acceleration -c^2 Gamma^r_tt -> -(C c^2/2)/r^2; (ii) circular geodesics give Omega^2 = C c^2/(2 r^3) EXACTLY, so Kepler III fixes C, and C/r = 2 v^2/c^2 exactly (the 1916 Sec.6 'alpha/r ~ 2v^2' as recorded by the sibling reading); (iii) Misner-Sharp mass = C/2. R3: horizon g_tt = 0 = g^rr only at r = C; r is areal. R4: Kerr-Newman r_+ and areal radius <= 2m (identity r_+^2 + a^2 = 2 m r_+ - q^2; 2000 random sub-extremal points), r_+ homogeneous of degree 1. R5: r_s(100 kg) = 1.485232e-25 m, matching warpfolder.py:43's '1.485e-25'; printed figures are truncations, within tolerance. R6: G sensitivity <5e-5. R7: 100 kg is 4.6e9 M_P, r_s = 9.19e9 l_P, tau = 8.411e-11 s (agrees with warpfolder.py:538), tau/(r_s/c) = 1.70e23, T_H = 1.23e21 K. Independently, python3 warpfolder.py --selftest prints [ok] on the three r_s rows (1.485232053823733e-25, 7.426160269118664e-24, 1.485232053823733e-22) and on 'so the proportionality arithmetic IS correct'.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "discover_papers call for later literature", "effect": "contested",
   "what": "NOT RUN: returned 'alphaXiv assistant quota exceeded'. No later literature was read in this stage. The entries below are named, not read, and none is used to support the grade.",
   "read_status": "NOT-RUN (tool quota)"},
  {"ref": "Hamilton & Lisle, 'The river model of black holes', arXiv:gr-qc/0411060", "effect": "extends",
   "what": "per the sibling stage's reading: Gullstrand-Painleve form with infall velocity sqrt(2GM/r) reaching c at r = 2GM/c^2 -- the horizon reading of r_s in a chart regular across it",
   "read_status": "READ by sibling stage (audits/schwarzschild-1916.json), not by this stage"},
  {"ref": "Antoci & Liebscher / Antoci, 'Reinstating Schwarzschild's original manifold and its singularity', arXiv:gr-qc/0406090; Loinger, astro-ph/0001453", "effect": "contested",
   "what": "a minority reading that r = alpha is Schwarzschild's 'origin' rather than a horizon; interpretive of the manifold, does not touch the value 2GM/c^2 and does not touch the tree's arithmetic use",
   "read_status": "NAMED-NOT-READ (titles only, via a web search result list)"}
 ],
 "lacked_data": "M's hypothesis, tested for this result. What the authors had: in 1916 alpha is a free integration constant whose value is fixed by the Newtonian limit, so no measured datum enters the FORM 2GM/c^2; the numerical value needs only G and c. What came later: G's value (tree uses CODATA 2018 = 2022, 6.67430(15)e-11) and c fixed exactly (SI 2019). Computed effect: moving G by +-1 sigma or to the 2014 value shifts r_s by <= 3.3e-5 relative, two decades inside the tree's 5e-3 comparison tolerance -- the conclusion does not move (rederive R6). The data genuinely LACKED, then and now: no black hole anywhere near 100 kg has been observed, and GR has not been tested at curvature radii ~1e-25 m (energy scale 1.33e9 GeV). Evidence either way on whether that gap could matter: within GR the Schwarzschild family is exactly scale-free in M (C enters only as a length), and the leading EFT corrections scale as (l_P/r_s)^2 = 1.2e-20; beyond-GR modifications at that scale are not excluded by any data read here and are OPEN, but they could only change the physics of an actual 100 kg hole, not the arithmetic the tree uses r_s for. So for the result AS THE TREE USES IT, having the missing data would not change the conclusion; for r_s as a physical horizon radius at 100 kg, the extrapolation is a named hypothesis, not a measurement.",
 "grade": "STANDS",
 "grade_evidence": "As the tree uses it -- r_s = 2GM/c^2 evaluated at 100, 5000 and 1e5 kg to confirm that the Warp-folder document's proportionality arithmetic is correct (warpfolder.py:42-44, 297-298, 491-502) -- the result is re-derived from the vacuum Einstein equations and identified with the Newtonian mass three independent ways (rederive R1-R2), the tree's value 1.485e-25 m is exact to 4 s.f., and no moved datum moves it (G shifts < 5e-5, R6). The tree's own selftest agrees. Recorded, not repaired, none moving the grade: (1) quasi-static, not static -- the 100 kg hole lives 8.41e-11 s, 1.7e23 light-crossing times (R7), a hypothesis the entry carries silently; (2) classical GR at r_s ~ 1e-25 m is an extrapolation (named, not load-bearing for arithmetic); (3) the canonical data_used labels two DOCUMENT-printed values as r_s values (7.42e-24, 1.48e-22 vs computed 7.426e-24, 1.485e-22); (4) the document's printed figures are 3-s.f. truncations, not roundings -- a discrepancy of presentation, inside the tree's tolerance at 70% of it; (5) the stated hypothesis (uncharged, non-rotating) is narrower than the use needs -- over Kerr-Newman the linear scaling survives and 2GM/c^2 is an upper bound (R4). SOURCE CAVEAT: this stage could not READ physics/9905030 (alphaXiv quota exhausted, arXiv mirrors blocked); the grade rests on computation plus the sibling stage's READ of the same source and of CODATA 2022, not on a reading made here.",
 "what_would_change_the_grade": "To OPEN: none on the physics side -- the statement is closed-form and re-derived here; only an insistence that the grade require this stage's own reading of physics/9905030 would move the SOURCE status (it would not move the computation). To NARROWED: a use elsewhere in the tree that treats r_s as a proper distance, as the horizon of a rotating/charged or non-vacuum object with coefficient exactly 2, or as a static object over times comparable to 8.4e-11 s at 100 kg. To WRONG: a computed contradiction of R1-R2 (none exists: sympy returns every residual 0) or a printed r_s outside the 5e-3 tolerance (the worst is 3.52e-3). A future direct reading of physics/9905030 that shows alpha identified otherwise than via the Newtonian limit would change the attribution text, not the formula.",
 "reverify_command": "python3 " + D + "/rederive/schwarzschild-radius.py && (cd /home/user/Claude-Method-Works/research/warp-drive && python3 warpfolder.py --selftest | grep -E 'r_s\\(|proportionality')",
 "report_path": D + "/audits/schwarzschild-radius.json"
}
json.dump(rep, open(D + "/audits/schwarzschild-radius.json", "w"), indent=1)
print("written")
