import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
SRC = D + "/src/casmag/all"
R = {
"key": "teleportation-no-cloning-no-signalling",
"name": "Quantum teleportation: a move not a copy, channel consumed, no substance, does not beat light (transit.py) -- merged with teleportation-no-cloning",
"source": {
 "located": "Primary classics, none on arXiv: Bennett, Brassard, Crepeau, Jozsa, Peres, Wootters, PRL 70, 1895 (1993) [teleportation]; Wootters & Zurek, Nature 299, 802 (1982) and Dieks, Phys. Lett. 92A, 271 (1982) [no-cloning]; Eberhard, Nuovo Cim. B 46, 392 (1978) and Ghirardi-Rimini-Weber, Lett. Nuovo Cim. 27, 293 (1980) [no-communication]. Read through exact restatements: (i) Pirandola, Eisert, Weedbrook, Furusawa, Braunstein, 'Advances in quantum teleportation', arXiv:1505.07831v1 (2015), p.1 ('The Basics of Quantum Teleportation' A) and p.2 (Fig. 1 caption and text), p.5 (distance records); (ii) Scarani, Iblisdir, Gisin, Acin, 'Quantum cloning', RMP 77, 1225 (2005), arXiv:quant-ph/0511088v1, p.2 (scope), p.3 Sec. I.B (statement and proof), p.30 (teleportation and no-cloning); (iii) Peres & Terno, 'Quantum information and relativity theory', RMP 76, 93 (2004), arXiv:quant-ph/0212023v2, pp.8-9 Sec. II.E eqs.(9)-(11) and the 'no closed causal loops' assumption; (iv) Bennett, DiVincenzo, Shor, Smolin, Terhal, Wootters, 'Remote State Preparation', arXiv:quant-ph/0006044v5, pp.1-2 (the KNOWN-state clause).",
 "read_status": "READ-VIA-RESTATEMENT",
 "via": "In this run the live alphaXiv tools (answer_pdf_queries on 1505.07831 and quant-ph/0511088, get_paper_content fullText, discover_papers) all returned 'assistant quota exceeded'. The quoted text is therefore alphaXiv page text that earlier D67 runs fetched, harvested from session transcripts by src/casmag/allpages.py and read from disk here: " + SRC + "/1505.07831v1.txt (md5 8bee2676dbc4ca8ad75a0d6c434a122f; pages 1,2,3,4,5,7,11,12,13), " + SRC + "/quant-ph_0511088v1.txt (md5 6aff8e226aac1eb82fba5632312c3982; pages 1,2,3,4,7,30,32), " + SRC + "/quant-ph_0212023v2.txt (pp.8-10), " + SRC + "/quant-ph_0006044v5.txt (pp.1-2). Every quotation below was re-read from those files in this run. Bennett 1993, Wootters-Zurek 1982, Dieks 1982, Eberhard 1978 and GRW 1980 are NAMED-NOT-READ. The sibling audits quant-ph_bennett-1993-teleportation, no-cloning-theorem, no-communication-theorem, teleportation-two-classical-bits, entanglement-consumed-locc-monotonicity and teleportation-transfers-state-not-matter audit the components one by one; this audit grades the four flags jointly as R11 and M-S1A-P5 consume them."
},
"published_statement": "TELEPORTATION (1505.07831 p.1, restating ref. 2 = Bennett et al. 1993): 'an unknown quantum state of a physical system is measured and subsequently reconstructed or \"reassembled\" at a remote location (the physical constituents of the original system remain at the sending location). This process requires classical communication and excludes superluminal communication. Most importantly, it requires the resource of quantum entanglement.' Protocol (pp.1-2): Alice and Bob 'share two qubits, A and B, prepared in a pure entangled state. In the ideal case, this is taken to be maximally entangled ... Alice is given another qubit a whose state rho is unknown. She then performs ... Bell detection, which projects her qubits a and A into one of the four Bell states ... the state of Alice's input qubit has been collapsed by measurement while Bob's qubit B is simultaneously projected onto P_k^dag rho P_k ... Alice communicates the classical outcome k ... to Bob, who then applies P_k to recover the original input state rho. Note that Alice's input state is assumed to be unknown, otherwise the protocol reduces to remote state preparation.' Fig. 1: output 'an exact replica of Alice's input state in the ideal case (F = 1)'. p.2: 'classical teleportation' (measure-prepare, no entanglement) 'has the maximum fidelity F_class = 2/3'. NO-CLONING (quant-ph/0511088 p.3): 'No-cloning theorem: No quantum operation exists that can duplicate perfectly an arbitrary quantum state', proved from linearity of the trace-preserving CP map ('So (2) may hold for states of an orthonormal basis, but cannot hold for all states'); p.2: cloning 'can be done perfectly and with probability 1 if and only if a basis to which psi belongs is known'; p.30: teleportation (Bennett et al. 1993): 'the original has to be destroyed in the process and the Bell-state measurement should not provide any information of the state to be teleported, otherwise there would be a contradiction with the no-cloning theorem (more precisely, with the optimal asymmetric cloning result ...)'. NO-SIGNALLING (quant-ph/0212023 pp.8-9): '[A_mu_m, B_nu_n] = 0 (9)' is 'a sufficient condition that no instantaneous information transfer can result from a distant intervention'; with sum_mu E_mu = 1 'all expressions involving Alice's operators A_mu_m have totally disappeared'; p.9: 'we assume that there are no closed causal loops'. KNOWN STATE (quant-ph/0006044 p.1): 'Remote state preparation (RSP) has the same goal, but the sender knows classically what state is to be transmitted ... the asymptotic classical communication cost of RSP is one bit per qubit'; p.2: 'it is also necessary by causality'.",
"published_hypotheses": [
 "P1 UNKNOWN input state (1505.07831 p.2); a known state reduces to remote state preparation (quant-ph/0006044 p.1)",
 "P2 a pure, ideally MAXIMALLY entangled pair previously shared between sender and receiver (1505.07831 p.1)",
 "P3 a complete four-outcome Bell detection and a classical channel carrying the outcome k (2 bits per qubit, d^2 signals for dimension d) to the receiver (1505.07831 pp.1-2)",
 "P4 the ideal case: F = 1 only with ideal resource and operations; with decoherence F < 1, and F_class = 2/3 is reachable with no entanglement at all (1505.07831 p.2)",
 "P5 no-cloning: LINEAR (trace-preserving CP) evolution, PERFECT (F = 1, probability 1) copies, an ARBITRARY input set containing non-orthogonal states (quant-ph/0511088 pp.2-3); 'if chronology is respected' (Ahn et al. arXiv:1207.6062 p.1)",
 "P6 no-signalling: linear CP maps in Kraus form, NON-SELECTIVE interventions (sum_mu E_mu = 1), commuting local operations [A,B] = 0 as a SUFFICIENT condition, and 'no closed causal loops' (quant-ph/0212023 pp.8-9)",
 "P7 the '<= c' of the classical channel is relativistic causality of the carrier, not part of any of these theorems ('excludes superluminal communication' is the teleportation statement; the speed limit itself is audited separately under relativistic-causality-signals-at-most-c)",
 "P8 the physical constituents of the input stay at the sender; the receiver's system must already be present (1505.07831 p.1)"
],
"hypothesis_drift": [
 "RETAINED (correctly): specthm.py:1188-1190 (hypothesis H_tele) and the statement at specthm.py:1205-1206 ('IF it is carried by teleportation as an unknown quantum state') keep P1. ledger.py:1376-1377 keeps it in the row's last column. specthm.py:1212-1213 ('A KNOWN state can be re-prepared rather than teleported') correctly marks where P1 fails.",
 "DROPPED -- exact fidelity (P4, and P5's 'perfect'): specthm.py:1186-1187 records 'the fidelity is not yet fixed', but specthm.py:1207-1209 binds IT_IS_A_MOVE_NOT_A_COPY and CHANNEL_IS_CONSUMED_BY_USE unconditionally, and both are exact only at F = 1. Computed: a Buzek-Hillery cloner followed by exact teleportation of one copy leaves Alice a 5/6 copy while Bob receives 5/6 (rederive H2). Measure-and-prepare reaches the average F = 2/3 with no ebit consumed (rederive H3). transit.py:24-28, :213-224 ('you could not hold it open if you wanted to') carry no fidelity qualifier.",
 "DROPPED -- linear, chronology-respecting quantum mechanics (P5, P6): no owner site names it. transit.py:30-33 and :231-232 say 'no-cloning enforced by the protocol'; ledger.py:1365-1370 quotes the flags with no hypothesis in its question column. The board holds CTCs open (latticectc.py:109 O3_CLOSED = False). Peres-Terno p.9 assumes 'no closed causal loops' (READ). Ahn et al. arXiv:1207.6062 p.1 (READ) show a Deutsch-CTC cloner exceeding the no-cloning bound. Gisin's theorem, restated in arXiv:2412.20854 (READ), says nonlinear dynamics signals (rederive H5 is a toy illustration).",
 "WEAKENED -- non-selectivity (P6): transit.py:17-18 and :176 claim 'EVERY operation A can perform', but the code tests unitaries only (transit.py:100-104, 40 in the selftest :318). A selective (post-selected) outcome does move B's conditional state (rederive H1). It carries no signal, because B cannot select without the outcome, but the sentence drops the hypothesis.",
 "WEAKENED -- maximal resource (P2): transit.py:37-38 'EXACTLY I/2' holds only for a maximally entangled pair. For cos t|00>+sin t|11>, B's state with the bits withheld is diag(cos^2 t, sin^2 t): still psi-free, so no signal, but not I/2 (rederive H4).",
 "ADDED/UNNAMED -- the KNOWN-state clause (specthm.py:1212-1213): 'the channel is not consumed' is right for re-preparation from a classical description (0 ebits). It silently needs that description to be FINITE: a finite alphabet, or a stated precision. Computed covering bound: >= log2(1/eps) bits at infidelity eps, unbounded as eps -> 0 (rederive K). Those bits still travel at <= c. The RSP route (quant-ph/0006044 p.1) instead spends 1 bit + 1 ebit, and there the channel IS consumed.",
 "BY CONSTRUCTION -- BEATS_LIGHT: transit.py:145-146 defines arrival_time(D) = D/C_SI, so advantage_over_light is D/c - D/c identically, and the selftest at transit.py:346-348 cannot fail. The source statement ('excludes superluminal communication') plus P7 is what makes it true. The tree's own ledger row D23 calls it 'ZERO BY CONSTRUCTION', which is correct. transit.py:44 and :249 ('provably') overstate this."
],
"data_at_publication": [
 {"quantity": "Earth-Proxima distance (ledger.PROXIMA_LY via foliation.py:583; transit.py:143 uses 4.0175e16 m)", "value_then": "4.2465 ly (seated; Gaia DR3 1/parallax 768.0665 mas = 4.24646 ly)", "value_now": "Gaia DR3 still current; DR2+zero-point 4.24390 ly (superseded); HST 2025 independent 4.24477 ly (per sibling audit gaia-dr3-proxima-distance, arXiv:2104.14972, 2512.08533)", "source_now": "sibling audit audits/gaia-dr3-proxima-distance.json (READ there); recomputed in rederive D", "moves_conclusion": "no. None of the four flags depends on D. The datum sets only the channel setup time (>= 4.2465 yr from a single origin) and the per-transit classical latency. Across 4.24390-4.24650 ly, advantage = D/c - D/c = 0.0 at every value."},
 {"quantity": "classical-teleportation benchmark F_class", "value_then": "2/3 (Massar-Popescu, as restated in 1505.07831 p.2)", "value_now": "2/3; re-derived exactly as the Bloch-sphere average of Z-measure-and-prepare (rederive H3)", "source_now": "1505.07831 p.2 (READ); sympy", "moves_conclusion": "no. It is a theorem, not a measurement. It is what shows the channel is not consumed below the quantum regime."},
 {"quantity": "experimental teleportation (confirmation, not an input)", "value_then": "1993: none (theory)", "value_now": "143 km free space, F >= 83% (1505.07831 p.5); ground-to-satellite up to 1400 km, average F = 0.80 +- 0.01 over six mutually unbiased input states (Ren et al. arXiv:1707.00934 p.2)", "source_now": "1505.07831 p.5; 1707.00934 p.2 (both READ from on-disk alphaXiv capture)", "moves_conclusion": "no. These confirm the protocol. Real links run at F ~ 0.8 < 1, which is the regime where the F = 1 flags are not exact (see the drift item on fidelity)."}
],
"rederivation": {
 "method": "sympy",
 "script_path": D + "/rederive/teleportation-no-cloning-no-signalling.py",
 "outcome": "21 PASS, 0 FAIL, exit 0, about 8 s. All four flags are computed from the protocol and none is read from transit.py's constants. T1/T2 (sympy, symbolic psi = a|0>+b|1>): each Bell outcome has p = 1/4. The Pauli correction returns psi exactly. The post-measurement state factorises |Bell_m>_(aA) (x) |v_m>_B on every outcome, so A|B entanglement goes 1 -> 0 (computed; transit.py hard-codes CHANNEL_BITS_AFTER = 0.0). Alice's pair is free of (a,b), and her input slot is I/2 (S = 1 bit). T1b: linsolve over every linear 4x2 map cloning {|0>,|1>,|+>} returns EmptySet; the orthogonal pair alone is consistent. T3: sympy identity Tr_A[sum K rho K^dag] = Tr_A[(sum K^dag K (x) I) rho] for generic symbolic rho and Kraus pairs, so rho_B is invariant under every trace-preserving local operation. Bits withheld: rho_B = I/2 exactly, independent of psi. Hypotheses bite, none a refutation. H1: a selective outcome moves B's conditional state to |0><0|. H2: Buzek-Hillery cloner followed by teleportation gives both parties 5/6 (200 random inputs, dev 5.6e-16). H3: measure-and-prepare with no ebit reaches average F = 2/3 exactly. H4: a non-maximal resource gives diag(cos^2 t, sin^2 t) without the bits, psi-free but not I/2. H5: a toy state-dependent nonlinear map at B makes Alice's basis choice visible (Delta rho_B[0,0] = 1/25); this is an illustration of Gisin's theorem, not a model. K: re-preparing a known state spends 0 ebits and needs >= log2(1/eps) classical bits at infidelity eps (6.6, 19.9, 39.9 bits at 1e-2, 1e-6, 1e-12). D: advantage = D/c - D/c = 0 symbolically, and at four Proxima distances. Two check lines are labelled consequences of an identity already checked rather than independent tests. transit.py --selftest also passes; it was run read-only at HEAD b8b929b.",
 "agrees_with_source": "yes"
},
"later_literature": [
 {"ref": "Ren et al., 'Ground-to-satellite quantum teleportation', arXiv:1707.00934 (Nature 549, 70, 2017)", "effect": "confirms", "what": "Teleportation of independent single-photon qubits over up to 1400 km, average F = 0.80 +- 0.01, 'well above the classical limit'. The classical feed-forward is still required. F < 1 in practice.", "read_status": "READ (p.2 abstract, from on-disk alphaXiv capture src/casmag/all/1707.00934v1.txt)"},
 {"ref": "Ahn, Myers, Ralph, Mann, 'Quantum state cloning in the presence of a closed timelike curve', arXiv:1207.6062 (PRA 88, 022332, 2013)", "effect": "narrows", "what": "States no-cloning holds 'if chronology is respected'. With Deutsch CTCs the induced map is nonlinear, perfect cloning of a finite alphabet is possible, and a universal cloner exceeds the no-cloning bound. This bears on the board because O3 (CTCs) is held open.", "read_status": "READ (p.1, on-disk capture 1207.6062v1.txt); contested by later work that this run did not read"},
 {"ref": "Lloyd, Maccone, Garcia-Patron, Giovannetti, Shikano, Pirandola et al., 'Closed timelike curves via post-selection', arXiv:1005.2219 (PRL 106, 040403, 2011)", "effect": "extends", "what": "P-CTCs are built from teleportation plus post-selection and are 'physically inequivalent' to Deutsch's model. Teleportation's guarantees depend on which CTC model holds, so the chronology hypothesis is model-dependent, not settled.", "read_status": "READ (p.1 abstract and intro, on-disk capture 1005.2219v1.txt)"},
 {"ref": "Bielinska, Eckstein, Horodecki, 'Superluminal signalling and chaos in nonlinear quantum dynamics', arXiv:2412.20854 (2024)", "effect": "narrows", "what": "Restates Gisin 1989: 'nonlinear quantum dynamics would lead to superluminal signalling'. The theorem needs clock synchronisation and the no-restriction hypothesis; one nonlocal nonlinear dynamics avoids signalling if that hypothesis is relaxed. Linearity is therefore a load-bearing hypothesis of BEATS_LIGHT = False.", "read_status": "READ (abstract, on-disk capture 2412.20854v1.txt)"},
 {"ref": "Bennett, DiVincenzo, Shor, Smolin, Terhal, Wootters, 'Remote State Preparation', arXiv:quant-ph/0006044 (PRL 87, 077902, 2001)", "effect": "narrows", "what": "For a KNOWN state the classical cost falls to 1 bit per qubit asymptotically; that bit is 'also necessary by causality'. This supports specthm's known-state clause. On the RSP route an ebit is still consumed, so 'the channel is not consumed' holds only for classical re-preparation.", "read_status": "READ (pp.1-2, on-disk capture quant-ph_0006044v5.txt)"},
 {"ref": "discover_papers search for later work (one call)", "effect": "contested", "what": "The call returned 'assistant quota exceeded', so no fresh search was run. The entries above are later papers already captured on disk by earlier D67 runs. The literature list is a floor, not a census.", "read_status": "NOT RUN (quota)"}
],
"lacked_data": "M's hypothesis tested for this result: did the authors lack data that changes the conclusion? Evidence either way. (1) These are theorems about linear quantum mechanics (1982, 1993, 1978/80). No measured datum enters any of the four conclusions, and rederive D shows the one datum the tree attaches (Proxima 4.2465 ly) is D-independent for every flag. (2) What 1993 lacked was experiment. Every test since confirms the protocol and its need for the classical channel: 143 km at F >= 83% (1505.07831 p.5) and 1400 km ground-to-satellite at F = 0.80 (1707.00934). None contradicts no-cloning or no-signalling. (3) The open 'data' are about what physics exists, not measurements the authors missed: whether quantum mechanics is exactly linear (Gisin's theorem, 2412.20854) and whether CTCs exist, and under which model (Deutsch vs P-CTC, 1207.6062, 1005.2219). The theorems state their own domain here; none of them failed for lack of data. Tests of QM linearity bound nonlinearity, and no CTC has been observed. This run READ no numerical bound on nonlinearity, so the size of that constraint is not quoted. Conclusion: M's hypothesis is not supported for this result. Nothing missing from the authors' data moves any flag. The live limitations are named hypotheses (F = 1, linearity, chronology, non-selectivity, finite classical description for known states), and none of them is a datum.",
"grade": "NARROWED",
"grade_evidence": "The external results STAND as published, and each is re-derived here symbolically: exact teleportation with psi-free residue at A, 1 -> 0 ebit on every outcome, no linear cloner, rho_B invariant under every trace-preserving local map, and I/2 without the bits. The tree's central hypothesis, the unknown state (H_tele), is retained in R11 and M-S1A-P5. The grade is NARROWED on the rule's 'a hypothesis the tree drops'. (a) Exact fidelity: R11 records 'the fidelity is not yet fixed' (specthm.py:1186-1187) yet binds MOVE and CONSUMED, which are exact only at F = 1. Computed: clone-then-teleport leaves a 5/6 copy at A, and measure-prepare at F = 2/3 consumes no ebit. (b) Linear, chronology-respecting QM is named nowhere, while the board holds CTCs open (O3_CLOSED = False). Peres-Terno assume 'no closed causal loops', and Ahn et al. show Deutsch-CTC cloning. (c) Non-selectivity is dropped from 'EVERY operation' (transit.py:17-18, 176). (d) The known-state clause needs a finite classical description (computed log2(1/eps) bits). Over-representation is checked both ways. None of (a)-(d) changes a flag's value in the scenario the tree actually runs: ideal F = 1 teleportation of an unknown state in linear QM with a vacuum EM classical channel. So nothing in the tree is WRONG, and BEATS_LIGHT = False and CARRIES_SUBSTANCE = False stand there. BEATS_LIGHT's zero is by construction (transit.py:145-146), as D23 itself says. It is not DATA-DEPENDENT: the only datum (Proxima distance) moves no flag. Discrepancies recorded, not repaired, and not errors in the sources: 'CONSERVATION LAW' (transit.py:24, 213, 221) is LOCC monotonicity; 'NO WORLDLINE CROSSES ANYTHING' (transit.py:21-22, 192) sits against the file's own 'moved earlier' (:46-50). Nothing under research/warp-drive was edited.",
"what_would_change_the_grade": "To STANDS: the tree names the dropped hypotheses at the owner sites, meaning R11 binds MOVE/CONSUMED 'at F = 1' (or fixes the fidelity at 1) and states 'in linear, chronology-respecting QM'. To WRONG: a demonstrated protocol inside linear QM without CTCs that copies an unknown state, keeps the ebit, or signals. None exists, and each is excluded by the identities re-derived here. To DATA-DEPENDENT: a measured violation of QM linearity or an observed CTC, which would make BEATS_LIGHT and no-cloning hinge on that datum. To OPEN on reading: if the on-disk alphaXiv captures were found not to match the live papers; their md5s are recorded under source.via.",
"reverify_command": "python3 " + D + "/rederive/teleportation-no-cloning-no-signalling.py && python3 /home/user/Claude-Method-Works/research/warp-drive/transit.py --selftest | tail -1 && sed -n '1186,1190p;1205,1213p' /home/user/Claude-Method-Works/research/warp-drive/specthm.py && sed -n '1362,1377p' /home/user/Claude-Method-Works/research/warp-drive/ledger.py && sed -n '17,18p;145,155p' /home/user/Claude-Method-Works/research/warp-drive/transit.py && grep -n 'O3_CLOSED = ' /home/user/Claude-Method-Works/research/warp-drive/latticectc.py && md5sum " + SRC + "/1505.07831v1.txt " + SRC + "/quant-ph_0511088v1.txt",
"report_path": D + "/audits/teleportation-no-cloning-no-signalling.json"
}
json.dump(R, open(R["report_path"], "w"), indent=1)
print("written", R["report_path"])
