import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "2309.05759-eq41",
 "name": "Kabat & Nomura eq. 41: bulk scalar coupling carries a free Yukawa lambda",
 "source": {
  "located": "D. Kabat and M. Nomura, 'Induced Lorentz violation on a moving braneworld', arXiv:2309.05759 (11 Sep 2023), Phys. Rev. D 108 (2023) 105014 -- identity from WebSearch result listings (arxiv.org/abs/2309.05759, journals.aps.org PhysRevD.108.105014, INSPIRE 2696708).",
  "read_status": "NAMED-NOT-READ",
  "via": "NOT reached at source this stage. alphaXiv get_paper_content(fullText), answer_pdf_queries (three tries) and discover_papers each returned 'alphaXiv assistant quota exceeded'. curl to arxiv.org, inspirehep.net, ar5iv.org, www.semanticscholar.org: CONNECT 403; WebFetch to arxiv.org, www.alphaxiv.org, ar5iv.labs.arxiv.org, link.springer.com: EGRESS_BLOCKED. No capture of the paper exists in research/warp-drive or the scratchpad. What WAS seen: (a) two WebSearch engine summaries saying the paper 'stud[ies] one-loop electron self-energy arising from a Yukawa coupling to a bulk scalar' and 'a real scalar field on the brane with a cubic coupling to a bulk scalar, starting from an action with coupling constant g' -- a search summary, not a verbatim read, and it names neither eq. (41) nor the symbol lambda; (b) the O6/O7 pass's own script /tmp/o6o7/o67.py:131-133, which says 'For a bulk SCALAR the same coefficient carries a free Yukawa lambda, so it bounds lambda^2 beta^2, not beta' WITHOUT any equation number. The eq.-41 locus therefore has no recorded read anywhere on disk."
 },
 "published_statement": "NOT READ. Eq. (41) of arXiv:2309.05759 could not be quoted. The only external content seen (search summary, not verbatim): the paper computes a one-loop brane-electron self-energy from a Yukawa coupling to a bulk scalar, and a brane-scalar self-energy from a cubic coupling (constant g) to a bulk scalar, on a flat brane moving on / spiralling around the S^1 of M^{3,1} x S^1; nonzero-winding bulk loops give UV-finite Lorentz-violating SME terms.",
 "published_hypotheses": [
  "NOT READ at source; from the abstract as relayed by search results only: flat 4D brane embedded in M^{3,1} x S^1",
  "brane moving on or spiralling around the S^1 (the global Lorentz breaking comes from the compactification)",
  "bulk fields considered: scalars (Yukawa to brane fermions; cubic to brane scalars) and gravitons -- the graviton is a BULK field in this paper (the tree's own READ of eqs. 68, 70-73)",
  "one loop, nonzero winding; results matched to the SME"
 ],
 "hypothesis_drift": [
  "UNVERIFIED LOCUS (branelink.py:48-51, 318-320): the tree cites 'eq. 41' for the free Yukawa coupling; branelink.COUPLING_SOURCE (branelink.py:158-159) records READ only for eqs. 68, 70-73, and the pass's script /tmp/o6o7/o67.py:133 states the free-lambda remark with no equation number -- so the number '41' and the symbol 'lambda' have no recorded read. The canonical status_word ('READ by the pass (via COUPLING_SOURCE...)') overstates what COUPLING_SOURCE covers. A discrepancy of provenance, not a refutation.",
  "ADDED HYPOTHESIS 'bulk carrier is a scalar' (branelink.py:318-320): in the source (per the relayed abstract) the bulk scalar is one of the fields whose loops are computed -- a model field with an input coupling -- not a field the paper claims exists. The tree's brane-confined branch needs a bulk scalar to exist at all for there to be a carrier; that existence is an added assumption of the tree, not a result of KN.",
  "OUTSIDE-SCOPE BRANCH (branelink.py:48-51): KN's graviton is a bulk field (eqs. 68-73, READ by the pass). The 'graviton brane-confined' branch is outside KN's setup; using KN's scalar sector there is legitimate only because the scalar sector does not depend on where the graviton lives -- true of the generic action (C1-C3 of the rederivation), not checked against KN's text.",
  "WEAKENED READING OF 'free' (branelink.py:50 'free Yukawa lambda ... no rate'): 'free' = not fixed by the model (confirmed dimensionally: [lambda_5] = -1/2, no measured anchor analogous to G for gravity). It does NOT mean unbounded: SME bounds of the kind the tree itself uses (Dreissen et al. 1e-21) constrain lambda_5^2 f/r, and fifth-force searches would constrain the zero-mode coupling lambda_4. 'No rate' is accurate as 'no PREDICTED rate'; whether an experimental CEILING on the rate exists was not computed here or by the tree.",
  "NAMING HAZARD (not a drift): the pass's /tmp/o6o7/final.py:6 uses 'Yukawa range lambda <= 38.6 um' for the Eot-Wash RANGE parameter; branelink's 'Yukawa lambda' is a COUPLING constant. Same letter, different quantity."
 ],
 "data_at_publication": [],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/2309.05759-eq41.py",
  "outcome": "ALL PASS (14 checks, sympy + one z3 obligation). Checked the GENERIC claim, not eq. (41) itself: C1 a 5D-bulk-scalar Yukawa to a brane fermion bilinear has mass dimension -1/2 (cubic brane-scalar coupling +1/2; graviton 1/Mbar5^{3/2} is -3/2); C2 the constant zero mode on the circle normalises to (2 pi r)^{-1/2}, lambda_4 = lambda_5 (2 pi r)^{-1/2} dimensionless, and the same step reproduces the READ gravity normalisation Mbar4 = (2 pi r)^{1/2} Mbar5^{3/2} (KN eq. 72 form) -- for gravity the measured G anchors the coupling, for the scalar nothing does; C3 any dimensionless one-loop LV coefficient is lambda_5^2/r x f(beta, m r, mu r), and z3 proves unsat the negation 'some beta in (0,1] is excluded by c <= B for every lambda > 0' -- a single SME bound bounds lambda^2 beta^2 f, not beta (the pass's own wording); C4 control: the graviton coefficient has no free coupling and reproduces branelink's 6.37e-64 to 0.06% at r = 38.6 um, beta = 1 (with Mbar4 = 2.435e18 GeV, magnitude only).",
  "agrees_with_source": "not-run"
 },
 "later_literature": [
  {"ref": "discover_papers NOT RUN (alphaXiv quota exceeded)", "effect": "contested", "what": "No later-literature search could be made through alphaXiv. WebSearch listings surfaced arXiv:2309.16226 ('Anomalous function of a Lorentz-violating QED effective action and the relation between compact bulk scalar propagator and path integral duality') and JHEP08(2026)192 ('Braneworlds in constant and accelerated motion and their causal characteristics') as related; neither was readable (arxiv.org, link.springer.com EGRESS_BLOCKED). Effect on eq. (41) UNKNOWN; 'contested' is the schema's nearest slot and here means only 'not assessed'.", "read_status": "NAMED-NOT-READ"}
 ],
 "lacked_data": "M's hypothesis tested for this result: the claim is a statement about the MODEL's parameter content, not a fit to data, so no datum available in 2023 and absent now bears on it. KN (2023) had the SME laboratory bounds and the Eot-Wash 2020 null; neither fixes a bulk-scalar Yukawa -- they bound it. Evidence either way: (for M) nothing -- a free coupling of a hypothetical field cannot be 'wrong for lack of data'; (against a data gap) the dimensional analysis (C1-C3) shows the freedom is structural: [lambda_5] = -1/2 with no measured anchor, unlike gravity where G is measured. New data could only BOUND lambda (and hence give the brane-confined branch a rate CEILING), never make it 'not free'. Having more data would not change the tree's conclusion 'no predicted rate'; it could change 'no rate' into 'rate <= X', which the tree has not computed.",
 "grade": "OPEN",
 "grade_evidence": "The source could not be read this stage (alphaXiv quota exhausted on every call; arxiv.org and all mirrors blocked by the egress proxy), so eq. (41) -- its numbering, symbol and prefactors -- is unverified; by M's rule an unreadable result is OPEN, never flattened to STANDS. What WAS established: (i) the physics the tree takes from it is generically correct -- a bulk-scalar Yukawa to brane matter has mass dimension -1/2 and is not fixed by the action (sympy, C1-C2), and a single SME bound cannot bite beta when it is free (z3 unsat, C3), matching the pass's own script; (ii) the eq.-41 citation has no recorded read on disk -- COUPLING_SOURCE covers eqs. 68, 70-73 and the pass's script states the remark with no equation number; (iii) 'free' is not 'unbounded' -- 'no rate' holds only as 'no predicted rate'. Nothing found refutes the tree's use; nothing found confirms the locus.",
 "what_would_change_the_grade": "Reading arXiv:2309.05759 at source (alphaXiv once the quota resets, or any unblocked mirror): if eq. (41) is the brane-fermion/bulk-scalar Yukawa with an unconstrained coupling and the paper imposes no normalisation on it -> STANDS on the claim, with a NARROWED note if the tree keeps 'no rate' rather than 'no predicted rate' or keeps the added 'a bulk scalar exists' hypothesis unnamed; if eq. (41) is a different equation (e.g. the cubic coupling g, or a propagator) -> the citation is a DISCREPANCY of locus (not WRONG), to be recorded against branelink.py:50 and :320; if KN fix the scalar coupling by some normalisation -> the tree's 'free' would be refuted and the grade WRONG for this use.",
 "reverify_command": "python3 " + D + "/rederive/2309.05759-eq41.py && grep -n 'eq. 41\\|COUPLING_SOURCE' /home/user/Claude-Method-Works/research/warp-drive/branelink.py && grep -n 'free Yukawa' /tmp/o6o7/o67.py  # then: alphaXiv answer_pdf_queries(paper='2309.05759', queries=['Equation (41) verbatim and what its coupling is','Is the bulk scalar Yukawa coupling fixed by any normalisation?'])",
 "report_path": D + "/audits/2309.05759-eq41.json"
}
json.dump(rep, open(rep["report_path"], "w"), indent=1)
print("ok")
