import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R = {
 "key": "gr-qc/0208045",
 "name": "Ford, Helfer & Roman, 'Spatially Averaged Quantum Inequalities Do Not Exist in Four-Dimensional Spacetime' (gr-qc/0208045v2; PRD 66, 124012 (2002)): for the massless minimally coupled free scalar in 4D Minkowski, S(F) = INT d^3x F(x) <:T_00:> at fixed time is unbounded below over a sequence of Hadamard states, although <H> >= 0 over all space",
 "source": {
  "located": "arXiv gr-qc/0208045v2 (24 Oct 2002), L.H. Ford (Tufts), A.D. Helfer (Missouri), T.A. Roman (Tufts/CCSU), 13 pp. Journal identity PRD 66 (2002) 124012 = arXiv gr-qc/0208045 confirmed READ in Fewster arXiv:1208.5399 ref. [43] -- so ledger D6's 'PRD 66 124012' and specthm D7's 'gr-qc/0208045' are the same paper (specthm.py:1744-1746 had not equated them; the merged key is correct).",
  "read_status": "READ",
  "via": "alphaXiv get_paper_content(fullText=true) returned the whole paper, pp.1-13 incl. references; every quotation below is from that text. Pre-2002 inputs it rests on: Helfer CQG 13 L129 (1996, gr-qc/9602060) [22] -- NAMED-NOT-READ (restated by FHR p.3 and p.12 only); Fewster-Eveson PRD 58 084010 [14] temporal QEI for all Hadamard states -- READ-VIA-RESTATEMENT in Kontou-Sanders arXiv:2003.01815 p.21 Eq.(61)."
 },
 "published_statement": "Abstract: 'We construct a particular class of quantum states for a massless, minimally coupled free scalar field which are of the form of a superposition of the vacuum and multi-mode two-particle states ... they can produce an arbitrarily large amount of negative energy in a given region of space at a fixed time. This class of states thus provides an explicit counterexample to the existence of a spatially averaged quantum inequality in four-dimensional spacetime.' Sec. III p.9: 'The first conclusion is the proof that there are no lower bounds on the spatially sampled energy density for the massless minimally coupled scalar field in four spacetime dimensions. ... S(F) = INT d^3x F(x) <:T00(x,t):> (42) at time t, where F(x) is a spatial sampling function. Let r0 be the characteristic width ... [or] the maximum width of F(x) in any direction.' p.10: 'Thus S(F) is unbounded below. However, this state satisfies the temporal quantum inequality, Eq. (1).' p.8: 'each state in this sequence will have the Hadamard form. By progressively increasing the values of Lambda ... we can make the energy density in our spatially sampled region as negative as we like.' p.10: 'The integration over all space removes the contribution of the rho2 term, leaving only the non-negative contribution of the rho1 term ... the compensating positive energy is arbitrarily far from the negative energy.' p.2: 'the total energy in any quantum state for a quantum field in boundary-free Minkowski spacetime must be non-negative ... <H> >= 0 (3), and <H> = 0 only in the vacuum state' (quoted as known, not proven here). p.12 summary: 'we have shown that there are no purely spatially averaged quantum inequalities over bounded regions in four-dimensional Minkowski spacetime, even though the integral over all space is bounded. However, spacetime averaged quantum inequalities do exist.' p.10: 'it seems likely that one can construct similar counterexamples to spatial quantum inequalities in all spacetime dimensions greater than two' (conjecture). p.12: 'The logarithmic divergences (of the energy density with the cutoff Lambda) are rather slow. We do not know whether it is possible to construct examples in Minkowski space with more severe divergences.'",
 "published_hypotheses": [
  "H1 massless (m = 0), minimally coupled (xi = 0), free (non-interacting) real scalar field -- abstract, Sec. II, and Sec. III p.9 'for the massless minimally coupled scalar field'",
  "H2 four-dimensional Minkowski spacetime, surface of constant time, no boundaries (Sec. I; <H> >= 0 stated for 'boundary-free Minkowski spacetime')",
  "H3 the refuted object is a STATE-INDEPENDENT lower bound: 'S(F) would have to have a lower bound when we vary over all quantum states for a given F(x)' (p.9)",
  "H4 purely spatial sampling at one instant t, F of finite characteristic width r0 (maximum width in any direction); normalization of F implicit",
  "H5 witness family: |psi> = N(|0> + sum c_{k1k2}|k1,k2>), b = chi(k1+k2)(|k1||k2|)^(nu-1/2), chi = chi0 on |p| <= p0 (Eqs.6-12); nu = -1/2 (normalizable iff nu < -1/4, Eq.14); chi0 < 3/(80 pi p0) (Eq.41)",
  "H6 each member has finite UV cutoff Lambda (Hadamard); unboundedness is reached only in the limit Lambda -> oo, and only logarithmically (Eqs.30-31, 36) -- i.e. the field theory is assumed valid to arbitrarily high momenta",
  "H7 method: leading-order asymptotics in omega >> p0 ('If the integral for rho2 is dominated by values of omega large compared to p0', p.7; '≈' throughout) -- not a rigorous theorem in the paper's own text",
  "H8 the region of approximately constant negative density is r << 1/p0 (p.8), with p0 arbitrary"
 ],
 "hypothesis_drift": [
  "DROPPED H1 (field): the tree states the no-go with no field qualifier -- bounds.py:31-32 ('FORD-HELFER-ROMAN PROVE NO QEI EXISTS'), bounds.py:144-146, bounds.py:211-216, bounds.py:262-264; achievable.py:151-153, 219-226 (keeps 'Hadamard states', drops the field), achievable.py:427-431 and :567-568; ledger.py:399-404 (D6); specthm.py:926-928. The canonical hypotheses for bounds.py read 'free quantum field', a weakening of 'massless minimally coupled scalar'. INHERITED: the paper's own title and p.12 summary sentence (which the tree quotes verbatim) also omit the field; the abstract and p.9 carry it. CONSEQUENCE BOTH WAYS: for the tree's reading as a refutation of a UNIVERSAL (matter-independent) spatial bound, one field suffices, so that reading stands; for a FIELD-SPECIFIC spatial bound (massive scalar, Maxwell, Dirac) FHR prove nothing -- such a bound would be a refusal instrument AGAINST the warp, so the narrowing does not run in M's favour. Nonminimal xi != 0 is covered by other work: Fewster 1208.5399 p.44 (READ), citing Fewster-Osterbrink: 'states of arbitrarily negative energy density can be sustained over arbitrarily large spacetime volumes'.",
  "DROPPED H3 (state-independence): FHR refute a lower bound uniform over states for fixed F. The tree says 'no QEI exists' (bounds.py:31-32, 144-146), 'no such instrument CAN exist' (bounds.py:211-216) and 'no bound in this family has spacelike signature, bounds an ENERGY, and applies to a BOUNDED region; FHR prove there cannot be one' (bounds.py:262-264) -- but bounds.py's own index carries an S slot (state-dependent RHS, 0/1) and FHR speak only to S = 0 with B = a negative constant. COMPUTED HERE (rederive script, leading-log, not in the source): in FHR's own family <H> ~ (64 pi^2/3) chi0^2 N^2 p0^3 ln Lambda, and with ln Lambda = 1/chi0^2, chi0 -> 0, <H> stays finite while S(F) -> -oo; so bounds depending on the state only through <H> also fail. General state-dependent spatial bounds (Kontou-Sanders 2003.01815 Eq.(53), -<Q(f)>) remain OPEN from this paper.",
  "DROPPED H2 (flatness) at two sites: bounds.py:214-215 'no such instrument CAN exist over a bounded region in four dimensions' and achievable.py:152-153, :568 'none can exist over a bounded region in four dimensions' drop 'Minkowski'. FHR is a constant-time surface of Minkowski space; the curved-spacetime case rests on Helfer CQG 13 L129 (1996), NAMED-NOT-READ, which FHR restate (p.12) as finding MORE severe divergences at Cauchy surfaces with nonzero second fundamental form -- direction favours the tree, but it is not read here. ledger.py:399-404 and specthm.py:926-928 keep '4D Minkowski'.",
  "DROPPED H6 (no UV cutoff): ledger.py:401-402 'The ball integral at an INSTANT is unbounded below, so THE MAGNITUDE AXIS CARRIES NO NO-GO' does not name that unboundedness is a Lambda -> oo statement, logarithmic in Lambda. COMPUTED HERE: with a finite cutoff the family reaches at most S = -K ln(Lambda/p0)/r0^4, K = 1.2554e-2 (optimised over chi0 and p0 r0 = 4.05; N^2 <= 1, q-constants dropped); at r0 = 1 m with a Planck cutoff that is 0.988 hbar c/r0^4, about 104x the Ford-Roman Lorentzian temporal value 3/(32 pi^2 t0^4) at t0 = r0/c. Family-specific: FHR do not know whether stronger divergences exist (p.12).",
  "WEAKENED H7 (rigour): ledger.py:399-404 codes D6 THEOREM and every owner says 'prove'; the paper's derivation is leading-order asymptotic. Checked here from the EXACT integrands: the ln Lambda coefficients of rho2 and rho1 agree with Eqs.(31),(36) to 1.2e-8 and 1.1e-5 (shell-size corrections O(p0^2/k^2)); Fewster 1208.5399 Remark 3 p.26 (READ) treats the result as established. Recorded as a status-word drift, not a fault.",
  "ADDED/GLOSS: achievable.py:90-92 'Ford, Helfer and Roman prove the sampling scale need not track the region at all' is not a statement in the paper; the nearest source words (p.10) are 'This allows the scale for the spatial variation of rho to be large compared to the temporal scale'. A fair inference from the witness family (lambda0 = 2 pi/p0 arbitrary, temporal scale ~1/omega), overstated as 'prove'.",
  "DROPPED 'boundary-free': bounds.py:251-253 seats <H> >= 0 ('with equality only in the vacuum') without FHR's hypothesis 'boundary-free Minkowski spacetime' (p.2); with boundaries, energy normal-ordered against the Minkowski vacuum can be negative (Casimir). The equality clause matches the source.",
  "NOT DRIFT (checked): achievable.py:223 and bounds.py:275-276 'witness states ... SATISFY the temporal inequality' -- FHR p.10 assert it; it follows because every finite-Lambda member is Hadamard (p.8) and the Fewster-Eveson QEI holds for all Hadamard states (Kontou-Sanders p.21 Eq.61). 'Transient': p.10 'if rho2 < 0 at one time, it has changed sign a short time later'. bounds.py:147-151 / specthm.py:1744-1746 'Ford-Helfer-Roman prove nothing about null smearing' with the p.4 quote -- verbatim match. bounds.py:244-248 and achievable.py:224-226 verbatim quote of the p.12 summary -- exact (capitals are the tree's emphasis). bounds.py:265-266 mechanism quote -- exact (p.10)."
 ],
 "data_at_publication": [
  {"quantity": "numerical physical inputs to the conclusion",
   "value_then": "none: a construction in free QFT; hbar = c = 1; p0, chi0, Lambda, nu are free parameters of the witness family",
   "value_now": "none",
   "source_now": "n/a (theorem-type result)",
   "moves_conclusion": "no -- no measured datum enters"},
  {"quantity": "Planck length l_P (used ONLY in this audit's computed cutoff estimate, not by FHR)",
   "value_then": "not used by the authors",
   "value_now": "1.616255e-35 m (CODATA 2018, as used in the script)",
   "source_now": "CODATA recommended values (not re-read this stage; value enters only inside a logarithm)",
   "moves_conclusion": "no -- a factor 10 change in the cutoff moves ln(Lambda r0) ~ 78.7 by 2.3 at r0 = 1 m; it bounds only the family's reach with a cutoff, not FHR's cutoff-free statement"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/gr-qc_0208045.py",
  "outcome": "28 checks PASS, 0 FAIL (sympy + numpy quadrature + Monte Carlo, ~10 s). Symbolic: Eq.(14) normalizability (radial power k^(4nu)); Eq.(23) expansion of khat.khat'; Eqs.(25)-(26) angular integrals and the 1/(6 pi^2) of Eq.(29); Eq.(27) f2 closed form both lines; Eq.(28) both asymptotics; Eq.(37) f1 = |INT_ball e^{ip.x}|^2 and Eq.(38); f2/f1 -> 9/(20 pi p0); Eq.(41) threshold 3/(80 pi p0); ln Lambda coefficient of rho1 + rho2 negative iff 0 < chi0 < 3/(80 pi p0); Gaussian-regulated INT d^3x f2 = 0 (the all-space integral removes rho2, Sec. III). Numerical from the EXACT integrands at x = 0, t = 0, nu = -1/2: rho2's ln Lambda coefficient = 16 pi^2/15 p0^5 to 1.15e-4, 1.15e-6, 1.15e-8 on shells [10,100], [100,1000], [1000,1e4] (O(p0^2/k^2) convergence); rho1's = 2(4pi/3)^2 4pi p0^6 (MC mean weight 1.999989 +- 0.000002, prediction 2). DISCREPANCY (prose, not a refutation): p.10 'we can choose lambda0 > r0' is not sufficient as literally stated -- f2 first changes sign at p0 r = 3.8703 = 0.616 lambda0, and at leading log rho < 0 only for p0 r < 3.80-3.86 (chi0 = 0.9-0.1 of threshold); the operative condition is p.8's r << 1/p0, and since p0 is arbitrary the conclusion is unaffected. MISPRINTS: p.4 'the integral in Eq. (5)' (twice) should read Eq.(10) -- Eq.(5) is the sampling-function normalization; Eq.(33) has an unbalanced parenthesis. COMPUTED EXTENSIONS (not in the source, leading-log): (i) <H> grows as ln Lambda with coefficient (64 pi^2/3) chi0^2 N^2 p0^3 by two independent routes (INT rho1 d^3x and 2 INT |b|^2 (w1+w2); MC 2.000000 +- 0.000004), and at fixed <H> S(F) -> -oo; (ii) with a finite cutoff the family's ball-averaged negativity is at most K ln(Lambda/p0)/r0^4, K = 1.2554e-2.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Fewster, 'Lectures on quantum energy inequalities', arXiv:1208.5399 (2012)", "effect": "confirms",
   "what": "Remark 3 p.26: 'One may show that no such bounds exist for smearings over spacelike surfaces (certainly above 2-dimensions) [43]' ([43] = FHR, PRD 66 124012, gr-qc/0208045). Also p.44: the nonminimally coupled scalar sustains arbitrarily negative energy density over arbitrarily large spacetime volumes, so the spatial no-go holds for xi != 0 by a different route. Fewster's wording generalizes beyond FHR's single field without a further citation.",
   "read_status": "READ (alphaXiv answer_pdf_queries, pp.1,2,10,14,15,24-26,44-50)"},
  {"ref": "Kontou & Sanders, 'Energy conditions in general relativity and quantum field theory', arXiv:2003.01815, CQG review (2020)", "effect": "narrows",
   "what": "p.24: 'in general dimensions there is USUALLY no QEI for energy densities which are only averaged in a spacelike direction' -- hedged, and 2D CFT spatial averages DO obey the same bound as timelike (Fewster-Hollands). Table 3 lists QEI status field by field (Maxwell/Proca, Dirac: QNEI/QSEI '?'), showing QEI existence is field-specific. p.25: Freivogel & Krommydas argue the analogous NULL counterexample (Fewster-Roman, built on FHR's construction, FHR p.4) is problematic because it uses arbitrarily high momenta; with momenta below a UV cutoff a finite bound -B/G_N follows. The same objection applies in form to FHR's log-in-Lambda spatial divergence; nobody in what was read here has made it for the spatial case.",
   "read_status": "READ (alphaXiv answer_pdf_queries, pp.1,2,4,20-25,34,52,55,57)"},
  {"ref": "Fewster & Roman, 'Null energy conditions in quantum field theory', PRD 67 044003, gr-qc/0209036", "effect": "extends",
   "what": "uses a related construction to prove no QEIs along null geodesics in 4D Minkowski (FHR p.4; Kontou-Sanders p.25).",
   "read_status": "NAMED-NOT-READ this stage (restated in FHR p.4 and Kontou-Sanders p.25; bounds.py:152-159 records reading it)"},
  {"ref": "discover_papers (one call, 'spatially averaged quantum inequalities' / 'quantum energy inequalities', historical)", "effect": "contested",
   "what": "returned no paper that addresses spatial averaging (hits were unrelated inequality papers, and 2608.11817 'Quantum Inequalities from the Second Law', not read). No contradiction and no rigorous re-proof or multi-field extension of FHR was found by this search; absence of a hit is not evidence of absence.",
   "read_status": "search only; nothing further read"}
 ],
 "lacked_data": "No measured datum enters FHR -- it is a construction in free QFT, so no later measurement can move it. What the authors lacked in 2002 was theory, not data: (a) a rigorous, non-asymptotic proof (the paper is leading-order); this audit's exact-integrand numerics confirm both ln Lambda coefficients (1.2e-8, 1.1e-5), evidence FOR the conclusion; (b) knowledge of other fields -- still missing in what was read (Kontou-Sanders Table 3 leaves Maxwell/Dirac '?'; spatial case is 'usually' no QEI), and this cuts AGAINST M: a field-specific spatial bound would be a refusal instrument, not a licence; (c) the UV completion. The divergence is only ln Lambda: if field theory stops at a physical cutoff (Freivogel-Krommydas make this objection for the null analogue), FHR's family reaches at most K ln(Lambda r0)/r0^4 with K = 1.2554e-2 -- at r0 = 1 m and a Planck cutoff, 0.988 hbar c/r0^4, ~104x the Lorentzian temporal scale at t0 = r0/c. So supplying the missing UV datum would turn 'unbounded below' into a finite, log-enhanced ceiling for this family, which weakens ledger D6's 'THE MAGNITUDE AXIS CARRIES NO NO-GO' rather than helping a warp. It does not reverse bounds.py's use: whatever the cutoff, a UNIVERSAL cutoff-free spatial bound is refuted by the massless minimally coupled scalar, and the board's actual refusal is priced on the duration axis (Fewster 1208.5399 Eq.(4)), which FHR's transient witnesses obey. Evidence either way is computed in the rederive script; the general-cutoff question is OPEN.",
 "grade": "NARROWED",
 "grade_evidence": "READ in full at source; every quotation the tree uses is verbatim; the re-derivation of Sec. II-III agrees (28/28 checks, including exact-integrand numerics for both log coefficients). The tree nonetheless states the result on a larger class than was proved: it drops the field (massless minimally coupled free scalar; bounds.py:31-32, 144-146, 211-216, 262-264; achievable.py:151-153; ledger.py:399-404), drops state-independence where bounds.py's own S slot makes it load-bearing (bounds.py:262-264 'FHR prove there cannot be one'), drops 'Minkowski' at bounds.py:214-215 and achievable.py:152-153/:568, and drops the cutoff-free (Lambda -> oo, logarithmic) hypothesis behind D6's 'magnitude axis carries no no-go' (ledger.py:401-402). The use that matters most -- no UNIVERSAL spatial bound over a bounded region in 4D Minkowski can refuse the corridor -- STANDS, since one admissible field is a counterexample; and the state-independence narrowing is partly closed here (bounds that depend on the state only through <H> fail too, computed at leading log). Not WRONG: nothing refutes the theorem; the lambda0 > r0 prose and the Eq.(5)/(10) cross-reference are discrepancies, not errors in the conclusion.",
 "what_would_change_the_grade": "To STANDS: the owners restore the dropped hypotheses (massless minimally coupled scalar or 'no universal bound'; state-independent; Minkowski; Lambda -> oo), or cited proofs extending FHR to Maxwell/Dirac/massive fields and to curved Cauchy surfaces are READ (Helfer CQG 13 L129 is the named candidate for the latter). To WRONG: an exact computation showing the neglected sub-leading terms or N^2 cancel the ln Lambda term (the exact-integrand numerics here make this unlikely), or a proof of a state-independent spatial bound for this field. To DATA-DEPENDENT: a published argument, read at source, that a physical UV cutoff restores a spatial bound for the scalar (the Freivogel-Krommydas style objection applied to the spatial case).",
 "reverify_command": "python3 " + D + "/rederive/gr-qc_0208045.py  # expect '0 FAIL', exit 0; then re-read arXiv gr-qc/0208045 pp.8-12 and grep -n 'Ford-Helfer-Roman\\|Ford, Helfer\\|FHR' /home/user/Claude-Method-Works/research/warp-drive/{bounds,achievable,ledger,specthm}.py",
 "report_path": D + "/audits/gr-qc_0208045.json"
}
json.dump(R, open(D + "/audits/gr-qc_0208045.json", "w"), indent=1, ensure_ascii=False)
print("ok")
