import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/"
KEY = "spectral-theory-friedrichs-rayleigh-ritz"
rep = {
 "key": KEY,
 "name": "Friedrichs extension keeps the form lower bound; Rayleigh-Ritz places the spectrum above the form bound (operator theory)",
 "source": {
  "located": "Friedrichs, Math. Ann. 109 (1934) 465-487, 685-713 (the extension theorem) and Reed-Simon Vol. II Thm X.23 (the form FFR cite) -- both NAMED-NOT-READ. Read instead: (1) Gesztesy & Sukhtaiev, 'Some Remarks on Krein-von Neumann Extensions', arXiv:2504.11718 (2025), Sec. 2, Thm 2.2, Eqs. (2.13)-(2.21), which restate the Friedrichs extension via form closure; (2) Fewster, Ford & Roman arXiv:1004.0179 note [18] (Rayleigh-Ritz (a)=>(b), spectral support (b)=>(c), (c)=>(a)); (3) Fewster, Ford & Roman arXiv:1204.3570 Sec. I p.2 and Sec. VIII.A (which self-adjoint operator is meant; 'not fully resolved'); (4) Sanders arXiv:1010.3978v3 (2012) for the state of essential self-adjointness.",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "alphaXiv answer_pdf_queries on 2504.11718 (pp.1,3-5,7-10), 1204.3570 (pp.1-3,9-10,12,15,19-20,25), 1010.3978 (pp.1-2,5,9-15); 1004.0179 note [18] from the stage's own transcript src/1004.0179-note18.txt (alphaXiv full text, 2026-09-26). The 1934 classic and Reed-Simon are only restated."
 },
 "published_statement": "Friedrichs (as restated by Gesztesy-Sukhtaiev 2504.11718 Sec. 2): for S densely defined, symmetric and bounded below, the form q_S(f,g) = (f,Sg) on dom(S) is closable; its closure Q_S is associated by the first/second representation theorems with a self-adjoint S_F extending S, dom(Q_S) = dom(S_F^{1/2}) (2.18)-(2.19), S_F >= 0 when S >= 0 (2.14), and shifting commutes with the construction, (S + c I)_F = S_F + c I (2.21) -- so S >= -Q on dom(S) gives S_F >= -Q. Among non-negative extensions S_F is the largest, S_K <= S~ <= S_F (Krein, Thm 2.2); S_K has ker(S_K) = ker(S*) (2.11). Rayleigh-Ritz, as FFR 1004.0179 note [18] state it: for A self-adjoint with domain D(A), (a) <psi|A psi> >= -Q for all normalised psi in D(A) <=> (b) sigma(A) in [-Q, oo) <=> (c) supp mu_psi in [-Q, oo); '(a) => (b) is the Rayleigh-Ritz variational principle; (b) => (c) because measurements always give values in the spectrum; (c) => (a) because any random variable taking values in [-Q, oo) has its expected value in that range.' FFR 1204.3570 p.2: the smeared normal-ordered operators 'are defined, in the first instance, only as symmetric operators on a dense domain ... it is possible that there is more than one way of extending them ... bounded from below on account of quantum inequalities ... so there is a distinguished Friedrichs extension (see Ref. [17], Theorem X.23), whose lower bound coincides with the sharpest possible quantum inequality bound. It is this operator that we have in mind ... The question of whether there is more than one self-adjoint extension, i.e., whether the normal ordered expressions fail to be essentially self-adjoint, is nontrivial and not fully resolved.'",
 "published_hypotheses": [
  "F1 (Friedrichs) S densely defined in a Hilbert space",
  "F2 (Friedrichs) S symmetric",
  "F3 (Friedrichs) S bounded below on dom(S): (u, S u) >= -Q ||u||^2 (restated for S >= 0 plus the shift rule (2.21))",
  "F4 (conclusion scope) the bound is kept by S_F; other self-adjoint extensions need not keep it (S_K <= S_F; for S >= eps > 0 with nonzero deficiency, 0 in sigma(S_K))",
  "R1 (Rayleigh-Ritz, FFR note [18]) A self-adjoint; the form bound (a) holds on D(A) (equivalently on the form domain)",
  "R2 (support) mu_psi is the spectral measure of A in psi, 'the distribution of individual measurement results'",
  "P1 (FFR 1204.3570 Sec. I) real-valued smearing, so the smeared normal-ordered operator is symmetric on a dense domain; semiboundedness from the QEI",
  "P2 (FFR 1204.3570 Sec. I) the physical observable is TAKEN to be the Friedrichs extension; essential self-adjointness 'not fully resolved'"
 ],
 "hypothesis_drift": [
  "NONE DROPPED on the Friedrichs/Rayleigh-Ritz step. F1-F3 are present at noise.py:157-159 (H3: 'the smeared Wick-ordered operator on Hadamard vectors' -- dense, symmetric for the real sampler g^2, semibounded by Fewster (3)); F4 is carried VERBATIM in substance at noise.py:160-162 ('a different self-adjoint extension of a semibounded operator need not keep the Friedrichs lower bound. C1 is about the Friedrichs extension'), noise.py:324 (H3 'ASSUMED, load-bearing'), ledger.py:590 and specthm.py:2239; P2's 'not fully resolved' is quoted correctly at noise.py:160 and noise.py:324.",
  "ATTRIBUTION COMPRESSED (not an error): noise.py:172-173 writes '<psi, A_tau psi> >= -C/tau^4 for every psi in the form domain (Fewster (3); ...)'. Fewster's (3) is a statement over Hadamard states, i.e. on the dense domain; its passage to the whole form domain of A_tau is the Friedrichs form closure (2504.11718 Eqs. (2.15), (2.17)-(2.19)), which H3 supplies, not Fewster (3). The inequality is preserved under form-norm limits, so the statement is correct; only the citation carries two steps under one name. Re-derived on a model operator (rederive check 'form closure').",
  "WORDING, EQUIVALENT: noise.py:158-159 'its lower bound is the form bound' vs FFR 1204.3570 p.2 'whose lower bound coincides with the sharpest possible quantum inequality bound'. The infimum of the form over the dense domain IS the sharpest state-independent bound over those vectors, so the two agree. The tree then uses Fewster's NON-optimal -C/tau^4 (Fewster p.10 'known not to be optimal', audited under 1208.5399) only as a containment, sigma(A_tau) in [-C/tau^4, oo) (noise.py:174-175) and 'bounded below ... by -C/tau^4' (noise.py:29-31) -- never as inf sigma. No over-claim found.",
  "DOMAIN WORDING: noise.py:158 'Hadamard vectors' vs FFR 1204.3570 'a dense domain' and Sanders 1010.3978 'the natural (Wightman) domain' D_omega; vector states in D_omega of a quasi-free Hadamard state are Hadamard (Sanders uses omega'_2(f,h) = <psi, Phi(f)Phi(h) psi> for psi in D_omega, proof of Thm 5.3), so the Fewster bound applies on the domain the Friedrichs construction starts from. No drift.",
  "NOT ADDED by the tree, recorded: FFR 1204.3570 p.2 also say 'If there are distinct self-adjoint extensions, their corresponding probability distributions will all share the same moments in the vacuum state', and Sec. VIII.A that 'the conclusion that the probability distribution has a lower bound is independent of any concerns about uniqueness, because this follows from existing quantum inequality bounds'. The tree does not borrow VIII.A's sentence to weaken H3; it keeps H3 load-bearing, which is the more careful reading (VIII.A's claim is about moment-uniqueness for the extension Sec. I says they mean, and does not give a spectral lower bound for a non-Friedrichs extension, whose domain may leave the Friedrichs form domain -- see the Robin/Krein counterexamples in the rederivation)."
 ],
 "data_at_publication": [],
 "rederivation": {
  "method": "z3",
  "script_path": D + "rederive/" + KEY + ".py",
  "outcome": "18 PASS, 0 FAIL (exit 0; ~3-4 min, dominated by sympy Galerkin integrals). (ii) Rayleigh-Ritz: z3 over the reals finds NO real-symmetric 2x2 or 3x3 matrix with a normalised eigenvector whose eigenvalue lies below a form bound that holds at that vector (unsat, both sizes); (c)=>(a) unsat for a 4-atom measure on [-Q, oo); sympy: RQ at the ground vector of tridiag(-1,2,-1) equals lambda_min = 2 - sqrt2 exactly. (i),(iv) on the concrete unbounded operator S = -d^2/dx^2 on C_c^oo(0,1), form bound pi^2: Friedrichs = Dirichlet, ground RQ = pi^2 exactly (KEEPS the bound); compactly supported trials have RQ 13.709, 10.852, 10.066 >= pi^2 = 9.870, decreasing toward it (form closure); Krein-von Neumann extension has ker S* = span{1, x}, so 0 in sigma(S_K) < pi^2 (LOSES it); Robin extensions u'(0) = -k u(0), u'(1) = k u(1) have eigenvalue -K^2 with K tanh(K/2) = k: -2.3821 (k=1), -25.6403 (k=5), -2500.0000 (k=50), ~-1.0e8 (k=1e4), boundary residual <= 1.4e-41 relative, ODE exact in sympy; finite differences reproduce pi^2 (9.869592) and -25.640 (Robin k=5). So H3's caveat is not hypothetical: extensions of one semibounded operator (deficiency (2,2)) have lower bounds 0, negative, and arbitrarily negative. (v) clamped sampler: mu_1 = 4.730040744862704026 from cos mu cosh mu = 1, C = mu_1^4/(16 pi^2) = 3.169857938310468; Rayleigh-Ritz upper bounds from clamped polynomials are 504, 504, 500.584681, 500.563908, monotone and >= mu_1^4 = 500.563902 -- the variational principle as the tree uses it at noise.py:173 ('the Rayleigh quotient of the clamped mode is mu_1^4').",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Sanders, arXiv:1010.3978v3 (2012), 'Essential self-adjointness of Wick squares in quasi-free Hadamard representations on curved spacetimes'",
   "effect": "narrows",
   "what": "Proves the Wick square :Phi^2:(f) essentially self-adjoint on the Wightman domain for f in S (finite sums of squares of real SPACETIME test functions), any d >= 2, any quasi-free Hadamard state (Thm 5.8); with derivatives (energy density), only that T is e.s.a. IF its one-particle compression T_1 is (Thm 5.4), which is not shown for the stress tensor ('requires a study of its compression ... more complicated'). Notes that for f in S 'T is semi-bounded [10], which implies ... self-adjoint extensions (e.g. the Friedrichs extension)'. It does not cover the tree's operator: A_tau is the energy density (derivatives) smeared along a WORLDLINE (g(t)^2 delta^3(x), not a spacetime test function of class S). So H3 stays an assumption for A_tau; the open set of FFR's 'not fully resolved' is narrowed (Wick square settled) but not closed for the energy density, as far as read here.",
   "read_status": "READ (pp.1-2, 5, 9-15 page text)"},
  {"ref": "Gesztesy & Sukhtaiev, arXiv:2504.11718 (2025), 'Some Remarks on Krein-von Neumann Extensions'",
   "effect": "confirms",
   "what": "Restates the Friedrichs extension (form closure, (2.13)-(2.19)), its extremality S_K <= S~ <= S_F (Krein 1947, Thm 2.2), the shift rule (S+c)_F = S_F + c (2.21), and 0 in sigma(S_K) = ker(S*) for strictly positive S with nonzero deficiency. The theorem as the tree uses it is unchanged in 2025.",
   "read_status": "READ (pp.1, 3-5, 7-10 page text)"},
  {"ref": "Bostelmann & Fewster, arXiv:0812.4760, 'Quantum Inequalities from Operator Product Expansions'",
   "effect": "extends",
   "what": "Returned by discover_papers: QIs for local averages of Wick-square/energy-density type observables from OPEs, beyond free fields. Named for the semiboundedness input (F3) in wider settings; not read, not used.",
   "read_status": "NAMED-NOT-READ (discover_papers abstract only)"}
 ],
 "lacked_data": "No datum enters this result: Friedrichs (1934), Krein (1947) and the Rayleigh-Ritz principle are theorems of Hilbert-space operator theory with no measured input, and the rederivation shows no computation that moves them (18/18). What was lacking in 2012, by FFR's own account, is not data but a mathematical fact -- whether the time-smeared normal-ordered energy density is essentially self-adjoint (1204.3570 p.2, 'not fully resolved'). The later work read here (Sanders 2012 v3) settles the Wick square without derivatives for spacetime smearings in class S, and leaves the energy density conditional on its one-particle compression; it does not reach worldline smearing. So M's hypothesis has a precise, non-empirical form here: the missing item is a proof, and having it would change nothing in C1 if it came out 'essentially self-adjoint' (then the Friedrichs extension is THE self-adjoint operator and H3 is discharged), while a proof of NON-e.s.a. would not falsify C1 either (C1 is stated about the Friedrichs extension) but would reopen H6's identification of the physical observable, since the rederivation shows other extensions can sit arbitrarily far below the form bound. Evidence against 'the old math is wrong': the theorem restated in 2025 is the same, and it re-derives here in finite dimensions (z3) and on an explicit unbounded operator.",
 "grade": "STANDS",
 "grade_evidence": "Statement as used (noise.py:29-31, 172-177) matches the source: the Friedrichs extension of a densely defined, symmetric operator bounded below by -Q keeps the bound (2504.11718 (2.14), (2.18)-(2.21)); Rayleigh-Ritz (FFR 1004.0179 note [18], (a)=>(b)) puts its spectrum in [-Q, oo) and every spectral measure is supported there ((b)=>(c)). Hypotheses as used: F1-F3 present; the extension-dependence (F4) and FFR's 'not fully resolved' are carried as the NAMED, load-bearing, ASSUMED H3 (noise.py:157-162, 324; ledger.py:590; specthm.py:2239), and C1 is stated only for the Friedrichs extension -- nothing dropped, so NARROWED does not apply. Re-derivation agrees: 18 PASS / 0 FAIL, including the counterexamples that justify H3's caveat (Krein 0 and Robin -K^2 < pi^2 for extensions of one operator). No datum: DATA-DEPENDENT does not apply. No contradiction computed: WRONG is not available. Two recorded wording points (form-domain step cited to Fewster (3) though it is the Friedrichs closure; 'form bound' = FFR's 'sharpest QEI bound') are attribution, not error. The physical question whether A_tau is essentially self-adjoint remains OPEN in the literature read here; that openness belongs to H3, which the tree already marks ASSUMED, not to this theorem.",
 "what_would_change_the_grade": "NARROWED if a site in the tree were found to apply the lower bound to a self-adjoint realisation of A_tau other than the Friedrichs extension, or to drop H3 (e.g. a ledger row printing C1 as unconditional); none found in noise.py, ledger.py:559-590, specthm.py:2239 or LEDGER.md D22. A proof that the worldline-smeared energy density is essentially self-adjoint would discharge H3 (no grade change here; it would upgrade C1's status in the tree). A proof that it is NOT e.s.a. would leave this grade STANDS but would make H6's choice of observable a live modelling decision. Reading Friedrichs 1934 / Reed-Simon X.23 directly would move read_status to READ; a discrepancy between them and the 2025 restatement would be recorded as such.",
 "reverify_command": "python3 " + D + "rederive/" + KEY + ".py  # expect 18 PASS, FAILS: 0, exit 0 (~4 min); and: sed -n 150,177p /home/user/Claude-Method-Works/research/warp-drive/noise.py; sed -n 320,326p /home/user/Claude-Method-Works/research/warp-drive/noise.py; grep -n 'Friedrichs' /home/user/Claude-Method-Works/research/warp-drive/ledger.py /home/user/Claude-Method-Works/research/warp-drive/specthm.py",
 "report_path": D + "audits/" + KEY + ".json"
}
json.dump(rep, open(rep["report_path"], "w"), indent=1)
print("written", rep["report_path"])
