import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R=D+"/rederive/nmc-classical-nec-violation.py"
rep={
"key":"nmc-classical-nec-violation",
"name":"Non-minimally coupled scalar (xi R phi^2) violates NEC and WEC classically",
"source":{
 "located":"Primary: Barcelo & Visser, 'Scalar fields, energy conditions, and traversable wormholes', arXiv:gr-qc/0003025v2 (14 Jul 2000) = Class. Quantum Grav. 17 (2000) 3843; abstract p.1; action (2.1) p.3; stress tensor (2.2) and effective stress tensor (2.3) p.4; SEC (2.4), WEC (2.5) p.4; NEC (2.6) and its case analysis p.5. The tree's exact wording is FFKPS arXiv:2309.10848v1 sec. I p.3 ('Terms in the Lagrangian of the form delta L = xi R phi^2 (1) allow violations of the Null Energy Condition (NEC) even at the classical level'), with FFKPS sec. II A-B eqs (7)-(18) pp.5-7. Corroborating: Fewster & Osterbrink arXiv:0708.2450v2 sec. 1 p.1 (classical T 'does not satisfy the weak energy condition (WEC) at non-minimal coupling, i.e. xi != 0').",
 "read_status":"READ",
 "via":"alphaXiv was QUOTA-EXCEEDED for this stage (answer_pdf_queries, get_paper_content and discover_papers all returned 'alphaXiv assistant quota exceeded'); arxiv.org and osti.gov are egress-blocked. The three sources were therefore READ from the workflow's cached full texts obtained earlier through alphaXiv by sibling stages: src/gr-qc_0003025.txt (65,298 bytes, md5 c52fcce47e6efbe2d0683dc63c476263, header 'arXiv:gr-qc/0003025v2 14 Jul 2000'), src/2309.10848.txt, src/0708.2450.txt (header 'arXiv:0708.2450v2 [gr-qc] 23 Oct 2007'). Journal version of BV (CQG 17, 3843) NAMED-NOT-READ; BV's refs [14,15,16] and FO's refs [1,2] (the older classical examples) NAMED-NOT-READ."
},
"published_statement":"Barcelo-Visser abstract (p.1): 'We demonstrate that a non-minimally coupled scalar field with a positive curvature coupling xi > 0 can easily violate all the standard energy conditions, up to and including the averaged null energy condition (ANEC).' Sec. 2.2 (p.5), eq. (2.6): 'G_mn k^m k^n = (1/kappa)[T^eff]_mn k^m k^n = [phi'^2 - xi (phi^2)''] / (kappa - xi phi^2) >= 0. This condition is clearly satisfied by minimally coupled scalars. However, for xi != 0 it can be violated in a number of ways: For xi < 0 any local minimum of phi^2 violates the NEC while for xi > 0 and |phi| small, [meaning |phi| < (kappa/xi)^(1/2)], any local maximum of phi^2 violates the NEC. Finally for xi > 0 and |phi| large ... any local minimum of phi^2 violates the NEC.' And (p.5): the NEC 'is the weakest pointwise energy condition, that is, when it is violated the WEC and SEC are violated too.' FFKPS sec. I (p.3): 'Terms in the Lagrangian of the form delta L = xi R phi^2 allow violations of the Null Energy Condition (NEC) even at the classical level'; 'At the classical level, the effective NEC can be violated by non-minimal coupling of either sign ... However, the effective Averaged Null Energy Condition (ANEC) ... is satisfied' (under their EFT field-range assumption); 'classically, non-minimal coupling can be eliminated by a combined conformal transformation and field redefinition ... to the Einstein frame, where the NEC is obeyed.' FO 0708.2450 p.1: 'the stress-energy tensor of the classical scalar field, obtained from the Lagrangean L = 1/2 (grad phi)^2 - 1/2 (m^2 + xi R) phi^2, does not satisfy the weak energy condition (WEC) at non-minimal coupling, i.e., xi != 0'.",
"published_hypotheses":[
 "BV: classical (unquantised) real scalar field; the analysis is 'completely classical' (p.5)",
 "BV: action (2.1), S = 1/2 int sqrt(-g) kappa R + int sqrt(-g)[-1/2 (grad phi)^2 - V(phi) - 1/2 xi R phi^2], mostly-plus signature (v^2 = -1), kappa = 1/(8 pi G_N), four dimensions",
 "BV: energy conditions are imposed on the EFFECTIVE stress tensor T^eff (2.3), i.e. on the Einstein tensor of the metric g that appears in (2.1) (the Jordan-frame metric); requires kappa - xi phi^2 != 0",
 "BV: pointwise conditions along geodesics, k^m nabla_m k^n = 0 (affinely parametrised null geodesic); the NEC statement is independent of V (V drops out of the null contraction)",
 "BV: the statement is EXISTENTIAL -- 'can be violated', at configurations where the sign condition holds (at a suitable extremum of phi^2 along the null geodesic), not at every configuration",
 "BV: NEC violable for any xi != 0 (either sign); 'all standard energy conditions up to ANEC' is claimed for xi > 0; ANEC violation needs |phi| > (kappa/xi)^(1/2) (trans-Planckian) -- the tree does not use ANEC",
 "FFKPS: violation is of the 'effective NEC' in the Jordan frame; the Einstein-frame metric obeys the NEC (sec. I, sec. II)",
 "FO 0708.2450: classical WEC fails for xi != 0 (Birrell-Davies conventions, (+,-,-,-))"
],
"hypothesis_drift":[
 "SOURCE DROPPED: candidates.py:159-160 cites no source for the classical statement (the canonical entry records 'no source cited'); the wording is FFKPS 2309.10848 sec. I p.3 almost verbatim, a paper the tree cites 21 lines later (candidates.py:180-181), and the underlying result is Barcelo-Visser gr-qc/0003025 sec. 2.",
 "MODALITY STRENGTHENED: candidates.py:159-160 'violates the NEC and WEC' vs FFKPS 'allow violations' / BV 'can be violated'. Read literally as a property of every configuration it is false: constant phi gives (kappa - xi phi^2) G_kk = 0 (saturated, not violated), and rederive C1 shows that at a strict extremum of phi^2 one extremum type NEVER violates in each case. The tree's use (KIND gate, candidates.py:168 and CANDIDATES kind=True at candidates.py:453) needs only existence, so the existential reading is the one that is load-bearing.",
 "FRAME HYPOTHESIS DROPPED: candidates.py:159-160 does not say the violation is of the effective NEC for the Jordan-frame metric g. FFKPS sec. I: in the Einstein frame 'the NEC is obeyed'; rederive E8 computes it on a backreacted solution (Einstein-frame dH_E/dt_E <= 0 while Jordan Hdot > 0). The tree's own quoted FFKPS verdict (candidates.py:406-407, 'in the Jordan frame') shows the frame is known to the tree elsewhere but is not attached to line 159.",
 "xi != 0 LEFT IMPLICIT: candidates.py:159 writes 'coupled to curvature by delta L = xi R phi^2' without xi != 0; harmless (xi = 0 is 'not coupled'), and for the pointwise NEC no sign of xi is needed (BV, FFKPS: either sign). The very next claim (candidates.py:163, FO) is xi > 0 only; the classical statement is not so restricted.",
 "NORMALISATION / SIGN CONVENTION: candidates.py:159 'delta L = xi R phi^2' copies FFKPS eq. (1), whereas FFKPS's own action (7), BV (2.1) and FO (1) all carry -1/2 xi R phi^2 (with FO in (+,-,-,-)). Read literally, xi_tree = -xi_BV/2. For the pointwise NEC/WEC statement this is harmless (violation exists for either sign), so it is a notational discrepancy inherited from FFKPS's introduction, not a drift that changes the claim; it matters for xi > 0 statements downstream (FO; sibling audits 0708.2450 and gr-qc_0003025-wormhole-branch record the xi-sign issue).",
 "WEC ADDED relative to FFKPS's NEC-only sentence: supported -- BV p.5 (NEC violation implies WEC violation) and FO p.1 state it; rederive D2 (T_00 < 0 in a test field) and E6 (boosted observer G_vv < 0, backreacted) compute it. Note E7: in the backreacted flat-FRW example the COMOVING observer's energy density 3 kappa H^2 stays >= 0; the WEC failure there is for boosted observers.",
 "CLASSICAL = TEST FIELD OR BACKREACTED left unstated: BV's statement is on-shell backreacted (via T^eff); FO/FFKPS's flat-space statement is a test field. Both hold (rederive D and E), so no narrowing -- recorded for completeness."
],
"data_at_publication":[
 {"quantity":"Newton's constant G (sets kappa = 1/(8 pi G) and the small/large-field threshold |phi| = (kappa/xi)^(1/2) = M_red/sqrt(xi))",
  "value_then":"not used numerically in BV sec. 2 (symbolic kappa); CODATA 1998 G = 6.673(10)e-11 m^3 kg^-1 s^-2 was current in 2000 (not re-read this stage)",
  "value_now":"6.67430e-11 m^3 kg^-1 s^-2 (candidates.py:315; CODATA 2018 recommended value -- not re-read at source this stage)",
  "source_now":"candidates.py:315 (tree constant); CODATA not re-read here",
  "moves_conclusion":"No. The existence of NEC/WEC-violating configurations is independent of G: in the test-field example (rederive D3) the violation persists at amplitude 1e-20 in any units, and the backreacted example (E) is in units kappa = 1 with xi phi^2/kappa <= 0.09. G only relocates the threshold between the xi>0 small-field and large-field cases."},
 {"quantity":"Curvature coupling xi of any physical scalar (e.g. the Higgs)",
  "value_then":"unmeasured (BV sec. 5 discusses conformal xi = 1/6 as natural; Higgs not yet observed in 2000)",
  "value_now":"still unmeasured; only collider bounds exist (not READ at source this stage; sibling audits read Atkins-Calmet 1211.0281 for this)",
  "source_now":"none read this stage",
  "moves_conclusion":"No for the result as the tree uses it (a property of the theory for any xi != 0). It would bear on whether a realised field has xi != 0, which the tree does not claim at line 159."}
],
"rederivation":{
 "method":"sympy",
 "script_path":R,
 "outcome":"29 PASS, 0 FAIL, exit 0, ~11 s (sympy 1.14.0, z3 5.1.0, numpy 2.4.6; output rederive/nmc-classical-nec-violation.out). A1: BV (2.2) is covariantly conserved on-shell -- div T_nu = (box phi - V' - xi R phi) d_nu phi identically on a curved spherically symmetric metric with arbitrary A(t,r), B(t,r), phi(t,r), V. A2 (control): the trace-term sign printed in FFKPS eq. (9)/(15) (-g box phi^2) is not conserved -> misprint-class discrepancy in FFKPS, invisible to null contractions. B1-B2: for null k, T_kk = (k.dphi)^2 + xi[G_kk phi^2 - kk nabla nabla phi^2], V and trace terms drop, giving BV (2.6) exactly. C (z3, all reals): at a strict extremum of phi^2 along the null geodesic, xi<0 -> local MAX always violates, MIN never; xi>0 small field -> MIN always, MAX never; xi>0 large field -> MAX always, MIN never. This equals FFKPS's restatement (text after eq. 18) and is the exact SWAP of BV's prose on p.5 in all three cases -- a discrepancy between BV's words and BV's own equation (already recorded by sibling audit gr-qc_0003025-eq2.6-minimal-scalar-nec), not a refutation: that violation exists for xi != 0 is untouched. C4: at a zero of phi with phi' != 0 the NEC is violated iff xi > 1/2. C5: xi = 0 cannot violate. D: on-shell TEST FIELD in Minkowski, phi = c + eps(t^2 + z^2) (box phi = 0): T_kk(0) = -8 xi c eps, T_00(0) = -4 xi c eps -- NEC and WEC both violated for xi c eps > 0 at arbitrarily small amplitude (numeric xi=1/6, c=eps=1e-20). E: FULLY BACKREACTED flat FRW, V = m^2 phi^2/2, xi = 1, kappa = m = 1, phi0 = 0.3: RK4 with constraint preserved to 9e-16, max xi phi^2/kappa = 0.09 (sub-Planckian), 13 zero crossings; closed form Hdot = (2xi - 1) phidot^2/(2 kappa) at phi = 0, so G_kk = -2 Hdot < 0 at every crossing (Hdot = 2.9e-2, 1.4e-2, ...): Jordan-frame NEC violated on-shell; boosted observer (rapidity 3) G_vv = -5.86 < 0 (WEC). E8 control: along the same solution the Einstein-frame Hubble rate never increases (max dH_E/dt_E = -4.9e-10), confirming FFKPS's Einstein-frame statement. F: BV contracted gives T_kk = (1-2xi)phi'^2 - 2xi phi kk nabla nabla phi + xi R_kk phi^2; FFKPS eq. (13) as printed carries -xi R_kk phi^2 (differs by 2 xi R_kk phi^2; zero in flat space; FFKPS's effective form (16)/(18) agrees with BV 2.6) -- discrepancy recorded, possibly a convention not visible in the text, not graded.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"Fliss, Freivogel, Kontou & Pardo Santos, arXiv:2309.10848 (2023; SciPost Phys. 16, 119 (2024) per web-search listing)","effect":"narrows","what":"Confirms classical effective-NEC violation for xi of either sign (sec. I, eq. 18 with the correct max/min assignment); narrows its reach: (i) Einstein frame obeys the NEC classically; (ii) under an EFT cutoff on field values the effective ANEC is satisfied classically and quantum mechanically. Neither narrowing touches the pointwise NEC/WEC claim at candidates.py:159, which is about the Jordan frame and does not claim ANEC.","read_status":"READ (cached full text src/2309.10848.txt, secs I, II A-B)"},
 {"ref":"Fewster & Osterbrink, arXiv:0708.2450 (2007/2008, J. Phys. A 41, 025402)","effect":"confirms","what":"Sec. 1: classical T for xi != 0 does not satisfy the WEC ('for more than 30 years it has been known'); the rest of the paper is the quantum result audited separately (audit 0708.2450).","read_status":"READ (cached full text src/0708.2450.txt, sec. 1-2)"},
 {"ref":"Fewster & Osterbrink, 'Averaged energy inequalities for the non-minimally coupled classical scalar field', arXiv:gr-qc/0606009, Phys. Rev. D 74, 044021 (2006)","effect":"narrows","what":"Per the web-search abstract listing only: pointwise energy conditions fail for the classical NMC field, but local averages obey inequalities; along causal geodesics in Ricci-flat backgrounds ANEC and AWEC hold. Confirms the pointwise claim; bounds its magnitude and averaged reach. Not graded on, since not read at source.","read_status":"NAMED-NOT-READ (abstract seen only as a WebSearch summary; arxiv.org and osti.gov egress-blocked, alphaXiv quota exceeded)"},
 {"ref":"discover_papers search for further later work","effect":"contested","what":"The one allotted discover_papers call failed ('alphaXiv assistant quota exceeded'); a WebSearch substitute returned only the papers above plus BV itself. No contradiction of the classical pointwise claim was found, but the later-literature search is INCOMPLETE and is recorded as such.","read_status":"NOT RUN (tool quota)"}
],
"lacked_data":"M's hypothesis tested: the result is a classical kinematic identity (BV 2.6, from the variational stress tensor 2.2) plus the existence of configurations meeting its sign condition. No empirical datum enters the conclusion -- rederive B1 shows V drops out, C shows the case analysis is pure algebra over the reals, D shows a violating on-shell test field at any amplitude, E shows a violating backreacted solution in kappa = 1 units. What BV lacked in 2000 (the Higgs discovery in 2012, precise G, any measurement of xi) cannot move it: G only relocates the small/large-field threshold; xi is still unmeasured and the claim holds for every xi != 0. Evidence the other way -- what later work added that DOES qualify it -- is conceptual, not data: the Einstein-frame NEC holds (FFKPS; computed E8), and averaged conditions hold under field-range limits (FFKPS; FO 2006 per abstract listing). Those qualify what the violation BUYS, not whether it exists, and the tree's own candidates.py already carries the FFKPS limitation for the magnitude gate. Verdict on M's hypothesis for this result: no missing datum changes the conclusion; one discrepancy (BV's prose swap of maxima/minima) was found and was corrected in the later literature (FFKPS 2023) -- a misprint-class discrepancy, not a refutation.",
"grade":"NARROWED",
"grade_evidence":"The mathematics STANDS: BV's stress tensor is conserved on-shell (A1), eq. (2.6) re-derives exactly (B1-B2), and NEC and WEC violation is exhibited both for an on-shell test field in Minkowski at arbitrarily small amplitude (D1-D3) and on a fully backreacted, sub-Planckian flat-FRW solution (E5-E6); no datum enters. The grade is NARROWED, not STANDS, because candidates.py:159-160 states it on a larger class than the sources do: (i) categorical 'violates' where BV/FFKPS say 'can be violated'/'allow violations' -- constant phi saturates rather than violates, and at an extremum of phi^2 one type never violates (C1); (ii) the Jordan-frame / effective-NEC hypothesis is dropped -- the Einstein-frame NEC holds (FFKPS sec. I; computed E8); (iii) no source is cited. The narrowing does NOT move the tree's use: the KIND gate (candidates.py:168, CANDIDATES kind=True at :453) needs only existence of violating configurations in the metric ordinary matter follows, which holds. Not over-represented in M's favour either: BV's p.5 prose swaps maxima and minima relative to its own (2.6) (C3) and FFKPS eqs (9) and (13) carry sign discrepancies (A2, F2) -- all recorded as discrepancies, none a refutation, none affecting the existence claim. Not WRONG: no counterexample to the existential statement exists (D, E are witnesses). Source read from cached alphaXiv full texts because alphaXiv was quota-exceeded this stage.",
"what_would_change_the_grade":"To STANDS: candidates.py:159-160 reworded as existential ('allows / can produce violations of the NEC and WEC') for the Jordan-frame metric (effective NEC), with BV gr-qc/0003025 sec. 2.2 or FFKPS 2309.10848 sec. I-II cited. To WRONG: a proof that no classical on-shell configuration with xi != 0 has G_kk < 0 for the Jordan metric -- contradicted here by the explicit witnesses D and E, so not expected. To DATA-DEPENDENT: none foreseeable; no datum enters. A later-literature read (the failed discover_papers call; FO gr-qc/0606009 at source; BV's journal version) could add qualifications but cannot remove the witnesses computed here.",
"reverify_command":"python3 "+R+"  # expect 'SUMMARY: 29 PASS, 0 FAIL', exit 0; source lines: sed -n 440,540p "+D+"/src/gr-qc_0003025.txt ; sed -n 72,125p "+D+"/src/2309.10848.txt ; sed -n 155,170p /home/user/Claude-Method-Works/research/warp-drive/candidates.py",
"report_path":D+"/audits/nmc-classical-nec-violation.json"
}
json.dump(rep,open(rep["report_path"],"w"),indent=1)
print("ok")
