import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R=D+"/rederive/kibble-1976-zurek-1985.py"
rep={
"key":"kibble-1976-zurek-1985",
"name":"Kibble-Zurek mechanism: rapid quench through symmetry breaking gives a topological-defect network",
"source":{
 "located":"T.W.B. Kibble, 'Topology of cosmic domains and strings', J. Phys. A 9 (1976) 1387; W.H. Zurek, 'Cosmological experiments in superfluid helium?', Nature 317 (1985) 505. Both pre-arXiv. Intended restatements: A. del Campo & W.H. Zurek, 'Universality of phase transition dynamics: topological defects from symmetry breaking', arXiv:1310.1600 (IJMPA 2014) -- identity corroborated only by a WebSearch listing -- and W.H. Zurek, Phys. Rep. 276 (1996) 177, cond-mat/9607135.",
 "read_status":"NAMED-NOT-READ",
 "via":"NOT reached at source this stage. alphaXiv answer_pdf_queries (1310.1600, 1508.07161, cond-mat/9607135), get_paper_content(fullText) (1310.1600, 1508.07161) and discover_papers each returned 'alphaXiv assistant quota exceeded'. curl to arxiv.org: CONNECT 403; WebFetch to ar5iv.org, en.wikipedia.org, www.nature.com, journals.aps.org: EGRESS_BLOCKED. Two WebSearch summaries were seen (a search-engine paraphrase of 1310.1600's abstract: KZM concerns 'a non-equilibrium continuous phase transition', adiabaticity fails 'due to critical slowing down', 'can lead to topological defect formation'; and of electroweak-string stability work) -- a summary is not a verbatim read, so nothing is marked READ. The owner itself says 'RECORDED AS ELEMENTARY; no source read for it here' (warpfolder.py:79). The standard form of Zurek's freeze-out argument used in the re-derivation is written from the argument itself, not quoted."},
"published_statement":"NOT READ at source; no verbatim quotation is offered. What the standard statement is usually taken to be (UNQUOTED, for orientation only, and graded on nothing): Kibble 1976 -- at a symmetry-breaking transition G -> H the order parameter takes values in the vacuum manifold M = G/H; causally disconnected regions choose points of M independently, and topologically stable defects form with density set by the correlation length, their type fixed by the homotopy of M (pi_0: walls, pi_1: strings, pi_2: monopoles). Zurek 1985 -- for a quench through a CONTINUOUS transition, critical slowing down (tau ~ tau0/|eps|^(z nu)) makes the dynamics freeze out at t^ ~ (tau0 tau_Q^(z nu))^(1/(1+z nu)), fixing domain size xi^ = xi0 (tau_Q/tau0)^(nu/(1+z nu)) and defect density ~ xi^-(D-d). The WebSearch paraphrase of arXiv:1310.1600 is consistent with this but is not a read.",
"published_hypotheses":[
 "(as usually stated; NOT READ) a symmetry-breaking phase transition G -> H with a genuine order parameter",
 "(Zurek; NOT READ) the transition is continuous (second order): equilibrium relaxation time and correlation length diverge at the critical point (critical slowing down), with exponents nu, z",
 "(Kibble; NOT READ) the vacuum manifold G/H has a nontrivial homotopy group pi_k appropriate to the defect (pi_0 walls, pi_1 strings, pi_2 monopoles in 3 space dimensions); only then are the defects topologically stable",
 "(both) causally disconnected / dynamically uncorrelated regions make independent choices; the quench rate relative to the relaxation time sets the domain size",
 "(gauge theories, NAMED-NOT-READ: Hindmarsh-Rajantie flux trapping; geodesic rule) for a gauged order parameter the 'phase' is gauge-dependent and the defect count is set by gauge-invariant windings/flux, a distinct mechanism from the global-symmetry KZM"],
"hypothesis_drift":[
 "DROPPED -- nontrivial homotopy of the vacuum manifold. warpfolder.py:77-79 ('The generic output of a rapid quench through a symmetry-breaking transition is a TOPOLOGICAL DEFECT NETWORK') applied, in context (warpfolder.py:65-72), to the Standard Model electroweak transition. The SM Higgs vacuum manifold is S^3 (computed: rederive A1-A5) and pi_0, pi_1, pi_2 of S^3 are trivial (witnessed: B1-B3), so in 3 space dimensions there are no topologically stable walls, strings or monopoles to form a network. The canonical entry already flags this hypothesis ('not addressed by owner'); this audit computes it.",
 "DROPPED -- a genuine (continuous) phase transition. warpfolder.py:77 says 'a symmetry-breaking transition'; the same file at warpfolder.py:69 says 'Raising T to the crossover', and the tree's own READ of D'Onofrio-Rummukainen 1508.07161 footnote 1 (massform.py:1127-1136, 'DRT-vev') is 'Although there is no real symmetry breaking phase transition, we use the conventional labels broken and symmetric'. Zurek's scaling needs critical slowing down; in a crossover tau and xi stay bounded and the KZ power law saturates (computed: rederive C3). Internal tension in the tree, recorded not repaired.",
 "WEAKENED -- 'picks independent phases' (warpfolder.py:75-76) is the global-symmetry picture; for the gauged Higgs the phase is gauge-dependent (tree-level fact READ-VIA-RESTATEMENT in the sibling audit sm-higgs-doublet-gauge-structure: Maas 1712.04721 p.2, 'v ... is dependent on the gauge'), and the gauge-invariant version of the argument is not addressed by the owner.",
 "UNQUANTIFIED -- 'rapid quench' (warpfolder.py:77): the owner names no quench time and no relaxation time, so 'rapid relative to the relaxation time' is asserted, not checked. Not checkable here: the device document's flash cooling time is not in the tree.",
 "NO CHECK ON THE FLAG -- QUENCH_GIVES_A_TEMPLATED_OBJECT = False (warpfolder.py:244) is defined and never asserted by warpfolder's selftest (grep: its only occurrence in research/warp-drive is line 244); the printed restatement at warpfolder.py:397-398 carries no hypotheses. The downstream owners do not read it: ledger S9 (LEDGER.md:66) cites reason (a) only, and specthm.py:1181-1182 (R11) reads FLASH_IS_A_RECONSTRUCTION_MECHANISM and HEATING_TO_EW_SCALE_RESTORES_SYMMETRY, not this flag."],
"data_at_publication":[
 {"quantity":"Higgs mass (decides whether the SM EW transition is first order or a crossover)","value_then":"unknown in 1976 and 1985 (Higgs not discovered until 2012); the crossover for m_H above a ~72 GeV endpoint was established by lattice work from 1996 (Kajantie et al., NAMED-NOT-READ)","value_now":"125.130 GeV (research/warp-drive/captures/PDG-2026.tsv row 25, the tree's PDG-2026 capture); 1.74x the ~72 GeV endpoint","source_now":"PDG 2026 via scikit-hep particle 1.0.1, as captured in the tree (not re-read this stage); endpoint value NAMED-NOT-READ","moves_conclusion":"It moves the TRANSITION hypothesis, not the external theorem: at m_H = 125 the SM has no phase transition, so Zurek's critical scaling does not apply to it (C3). It does not move the tree's conclusion 'not a templated object' (see C5 and lacked_data)."},
 {"quantity":"m_H^2/m_Z^2 and sin^2 theta_W (decide stability of the non-topological Z/semilocal strings, the only string-like EW objects)","value_then":"not relevant to Kibble 1976/Zurek 1985; Z-strings were introduced 1992 (Vachaspati, NAMED-NOT-READ)","value_now":"beta = 1.8830 (m_H 125.130, m_Z 91.1879 GeV), on-shell sin^2 theta_W = 0.2233 (from m_W 80.362) -- computed from the tree's PDG-2026 capture","source_now":"research/warp-drive/captures/PDG-2026.tsv rows 23-25; stability criterion (James-Perivolaropoulos-Vachaspati 1993, 'unstable for m_H > 23 GeV at sin^2 theta_W = 0.23' per a WebSearch summary) NAMED-NOT-READ","moves_conclusion":"No: every reading of it seen points the same way (no stable EW string network), which reinforces the drop of the homotopy hypothesis; the criterion itself is not READ, so it carries no weight in the grade."},
 {"quantity":"T_EW (tree constant T_EW_CROSSOVER_GEV, warpfolder.py:230, status 'ORDER')","value_then":"not an input of Kibble/Zurek","value_now":"159.5 +/- 1.5 GeV as the tree quotes 1508.07161 (massform.py:1116-1125; sibling audit 1508.07161 graded that read OPEN); tree 160 GeV is 0.33 sigma away; 160 GeV = 1.8567e15 K","source_now":"massform.py DR-Tc quotation (tree's READ, not independently re-read)","moves_conclusion":"No; used only for the printed temperature in reason (a)."}],
"rederivation":{"method":"sympy","script_path":R,
 "outcome":"16/16 checks PASS (exit 0). A (sympy): H^dag H = |x|^2 so the vacuum manifold is S^3; an explicit SU(2) matrix with U^dag U = 1, det U = 1 carries (0, v/sqrt2) to every vacuum (transitive); 4 - 1 = 3 = dim S^3. B (numeric witnesses, seed 67): pi_0 -- arc between random vacua stays on S^3; pi_1 -- 20 random Fourier loops, pi_2 -- 10 random smooth 2-spheres, each null-homotoped on S^3 by missing a point, stereographic projection, straight-line contraction in R^3 and inverse projection (|q|^2 - 1 < 1e-12 throughout). This is a witness of the standard dimension argument (a smooth k<3 dimensional image misses a point of S^3), not a formal proof over all maps; pi_3(S^3) = Z (textures) is stated, NOT computed, and texture stability is not decided. C (sympy): Zurek's freeze-out solved symbolically -- t^ = (tau0 tau_Q^(z nu))^(1/(1+z nu)), xi^ = xi0 (tau_Q/tau0)^(nu/(1+z nu)); exponents 1/4 (mean field), 0.2866 (3D XY, nu = 0.6717, z = 2, value from memory). Crossover model (tau, xi regulated by d = 0.05): xi^ saturates at xi_max = 4.4721 for tau_Q >= 1e6 while the critical xi^ keeps growing as tau_Q^(1/4); for a rapid quench (tau_Q = 1) the two agree to 0.03 %. D: data as in data_at_publication. What is NOT re-derived: any statement quoted from Kibble 1976 or Zurek 1985 (neither READ).",
 "agrees_with_source":"partly"},
"later_literature":[
 {"ref":"A. del Campo & W.H. Zurek, arXiv:1310.1600, IJMPA 29 (2014) 1430018","effect":"confirms","what":"Per a WebSearch paraphrase only: KZM is stated for a non-equilibrium CONTINUOUS phase transition with critical slowing down, and 'can lead to' topological defect formation -- i.e. the two hypotheses this audit finds dropped are part of the mechanism's own statement.","read_status":"NAMED-NOT-READ (WebSearch summary; alphaXiv quota exhausted; arxiv.org egress-blocked)"},
 {"ref":"H.-K. Zeng et al., 'Universal breakdown of Kibble-Zurek scaling in fast quenches across a phase transition', PRL 130 (2023) 060402; arXiv:2506.06841 'Verified universal breakdown...'","effect":"narrows","what":"Per WebSearch paraphrase: for quenches faster than a critical rate, defect density and freeze-out time become independent of the quench rate -- the KZ power law is a slow-quench law. Bears on the tree's 'rapid quench' wording: the fast end is not KZ scaling, though domains are still uncorrelated.","read_status":"NAMED-NOT-READ (WebSearch listing/summary only)"},
 {"ref":"M. James, L. Perivolaropoulos, T. Vachaspati, 'Detailed stability analysis of electroweak strings', Nucl. Phys. B 395 (1993) 534; A. Achucarro & T. Vachaspati, 'Semilocal and electroweak strings', Phys. Rep. 327 (2000) 347 (hep-ph/9904229)","effect":"narrows","what":"Per WebSearch summary: Z-strings at sin^2 theta_W = 0.23 are unstable for m_H above ~23 GeV; the SM's string-like objects are non-topological. Consistent with the computed trivial pi_1(S^3).","read_status":"NAMED-NOT-READ"},
 {"ref":"M. D'Onofrio & K. Rummukainen, arXiv:1508.07161, PRD 93 (2016) 025003","effect":"narrows","what":"As the tree quotes it (massform.py:1127-1136): 'Although there is no real symmetry breaking phase transition' -- the SM at m_H = 125 is a crossover, so no critical point for Zurek's scaling.","read_status":"READ by the tree (massform.py DRT-vev); not re-read this stage; sibling audit graded that read OPEN"},
 {"ref":"discover_papers call","effect":"contested","what":"The one discover_papers call permitted returned 'alphaXiv assistant quota exceeded'; no later-literature search through alphaXiv was possible. The entries above come from WebSearch listings and the tree's own reads.","read_status":"NOT RUN (quota)"}],
"lacked_data":"What Kibble (1976) and Zurek (1985) lacked that bears on the TREE'S use: the Higgs mass (discovered 2012) and the non-perturbative lattice result that the SM electroweak transition is a crossover for m_H above ~72 GeV (1996 onward; 1508.07161 at m_H = 125). Having it does NOT change the KZ mechanism itself -- nothing seen here, read or computed, refutes it within its hypotheses (continuous transition, nontrivial homotopy); the rederived freeze-out algebra agrees with the standard form. What the later data changes is the APPLICABILITY to the SM: (i) no true transition, so Zurek's critical scaling does not apply (C3: xi^ saturates); (ii) the vacuum manifold S^3 has trivial pi_0..pi_2 (A, B), a fact independent of any datum and available in 1976 -- it is not a data gap of the authors but a hypothesis the tree drops. Evidence the other way, also recorded: the tree's conclusion QUENCH_GIVES_A_TEMPLATED_OBJECT = False is not moved -- for a rapid quench the critical and crossover models give the same freeze-out domain (C5, 0.03 %), so domains are uncorrelated either way, and neither KZM nor anything read here supplies a channel by which a template could bias the ordering. That last point is an absence of a mechanism, not a theorem; it is NOT established here that the uncorrelated EW domains relax to a uniform vacuum rather than some other state. M's hypothesis is therefore not supported for this result: the authors lacked data, but the data that came later narrows where the tree may invoke them, not what they said.",
"grade":"NARROWED",
"grade_evidence":"The source could not be READ (alphaXiv quota exhausted on all three tools; arXiv/ar5iv/Wikipedia/Nature/APS egress-blocked), so the published wording and exponents are OPEN and no quotation from Kibble or Zurek is offered. The NARROWING does not rest on reading them: it rests on (1) a computation here -- the SM Higgs vacuum manifold is S^3 (sympy A1-A5) with trivial pi_0, pi_1, pi_2 (numeric null-homotopy witnesses B1-B3), so a 'TOPOLOGICAL DEFECT NETWORK' (warpfolder.py:77-79) has no stable walls, strings or monopoles to be made of in the SM case the owner applies it to; a topological defect is by definition a nontrivial homotopy class, so this holds whatever the sources' wording; and (2) the tree's own READ (massform.py:1127-1136, 1508.07161 fn.1 'no real symmetry breaking phase transition') plus warpfolder.py:69 'the crossover', against warpfolder.py:77 'a symmetry-breaking transition' -- Zurek's scaling needs a critical point, and in a regulated (crossover) model the freeze-out length saturates (C3). So the result holds on a smaller class (continuous transitions with nontrivial homotopy) than the tree uses (the SM EW crossover). NOT WRONG: nothing shown refutes KZM within its hypotheses, and the tree's conclusion that the quench does not give a templated object is not contradicted (C5: rapid-quench domains are uncorrelated in both models). NOT DATA-DEPENDENT for the external result: the homotopy fact involves no datum; the Higgs mass moves only the applicability. Downstream: S9 (LEDGER.md:66) and R11 (specthm.py:1181-1182) read reasons (a) and FLASH flags, not QUENCH_GIVES_A_TEMPLATED_OBJECT, and the owner states (a), (b), (c) are each independently sufficient (warpfolder.py:107) -- (a) and (c) are not audited here. A discrepancy, not a refutation: the owner's reason (b) says 'defect network' where for the SM the computed statement is 'no topologically stable defects'; recorded, not repaired, and MUST NOT be quoted as an error in the journal version of either source.",
"what_would_change_the_grade":"To STANDS: the owner restricting (b) to 'uncorrelated domains / no templating channel' with the vacuum manifold and crossover named as hypotheses, AND a verbatim read of Kibble 1976 / Zurek 1985 (or 1310.1600, cond-mat/9607135) confirming the statement and hypotheses as restated. To OPEN: if the homotopy computation were set aside (it is not a read), the grade would fall to OPEN for want of the source. To WRONG: a READ showing the tree's application to the SM claims stable defects form -- none seen. A read of the Hindmarsh-Rajantie gauge-theory mechanism or of lattice real-time studies of the EW crossover (non-topological transients, magnetic fields, Chern-Simons winding) could refine what the SM quench does produce; none was readable here.",
"reverify_command":"python3 "+R+"  # expect 'ALL A-D CHECKS PASS', exit 0 (16 checks); then: grep -n 'QUENCH_GIVES_A_TEMPLATED_OBJECT' -r /home/user/Claude-Method-Works/research/warp-drive --include=*.py  # only warpfolder.py:244; sed -n 65,80p /home/user/Claude-Method-Works/research/warp-drive/warpfolder.py; sed -n 1126,1137p /home/user/Claude-Method-Works/research/warp-drive/massform.py",
"report_path":D+"/audits/kibble-1976-zurek-1985.json"}
json.dump(rep,open(rep["report_path"],"w"),indent=1)
print("ok")
