import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
r = {
 "key": "gklp-rank1-moving-brane-no-ctc",
 "name": "GKLP: no closed causal curve on a moving brane in M4 x S1 (rank-1 spatial compactification)",
 "source": {
  "located": "Greene, Kabat, Levin, Porrati, 'Back to the Future: Causality on a Moving Braneworld', arXiv:2208.09014v3 (24 Jan 2023), Phys. Rev. D 107, 025016 (2023) -- the paper whose initials are GKLP. Its predecessor, Greene, Kabat, Levin, Menon, 'Superluminal Propagation on a Moving Braneworld', arXiv:2206.13590v2, PRD 106, 085001 (2022), is GKLM, not GKLP; it sets up the geometry (eqs. 1-3) and carries no causality/CTC claim.",
  "read_status": "READ",
  "via": "alphaXiv answer_pdf_queries: full page text of 2208.09014v3 (pp. 1-17) and 2206.13590v2 (pp. 1-19). latticectc.py cites no arXiv id for GKLP; the identification rests on the matching setup and matching eq. (22) cited in branelink.py:81, and on ledger.py/LEDGER.md naming 2208.09014."
 },
 "published_statement": "2208.09014 abstract: 'Brane observers executing appropriate motion through a partially compactified Lorentz invariant bulk spacetime, such as M4 x S1, can send signals along the brane that are instantaneous or even travel backward in time. Nevertheless, causality in the braneworld remains intact.' p.4: 'A quick argument suggests that this cannot happen. In the covering space, image points that are mutually identified all lie outside of each other's respective lightcones. This ensures that no image signal identified with that emitted from a given point can lie in that point's past lightcone.' Sec. 4, eqs. (27)-(28): out-and-back time T = D(1/v - 1/w) = 2D/v_eff with v_eff = gamma(1 + Gamma^2 B^2 beta^2), 'always positive ... 0 < T <= 2D/gamma. An instantaneous round trip is possible but closed time-like curves are not.' Eqs. (29)-(32): with a brane-direction circle L' added, total return time Gamma L'/gamma (1+B/gamma)/(1+Gamma^2 B^2 beta^2) > 0, 'no causality violation'. Sec. 6: 'all roundtrip signals return to their starting location after a non-negative amount of elapsed time, obviating the possibility of causality-challenging closed timelike curves.' Sec. 5: free-scalar commutator has a well-defined causal future and past on the brane; 'we expect causality to be robust with respect to interactions'.",
 "published_hypotheses": [
  "bulk is flat ('Lorentz invariant bulk'), M4 x S1 = M5 with z ~ z + 2 pi R n, purely spatial identification in a preferred frame (2206.13590 eq. 1; 2208.09014 eq. 1)",
  "brane-frame identification (t', z') ~ (t', z') + (-gamma beta 2 pi R, gamma 2 pi R) (eq. 6/8); observer boost B along the brane gives eq. (10)",
  "ONE brane (with its covering-space images z = beta t + 2 pi R n), constant velocity |beta| < 1, flat, untilted, no back-reaction on the bulk (implicit: static bulk geometry)",
  "brane observers at constant velocity B in (0,1), including supercritical Gamma^2 B > 1/(gamma beta^2)",
  "explicit round trips are collinear out-and-back trips along x'' built from the late-time envelope velocities v, w (eqs. 20, 25), plus one trip around an added brane circle (eq. 29); the general bulk statement is given only as the p.4 'quick argument' ('suggests')",
  "microcausality: free massless scalar only; interactions 'expected', not shown"
 ],
 "hypothesis_drift": [
  "ADDED (by the owner, as its own theorem, not attributed to GKLP): 'any number of branes, any velocities' (latticectc.py:35-38) -- GKLP have one brane at one beta. Legitimate under the owner's H3 (latticectc.py:21-23): in a flat quotient with test branes causal curves are unconstrained, so brane content is irrelevant; re-derived here (z3 + Lagrange/scalar lemma). Not a drift in GKLP's result; an extension proved in the tree.",
  "ADDED: 'any chain length' (latticectc.py:38) -- GKLP compute two-leg (out-and-back) and one-circuit trips; the K-leg generalisation is the owner's reduction lemma (latticectc.py:25-32), re-derived here for every K by the cone-closure route.",
  "ADDED: 'any tilt' (latticectc.py:37) -- not in GKLP; covered by Polychronakos 2210.11497 eq. 2.4 (periodicity vector norm R^2 for every tilt and boost, checked here) and Debolt & Kagan 2602.13448. Consistent.",
  "DISCREPANCY (characterisation of the source): latticectc.py:23 says the owner's H3 is 'stronger than GKLP, who keep it on branes'. GKLP's explicit Sec. 4 trips are brane-endpoint envelope trips, but their p.4 'quick argument' is exactly the unconstrained-bulk, rank-1 statement (identified images mutually spacelike), and Polychronakos 2210.11497 sec. 3.1/4 attributes that argument to them ('As also noted in [2]'). The tree's claim of strength is true against GKLP's COMPUTED trips and overstated against their stated argument; the tree's contribution is to make the quick argument a checked theorem with the K-leg reduction. Recorded, not repaired.",
  "DISCREPANCY (naming): ledger.py:1863 / LEDGER.md O6 and branelink.py:17 speak of 'the two GKLP papers'; 2206.13590 is Greene-Kabat-Levin-MENON (GKLM), 2208.09014 alone is GKLP. latticectc.py carries no arXiv id for GKLP at all (status_word 'none'). A citation defect, not a mathematical one.",
  "DIMENSION suppressed: owner's xi = (-gamma beta, 0, 0, gamma) (latticectc.py:129-131, 179-184) is a 3+1 covering-space vector; GKLP's bulk is 4+1 (brane has 3 spatial directions). Harmless: xi has zero brane-direction components and cone closure holds in every dimension (H1 is R^{1,d}).",
  "NOT DROPPED, correctly named by the owner: flat bulk (H1), free translation quotient (H2 -- excludes orientation-reversing/glide identifications such as the later GKLP Klein-bottle compactification 2510.05270), test branes/no back-reaction (H3). GKLP leave no-back-reaction implicit; the owner names it."
 ],
 "data_at_publication": [
  {"quantity": "brane velocity beta", "value_then": "free parameter |beta| < 1; figures at beta = 0.6 (2208.09014 Figs. 2-6; 2206.13590 Figs. 3-4)", "value_now": "free parameter; owner uses beta = 3/5 exactly (latticectc.py:131)", "source_now": "latticectc.py:131; GKLP figure captions", "moves_conclusion": "no -- |xi|^2 = (2 pi R)^2 > 0 identically in beta (sympy, check A); T > 0 for all B, beta"},
  {"quantity": "compactification radius R (2 pi R = 1 in owner units)", "value_then": "free; R = 1 in GKLP figures", "value_now": "free; 2 pi R = 1 (latticectc.py:129)", "source_now": "latticectc.py:129", "moves_conclusion": "no -- enters only as an overall scale of xi"},
  {"quantity": "observer boost B, critical value", "value_then": "Gamma^2 B_crit = 1/(gamma beta^2); B_crit = 0.8 at beta = 0.6 (Fig. 3 caption)", "value_now": "recomputed: B_crit = 0.8 at beta = 0.6 (nsolve)", "source_now": "rederive check B", "moves_conclusion": "no -- supercritical one-way legs are negative (checked, B = 0.9) but every round trip stays positive"},
  {"quantity": "GW170817 speed bound -3e-15 <= dc/c <= 7e-16 (2206.13590 eq. 39)", "value_then": "Abbott et al. 2017, used to bound beta today if the graviton is a bulk field", "value_now": "unchanged bound family; not an input to the no-CTC result", "source_now": "2206.13590 eq. (39) as read", "moves_conclusion": "no -- constrains the size of beta, not the sign of |xi|^2; the no-CTC conclusion holds for every |beta| < 1"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/gklp-rank1-moving-brane-no-ctc.py",
  "outcome": "34/34 checks ok, exit 0, ~1.5 s (output in rederive/gklp-rank1-moving-brane-no-ctc.out). (A) sympy: GKLP eq. 8 and eq. 10 identification vectors have norm exactly L^2 for all |beta|,|B| < 1; owner's xi = (-3/4,0,0,5/4), |xi|^2 = 1 exact. (B) sympy: GKLP eq. 17 consistent with tan alpha = Gamma gamma beta; eqs. 20 and 25 follow from tan(theta +- alpha); eq. 22 at cos theta = 1 equals eq. 20 (their eqs. 23-24); eq. 28 v_eff = gamma(1+Gamma^2B^2beta^2); eq. 32 closed form; B_crit = 0.8 at beta = 0.6. (C) numeric, INDEPENDENT of GKLP's envelope construction: earliest arrival on the brane axis from the bulk quotient, min over winding of n xi_t + |X - n xi_s|, reproduces 1/v and -1/w to 1e-7 at B = 0, 0.4, 0.7, 0.9. (D) integer-winding round trips: T > 0 in all 30 (B, D) cases, B up to 0.99, although the supercritical outgoing leg is negative; z3: spacelike xi implies n xi_t + |n||xi_s| > 0 for n != 0 (negation unsat), which with the triangle inequality gives T > 0 for every round trip. (E) z3: no nonzero causal real multiple of a spacelike vector; no K = 1, 2 future-causal chain sums to m xi_owner for any 0 < |m| <= 6; every K via Lagrange identity (sympy) + scalar lemma (z3, unsat). (F) GKLP's brane-circle example (eq. 29) is the owner's rank-2 spacelike-span case: Gram (L^2, L'^2, 0), positive definite. (G) Polychronakos eq. 2.4 tilted+boosted vector has norm R^2. Owner's own selftest also run read-only: 'python3 latticectc.py --selftest' -> SELFTEST OK (8 s). A direct z3 encoding of K = 3 legs and of generic 4-vector cone closure did not return within 110-300 s and was replaced by the Lagrange + scalar-lemma route (the same route the owner uses).",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Polychronakos, arXiv:2210.11497v3 (PLB 841, 137917, 2023)", "effect": "extends", "what": "Tilted and boosted branes in M4 x S1: periodicity vector (sin theta R, 0, gamma cos theta R, -gamma v cos theta R) (eq. 2.4); sec. 3.1: 'The five-vector a is necessarily spacelike, otherwise the bulk spacetime would have closed timelike curves'; sec. 4: images n a spacelike-separated, 'As also noted in [2]'; round-trip time 2Lc(1-u^2)/(c^2-u^2) never negative (eq. 4.7). Confirms the rank-1 statement for every tilt; attributes the bulk argument to GKLP. Sec. 6: a spinning cosmic string gives CTCs for L < tau -- a gravitating (non-flat) source outside H1.", "read_status": "READ (alphaXiv, pp. 1-17)"},
  {"ref": "Debolt & Kagan, arXiv:2602.13448v1 (Feb 2026)", "effect": "extends", "what": "General boosted+tilted frames: round-trip v_eff >= 1, 0 < T <= 2l (eqs. 46-48), 'the bounds on the round-trip time first described in [2] extend to our more general class of frames'; constantly accelerating (Rindler) branes, tilted or not: no detection before emission, causality maintained. States explicitly: 'Our analysis is purely kinematic, neglecting any interactions between branes, observers, and signals.'", "read_status": "READ (alphaXiv, pp. 1-31 partial page set)"},
  {"ref": "Kabat & Nomura, arXiv:2309.05759 (2023)", "effect": "extends", "what": "Named in discover_papers as the group's follow-up (induced Lorentz violation on a moving/spiralling brane); the tree reads it for couplings (branelink.py), not for causality. Not re-read for this audit.", "read_status": "NAMED-NOT-READ (for this key)"},
  {"ref": "Greene, Kabat, Levin, Porrati, arXiv:2510.05270 / 2511.23447 (2025, Klein bottle)", "effect": "extends", "what": "Cited by Debolt & Kagan as brane motion on a Klein-bottle compactification -- an orientation-reversing identification outside the owner's H2 (translation lattice). Boundary of the class, not a counterexample.", "read_status": "NAMED-NOT-READ (cited in 2602.13448 refs [6,7])"}
 ],
 "lacked_data": "The result is a kinematic theorem on a flat quotient: its conclusion depends on NO measured datum. beta and R are free parameters, and the only fact used is |xi|^2 = (2 pi R)^2 > 0, which holds identically (sympy, check A); GW170817 (2206.13590 eq. 39) bounds beta's size, not this sign. So the M hypothesis 'the authors lacked certain data' has no purchase on this result as stated -- evidence: every check above is parameter-free or holds for all |beta|,|B| < 1, and the 2023-2026 follow-ups (Polychronakos 2210.11497, Debolt & Kagan 2602.13448) recover the same positivity in wider kinematic classes. What WOULD move it is not data but a hypothesis: a non-flat bulk (brane tension, back-reaction, gravitating sources -- Polychronakos sec. 6 exhibits CTCs around a spinning string when L < tau, i.e. outside H1), a non-translation identification (Klein bottle, outside H2), or interactions beyond free fields in the microcausality statement (GKLP sec. 5: 'expected', not shown). Those are the owner's named H1-H3 and the O3 remainder the tree already keeps OPEN (latticectc.py:95-96: 'the warped / field-equation-satisfying case is what remains'). Whether our bulk is flat is not measured; that is an OPEN physical question, not a defect of the theorem.",
 "grade": "STANDS",
 "grade_evidence": "Statement as used (latticectc.py:34-38, :120, :129-131): rank-1 lattice Z xi with xi spacelike in a flat bulk admits no closed causal curve, for any chain length, boost or brane content. Re-derived: m^2|xi|^2 > 0 (z3), K-leg chains impossible (z3 K = 1, 2 per m; every K by Lagrange identity + scalar lemma), GKLP's eqs. 8/10/17/20/22/25/28/32 verified in sympy, v and w reproduced from the bulk quotient independently of GKLP's envelope picture, and T > 0 in every integer-winding round trip including supercritical B. The published GKLP result is NARROWER than the tree's statement (one brane, collinear envelope round trips, plus a heuristic p.4 bulk argument), but the tree presents the wider form as its OWN theorem, proves it, and names its hypotheses H1-H3, which the source satisfies. No moved datum enters. Recorded discrepancies, none of which changes the mathematics: (i) 'stronger than GKLP, who keep it on branes' (latticectc.py:23) overstates the gap against GKLP's p.4 bulk argument; (ii) 'the two GKLP papers' conflates GKLM 2206.13590 with GKLP 2208.09014, and latticectc.py cites no arXiv id.",
 "what_would_change_the_grade": "NARROWED if a tree owner used D21/'GKLP's no is forced' beyond H1-H3 -- for a warped or back-reacting bulk, a tension-carrying brane, an orientation-reversing compactification, or interacting-field microcausality (checked: latticectc.py:95-96, :148-152 and LEDGER.md O3 keep that case OPEN, so not at present). WRONG only if a closed causal curve were exhibited in a flat translation quotient with spacelike generator -- excluded by the z3 unsat results above. A later reading that GKLP's 'no' was meant for something other than the spacelike-identification quotient would change only the attribution, not the grade of the mathematics.",
 "reverify_command": "python3 " + D + "/rederive/gklp-rank1-moving-brane-no-ctc.py && (cd /home/user/Claude-Method-Works/research/warp-drive && PYTHONDONTWRITEBYTECODE=1 python3 latticectc.py --selftest | tail -2)",
 "report_path": D + "/audits/gklp-rank1-moving-brane-no-ctc.json"
}
json.dump(r, open(r["report_path"], "w"), indent=1)
print("written", r["report_path"])
