import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
r={
"key":"1307.3536",
"name":"Buttazzo, Degrassi, Giardino, Giudice, Sala, Salvio, Strumia, 'Investigating the near-criticality of the Higgs boson', arXiv:1307.3536v4 (22 Sep 2014; JHEP 12 (2013) 089): SM electroweak vacuum metastability (stability to M_Pl excluded at 2.8 sigma; M_t < 171.53 +- 0.42 GeV; Lambda_I = 10^10-10^12 GeV; lifetime; 'metastability preferred at 99.3% CL')",
"source":{
 "located":"arXiv:1307.3536v4 [hep-ph], 22 Sep 2014 (PDF p.1 stamp). Passages used: Sec.1 p.3 (metastable state sentence; M_h = 125.15 +- 0.24); Sec.4.2 p.17 (eq.63, definition of Lambda_I); Sec.4.3 pp.19-20 (Fig.3, eqs.64-67, the 2.8 sigma sentence, top-mass-definition caveat, gauge/scheme statements); Sec.3.3 p.14 (Lambda_QCD caveat on M_t); Sec.6.3 pp.29-31 (eqs.80-87, gravity and Planckian-dynamics caveats, lifetime sentence); Sec.7 pp.31-32 (99.3% CL, Lambda_I = 10^10-10^12, 'assuming the validity of the SM up to very high energy scales'). PDF page numbers equal printed page numbers in this paper, so the tree's p.3 / p.20 / p.31 / p.32 are both.",
 "read_status":"READ",
 "via":"Page text of v4 as returned by alphaXiv answer_pdf_queries in earlier stages of this same session (PDF pp.1-22, 24, 28-32, 34-36, 39), recovered verbatim from the session's recorded tool results and saved to "+D+"/src/1307.3536.pages.txt. In THIS stage alphaXiv returned 'assistant quota exceeded' for answer_pdf_queries, get_paper_content and discover_papers, and arxiv.org / alphaxiv.org are refused by the egress proxy (curl 403, WebFetch EGRESS_BLOCKED). Every quotation below was checked against that saved page text, not against the tree's quotation of it. Not held: PDF pp.23, 25-27, 33, 37-38 (Sec.5 interpretations, part of App. A/B) and the reference list, so ref. [52] ('unknown Planckian dynamics') is not identified here."
},
"published_statement":"p.3: 'in the context of the SM the measured value of M_h is special because it corresponds to a near-critical situation in which the Higgs vacuum does not reside in the configuration of minimal energy, but in a metastable state close to a phase transition [4]'. p.19: 'In the neighbourhood of the measured values of M_h and M_t, the stability condition is well approximated by M_h > 129.6 GeV + 2.0(M_t - 173.34 GeV) - 0.5 GeV (alpha_3(M_Z) - 0.1184)/0.0007 +- 0.3 GeV. (64) The quoted uncertainty comes only from higher order perturbative corrections.' p.20: 'Other non-perturbative uncertainties associated with the relation between the measured value of the top mass and the actual definition of the top pole mass used here (presumably of the order of Lambda_QCD) are buried inside the parameter M_t in eq. (64). For this reason we include a theoretical error in the top pole mass and take M_t = (173.34 +- 0.76_exp +- 0.3_th) GeV. Combining in quadrature theoretical uncertainties with experimental errors, we find M_h > (129.6 +- 1.5) GeV (stability condition). (65) From this result we conclude that vacuum stability of the SM up to the Planck scale is excluded at 2.8 sigma (99.8% C.L. one-sided). Since the main source of uncertainty in eq. (64) comes from M_t, any refinement in the measurement of the top mass is of great importance ... M_t < (171.53 +- 0.15 +- 0.23_alpha3 +- 0.15_Mh) GeV = (171.53 +- 0.42) GeV. (66) ... Notice that the stability bound is scheme and gauge independent. ... log10(Lambda_V/GeV) = 9.5 + 0.7(M_h/GeV - 125.15) - 1.0(M_t/GeV - 173.34) + 0.3 (alpha_3(M_Z) - 0.1184)/0.0007. (67) ... the scale Lambda_I at which lambda_eff vanishes, is gauge dependent. In the Landau gauge we find Lambda_I ~ 13 Lambda_V around the observed values'. p.31: 'As shown, the SM vacuum is likely to survive for times that are enormously longer than any significant astrophysical age (e.g. the sun will exhaust its fuel in about five billion years).' p.31: 'assuming the validity of the SM up to very high energy scales, the measured value of M_h is near-critical ... Because of the present experimental uncertainties on the SM parameters (mostly the top quark mass), we cannot conclusively establish the fate of the EW vacuum, although metastability is now preferred at 99.3% CL.' p.32: 'We find Lambda_I = 10^10-10^12 GeV, see eq. (67), suggesting that the instability is reached well below the Planck mass. The presence of an instability at an intermediate scale could be interpreted as a sign of a new-physics threshold around Lambda_I.'",
"published_hypotheses":[
 "H-SM-UV: the SM alone, extrapolated to M_Pl with no new physics: 'assuming the validity of the SM up to very high energy scales' (p.31); the paper itself offers Lambda_I as a possible new-physics threshold (p.32) and states the SM-to-M_Pl option as an assumption the small beta_lambda 'makes it possible to assume' (p.32).",
 "H-NNLO: two-loop (NNLO) threshold matching of lambda, m^2, y_t, g_2, g_Y to pole masses M_h, M_t, M_Z, M_W, alpha_3(M_Z), G_mu; three-loop RGEs; two-loop effective potential (abstract p.1, Table 1 p.4, p.19 'lambda_eff ... at two loops [112]'). Theory error in eq.(64) is +-0.3 GeV from 'higher order perturbative corrections' only (p.19).",
 "H-TOP-POLE: the collider top mass is identified with the pole mass up to an O(Lambda_QCD) non-perturbative ambiguity, carried as +-0.3_th GeV on M_t (p.20; p.14 'does not take into account the non-perturbative theoretical uncertainty of order Lambda_QCD in the definition of M_t').",
 "H-INPUTS: M_h = 125.15 +- 0.24 GeV (p.3); M_t = 173.34 +- 0.76_exp +- 0.3_th GeV (p.20); alpha_3(M_Z) = 0.1184 +- 0.0007 (p.19 Fig.3 caption; eqs.60-61); M_W = 80.384 +- 0.014 GeV (eqs.58-59). Figs.2, 7 use M_t = 173.3 +- 0.8, M_h = 125.1 +- 0.2.",
 "H-LIN: eqs.(64), (67) are linearisations valid 'in the neighbourhood of the measured values' (p.19) / 'around the observed values' (p.20).",
 "H-GAUGE: the stability bound (64)-(66) and Lambda_V are gauge- and scheme-independent; Lambda_I (lambda_eff = 0) is gauge dependent, Landau gauge Lambda_I ~ 13 Lambda_V; Lambda_lambda ~ 2 Lambda_V is scheme dependent (p.20).",
 "H-TUNNEL: tunnelling rate d(P) = dt dV Lambda_B^4 exp(-S), S = 8 pi^2/(3|lambda(Lambda_B)|) with one-loop action (eqs.80-81); 'As long as Lambda_B << M_Pl, gravitational effects are irrelevant ... The effect of gravitational corrections is to slow down the tunnelling rate ... In some cases, unknown Planckian dynamics can affect the tunnelling rate [52]' (p.30); lifetime depends on the future cosmology assumed, matter- or vacuum-energy-dominated (eqs.84-87, Fig.7b)."
],
"hypothesis_drift":[
 "DROPPED (H-SM-UV) -- massform.py:414-425 and the D29 text massform.py:2894-2904 (carried into the ledger by ledger.py:744-745, which appends massform.PROPOSED['D29']): 'Beyond tree level, at the central measured masses, the potential has a deeper minimum at large field' and 'metastability is PREFERRED, not established' are stated without the source's own condition 'assuming the validity of the SM up to very high energy scales' (p.31). The stable/metastable dichotomy on which the case split is built is itself conditional on no new physics below M_Pl; the source (p.32) and AFS 1707.08124 p.51 ('new physics at an arbitrary high scale can destabilize the SM by opening up new tunneling directions') say new physics can change it either way. C4 is not moved by this (rederive C7): with new physics the only releases are still vacuum transitions, which the tree's inference covers -- but the hypothesis is unnamed at the use site.",
 "DROPPED (H-GAUGE qualifier) -- massform.py:418-419: 'The instability sets in at \"10^10-10^12 GeV\" in field value (p.32)'. The source defines Lambda_I as the field value where lambda_eff vanishes and states on p.20 that it 'is gauge dependent. In the Landau gauge we find Lambda_I ~ 13 Lambda_V'; the gauge-independent scale is Lambda_V ~ 10^9.5 GeV. The quoted range is verbatim (massform.py:1295) but the Landau-gauge qualifier is not carried. Nothing in C4 turns on the number.",
 "DROPPED (H-TUNNEL qualifiers) -- massform.py:426-427 (and SOURCES 'BU-life' massform.py:1284-1291): 'the SM vacuum is likely to survive for times that are enormously longer than any significant astrophysical age' is verbatim (p.31), but the source's conditions on it -- gravity neglected for Lambda_B << M_Pl, 'unknown Planckian dynamics can affect the tunnelling rate [52]' (p.30), and dependence on future cosmology (Fig.7b) -- are not carried. AFS 1707.08124 p.48: 'there is no sensible way of estimating a lower bound on the lifetime of our vacuum including new physics.' No verdict of the tree rests on the lifetime.",
 "ADDED (tree's own claim, not a sentence of the source) -- massform.py:414 'THE ONE WAY A HIGGS FIELD COULD RELEASE ENERGY' and massform.py:2895-2896 'Its one release is decay of a metastable vacuum': 1307.3536 discusses the stability of the EW vacuum; it does not state that decay is the only way the Higgs field could release energy. The tree attaches 'READ 1307.3536' only to the status clause ('top-mass dependent, READ 1307.3536', massform.py:2897), which is accurate; the 'one release' is the tree's inference from its own tree-level THEOREM plus H-REAL, and is correctly not attributed to the source.",
 "NONE (verbatim, correctly paged) -- massform.py:1268-1297 SOURCES 'BU-meta' (p.3), 'BU-mt' (p.20, eqs.65-66, including '99.8% C.L. one-sided'), 'BU-life' (p.31, both sentences), 'BU-scale' (p.32); endpoint.py:124-127 and 319-327 eq.(67) coefficients, 125.15 / 173.34 reference values, Lambda_lambda ~ 2 Lambda_V and 'Lambda_I ~ 13 Lambda_V, Landau gauge' -- all match the source text. endpoint.py (not a canonical owner) DOES carry the Landau-gauge qualifier that massform.py:418 drops.",
 "NOTED, not a drift -- the tree quotes two confidence levels from the one paper side by side (massform.py:1278 '2.8 sigma (99.8% C.L. one-sided)'; massform.py:1291 '99.3% CL') without remarking that they differ; they are the source's own two numbers (p.20 and p.31), see rederivation DISC items."
],
"data_at_publication":[
 {"quantity":"top pole mass M_t","value_then":"173.34 +- 0.76_exp +- 0.3_th GeV (p.20)","value_now":"172.57 +- 0.29 GeV (M_t^MC, template fits) and 172.4 +- 0.7 GeV (M_t^sigma, pole mass from cross sections), PDG 2024","source_now":"PDG 2024 as READ in Hiller, Hoehne, Litim, Steudtner arXiv:2401.08811v4 Table I p.4 (cached alphaXiv page text, src/2401.08811.pages.txt)","moves_conclusion":"Moves the SIZE of the exclusion, not the status the tree uses. Via the source's own eq.(64): stability disfavoured at 2.86 sigma with M_t^MC but 1.67 sigma with M_t^sigma (rederive C5); Hiller's full analysis: 5.1 sigma (MC) and 1.9 sigma (sigma). Both keep the vacuum on the metastable side at the central value; 'preferred, not established, top-mass dependent' (massform.py:425, 2896-2897) still holds, and the dependence is now on the DEFINITION of M_t as much as on its value."},
 {"quantity":"Higgs mass M_h","value_then":"125.15 +- 0.24 GeV (p.3)","value_now":"125.20 +- 0.11 GeV","source_now":"PDG 2024 via arXiv:2401.08811v4 Table I","moves_conclusion":"No: +0.05 GeV moves M_t,crit by +0.025 GeV (eq.64 slope) and log10 Lambda_V by +0.035."},
 {"quantity":"alpha_3(M_Z)","value_then":"0.1184 +- 0.0007","value_now":"0.1180 +- 0.0009","source_now":"PDG 2024 via arXiv:2401.08811v4 Table I","moves_conclusion":"Slightly toward stability (-0.29 GeV on M_h,crit, -0.14 GeV on M_t,crit via eq.64) with a larger error; Hiller: stability needs +3.7 sigma in alpha_s. Does not move the status."},
 {"quantity":"significance of the exclusion of absolute stability","value_then":"2.8 sigma (99.8% C.L. one-sided), p.20; 'metastability is now preferred at 99.3% CL', p.31","value_now":"2.48 sigma = 99.3% one-sided (AFS 2018); 1.9 sigma (M_t^sigma) / 5.1 sigma (M_t^MC) (Hiller 2024/2026)","source_now":"Andreassen, Frost, Schwartz arXiv:1707.08124v4 p.51; arXiv:2401.08811v4 p.4 (both cached alphaXiv page text)","moves_conclusion":"Contested by top-mass definition; it moves on either side of 2 sigma. It does not move the tree's use, which states 'preferred, not established' and does not rest a verdict on the number."},
 {"quantity":"critical top mass for stability","value_then":"M_t < 171.53 +- 0.42 GeV (eq.66)","value_now":"171.18 (+0.17 -0.35 th) GeV (AFS 2018, m_h 125.09, alpha_s 0.1181); 171.10 GeV (Hiller, PDG 2024 inputs)","source_now":"arXiv:1707.08124v4 p.50 eq.(6.30); arXiv:2401.08811v4 Table I","moves_conclusion":"No: the later values sit 0.35-0.43 GeV lower, which is where the source's own eq.(64) inverted puts it (171.12, rederive C3); every value remains below both measured top masses."},
 {"quantity":"instability scale Lambda_I (Landau gauge)","value_then":"10^10-10^12 GeV (p.32); eq.(67) central log10 Lambda_I = 10.61","value_now":"10^11.25 (M_t^MC) / 10^11.42 (M_t^sigma) via eq.(67) at PDG 2024; Hiller 5.3e11 GeV (per sibling audit 1205.6497)","source_now":"computed here from eq.(67) (rederive C6); arXiv:2401.08811 p.3 as read by audits/1205.6497.json","moves_conclusion":"No: inside 10^10-10^12."},
 {"quantity":"lifetime of the EW vacuum","value_then":"'enormously longer than any significant astrophysical age' (p.31, Fig.7b, 10^200-10^1000 yr scale over M_t 172-176)","value_now":"tau_SM = 10^(161 +160 -59) yr; > 10^65 yr at 95%","source_now":"arXiv:1707.08124v4 p.50 eq.(6.27) (cached page text)","moves_conclusion":"No: still enormously longer than astrophysical ages, within SM-only assumptions (AFS: no lower bound with new physics)."}
],
"rederivation":{
 "method":"numeric",
 "script_path":D+"/rederive/1307.3536.py",
 "outcome":"ALL PASS (13 checks), 4 DISCREPANCIES RECORDED (not refutations). C1: the printed eq.(65) error +-1.5 reproduces only as 2.0 x 0.76 (M_t experimental alone, 1.52); the quadrature of the components the text names (2.0 x (0.76 (+) 0.3), 0.5 for alpha_3, 0.3 theory) gives +-1.74 (+-1.63 without the top theory error) -- DISC. C2: (129.6 - 125.15)/sigma = 2.93 with the printed 1.5, 2.54 with the full budget; 2.8 lies between; 2.8 sigma one-sided is 99.74% (prints as 99.8%) -- DISC at rounding level; every reading excludes stability at > 2.5 sigma. C3: eq.(64) inverted gives M_t,crit = 171.12 GeV, 0.41 GeV below the printed eq.(66) 171.53 (the text says (66) 'express[es] the stability condition of eq. (64)') -- DISC; eq.(64) is linear only near the measured values and 171.5 lies 1.8 GeV away, so boundary curvature is a possible cause, not computed; later full analyses give 171.18 (AFS) and 171.10 (Hiller), near the inverted value. eq.(66)'s +-0.42 is not the quadrature of its three printed components (0.31) but is reproduced (0.43) if the 0.3 top theory error is added -- DISC. C4: THEN M_t = 173.34 +- 0.76 sits 2.08 sigma (vs 171.53 +- 0.42) or 2.71 sigma (vs 171.12) above the bound; the p.31 '99.3% CL' is 2.46 sigma one-sided -- a different number from p.20's 2.8 sigma, not reconciled in the pages read. C5: at PDG 2024 through eq.(64): 2.86 sigma (M_t^MC) and 1.67 sigma (M_t^sigma), both on the metastable side; spread 1.19 sigma between the two top-mass definitions. C6: eq.(67) + Lambda_I ~ 13 Lambda_V gives log10 Lambda_I = 10.61 then, 11.25 / 11.42 now, all inside 10^10-10^12. C7: massform's case split field_supplies_mass_energy = rel or (metastable and dec) returns the same verdict for stable and metastable at rel = dec = False, and flips in the metastable case if dec = True -- the top mass is not load-bearing for C4, the inference 'decay forms no atomic mass at the seat' is. NOT re-derived: the NNLO matching, three-loop running and two-loop effective potential themselves (beyond a stdlib/sympy check here); the comparison is to later independent computations (AFS 2018, Hiller 2024).",
 "agrees_with_source":"partly"
},
"later_literature":[
 {"ref":"Andreassen, Frost, Schwartz, 'Scale invariant instantons and the complete lifetime of the Standard Model', arXiv:1707.08124v4 (2018)","effect":"narrows","what":"Complete NLO tunnelling calculation: tau_SM = 10^(161 +160 -59) yr, > 10^65 yr at 95% (p.50 eq.6.27; abstract). 'Absolute stability is currently excluded at 2.48 sigma, which translates to a one-sided confidence of 99.3%' (p.51) -- lower than Buttazzo's 2.8 sigma; m_t,crit = 171.18 (+0.17 -0.35 th) GeV (eq.6.30). 'Higher-dimension operators do not decouple: new physics at an arbitrary high scale can destabilize the SM by opening up new tunneling directions' (p.51); 'there is no sensible way of estimating a lower bound on the lifetime of our vacuum including new physics' (p.48). Confirms metastability-preferred and the long lifetime within the SM; narrows the lifetime claim to SM-only.","read_status":"READ (cached alphaXiv page text of v4, PDF pp.1-2, 5-6, 10-11, 15-17, 19, 44-46, 48-51, 56-59, 67; src/1707.08124.pages.txt)"},
 {"ref":"Hiller, Hoehne, Litim, Steudtner, 'Vacuum stability in the Standard Model and beyond', arXiv:2401.08811v4 (5 Mar 2026)","effect":"narrows","what":"PDG 2024 inputs, higher-order running: stability requires M_t^sigma 1.9 sigma lower or M_t^MC 5.1 sigma lower, or alpha_s +3.7 sigma (Table I p.4); 'Given the sizable uncertainty in the pole mass M_t^sigma, the PDG central values are less than 2 sigma away from stability ... the smaller uncertainty in the Monte-Carlo mass indicates a 3 sigma tension' (p.5, uncorrelated 2D); 'the fate of the standard model vacuum remains an important open question, which requires higher precision in the determinations of the top mass, the strong coupling, and their uncertainties and correlation' (p.5); onset of metastability 'around 10^10 GeV' (p.1). Confirms 'preferred, not established, top-mass dependent'; shows the significance turns on which top mass is used.","read_status":"READ (cached alphaXiv page text of v4, PDF pp.1-5, 16, 23-24; src/2401.08811.pages.txt)"},
 {"ref":"Degrassi et al., arXiv:1205.6497v2 (2012) -- audited in this pass (audits/1205.6497.json)","effect":"confirms","what":"The predecessor (Buttazzo's ref.[4]): stability excluded at 2 sigma for M_h < 126 GeV, Lambda_I = 10^(11+-1) GeV; graded NARROWED there on the tree's use; its C5/C6 re-derivations agree with the numbers here.","read_status":"READ by sibling audit (not re-read in this stage)"},
 {"ref":"discover_papers search for further later work (Bednyakov et al. 2015, gauge-independent instability scale, Planck-suppressed operators)","effect":"contested","what":"Not performed: alphaXiv discover_papers returned 'assistant quota exceeded' twice in this stage. No claim is made about work not read.","read_status":"NAMED-NOT-READ"}
],
"lacked_data":"What Buttazzo et al. had in 2013/14: M_t = 173.34 +- 0.76 (the first Tevatron+LHC world combination), M_h = 125.15 +- 0.24, alpha_s = 0.1184 +- 0.0007, NNLO matching and three-loop running, a one-loop-action tunnelling estimate, and an O(Lambda_QCD) ~ 0.3 GeV allowance for the pole-mass identification. What came later: (1) a top mass whose experimental error has shrunk (0.29 GeV, MC) while its interpretation has split -- PDG 2024 quotes M_t^MC = 172.57 +- 0.29 and a cross-section pole mass 172.4 +- 0.7, and Hiller et al. note 'sharpening its interpretation would ... be a useful endeavor'; (2) a complete NLO lifetime computation (AFS 2018); (3) higher-order running (Hiller 2024). Does having them change the conclusion? EVIDENCE AGAINST a change in what the tree uses: every later analysis read here still puts the central values on the metastable side (AFS 2.48 sigma; Hiller 1.9-5.1 sigma; eq.(64) at PDG 2024 1.67-2.86 sigma), keeps Lambda_I in 10^10-10^12 (10^11.25-10^11.42 via eq.67), keeps the lifetime astronomically long (10^161 yr), and places the critical top mass at 171.1-171.2 GeV, below both measured top masses. EVIDENCE FOR M's hypothesis, in a narrower form: (a) the headline '2.8 sigma' was not stable -- AFS put it at 2.48 sigma in 2018, and today it ranges 1.9-5.1 sigma depending on a datum the authors could only bound (the meaning of M_t, which they carried as +-0.3 GeV); (b) the source's own arithmetic has rounding- and linearisation-level discrepancies (eq.65 +-1.5 vs 1.74 from its stated components; eq.66's 171.53 vs 171.12 from inverting eq.64; 2.8 sigma printed as 99.8%; 99.3% on p.31 vs 99.8% on p.20), which are discrepancies, not errors -- the later full analyses land near the eq.(64)-inverted value, not 171.53; (c) all of it is conditional on no new physics to M_Pl, which the data cannot test. None of this changes 'metastability preferred, not established, top-mass dependent', which is the only form in which the tree uses the result, and C4 does not turn on it.",
"grade":"NARROWED",
"grade_evidence":"READ at source (v4 page text, pp.3, 14, 17, 19-20, 29-32). Every quotation the tree holds is verbatim and correctly paged (massform.py:1268-1297 BU-meta/BU-mt/BU-life/BU-scale; endpoint.py:124-127, 319-327). The tree's conclusion from it -- 'metastability is PREFERRED, not established, and it turns on the top mass' (massform.py:425; D29 massform.py:2896-2897, ledger.py:744-745) -- survives every moved datum: at PDG 2024 the central values stay on the metastable side under both top-mass definitions (1.67 / 2.86 sigma via eq.64; 1.9 / 5.1 sigma Hiller; 2.48 sigma AFS), Lambda_I stays in 10^10-10^12, and the lifetime stays astronomically long (rederive C4-C6). The case split makes C4 independent of the metastability status (rederive C7). The grade is NARROWED, not STANDS, because the tree uses the result without three hypotheses the source states: (i) 'assuming the validity of the SM up to very high energy scales' (p.31) is not named at massform.py:414-425 or in the D29 text, though the stable/metastable dichotomy rests on it and AFS p.51 shows new physics at any scale can change tunnelling; (ii) Lambda_I is carried 'in field value' (massform.py:418) without the source's 'gauge dependent ... Landau gauge' (p.20); (iii) the lifetime sentence (massform.py:426-427) is carried without the source's gravity / 'unknown Planckian dynamics' / future-cosmology conditions (p.30, Fig.7b). None of these moves a verdict of the tree. Also recorded, NOT graded as WRONG: four arithmetic discrepancies internal to the source (eq.65 +-1.5 vs 1.74; eq.66 171.53 vs 171.12 from eq.64 inverted; eq.66 +-0.42 vs 0.31 quadrature of its printed parts; 2.8 sigma one-sided = 99.74%, printed 99.8%, and p.31's 99.3% differs from p.20's 99.8%). Per M's rule these are discrepancies, and none moves the source's conclusion (every reading excludes stability at > 2 sigma at 2013 inputs). The significance itself is DATA-DEPENDENT (it turns on the top-mass definition, 1.9 vs 5.1 sigma today), but the tree states it as top-mass dependent and rests no verdict on it.",
"what_would_change_the_grade":"To STANDS: the tree names H-SM-UV ('assuming the SM valid to M_Pl', p.31) at massform.py:414-425 and in the D29 text, carries 'Landau gauge' on Lambda_I at massform.py:418, and carries the p.30 conditions (gravity neglected for Lambda_B << M_Pl; unknown Planckian dynamics; future cosmology) with the lifetime sentence at massform.py:426-427. To DATA-DEPENDENT: if a verdict of the tree were shown to turn on the metastability status or its significance (it does not: rederive C7), since that significance now ranges 1.9-5.1 sigma with the top-mass definition. To WRONG: only a computed contradiction of the source's conclusion -- e.g. a full analysis at current inputs placing the SM central values in the absolutely stable region; none was found (AFS, Hiller: metastable side). A reading of the source's pp.23-27, 33 or its reference list, or of an erratum, could resolve the four internal discrepancies without changing the grade.",
"reverify_command":"python3 "+D+"/rederive/1307.3536.py  # expect ALL PASS (13 checks) and 4 DISC lines: eq.65 '+-1.74', eq.66 '171.12' vs 171.53, eq.66 '0.31' vs 0.42, '99.74%'; C5 '2.858' (M_t^MC) and '1.666' (M_t^sigma); C6 log10 Lambda_I 10.614 / 11.248 / 11.418. Source text: grep -n 'excluded at 2.8\\|171.53\\|99.3% CL\\|gauge dependent\\|unknown Planckian\\|assuming the validity' "+D+"/src/1307.3536.pages.txt ; re-read at source when quota allows: alphaXiv answer_pdf_queries(paper='1307.3536', queries=['eq. (64)-(67) and the 2.8 sigma sentence', 'Sec. 6.3 gravity and Planckian dynamics caveats', 'Sec. 7 99.3% CL', 'reference [52]'])",
"report_path":D+"/audits/1307.3536.json"
}
json.dump(r,open(D+"/audits/1307.3536.json","w"),indent=1)
print("ok")
