import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep={
"key":"stokes-divergence-theorem",
"name":"Stokes / divergence theorem underlying the Laue step",
"kind":"theorem",
"source":{
 "located":"Classical Gauss-Green / Gauss-Ostrogradsky divergence theorem (Lagrange 1762 special case; Gauss 1813; Ostrogradsky 1828/1831; Green 1828), none on arXiv. The tree's own citation route is Wang arXiv:1206.5618v12 (= Can. J. Phys. 93, 1470 (2015)) eq.(20), which invokes 'the three-dimensional Gauss divergence law'. Modern statements with exact hypotheses: G.-Q. Chen & M. Torres, arXiv:2005.10949v3 (Notices AMS 68, 1282 (2021)); T. Ruf, arXiv:2506.09978v2 (2025).",
 "read_status":"READ-VIA-RESTATEMENT",
 "via":"alphaXiv answer_pdf_queries page text: Chen-Torres 2005.10949 pp.1-11 (history p.1-3; classical statement eq.(1) p.3; De Giorgi-Federer Lipschitz/finite-perimeter form eq.(4) p.5; Sobolev/BV on Lipschitz domains p.5; DM-field Gauss-Green Theorems 1-3 pp.7-10; Whitney's counterexample Example 2 p.8; Silhavy Example 3 p.10); Wang 1206.5618 pp.2, 4-5 (eq.(20) and its introducing sentence; 'The integral domain V can be multiply connected'); Ruf 2506.09978 pp.1-2, 5-7, 15-16 (inner boundaries; Theorem 1.1/4.4). Gauss 1813, Ostrogradsky 1831, Green 1828, Whitney 1957, Federer 1945/1958, De Giorgi 1954-55, Chen-Frid 1999, Silhavy 2005/2009 are NAMED-NOT-READ (restated in Chen-Torres)."
},
"published_statement":"Chen-Torres 2005.10949 p.3, eq.(1): 'The divergence theorem in its vector form for the n-dimensional case (n >= 2) can be stated as INT_E div F dy = - INT_{dE} F . nu dH^{n-1}, where F is a C^1 vector field, E is a bounded open set with piecewise smooth boundary, nu is the inner unit normal vector to E'; p.1: 'The classical Gauss-Green formula for the multidimensional case is generally stated for C^1 vector fields and domains with C^1 boundaries.' p.5 eq.(4): the same formula 'for Lipschitz vector fields F over sets of finite perimeter was proved by De Giorgi (1954-55) and Federer (1945, 1958)', and it 'is also valid for BV vector fields over Lipschitz domains'. p.8 Example 2 (Whitney): 'F(y1,y2) = (y1,y2)/(y1^2+y2^2) ... If E = (0,1)^2 ... 0 = divF(E) != - INT_{dE} F . nu_E dH^1 = pi/2'. The form the tree uses is Wang 1206.5618 p.5 eq.(20): 'from the three-dimensional Gauss divergence law we have oint_S dS_l (Theta^{l mu} X^i) = INT_V (d_l Theta^{l mu}) X^i d^3x + INT_V Theta^{i mu} d^3x', with p.2 'The integral domain V can be multiply connected' and p.4 (charged metal sphere) 'V is surrounded by the infinite spherical surface S_inf and the metal sphere's surface S_met'.",
"published_hypotheses":[
 "F (here W^l = T^{lj} x^i) is C^1 on the closure of the region (classical, Chen-Torres p.1, p.3); weakened to Lipschitz (De Giorgi-Federer, p.5), Sobolev/BV on Lipschitz domains (p.5), or a divergence-measure field DM^p with the formula as a limit over interior smooth approximations (Chen-Comi-Torres Theorems 2-3, pp.9-10)",
 "divergence taken over the WHOLE region: a singular point of F inside (or on the boundary of) the region carries its own contribution; Whitney's example (p.8) has div F = 0 pointwise in the open square yet the boundary flux is pi/2 -- the pointwise divergence is not the distributional one",
 "region bounded, with piecewise smooth / C^1 / Lipschitz / finite-perimeter boundary (p.3-5); multiply connected regions allowed, every boundary component contributes (Wang p.2, p.4; Ruf 2506.09978 Theorem 1.1 for inner boundaries)",
 "flat Euclidean 3-space and Cartesian x^i in Wang's eq.(20) (Wang's setting is the laboratory frame of special relativity)",
 "the divergence theorem says NOTHING about div F = 0 or about any boundary term vanishing: in Wang eq.(20) both the volume divergence term and the surface term are kept; zeroing either is an additional physical hypothesis (Wang p.5: 'divergence-less (itself) is neither a necessary condition nor a sufficient condition')"
],
"hypothesis_drift":[
 "UNNAMED AT THE CITING SITES; SUPPLIED ELSEWHERE IN THE FILE: regularity of T across the whole ball, centre included. tolman.py:937-939 ('Stokes's theorem is CITED') names no hypothesis. tolman.py:139 ('DOCKET 54's \"EXACT, NO INTEGRATION CONSTANT\" is Laue plus the divergence theorem') credits the theorem with removing the constant, but the theorem removes it only when its regularity hypothesis holds at r = 0, and that hypothesis is exactly C = 4 pi lim r^3 p_r = 0. The tree's own independence_witness (tolman.py:1381-1388: p_r = A/r^3, p_t = -A/(2 r^3)) is conserved and trace-free with d_l T^{lj} = 0 at every point of the punctured ball (rederive D5a-b). On it int_B T^ii = 0 while 4 pi R^3 <T^rr> = 4 pi A (D5c). The shell form on B_R minus B_eps is exact (D5d), and the distributional divergence at the origin is nonzero: pairing = -4 pi A (D5e). This is the 3-D analogue of Whitney's example as READ in Chen-Torres p.8 (D6). Family F's z3 encoding bakes the hypothesis in. LAUE at tolman.py:2196-2198 has no centre term, and z3 shows LAUE EXCLUDES the independence witness (D8a unsat) while LAUE plus C admits it (D8b sat). The mutation table at tolman.py:886-905 lists 'F axisymmetry baked into LAUE' but no row for 'regular interior baked into LAUE'. The hypothesis is KEPT everywhere else: the master formula's C at tolman.py:280-286, refusal 3 at :931-936, pointwise_test's regular_centre requirement (tolman.py:1266-1273, exercised at :2964-2967), and the D-family rows D6 at :2145. So the drop is confined to prose and to F's encoding, and no verdict moves.",
 "OVER-RESTRICTIVE in the canonical entry (not the tree's word): 'smooth divergence-free tensor on a ball'. Smoothness is sufficient but not needed. The tree's own W3 (tolman.py:584, p_r = -2 + 10 r^{-5/2}) is NOT C^1 at the centre: W = T.x is unbounded as r -> 0 (D4b). Yet int_B T^ii = 4 pi R^3 p_r(R) holds exactly as an improper integral, because the inner flux goes to 0 (D4c). The correct hypothesis is the DM/limit form (Chen-Torres Theorems 2-3): T divergence-free in the DISTRIBUTIONAL sense on the ball, equivalently vanishing inner flux lim 4 pi eps^3 <T^rr>(eps) = 0. It is the tree's 'regular centre', not smoothness. W3 is used in family G via the ODE route, not in F, so nothing in the tree rests on the canonical wording.",
 "INTERFACE HYPOTHESIS: KEPT. 'Divergence-free' must hold distributionally across material interfaces, surface stresses included. With a pressure jump and no surface stress, the ball identity fails by exactly 4 pi a^3 (p1 - p2) (D7a). A Laplace surface tension restores it exactly (D7b). The tree's demand for the COMPLETE apparatus (field plus mirrors, tolman.py:2608 and the Sorge discussion at :165-175) is this hypothesis. pointwise_test refuses a ball containing a mirror (:2974), which is a content refusal and conservative.",
 "REGION: KEPT, with a small over-statement. tolman.py:567 says 'Wang's eq. (20) needs the REGION to be a ball'. The divergence theorem needs only a bounded Lipschitz (even finite-perimeter) region, and Wang allows multiply connected V (p.2). The ball is needed only to reduce the surface term to 4 pi R^3 <T^rr>. The sibling vonlaue-1911-annphys audit records the same point.",
 "FLAT SPACE: KEPT. The Laue step is taken with gravity stripped (tolman.py:129), in line with Wang's Cartesian, special-relativistic setting. Curvature enters the master formula separately through K (tolman.py:285).",
 "NAMING (a discrepancy, not an error): tolman.py:938 says 'Stokes's theorem' and :139 says 'the divergence theorem'. The theorem used is the Gauss-Ostrogradsky divergence theorem, which Chen-Torres p.1 also calls the Gauss-Green formula or Ostrogradsky's theorem. It is the n-dimensional case of the generalised Stokes theorem, so the name is conventional."
],
"data_at_publication":[
 {"quantity":"none. The result is a mathematical theorem, and no numerical input enters its conclusion",
  "value_then":"n/a",
  "value_now":"n/a",
  "source_now":"n/a",
  "moves_conclusion":"no. There is no datum to move"}
],
"rederivation":{
 "method":"sympy",
 "script_path":D+"/rederive/stokes-divergence-theorem.py",
 "outcome":"ALL PASS, 21 checks, about 3 s, exit 0; sympy 1.14.0 and z3 5.1.0. D1: the product rule under Wang eq.(20) holds for an arbitrary T. D2: for a smooth, non-spherical, divergence-free T = delta Lap(phi) - dd(phi) (phi a quartic polynomial), int_B T^ii = 32 pi R^5/3 = 4 pi R^3 <T^rr>(R), residual 0 and nonzero, so the classical theorem as the tree uses it is confirmed. D3: the F5/F6 constant plate stress gives Laue residual 0 and <T^rr> = (2 p_t + p_z)/3 = -3 at p_t = -5, p_z = 1, matching tolman.py:572. D4: the tree's W3 is not C^1 at the centre, yet the identity holds with inner flux -> 0, so 'smooth' is sufficient, not necessary. D5: the tree's independence_witness has pointwise divergence 0 on the punctured ball. The ball form FAILS (0 vs 4 pi A), the shell form is exact, and the distributional divergence at the origin is nonzero (-4 pi A). The theorem's hypothesis fails there; the theorem does not. D6: Whitney's example as READ in Chen-Torres Ex.2 gives div F = 0 and outward flux pi/2. D7: a pressure jump without surface stress breaks the ball identity by 4 pi a^3 (p1 - p2), and a Laplace tension restores it. D8 (z3): family F's LAUE conjunct excludes the independence witness (unsat), LAUE plus the centre term admits it (sat), and the vacuity guard is sat.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"G.-Q. Chen & M. Torres, arXiv:2005.10949 (Notices AMS 2021)","effect":"extends","what":"Survey of how the classical C^1 / C^1-boundary theorem extends to Lipschitz fields on sets of finite perimeter (De Giorgi, Federer), Sobolev/BV fields on Lipschitz domains, and divergence-measure fields DM^p with normal traces (Anzellotti, Chen-Frid, Chen-Torres, Silhavy, Chen-Comi-Torres). Whitney's Example 2 and Silhavy's Example 3 show the formula needs an extra term, or has no measure-valued normal trace, when the field is singular. These are limits of the hypotheses, not counterexamples to the theorem.","read_status":"READ (pp.1-11 page text)"},
 {"ref":"T. Ruf, 'A Rough Divergence Theorem', arXiv:2506.09978v2 (2025)","effect":"extends","what":"A divergence theorem that allows inner boundaries (slits, cracks) for bounded divergence-measure fields. It holds if and only if H^{m-1}(dU minus ext*U) < infinity (Theorem 1.1/4.4). It shows that every boundary component, inner ones included, contributes, which is the structure behind the tree's centre term C.","read_status":"READ (pp.1-3, 5-7, 9, 13, 15-16 page text)"},
 {"ref":"C. Wang, arXiv:1206.5618 (Can. J. Phys. 93, 1470 (2015))","effect":"narrows","what":"Uses the divergence theorem to show that divergence-free alone is neither necessary nor sufficient for int Theta^{ij} = 0; a boundary condition is required. This narrows the Laue conclusion, not the divergence theorem. See the sibling audit vonlaue-1911-annphys.","read_status":"READ (pp.1-7 page text)"},
 {"ref":"G.-Q. Chen, G. E. Comi & M. Torres, arXiv:2410.09214 (2024), 'Extended Divergence-Measure Fields, the Gauss-Green Formula, and Cauchy Fluxes'","effect":"extends","what":"The Gauss-Green formula for vector-valued measures whose divergence is a Radon measure, over open sets. It covers measure-valued (delta-supported) stresses such as idealised mirror or wall tensions.","read_status":"abstract only (discover_papers listing); not read"},
 {"ref":"arXiv:2607.11467 (2026), 'Gauss-Green formulas for divergence measure tensor fields on rough domains'","effect":"extends","what":"A tensorial DM Gauss-Green formula, the setting of the Laue step (T^{lj} x^i).","read_status":"abstract only (discover_papers listing); not read"}
],
"lacked_data":"This is a mathematical theorem, so there is no measured input that its 19th-century authors lacked and that could move its conclusion. What came later is analysis, not data. The regularity hypotheses were WEAKENED (Lipschitz, BV, DM^p, rough domains, inner boundaries), which EXTENDS the theorem. Counterexamples such as Whitney's were found, but they apply only to fields outside the hypotheses (a point singularity with nonzero distributional divergence), so they are not refutations. No later work READ here, and none listed by discover_papers, contradicts the theorem within its hypotheses. So for this result M's hypothesis is NOT supported. The only 'missing input' is on the tree's side: at the Laue sites (tolman.py:139, 937-939; LAUE at 2196-2198) the regularity input, C = 0 / a regular centre, is used without being named. The same file names it everywhere else, so the missing piece is a label, not data, and no conclusion moves.",
"grade":"NARROWED",
"grade_evidence":"THE EXTERNAL THEOREM STANDS. It was read at source via restatement (Chen-Torres 2005.10949 eq.(1), p.3; Wang 1206.5618 eq.(20), p.5). It was re-derived in sympy with residual 0 on a smooth, non-spherical, divergence-free stress (D2) and on the tree's own F5/F6 plate witness (D3). No datum enters it, and later literature only extends it. THE TREE'S STATEMENT-AS-USED IS WIDER THAN THE THEOREM AT THE CITING SITES. tolman.py:139 credits 'the divergence theorem' with 'NO INTEGRATION CONSTANT', and tolman.py:937-939 cites Stokes with no hypothesis. Family F's LAUE (tolman.py:2196-2198) encodes the no-centre-term conclusion with no guard or mutation row for it; the table at :886-905 names only axisymmetry for F. The counterexample is SHOWN, and it is the tree's own independence_witness (tolman.py:1381-1388). It is divergence-free at every point of the punctured ball, yet int_B T^ii = 0 while 4 pi R^3 <T^rr> = 4 pi A (D5c). The discrepancy is the inner flux (D5d), and the distributional divergence at the origin is -4 pi A (D5e); z3 confirms LAUE excludes this witness (D8a/b). It is Whitney's example (READ, Chen-Torres p.8; D6) in three dimensions. The narrowing moves NO VERDICT. The master formula carries C (tolman.py:280-286), refusal 3 carries the regular centre (:931-936), pointwise_test refuses without regular_centre (:1266-1273, :2964-2967), and F's only realised witnesses are constant-stress, hence regular. Separately, the canonical entry's 'smooth' is over-restrictive (D4: W3 is not C^1 at the centre and the identity holds), and the interface hypothesis is correctly kept by the tree's 'complete apparatus' rule (D7). This is a missing label at three sites, not an error in the tree's mathematics and not a refutation of the theorem.",
"what_would_change_the_grade":"To STANDS: the citing sentences (tolman.py:139, 937-939) name the hypothesis 'T divergence-free in the distributional sense on the whole ball, equivalently a regular centre / C = 0', and family F carries it as a named conjunct or drift row. That is the same hypothesis the file already states at :280-286 and :931-936. To WRONG: only an F-family verdict, or a pointwise_test REPORT, issued on a source with C != 0. None was found: pointwise_test refuses without regular_centre, and F's witnesses are constant-stress. OPEN would apply only if the source statement could not be read; it was read via restatement.",
"reverify_command":"python3 "+D+"/rederive/stokes-divergence-theorem.py && sed -n '129,139p;280,286p;567,572p;886,905p;931,939p;1381,1388p;2195,2198p;2964,2975p' /home/user/Claude-Method-Works/research/warp-drive/tolman.py",
"report_path":D+"/audits/stokes-divergence-theorem.json"
}
json.dump(rep,open(D+"/audits/stokes-divergence-theorem.json","w"),indent=1)
print("ok")
