import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R={
"key":"gr-qc/9607003-sec4-curved",
"name":"Ford & Roman: QI 'should also hold' in curved spacetime / with boundaries if sampling time << curvature radius",
"source":{
 "located":"L.H. Ford & T.A. Roman, 'Restrictions on Negative Energy Density in Flat Spacetime', arXiv:gr-qc/9607003v2 (TUTP-96-2, 1 Jul 1996, revised 2 Oct 1996, v2 24 Jan 1997); PRD 55, 2082 (1997). The passage is Sec. 4 'Conclusions', p.11 (heading on p.10); companion sentence Sec. 1, pp.2-3. It cites ref.[23] = Ford & Roman PRD 53, 5496 (1996) (= gr-qc/9510071) for the argument and ref.[24] = Pfenning & Ford gr-qc/9608005 for the worked example.",
 "read_status":"READ",
 "via":"alphaXiv page text of gr-qc/9607003v2, all 17 pages. In THIS stage every alphaXiv call (get_paper_content, answer_pdf_queries, discover_papers) returned 'assistant quota exceeded', and arxiv.org/export.arxiv.org are egress-blocked. The text read is the verbatim alphaXiv answer_pdf_queries tool_result returned earlier this session (transcript subagents/workflows/wf_45789490-3e4/agent-a635ac248a99bc2d8.jsonl, 2026-09-26T13:05:57Z), saved unmodified to scratchpad d67/src/gr-qc_9607003.alphaxiv_pages.txt (md5 8f3ba9f58345e3a4f72902e8369df2f4) and read page by page here; the re-derivation script string-checks the quotation against it. Ref.[23] itself (gr-qc/9510071) was not re-read in this stage; its sibling audit audits/gr-qc_9510071.json records it READ."
},
"published_statement":"p.11 (Sec. 4), verbatim: 'Note that in Minkowski spacetime, our bounds hold for an arbitrary choice of the sampling time, t0. Recently we argued that such bounds should also hold in a curved spacetime and/or one with boundaries, if the sampling time is restricted to be much smaller than the smallest local radius of curvature and/or the distance to any boundaries in the spacetime [23]. An explicit example of the validity of this assumption has been given in Ref. [24]. There a QI is derived in the static closed and open Robertson-Walker universe models. For a choice of sampling time which is small compared to the local radius of curvature, the QI reduces to our flat spacetime bound.' pp.2-3 (Sec. 1), verbatim: 'These inequalities were derived for Minkowski spacetime, in the absence of boundaries. However, we recently argued [23] that if one is willing to restrict the choice of sampling time, then the bound should also hold in curved spacetime and/or one with boundaries. For example, we proved that the inequality Eq. (1) holds in the case of the Casimir effect for sampling times much smaller than the distance between the plates. ... Quantum inequalities in particular curved spacetimes, which reduce to Eq. (1) in the short sampling time limit, are given in Ref. [24].'",
"published_hypotheses":[
 "P1 'such bounds' = this paper's flat-space QIs: free quantized massless scalar Eq.(1)/(17) -3/(32 pi^2 t0^4), massive scalar Eq.(16), EM field Eq.(48) -3/(16 pi^2 t0^4); minimal coupling (stress tensor Eq.(6)); Lorentzian time average along an INERTIAL worldline at one spatial point; arbitrary state, renormalised w.r.t. the Minkowski vacuum",
 "P2 sampling time t0 'much smaller than the smallest local radius of curvature' (curved case) -- qualitative, no numerical threshold, 'radius of curvature' not defined (which tensor, which components)",
 "P3 AND/OR t0 'much smaller than ... the distance to any boundaries in the spacetime' (bounded case)",
 "P4 status: ARGUED in ref.[23], called an 'assumption' on p.11 -- not proved in this paper; supported by two worked cases: the Casimir effect (p.2, 'we proved', in [23]) and static closed/open Robertson-Walker QIs of ref.[24] that reduce to Eq.(1) for short sampling times",
 "P5 (implicit) units hbar = c = 1: a sampling TIME is compared to LENGTHS"
],
"hypothesis_drift":[
 "DROPPED -- achievable.py:226-230 (and the same quote at noise.py:185-187, a site the canonical entry does not list as an owner): the quotation ends '...smallest local radius of curvature.' with a closing period and no ellipsis; the source continues 'and/or the distance to any boundaries in the spacetime [23].' The boundary-distance condition P3 is dropped. rederive C1/C2 show it is load-bearing: between conducting plates the flat EM QI (Eq.48) holds only for t0 <= (135/pi^4)^(1/4) a = 1.0850 a and fails at t0 = 2a.",
 "ALTERED QUOTATION -- achievable.py:227: quoted as verbatim, the tree prints 'we recently argued that such bounds ...'; p.11 prints 'Recently we argued that such bounds ...'. The tree's word order is p.2's ('we recently argued [23] that if one is willing ...'), so two sentences from different pages are conflated. A discrepancy in the quotation, not in substance (rederive T2-T4).",
 "ADDED EMPHASIS, UNMARKED -- achievable.py:229: 'IF' in capitals; the source prints lower-case 'if'. It is the tree's house style for emphasis, but inside quotation marks it is not marked as added.",
 "OMITTED SUPPORT -- achievable.py:226-230: the tree keeps the word 'argued' (the source's own, rederive T8) but leaves out the source's two supporting cases in the same passages: the Casimir case, which p.2 says was 'proved', and ref.[24]'s static RW QIs, which reduce to the flat bound for short t0 (T6, T7). The omission makes the curved step look weaker than the source presents it. Given the tree's verdict, that runs in M's favour.",
 "SCOPE NOT CARRIED -- achievable.py:226-230: P1 (free, minimally coupled field, inertial worldline, Lorentzian sampler) is not repeated at this site, but achievable.py:237-251's caveats (a)-(c) carry it for the replacement bound, so this is not an uncarried hypothesis in the tree's argument.",
 "NOT A DRIFT, RECORDED: noise.py:183-187 makes P2 quantitative by taking the curvature length l_G = (8 pi G D/c^4)^(-1/2) from G_00. The source defines no radius of curvature. Kontou-Olum 1410.0665 later proves that to first order only the Ricci tensor enters, which licenses a Ricci/Einstein-based length (see later_literature). The source's 'much smaller' still gives no threshold."
],
"data_at_publication":[
 {"quantity":"no measured datum: the result is a qualitative scope extrapolation (sampling time << curvature radius / boundary distance), and no number in it came from experiment",
  "value_then":"n/a","value_now":"n/a","source_now":"n/a",
  "moves_conclusion":"no. The numbers checked here are closed-form theory (the EM plate Casimir density -pi^2/(720 a^4), the flat QI constants, and K-O's Gaussian integral), not measured inputs."}
],
"rederivation":{
 "method":"sympy",
 "script_path":D+"/rederive/gr-qc_9607003-sec4-curved.py",
 "outcome":"ALL PASS (20 checks, 3 guards shown able to fail). T1-T8: string checks against the source page text. T1 finds the full p.11 sentence, boundary clause and ref.[23] included. T2: the tree's quoted string is not a verbatim substring. T3/T4: the tree's word order is p.2's. T5: the dropped boundary clause. T6/T7: the source's supporting cases the tree omits. T8: 'argued' appears on both p.2 and p.11. C1: EM plates, constant rho = -pi^2/(720 a^4) against Eq.(48); the flat QI holds iff t0 <= (135/pi^4)^(1/4) a = 1.085010 a. C2: violated at t0 = 2a, so the boundary clause is necessary. C3: a periodic massless scalar (rho = -pi^2/(90 L^4)) against Eq.(1) holds iff t0 <= 0.542505 L. That is a topology scale, and neither of the source's two clauses names it, though [23]'s own worked example is this periodic case. K1: for the Gaussian g = exp(-t^2/t0^2), INT (g'')^2 dt = 3 sqrt(pi/2)/t0^3 = 3.7599/t0^3, which reproduces Kontou-Olum Eq.(130)'s printed leading 3.76. K2/K3: (b/l_G)^2 = 6(M/b)/(a/b)^3 = 3750 symbolically, b/l_G = 61.237 (noise.py:182). K4: K-O Eq.(3) bounds every Fermi-frame Ricci component by R_max, so R_max >= G_00/3 = 1/(3 l_G^2). At t0 = b the first-order curvature term is then >= 874x the flat term: sampling at b lies outside the PROVED small-curvature regime, which supports noise.py's conclusion. K5: at t0 = l_G the ratio is >= 0.233 (not small); at t0 = 0.1 l_G it is >= 0.00233.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"Kontou & Olum, 'Quantum inequality in spacetimes with small curvature', arXiv:1410.0665v2 (2014); PRD 91, 104005 (2015)",
  "effect":"extends",
  "what":"PROVES a version of the argued extrapolation. Class: massless minimally coupled scalar, a timelike GEODESIC, smooth positive COMPACTLY SUPPORTED sampling g (the Lorentzian is excluded), first order in curvature, with Fermi-frame bounds |R_ab| <= R_max, |R_ab,cd| <= R''max, |R_ab,cde| <= R'''max (Eq.3). Result Eq.(128), Gaussian Eq.(130): -1/(16 pi^2 t0^3){3.76 + 2.63 R_max t0^2 + [3.42 + 197.9(24|a|+11|b|)] R''max t0^4 + 6.99 R'''max t0^5}. Intro, verbatim: 'Ford, Pfenning and Roman [6, 7] also have suggested that the flat-space quantum inequalities can be used in spacetimes with small curvature. However none of these results have been explicitly proven.' Conclusion: the corrections are small iff R_max t0^2, R''max t0^4, R'''max t0^5 << 1, 'if t0 is much smaller than any curvature radius', and the variation scale of the curvature is also controlled. NEW NAMED HYPOTHESES beyond Ford-Roman: bounded Ricci DERIVATIVES; a geodesic; compact support; the renormalisation ambiguity (a, b), which enters the R'' term with unknown coefficients. And a SHARPENING: only the Ricci tensor enters, so there is no first-order correction on paths that meet no matter. The leading 3.76 is re-derived exactly in the script (K1).",
  "read_status":"READ (alphaXiv page text of 1410.0665v2, pp.1-17, 19-21, returned earlier this session and saved to d67/src/_cache_1410..txt; abstract, pp.2-4 and p.19 read here)"},
 {"ref":"Fewster & Smith, 'Absolute quantum energy inequalities in curved spacetime', arXiv:gr-qc/0702056v3 (2007); Ann. Henri Poincare 9, 425 (2008)",
  "effect":"confirms",
  "what":"Confirms that the curved step was not proved as of 2007, verbatim: 'Typically these problems have been avoided by heuristic appeals to the equivalence principle to justify the use of Minkowski spacetime QEIs on sufficiently small scales. To date, this approach, while physically reasonable, lacks full mathematical justification and control over the scales on which it is valid.' Supplies the first 4D absolute QEI for the minimally coupled massive KG field on any globally hyperbolic spacetime ('local curvature terms', Eq.6). On small scales: 'We expect that the same should hold ... This will be investigated in a future work.' So the tree's word 'argued' was exact through 2007.",
  "read_status":"READ (alphaXiv page text of gr-qc/0702056v3 held in d67/src/0702056.recovered.txt; abstract, pp.1-3 and the passage after Eq.(88) read here)"},
 {"ref":"Kontou & Sanders, 'Energy conditions in general relativity and quantum field theory', arXiv:2003.01815 (2020)",
  "effect":"confirms",
  "what":"Review restatement: 'Kontou and Olum used this inequality [Fewster-Smith] to derive the first QEIs with explicitly curvature dependent bounds, both for QWEI [82] and QNEI [83].' It cites Fewster [80] as the first general-spacetime difference QWEI for the minimally coupled field. No contradiction of the Ford-Roman short-sampling premise is recorded.",
  "read_status":"READ in part (alphaXiv page text, d67/src/_cache_2003.01815.txt, the passages quoted)"},
 {"ref":"Fewster & Teo, gr-qc/9812032, PRD 59, 104016 (1999)",
  "effect":"narrows",
  "what":"Exact difference QIs in static spacetimes. Per the tree's own reading (achievable.py:264-266, audits/gr-qc_9812032.json), their Schwarzschild section has the bound going arbitrarily negative near a horizon: strong curvature can weaken the bound drastically, consistent with the short-sampling restriction being essential.",
  "read_status":"READ-VIA the sibling audit and the tree's Docket 55/62 reading; not re-read in this stage (quota)"},
 {"ref":"Pfenning & Ford, gr-qc/9608005 (static Robertson-Walker QIs) -- the source's ref.[24]",
  "effect":"confirms",
  "what":"The source's worked example: a QI in static closed/open RW universes that reduces to the flat bound for short sampling times.",
  "read_status":"NAMED-NOT-READ (restated in gr-qc/9607003 p.3 and p.11 only)"},
 {"ref":"discover_papers search for later work",
  "effect":"contested",
  "what":"The one discover_papers call this stage returned 'alphaXiv assistant quota exceeded', so no new search was possible. The entries above come from alphaXiv texts already returned in this session. 'contested' is here only because the schema requires an effect: no contesting paper was found or searched for.",
  "read_status":"NOT RUN (quota)"}
],
"lacked_data":"What Ford & Roman lacked in 1996 was PROOF, not data. The extrapolation has no measured input, so no moved datum can move it (data_at_publication). What came later is mathematics: Fewster-Smith's absolute curved-space QEI (2007/8), and Kontou-Olum's first-order small-curvature QI (2014), which proves the extrapolation for the massless minimally coupled scalar on geodesics. Having it does NOT overturn the conclusion. It CONFIRMS the claimed limit (leading term = the flat bound, K1) and NARROWS its licence: added hypotheses (bounded Ricci derivatives, a geodesic, compact-support samplers that exclude Ford-Roman's own Lorentzian, renormalisation ambiguity a, b), and the finding that only Ricci enters at first order. Evidence against M's hypothesis for this result: the 1996 argument is vindicated in its proved domain, and the one numerical check of the later proof here agrees (3 sqrt(pi/2) = 3.7599 vs printed 3.76). Evidence for it, narrowly: the source's two clauses (curvature radius, boundary distance) are incomplete. rederive C3 shows a periodic identification imposes its own cap t0 <= 0.5425 L, a scale the source names in neither clause, and Kontou-Olum add a curvature-variation scale Ford-Roman did not state. Both are incompleteness of a qualitative remark, not errors in it. For the tree: the corridor has sampling length b = 61.2 l_G, and K-O's first curvature term is then >= 874x the flat term (K4), so neither the 1996 argued form nor the 2014 proved form reaches the corridor at t0 = b. That is what noise.py already says.",
"grade":"NARROWED",
"grade_evidence":"The published remark STANDS as a statement of its own 1996 status. It is READ verbatim on p.11 and p.2 of the source page text, and the tree's load-bearing word 'argued' is the source's own (T8). Its substance is later proved in a restricted class (Kontou-Olum 1410.0665, READ; leading term re-derived, K1). The grade is NARROWED because the tree's use DROPS a published hypothesis. achievable.py:226-230 (and noise.py:185-187) close the quotation after 'smallest local radius of curvature.' and omit 'and/or the distance to any boundaries in the spacetime [23]' (T5). rederive C1/C2 show the clause is load-bearing: between conducting plates the flat EM QI holds only for t0 <= 1.0850 a and fails at 2a. Secondary discrepancies, recorded, not refutations: the quotation's word order is p.2's, not p.11's (T2-T4); 'IF' is capitalised inside quotation marks; the source's two supporting cases are omitted, which understates the curved step in M's favour. The tree also cites 'argued' without noting that Kontou-Olum (2014) PROVED the minimally-coupled-scalar case to first order in curvature. That again understates the bound's reach in M's favour, though the tree's own O2 row names Fewster-Smith as the route. What rests on it survives: ledger W1's clause (3) withdrawal is carried chiefly by Ford-Helfer-Roman gr-qc/0208045 (no spatially averaged QI), and every later curved result read here is still a worldline TIME average, so the withdrawal of 'a theorem about QFT' for a ball integral stands. Not WRONG: no counterexample to the remark itself. Not DATA-DEPENDENT: there is no measured input. Not OPEN: the source was read and the finite parts checked.",
"what_would_change_the_grade":"To STANDS: the tree restores the boundary clause verbatim ('... and/or the distance to any boundaries in the spacetime [23]') with p.11's word order, or marks the truncation with an ellipsis and states that the corridor has no boundaries within its sampling scale. Adding the Kontou-Olum status would remove the under-statement. To WRONG (of the source): a proved curved-spacetime QEI whose t0 -> 0 limit is NOT the flat bound for the minimally coupled free field on a geodesic in a region of small bounded curvature. None is known; K-O shows the opposite to first order. To OPEN: if the saved alphaXiv page text were shown not to be the arXiv v2 text. A re-read at source (not possible this stage: quota) would confirm it; the journal version PRD 55, 2082 was not read.",
"reverify_command":"python3 "+D+"/rederive/gr-qc_9607003-sec4-curved.py && sed -n 224,231p /home/user/Claude-Method-Works/research/warp-drive/achievable.py && sed -n 183,188p /home/user/Claude-Method-Works/research/warp-drive/noise.py",
"report_path":D+"/audits/gr-qc_9607003-sec4-curved.json"
}
json.dump(R,open(R["report_path"],"w"),indent=1,ensure_ascii=False)
print("written",R["report_path"])
