import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S=D+"/src/casmag/all/"
r={
"key":"casimir-anec-violation-curved",
"name":"ANEC false in curved spacetime in general; Casimir vacuum as the standard counterexample (anecscope.py:25-28, :33-34, :109, :166-168; obstruct.py:163-166)",
"source":{
 "located":"The tree cites no source. The statement is the standard one in: Graham & Olum, 'Achronal averaged null energy condition', arXiv:0705.3193v2 (PRD 76 064001, 2007), abstract, p.2 and Sec. II p.3; Fewster, Olum & Pfenning, 'Averaged null energy condition in spacetimes with boundaries', arXiv:gr-qc/0609007v3 (PRD 75 025007, 2007), abstract, pp.2-3, Sec. IV pp.9-10, p.11; Kontou & Sanders, 'Energy conditions in general relativity and quantum field theory', arXiv:2003.01815v2 (CQG 37 193001, 2020), Sec. 4.3 p.34 eq.(101); Visser, 'Scale anomalies imply violation of the averaged null energy condition', arXiv:gr-qc/9409043v1, p.1; Urban & Olum, 'Averaged null energy condition violation in a conformally flat spacetime', arXiv:0910.5925v2 (PRD 81 024039, 2010), abstract; Gao-Jafferis-Wall arXiv:1608.05687v3 p.2. Classics restated, not read: Graham & Olum 'Plate with a hole obeys the ANEC', PRD 72 025013 (2005) [hep-th/0506136] (restated in 0705.3193 p.2 and 2003.01815 p.34); Visser 1996 Boulware/Schwarzschild (gr-qc/9604008, restated in 0705.3193 p.3); Wald-Yurtsever 1991 note added in proof (restated in gr-qc/9409043 p.1).",
 "read_status":"READ",
 "via":"alphaXiv page text. In THIS stage every alphaXiv call (answer_pdf_queries on 0705.3193 and 2003.01815, get_paper_content on 0705.3193, discover_papers) returned 'alphaXiv assistant quota exceeded', and arxiv.org/export.arxiv.org are refused by the egress proxy (CONNECT 403). The texts read are verbatim alphaXiv <page> outputs banked earlier in this session by sibling stages: "+S+"0705.3193v2.txt (pp.1-8), "+S+"gr-qc_0609007v3.txt (pp.1-11), "+S+"0910.5925v2.txt, "+S+"gr-qc_9409043v1.txt, "+D+"/src/_cache_2003.01815.txt (pp.1,27,34,52), "+D+"/src/1608.05687.txt. Source text, not summaries; only the banked pages were available."},
"published_statement":"Graham & Olum 0705.3193 abstract: ANEC 'is sufficient to prove many important theorems in general relativity, but it is violated by quantum fields in curved spacetime.' p.2: 'In flat space, this condition has been found to be obeyed by quantum fields in many backgrounds where one might expect it to be violated, such a domain wall [1] or a Casimir plate with a hole [2]. The latter result has been generalized to arbitrary Casimir systems, as long as the geodesic does not intersect or asymptotically approach the plates [3]. However, a quantum scalar field in a spacetime compactified in one spatial dimension or in a Schwarzschild spacetime around a black hole violates ANEC [4].' Sec. II p.3: 'To our knowledge, there are two specific spacetimes in which ANEC has been explicitly calculated and found to be violated. The first is Minkowski space compactified in one spatial dimension ... very much analogous to the Casimir effect. ANEC is violated on any geodesic that does not remain at constant z. However, no such geodesic is achronal ... The second known violation is in Schwarzschild spacetime, in particular in the Boulware vacuum state [4]. But every complete geodesic in the Schwarzschild spacetime is chronal.' Fewster-Olum-Pfenning gr-qc/0609007 abstract: 'the ANEC holds in flat space with boundaries, as in the Casimir effect, for geodesics which stay a finite distance away from the boundary.' p.2: the ANEC 'is not expected to be violated by the Casimir plate system, because geodesics parallel to the plates do not violate the NEC, while any other geodesic eventually intersects the plate material, where it picks up a positive contribution to the integral.' p.3: 'It is known that the ANEC may be violated in general curved spacetimes ... The ANEC is also violated for the ground state of the Klein-Gordon field in flat space with a periodic identification in one spatial direction along any null geodesic which winds around the compact direction ... essentially the Casimir system without the plates.' Sec. IV p.10, eq.(24): <T_ab> = (pi^2/90L^4) diag(-1,1,1,-3); '(A)NEC is violated along any null geodesic with a nonzero z-component of velocity ... obeyed along complete null geodesics with zero velocity in the z-direction ... null geodesics which wind round the cylinder are not achronal.' Kontou-Sanders 2003.01815 p.34: plates T_mu nu = (C(z)/L^4)(eta_mu nu - 4 k_mu k_nu), C = pi^2/720; the Casimir state 'violates all the pointwise energy conditions ... also violates the AWEC ... However it has be[en] shown to obey the ANEC [123, 16].'",
"published_hypotheses":[
 "H1 ANEC in its unrestricted form: integral of T_ab k^a k^b over a COMPLETE affinely parametrised null geodesic (0705.3193 eq.(1); gr-qc/0609007 eq.(1)) -- chronal geodesics allowed",
 "H2 FIELDS: free quantum TEST fields on a FIXED background (scalar in the cylinder and Schwarzschild cases; conformally coupled scalar in Urban-Olum; minimally coupled free scalar in the FOP positive theorem); semiclassical self-consistency NOT imposed (0705.3193 p.2 separates it out as Condition 1's second change)",
 "H3 VIOLATING SYSTEMS as published: (a) Minkowski space periodically identified in one spatial direction -- FLAT, nontrivial topology, 'the Casimir system without the plates' -- on WINDING geodesics, which are CHRONAL; (b) Schwarzschild, Boulware vacuum, on complete geodesics that are all CHRONAL; (c) later, Urban-Olum: conformally flat 4D spacetime, conformally coupled scalar, on ACHRONAL complete geodesics; (d) Visser: generic curved spacetimes with a nonzero scale anomaly",
 "H4 THE PLATE SYSTEM IS NOT A COUNTEREXAMPLE: ANEC HOLDS in flat space with boundaries for complete null geodesics staying a finite distance from the boundary (FOP theorem, minimally coupled free scalar, subject to their tubular-neighbourhood conditions); parallel geodesics give zero NEC integrand, all others intersect the plates (FOP p.2); plate with a hole obeys ANEC (Graham-Olum 2005, restated)",
 "H5 STATUS: an explicit-calculation result (two calculated spacetimes in 2007; more later), not a theorem that ANEC fails on every curved background"
],
"hypothesis_drift":[
 "SUBSTITUTED SYSTEM (anecscope.py:25-26 'the standard counterexample is the Casimir vacuum, where a geodesic between the plates violates it'; anecscope.py:166-167; obstruct.py:164-165): the READ sources say the opposite about plates -- the Casimir PLATE system OBEYS ANEC for geodesics a finite distance from the plates (FOP abstract and p.2; G&O p.2; Kontou-Sanders p.34 'it has be[en] shown to obey the ANEC'). The Casimir-type counterexample is the plate-FREE periodically identified Minkowski space (FOP p.3 'essentially the Casimir system without the plates'; G&O p.3 'very much analogous to the Casimir effect'). Computed here (parts A, B): T_kk = 0 identically on every null geodesic parallel to ideal plates, for the EM field and for a scalar of any mass, any xi, Dirichlet or Neumann; any other null geodesic reaches a plate at finite affine parameter and is not complete in the gap.",
 "MISATTRIBUTED ACHRONALITY (anecscope.py:33-34 'Casimir escapes it because the geodesic between the plates is not achronal'): every null geodesic between plates in Minkowski space is ACHRONAL (part D: z3 proves the sum of a future timelike and a future causal vector is timelike, so no timelike curve joins two points of one null line; Kontou-Sanders p.35 as restated by the sibling audit anec-klinkhammer-wald-yurtsever). The plate system escapes achronal ANEC by not violating ANEC at all. The chronality escape belongs to the WINDING geodesics of the cylinder (FOP p.10; G&O p.3; part C4 computes the covering-space interval to the image point as -L^2, timelike). anecscope.py:109 ('the SAME escape Casimir uses and the same one Gao-Jafferis-Wall use') is right only for the compactified vacuum -- which is exactly GJW's own analogy (1608.05687 p.2: 'similar to the Casimir effect, since the interaction between the boundaries implies that the radial direction is effectively a compact circle').",
 "CURVED vs FLAT (anecscope.py:25-26, obstruct.py:163-165): the tree offers as 'the standard counterexample' to ANEC 'in curved spacetime' a FLAT system (plates: flat with boundary; the cylinder: flat with nontrivial topology). The curved counterexamples in the READ sources are Schwarzschild/Boulware (G&O p.3, chronal), Visser's scale-anomaly class (gr-qc/9409043 p.1) and Urban-Olum's conformally flat spacetime (0910.5925 abstract, ACHRONAL). The headline 'false in curved spacetime' is supported, but not by the example the tree names.",
 "DROPPED H2 (anecscope.py:25-28; obstruct.py:163-166): the violations are free TEST-field results on fixed backgrounds; the tree states no field class, no state and no fixed-background qualifier for 'FALSE IN GENERAL'. Harmless for the tree's use (it draws only 'violating ANEC is not by itself a disqualification'), load-bearing if read as a statement about self-consistent solutions -- which the tree does NOT do (it keeps the self-consistent achronal version separate at anecscope.py:35-37).",
 "NO SOURCE CITED (anecscope.py:25-28, :166-168 'Nobody disputes this'): the headline is consistent with every source read (G&O abstract; FOP p.3; Visser p.1; Urban-Olum); the example is not."
],
"data_at_publication":[
 {"quantity":"EM plate Casimir coefficient C = pi^2/720 (T_00 = -C/L^4)","value_then":"pi^2/720 (Brown-Maclay 1969, as used by Kontou-Sanders eq.101)","value_now":"unchanged -- a computed QFT constant, not a measured datum","source_now":"2003.01815v2 p.34","moves_conclusion":"no -- the conclusion T_kk = 0 on parallel geodesics is independent of C (part A2)"},
 {"quantity":"cylinder ground-state coefficient pi^2/90 (minimally coupled massless scalar, period L)","value_then":"pi^2/90 (FOP eq.24; Kuo-Ford eq.3.32)","value_now":"unchanged, computed constant","source_now":"gr-qc/0609007v3 p.10","moves_conclusion":"no -- only the sign enters: T_kk = -(2 pi^2/45 L^4) sin^2 theta < 0 on every winding geodesic (part C1)"},
 {"quantity":"scalar trace-anomaly coefficient beta = -1/(5760 pi^2) (Urban-Olum vacuum violation)","value_then":"-1/(5760 pi^2)","value_now":"unchanged, computed constant","source_now":"0910.5925v2 eq.(29), via sibling audit anec-klinkhammer-wald-yurtsever","moves_conclusion":"no -- sets magnitude (-2.116e-7 at a=0.01, b=0.05, r=1), sign fixed by b > 2a"}
],
"rederivation":{"method":"sympy","script_path":D+"/rederive/casimir-anec-violation-curved.py",
 "outcome":"ALL AGREE, exit 0, 16/16 PASS. A (sympy): EM plate stress tensor T = (C/L^4)(eta - 4 zz) gives T_kk = -4C kz^2/L^4 on null k: ZERO for every geodesic parallel to the plates; negative only for kz != 0, and that geodesic hits a plate at affine parameter (L - z0)/kz. B (sympy): scalar image sum with an ARBITRARY function f(sigma) of the interval (so any mass), both translated and reflected images (Dirichlet or Neumann): the renormalised <(k.d phi)^2> vanishes at coincidence for k parallel to the plates, and the xi-term -xi (k.d)^2 <phi^2>(z) vanishes by translation invariance -> <T_kk> = 0 for every xi; vacuity guard: the same machinery gives -16 a^2 n^2 f''(4a^2n^2) != 0 for k across the plates. C (sympy): cylinder T_kk = -(2 pi^2/45 L^4) sin^2 theta (FOP eq.24), ANEC integral -> -infinity on a winding geodesic, 0 for non-winding; covering-space interval from start to its image after one winding = -L^2 (timelike): the violating geodesics are CHRONAL. D (z3, unsat + sat vacuity guard): future timelike + future causal is timelike, so straight null lines between plates are ACHRONAL. E: Urban-Olum eq.(42) as printed evaluates negative (-2.116e-7), not re-derived here (re-derived by the sibling audit). Net: the headline (ANEC fails for test fields on curved backgrounds) is supported; the tree's specific plate example is contradicted by computation, and the chronality escape it attributes to plates belongs to the plate-free compactified vacuum.",
 "agrees_with_source":"yes"},
"later_literature":[
 {"ref":"Fewster, Olum & Pfenning, PRD 75 025007 (2007), gr-qc/0609007","effect":"contradicts","what":"Contradicts the tree's PLATE clause (not the headline): ANEC holds in flat space with boundaries, as in the Casimir effect, for complete null geodesics a finite distance from the boundary (minimally coupled free scalar, tubular-neighbourhood conditions); winding geodesics of the cylinder violate ANEC and are chronal; 'Casimir plates would not seem to be useful to support a wormhole ... because of the need to get through the plate' (p.11). Confirms 'ANEC may be violated in general curved spacetimes' (p.3).","read_status":"READ (banked pp.1-11)"},
 {"ref":"Graham & Olum, PRD 76 064001 (2007), 0705.3193","effect":"confirms","what":"Confirms the headline ('violated by quantum fields in curved spacetime') and names the two calculated counterexamples: compactified Minkowski (analogous to Casimir; winding geodesics, chronal) and Schwarzschild Boulware (all complete geodesics chronal). Says plates with a hole / arbitrary Casimir systems OBEY ANEC for geodesics not meeting or approaching the plates.","read_status":"READ (banked pp.1-8)"},
 {"ref":"Graham & Olum, 'Plate with a hole obeys the averaged null energy condition', PRD 72 025013 (2005), hep-th/0506136","effect":"contradicts","what":"Contradicts the plate clause: a geodesic threading a hole in a Casimir plate satisfies ANEC.","read_status":"NAMED-NOT-READ (restated in 0705.3193 p.2 and 2003.01815 p.34)"},
 {"ref":"Visser, gr-qc/9409043 (1994)","effect":"confirms","what":"Confirms the headline for fixed curved backgrounds: a nonzero scale anomaly guarantees ANEC violation for a broad class; quotes Wald-Yurtsever's note added in proof that ANEC fails for generic perturbations of Minkowski in 4D; scale anomaly zero for Einstein and conformally flat spacetimes.","read_status":"READ (p.1)"},
 {"ref":"Urban & Olum, PRD 81 024039 (2010), 0910.5925","effect":"extends","what":"Extends the headline: ANEC violated by a conformally coupled scalar in a conformally flat 4D spacetime, state-dependently without bound (non-anomalous) and in the vacuum via the anomaly; all geodesics there are achronal, so achronal ANEC also fails on a fixed curved background (test field).","read_status":"READ (abstract; eq.42 re-derived by sibling audit)"},
 {"ref":"Kontou & Sanders, CQG 37 193001 (2020), 2003.01815","effect":"contradicts","what":"Review, p.34: the parallel-plate Casimir state violates all pointwise conditions and the AWEC 'However it has be[en] shown to obey the ANEC [123, 16]' -- contradicts the plate clause; confirms the compactification route to negative energy (p.27).","read_status":"READ (banked pp.1,27,34,52)"},
 {"ref":"Gao, Jafferis & Wall, 1608.05687 (2016/2017)","effect":"confirms","what":"p.2: their negative energy 'is similar to the Casimir effect, since the interaction between the boundaries implies that the radial direction is effectively a compact circle', and the null geodesics through the wormhole are 'no longer achronal' -- the compact-circle (chronal) reading of the Casimir escape, which is what anecscope.py:109 actually describes.","read_status":"READ (banked p.2)"},
 {"ref":"discover_papers survey of later work","effect":"contested","what":"NOT RUN: alphaXiv returned 'assistant quota exceeded'. The later-literature list is drawn from sources banked in scratchpad/d67/src and is a floor, not a survey.","read_status":"NOT RUN"}
],
"lacked_data":"M's hypothesis tested for this result. The result rests on NO measured datum: every input is a computed QFT constant (pi^2/720, pi^2/90, the anomaly coefficient) and every conclusion used is a SIGN, so no later measurement can move it -- evidence AGAINST the hypothesis here. What the earliest sources lacked was later CALCULATION, and it moved in both directions: (i) the plate system, once a candidate violator, was shown to OBEY ANEC (Graham-Olum 2005; Fewster-Olum-Pfenning 2007) -- this is the refinement the tree has not absorbed, and the error it produces is the TREE's (a misidentified example), not the outside literature's; (ii) curved-background violations were extended to ACHRONAL geodesics for test fields (Urban-Olum 2010), strengthening the headline the tree quotes. Having all of this does not change the tree's operative conclusion ('violating ANEC is not by itself a disqualification'); it changes which system is the counterexample and why it escapes achronal ANEC.",
"grade":"NARROWED",
"grade_evidence":"Two clauses, graded separately and then combined. (1) HEADLINE -- 'ANEC in curved spacetime is false in general; violating it is not by itself a disqualification' -- STANDS on READ sources: Graham-Olum 0705.3193 abstract and Sec. II (Schwarzschild Boulware), FOP gr-qc/0609007 p.3, Visser gr-qc/9409043 p.1, Urban-Olum 0910.5925 abstract (achronal, conformally flat; eq.42 evaluates to -2.116e-7). Qualifier the tree drops: these are free TEST fields on FIXED backgrounds. (2) THE NAMED COUNTEREXAMPLE -- 'the Casimir vacuum, where a geodesic between the plates violates it', and 'Casimir escapes [achronal ANEC] because the geodesic between the plates is not achronal' -- is CONTRADICTED as worded, by the sources (FOP abstract/p.2, G&O p.2, Kontou-Sanders p.34: the plate system OBEYS ANEC) and by computation shown here: T_kk = 0 identically on every parallel geodesic (EM; scalar of any mass and any xi, Dirichlet or Neumann), every non-parallel geodesic hits a plate at finite affine parameter, and every straight null line between plates is achronal (z3). The Casimir-type counterexample that exists is the plate-FREE periodically identified Minkowski space, whose violating winding geodesics are chronal (computed: covering interval -L^2) -- and that is flat, not curved. So the result holds on a smaller/different class than the tree states: headline yes, example only as the compactified vacuum, and the tree's plate wording at anecscope.py:26, :33-34, :167 and obstruct.py:164-165 is a computed discrepancy. Not graded WRONG overall because nothing that rests on it moves: obstruct.py's ANEC row (RELOCATED) and index3 ANEC-RELOCATES use only 'violating ANEC is not by itself a disqualification', which the READ curved counterexamples carry; and the tree's escape mechanism (chronality, 'same escape as GJW', anecscope.py:109) is exactly the compactified-Casimir mechanism the sources describe. Not graded STANDS because the specific example as used is contradicted.",
"what_would_change_the_grade":"To STANDS: the tree's example rewritten as 'Minkowski space compactified in one spatial direction (the Casimir system without the plates), on winding -- hence chronal -- geodesics; and in curved spacetime Schwarzschild/Boulware (chronal) and Urban-Olum (achronal, test field)', with the test-field/fixed-background qualifier stated. To WRONG: a dependent that used the PLATE geometry itself as an ANEC violator (e.g. sizing a plate configuration as a ANEC-violating source for the corridor) -- none found at the two recorded dependents. To OPEN/revisited: a reading of the Graham-Olum 2005 and Visser 1996 papers themselves (restated only) that differed from the concordant restatements; or a treatment of real (imperfect, dispersive) plates showing a complete geodesic that avoids the plates yet has negative ANEC -- FOP's theorem (minimally coupled free scalar, tubular-neighbourhood conditions) excludes this for its class, and nothing read here asserts it for other fields.",
"reverify_command":"python3 "+D+"/rederive/casimir-anec-violation-curved.py  # exit 0 = ALL AGREE (16 PASS); then: sed -n 40,62p "+S+"0705.3193v2.txt; sed -n 128,145p "+S+"0705.3193v2.txt; sed -n 16,24p "+S+"gr-qc_0609007v3.txt; sed -n 76,82p "+S+"gr-qc_0609007v3.txt; sed -n 1013,1035p "+S+"gr-qc_0609007v3.txt; sed -n 1026,1032p "+D+"/src/_cache_2003.01815.txt; grep -n -i 'casimir' /home/user/Claude-Method-Works/research/warp-drive/anecscope.py /home/user/Claude-Method-Works/research/warp-drive/obstruct.py",
"report_path":D+"/audits/casimir-anec-violation-curved.json"
}
json.dump(r,open(r["report_path"],"w"),indent=1)
print("written",r["report_path"])
