import json
SP="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
CM=SP+"/src/casmag/all/"
r={
"key":"gr-hyperbolicity-causal-propagation",
"name":"Einstein evolution is hyperbolic with characteristic speed c; matter in a compact region cannot change the metric outside its causal future (domain of dependence / Cauchy well-posedness) -- phase1.py Theorem 4",
"source":{
 "located":"The tree cites nothing (status word 'none'). The exact external result as used is R.J. Low, 'Speed limits in general relativity', arXiv:gr-qc/9812067v1 (18 Dec 1998; Class. Quantum Grav. 16 (1999) 543): Theorems 2.1/2.4 (existence, geometric uniqueness, Cauchy-development isometry, continuity), Corollaries 2.2/2.5, Corollary 3.1 (finite perturbations: D(Sigma\\K) unchanged), Corollary 4.1 and Sec. 4 (a decision at an event p cannot make any point of a distant worldline reachable earlier), Definition 2.3 and Theorem 4.2 (no warp drive without exotic matter), pp. 1-6. Low restates, without proof, the classics: Fourès-Bruhat (Choquet-Bruhat) 1952 local well-posedness, Choquet-Bruhat & Geroch 1969 maximal globally hyperbolic development, Hawking & Ellis 1973 Ch. 7 (proofs) and Sec. 4.3 conservation theorem, Wald 1984 Ch. 10. Second restatements READ: Fewster arXiv:math-ph/0501073v1 p.1 (DEC => a conserved T vanishing on a closed achronal set vanishes on its domain of dependence, 'see Sec. 4.3 in [1]' = Hawking-Ellis); Galanda et al. arXiv:2604.01047v1 Sec. 1.6 (local well-posedness 'established by Fourès-Bruhat [37] ... extended to maximal globally hyperbolic developments by Choquet-Bruhat and Geroch [15]'); Gourgoulhon arXiv:gr-qc/0703035v1 p.162 ('well-posedness of the Cauchy problem established by Choquet-Bruhat in 1952 ... by means of harmonic coordinates').",
 "read_status":"READ",
 "via":"Low gr-qc/9812067v1 READ in full (all 7 pages, verbatim) from alphaXiv page text returned by an earlier alphaXiv tool call and harvested into "+CM+"gr-qc_9812067v1.txt (harvester "+SP+"/src/casmag/allpages.py reads alphaXiv tool_results from session transcripts). In THIS stage every live alphaXiv call (answer_pdf_queries on gr-qc/0002074, get_paper_content, discover_papers) returned 'alphaXiv assistant quota exceeded', and arxiv.org / export.arxiv.org / semanticscholar / wikipedia are refused by the egress proxy (CONNECT 403), so Friedrich-Rendall gr-qc/0002074 and Rendall gr-qc/0505133 could NOT be read. The classics (Choquet-Bruhat 1952, Choquet-Bruhat-Geroch 1969, Hawking-Ellis 1973 Sec. 4.3 and Ch. 7) are NAMED-NOT-READ: READ-VIA-RESTATEMENT in Low pp.1-3, Fewster math-ph/0501073 p.1, Galanda et al. 2604.01047 Sec. 1.6, Gourgoulhon gr-qc/0703035 p.162 (all from the same alphaXiv cache)."
},
"published_statement":"Low 1998, Theorem 2.4 (matter case, p.3): 'Let (Sigma, h_ab, K_ab, J_a, rho) be an initial data set. Then 1. there exists a unique smooth space-time (M, g) known as the maximal development ... such that M is globally hyperbolic with Cauchy surface i(Sigma) ... and J_a and rho are induced on Sigma by a matter field satisfying (2.2). Furthermore, any other space-time satisfying these conditions may be mapped isometrically in (M, g). 2. if ... there is a diffeomorphism from S in Sigma to S' in Sigma' taking (h,K,J,rho) on S to (h',K',J',rho') on S', then the Cauchy development D(i(S)) in M is isometric to the Cauchy development D(i'(S')) in M'. 3. the metric g on M depends continuously on the initial data.' p.3: 'this theorem and corollary are true for a fixed equation of the form (2.2). One could have identical initial conditions with non-isometric maximal developments if the physical properties of the matter fields involved, and hence the evolution equations, were different.' Sec. 3, Corollary 3.1 (p.4): changing the data on K only, 'there is an isometry from D(i(Sigma\\K)) in M to D(i'(Sigma\\K)) in M'' ... 'we can interpret this result as stating that no gravitational influence propagates faster than light.' p.4: linear perturbations' bicharacteristics 'are the null geodesics of the background'; for finite perturbations 'since the metric itself determines the null geodesics, what can it mean to say that perturbations in the metric travel at light speed?' Sec. 4 (p.5): with the decision modelled at an event p, K = J+(p) cap Sigma, matter obeying (2.2) 'with the ray cones lying inside the light cones' (Corollary 4.1), 'the earliest point on L one can arrive at is the intersection of L with the boundary of D+(i(Sigma\\K))' and 'in neither case is it possible to reach L any sooner than it is in M'. p.6: to beat this 'the ray cone of the evolution equation (2.2) cannot lie inside the null cone of the metric ... this is only possible if the matter violates the dominant energy condition' (Hawking-Ellis); Theorem 4.2: 'In the absence of exotic matter, it is impossible to construct a warp-drive.' KIND: THEOREM (PDE existence/uniqueness + causal-structure corollary), no measured input.",
"published_hypotheses":[
 "L1 smooth initial data (Sigma, h, K, J, rho) satisfying the Einstein constraint equations (2.3) (Low p.2-3; smoothness also in Thm 2.1)",
 "L2 the development considered is the MAXIMAL GLOBALLY HYPERBOLIC development with Cauchy surface i(Sigma); nothing is said beyond it (Low p.2: M 'need not be an inextensible space-time')",
 "L3 matter described by a quasilinear symmetric hyperbolic system A^a nabla_a u + B u = c (2.2), with T_ab depending only on u and g (Low p.2)",
 "L4 the ray cone of (2.2) lies INSIDE the light cone of g (bicharacteristics causal) -- required for Corollary 4.1 and Sec. 4 (Low p.2, p.5)",
 "L5 the evolution equation is FIXED; only initial data are changed ('we will consider only the effects of changing the initial conditions, while keeping the evolution equation fixed', p.3)",
 "L6 a 'decision' is modelled as a change of data on K = J+(p) cap Sigma for a single event p to the past of Sigma; data on Sigma\\K unchanged (p.5)",
 "L7 (for Theorem 4.2 only) 'physically reasonable' = symmetric hyperbolic AND DEC; exotic otherwise (Def. 2.3); DEC enters only through Hawking-Ellis to exclude ray cones outside the light cone",
 "L8 (linear statement) bicharacteristics of linearised vacuum perturbations are the null geodesics of the background (p.4, citing Wald 1984)"
],
"hypothesis_drift":[
 "DROPPED (load-bearing) -- matter class, L3+L4: phase1.py:114-116 and :312-313 say 'matter acting in a compact region cannot alter the metric outside its causal future' with NO condition on the matter. Low's Corollary 4.1 needs matter obeying a symmetric hyperbolic system whose ray cone lies inside g's light cone. phase1's winning device holds NEGATIVE enclosed mass (phase1.py:36, :183 'A GALAXY OF NEGATIVE MASS'), i.e. violates WEC hence DEC -- 'exotic' in Low's Def. 2.3 -- and its matter model is never specified (CANDIDATES, phase1.py:394-407, include Casimir and GJW quantum sources). DEC violation does NOT by itself break causal propagation (Kontou-Sanders 2003.01815 p.2: energy conditions 'seem by no means a necessary condition for a classical field theory to have a well-posed initial value formulation'); nor is causal propagation guaranteed without it (the Hawking-Ellis conservation theorem, restated in Fewster math-ph/0501073 p.1, is DEC-SUFFICIENT). The re-derivation C4 shows the hypothesis is load-bearing: a metric-like field sourced by matter with characteristic speed 1.5c is altered out to 1.5ct. Needed as a NAMED hypothesis: H_M 'the device's matter obeys a (symmetric) hyperbolic evolution with characteristic cones inside or on g's null cone'.",
 "DROPPED -- quantum sources: for Casimir/GJW-type sources (phase1.py:400-404) the evolution is the semiclassical Einstein equation, higher-order and nonlocal; Galanda et al. 2604.01047 (2026) establish well-posedness only for the LINEARISED semiclassical Einstein-Klein-Gordon system on Minkowski ('the conceptual path toward local well-posedness in the nonlinear case is clear ... we postpone this detailed derivation to future work', Sec. 1.5). For that class Theorem 4 rests on a theorem that is not yet proved in the form used; OPEN, not refuted.",
 "WEAKENED/REWORDED (harmless as used) -- 'characteristic speed c', phase1.py:114: in the source the characteristics are the null cone of the DYNAMICAL metric g (Low p.4; C3: with shift v the coordinate speeds are v +/- c). The tree's L/2c is nonetheless right, because the bound is set by the boundary of D+(Sigma\\K), which lies in the region isometric to the UNCHANGED spacetime M (Low Sec. 4); with M flat along the corridor that boundary moves at c. Unnamed premise: the pre-action spacetime along the corridor is (near) flat -- with NEC-respecting background masses the Shapiro effect only delays (Visser-Bassett-Liberati gr-qc/9908023 p.1), so the floor can only get later.",
 "ADDED/REWORDED -- the agent model, phase1.py:116-119 and :310-313: 'established by agents acting inside it ... not complete before L/2c after the first action -- best case, acting from the midpoint'. Low's form is L6: a change on K = J+(p) cap Sigma for ONE decision event p. The tree's 'first action' must mean that decision event. If agents are pre-positioned along the corridor and act at a pre-agreed instant, completion after the first physical action can be ~0 (< L/2c; C5c) -- the causal cost moves into the earlier deployment, which Low's theorem prices from ITS originating event. The clause 'an endpoint cannot know it is complete before then' survives unconditionally (knowledge of the far end needs a signal, L/c >= L/2c; C5c). A naming gap, not an error.",
 "DROPPED (minor) -- L1, L2, L5: smoothness, the maximal globally hyperbolic development, and a fixed evolution equation are not stated. They are met by a static, compactly supported, smooth corridor on the fixed manifold of D1 (phase1.py:17-30), which contains no Cauchy horizon; a construction that created a Cauchy horizon or changed the matter's physics (not just its data) would leave the theorem's scope. create.py's wormhole scope note (phase1.py:47-58) already keeps throats outside D1-D5.",
 "SCOPE (not a drift of the source) -- the corollary's 1.5 factor, phase1.py:121-122, :316-340: Low's theorem gives the FLOOR 'nothing reaches the far endpoint before a light signal from the decision event through the unchanged M' (L/2c from a midpoint decision; C5a). single_transition_total = L/2c + L/c is a PROTOCOL total (wait for completion, then traverse at c) that also rests on the tree-internal claim that the corridor's saving is a saturated offset (phase1.py:320-324). The external theorem supports 'never beats light from the decision event'; the specific 1.5 is the tree's own arithmetic (C1d agrees)."
],
"data_at_publication":[
 {"quantity":"speed of gravitational disturbances relative to c (the result's 'characteristic speed c')",
  "value_then":"1952/1998: a property of the theory (characteristics = null cone of g); no direct measurement of v_gw",
  "value_now":"-3e-15 <= (v_gw - c)/c <= +7e-16 (GW170817/GRB170817A, eq. (1))",
  "source_now":"arXiv:1710.05834v2 abstract and Sec. 4.1 eq. (1), READ by the sibling DOCKET 67 audit "+SP+"/audits/1710.05834.json (cached alphaXiv text); not re-read in this stage (quota)",
  "moves_conclusion":"No. Computed (C1e): the +7e-16 edge moves L/2c = 6.311520e7 s by 4.42e-8 s. The measurement CONFIRMS the premise at the 1e-15 level."},
 {"quantity":"L = 4 ly, light year",
  "value_then":"phase1.py:213 LIGHT_YEAR = 9.4607e15 m (truncated)",
  "value_now":"IAU light year = c x Julian year = 9460730472580800 m exactly (definition; c = 299792458 m/s exact SI)",
  "source_now":"SI definition of c; IAU Julian-year light year (arithmetic identity, C1a)",
  "moves_conclusion":"No. With the IAU value L/2c = 63115200 s = 2 Julian years exactly; with the tree's value 63114997 s. The tree's pinned 6.3113e7 s (phase1.py:474) differs from either by 3.2e-5 relative -- inside its stated 1e-3 tolerance: a rounding DISCREPANCY in a pinned figure, recorded, not an error."},
 {"quantity":"year used for the 2.0 yr figure",
  "value_then":"3.15576e7 s (Julian year), phase1.py:475",
  "value_now":"same (definition)",
  "source_now":"definition",
  "moves_conclusion":"No. 1.9999936 yr with the tree's light year (C1c)."}
],
"rederivation":{
 "method":"sympy",
 "script_path":SP+"/rederive/gr-hyperbolicity-causal-propagation.py",
 "outcome":"ALL PASS, 15/15, exit 0 (~55 s; output in rederive/gr-hyperbolicity-causal-propagation.out). C1a-d: L/2c = 2 Julian years exactly with the IAU light year; tree value 6.31150e7 s vs pinned 6.3113e7 (3.2e-5 rel, inside 1e-3 tolerance); 1.9999936 yr; penalty = 3/2 exactly. C1e: GW170817 bound moves L/2c by 4.4e-8 s. C2a: linearised Ricci identity R1_mn = -1/2 box h_mn + d_(m V_n) verified for all 10 components with generic h_mn(t,x,y,z) -- de Donder principal part is -1/2 box; C2b: characteristic set omega = +/- c k (Low p.4 linear statement). C3: nonlinear harmonic-gauge principal symbol g^{ab} xi_a xi_b = 0 with shift v gives coordinate speeds v +/- c: 'speed c' is local to the dynamical metric, and equals c at the front where v -> 0. C4: Duhamel front law for a metric-like field (speed c) sourced by matter (speed c_m) sourced by a compact midpoint action: front = a + max(c, c_m) t, checked by exact support algebra and by quadrature with positive sources for c_m = 0.5c, c, 1.5c (4.500, 4.500, 6.500) -- the matter ray-cone hypothesis L4 is load-bearing. C5: floor at the far end after a midpoint decision = L/2c = 2.0 yr; 1.5 L/c = 6.0 yr is a protocol total; pre-positioned agents defeat the 'first action' clause (completion ~0) but not the 'endpoint cannot know' clause (L/c). NOT checked (not finite): the Choquet-Bruhat / Choquet-Bruhat-Geroch existence and geometric-uniqueness theorems and the Hawking-Ellis conservation theorem themselves.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"M. Visser, B. Bassett, S. Liberati, 'Perturbative superluminal censorship and the null energy condition', arXiv:gr-qc/9908023v1 (1999)","effect":"extends","what":"Linearised about Minkowski, the NEC forces light cones to narrow: 'the Shapiro time delay in any weak gravitational field is always a delay relative to the Minkowski background, and never an advance' (abstract p.1). Supports the tree's unnamed flat-background premise (NEC-respecting background matter can only make the L/2c floor later) and names the complement: effective FTL needs NEC violation, which the tree's device has.","read_status":"READ (alphaXiv cached page text pp.1-2 and refs, "+CM+"gr-qc_9908023v1.txt)"},
 {"ref":"E.-A. Kontou, K. Sanders, 'Energy conditions in general relativity and quantum field theory', arXiv:2003.01815v2 (2020)","effect":"narrows","what":"p.2: energy conditions 'seem by no means a necessary condition for a classical field theory to have a well-posed initial value formulation, even though they may enter as a useful method in the proof' (citing Ringstrom). So Low's DEC route (L7) is sufficient, not necessary: the tree's negative-mass device is not thereby excluded from causal propagation, but neither is it included -- the relevant hypothesis is the matter's characteristic cone (L4), which the tree does not state.","read_status":"READ (alphaXiv cached text, "+CM+"2003.01815v2.txt, p.2 passage)"},
 {"ref":"S. Galanda, P. Meda, et al., 'The Semiclassical Einstein-Klein-Gordon System: Asymptotic Analysis of Minkowski Spacetime', arXiv:2604.01047v1 (2026)","effect":"narrows","what":"Restates Fourès-Bruhat 1952 and Choquet-Bruhat-Geroch 1969 (Sec. 1.6). For quantum matter the metric perturbations obey 'a higher-order, nonlocal hyperbolic PDE'; well-posedness proved for the LINEARISED problem on Minkowski treating nonlocal terms perturbatively (Thm 4.14), with a late-time exponential instability (Thm 4.16); the nonlinear case is postponed. For the tree's quantum candidates (Casimir, GJW) the domain-of-dependence statement is therefore not yet a theorem in the nonlinear regime.","read_status":"READ (alphaXiv cached text, "+CM+"2604.01047v1.txt, abstract, Sec. 1.4-1.6)"},
 {"ref":"C. de Rham, A.J. Tolley, 'Causality in Curved Spacetimes: The Speed of Light & Gravity', arXiv:2007.01847v2 (2020)","effect":"contested","what":"Within low-energy EFTs of QED and gravity the low-energy speed of light or of GWs 'can typically be mildly superluminal in curved spacetimes', but consistent EFTs 'self-protect' so that any such superluminality 'is necessarily unresolvable, and cannot be argued to lead to a macroscopically larger lightcone' (abstract); causality is the front velocity v_f = lim 1/n(omega) <= 1 and a retarded propagator vanishing outside the forward light cone (Sec. 2.1, p.8). Bears on L4 at the EFT level: small local superluminality does not by their argument give a macroscopic lead; this is an argument within EFT, not a theorem for arbitrary exotic matter.","read_status":"READ (alphaXiv cached text, "+CM+"2007.01847v2.txt, pp.1, 8, 12)"},
 {"ref":"J. Osorio Morales, O.P. Santillan, 'About apparent superluminal drives in generic gravity theories', arXiv:2004.12523v4 (2022)","effect":"extends","what":"Independent proof of Galloway's generalisation of Gao-Wald: time advance through a compact deformation K is excluded regardless of gravity model unless a null line exists (abstract). This is the TRAVERSAL-side wall (chronology.py's 'LATE'), not the establishment-side causal-propagation theorem audited here; it corroborates phase1.py:125-127's 'same wall seen from the propulsion side' only as a companion result.","read_status":"READ (alphaXiv cached text pp.1-2, "+CM+"2004.12523v4.txt)"},
 {"ref":"discover_papers search (this stage)","effect":"contested","what":"The single permitted discover_papers call returned 'alphaXiv assistant quota exceeded'; the later literature above was drawn from alphaXiv page text already cached in this workflow. Friedrich-Rendall gr-qc/0002074 and Rendall gr-qc/0505133 (standard reviews of the Cauchy problem) could not be read. Absence of a found refutation is not proof of absence.","read_status":"NAMED-NOT-READ (tool quota; egress 403 on arxiv.org)"}
],
"lacked_data":"M's hypothesis tested for this result. The result is a THEOREM of PDE and causal structure (Fourès-Bruhat 1952; Choquet-Bruhat-Geroch 1969; applied by Low 1998); its conclusion depends on no measured datum, so there is no datum the authors could have lacked that would move it. The one physical premise with an empirical face -- that gravitational disturbances propagate at c -- was untested by direct measurement until GW170817 (2017), which confirmed it to -3e-15..+7e-16; computed here, that moves L/2c by 4.4e-8 s (C1e). Evidence FOR M's suspicion in a different form: what the source had and the tree omits is a HYPOTHESIS, not a datum -- the matter must obey a fixed hyperbolic evolution with characteristic cones inside the light cone (Low L3-L5). Low's own warp-drive theorem is explicitly conditional on it ('In the absence of exotic matter'), the tree's device is exotic (negative mass), and for quantum sources the nonlinear semiclassical Cauchy problem is still unproved (2604.01047, 2026). Evidence AGAINST over-reading that: no read source exhibits matter that is both consistent and macroscopically superluminal (de Rham-Tolley argue EFT superluminality is unresolvable), energy-condition violation alone does not produce superluminal characteristics (Kontou-Sanders; e.g. any field whose principal part is the wave operator of g), and the tree names no such matter. So having the missing piece would not change the theorem; it would decide whether the tree's device lies in its scope.",
"grade":"NARROWED",
"grade_evidence":"(1) Source READ: Low gr-qc/9812067 Thm 2.4, Cor. 3.1, Cor. 4.1 and Sec. 4 state exactly the tree's claim -- data unchanged on Sigma\\K => metric unchanged on D(Sigma\\K); nothing reaches a distant worldline earlier than the boundary of D+(Sigma\\K) in the unchanged spacetime -- but only for smooth data, the maximal globally hyperbolic development, a FIXED matter evolution that is symmetric hyperbolic with ray cones INSIDE the light cone, and a change originating at one event p. (2) The tree (phase1.py:114-119, :312-313) states it for 'matter' with no condition, while its winning device carries negative mass (phase1.py:36, :183) of unspecified model and its candidate list includes quantum sources (phase1.py:400-404) whose nonlinear Cauchy problem is not proved (2604.01047). The dropped hypothesis is load-bearing: C4 computes the metric-like front at a + max(c, c_m) t, so a source with c_m > c alters the field outside the c-cone. Hence the theorem holds on a SMALLER class than the tree applies it to: NARROWED. (3) Not WRONG: no counterexample to Theorem 4 is exhibited for any matter the tree specifies; for causal hyperbolic matter the re-derivation agrees with the source and with the tree's numbers (C1-C3, C5; 15/15 PASS). (4) Not DATA-DEPENDENT: the only moved datum (GW170817) confirms c to 1e-15 and moves L/2c by 4.4e-8 s. (5) Recorded discrepancies, nothing repaired: pinned 6.3113e7 s vs computed 6.31150e7 s (3.2e-5 rel, inside the tree's 1e-3 tolerance); 'characteristic speed c' is a local-cone statement that yields L/2c only because the front lies in the unchanged, flat region; 'first action' must be read as Low's single decision event (pre-positioned agents defeat the completion clause, not the knowledge clause).",
"what_would_change_the_grade":"STANDS if the tree names H_M ('the device's matter obeys a hyperbolic evolution with characteristic cones inside or on g's null cone, with a fixed evolution equation') and 'first action = the single decision event whose future contains the change' as hypotheses of Theorem 4, or specifies a matter model for the corridor that is shown to satisfy them (e.g. a field whose principal part is the wave operator of g, with the coupled system well-posed). WRONG (for the tree's use) only if a consistent matter model admissible to the corridor were exhibited whose characteristics lie outside g's light cone at macroscopic scale and whose coupled Einstein-matter system is well-posed -- none is exhibited in anything read here, and de Rham-Tolley argue EFT superluminality cannot do it. OPEN for the quantum candidates until a nonlinear local well-posedness / domain-of-dependence theorem for the semiclassical Einstein equations exists (2604.01047 postpones it). A reading of Friedrich-Rendall gr-qc/0002074 or Rendall gr-qc/0505133 disagreeing with Low's restatement of the classics would reopen (1); nothing read here disagrees.",
"reverify_command":"python3 "+SP+"/rederive/gr-hyperbolicity-causal-propagation.py  # expect '15/15 PASS', 'OUTCOME: ALL PASS', exit 0 (~55 s). Source text: sed -n '1,120p;400,470p;500,640p' "+CM+"gr-qc_9812067v1.txt (Low Thm 2.1, 2.4, Cor. 2.5, Sec. 3-4, Thm 4.2); live re-read when quota allows: alphaXiv answer_pdf_queries(paper='gr-qc/9812067', queries=['Theorem 2.4','Corollary 4.1','ray cone inside light cone','Theorem 4.2']) and answer_pdf_queries(paper='gr-qc/0002074', queries=['domain of dependence','characteristics of the Einstein equations','matter models']). Restatements: grep -n 'dominant energy condition (DEC)' "+CM+"math-ph_0501073v1.txt; grep -n 'Four.s-' "+CM+"2604.01047v1.txt; grep -n 'necessary condition' "+CM+"2003.01815v2.txt. Tree sites: sed -n '24,40p;111,128p;175,196p;213p;309,340p;394,407p;471,477p' /home/user/Claude-Method-Works/research/warp-drive/phase1.py",
"report_path":SP+"/audits/gr-hyperbolicity-causal-propagation.json"
}
json.dump(r, open(r["report_path"],"w"), indent=1, ensure_ascii=False)
print("ok", len(json.dumps(r)))
