import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
C = D + "/src/casmag/all/"
rep = {
"key": "le-2026-stiffer-wall-clause",
"name": "Le's clause: a slightly stiffer still-admissible wall is strictly stable at no cost in surface dec margin (decoupling)",
"source": {
 "located": "An T. Le, 'Steering a warp drive without exotic matter', arXiv:2606.22531v2 [gr-qc] 30 Jun 2026 (stamp at line 59 of the cache file), Sec. 15 ('Linear stability'), printed p.28, lines 1512-1529 of the cache; the clause cites App. J for its derivation. Later version read too: arXiv:2606.22531v4 [gr-qc] 13 Sep 2026, retitled 'Radiative steering of warp shells'.",
 "read_status": "READ",
 "via": "Live alphaXiv calls in this stage (answer_pdf_queries, get_paper_content fullText, discover_papers) all returned 'alphaXiv assistant quota exceeded'; direct curl to arxiv.org / export.arxiv.org / alphaxiv.org returned no response (code 000). What was read instead is verbatim alphaXiv <page> text returned earlier in this project and harvested by src/casmag/allpages.py: " + C + "2606.22531v3.txt (md5 b9eaaa51be71f3bcc3b4845c828a4564; the file is keyed 'v3' but its arXiv stamp reads v2, 30 Jun 2026; pages 1-4, 7, 8, 12, 23, 25-28, 45 only) and " + C + "2606.22531v4.txt (md5 5a693452d50444f5188264f046e56c17; pages 1-10, 13, 23, 29, 30, 38, 39 only). The clause itself is READ verbatim at source. App. J (where Le derives it) is NOT among the cached pages and is NAMED-NOT-READ, so Le's own statement of the clause's hypotheses beyond the one sentence is unread. The Poisson-Visser formalism used in the re-derivation (eq (15) conservation, eq (23) beta^2 = dp/dsigma, V''>0 criterion) is as read at source in the sibling audit gr-qc_9506083; PSP arXiv:2604.05980v1 read from the cache " + C + "2604.05980v1.txt (md5 9916ebc75c7859da12c37c59acc4458f)."
},
"published_statement": "Le, arXiv:2606.22531v2, p.28 (Sec. 15), verbatim: 'Linear stability: marginal, conditionally burn-limited. The realized tangential-pressure wall sits exactly on the Poisson-Visser marginal curve V''(R) = 0 (App. J): a radial displacement is a neutral zero mode. Under the frozen-background rear-pole redshift the marginal wall e-folds in tau_efold = sqrt(2/|V''|), of order a light-crossing time (App. J), so the Tsiolkovsky burn outruns the instability only in a restricted high-compactness, brief-rapidity corner. A slightly stiffer, still-admissible wall is strictly stable at no cost in the surface dec margin, which is junction-fixed and independent of the equation-of-state slope, so strict stability and strict dominant energy decouple; this stiffened wall is a nearby model, not the realized one (App. J). The interior cavity is tidally regular (K^mu_rho = 0) for lambda < 1, and the fully-dynamic, flux-coupled stability of the radiating shell remains open.' The later version v4 (13 Sep 2026) carries, in its cached pages, NO stiffer-wall clause, no 'marginal', no V''; its abstract reads 'Self-similar shells require anisotropic stress and have growing normal modes with the ambient geometry and coefficients held fixed', its Sec. 7 'compression produces growing normal modes in the frozen surface equations on a prescribed geometry', its Fig. 1 caption 'DEC does not establish stability', and its intro cites PSP [19]: 'For a barotropic fluid shell, the fully coupled study [19] finds growing even-parity modes at all sampled multipoles l >= 2 ... Its constitutive assumptions differ from those of the radiating shell considered here.' v4 pages 11-12 (its Sec. 4.3-4.x, 'normal stability') are not cached, so whether v4 restates, withdraws or supersedes the clause is UNREAD.",
"published_hypotheses": [
 "LH1 (read, v2 p.28): the setting is LINEAR stability of the wall's RADIAL displacement ('a radial displacement is a neutral zero mode'), measured by the Poisson-Visser potential V''(R).",
 "LH2 (read): FROZEN BACKGROUND ('Under the frozen-background rear-pole redshift'); the flux-coupled dynamic stability of the radiating shell is explicitly left open in the same paragraph.",
 "LH3 (read): the stiffened wall is 'a nearby model, not the realized one' -- the clause is about a hypothetical wall with a steeper equation-of-state slope, not about Le's realized tangential-pressure wall.",
 "LH4 (read): 'still-admissible' -- the stiffened wall must remain admissible; which conditions (surface dec only, or also a causal sound speed) are meant is stated in App. J, which is UNREAD.",
 "LH5 (read): the surface dec margin is 'junction-fixed' -- the static (sigma_0, p_0) of the matched thin shell; Eq (17) of v2 (surface dec iff x < 24/25, v2 line 1147, abstract).",
 "LH6 (implied by 'equation-of-state slope' and 'Poisson-Visser', not read in App. J): a barotropic surface law with slope beta^2 = dp/dsigma at the equilibrium (PV eq (23)); thin (distributional) shell; static Minkowski interior / Schwarzschild exterior anchor at lambda = 0."
],
"hypothesis_drift": [
 "DROPPED -- the caveat. wall.py:11-14 quotes the clause and stops at 'decouple.'; Le's sentence continues '; this stiffened wall is a nearby model, not the realized one (App. J).' The word 'nearby' does not occur in wall.py. The substance is partly restored at wall.py:193-196 ('Le's own realized wall is a Bowers-Liang anisotropic equilibrium rather than this one'), and research/README.md:887-888 carries the caveat in full. Recorded: the quotation as used is a truncation, not a misquote.",
 "DROPPED at the dependent sentence -- RADIAL/LINEAR. Le's clause sits in a paragraph about the linear RADIAL mode (LH1). The tree's rests_on_it statement wall.py:39-40 'STRICT STABILITY IS AVAILABLE EVERYWHERE THE WALL IS REALIZABLE' carries no 'radial'. wall.py:22 ('the linearised radial mode is strictly stable iff') and wall.py:119-128 ('STIFFENING THE WALL FIXES THE RADIAL MODE AND DOES NOTHING TO l >= 2', from PSP arXiv:2604.05980, which finds an unstable even-parity mode 'for all sampled values of the shell's compactness and adiabatic index, and all sampled values of the multipolar order l >= 2') supply the restriction in the same file. The canonical hypotheses list ('linear surface EoS', 'statics fixed by the junction alone') omits it. 'Strictly stable' is true of l = 0 only.",
 "OMITTED from the canonical hypotheses, named in the file -- FROZEN BACKGROUND / lambda = 0 (LH2, LH6): wall.py computes the static Minkowski/Schwarzschild thin shell (statics(), wall.py:247-255); Le's realized exterior radiates. wall.py:197-200 names it ('Not the flux-coupled dynamic stability of the RADIATING shell, which Le leaves open in his Sec. 15').",
 "OMITTED from the canonical hypotheses, named in the file -- THIN SHELL and beta^2 AS A PROXY: wall.py:201-203 ('beta^2 here is the slope of the thin-shell surface equation of state, which is not identical to the microphysical sound speed of the finite-thickness wall. The causality reading beta^2 <= 1 is ... a proxy'). PV sec IV (read in sibling audit gr-qc_9506083) says the same: 'there is no guarantee that beta0 actually is the speed of sound'.",
 "SCOPE OF 'still-admissible' -- NOT a drift in the tree, a limit on the clause read universally: under the causal proxy beta^2 <= 1 a stiffer admissible wall exists iff 15s^3+3s^2-s-1 > 0, i.e. x < x* = 0.843741892629 (C7). On x in (x*, 24/25) the thin shell satisfies strict surface dec (Le's Eq (17) window) but NO causal stiffening stabilises it (z3 witness s = 1/4, x = 15/16). The tree respects this: it asserts the clause only on the realized-wall window x < 4/5 (wall.py:32-35; z3 C7 proves a causal stiffer wall exists on all of x < 4/5) and records 'the thin-shell dec window 24/25 is NOT' below x* (wall.py:554). If Le's 'admissible' is surface dec alone, the clause holds on the whole 0 < x < 24/25 with some beta^2 (possibly > 1). App. J unread, so which reading Le intends is OPEN.",
 "IMPLICIT, not named -- EQUILIBRIUM-ONLY decoupling: sigma_0, p_0 carry no beta^2 (C2, C3, C6), but off equilibrium d(sigma-p)/dR|R0 = -(beta^2-1)(s-1)(3s+1)/(8 pi R0^2 s), which depends on beta^2 (C9). The tree goes beyond Le here (wall.py:207-221, 'bonus theorem') and the finite-amplitude claim holds: for p0/sigma0 < beta^2 <= 1 the surface dec sigma >= |p| holds on the whole ray (C10 numeric, R/R0 in [1e-3, 1e6]), and beta^2_crit - p0/sigma0 = x/(4s^2(1+3s)) > 0 exactly (C10 sympy). Wording nuance recorded, not a fault: wall.py:209-212 uses sigma - p as 'the margin'; when beta^2 > p0/sigma0, p turns negative at large R (p -> K/A < 0) and the worst-observer margin there is sigma + p, which stays positive; the conclusion is unchanged.",
 "STRONGER THAN NEEDED, not a narrowing -- the canonical hypothesis 'linear surface EoS p = p0 + beta^2 (sigma - sigma0)': V''(R0) depends on the equation of state only through its slope at R0 (C4 uses sigma'' built from beta^2 at R0), so the radial criterion holds for any barotropic law with that local slope; linearity is used only by wall.py's closed-form V(R) (wall.py:257-268) for finite-amplitude checks.",
 "DISCREPANCY IN THE TREE'S OWN CHECK, recorded not repaired: the data_used check wall.py:527-528 'dec margin is identical for every beta^2' computes len({round(dec_margin_scaled(0.3), 12)}) == 1, a one-element set for any input; no beta^2 is varied, so the test is vacuous. The claim it guards is true (statics() takes no beta^2; C2', C6 here). The companion checks wall.py:522-526 (V(R0)=0 and V'(R0)=0 at beta^2 = 0, 0.05, 0.5, 1.0) are real and are here extended to all beta^2 symbolically (C3).",
 "SOURCE VERSION: the tree cites the v2 title and content (warpshell.py:6; README:831). The cached pages of v4 (13 Sep 2026, retitled) do not carry the clause and instead report growing normal modes for the self-similar (accelerating) family in the frozen surface equations. That v4 result concerns the anisotropic reconstructed law on a prescribed accelerating geometry, not the static barotropic anchor, so it does not contradict the clause as read; whether its uncached Sec. 4 addresses the stiffer-wall clause is unread."
],
"data_at_publication": [
 {"quantity": "any empirical datum (constants, measurements)", "value_then": "none -- the clause is a closed-form statement in s = sqrt(1-x) and beta^2, geometric units", "value_now": "none", "source_now": "re-derivation rederive/le-2026-stiffer-wall-clause.py", "moves_conclusion": "no -- nothing measured enters"},
 {"quantity": "beta^2_crit at Le's operating point x = 0.3 (the 'slightly' in 'slightly stiffer')", "value_then": "not printed in the cached v2 pages (App. J unread); wall.py:28 gives 0.07933", "value_now": "0.0793318... = (1-s)(3s^2+2s+1)/(4s^2(1+3s)), s = sqrt(0.7)", "source_now": "sympy C4, wall.py beta2_crit agreement to 1e-13 (C11)", "moves_conclusion": "no"},
 {"quantity": "causal ceiling x* (beta^2_crit = 1)", "value_then": "0.84374189 (wall.py:32)", "value_now": "0.843741892629416 (unique root in (0,1) of 15s^3+3s^2-s-1, s* = 0.395294962490777)", "source_now": "sympy nroots + z3 (C7)", "moves_conclusion": "no -- but it bounds 'still-admissible' under the causal proxy to x < x*, below the 24/25 dec window"},
 {"quantity": "PSP radial index Gamma_1 (independent literature value)", "value_then": "PSP arXiv:2604.05980v1 (8 Apr 2026) eq (3.16b): Gamma_1 = (1+2 sqrt F+3F)/(4F), F = 1-2C = s^2 (restating LeMaitre-Poisson 2019)", "value_now": "equals beta^2_crit (sigma0+p0)/p0 identically", "source_now": "sympy C8", "moves_conclusion": "no -- confirms the radial threshold the clause relies on"},
 {"quantity": "source text of the clause", "value_then": "arXiv:2606.22531v2, 30 Jun 2026, p.28", "value_now": "arXiv:2606.22531v4, 13 Sep 2026: clause absent from the cached pages (1-10, 13, 23, 29, 30, 38, 39); v4 Sec. 4 pages 11-12 uncached", "source_now": C + "2606.22531v4.txt", "moves_conclusion": "undetermined -- a changed later version is a source-status fact, not a refutation; its bearing on the clause is unread"}
],
"rederivation": {
 "method": "sympy",
 "script_path": D + "/rederive/le-2026-stiffer-wall-clause.py",
 "outcome": "ALL CHECKS PASS, exit 0 (output in rederive/le-2026-stiffer-wall-clause.out). From scratch, Minkowski inside / Schwarzschild outside, PV conservation sigma' = -2(sigma+p)/R, slope beta^2 at R0: C1 V = 1-(m_s/2R+M/m_s)^2 solves the Lanczos junction. C2 V(R0)=0, V'(R0)=0 give sigma0 = (1-s)/(4 pi R0), p0 = (1-s)^2/(16 pi R0 s) uniquely, no beta^2. C3 dV(R0)/dbeta^2 = dV'(R0)/dbeta^2 = 0 identically (all beta^2, not four samples). C4 V''(R0) = (12 beta^2 s^3 + 4 beta^2 s^2 + 3s^3 - s^2 - s - 1)/(2 R0^2 s^2): affine in beta^2, slope 2(1+3s)/R0^2 > 0, unique zero beta^2_crit = (1-s)(3s^2+2s+1)/(4s^2(1+3s)) = wall.py's and the sibling audit's form. C5 z3 (nonlinear reals, negation unsat, vacuity guard sat): for all s in (0,1) and eps > 0, V''(beta^2_crit+eps) > 0 -- 'slightly stiffer' suffices. C6 8 pi R(sigma0-p0) = -(5s-1)(s-1)/(2s), beta^2-free. C7 causal admissibility: beta^2_crit < 1 <=> x < x* = 0.843741892629; z3: on (x*, 24/25) strict dec holds with no causal stiffer wall (witness x = 15/16); on x < 4/5 a causal stiffer wall always exists. C8 beta^2_crit (sigma0+p0)/p0 = PSP Gamma_1 identically. C9 off-equilibrium d(sigma-p)/dR|R0 depends on beta^2. C10 beta^2_crit - p0/sigma0 = x/(4s^2(1+3s)) > 0; sigma >= |p| on R/R0 in [1e-3,1e6] for stable causal walls. C11 wall.py (imported read-only) agrees to 1e-12; wall.py:527-528's check is vacuous but true. The clause is CORRECT for the linear radial mode of the static barotropic thin shell; under the causal proxy it holds for x < x*, which contains the realized-wall window x < 4/5.",
 "agrees_with_source": "yes"
},
"later_literature": [
 {"ref": "A. T. Le, arXiv:2606.22531v4 (13 Sep 2026), 'Radiative steering of warp shells' -- later version of the source", "effect": "contested", "what": "The clause, the 'marginal' zero-mode statement and the V'' language are absent from all cached v4 pages; v4 instead states that self-similar (accelerating, lambda != 0) shells 'require anisotropic stress and have growing normal modes with the ambient geometry and coefficients held fixed' and that 'DEC does not establish stability', and cites PSP for l >= 2 growth in barotropic shells while noting 'Its constitutive assumptions differ'. This is a different class (reconstructed anisotropic law, prescribed accelerating geometry, frozen surface equations) from the clause's static barotropic anchor, so it does not contradict the clause as read; but the author's later version no longer relies on it in any page read. 'contested' is used because the enum has no 'superseded/unread' value; no contest of the clause's content is shown.", "read_status": "READ (partial: cached pages 1-10, 13, 23, 29, 30, 38, 39; Sec. 4 pages 11-12 unread)"},
 {"ref": "T. Pitre, B. Schneider & E. Poisson, arXiv:2604.05980v1 (8 Apr 2026), 'Self-gravitating thin shells are dynamically unstable on all angular scales'", "effect": "narrows", "what": "Same configuration (static barotropic perfect-fluid thin shell, Minkowski inside, Schwarzschild outside). Restates LeMaitre-Poisson 2019: 'radially stable whenever Gamma >= 3/2' (Newtonian) and eq (3.16b) Gamma_1 -- which equals the clause's beta^2_crit exactly (C8), CONFIRMING the radial half. Then finds an exponentially growing even-parity mode 'for all sampled values of the shell's compactness and adiabatic index, and all sampled values of the multipolar order l >= 2', so 'strictly stable' in the clause is true of the radial mode only. Contemporaneous with (earlier than) Le v2; whether v2 cites it is not visible in the cached pages; v4 cites it as [19].", "read_status": "READ (cached verbatim alphaXiv page text, abstract and sec. X)"},
 {"ref": "E. Poisson & M. Visser, arXiv:gr-qc/9506083 (1995) -- the formalism, pre-dating the clause", "effect": "confirms", "what": "Supplies the V''(a0) > 0 criterion, beta^2 = dp/dsigma (eq 23) and the conservation law (eq 15) used in the re-derivation; its sec IV caveat that beta need not be the sound speed is the reason 'still-admissible' via beta^2 <= 1 is a proxy.", "read_status": "READ-VIA-RESTATEMENT (verbatim quotes in sibling audit audits/gr-qc_9506083.json, read at source there)"},
 {"ref": "discover_papers for later work on stiffened thin-shell stability and the dec/stability decoupling", "effect": "contested", "what": "NOT RUN TO RESULT: the one discover_papers call returned 'alphaXiv assistant quota exceeded'. No later literature beyond the two cached papers above was searched; recorded as a gap, not as absence of later work. H. Yang, B. Bonga & Z. Pan, PRL 130, 011402 (2023), arXiv:2207.13754 (eikonal l >> 1 membrane instability) and P. Mourao, J. Natario & R. Vicente, CQG 42, 025023 (2025), arXiv:2409.10602 are cited by Le v4 [17, 18] and are NAMED-NOT-READ here.", "read_status": "NAMED-NOT-READ"}
],
"lacked_data": "M's hypothesis tested: the clause contains no measured quantity, so no datum the author lacked can move it; the re-derivation from the metric reproduces every part of it (C2-C6) and an independent literature threshold (PSP Gamma_1, C8) agrees identically. What bears on it is INFORMATION rather than data: the PSP result (arXiv:2604.05980, April 2026) that the same static barotropic thin shell is unstable at every sampled l >= 2, with beta^2-independent-looking growth across all sampled Gamma. Having it does not change the clause's radial conclusion -- Le's v2 sentence is already in a paragraph about the radial mode -- but it does change what 'strictly stable' can be read to cover: l = 0 only. Evidence that the author later had it: Le v4 cites PSP [19] and no longer carries the clause in any cached page. Evidence either way that the author was wrong: none -- the radial statement is re-derived and machine-checked; the v4 change is unexplained in the pages read. The tree already absorbed the PSP information (wall.py:109-128) and corrected its own over-reading of the diffuse corner (wall.py:57-62, 153-190), so M's hypothesis is borne out here as INCOMPLETENESS (a mode not covered), not inaccuracy.",
"grade": "NARROWED",
"grade_evidence": "The clause is READ verbatim at source (Le arXiv:2606.22531v2 p.28) and its content re-derives exactly (sympy C1-C6, C8; z3 C5, C7; wall.py agreement C11): at the static barotropic thin shell, sigma0 and p0 carry no beta^2, V''(R0) is affine in beta^2 with slope 2(1+3s)/R0^2 > 0, so any epsilon of extra stiffness makes the RADIAL mode strictly stable while the dec margin -(5s-1)(s-1)/(2s) is unchanged. No datum enters; no misprint found. It is NARROWED, not STANDS, because it holds on a smaller class than the tree's dependent sentence states: (i) 'strictly stable' is true of the linear radial (l = 0) mode on a frozen background only -- PSP arXiv:2604.05980 finds an unstable even-parity mode for every sampled compactness, adiabatic index and l >= 2 in exactly this configuration -- while wall.py:39-40 says 'STRICT STABILITY IS AVAILABLE EVERYWHERE THE WALL IS REALIZABLE' with no 'radial', and the canonical hypotheses omit radial/frozen-background/thin-shell/lambda = 0; (ii) the quotation at wall.py:11-14 drops Le's own caveat 'this stiffened wall is a nearby model, not the realized one'; (iii) the decoupling is an equilibrium statement (C9), though the tree's finite-amplitude extension survives (C10); (iv) under the causal proxy 'still-admissible' requires x < x* = 0.8437, strictly inside the 24/25 dec window (C7) -- the tree already restricts to x < 4/5 and records this (wall.py:554). Each of (i)-(iii) is named elsewhere in wall.py itself (lines 22, 119-128, 193-205), so the narrowing is of the sentence as used at 11-14 and 39-40, not a hidden error in the file. App. J (Le's derivation) and v4 Sec. 4 are unread; v4 no longer carries the clause in any cached page.",
"what_would_change_the_grade": "To STANDS: the tree's dependent sentence (wall.py:39-40) and the canonical entry carrying 'linearised radial mode, frozen background, static thin shell (lambda = 0)' as named hypotheses, with the 'nearby model' caveat restored -- i.e. use matching the class on which the clause is proved. To WRONG: a computed counterexample to the RADIAL statement -- a static barotropic Minkowski/Schwarzschild thin shell with beta^2 > beta^2_crit and V''(R0) <= 0, or a beta^2-dependence of sigma0 or p0 -- which C3-C5 exclude over all s in (0,1). To OPEN or a recorded DISCREPANCY: reading App. J of v2, or v4 pages 11-12, and finding that Le states the clause under hypotheses different from those re-derived here (e.g. a non-barotropic or finite-thickness law), or that v4 withdraws it with a stated reason.",
"reverify_command": "python3 -B " + D + "/rederive/le-2026-stiffer-wall-clause.py && sed -n 1512,1529p " + C + "2606.22531v3.txt && grep -c -i 'stiffer' " + C + "2606.22531v4.txt; python3 -B /home/user/Claude-Method-Works/research/warp-drive/wall.py --selftest | tail -1",
"report_path": D + "/audits/le-2026-stiffer-wall-clause.json"
}
json.dump(rep, open(rep["report_path"], "w"), indent=1, ensure_ascii=False)
print("written")
