import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "ftc-absolute-continuity",
 "name": "Fundamental theorem of calculus for the integration step (r^3 p_r absolutely continuous on (0, R] with a limit at 0)",
 "kind": "theorem",
 "source": {
  "located": "H. Lebesgue, Lecons sur l'integration (1904) and G. Vitali (1905) -- neither on arXiv. Read through: G. Banerjee, arXiv:2510.20843v2 (2025) pp.1-2, 5-6 (exact statement of Lebesgue's FTC for AC functions on [a,b], definition of AC on an interval, AC vs AC_loc on non-compact intervals; cites Folland, Real Analysis 3rd ed.); R. Affeldt & Z. Stone, arXiv:2403.18229v2 (ITP 2024) pp.1, 12-15 (first FTC for the Lebesgue integral machine-checked in Coq/MathComp-Analysis; the AC (second) FTC named as future work p.15).",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "Lebesgue 1904 / Vitali 1905 originals NAMED-NOT-READ; the theorem READ as restated verbatim in arXiv:2510.20843 p.5 and p.1, and its first-FTC half READ as formalized in arXiv:2403.18229 sec.10.1 (Lemma FTC1_lebesgue_pt, Corollary FTC1Ny). Rudin RCA Thm 7.21 (everywhere-differentiable F with F' in L^1) is NAMED-NOT-READ and used only as a pointer in T5."
 },
 "published_statement": "arXiv:2510.20843 p.5: 'Let f : [a,b] -> R be an absolutely continuous function. Then: 1. f is differentiable almost everywhere on [a,b], 2. its derivative f' is Lebesgue integrable on [a,b], and 3. for all x in [a,b], f(x) = f(a) + INT_a^x f'(t) dt. Conversely, if g in L^1([a,b]) and we define F(x) = INT_a^x g(t) dt, then F is absolutely continuous on [a,b], F' = g almost everywhere.' p.1: 'a function F defined on [a,b] is absolutely continuous if and only if F' exists almost everywhere, belongs to L^1([a,b]), and F(x) = F(a) + INT_a^x F'(t) dt.' p.2 Def 2.0.1: AC on an interval I = the eps-delta condition over finite disjoint subintervals OF I; p.2-3: 'A function may be absolutely continuous on every compact subinterval yet fail to be absolutely continuous globally', AC(I) strictly inside AC_loc(I). arXiv:2403.18229 p.13: 'for f in L^1, F(x) := INT_{]-oo,x]} f(t) dmu is differentiable and F'(x) = f(x) a.e.'",
 "published_hypotheses": [
  "compact interval [a,b] (2510.20843 p.5); on a non-compact interval only AC on each compact subinterval (AC_loc) is automatic, and AC_loc does not imply AC (p.2, Example 3.0.1)",
  "F absolutely continuous on [a,b] in the eps-delta sense of Def 2.0.1 (p.2)",
  "the conclusion is an identity of LEBESGUE integrals: F' exists a.e. and is in L^1([a,b]) (p.5)",
  "no hypothesis on the value of F at the endpoint; F(a) appears in the conclusion (p.5) -- the FTC does not set any boundary term to zero",
  "continuity + a.e. differentiability is NOT enough (the theorem is iff; Cantor function) -- 2510.20843 does not show the Cantor counterexample; it is re-derived here (T4)"
 ],
 "hypothesis_drift": [
  "DROPPED: 'the limit is ZERO'. tolman.py:935 words the hypothesis as 'r^3 p_r must be absolutely continuous on (0, R] with a limit at 0' and :935-936 says '\"Regular centre\" means exactly that'. The FTC with a limit L at 0 gives m(R) = 4 pi (R^3 p_r(R) - L) (T1); the conclusion m = 4 pi R^3 p_r at :933-934 needs L = 0. The tree's OWN independence_witness (tolman.py:1380-1386, V32 at :1937) satisfies the hypothesis exactly as worded -- r^3 p_r = A is constant, hence AC on (0,R], with limit A -- and the identity fails by -4 pi A (T2). The condition is NOT dropped elsewhere in the same file: :51 states the hypothesis as 'r^3 p_r -> 0', the master formula :281-286 carries C = 4 pi lim r^3 p_r explicitly, and the machine layer's FULL at :2055 imposes Cc == 0 before B1 (:2070) is discharged. The drift is confined to the citing sentence.",
  "OVERSTATED COMPARISON: tolman.py:936 '[regular centre] is STRONGER than \"p_r is finite at the centre\"'. As an implication it fails: the tree's own W3 (tolman.py:584, p_r = -2 + 10 r^(-5/2), labelled 'regular centre') has r^3 p_r -> 0 and p_r -> +oo (T3). The true half is the converse non-implication: finiteness does not suffice (Cantor witness, T4). The two conditions are INCOMPARABLE, not ordered. A wording discrepancy, not a refutation of anything the file computes.",
  "WEAKENED/AMBIGUOUS: 'absolutely continuous on (0, R]' (tolman.py:935) on a half-open interval. Read as AC in Def 2.0.1's sense on (0,R] itself, it implies uniform continuity, so the limit at 0 exists automatically ('with a limit at 0' is then redundant) and r^2 u is in L^1(0,R). Read as AC_loc (every compact subinterval), the FTC plus the limit gives the identity with m(R) as an IMPROPER integral lim_{eps->0} INT_eps^R, not necessarily a Lebesgue integral: r^3 p_r = r^2 sin(r^-2) is differentiable on (0,R] with limit 0 while INT |r^2 u| diverges logarithmically (T6). The tree does not say which reading; m is written INT_0^R r^2 u dr (:281-286 context). Where u is of one sign (the G2 route, :940-942) monotone convergence makes the two readings agree.",
  "ADDED (a hypothesis the tree may not need): if the ODE d/dr(r^3 p_r) = r^2 u holds at EVERY r in (0,R] (the tree's V2/V3 computes it for differentiable fields), F = m - 4 pi r^3 p_r has F' = 0 identically (T5) and is constant by the mean-value theorem with no absolute-continuity hypothesis; the same file's own device 'C IS A FIRST INTEGRAL, NOT A LIMIT' (:291-296) is exactly this route. AC is load-bearing only if the ODE is asked of an a.e.-solution (T4). Sufficient, not necessary; recorded, not a fault."
 ],
 "data_at_publication": [],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/ftc-absolute-continuity.py",
  "outcome": "ALL PASS, exit 0. T1 (sympy, undefined F): INT_eps^R r^2 u = F(R) - F(eps); with limit L the identity holds iff L = 0. T2: tree's V32 witness p_r = A/r^3 meets the hypothesis as worded at :935 and m = 0 while 4 pi R^3 p_r = 4 pi A. T3: tree's W3 is regular-centred with p_r -> +oo. T4: Cantor function c, p_r = c bounded, r^3 p_r -> 0, ODE holds a.e. with u = 3c; exact Cantor moments E[X^3] = 5/16 give m(1)/(4 pi) = 11/16 != 1 = p_r(1) (numeric midpoint sum 0.687500). T5: on shell dF/dr == 0 identically (MVT route). T6: r^2 sin(r^-2): signed integral converges to G(1) = 0.841471, absolute integral grows by 2.9335 per decade of eps against predicted (2/pi) ln 100 = 2.9317.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "R. Affeldt & Z. Stone, arXiv:2403.18229 (ITP 2024)", "effect": "confirms", "what": "First FTC for the Lebesgue integral machine-checked in Coq (MathComp-Analysis, ftc.v, ~265 loc); the AC (second) FTC is stated as future work (p.15), so this confirms the integral-to-derivative half, not the AC half the tree cites. Mathlib FTC variants requiring integrability/continuity mentioned p.13-14 (NAMED-NOT-READ).", "read_status": "READ (pp.1-5, 12-16)"},
  {"ref": "G. Banerjee, arXiv:2510.20843 (2025)", "effect": "narrows", "what": "On non-compact intervals AC_loc does not imply AC; AC(I) <=> AC_loc(I) and f' in L^1_G. Bears on the (0,R] reading in drift item 3. The same paper's p.5 statement of the Henstock-Kurzweil FTC ('if f' exists almost everywhere, then INT_a^b f' = f(b) - f(a)') is a DISCREPANCY in that restatement: the Cantor function is a counterexample (T4 computes the analogous failure); the standard HK form needs differentiability everywhere or off a countable set with continuity. Recorded, not quoted as an error in the journal version.", "read_status": "READ (pp.1-11)"},
  {"ref": "Henstock-Kurzweil integral (discover_papers: arXiv:2602.09151 survey; 2501.17118)", "effect": "extends", "what": "Every everywhere-derivative is HK-integrable with INT f' = f(b) - f(a), no absolute continuity needed; this is the route T5 takes and it removes the AC hypothesis for pointwise-differentiable fields.", "read_status": "NAMED-NOT-READ (titles/abstracts only)"}
 ],
 "lacked_data": "Not applicable in the data sense: the result is a theorem of real analysis (Lebesgue 1904, Vitali 1905) whose conclusion depends on no measured quantity, and the canonical entry lists data_used = []. Evidence either way: (for) the theorem is restated identically in a 2025 arXiv paper and its first-FTC half is machine-checked in Coq (2403.18229); the re-derivation here agrees on every checkable instance, including the exact Cantor-measure computation that shows why AC cannot be weakened to continuity. (against) nothing found. M's hypothesis ('previous physicists may have lacked certain data') does not bite on this result; what does bite is the tree's own wording of the hypothesis at the citing sentence (limit at 0 vs limit ZERO), which the tree's own V32 witness already exhibits.",
 "grade": "NARROWED",
 "grade_evidence": "The external theorem STANDS: read at source via restatement (2510.20843 p.5), first half machine-checked in Coq (2403.18229 sec.10.1), re-derived in sympy (T1), no datum. The result AS THE TREE USES IT at tolman.py:932-936 is stated on a larger class than it holds: 'absolutely continuous on (0, R] with a limit at 0' yields m(R) = 4 pi (R^3 p_r(R) - lim r^3 p_r), and m = 4 pi R^3 p_r requires the limit to be ZERO. Counterexample SHOWN (T2), and it is the tree's own independence_witness (V32). The narrowing is confined to the citing sentence: tolman.py:51, the master formula :281-286 and the z3 FULL hypothesis :2055 (Cc == 0) all carry the zero limit, so B1 (:2070), D8 and specthm:R2 do NOT move. Secondary discrepancies recorded, not refutations: 'STRONGER than p_r finite' at :936 is an incomparability (T3, T4); '(0, R]' leaves AC vs AC_loc (Lebesgue vs improper integral) unstated (T6).",
 "what_would_change_the_grade": "To STANDS: the citing sentence tolman.py:935 reading 'with limit ZERO at 0' (C = 0) or pointing at FULL's Cc == 0, and ':936 STRONGER' reading 'not implied by'. To WRONG: only a counterexample to m = 4 pi R^3 p_r under AC on [0,R] with r^3 p_r -> 0 -- impossible by T1 and the Lebesgue FTC. Nothing in this grade moves with data.",
 "reverify_command": "python3 " + D + "/rederive/ftc-absolute-continuity.py && sed -n 49,52p;281,296p;932,937p;1380,1386p;2055p /home/user/Claude-Method-Works/research/warp-drive/tolman.py",
 "report_path": D + "/audits/ftc-absolute-continuity.json"
}
rep["reverify_command"] = "python3 " + D + "/rederive/ftc-absolute-continuity.py && sed -n '49,52p;281,296p;932,937p;1380,1386p;2055p' /home/user/Claude-Method-Works/research/warp-drive/tolman.py"
json.dump(rep, open(D + "/audits/ftc-absolute-continuity.json", "w"), indent=1)
print("ok")
