import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "gr-qc/0209075#needs-solution",
 "name": "AMM linear response (3.4) is defined only about a solution of the semiclassical equations (2.9)",
 "source": {
  "located": "arXiv gr-qc/0209075 v1 (21 Sep 2002), Anderson, Molina-Paris, Mottola, 'Linear Response, Validity of Semi-Classical Gravity, and the Stability of Flat Space', PRD 67, 024026 (2003). Sec. II eq. (2.9) p. 7; Sec. III eqs. (3.1)-(3.11) pp. 8-10; Sec. V Discussion p. 13.",
  "read_status": "READ",
  "via": "arXiv v1 text layer obtained through alphaXiv get_paper_content(fullText) earlier in DOCKET 67 and banked at d67/amm_0209075.txt (5,015 lines, md5 486395c6c5ea8f9b16f0478d78a0f375); read in this stage at lines 840-1200 (eqs. 2.9-3.5), 1380-1640 (3.6-3.11, criterion, start of IV), 2320-2420 (Discussion). Page markers in the layer put the (3.3) sentence on p. 8 (page-8 marker at line 1263) and the 'leading order solution' sentence on p. 9 (marker at line 1613), matching the tree's page cites. In THIS stage all three alphaXiv tools returned 'quota exceeded' and arxiv.org is refused by the egress proxy (403), so no fresh fetch was possible; the banked layer is the source text itself, not a restatement. The layer drops ligatures 'fi'/'fl' and Greek letters; no quoted conclusion depends on a dropped glyph."
 },
 "published_statement": "p. 8: 'The linear response equation can be obtained by expanding the CTP effective action, in a functional Taylor series to one higher order, around a given semi-classical geometry g_ab that solves eq. (2.9). Writing g_ab -> g_ab + h_ab (3.2) one finds that to second order in h_ab the CTP effective action is S[g+h] = S[g] + int dS/dg^A h^A + 1/2 int int d^2S/dg^A dg^B h^A h^B + ... (3.3) where the first variation vanishes by (2.9). Varying with respect to h^1 and then setting h^1 = h^2 = h and g^1 = g^2 = g, gives the linear response equation which is equivalent to the first variation of the semi-classical Einstein equations, namely delta[ alpha (C)H_ab + beta (1)H_ab + (G_ab + Lambda g_ab)/(8 pi G_N) ] = delta<T_ab> = -(1/4) M_ab^cd h_cd(x) - (1/2) int d^4x' sqrt(-g(x')) Pi^(ret)cd_ab(x,x') h_cd(x') (3.4)'. p. 9: 'According to the general principles of linear response analysis, this retarded correlation function is evaluated in the background geometry of the leading order solution of the semi-classical equations (2.9).' p. 13 (Discussion): 'If, for a given state and background geometry that solves the semi-classical equations, one or more solutions to the linear response equations experience unbounded growth in a gauge invariant sense, then the semi-classical approximation is not valid for that particular geometry, at least not for that particular state.' AMM do not use the word 'only' and do not discuss linearisation about a non-solution.",
 "published_hypotheses": [
  "A1 (p. 8) a background geometry g_ab that SOLVES (2.9); (3.3) 'the first variation vanishes by (2.9)'",
  "A2 (p. 7) (2.9) is the equation 'for zero expectation value of the free scalar field', with <T_ab>_R the renormalised expectation value; large-N leading order (p. 7, 'large N semi-classical equations of motion (2.9)', p. 10)",
  "A3 (p. 7) renormalised parameters defined by removing, at an arbitrary but fixed scale mu, every term of the form of the local geometric tensors on the LHS of (2.9) from <T_ab> by explicit subtraction",
  "A4 (pp. 8-9) CTP (in-in) expectation values in the state |in>; Pi^(ret) = Pi^11 + Pi^12 (3.5), formally (3.9) = -(i/2) theta(t,t') <in|[T_ab(x),T_cd(x')]|in>; evaluated on the leading-order solution of (2.9)",
  "A5 (p. 9) the derivation is 'still formal': Pi^(ret) must be combined with the local contact term (1/4)M_ab^cd h_cd and renormalised by exactly the counterterms of (2.9), giving answers 'unique up to finite redefinitions of the coefficients alpha and beta'; carried out explicitly only in the flat-space example of Sec. IV",
  "A6 (pp. 9-10) gauge freedom (3.11) h -> h + nabla X + nabla X; singular gauge transformations in the initial data excluded; transformations under which (2.7) is not invariant (boundary terms) excluded",
  "A7 (p. 10, p. 13) the criterion built on (3.4) is a NECESSARY, 'perhaps not a sufficient', condition, and is stated per state and per geometry"
 ],
 "hypothesis_drift": [
  "ADDED by the tree (inference, not AMM's text): the word 'only' in the entry's name. linstab.py:52-57 itself says 'ABOUT A SOLUTION' and quotes AMM exactly (p. 8 and p. 9 cites verified against page markers); the 'only' is the tree's inference that off a solution the linearised equation carries a zeroth-order source, backed at linstab.py:57-60 by its toy witnesses W1, W2 (linstab.py:662-702). AMM never discuss off-solution linearisation. Re-derived here (C1): the stationarity equation of S[g+h] to O(h^2) is E(g) + K(g)h = 0, which is AMM's homogeneous form K h = 0 iff E(g) = 0 -- so 'only', read as 'only then is (3.4) the first variation of (2.9)', is COMPUTED, not declared. A further reason the tree does not state, computed here (C2): AMM's claim that (3.4) is 'non-unique up to' gauge transformations (3.11) (p. 9) itself requires H1, because E'[g](L_X g) = L_X E[g] for any diffeomorphism-covariant E; off a solution pure-gauge h fails the homogeneous equation. Checked for the Einstein + Lambda part of (2.9) only; for the full LHS minus <T>_R it holds if the state is assigned covariantly (named hypothesis, not checked here).",
  "NOT SPELLED OUT (no drift in substance): H2 at linstab.py:279 ('the in-state |in> ... in which (2.9) holds') does not state AMM's p. 7 proviso that (2.9) is written 'for zero expectation value of the free scalar field'. Because H2 names (2.9) by number, the proviso is inherited; a state with <Phi> != 0 would add a classical stress tensor and is simply outside (2.9) as printed. The tree's verdict (NOT EVALUABLE) is unaffected.",
  "UNDERSTATED requirement (the tree lists LESS than AMM require, which makes its refusal stricter, not weaker): linstab.py:72-76 ('THE MISSING QUANTITY, EXACTLY: ... THEN the retarded polarization tensor Pi^(ret) (AMM (3.5), (3.9))'), H3 at linstab.py:280 and SEMICLASSICAL_MISSING at linstab.py:338-340 name Pi^(ret) alone. AMM p. 9 (A5): (3.9) is formal; the object that enters (3.4) is the renormalised combination of Pi^(ret) with the contact term M_ab^cd, defined up to finite redefinitions of alpha, beta, and AMM construct it only in flat space. 'EXACTLY' is therefore incomplete: the missing quantity is the covariantly renormalised (M/4 + Pi^(ret)) in omega on the configuration. A discrepancy of completeness, recorded not repaired; it adds to what is missing and moves no verdict.",
  "NOT CARRIED (bears on the criterion, not on this entry): AMM p. 9 exclude singular gauge transformations in the initial data; H5 at linstab.py:282 carries (3.11) and the (2.7) rule but not this exclusion.",
  "NONE on H1, H4: H1 (linstab.py:278) matches A1 verbatim in substance; H4 (linstab.py:281, 'fixed by a stated condition') matches A3."
 ],
 "data_at_publication": [
  {
   "quantity": "numerical inputs to 'the linear response (3.4) is the first variation of (2.9) about a solution of (2.9)'",
   "value_then": "none -- the statement is structural (functional Taylor expansion of an action about a stationary point); no measured constant enters",
   "value_now": "none",
   "source_now": "n/a (canonical data_used = [])",
   "moves_conclusion": "no -- C1 and C2 hold identically in every symbol (generic action coefficients; M, c, Lambda, x(r))"
  }
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/gr-qc_0209075_needs-solution.py",
  "outcome": "13/13 PASS (output banked at rederive/gr-qc_0209075_needs-solution.out, ~34 s). C1: for a generic two-variable quartic action, d/dh[S(q0+h) to O(h^2)] = E(q0) + K(q0)h identically, and d/deps E(q0+eps h)|0 = K(q0)h -- so the homogeneous equation K h = 0 (AMM's (3.4) form) is the first variation of E = 0 iff E(q0) = 0; E(1,0) != 0 exhibits the zeroth-order source. C2: with E_ab = G_ab + Lambda g_ab on g = diag(-f, 1/f, r^2, r^2 sin^2) with f = 1 - 2M/r - c r and X = x(r) d_r, the identity E'[g](L_X g) = L_X E[g] holds for all M, c, Lambda, x; at c = 0, Lambda = 0 (Schwarzschild, a solution) pure gauge solves the linearised equation; at c = 1, M = 0, x = r it does not (nonzero tt, rr, theta-theta, phi-phi components: -2/r, -2/(r (r-1)^2), -r, -r sin^2). So AMM's gauge freedom (3.11) of (3.4) presupposes H1. C3/C4: the tree's W1 (logistic from 1/2: true flow bounded, residual-kept linearisation d = t/4 unbounded) and W2 (x' = 1/(1+x^2) from 1: true flow unbounded, t = x + x^3/3 - 4/3; both linearised verdicts bounded) re-derived from scratch, with equilibrium controls agreeing. Scope named: W1/W2 are 1-D ODE toys showing an off-equilibrium linearised verdict is not a property of the dynamics in general; they are not a computation on AMM's (3.4).",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {
   "ref": "arXiv:2604.01047 v1 (Galanda, Meda, Murro, Pinamonti, Schmid 2026, GMMPS)",
   "effect": "confirms",
   "what": "Rigorous treatment of the same system (one massive KG field) linearised about (R^4, eta) with the Poincare vacuum, a background fixed to solve the semiclassical equations (alpha_1, 'plays the role of a cosmological constant', fixed by the background, p. 22 as quoted in the sibling audit). Confirms the practice of linearising only about a semiclassical solution; it makes no statement about off-solution linearisation, and it contests AMM's renormalisation condition, which is a different entry (gr-qc/0209075#renorm-4.4).",
   "read_status": "NOT re-read in this stage (alphaXiv quota exceeded); READ at alphaXiv in the tree (linstab.py GMMPS_READ, sections 1-5, appendices A, B) and in sibling audits d67/audits/2604.01047_*.json and gr-qc_0209075_renorm-4.4.json"
  },
  {
   "ref": "arXiv:2512.00503 v2 (Ishibashi, Maeda, Okamura 2025)",
   "effect": "confirms",
   "what": "Holographic semiclassical gravity; perturbs Minkowski and de Sitter backgrounds that solve the semiclassical equations, citing AMM as ref. [9]. Consistent with linearising about a solution; no statement on non-solutions was read.",
   "read_status": "NOT re-read in this stage; READ at alphaXiv in sibling audits gr-qc_0209075_renorm-4.4.json and gr-qc_0209075_flat-scalar-and-conclusion.json"
  },
  {
   "ref": "discover_papers search for work narrowing or contradicting the requirement",
   "effect": "contested",
   "what": "NOT RUN: the single discover_papers call returned 'alphaXiv assistant quota exceeded'. 'contested' is the nearest enum value to UNKNOWN and records no dispute. No later work contradicting the requirement is known here; none was searched for in this stage.",
   "read_status": "NOT-RUN (quota)"
  }
 ],
 "lacked_data": "M's hypothesis tested: none of the content of this result depends on data. It is a structural statement about perturbation theory -- the functional Taylor expansion of an action about a stationary point -- and C1/C2 hold identically in every symbol, so no later measurement (G_N, Lambda_obs, particle masses, the value of the renormalised alpha, beta) can move it. What AMM lacked in 2002 was not data but a construction: the covariantly renormalised Pi^(ret) on a curved, non-flat solution (they do it only in flat space, and say so, p. 9) and self-consistent solutions of (2.9) to apply it to (they list de Sitter, thermal Einstein-de Sitter and Hartle-Hawking black holes as future applications, p. 13). Evidence either way: the later rigorous work read in the tree (GMMPS 2604.01047) keeps the requirement -- it linearises about a background fixed to solve the equations -- and changes AMM's renormalisation CONDITION instead, which is a separate entry. Having more data does not change this conclusion.",
 "grade": "STANDS",
 "grade_evidence": "READ at source: AMM p. 8 expand 'around a given semi-classical geometry g_ab that solves eq. (2.9)' and '(3.3) where the first variation vanishes by (2.9)'; p. 9 Pi^(ret) 'is evaluated in the background geometry of the leading order solution of the semi-classical equations (2.9)'; p. 13 'for a given state and background geometry that solves the semi-classical equations'. The tree quotes both sentences correctly with correct page numbers (linstab.py:52-57, 273-276). The one word the source does not contain, 'only', is computed here (C1: off a solution the stationarity equation carries the zeroth-order source E(g); C2: the gauge freedom (3.11) AMM ascribe to (3.4) holds only when E(g) = 0 -- shown on an explicit non-solution). Hypotheses H1-H5 match A1, A3, A4, A6; the unspelled <Phi> = 0 proviso is inherited through '(2.9)'. No numerical datum enters. Why not NARROWED: the tree uses this result only to REFUSE (SEMICLASSICAL_EVALUABLE_ON_DEMAND = False, 'not a proof that none is one'); it applies the result to no class larger than AMM's, and the one incompleteness found -- linstab.py:72-76, 338-340 naming Pi^(ret) without AMM's contact term M and the covariant renormalisation of p. 9 -- understates what is missing, which makes the refusal stricter, not weaker. That incompleteness is a recorded DISCREPANCY in the tree's word 'EXACTLY', not a narrowing of AMM's result.",
 "what_would_change_the_grade": "To NARROWED: if the tree applied (3.4) or the AMM criterion to a background it DOES treat as a solution but one that fails A2 (e.g. <Phi> != 0, or a state not assigned covariantly so that C2's identity fails for <T>_R) -- not found in linstab.py at the lines cited. To OPEN/contested: a later paper defining a gauge-invariant linear response about a non-solution of the semiclassical equations (e.g. with the residual treated as a source and a separate boundedness criterion) that the tree's refusal would have to answer; the discover_papers search that could find one was not run (quota) and should be run when alphaXiv resets. The tree's 'EXACTLY' at linstab.py:72 would be accurate if it added AMM's contact term M and the covariant renormalisation (AMM p. 9) to SEMICLASSICAL_MISSING; that is a wording discrepancy, not a grade change.",
 "reverify_command": "python3 " + D + "/rederive/gr-qc_0209075_needs-solution.py && grep -n 'rstvariation vanishesby\\|leading order solution ofthe\\|solves eq.(2.9)\\|background geometry thatsolvesthe' " + D + "/amm_0209075.txt ; tr -s '\\n' ' ' < " + D + "/amm_0209075.txt | grep -o 'around a given sem i-classical geom etry g ab that solves eq.(2.9)' ; sed -n 52,76p /home/user/Claude-Method-Works/research/warp-drive/linstab.py; sed -n 273,287p /home/user/Claude-Method-Works/research/warp-drive/linstab.py; sed -n 334,340p /home/user/Claude-Method-Works/research/warp-drive/linstab.py",
 "report_path": D + "/audits/gr-qc_0209075_needs-solution.json"
}
json.dump(rep, open(D + "/audits/gr-qc_0209075_needs-solution.json", "w"), indent=1)
print("ok")
