import json
D = '/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67'
rep = {
"key": "2309.10848-thmiv.1",
"name": "Fliss-Freivogel-Kontou-Pardo Santos Thm IV.1, eq. (72): curved-spacetime worldvolume null QEI, state-dependent, any xi",
"source": {
 "located": "J.R. Fliss, B. Freivogel, E.-A. Kontou, D. Pardo Santos, 'Non-minimal coupling, negative null energy, and effective field theory', arXiv:2309.10848v1 (dated 21 Sep 2023; SciPost Phys. 16 (2024) 119 per a later citer, NOT read). Sec. IV.A eqs. (54)-(59) (src lines 2340-2660); Sec. IV.B eqs. (60)-(74) incl. the small sampling domain (66), (69b), (70), Theorem IV.1 / eq. (72) and the 'any value of the coupling constant' sentence (src lines 2670-3080); Sec. II.A eqs. (7)-(16) for the stress tensor (src lines 425-735). FFKP ref. [20] Fewster & Smith gr-qc/0702056v3 Sec. 3.1, definition of a small sampling domain and Theorem 3.1 (src/0702056.pages.txt lines 1585-1780, pp.17-18).",
 "read_status": "READ",
 "via": "The v1 full text as returned earlier in this DOCKET 67 workflow by alphaXiv get_paper_content(fullText=true), cached at scratchpad/d67/src/2309.10848.txt (84,715 bytes, md5 4f31876842f625e48506444afd216ee0, re-verified this stage); every quotation here was read from that file this stage. Fresh alphaXiv calls in THIS stage (answer_pdf_queries, get_paper_content, discover_papers) were all refused 'alphaXiv assistant quota exceeded', and arxiv.org is refused by the egress proxy (403), so the PDF itself could not be re-read: equation coefficients are as the alphaXiv text layer extracted them. Fewster-Smith read from the cached extraction src/0702056.pages.txt. Only v1 read; per the tree's fluctuation.py precedent, the discrepancy below is not to be quoted against the SciPost version until it is read."
},
"published_statement": "Theorem IV.1 (src lines 3003-3040): 'Let f be any real-valued test function compactly supported in a small sampling domain. Let l^mu be a null vector field defined in the neighbourhood of support of f. Then, for all Hadamard states psi, <:rho_n:(f^2)>_psi >= -2 INT_D d^n alpha/(2 pi)^n ((Q x Q) W_0)_kappa(fbar_alpha, f_alpha) - xi <:phi^2:(Q[f])>_psi, (72) where W_0 is the two-point function of the reference Hadamard state psi_0 and Q = l^mu nabla_mu.' With (69b) Q[f] = nabla_mu nabla_nu (l^mu l^nu f^2) + (1/2) R_mn l^m l^n f^2, (71) f_alpha(x) = e^{i alpha x} f(x), and (65) <:rho_n:(f)>_psi = <rho_n(f)>_psi - <rho_n(f)>_psi0. Following text: 'unlike those two inequalities [FO, FK], the QEI derived holds for any value of the coupling constant xi'; 'the bound of Eq. (72) is a non-trivial bound'; 'as this bound is derived by discarding positive terms we do not expect it to be optimal.' Sec. IV opening: 'the derivation is for a difference QEIs unlike the absolute one that was possible for the minimally coupled field ... the strongest bound we will be able to derive is state-dependent'.",
"published_hypotheses": [
 "H1 (Sec. IV.A, src 2343-2349): the free massive non-minimally coupled real scalar, V = m^2 phi^2/2, field equation (10) (box + m^2 + xi R) phi = 0, quantised as the algebra A(M) 'on our globally hyperbolic, time-oriented manifold M' (n dimensions).",
 "H2 (Thm IV.1 + (66), after Fewster-Smith [20]): f real-valued, compactly supported in a SMALL SAMPLING DOMAIN Sigma: an open subset of (M,g) contained in a globally hyperbolic convex normal neighbourhood of M and covered by a single hyperbolic chart: d/dx^0 future-pointing timelike and a constant c > 0 with c|u_0| >= sqrt(sum_{j=0}^{n-1} u_j^2) for every causal covector u on Sigma (bounded coordinate speed of light).",
 "H3: l^mu a null vector field defined in a neighbourhood of supp f (Fewster-Smith Thm 3.1, which (70) invokes, requires Q = l.nabla to have SMOOTH REAL coefficients in a neighbourhood of Sigma).",
 "H4: psi any Hadamard state.",
 "H5: psi_0 a reference Hadamard state with two-point function W_0 (difference QEI: left side normal-ordered relative to psi_0, eqs. (59), (65)); <:phi^2:> on the right is also relative to psi_0.",
 "H6 (scope, not a hypothesis): any real xi; no smallness of Sigma relative to a curvature or Planck scale is assumed by the theorem; the bound is not claimed optimal."
],
"hypothesis_drift": [
 "FAITHFUL (formula, as printed), qeihps.py:94-100: eq. (72), Q = l^mu nabla_mu and Q[f] (69b) including its '+ (1/2) R_mn l^m l^n f^2' are copied exactly as the v1 text layer prints them; FFKP_XI_RANGE = None (qeihps.py:385) matches 'any value of the coupling constant xi'; QEI_KIND difference (qeihps.py:394) matches Sec. IV opening and (65). But see the DISCREPANCY entry: the printed curvature coefficient is not the one the paper's own (9) yields, so the tree has inherited it.",
 "WEAKENED (global hyperbolicity of M), qeihps.py:98-103 and hypothesis_table row qeihps.py:436-439 (verdict 'MET LOCALLY' computed from f(0) > 0, r(0) > 0 only): the source quantises on a globally hyperbolic, time-oriented M (H1); the tree evaluates only the LOCAL condition (a globally hyperbolic convex normal neighbourhood exists). HPS's M is not established globally hyperbolic in the tree (HPS print Taylor data (9) and figures only; TAYLOR_RADIUS_OF_CONVERGENCE_PROVED = False, qeihps.py:339). Benign for the in-form claim: restricting to a globally hyperbolic neighbourhood N as a spacetime in its own right, with psi restricted to N, is the standard localisation -- NAMED here, not proved -- and the tree's verdict is OPEN either way.",
 "DROPPED (time orientation, H1), qeihps.py:98-103: not listed. MET at the throat, computed here: F(0) = e^{-2/3} = 0.513417 > 0 so d_t is timelike and time-orients the static region (rederive E1).",
 "UNCHECKED -> now COMPUTED (hyperbolic chart, (66)), qeihps.py:99-100 ('one hyperbolic chart') and 436-439: the tree names the chart but checks neither d/dx^0 future timelike nor the speed-of-light bound. Computed here in the chart (t,l,theta,phi) away from the poles: c^2 = 1 + (1 + r^2 + r^2 sin^2 theta)/F; at the throat c = 1.717565 (theta = pi/2), with 10,499 random causal covectors none violating (66) (rederive E3-E4). The tree's 'Whitehead NAMED' is also upgraded: Fewster & Smith p.18 (READ, src/0702056.pages.txt ~1600-1640) state 'every point of a general timelike submanifold Sigma has a neighbourhood (in Sigma) which is a small sampling domain'. MET LOCALLY stands.",
 "IMPLICIT (free field, H1), qeihps.py:94-117: not named. HPS's field is a free conformally coupled massless scalar (HPS_XI = 1/6, m = 0, qeihps.py:325-326) -- MET; the theorem is a fixed-background QFT statement, so HPS's semiclassical self-consistency (metric sourced by the AHS <T>) is outside it, as the tree's NOT-ESTABLISHED Hadamard row already records.",
 "IMPLICIT (smooth real l, H3), qeihps.py:102-104: the radial l = f^{-1/2} d_t + d_l is smooth and real wherever f > 0 -- MET; g(l,l) = 0 re-derived (rederive C1).",
 "FAITHFUL (evaluation inputs), qeihps.py:105-110, 216-224: W_0 of a reference Hadamard state on HPS and <:phi^2:> in the state are correctly classed as INPUTS needed to evaluate (72), not hypotheses of form; the source's (72) indeed needs both. Minor: the tree cites eq. (59) (the :T_mn: definition) where (65) is the :rho_n: one; same content.",
 "ADDED (caveat, not a hypothesis), qeihps.py:113-117: 'the convex normal neighbourhood about the throat is set by a curvature radius of 0.0243 l_P'. The theorem imposes no scale; the tree correctly labels this a CAVEAT. That the Lorentzian convex-normal-neighbourhood size is set by the curvature radius is a heuristic -- no Lorentzian convexity-radius bound is named or computed in the tree.",
 "NOT EXAMINED -> now examined (self-reference instance psi_0 = psi), qeihps.py:111-112: with psi_0 = psi the left side and <:phi^2:> vanish and (72) reads 0 >= -2 INT_D ((Q x Q)W_0)_kappa(fbar_alpha, f_alpha); the integrand is W_0(Q^t fbar_alpha, Q^t f_alpha) = omega_0(A* A) >= 0 by positivity of the state (Q real), so the instance is TRUE FOR EVERY BACKGROUND AND VACUOUS -- the same shape as the tree's FO instance; numerically confirmed nonnegative in 1+1 Minkowski with a massive W_0 at 12 alpha (rederive F1). 'Blocked the same way as FO Thm 4.2' is thereby confirmed rather than only asserted."
],
"data_at_publication": [
 {"quantity": "measured physical inputs to Thm IV.1", "value_then": "none -- the theorem is an exact inequality in algebraic QFT on a fixed background; no constant or measurement enters", "value_now": "none", "source_now": "n/a", "moves_conclusion": "no -- nothing to move"},
 {"quantity": "tree-side input: f(0) = e^{ln f(0)} at HPS's plotted solution ln f(0) = -2/3 (HPS gr-qc/9701064)", "value_then": "0.513417 (qeihps.THROAT_F0)", "value_now": "0.513417 (recomputed)", "source_now": "HPS boundary data (9) as the tree reads it; a chosen solution parameter, not a measurement", "moves_conclusion": "no -- only its sign (> 0) enters the MET LOCALLY / time-orientation verdicts"},
 {"quantity": "tree-side input: throat radius r(0) = sqrt(-16 K^2 ln f(0)), K^2 = 1/(5760 pi) (one-loop AHS coefficient)", "value_then": "0.0242789 l_P (qeihps.CURVATURE_RADIUS_LP)", "value_now": "0.0242789 l_P (recomputed; agrees with qeihps.throat() to 1e-12)", "source_now": "HPS / AHS coefficient; a pure number in Planck units", "moves_conclusion": "no -- enters the theorem only through r(0) > 0 and the caveat; the Planck length's SI value (CODATA) does not enter"},
 {"quantity": "tree-side input: R_ll at and near the throat (radial null l)", "value_then": "not computed in the tree for this theorem", "value_now": "R_ll = F'r'/(F r) - 2 r''/r = 0 at l = 0 under data (9); R_ll = nec2 l^2 + O(l^3), nec2 = 129600 pi^2 (L^2 - 2)/(L^2 (3L + 4)) = -2.23843e6 l_P^-4 at L = -2/3 (from qeihps.throat())", "source_now": "computed here (rederive D1-D3)", "moves_conclusion": "no for the tree's OPEN verdict; yes for any future EVALUATION of (72) on HPS, because R_ll != 0 on every open supp f makes the curvature coefficient of Q[f] (see discrepancy) load-bearing"}
],
"rederivation": {
 "method": "sympy",
 "script_path": D + "/rederive/2309.10848-thmiv.1.py",
 "outcome": "REDERIVE PASS (all 20 checks; output saved to rederive/2309.10848-thmiv.1.out). A (any xi): with the Leibniz step (62)-(63), the (l.grad phi)^2 coefficient of rho_n(f) is 1 identically in xi under every reading, so all xi-dependence sits in the phi^2 term -- 'holds for any value of the coupling constant' re-derived. C3: the distributional step (63) is an exact covariant divergence on the HPS metric form -F dt^2 + dl^2 + r^2 dOmega^2 (sympy, generic F, r, Phi, f); C2: G_ll = R_ll for null l. B (DISCREPANCY, v1 as extracted): the coefficient k of R_ll f^2 in Q[f] = nabla nabla(l l f^2) + k R_ll f^2 comes out k = -1 from the paper's own (9) (T contains +xi G_mn phi^2 -- forced by the paper's own (15)/(16) denominator 1 - 8 pi G xi phi^2, B0, and matching Fliss 2026 eq. (1.40)); k = +1 from (13) as extracted (-2 xi[... + (1/2) R_ll phi^2]); k = +2 from (61) as extracted (-2 xi[... + phi^2 R_ll]); the printed (64)/(69b) have k = +1/2. The step (61)->(64) is convention-free algebra and still does not give 1/2. On coherent states (W_psi - W_0 = Phi x Phi) the printed (72) would be equivalent to the classical claim INT f^2 (l.grad Phi)^2 >= -(3/2) xi INT R_ll f^2 Phi^2 for every solution Phi, which the proof does not establish; with Q[f] re-derived (k = -1) the theorem's proof goes through. Where R_ll = 0 on supp f (e.g. Minkowski, where FFKP then work) all readings coincide. D: R_ll = 0 exactly at the HPS throat (data (9)) but -2.23843e6 l^2 l_P^-4 off it, so on HPS the coefficient is load-bearing. E: (66) holds at the throat with c = 1.717565; F(0) > 0; g(l,l) = 0. F: the psi_0 = psi instance is vacuous (integrand >= 0, min 9.3e-14 at 12 sampled alpha in 1+1 Minkowski). Not checkable here: the positivity bound (70) itself (FFKP cite [7] Fewster-Kontou 1809.05047 and [20] Fewster-Smith for it; FS Thm 3.1 is the ABSOLUTE version with |h_kappa|^{1/4} density weights that FFKP's (70) notation suppresses -- notation, not claimed as an error); the difference version in [7] was NOT read.",
 "agrees_with_source": "partly"
},
"later_literature": [
 {"ref": "discover_papers (this stage)", "effect": "contested", "what": "The one allowed discover_papers call was REFUSED ('alphaXiv assistant quota exceeded'); arxiv.org is refused by the egress proxy (403). No later-literature search completed in this stage; nothing is claimed from absence.", "read_status": "NOT RUN (quota / proxy refusal)"},
 {"ref": "DOCKET 67 stage 2309.10848 (same paper): discover_papers 2023-09 onward on NMC / SNEC / QEI", "effect": "confirms", "what": "Returned no paper that narrows, contradicts or supersedes FFKP (hits 2606.08003, 2512.04934, 2601.18860, 2510.26247, 2608.01814, 2608.11817). One search, titles only: NOT-FOUND, not confirmation of Thm IV.1.", "read_status": "search results only, carried from audits/2309.10848.json"},
 {"ref": "J.R. Fliss, 'Modave lectures on energy conditions in quantum field theory and semi-classical gravity', arXiv:2605.18964v1 (May 2026)", "effect": "confirms", "what": "An FFKP author restates the NMC stress tensor as T_mn = d phi d phi - g(...) - xi(g nabla^2 + nabla_m nabla_n - G_mn) phi^2 (eq. 1.40) and T^eff with denominator 1 - 8 pi G xi phi^2 (1.43): the +xi G_mn phi^2 sign of FFKP's (9), i.e. T_ll contains +xi R_ll phi^2 and Q[f]'s curvature coefficient is -1, not the printed +1/2. The lectures restate only the flat DSNEC of [9] (FFKP) and the 'sensible EFT for small <:phi^2:>' reading; they do NOT restate the curved Thm IV.1, so they neither confirm nor correct (69b) directly.", "read_status": "READ from the cached extraction scratchpad/d67/src/casmag/all/2605.18964v1.txt lines 943-1080, 2470-2500, 2595-2610 (produced by an earlier DOCKET 67 stage; not re-fetched)"},
 {"ref": "C.J. Fewster & C.J. Smith, 'Absolute quantum energy inequalities in curved spacetime', gr-qc/0702056 (AHP 9 (2008) 425) -- FFKP ref. [20], PRE-dates FFKP", "effect": "confirms", "what": "Origin of the small-sampling-domain machinery: definition (i)-(ii) and (62) = FFKP (66) verbatim in content; Thm 3.1 requires Q of order <= 1 with smooth real coefficients; p.18 'every point of a general timelike submanifold Sigma has a neighbourhood which is a small sampling domain' -- which supports the tree's MET LOCALLY at source.", "read_status": "READ (cached extraction src/0702056.pages.txt lines 1585-1780)"},
 {"ref": "C.J. Fewster & E.-A. Kontou, 'Quantum strong energy inequalities', PRD 99 (2019) 045001, arXiv:1809.05047 -- FFKP ref. [7]", "effect": "extends", "what": "Cited by FFKP with [20] for the difference bound (70); the analogous state-dependent QEI for the effective energy density. Not read in this stage.", "read_status": "NAMED-NOT-READ"},
 {"ref": "Fliss, Freivogel, Kontou & Pardo Santos, arXiv:2412.10618 (SciPost Phys. 19, 087 (2025))", "effect": "extends", "what": "Same authors' follow-up on null energy in large-N CFTs; per the Fliss 2026 lectures an indication that particle-piling can fail in interacting large-N CFTs -- not a statement about the free-field Thm IV.1. Not read.", "read_status": "NAMED-NOT-READ"}
],
"lacked_data": "M's hypothesis tested for this result: Thm IV.1 is a data-free structural inequality of algebraic QFT on a fixed globally hyperbolic background; no measured number enters it, so there is no datum the authors (2023) lacked that could move it -- evidence: the statement and its proof (Leibniz step + the positivity bound (70)) contain no constant beyond xi, which is free ('any value'). What IS missing is on the application side, and it is data about HPS, not about the theorem: (i) a reference Hadamard two-point function W_0 on HPS, (ii) <:phi^2:> in HPS's state, (iii) an established Hadamard state (HPS use the AHS approximation). None is in print (the tree's two alphaXiv searches, qeihps.py:216-224; not re-searched here -- quota). Having them would not change the theorem; it would make the tree's test EVALUABLE, and then the curvature coefficient of Q[f] would matter, because R_ll != 0 on every open neighbourhood of the throat (nec2 = -2.23843e6 l_P^-4). The one defect found is not a data gap: it is an internal coefficient discrepancy in the v1 text between (9)/(15) and (13)/(61)/(64)/(69b), recorded as a discrepancy, not an error, until the PDF and the SciPost version are read.",
"grade": "NARROWED",
"grade_evidence": "READ at source (v1 text, cached alphaXiv extraction, md5 verified). The tree quotes (72), (69b), Q and 'any xi' exactly as printed and classes W_0 and <:phi^2:> correctly as evaluation inputs, and its verdict -- applies in form, NOT EVALUABLE, OPEN -- is untouched by anything found here. But the result holds on a smaller class than the formula the tree carries: (1) the printed eq. (72) is supported by the source's own derivation only where R_ll vanishes on supp f; the paper's own (9), confirmed by its (15)/(16) denominator and by Fliss 2026 eq. (1.40), gives Q[f] = nabla nabla(l l f^2) - R_ll f^2, whereas (69b) prints + (1/2) R_ll f^2 and the intermediate (13) and (61) as extracted imply +1 and +2 (sympy, rederive B0-B3; the step (61)->(64) does not give 1/2 in any convention). On coherent states the printed form would need an unproved classical inequality; with Q[f] re-derived, the theorem's proof goes through and 'any xi' is re-derived (A). On HPS R_ll = 0 at the throat but -2.23843e6 l^2 l_P^-4 beside it, so the coefficient is load-bearing on any open supp f (D). This is a DISCREPANCY in the v1 text layer (PDF not re-read, SciPost version not read), NOT a refutation: no counterexample to FFKP is shown, and it MUST NOT be quoted as an error in the journal version until that is read. (2) Hypothesis drift: the tree evaluates global hyperbolicity of M only locally (benign by standard localisation, NAMED) and omits time orientation and the chart condition (66) -- both now computed MET at the throat (E1, E3-E4), and MET LOCALLY is supported at source by Fewster-Smith p.18. (3) The psi_0 = psi instance the tree left unexamined is vacuous (F1), confirming 'blocked the same way as FO'. Not WRONG (nothing refuted is shown); not DATA-DEPENDENT (no datum enters); not OPEN (the statement was read and its finite algebra checked).",
"what_would_change_the_grade": "To STANDS: the PDF of v1 or the SciPost Phys. 16 (2024) 119 version shows a curvature coefficient in (69b) consistent with its (9) (i.e. the discrepancy is an extraction artefact or was corrected), and the tree either adopts that coefficient or notes it; the tree names global hyperbolicity as local-only. To WRONG: a constructed coherent state on a background with xi R_ll of the relevant sign on supp f for which the PRINTED (72) fails -- not constructed here, and it would refute only the misprinted form, not the corrected theorem. To OPEN: if the cached v1 extraction were shown not to be FFKP's text. The tree's OPEN verdict on HPS would change only if W_0, <:phi^2:> and a Hadamard HPS state were supplied.",
"reverify_command": "md5sum " + D + "/src/2309.10848.txt && python3 " + D + "/rederive/2309.10848-thmiv.1.py && sed -n 2995,3055p " + D + "/src/2309.10848.txt | tr '\\n' ' ' && echo && for n in 540 603 643 701 2708 2802 2968; do sed -n \"$((n-14)),${n}p\" " + D + "/src/2309.10848.txt | tr '\\n' ' ' | cat -v; echo; done && sed -n 94,117p /home/user/Claude-Method-Works/research/warp-drive/qeihps.py",
"report_path": D + "/audits/2309.10848-thmiv.1.json"
}
json.dump(rep, open(rep['report_path'], 'w'), indent=1, ensure_ascii=False)
print('written', rep['report_path'])
