import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
SRC=D+"/src/casmag/all/gr-qc_9510071v1.txt"
r={
"key":"ford-roman-sampling-practice",
"name":"Ford & Roman's practice of sampling at a hundredth of the geometric scale",
"source":{
 "located":"L.H. Ford & T.A. Roman, 'Quantum field theory constrains traversable wormhole geometries', arXiv:gr-qc/9510071v1 (31 Oct 1995, TUTP-95-4), journal Phys. Rev. D 53, 5496 (1996). The practice is at: Sec. 4.1 eqs (50)-(51) p.12 ('tau_0 = f r_m = f r_0 << r_c, with f << 1 ... For example, for f ~= 0.01, r_0 <~ 10^4 l_p'); the subsection after 4.2, eq (69) p.16 ('A reasonable choice of f is f ~= 0.01'; the '4.3' heading is missing from the text layer); Sec. 5.1 pp.20-21 ('for f ~= 0.01' three times); the COUNTER-EXAMPLE is Sec. 4.5 eq (88) p.19 ('A reasonable choice of f in this case would seem to be f ~= 0.1'). Cross-read: Pfenning & Ford gr-qc/9702026 eqs (20)-(23), as restated identically in Pfenning's thesis gr-qc/9805037 ch.5 eqs (5.20)-(5.23): 't_0 = alpha 2Delta/(sqrt3 v_b), 0 < alpha << 1 ... as an example, if we let alpha = 1/10'.",
 "read_status":"READ",
 "via":"Full arXiv v1 text layer held locally at "+SRC+" (md5 ad04d0ad4274a7a06f2c62502d08c3e6; header 'arXiv:gr-qc/9510071v1 31 Oct 1995'), fetched earlier in this session; every passage above read verbatim from it. In THIS stage alphaXiv returned 'quota exceeded' on answer_pdf_queries, get_paper_content and discover_papers, and arxiv.org is egress-blocked (403, WebFetch EGRESS_BLOCKED), so the text was not re-fetched; it agrees verbatim with the sibling audit audits/gr-qc_9510071.json's independently fetched Sec. 4.5 quote (f ~ 0.1). Journal version PRD 53, 5496 NAMED-NOT-READ. Pfenning-Ford gr-qc/9702026 READ-VIA-RESTATEMENT here (cached thesis gr-qc/9805037 pp.75-78, src/_cache_gr-qc_9805037.txt); the sibling audit audits/gr-qc_9702026.json read 9702026 itself and records the same eqs (22)-(23)."
},
"published_statement":"gr-qc/9510071 abstract: 'When spacetime is curved and/or has boundaries, we argue that the bound should hold in regions small compared to the minimum local characteristic radius of curvature or the distance to any boundaries, since spacetime can be considered approximately Minkowski on these scales.' Sec. 4.1: 'Choose our sampling time to be: tau_0 = f r_m = f r_0 << r_c, with f << 1. Substitution into Eq. (50) yields r_0 <~ l_p/(2f^2), (51) ... Here it is fairly obvious that any reasonable choice of f gives a value of r_0 which is not much larger than l_p. For example, for f ~= 0.01, r_0 <~ 10^4 l_p = 10^-31 m.' p.16: 'We then choose our sampling time to be: tau_0 = f a_0, where f << 1. Equation (68) then yields a_0 <~ (r_0/(8 f^4 l_p))^(1/3) l_p. (69) A reasonable choice of f is f ~= 0.01.' Sec. 5: 'Let r_m be the smallest of the length scales: r0-bar, r_1, R_2, r_3 ... the smallest proper radius of curvature ... is r_c ~= 1/sqrt(R_max) >~ r_m' and 'tau_0 = f r_m << r_c, with f << 1' with examples 'for f ~= 0.01'. Sec. 4.5 (MTY Casimir plates): 'Take tau_0 = f s ... A reasonable choice of f in this case would seem to be f ~= 0.1.' Pfenning-Ford (9702026 eq 23 / thesis 5.23): 'Now as an example, if we let alpha = 1/10, then Delta <= 10^2 v_b L_Planck.'",
"published_hypotheses":[
 "P1 The flat-space Ford-Roman QI (massless minimally coupled scalar, inertial = timelike GEODESIC observer, Lorentzian sampler, coefficient 3/(32 pi^2)) is ARGUED ('we argue', abstract) to hold in curved and/or bounded spacetime for sampling times small compared with the minimum local proper radius of curvature or distance to a boundary.",
 "P2 The geometric scale is r_m, the smallest of the local length scales, with r_c ~ 1/sqrt(R_max) >~ r_m in the (static or boosted) orthonormal frame; for a boosted observer the scale is r_m/gamma (Secs 4.1b, 5.2). It is NOT an arbitrary size of the object.",
 "P3 f << 1 is the hypothesis; the NUMBER is a choice: 'For example, for f ~= 0.01' (4.1), 'A reasonable choice of f is f ~= 0.01' (p.16), but 'f ~= 0.1' for the flat region between Casimir plates (4.5). No derivation of 0.01 is given.",
 "P4 The energy density is approximately constant over tau_0 (static observer at the throat, 'such an observer is geodesic', or a boosted geodesic observer), so the sampled integral reduces to the local value.",
 "P5 Order-of-magnitude reasoning: eq (51)'s coefficient is quoted as 1/2 (exact algebra gives sqrt(3/(4 pi)) = 0.4886) and Sec. 5 restates the same case as r_0 <~ l_p/f^2."
],
"hypothesis_drift":[
 "ATTRIBUTION NARROWED, achievable.py:119-121: 'Ford & Roman's own practice of sampling at a hundredth' is supported by gr-qc/9510071 Secs 4.1, p.16 and 5.1 (f ~= 0.01 in every curved-throat example), but it is not their only choice: Sec. 4.5 takes f ~= 0.1, and Pfenning & Ford (Ford's own 1997 warp application, which achievable.py's subject is closer to) take alpha = 1/10 'as an example'. 'Practice' is fair for the 1996 wormhole paper; it is not a uniform practice of the authors. No paper or section is cited at the site (canonical status_word: none).",
 "SCALE CHANGED, achievable.py:119-121 with :68-72 and crossing_radius(): F&R's scale is r_m, the minimum local proper radius of curvature (P2); the tree's 'geometric scale' is the core radius a = 0.02 b. Computed in the tree's own core (G m/(c^2 a) = 0.25): r_c = 0.82 a from 8 pi G rho/c^2 and 2.0 a from the tidal term, so the substitution is an order-level identification, not F&R's definition; it moves 3989 l_P to 997..5984 l_P (rederive step 6), under one decade.",
 "DROPPED, achievable.py:119-121: f << 1 is F&R's hypothesis and 0.01 is a 'reasonable choice', not a derived value; the tree states the number as 'practice' without the qualifier. The tree's own point (fragility on an unargued choice, achievable.py:184-186 '8.8 orders ... unargued sampling choice') is consistent with this and is not weakened by it.",
 "ADDED (silently), achievable.py:120-121: the 3989 l_P figure carries F&R's coefficient 3/(32 pi^2) as well as f = 0.01 (reproduced: 4.0933 x sqrt(3/32 pi^2) x 10^4 = 3989.42). The site does not say so; data_used notes it is 'not computed in this file's code'.",
 "DISCREPANCY (wording, not refutation), achievable.py:121 'four decades away': measured from the F&R-coefficient f = 1 crossing (0.3989 l_P) the move is exactly 4.000 decades; measured from the 4.0933 l_P printed in the immediately preceding sentence (achievable.py:117-118) it is 2.989 decades. Both readings exist; the adjacent-sentence reading is ~3 decades.",
 "DROPPED (inherited from the QI, not specific to this entry), achievable.py:110-122: F&R's application is to a GEODESIC observer (static at a throat, or boosted); a static observer inside the tree's static core is not geodesic except at the centre. The crossing this entry perturbs is already withdrawn to DIMENSIONAL IDENTITY, so nothing further rests on it.",
 "KEPT (correctly), achievable.py:228-230 (not this site): the curved-space step is 'argued' per gr-qc/9607003 Sec. 4; gr-qc/9510071's abstract uses the same word."
],
"data_at_publication":[
 {"quantity":"sampling fraction f (tau_0/r_m)","value_then":"f << 1; examples f ~= 0.01 (Secs 4.1, p.16, 5.1), f ~= 0.1 (Sec. 4.5); Pfenning-Ford alpha = 1/10","value_now":"still a choice, not a datum. Kontou & Olum 1410.0665 (READ, cached) show curvature corrections are small when R_max t_0^2, R''_max t_0^4, R'''_max t_0^5 << 1, i.e. the correction scales as f^2 (1e-4 at f = 0.01, 1e-2 at f = 0.1)","source_now":"arXiv:1410.0665 p.19-20 (local cache src/_cache_1410..txt)","moves_conclusion":"The crossing scales as f^-2 exactly (sympy: a_cross(f,kappa)/a_cross(1,1) = sqrt(kappa)/f^2). f = 0.1 gives 39.9 l_P, f = 0.01 gives 3989 l_P. The tree's conclusion -- the Planck-scale crossing is fragile and a dimensional identity -- holds for ANY f the sources use; the specific 3989 holds only at f = 0.01."},
 {"quantity":"QI coefficient c = 3/(32 pi^2)","value_then":"0.0094989 (Ford-Roman 1995, PRD 51 4277)","value_now":"unchanged for the Lorentzian sampler; the optimal compactly supported sampler differs (Fewster-Eveson / Fewster 1208.5399 C ~ 3.17 on a duration), which the tree already uses elsewhere","source_now":"gr-qc/9607003 eq (1)/(17), READ in sibling audits","moves_conclusion":"no -- 3989 is defined with this coefficient; a different sampler changes the number by sqrt(coefficient ratio), not the fragility conclusion"},
 {"quantity":"Planck length l_P","value_then":"~1.6e-33 cm (order only in the paper)","value_now":"1.616255e-35 m (CODATA 2018 = CODATA 2022 value used by achievable.py)","source_now":"CODATA; achievable.py L_PLANCK","moves_conclusion":"no -- the result is expressed in l_P"},
 {"quantity":"core geometry m/b = 5e-3, a/b = 0.02 (the tree's, not the source's)","value_then":"n/a (tree inputs)","value_now":"as in achievable.py:333-334","source_now":"achievable.py","moves_conclusion":"no -- 3989 reproduced from these inputs by symbolic crossing and by a numeric root of the file's own ford_roman_allow(0.01 a/c) = required_density(a/0.02)"}
],
"rederivation":{
 "method":"sympy",
 "script_path":D+"/rederive/ford-roman-sampling-practice.py",
 "outcome":"ALL CHECKS PASS, exit 0. (1) achievable.crossing_radius() core = 4.09331 l_P reproduced from the file's own code (imported read-only, bytecode off). (2) sympy: a_cross = 50 sqrt(G hbar kappa)/(sqrt(K) c^(3/2) f^2), so a_cross(f,kappa)/a_cross(1,1) = sqrt(kappa)/f^2; with kappa = 3/(32 pi^2): f = 1 -> 0.39894, f = 0.1 -> 39.894, f = 0.01 -> 3989.42 l_P; independent numeric root of ford_roman_allow(0.01 a/c) = required_density(a/0.02) -> 3989.42 l_P. The tree's 3989 is REPRODUCED. (3) 'four decades': 4.000 from the f = 1 F&R crossing, 2.989 from the printed 4.0933 (discrepancy of wording). (4) F&R's own examples re-derived: eq (51) r_0 <~ sqrt(3/(4pi))/f^2 = 0.4886/f^2 (printed 1/(2f^2)), 4886 l_p at f = 0.01 (printed '10^4 l_p'); eq (69) r_0 = 1 m, f = 0.01 -> a_0 = 10^13.96 l_p (printed 10^14); eq (88) f = 0.1, s = 1e23 l_p -> 1e44 l_p = 0.0108 AU (printed '~0.01 A.U.'); Sec. 5 l_p/f^2 = 1e4. (5) Pfenning-Ford (3/4)sqrt(3/pi)/alpha^2 at alpha = 1/10 = 73.3 v_b l_P (printed '10^2') -- a TENTH. (6) Tree's core: G m/(c^2 a) = 0.25, r_c/a = 0.8165 (Ricci) .. 2.0 (tidal); crossing at tau_0 = 0.01 r_c is 997..5984 l_P.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"Kontou & Olum, 'Quantum inequality in spacetimes with small curvature', arXiv:1410.0665, PRD 91 104005 (2015)","effect":"confirms","what":"'Ford and Roman [6] have argued that flat-space quantum inequalities can be applied in curved spacetime ... The present paper explicitly confirms this claim and calculates the magnitude of the deviation', to first order in the Ricci tensor; corrections small if R_max t_0^2, R''_max t_0^4, R'''_max t_0^5 << 1 -- i.e. the f << 1 hypothesis, with correction ~ f^2. Adds conditions F&R did not state: curvature must be small over the whole causal diamond of the sampled segment, and a renormalisation ambiguity (a, b). NB their sentence prints 'radius of curvature is small as compared to the sampling time', the inverse of what they prove -- a misprint, recorded as a discrepancy only.","read_status":"READ (locally cached alphaXiv text src/_cache_1410..txt, pp.1-21; not re-fetched this stage)"},
 {"ref":"Pfenning, PhD thesis 'Quantum inequality restrictions on negative energy densities in curved spacetimes', arXiv:gr-qc/9805037 (1998)","effect":"confirms","what":"Ch.3.3 short-sampling-time expansion: 'the QI in this limit reduces to the flat space form with subdominant correction terms which depend on the spacetime geometry'; ch.5 p.75: 'It has been argued by Ford and Roman [44] that one may apply the QI to non-Minkowski spacetimes if the sampling time is smaller than the local radius of curvature. We know this to be true.' Uses alpha = 1/10, not 1/100.","read_status":"READ (cached text src/_cache_gr-qc_9805037.txt, pp.1,4,5,10,13,14,31,71-79,85)"},
 {"ref":"Fewster & Teo, arXiv:gr-qc/9812032, PRD 59 104016 (1999)","effect":"extends","what":"Exact QIs in static spacetimes with no curvature cap and no sampling fraction to choose; up to an order of magnitude stronger than Pfenning-Ford's for the Lorentzian sampler. Removes the need for the f-choice in static cases; the tree already carries this (achievable.py:242-253, fewsterteo.py).","read_status":"READ (cached text src/gr-qc_9812032.cached.txt; full audit in sibling files)"},
 {"ref":"discover_papers (alphaXiv) for later work narrowing/contradicting the f-choice","effect":"contested","what":"NOT RUN: the one permitted discover_papers call returned 'alphaXiv assistant quota exceeded'. No search for later literature on the sampling fraction itself was possible in this stage; the three items above are from sources already cached in d67/src. This row records the gap; it is not evidence either way.","read_status":"NAMED-NOT-READ (search failed: quota)"}
],
"lacked_data":"What F&R lacked in 1995: a proof that the flat-space QI holds in curved spacetime at short sampling times, and hence any principled value of f. They supplied f by judgement ('reasonable choice'). Later data: Pfenning 1998 (short-sampling expansion), Fewster-Smith 2008 and Kontou-Olum 2014/15 (first-order Ricci corrections ~ R_max t_0^2 ~ f^2) CONFIRM the premise and show the correction at f = 0.01 is ~1e-4 relative, at f = 0.1 ~1e-2 -- so later data would PERMIT a larger f (less conservative) with small error, and F&R's 0.01 was conservative. Having that data does not change the conclusion the tree draws from this entry: the crossing moves as f^-2 whatever f is, so the 'third Planck route' is fragile at any sourced f (39.9 l_P at 0.1, 3989 at 0.01) and is a dimensional identity at all f (computed). Evidence AGAINST M's hypothesis for this result: the one gap (curved-space validity) was later closed in F&R's favour to first order; nothing in the sampling practice was 'inaccurate'. Evidence FOR a narrower claim: the '0.01' is a choice the authors themselves varied (0.1 in Sec. 4.5; Ford's 1997 warp paper used 1/10), so the tree's word 'practice' fits one paper, not the authors' body of work.",
"grade":"NARROWED",
"grade_evidence":"READ at source (gr-qc/9510071v1 local full text): F&R do sample at tau_0 = f r_m with f << 1 and take f ~= 0.01 in every curved-throat example (eq 51 p.12, eq 69 p.16, Sec. 5.1), so the tree's attribution is supported for that paper, and the tree's 3989 l_P is reproduced exactly (sympy + numeric root, 3989.42). It is NARROWED, not STANDS, on three named points: (i) the practice is not uniform -- F&R Sec. 4.5 uses f ~= 0.1 and Pfenning-Ford use alpha = 1/10; (ii) F&R's scale is the minimum local proper radius of curvature r_m, the tree's 'geometric scale' is the core radius a (computed r_c/a = 0.82..2.0, moving 3989 to 997..5984 l_P); (iii) the 3989 silently includes the 3/(32 pi^2) coefficient, and 'four decades away' is 4.000 decades from the f = 1 F&R crossing but 2.989 from the 4.0933 printed in the preceding sentence (a wording discrepancy, not an error of substance). Nothing is WRONG: no counterexample; the conclusion the entry supports (the Planck crossing is fragile and a dimensional identity) holds at every f the sources use.",
"what_would_change_the_grade":"To STANDS: the site cites gr-qc/9510071 Secs 4.1/5.1 for the f ~= 0.01 choice, names r_m (minimum local curvature radius) as the scale or states the r_m -> a identification with its measured 0.82..2.0 factor, says the 3989 carries 3/(32 pi^2), and reads 'three decades from the 4.09 printed above, four from the coefficient-bearing f = 1 crossing'. To DATA-DEPENDENT: a later paper fixing f from first principles at a value that moves the crossing across the Planck scale (none known here; the literature search could not be run -- quota). To WRONG: only a showing that F&R never used f ~= 0.01, which the source text refutes.",
"reverify_command":"python3 "+D+"/rederive/ford-roman-sampling-practice.py && grep -n 'f ≈ 0.01\\|f ≈ 0.1\\|f ≪ 1' "+SRC+" && grep -n -A3 'alpha = 1/10\\|α = 1/10\\|let α' "+D+"/src/_cache_gr-qc_9805037.txt | head; sed -n 110,122p /home/user/Claude-Method-Works/research/warp-drive/achievable.py",
"report_path":D+"/audits/ford-roman-sampling-practice.json"
}
json.dump(r,open(r["report_path"],"w"),indent=1,ensure_ascii=False)
print("written")
