import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "linearised-weak-field-metric",
 "name": "Linearised (weak-field, isotropic) static metric ds^2 = -(1+2Phi)dt^2 + (1-2Phi)dx^2, Phi = -M/r, extrapolated to M < 0 (composite.py; reused by concentric.py)",
 "source": {
  "located": "Textbook result (Einstein 1916 weak-field limit; standard linearised GR). Read in S.M. Carroll, Lecture Notes on General Relativity, arXiv:gr-qc/9712019v1 (Dec 1997), ch.6 'Weak fields and gravitational radiation', PDF p.154 (notes p.147): harmonic gauge (6.17)/(6.21), linearised field equations (6.18)/(6.22), vacuum (6.23), 'h_00 = -2Phi (6.24), where Phi is the conventional Newtonian potential, Phi = -GM/r', and the assumption 'the energy-momentum tensor of our source is dominated by its rest energy density rho = T_00. (Such an assumption is not generally necessary in the weak-field limit, but will certainly hold for a planet or star...)', leading to (6.25) h = hbar_00. Also PDF p.118-119: Poisson (4.35), Newtonian-limit metric (4.21), nabla^2 h_00 = -8 pi G T_00 (4.36, 4.51). The final line of the derivation (the isotropic ds^2 itself, next PDF page) was NOT in the cached page set.",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "Cached alphaXiv answer_pdf_queries page text for gr-qc/9712019v1, saved by an earlier stage of this docket at d67/src/carroll_hits.json (PDF pages 1, 116-119, 125, 154, 169, 229). This stage's own alphaXiv calls (answer_pdf_queries x2, get_paper_content fullText, discover_papers) all returned 'alphaXiv assistant quota exceeded'; direct arxiv.org is connect_rejected by the egress proxy. The Einstein-1916 classic is NAMED-NOT-READ; Carroll is a later restatement read in part. Because the last line of Carroll's derivation was not read, the metric form itself was RE-DERIVED here (R1, sympy) rather than taken from the page: it is the O(M) truncation of exact Schwarzschild in isotropic coordinates and its O(M) Ricci vanishes identically."
 },
 "published_statement": "Carroll gr-qc/9712019 ch.6: in harmonic gauge the linearised Einstein equations are Box hbar_mu_nu = -16 pi G T_mu_nu (6.22); 'From (6.22) and our previous exploration of the Newtonian limit, it is straightforward to derive the weak-field metric for a stationary spherical source such as a planet or star ... h_00 = -2Phi (6.24), where Phi is the conventional Newtonian potential, Phi = -GM/r. Let us now assume that the energy-momentum tensor of our source is dominated by its rest energy density rho = T_00 ... Then the other components of T_mu_nu will be much smaller than T_00, and from (6.22) the same must hold for hbar_mu_nu' -> (6.25) h = hbar_00, whence (re-derived here, R1) ds^2 = -(1+2Phi)dt^2 + (1-2Phi)(dx^2+dy^2+dz^2), which equals exact Schwarzschild in isotropic coordinates to O(M): -g_tt = 1 - 2M/r + 2M^2/r^2 + O(M^3), g_ii = 1 + 2M/r + (3/2)M^2/r^2 + O(M^3).",
 "published_hypotheses": [
  "H1 weak field: g = eta + h with |h_mu_nu| << 1, field equations kept to first order in h (Carroll ch.6, eq. 6.6 onward)",
  "H2 harmonic (de Donder) gauge, partial_mu hbar^mu_lambda = 0 (6.17)/(6.21); the isotropic form is a gauge statement, fixed only to O(h)",
  "H3 stationary (static) source",
  "H4 source dominated by rest energy density rho = T_00 >> T_ij ('will certainly hold for a planet or star'; Carroll notes it is 'not generally necessary in the weak-field limit')",
  "H5 Phi is the Newtonian potential solving nabla^2 Phi = 4 pi G rho (4.35); Phi = -GM/r for a point/spherical source, M > 0 implicit ('planet or star')",
  "H6 the stress-energy itself small, of the same order as the perturbation (Carroll PDF p.153-154: 'the lowest nonvanishing order in T_mu_nu is automatically of the same order of magnitude as the perturbation')"
 ],
 "hypothesis_drift": [
  "ADDED/EXTRAPOLATED (named by the owner): M < 0. Carroll's derivation is for 'a planet or star' (rho > 0, H4/H5). composite.py:35-36 'with M of either sign'; composite.py:99-101 'NEGATIVE MASS IS ASSUMED, NOT DERIVED'. The linearised equations are linear, so -M is a linearised solution; its exact vacuum completion (negative-mass Schwarzschild, isotropic) was verified Ricci-flat here at M = -0.04 (R1). Not a hidden drop: the owner names it.",
  "WEAKENED (named by the owner, but its size understated in part of the window): |Phi| << 1 (H1). composite.py:102-104 calls the window location INDICATIVE; at composite's grid top |M| = 4e-2, b = 0.3, Phi(b) = 0.133 and 4|M|/b = 0.53 rad; at the computed upper edge |M| = 1.77e-2, Phi(b) = 0.059 (R4). Tested against the exact completion: edges move by -0.15 % and -0.59 % (R4), so for composite the named limitation is conservative, not concealing.",
  "WEAKENED AND MIS-LOCATED in concentric.py:139-141: 'Phi_max ~ m/a = 0.25 at the design point, which is NOT small'. (a) The ray the verdict rests on (b = 1) sees max |Phi| = 4.97e-3 at m = 5e-3 and 3.98e-2 at m = 4e-2 (R5): along the ray H1 holds to <= 4 %. (b) In the core the violation is larger than stated across the stated window 5e-3..4e-2 (concentric.py:78, 360): g_ii = 1-2Phi reaches 0 at the core centre at m = 0.010001 and is NEGATIVE inside r* = 0.0346 (m = 2e-2) and r* = 0.0774 (m = 4e-2) (R6) -- the linearised form is not a Lorentzian metric there. The tree names only the design-point value 0.25. No ray enters the core, so no computed figure uses the non-Lorentzian region; the physical configuration the upper half of the window describes is outside H1 at its core.",
  "DROPPED (not named by either owner): H2 gauge/coordinates. The 'early' test t - |dx| < 0 (composite.py survey; concentric.py survey 'leads') compares coordinate time with coordinate distance; the linearised coordinates coincide with isotropic (or harmonic) ones only to O(M). R4 tests the isotropic completion only; a completion in another O(M)-equivalent chart (e.g. harmonic) differs at O(M^2) in the coordinate delay and was NOT computed.",
  "DROPPED (not named): H4/H6 for concentric's sources. concentric.py:163-167 superposes a Plummer core Phi = m/sqrt(r^2+a^2) and a shell term; the corridor is not exact vacuum (owner measures traceless to 7.5e-4, concentric.py:355-356). No stress content is specified for either source; the metric form presumes T_ij << T_00 (H4) wherever the source is. Not computed here.",
  "DISCREPANCY in the owner's validation narrative, not in the external result: composite.py:326-327 prints 'h-independent at 1.6e-4 over an order of magnitude in step size, so this residue is the metric's own O(Phi^2), not the difference'. Computed (R2, R2b): the same quantity (k = (1,1,0,0), coordinate e_y, e_z, M = -2e-3, b = 0.3) is exactly 5.90e-5; composite.riemann_lower gives 9.88e-4, 1.62e-4, 6.83e-5, 6.00e-5 at h = 3e-3, 1e-3, 3e-4, 1e-4 -- h-DEPENDENT, converging to 5.90e-5, so ~1.0e-4 of the printed 1.6e-4 is finite-difference error. With a truly null k and orthonormal screen the metric's own O(Phi^2) Ricci gives |trace|/max = 8.69e-3 (R2), which matches the along-ray 'Euler leak' 9.29e-3 that composite.py:328-330 attributes to screen transport. The exact vacuum completion is traceless identically (R2) and reproduces every conjugate point to <= 0.06 affine units (R4), so VALIDATION 2's conclusion ('what focuses is shear') stands; only the attribution of the two residues is swapped. Recorded, not repaired."
 ],
 "data_at_publication": [
  {"quantity": "G, c", "value_then": "G = c = 1 (geometrised); no measured value enters", "value_now": "unchanged (units)", "source_now": "n/a", "moves_conclusion": "no -- the result is a closed-form statement in M/r"},
  {"quantity": "PPN gamma (coefficient of the g_ij term: 1 - 2 gamma Phi; GR predicts 1)", "value_then": "gamma = 1 exactly (GR, assumed by the metric form)", "value_now": "gamma = 1 - (0.6 +/- 3.1)e-4 (VLBI), as restated verbatim in Barcelo & Visser gr-qc/0003025 eq.(5.52), cached d67/src/gr-qc_0003025.txt:2428-2432. The tighter Cassini bound (Bertotti et al. 2003) was NOT READ this stage.", "source_now": "gr-qc/0003025 eq.(5.52) (READ, cached text); Cassini NAMED-NOT-READ", "moves_conclusion": "no -- deflection scales as (1+gamma)/2, a relative shift <= 1.9e-4 at 1 sigma above the central value, against edge shifts of 1.5e-3 / 5.9e-3 from the nonlinear completion (R4) and composite's own INDICATIVE label"},
  {"quantity": "tree parameters (not measured data): composite b = 0.3, x0 = -40, lam = 75, n = 900; |M| grid 2e-4..4e-2 (composite.py:122-124, 394-399)", "value_then": "as coded", "value_now": "reproduced by an independent integrator: conj 56.57 vs printed 56.50, delay -3.76176e-2 vs -3.7618e-2 at M = -2e-3; all six rows agree to <= 0.07 in conj and <= 3e-4 relative in delay (R4)", "source_now": "rederive R4", "moves_conclusion": "no; computed window edges |M| = 1.238e-3 (seats) and 1.768e-2 (delay sign) linearised, 1.236e-3 and 1.758e-2 exact"},
  {"quantity": "concentric a = 0.02, R_s = 200, b = 1, m = 5e-3 design point (concentric.py:155-160, 139-140)", "value_then": "Phi_max ~ m/a = 0.25 (stated)", "value_now": "Phi(0) = 0.2500 at m = 5e-3 (confirmed); Phi(0) = 1.9998 at m = 4e-2 (window top); along the ray <= 3.98e-2 (R5, R6)", "source_now": "rederive R5, R6", "moves_conclusion": "not for the ray figures; the core metric is non-Lorentzian for m > 0.010001 (R6)"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/linearised-weak-field-metric.py",
  "outcome": "R1 (sympy): O(M) Ricci of the linearised metric = 0 in all 16 components; O(M^2) R_tt = -2M^2/r^4 (not an exact vacuum solution); O(M) coefficients equal exact isotropic Schwarzschild's; dropped O(M^2): g_tt +2M^2/r^2, g_ii +3M^2/(2r^2); exact isotropic Schwarzschild is Ricci-flat at M = -0.04. R2: composite's fixed-point residue exactly 5.90e-5 (printed 1.6e-4); proper null frame O(Phi^2) Ricci ratio 8.69e-3; exact Schwarzschild 0. R2b: composite's residue is h-dependent (9.9e-4 -> 6.0e-5 over h 3e-3 -> 1e-4). R3 (mpmath quadrature): second-order deflection coefficient of the linearised metric ~12.6 (4 pi = 12.566) vs exact 11.80/11.76 -> 15 pi/4 = 11.781, both signs; at M = -0.04, b = 0.3 the linearised deflection differs from exact by 0.72 %. R4 (scipy DOP853, analytic Christoffels, conjugate points from neighbouring geodesics, independent of composite's Riemann/Jacobi): composite's printed table reproduced; exact negative-mass Schwarzschild gives the same seat/early verdict at every grid row and moves the window edges by factors 0.9985 (lower, |M| 1.238e-3 -> 1.236e-3) and 0.9941 (upper, 1.768e-2 -> 1.758e-2). R5/R6: concentric's ray sees |Phi| <= 4e-2; its core has g_ii <= 0 for m >= 0.010001.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Keeton & Petters, gr-qc/0511019 (PPN lensing formalism, second-order deflection 15 pi/4 (M/b)^2 for Schwarzschild)", "effect": "extends", "what": "Second-order coefficients of the static spherical metric; the O(M^2) deflection coefficient 15 pi/4 that the linearised metric misses (it gives 4 pi). Value re-derived here by quadrature (R3), not taken from the paper.", "read_status": "NAMED-NOT-READ (alphaXiv quota exceeded; arxiv egress-blocked)"},
  {"ref": "Freivogel & Krommydas, arXiv:1807.03808 (Smeared Null Energy Condition), sec. 'Negative Mass Black Holes'", "effect": "narrows", "what": "Bounds the potential of a uniform spherical negative-energy distribution built from quantum fields: G_N M/r = G_N r^2 <T> >= -B (eq.42), 'for the zeroth order gravitational potential to be significant, the radius of the distribution should be comparable to the UV cut-off' (eq.43). Bears on whether the M < 0 sources (Phi(0) = 0.25..2 in concentric's core, |Phi(b)| up to 0.13 in composite) can be realised -- the owners' named ASSUMED limitation -- not on the linearised metric's accuracy.", "read_status": "READ at cached text d67/src/1807.03808.txt lines 1743-1780 (saved by an earlier stage); not re-fetched this stage"},
  {"ref": "Barcelo & Visser, gr-qc/0003025", "effect": "confirms", "what": "'M < 0 represents a perfectly good solution to the Einstein field equations, normally the negative mass Schwarzschild geometry is excluded by hand' -- the exact vacuum completion used in R4 is a solution of the field equations (also verified here, R1).", "read_status": "READ at cached text d67/src/gr-qc_0003025.txt ~line 865-868"},
  {"ref": "discover_papers (one call, this stage)", "effect": "contested", "what": "The mandated later-literature search could not run: 'alphaXiv assistant quota exceeded'. No later paper was found or read this stage beyond the cached texts above; this is a gap, not a finding.", "read_status": "NOT RUN (quota)"}
 ],
 "lacked_data": "M's hypothesis for this result: the weak-field metric is a first-order truncation, not a measurement-dependent law, so what its authors 'lacked' is not data but the O(M^2) terms they deliberately dropped. The only empirical input is gamma = 1 (GR); the current VLBI restatement 1 - (0.6 +/- 3.1)e-4 (gr-qc/0003025 eq.5.52) moves the deflection by <= 2e-4 relative -- it cannot move the conclusion. Evidence against M's suspicion here: the dropped terms were computed (R1: +2M^2/r^2 in g_tt, +3M^2/2r^2 in g_ii) and restored by integrating the exact negative-mass Schwarzschild geometry (R4): every seat/early verdict in composite's table is unchanged and the window edges move by 0.15 % and 0.59 %. Evidence FOR a limitation, found in the tree's use rather than the source: concentric's core is outside the result's domain (g_ii <= 0 for m >= 0.010001, R6), and composite's own validation mis-attributes its two residues (R2b). Neither is new data the original authors lacked; both are extrapolations the tree makes. Extrapolation to M < 0 is not tested by any datum anywhere -- there is no observed negative mass -- so that part is a named hypothesis, not a data question.",
 "grade": "NARROWED",
 "grade_evidence": "The external result STANDS as mathematics: R1 (sympy) shows the metric solves the linearised vacuum equations exactly at O(M) and equals exact isotropic Schwarzschild to O(M), for either sign of M. The tree's use is NARROWED on two computed grounds and one dropped hypothesis: (i) concentric.py applies the form to a core with Phi(0) up to 1.9998 inside its stated window 5e-3..4e-2; for m >= 0.010001 g_ii = 1-2Phi <= 0 in a core ball (r* = 0.0774 at m = 4e-2), i.e. outside the result's class, which concentric.py:139-141 names only as 'Phi_max ~ 0.25 at the design point' (R6); the ray itself sees |Phi| <= 0.04 (R5), so no concentric figure is shown wrong, and its strong-field completion was NOT computed; (ii) the gauge/coordinate hypothesis H2 is dropped by the coordinate 'early' test t - |dx| < 0 (tested in the isotropic completion only); (iii) M < 0 lies outside Carroll's 'planet or star' premise but is NAMED by the owner (composite.py:99). For composite the named INDICATIVE caveat is conservative: the exact vacuum completion reproduces its seat/early verdict at all six grid rows and moves the window edges by -0.15 % and -0.59 % (R4). Discrepancy recorded, not an error: composite.py:326-327's 'h-independent 1.6e-4 ... the metric's own O(Phi^2)' is h-dependent and converges to 5.90e-5 (R2b), while the metric's O(Phi^2) Ricci in a proper null frame is 8.69e-3 (R2), matching the along-ray 9.29e-3 the owner calls Euler leak. Not WRONG: no counterexample to the result or to any verdict resting on it was found.",
 "what_would_change_the_grade": "To STANDS: concentric restricted to m < 0.010001 (or its core given a strong-field completion that reproduces the ray figures), and the 'early' test shown chart-independent at O(M^2) (e.g. by repeating R4 in harmonic coordinates or with an invariant arrival comparison). To WRONG: a nonlinear completion of concentric's core+shell (e.g. interior Schwarzschild for the core plus a static shell, Israel junction) in which the corridor ray's seat or lead flips inside 5e-3..4e-2 -- not computed here. To OPEN on the source side it cannot go: the form was re-derived independently of the unread final page. Reading Carroll's final line (PDF p.155) or Keeton-Petters would upgrade read_status, not the grade.",
 "reverify_command": "python3 " + D + "/rederive/linearised-weak-field-metric.py   # ~6 min; R1-R6 and R2b print; compare R4 edges 1.2380e-03/1.7684e-02 (lin) vs 1.2361e-03/1.7580e-02 (exact), R6 threshold m = 0.010001, R2b h-series 9.88e-4, 1.62e-4, 6.83e-5, 6.00e-5",
 "report_path": D + "/audits/linearised-weak-field-metric.json"
}
json.dump(rep, open(rep["report_path"], "w"), indent=1, ensure_ascii=False)
print("written", rep["report_path"])
