import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R = {
 "key": "gr-qc/9701064#omega",
 "name": "HPS far-zone oscillation frequencies omega_1^2 = 1/(16 K^2), omega_2^2 = 1/(16 K^2 (4 + 3 ln F))",
 "source": {
  "located": "Hochberg, Popov, Sushkov, 'Self-consistent Wormhole Solutions of Semiclassical Gravity', arXiv gr-qc/9701064 v1 (30 Jan 1997; dated 23 Oct 1996), PRL 78, 2050 (1997). The statement is on p.8 of the arXiv text layer; K^2 = 1/(5760 pi) on p.4; eqs. (5)-(7) pp.4-5; footnote [20] p.9.",
  "read_status": "READ",
  "via": "alphaXiv page-text capture of the arXiv v1 PDF, all 12 pages, held at d67/src/hps/hps_0.xml (captured earlier in this session through alphaXiv answer_pdf_queries; read here in full). Live alphaXiv calls in THIS stage (get_paper_content, answer_pdf_queries, discover_papers) all returned 'assistant quota exceeded'; arxiv.org and kpfu.ru (which hosts a PRL copy) are refused by the egress proxy. The PRL journal text was NOT read -- the same limit hpscentre.py:117 records."
 },
 "published_statement": "p.8: 'From the numerical calculations, we see that for sufficiently large l, both the redshift and shape functions can be represented as a sum of two distinct components f(l) = F(l) + phi(l); r(l) = R(l) + rho(l), where F(l) and R(l) are strictly monotone increasing and phi(l) and rho(l) are bounded oscillating functions. The relative magnitudes of these components and their derivatives may be estimated straightforwardly and then used to expand consistently the coupled Einstein equations. We find that the oscillating modulation is composed of two modes with frequencies omega_1^2 = 1/(16K^2) and omega_2^2 = 1/(16K^2 (4+3 ln F)), respectively, while in the limit of large l, R(l) ~ l and F(l) ~ (a ln l - b)^2 for a = 5.3 and b = 25.5.' p.4: '(K^2 = 1/(5760 pi))'. Footnote [20]: 'We have also set the scalar mass and temperature to zero: m = kappa = 0. In this case, the arbitrary renormalization scale parameter mu appearing in (T)_log can be absorbed into the definition of f.'",
 "published_hypotheses": [
  "H1 semiclassical field equations G = 8 pi <T> with <T> the Anderson-Hiscock-Samuel ANALYTIC APPROXIMATION (eq. 4), not an exact <T>",
  "H2 conformally coupled scalar, xi = 1/6; scalar mass and temperature zero, m = kappa = 0 (footnote [20])",
  "H3 the renormalisation scale mu absorbed into the definition of f (footnote [20]) -- so 'ln F' carries the unfixed mu",
  "H4 far zone: 'sufficiently large l'",
  "H5 decomposition f = F + phi, r = R + rho with F, R strictly monotone increasing and phi, rho bounded oscillating -- read off the numerics ('guided by the results of the numerical investigation', p.7)",
  "H6 a consistent expansion by estimated relative magnitudes (in effect: linearisation in the oscillating parts about a slowly varying F, R ~ l) -- the expansion itself is NOT printed",
  "H7 (implicit, not stated by HPS) no finite R^2 / C^2 counterterm beyond what AHS's <T> carries: the box R coefficient in the trace is AHS's 1/(2880 pi^2)"
 ],
 "hypothesis_drift": [
  "REGIME CHANGED, AND STATED BY THE TREE (not a hidden drift): hpscentre.py:51-56 applies the frequencies at a REGULAR CENTRE, linearising about flat space f = e^{L0}, r = l, with ln F replaced by L0 = ln f(0); HPS state them for the FAR ZONE of their throat about slowly varying F, R ~ l. The tree says so ('printed for the far zone ... recovered here at the centre'). The identification is CHECKED here: the far-zone leading-order WKB dispersion (T2) and the exact centre spherical-mode dispersion (T3) are the same polynomial (3L0+4)s^2 - (3L0+5)s + 1, s = 16K^2 k^2.",
  "HYPOTHESIS STRONGER THAN NEEDED (not a weakening): hpscentre.py canonical hypothesis 'conserved reading' -- the frequencies do NOT depend on the reading. Under all four readings of the disputed slots M1 (16/116) and M2 (r^1/r^2) the far-zone and centre dispersions are identical (T4), because both slots are cubic in the perturbation (f'^2 f'', f'^2 r'^2). So omega_1, omega_2 hold on the printed system too; the tree's restriction is harmless but unnecessary for THIS result.",
  "DROPPED AT THE SITE (named elsewhere in the tree): HPS footnote [20] (H3), that mu is absorbed into f, is not carried at hpscentre.py:51-59 or :1411 where omega_2 = 1/16K^2(4+3 ln F) is identified with k^2 = 1/(16K^2(3L0+4)). It IS read at hpscentre.py:116 and named at qeihps.py:143 ('ln(mu^2 f), mu arbitrary'). Consequence: omega_2 is a one-parameter family in the unfixed mu (3L0+4 can take any real value as mu varies), and the tree's CENTRE_L0 = 0 (hpscentre.py:273) is a choice of mu. The tree's theorem (b) is stated for every 3L0+4 > 0, L0 != -1, so no conclusion of the tree moves.",
  "UNNAMED BY SOURCE AND TREE ALIKE (H7): omega_1 comes from the TRACE equation alone -- at linear order -R = 16K^2 box R (T5, conserved reading; the log part is traceless), so k_1^2 = 1/(16K^2). A finite R^2 counterterm rescales the box R coefficient to c and gives k_1^2 = 1/(16K^2 c); c < 0 turns the ripple into a growing/decaying exponential. The tree itself records elsewhere that the corresponding constants are FREE (linstab.py:141 'alpha~^S_3 and alpha~^TT_4 (through b_2) are FREE', :176) but does not carry that hypothesis at hpscentre.py:51-59 / :206. Within 'HPS's model system' (G = 8 pi <T>_AHS, which the tree always scopes to) the value is fixed by the model, so this is a scope note, not a refutation.",
  "WORDING DISCREPANCY (recorded, not a numerical error): hpscentre.py:264 calls RIPPLE_WINDOW_K = 8 pi 'two ripple periods, 2 pi/omega_1'. 8 pi K = 2 pi/omega_1 exactly (T6), which is ONE full period of the omega_1 mode and TWO extremum spacings (pi/omega_1 = 4 pi K, the tree's own 'ripple spacing' at :206). The number is right; 'period' there means extremum spacing.",
  "NOT A DRIFT: 'frequency' in HPS is a spatial wavenumber in proper distance l (static metric); the tree uses it as such (k)."
 ],
 "data_at_publication": [
  {"quantity": "K^2 (the coupling that sets both frequencies)", "value_then": "1/(5760 pi) in Planck units (HPS p.4) = 8 pi x 1/(46080 pi^2)", "value_now": "unchanged: a pure number fixed by the conformal-scalar trace coefficients alpha = beta = 1/(2880 pi^2) (16 K^2 = 8 pi/(2880 pi^2), checked in T6). Not a measured datum.", "source_now": "AHL gr-qc/9504019 eq. (6) as read by hpscentre.py:125-126; identity machine-checked in rederive T6", "moves_conclusion": "no"},
  {"quantity": "Planck length (converts K to metres)", "value_then": "~1.616e-35 m (CODATA 1986/1990 era; HPS quote no value)", "value_now": "1.616255(18)e-35 m (CODATA 2018 and 2022)", "source_now": "CODATA 2022 recommended values (not re-read in this stage; NAMED)", "moves_conclusion": "no -- the frequencies are stated in units of K; K = 0.007434 l_P, omega_1 = 33.63 l_P^-1, pi/omega_1 = 0.0934 l_P, independent of the metre value"},
  {"quantity": "renormalisation scale mu (enters omega_2 through ln F / L0, footnote [20])", "value_then": "absorbed into f; not fixed", "value_now": "still not fixed: TSH gr-qc/9608036 p.3 (as read by hpscentre.py:122-124) -- 'an arbitrary parameter whose value cannot be fixed except by experiment'", "source_now": "gr-qc/9608036 via hpscentre.py:122-124", "moves_conclusion": "moves the VALUE of omega_2 (any 3 ln F + 4 as mu varies) but not the formula nor any tree conclusion (theorem (b) is stated for all 3L0+4 > 0)"},
  {"quantity": "far-zone fit a = 5.3, b = 25.5 (enters omega_2 only through ln F in the far zone)", "value_then": "5.3, 25.5 (HPS p.8, window unstated)", "value_now": "not converged in the tree's own window sweep (hpscentre.py:168-181); on HPS's fit with l in K, omega_2/omega_1 = 0.233 (l = 1e3), 0.209 (1e4), 0.198 (1e5); the fit's a ln l - b is negative for l < e^(25.5/5.3) = 122.9", "source_now": "computed, rederive T6", "moves_conclusion": "no -- omega_1 is independent of F; omega_2's formula is independent of (a, b)"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/gr-qc_9701064_omega.py",
  "outcome": "28 PASS / 0 FAIL (exit 0). Transcription of HPS (5)-(7) made afresh from the capture, NOT imported from hpscentre.py. T0 guard: of the four readings of (M1, M2) only (116, r^2) is covariantly conserved identically for arbitrary f(l), r(l), and its ln f coefficient vanishes on its own -- the transcription is right and agrees with hpscentre.py:156-165. T1: flat f = f0, r = l solves all three equations. T2 FAR ZONE (HPS's regime): plane wave phi = A e^{ikl}/l, rho = B e^{ikl} about F0 const, r = l, leading order in 1/l -> dispersion (s - 1)(3 L0 s + 4 s - 1) = 0, roots s = 16K^2 k^2 = 1 and 1/(3L0+4): exactly HPS's omega_1^2 = 1/16K^2, omega_2^2 = 1/16K^2(4+3 ln F). A probe (_scaling_probe.py) shows the 1/l scaling is forced: with phi O(1) the tt leading term is -16 A K^2 k^4 (L0+1) and the thth one A k^2 (16K^2(L0+2)k^2 - 1)/2, incompatible unless A = 0 (or L0 = -1, the case theorem (b) excludes). T3 CENTRE (the tree's regime): exact spherical modes phi = A sin(kl)/l, rho' = B(sin kl - kl cos kl)/l give the same dispersion; bare rho is absent; the modes A = -2B (omega_1) and A = 4B (omega_2) have exact zero residuals -- reproducing hpscentre.py:1407-1414 independently. T4: T2 and T3 identical under all four readings. T5: omega_1 follows from the trace alone, -R = 16K^2 box R_lin; with the box R coefficient rescaled to c, k_1^2 = 1/(16K^2 c). T6: K^2 = 1/(5760 pi) = 8 pi/(46080 pi^2); 16K^2 = 8 pi/(2880 pi^2); pi/omega_1 = 4 pi K; 2 pi/omega_1 = 8 pi K = RIPPLE_WINDOW_K; omega_2/omega_1 = 1/sqrt 2 at HPS's L0 = -2/3; adiabaticity |F'/F|/omega_1 = 3.8e-3 (l = 1e3 K), 1.8e-4 (1e4 K) on HPS's fit (l taken in K; HPS's unit for the fit is not stated). HPS's leading-order far-zone statement neglects terms of relative order K/l and F'/(F omega); not computed beyond leading order here.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Anderson, Molina-Paris, Mottola, gr-qc/0209075 (PRD 67, 024026, 2003)", "effect": "contested", "what": "pp.4-5, 7: the fourth-order terms needed to renormalise the semiclassical equations produce a class of solutions 'which become singular' as the higher-derivative coefficients go to 0 and 'vary on Planck length and time scales'; 'There is clearly no experimental basis for taking these solutions seriously'; order-reduction prescriptions [47, 48] eliminate them. HPS's omega_1 = 1/(4K) diverges as K -> 0 and its wavelength 8 pi K = 0.187 l_P: the ripples are of exactly that class. This contests the PHYSICAL standing of the modes in semiclassical gravity; it does not touch the computation of omega_1, omega_2 in HPS's model system, which is what the tree uses.", "read_status": "READ (alphaXiv capture of gr-qc/0209075v1 held at d67/amm_0209075.txt, pp.4-5 and 7 read in this stage)"},
  {"ref": "GMMPS, arXiv 2604.01047 (semiclassical Einstein-Klein-Gordon, linearised about Minkowski)", "effect": "extends", "what": "sec. 5.1 (p.59): 'b_2 is a free parameter which depends on the renormalisation constant alpha~^S_3' -- the coefficient of the box^2 term in the linearised equation is a free renormalisation constant. That is the constant whose value fixes omega_1 (T5: k_1^2 = 1/(16K^2 c)); HPS's value is the AHS-implicit one. Extends the named hypothesis H7; no contradiction of HPS's computation.", "read_status": "READ-VIA-RESTATEMENT: quoted verbatim in the sibling audit d67/audits/2604.01047_dispersion-s-tt.json (graded STANDS there) and in linstab.py:141, 176; not re-read in this stage"},
  {"ref": "Parker & Simon, 'Einstein equation with quantum corrections reduced to second order', gr-qc/9211002, PRD 47, 1339 (1993)", "effect": "contested", "what": "order reduction: physically relevant solutions satisfy reduced equations with no higher than second derivatives; under that prescription HPS's Planck-scale ripple modes would not be retained. Predates HPS (1993), so it was available to them.", "read_status": "NAMED-NOT-READ (title and summary from a web search result only; arxiv.org refused by the proxy; alphaXiv quota exceeded)"},
  {"ref": "discover_papers (this stage)", "effect": "narrows", "what": "The required discover_papers call returned 'alphaXiv assistant quota exceeded'. A WebSearch substitute ('Hochberg Popov Sushkov self-consistent wormhole ... ripples reexamined') returned only HPS itself and unrelated self-sustained-wormhole papers: no paper found that re-derives or contradicts omega_1, omega_2. This is an absence of a find, not evidence of absence.", "read_status": "NOT-READ (search only)"}
 ],
 "lacked_data": "M's hypothesis for this result. WHAT HPS HAD (1996-97): the AHS analytic approximation for <T> (PRD 51 4337, 1995), no exact <T> on their metrics, their own Runge-Kutta numerics, and the pre-existing order-reduction literature (Simon 1990-91; Parker-Simon 1993, NAMED-NOT-READ). WHAT CAME LATER: (a) AHL gr-qc/9504019 (1995, roughly contemporaneous) showing AHS's approximation misbehaves near horizons; (b) Popov hep-th/0302039 (2003) establishing that the AHS form is derived only for asymptotically flat spacetimes, which HPS's metric is not (both as read by hpscentre.py:118-129); (c) AMM gr-qc/0209075 (2002, READ) classing Planck-scale higher-derivative solutions as physically untrustworthy; (d) GMMPS 2604.01047 (2026, via restatement) making explicit that the box^2 coefficient is a free renormalisation constant. DOES ANY OF IT CHANGE THIS CONCLUSION? No, for the conclusion as stated: omega_1^2 = 1/16K^2 and omega_2^2 = 1/16K^2(4+3 ln F) are properties of the model system G = 8 pi <T>_AHS, and they re-derive exactly here in both regimes and under every reading of the disputed printed slots; no datum enters except the pure number K^2, which has not moved. What the later work changes is the PHYSICAL reach, and it does so as named hypotheses, not as errors: omega_1's value (and whether it oscillates at all) rests on the finite R^2 coupling (H7), omega_2's value on the unfixed mu (H3), and the modes belong to the Planck-scale class AMM say cannot be trusted. Evidence against 'the classic was wrong': none found -- the computation stands. Evidence for 'they lacked data': the renormalisation freedom and the domain of AHS were not stated by HPS and are now explicit; this narrows what the ripples mean, not what they are in the model.",
 "grade": "STANDS",
 "grade_evidence": "As the tree uses it -- HPS's omega_1, omega_2 as properties of HPS's model system, recovered at a regular centre by linearising about flat space (hpscentre.py:51-56, 1407-1414) and used for the ripple spacing pi/omega_1 = 4 pi K (:206) and RIPPLE_WINDOW_K = 8 pi (:264) -- the published statement is READ verbatim (p.8), the far-zone dispersion re-derives from an independent transcription of HPS (5)-(7) at leading order in 1/l, the centre dispersion re-derives with exact zero residuals, the two are the same polynomial, and all of it is reading-independent (T4), so the tree's 'conserved reading' restriction is stronger than needed. No datum moves: K^2 is a pure number (T6). Recorded, not repaired: (i) footnote [20]'s mu absorption is not carried at the omega site (named at hpscentre.py:116, qeihps.py:143); omega_2 is a mu-family and CENTRE_L0 = 0 is a mu choice -- no tree conclusion moves because theorem (b) is stated for all 3L0+4 > 0; (ii) the finite R^2 coupling behind omega_1 (T5) is named by neither HPS nor hpscentre.py (the tree names the free constants at linstab.py:141, 176); (iii) 'two ripple periods' at hpscentre.py:264 means two extremum spacings = one omega_1 period; (iv) AMM contest the physical standing of Planck-scale modes -- the tree already keeps O5 OPEN and never claims the modes inside the established domain. (v) The PRL journal text is unread; the grade is on the arXiv v1 text layer.",
 "what_would_change_the_grade": "NARROWED if a downstream use (O5, specthm R7) quotes omega_1 or the ripple as a property of the conformal scalar in semiclassical gravity rather than of HPS's model system with AHS's implicit R^2 coupling and HPS's absorbed mu; or if the PRL journal text prints different frequencies from the arXiv v1 text layer (then a DISCREPANCY to record). WRONG only on a computed contradiction: e.g. a next-to-leading far-zone expansion showing HPS's leading-order form fails at the l the tree uses -- the tree measures the spacing to 1 % at l in [50 K, 1e4 K], consistent with leading order. OPEN would apply to any claim about the modes in exact semiclassical gravity, which nothing here reaches.",
 "reverify_command": "python3 " + D + "/rederive/gr-qc_9701064_omega.py   (expect 'SUMMARY: 0 FAIL', exit 0, several minutes); python3 " + D + "/rederive/_scaling_probe.py (amplitude-scaling probe); cd /home/user/Claude-Method-Works/research/warp-drive && sed -n 51,59p hpscentre.py && sed -n 1407,1414p hpscentre.py && sed -n 262,265p hpscentre.py; grep -n -A3 'frequencies' " + D + "/src/hps/hps_0.xml",
 "report_path": D + "/audits/gr-qc_9701064_omega.json"
}
json.dump(R, open(D + "/audits/gr-qc_9701064_omega.json", "w"), indent=1)
print("ok")
