import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
r={
"key":"epstein-glaser-jaffe-1965",
"name":"Epstein-Glaser-Jaffe (1965): nonpositivity of the energy density in Wightman QFT -- as used by the tree: 'no pointwise lower bound on rho(x)'",
"source":{
 "located":"H. Epstein, V. Glaser, A. Jaffe, 'Nonpositivity of the energy density in quantized field theories', Nuovo Cim. 36 (1965) 1016-1022 -- not on arXiv. Read through: C.J. Fewster, math-ph/0501073 ('Energy inequalities in QFT', XIV ICMP) pp.2-3 and Appendix A pp.10-12; C.J. Fewster, arXiv:1208.5399 ('Lectures on QEIs') pp.7-9, 11; E.-A. Kontou & K. Sanders, arXiv:2003.01815 pp.17-18 (Thm 3.1, 3.2), p.22; L.H. Ford & T.A. Roman, gr-qc/9607003 p.2 (intro) and ref.[2] p.16; D. Cadamuro, arXiv:1912.11102 pp.2-5.",
 "read_status":"READ-VIA-RESTATEMENT",
 "via":"The 1965 original is NAMED-NOT-READ. Its theorem is READ as restated with proof in Fewster math-ph/0501073 p.2 ('In 1965, Epstein, Glaser and Jaffe proved that the energy density in any Wightman field theory necessarily admits negative expectation values (unless it is trivial)'), Kontou-Sanders 2003.01815 Thm 3.2, and Fewster 1208.5399 p.8. Whether the 1965 paper ALSO states unboundedness is not determinable here: Ford-Roman attribute the 'unboundedly negative at a spacetime point' fact to EGJ (ref.[2]); Fewster and Kontou-Sanders attribute only nonpositivity to EGJ and derive unboundedness separately."
},
"published_statement":"As restated (Kontou-Sanders 2003.01815 p.18, Thm 3.2, verbatim): 'Let A in A(O) be a self-adjoint local operator of a QFT such that <psi|A psi> >= 0 for all psi in the domain of A. Suppose <Omega|A Omega> = 0. Then A == 0.' Preceding sentence p.17: EGJ 'proved that non-positivity is necessary for any (non-vanishing) Wightman field in Minkowski space with vanishing vacuum expectation values.' Fewster math-ph/0501073 p.2: 'Epstein, Glaser and Jaffe proved that the energy density in any Wightman field theory necessarily admits negative expectation values (unless it is trivial).' UNBOUNDEDNESS is a separate result, Fewster math-ph/0501073 p.3: 'We may pursue this line of reasoning a little further IF we may assume that the vacuum admits a nontrivial scaling limit for T with positive canonical dimension ... It then follows from Eq. (5) that the expectation value of T at a point (if it exists) is unbounded from below as the state varies in D' (proof in Appendix A, eq.(36)); for the free field, Fewster 1208.5399 p.8: 'By a scaling argument [18] it may be shown that the expectation value of :Phi^2: at a point is unbounded from below as the state varies among Hadamard states.' Ford-Roman gr-qc/9607003 p.2 sentences 1-3: 'In quantum field theory, unlike in classical physics, the energy density may be unboundedly negative at a spacetime point. Such situations entail violations of all the known classical pointwise energy conditions ... This fact has been known for quite sometime [2]' with [2] = EGJ.",
"published_hypotheses":[
 "H1 Wightman framework in Minkowski space: Hilbert space, dense invariant domain D, vacuum Omega, operator-valued distribution T(f) (Fewster math-ph/0501073 p.2; Kontou-Sanders p.17).",
 "H2 Reeh-Schlieder property: no nonzero local observable T(f) annihilates the vacuum (Fewster p.2; Kontou-Sanders Thm 3.1).",
 "H3 Vanishing vacuum expectation value <Omega|T(f) Omega> = 0 (vacuum as zero of energy); otherwise apply to T(f) - <T(f)>_Omega (Fewster p.2).",
 "H4 The field is nontrivial (T(f) != 0 for nontrivial f).",
 "H5 (for UNBOUNDEDNESS ONLY, not EGJ) the vacuum admits a nontrivial scaling limit for T with positive canonical dimension and nontrivial limiting two-point function (Fewster math-ph/0501073 p.3, Appendix A, following Fredenhagen-Haag 1987); or, for free fields, the explicit scaling over Hadamard states (Fewster 1208.5399 p.8).",
 "H6 (for 'at a point') the pointwise expectation value exists -- 'if it exists' (Fewster p.3); for free fields this is the class of Hadamard states, where <T_00(x)> is smooth (Kontou-Sanders p.19)."
],
"hypothesis_drift":[
 "ADDED CONCLUSION / DROPPED HYPOTHESIS -- bounds.py:232-233: 'F1 POINTWISE rho(x) at a spacetime point. NO lower bound exists (Epstein-Glaser-Jaffe).' EGJ as restated proves NONPOSITIVITY (some state has <rho> < 0), not unboundedness. 'No lower bound' needs H5 (scaling limit of positive canonical dimension, or the free-field scaling argument) and H6 (pointwise value exists), neither named at the site. The rederivation's C3 exhibits the gap: an observable with <Omega,A Omega> = 0 and A Omega != 0 that is nonpositive yet bounded below.",
 "SAME DRIFT -- achievable.py:320-321: 'no pointwise cap on |rho| exists at all (Epstein-Glaser-Jaffe 1965 ...)'. Attributes unboundedness to EGJ without H5/H6.",
 "QUOTE-ATTRIBUTION DISCREPANCY (not a refutation) -- achievable.py:199-203 and 321: 'the first line of their introduction is \"the energy density may be UNBOUNDEDLY NEGATIVE at a spacetime point\" (Epstein, Glaser and Jaffe ...)' / 'quoted in gr-qc/9607003's first line'. The first line is verbatim correct (gr-qc/9607003 p.2), but it carries no citation; EGJ is cited as [2] on the THIRD sentence ('This fact has been known for quite sometime [2]'), and gr-qc/9607003 does not quote EGJ. The attribution of 'unboundedly' to EGJ is Ford-Roman's, and two later restatements (Fewster, Kontou-Sanders) do not make it.",
 "DROPPED HYPOTHESES H1-H3 -- bounds.py:232-233 names only 'pointwise energy density in QFT'; achievable.py names the framework only implicitly (canonical entry: 'Wightman framework, not restated by owner'). Minkowski space and vanishing VEV (or difference/normal-ordered density) are not named; in curved space or with boundaries the statement is about the difference from a reference state (Fewster math-ph/0501073 p.3 on 'difference QWEIs').",
 "NO drift toward a stronger use elsewhere: the tree does NOT claim EGJ bounds or refutes time-averaged (F2) or ball (F3) functionals; F3's unboundedness is correctly carried to Ford-Helfer-Roman gr-qc/0208045 in bounds.py, not to EGJ."
],
"data_at_publication":[],
"rederivation":{
 "method":"sympy",
 "script_path":D+"/rederive/epstein-glaser-jaffe-1965.py",
 "outcome":"13/13 PASS, exit 0. C1a (sympy, general 2x2 PSD) and C1c (numeric, 2000 random PSD, 0 violations of |B O|^2 <= |B| <O,B O>): the EGJ core step, positivity + zero VEV => A Omega = 0. (C1b is true by construction and only a sanity check.) C2a-c (sympy): Fewster math-ph/0501073 eqs.(3)-(5) re-derived exactly -- <psi_a|A psi_a> = zeta sin2a + eta(1-cos2a), minimum eta - sqrt(eta^2+zeta^2) < 0 for zeta > 0. C3: nonpositive-but-bounded-below example (eigenvalues -1, +1) -- nonpositivity does not entail 'no lower bound'. C4 (sympy, exact truncated Fock space, massless scalar box mode): <:T00:(0)> in cos a|0> + sin a|2> = (omega/V) s(2s - sqrt2 c); minimum over a = (2 - sqrt6) omega/(2V) = -0.449490 omega/(2V), linear in omega, -> -inf as omega -> inf: pointwise unboundedness holds for the free field. C5: the Lorentzian average (width t0) damps the cross term by exp(-2 omega t0) (sympy integral), and the same state family then has a finite worst case (-0.022040 at V = t0 = 1) -- the bound lives in the functional, consistent with F1 vs F2 in bounds.py.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"C.J. Fewster, math-ph/0501073 (2003/2005)","effect":"narrows","what":"Gives EGJ as NONPOSITIVITY in any Wightman theory and proves unboundedness at a point only under an added hypothesis: a nontrivial scaling limit of positive canonical dimension (Appendix A, eq.(36)). 'in many models, the energy density is in fact unbounded from below' (p.2) -- many, not all.","read_status":"READ (pp.1-3, 10-12)"},
 {"ref":"C.J. Fewster, arXiv:1208.5399 (2012)","effect":"confirms","what":"Same split: EGJ = loss of positivity for Wightman fields with vanishing VEV (p.8); pointwise unboundedness of :Phi^2: for the free field by a scaling argument (p.8); 'no possibility of insisting on pointwise energy conditions in QFT' (p.9).","read_status":"READ (pp.7-11)"},
 {"ref":"E.-A. Kontou & K. Sanders, arXiv:2003.01815 (2020)","effect":"confirms","what":"Thm 3.2 restates EGJ (positivity + zero VEV => A = 0) with the Reeh-Schlieder proof; p.22 cites pointwise unboundedness as 'the fact' without attributing it to EGJ.","read_status":"READ (pp.17-24)"},
 {"ref":"D. Cadamuro, arXiv:1912.11102 (2019); Bostelmann-Cadamuro PRD 93 065001 (2016); Bostelmann-Cadamuro-Fewster PRD 88 025019 (2013)","effect":"extends","what":"In interacting integrable models (Ising, sinh-Gordon) negative energy density occurs even in ONE-PARTICLE states (p.2, p.4 Prop. 4.1), i.e. nonpositivity is more pervasive with interaction; state-independent worldline QEIs still hold for massive Ising. Nothing here restores a pointwise lower bound.","read_status":"READ (1912.11102 pp.1-6); the 2013/2016 papers NAMED-NOT-READ"},
 {"ref":"L.H. Ford & T.A. Roman, gr-qc/9607003 (1997)","effect":"contested","what":"Attributes the 'unboundedly negative at a spacetime point' fact to EGJ (ref.[2]); the later reviews above attribute only nonpositivity to EGJ. The attribution, not the physics, is contested.","read_status":"READ (pp.1-4, 16)"}
],
"lacked_data":"M's hypothesis tested: EGJ is a theorem from axioms (Wightman, Reeh-Schlieder, zero VEV) with NO numerical input, so no measured datum -- then or now -- can move it; data_at_publication is empty because nothing is there to move. Negative energy density's observational support (Casimir 1948 prediction; squeezed light, Wu-Kimble-Hall-Wu PRL 57 2520 (1986), cited by Ford-Roman p.2) is consistent with it and was not needed by it. What the 1965 authors lacked was MATHEMATICAL, not empirical: the scaling-limit theory (Fredenhagen-Haag 1987) that Fewster uses to turn nonpositivity into pointwise unboundedness, and the QEI programme (Ford 1978 onward) that separated pointwise (F1) from worldline (F2) functionals. Having it NARROWS what EGJ alone may be cited for (nonpositivity) and SUPPLIES the unboundedness under H5; it does not overturn anything. Evidence either way: for M's hypothesis -- none (no datum, no counterexample); against -- the re-derivation C1-C2 reproduces the theorem from its hypotheses, and C4 reproduces pointwise unboundedness in the free field the board uses.",
"grade":"NARROWED",
"grade_evidence":"The theorem itself STANDS as restated (C1, C2 re-derive it; no later work contradicts it). The tree's USE is narrower than it writes: bounds.py:232-233 and achievable.py:320-321 cite EGJ for 'NO lower bound' / 'no pointwise cap at all', but EGJ (per Fewster math-ph/0501073 p.2 and Kontou-Sanders Thm 3.2) delivers only nonpositivity; pointwise unboundedness requires the dropped hypotheses H5 (scaling limit with positive canonical dimension, or the free-field scaling argument) and H6 (pointwise value exists, e.g. Hadamard states). C3 shows nonpositivity alone does not imply unboundedness. On the class the board actually works in -- free scalar/EM fields in Minkowski, Hadamard states -- the tree's conclusion is TRUE (C4: minimum (2 - sqrt6) omega/(2V) -> -inf). Downstream: ledger W1 and the F1/F2/F3 separation are UNAFFECTED, because W1's withdrawal rests on Ford-Roman being a time average at one point (wrong functional), which holds whether or not a pointwise cap exists; and the free-field unboundedness the board needs is re-derived here. A theory with no scaling limit of positive dimension is a class where 'no pointwise lower bound' is NOT established by anything read here -- OPEN on that class, not refuted. The Ford-Roman 'first line' attribution is a citation discrepancy, recorded, not a refutation.",
"what_would_change_the_grade":"To STANDS: reading the 1965 Nuovo Cimento paper itself and finding an unboundedness statement proved under the Wightman axioms alone (Ford-Roman's attribution would then be exact, and H5 unnecessary), or the owner sites re-worded to cite EGJ for nonpositivity and Fewster math-ph/0501073 (scaling limit) / the free-field scaling argument for unboundedness. To WRONG: only a Wightman-class theory, of the kind the board uses (free fields, Hadamard states), exhibiting a finite pointwise lower bound on <T_00(x)> -- excluded for the free field by C4. To OPEN: nothing short of losing all restatements.",
"reverify_command":"python3 /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/rederive/epstein-glaser-jaffe-1965.py  # expect 13 PASS, exit 0; sources: alphaXiv answer_pdf_queries on math-ph/0501073 (p.2-3, App. A), 1208.5399 (p.8), 2003.01815 (p.17-18), gr-qc/9607003 (p.2, ref [2]); owner sites: grep -n 'Epstein' /home/user/Claude-Method-Works/research/warp-drive/bounds.py /home/user/Claude-Method-Works/research/warp-drive/achievable.py",
"report_path":D+"/audits/epstein-glaser-jaffe-1965.json"
}
json.dump(r,open(r["report_path"],"w"),indent=1)
print("ok")
