import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R = {
"key": "gr-qc/0003025-anec-cases",
"name": "Barcelo-Visser: for xi > 0 with phi^2 < kappa/xi everywhere the ANEC is satisfied (case 2); only phi^2 > kappa/xi somewhere (case 3) admits ANEC violation",
"source": {
 "located": "C. Barcelo & M. Visser, 'Scalar fields, energy conditions, and traversable wormholes', arXiv:gr-qc/0003025v2 (14 Jul 2000; dated 7 March 2000), Class. Quant. Grav. 17 (2000) 3843-3864. Sect. 2.1 eqs.(2.1)-(2.3) p.3-4 (kappa = 1/(8 pi G_N), action, T_eff); sect. 2.3 eqs.(2.7)-(2.11) and cases 1-3, pp.5-6; sect. 4 p.16 ('~ m_p/sqrt(xi)', footnotes 4-5); sect. 5 eq.(5.51) p.19 (physical Newton constant).",
 "read_status": "READ",
 "via": "alphaXiv answer_pdf_queries(gr-qc/0003025) returned page text pp.1-6,10,16-19,21-23 this stage; cross-checked line by line against the workflow's cached full text src/gr-qc_0003025.txt (65,298 bytes, header 'arXiv:gr-qc/0003025v2 14 Jul 2000'). Secondary reads: Bezrukov-Shaposhnikov arXiv:0710.3755v2 pp.1-5 (alphaXiv, this stage); Atkins-Calmet arXiv:1211.0281v2 pp.1-8 (alphaXiv, this stage); Fliss-Freivogel-Kontou-Pardo Santos arXiv:2309.10848v1 sect. II B-C and V (cached text src/2309.10848.txt)."
},
"published_statement": "BV p.5-6, sect. 2.3: I(l1,l2) = INT [T_eff]_mn k^m k^n dl (2.7) = INT kappa/(kappa - xi phi^2) [ (dphi/dl)^2 - 2 xi d/dl(phi dphi/dl) ] dl (2.8) = INT kappa[kappa - xi(1-4xi)phi^2]/(kappa - xi phi^2)^2 (dphi/dl)^2 dl - {2 xi kappa/(kappa - xi phi^2) (phi dphi/dl)}|_{l1}^{l2} (2.10). 'Discarding the boundary terms is an issue fraught with subtlety: We start by considering a complete null geodesic and assuming sufficiently smooth asymptotic behaviour. Then the boundary terms from asymptotic infinity can be neglected, and the only potential problems with the boundary terms come from the places l_i where kappa = xi phi(l_i)^2' (2.11). '1. If xi < 0 ... the integrand in the above formula is itself guaranteed positive so ANEC is satisfied. 2. If xi > 0, but we have (phi)^2 < kappa/xi, then again there are no places on the geodesic where kappa = xi[phi(l)]^2. Furthermore the integrand appearing above is again positive and ANEC is satisfied. 3. Finally, if xi > 0, and we have at least some places where (phi)^2 > kappa/xi ... The boundary terms can no longer be neglected and potentially can contribute -- typically making negative and infinite contributions to the ANEC integral. Furthermore the integrand appearing above is no longer guaranteed to be positive. (If xi in (0,1/4) then it is possible to have (phi)^2 > kappa/[xi(1-4xi)] and so make the integrand negative.) In short: there is definitely the possibility of ANEC violations under these conditions.' p.3: 'kappa = 1/(8 pi G_N)'; S = 1/2 INT sqrt(-g) kappa R + INT sqrt(-g)(-1/2 (d phi)^2 - V(phi) - 1/2 xi R phi^2) (2.1). p.16: 'In all these solutions the scalar field has to reach absolute values above ~ m_p/sqrt(xi), where m_p is the Planck mass.'",
"published_hypotheses": [
 "classical (not quantised) single real scalar field, action (2.1), signature (-,+,+,+), conformal coupling at xi = +1/6 in this convention (effective gravitational coefficient kappa - xi phi^2)",
 "kappa = 1/(8 pi G_N) is the BARE coefficient in (2.1); the physical Newton constant is G_phys = (1/8pi) (1/(kappa - xi phi_inf^2)) (4+2w)/(3+2w)|_asymp (eq. 5.51, massless-scalar Brans-Dicke form)",
 "arbitrary potential V(phi): it drops out of T_eff k k because g_mn k^m k^n = 0",
 "the ANEC is evaluated on the EFFECTIVE stress tensor T_eff of (2.3), the one with kappa G_mn = T_eff, not on T of (2.2)",
 "a COMPLETE null geodesic, affinely parametrised",
 "'sufficiently smooth asymptotic behaviour' so the boundary terms at infinity vanish",
 "case 2 requires phi^2 < kappa/xi along the whole geodesic (strict); case 3 is phi^2 > kappa/xi at some point; the marginal set (phi^2 <= kappa/xi with equality somewhere) is in neither case",
 "case 3 is a POSSIBILITY of violation, not a theorem that it occurs; violation is exhibited only in specific exact solutions of sect. 4 (static, spherically symmetric, massless)",
 "no static/spherical ansatz is used in sect. 2.3 -- that restriction enters only in sects. 3-4"
],
"hypothesis_drift": [
 "DROPPED (named nowhere at the use site): 'complete null geodesic + sufficiently smooth asymptotic behaviour' so that boundary terms at infinity vanish -- higgs.py:124-127 and flag higgs.py:220 state case 2 as 'ANEC is satisfied' without it. It is LOAD-BEARING: rederive D2 exhibits a case-2 profile (phi = 0.05 lam, xi = 1, xi phi^2 <= 0.0025 kappa) whose integral over the finite segment [0,1] is -0.0025 < 0. The tree's use is in a topological-censorship context (higgs.py:124) whose own theorem supplies complete geodesics in an asymptotically flat spacetime, so the drop does not change the tree's verdict, but the hypothesis should be named.",
 "DROPPED: the ANEC in BV is the ANEC of T_eff (2.3), the tensor sourcing kappa G_mn, not of T (2.2). higgs.py:124-127 says only 'ANEC'. Harmless for the topological-censorship use (which is geometric, R_mn k k), but an unnamed hypothesis.",
 "ADDED (not in the source for this result): the canonical entry lists 'BV's static spherically symmetric wormhole ansatz' as a hypothesis of the cases. Sect. 2.3 uses no ansatz; the cases hold for any configuration satisfying the hypotheses above. The addition makes the tree's hypothesis list narrower than the source's, never broader -- no over-claim results.",
 "EXTENDED without statement: higgs.py:116 applies BV to 'xi H^dagger H R', a complex doublet (four real fields); BV treat one real field. rederive C1-C3 shows the identity and case-2 positivity carry over exactly to an O(4)-symmetric multiplet with rho = sum phi_a^2 (bulk = kappa/(kappa - xi rho) sum phi_a'^2 + kappa xi^2 rho'^2/(kappa - xi rho)^2, both terms non-negative when kappa - xi rho > 0). The extension HOLDS; it is recorded because the tree does not state it.",
 "SIGN-CONVENTION DRIFT at higgs.py:149-151, 213, 471-482, 634-639: the tree compares BV's xi > 0 gate with Higgs inflation's 'xi ~ 1.7e4' ('TWENTY-EIGHT ORDERS BELOW'). READ at source: Bezrukov-Shaposhnikov 0710.3755 footnote 1, 'In our notations the conformal coupling is xi = -1/6', action -(M^2 + xi h^2)R/2 (eq. 2), Omega^2 = 1 + xi h^2/M_P^2 (eq. 3): their effective Planck mass GROWS with h. In BV's convention (conformal = +1/6, effective coefficient kappa - xi phi^2) Higgs inflation's coupling is xi_BV = -xi_BS ~ -1.76e4 (rederive F6), i.e. BV CASE 1: ANEC satisfied at every field value, no gate at all. Atkins-Calmet 1211.0281 eq.(6) uses the same sign as BS. The tree's comparison is therefore between quantities of opposite sign. This STRENGTHENS the tree's verdict (the Higgs-inflation coupling cannot open the gate at any field value) but the figure 'twenty-eight orders below' compares |xi| across a sign flip and is a discrepancy, recorded, not repaired.",
 "FIELD-VALUE DRIFT at higgs.py:141-143 ('Put the Higgs VEV into their condition ... phi > M_reduced/sqrt(xi) i.e. xi > (M_reduced/v)^2') and higgs.py:513 ('a line the field cannot leave'): BV's case-3 condition is on the field ANYWHERE on the geodesic, not on the vacuum value. The 'i.e.' substitutes phi = v. BS 0710.3755 p.3 (READ) puts the Higgs at h_COBE ~ 9.4 M_P/sqrt(xi) during inflation -- above the gate magnitude M_P/sqrt(|xi|) (rederive: 1.73e17 vs 1.84e16 GeV). So the Higgs field is not confined to v; what keeps Higgs inflation out of case 3 is the sign (previous item), not the field value. 'The field cannot leave' is the tree's premise, not BV's.",
 "KAPPA DRIFT at higgs.py:141-147, 390-397: the tree sets BV's kappa = M_reduced^2 from the MEASURED G while also putting phi = v in the vacuum. BV eq.(5.51) (READ, p.19) makes the measured Newton constant 1/(8pi(kappa - xi phi_inf^2)) (times a Brans-Dicke factor that applies to a massless scalar's long-range force; the 125 GeV Higgs force is Yukawa-cut). With G fixed by measurement in the phi = v vacuum, kappa = M_red^2 + xi v^2 and the case-3 condition becomes phi^2 > v^2 + M_red^2/xi: the vacuum sits BELOW the gate at every xi > 0 (rederive F7, exact). The two gates agree to 8.7e-29 relative at xi = 1.7e4 (F8) and differ by O(1) only at xi ~ 1e30-1e33 (at xi_required: consistent gate = sqrt(2) v = 348.2 GeV, not v). xi_required = (M_red/v)^2 is exactly the point where kappa_bare - xi v^2 = 0 if kappa_bare = M_red^2 -- the induced-gravity point of Atkins-Calmet eq.(7) ('xi <= M_P^2/v^2 ~ 1e32') -- so the hierarchy IDENTITY (higgs.py:641-644) is exact as arithmetic, but its reading as 'the xi that brings the gate down to v' does not survive a consistent kappa. No verdict of the tree moves: that region is excluded by data (next section).",
 "FAITHFUL: the quotation at higgs.py:125-127 matches BV p.6 case 2 verbatim; 'everywhere' is implied by BV's case split; 'admits' (not 'entails') correctly carries BV's 'possibility'. The 'Only case 3' claim relies on BV's split omitting the marginal touching set; rederive E1 shows that set gives a positive non-integrable divergence (+4 kappa/(lam - lam0)^2), not a violation, so 'only case 3' survives it.",
 "INCIDENTAL (belongs to key gr-qc/0003025-eq2.6-minimal-scalar-nec, not graded here): BV sect. 2.2 prose says 'for xi > 0 and |phi| small ... any local MAXIMUM of phi^2 violates the NEC'; their own eq.(2.6) gives NEC numerator +2 xi b0 > 0 at a maximum and -2 xi b0 at a MINIMUM (rederive G1). FFK 2309.10848 eq.(18) text states the (2.6)-consistent version. higgs.py:121-122 reproduces the prose ('ANY LOCAL MAXIMUM OF phi^2 VIOLATES'). A misprint-class discrepancy; 'pointwise NEC violation is cheap' survives with max -> min."
],
"data_at_publication": [
 {"quantity": "G (enters kappa = 1/(8 pi G), M_red = 2.435323e18 GeV)", "value_then": "BV used no number (kappa symbolic; '~ m_p'). Tree: 6.67430e-11 (ladder.py:54)", "value_now": "6.67430(15)e-11 m^3 kg^-1 s^-2, CODATA 2022 identical to CODATA 2018", "source_now": "CODATA 2022 arXiv:2409.03787 Table XXXII / sect. XIV, as READ in sibling audit einstein-field-equations.json", "moves_conclusion": "No. +-1 sigma moves xi_required by -+2.20e-5 relative (rederive F: 9.782692e31 / 9.783122e31)."},
 {"quantity": "G_F (enters v = (sqrt2 G_F)^-1/2 = 246.2196 GeV)", "value_then": "not used by BV; tree 1.1663788e-5 GeV^-2 (higgs.py:209, NAMED-NOT-READ there)", "value_now": "1.1663788(6)e-5 (PDG 2024 Table 1.1); 1.1663787(6)e-5 (CODATA 2022); 1.16637859(59)e-5 (Eberhart et al. 2026, 2607.02657)", "source_now": "as READ in sibling audit fermi-constant-g_f-and-tree-level-vev.json", "moves_conclusion": "No. xi_required moves by -8.6e-8 / -1.8e-7 relative. (That sibling grades the tree-level v NARROWED vs the on-shell/MS-bar vev at the per-mille level -- irrelevant to a 16-order gap.)"},
 {"quantity": "which Planck mass sets the gate", "value_then": "BV p.16: '~ m_p/sqrt(xi), where m_p is the Planck mass' (loose); exact threshold kappa/xi with kappa = 1/(8 pi G) (p.3, p.6)", "value_now": "unchanged (definition)", "source_now": "BV itself", "moves_conclusion": "No. The tree's M_red is the exact kappa^(1/2); using BV's loose non-reduced m_p would give xi = (M_P/v)^2 = 2.4587e33 (x 8 pi) -- a factor, not a verdict."},
 {"quantity": "Higgs non-minimal coupling xi (the quantity the gate is on)", "value_then": "2000: 'completely unconstrained in the flat-space standard model' (BV p.18); Higgs not yet discovered", "value_now": "|xi| < 2.6e15 at 95% CL from the 2012 LHC signal strength mu = 1.07 +- 0.18 (Atkins-Calmet 1211.0281v2 p.5); the bound is on |xi| (the decoupling factor beta = 6 xi^2 v^2/M_P^2 is sign-blind)", "source_now": "arXiv:1211.0281v2 pp.1,4-5 (READ this stage). Current ATLAS/CMS combinations are NAMED-NOT-READ here.", "moves_conclusion": "No -- it confirms. xi_required = 9.78e31 is excluded by 16.6 orders; at the bound the consistent gate is phi > 4.78e10 GeV. Recomputing AC's figure from their stated inputs gives 2.54e15 (1.96 sigma two-sided lower mu) or 2.19e15 (1.645 sigma) against the printed 2.6e15: a small discrepancy in the bound's last digit, recorded, not adjudicated; it cannot move a 16-order margin."},
 {"quantity": "Higgs-inflation xi and its sign", "value_then": "tree: 1.7e4, 'Bezrukov-Shaposhnikov NAMED-NOT-READ' (higgs.py:213)", "value_now": "BS eq.(13): xi ~ 49000 sqrt(lambda) = 1.761e4 with m_h = 125.13, v = 246.2196 (rederive F); sign: BS conformal = -1/6, so xi_BV = -1.761e4", "source_now": "arXiv:0710.3755v2 p.1 footnote 1, eqs.(2),(3),(13) (READ this stage)", "moves_conclusion": "Magnitude: no. Sign: yes for the tree's comparison sentence (higgs.py:149-151) -- Higgs inflation is BV case 1, not 'twenty-eight orders below' the case-3 gate. The tree's verdict (no ANEC violation for the Higgs) is strengthened, not reversed."},
 {"quantity": "m_h (enters only the BS xi magnitude check; the gate has no m_h)", "value_then": "not used by BV", "value_now": "125.13 GeV (tree's captures/PDG-2026.tsv, READ by the tree)", "source_now": "higgs.py M_HIGGS", "moves_conclusion": "No; the xi gate carries no m_h (higgs.py's own selftest asserts it did not move)."}
],
"rederivation": {
 "method": "sympy",
 "script_path": D + "/rederive/gr-qc_0003025-anec-cases.py",
 "outcome": "29 checks, 0 FAIL (runtime ~1 s; sympy 1.14.0, z3 get_version_string 5.1.0). A1-A2 (sympy): for arbitrary phi(lam), the (2.8) integrand equals the (2.10) integrand minus d/dlam[2 xi kappa phi phi'/(kappa - xi phi^2)] -- BV's integration by parts is exact, sign of the boundary term as printed. B1-B5 (z3, all real kappa, xi, s): case 1 and case 2 coefficients strictly positive; for xi >= 1/4 positive for every s (any case-3 violation must come from crossing boundary terms); for 0 < xi < 1/4 a negative integrand exists (model kappa=1, xi=1/8, s=17) and only with s > kappa/xi. C1-C3: identity and case-2 positivity hold for an N=4 multiplet (Higgs doublet) and reduce to BV at N=1. D1: direct numerical integration of (2.8) with no integration by parts, phi = A sech(lam), max xi phi^2 = 0.9 kappa, xi in {1/6, 0.3, 5, 1e4}: I = 14.99, 11.88, 8.22, 7.98 > 0. D2: case-2 profile on a FINITE segment gives I = -0.00250 (leading order A^2(1-2xi)) -- the complete-geodesic/asymptotic hypothesis is load-bearing. E1: marginal touching set gives integrand ~ +4 kappa/(lam-lam0)^2, positive. F1-F4 reproduce the tree's data_used exactly (M_red 2.4353235e18, v 246.219640, xi_required 9.7829068836e31, v/M_red 1.0110346504e-16). F6: Higgs-inflation xi is negative in BV's convention. F7-F8 (exact Fractions): with kappa fixed by the measured G in the phi = v vacuum the gate is phi^2 > v^2 + M_red^2/xi, above v at every xi; identical to the tree's to 8.7e-29 at xi = 1.7e4. F9: LHC bound |xi| < 2.6e15 lies 16.6 orders below xi_required. G1 (incidental): BV sect. 2.2 prose max/min reversed relative to eq.(2.6).",
 "agrees_with_source": "yes"
},
"later_literature": [
 {"ref": "Fliss, Freivogel, Kontou, Pardo Santos, 'Non-minimal coupling, negative null energy, and effective field theory', arXiv:2309.10848v1 (2023)", "effect": "confirms", "what": "Sect. II B eqs.(19)-(20) re-derive BV's effective-ANEC integrand, 'where we discarded the boundary terms, assuming a smooth geodesic', 'non-negative for xi < 0 and xi > 1/4; for 0 < xi < 1/4 positive for small field values 8 pi xi(1-4xi)G phi^2 < 1', and conclude 'the self-consistent, effective, ANEC is only violated when we have large field values, an unphysical effect if we view non-minimal coupling as an EFT'. Their eq.(18) text also gives the (2.6)-consistent NEC max/min assignment (see incidental drift).", "read_status": "READ (cached full text src/2309.10848.txt, sect. II B-C lines 748-900, 1020-1050)"},
 {"ref": "Fliss, Freivogel, Kontou, Pardo Santos, arXiv:2309.10848v1 sect. V", "effect": "extends", "what": "Argue the non-minimally coupled theory is an EFT of states with bounded field values, phi_max^2 <~ (8 pi G |xi|)^-1 -- exactly BV's kappa/|xi| -- with breakdown of perturbative/semiclassical control in both frames at phi^2 ~ (8 pi G xi)^-1. So BV's case-3 region is also where the classical description is argued to fail. Also: 'While there is no relevant theorem, it is obvious that the violation of effective ANEC is needed to sustain long wormholes ... This point requires further consideration' -- a caution for the tree's 'A WORMHOLE NEEDS ANEC' (higgs.py:124), which is a different key.", "read_status": "READ (cached full text, lines 1034-1044, 4274-4320)"},
 {"ref": "Atkins & Calmet, 'Bounds on the non-minimal coupling of the Higgs boson to gravity', arXiv:1211.0281v2 (2013)", "effect": "confirms", "what": "First measured bound on the Higgs xi: |xi| < 2.6e15 (95% CL). Excludes the tree's xi_required = 9.8e31 by 16.6 orders, and identifies xi ~ M_P^2/v^2 ~ 1e32 as the induced-gravity point (their eq. 7), which is what the tree's xi_required is under a consistent kappa.", "read_status": "READ (alphaXiv, pp.1-8)"},
 {"ref": "Bezrukov & Shaposhnikov, 'The Standard Model Higgs boson as the inflaton', arXiv:0710.3755v2 (2008)", "effect": "narrows", "what": "Not a paper on BV, but the source of the tree's comparison value; READ here it shows the Higgs-inflation coupling has the sign opposite to BV's xi > 0 (conformal = -1/6), placing it in BV case 1, and that the Higgs field reaches ~9.4 M_P/sqrt(xi) during inflation (so the field is not confined to v). Narrows the tree's comparison sentence, not BV.", "read_status": "READ (alphaXiv, pp.1-5)"},
 {"ref": "Kontou et al., 'Wormhole restrictions from quantum energy inequalities', arXiv:2405.05963 (2024)", "effect": "extends", "what": "Surfaced by discover_papers as later work on wormhole restrictions; not read -- nothing is claimed from it.", "read_status": "NAMED-NOT-READ"}
],
"lacked_data": "M's hypothesis tested for THIS result. What BV had (2000): no numerical input at all -- sect. 2.3 is an identity (integration by parts) plus sign analysis, symbolic in kappa, xi, phi; the Higgs was undiscovered and its xi 'completely unconstrained' (BV p.18). What came later: (i) the Higgs discovery (2012) and the first measured bound |xi| < 2.6e15 (Atkins-Calmet 1211.0281); (ii) CODATA 2018/2022 G, unchanged; G_F refined at the 0.1-ppm level; (iii) FFK 2023's EFT analysis of the same integrand. Does any of it change the conclusion? No, by evidence both ways: the case analysis is data-free and re-derives exactly (sympy identity, z3 sign analysis, direct numerical integration), so no datum can move it; FFK independently re-derive and agree. The later data bear only on the TREE'S APPLICATION, and there they cut in the tree's favour, not against it: the measured bound excludes xi_required by 16.6 orders, and the Higgs-inflation coupling the tree cites sits in BV's case 1 (sign) where no gate exists. What the data do expose are two conventions the tree did not have to hand: the sign of xi across BV/BS/AC, and kappa bare-vs-measured (BV eq. 5.51). Neither is a datum 'previous physicists lacked'; both are bookkeeping in the tree's use. M's hypothesis is NOT supported for this result: nothing here was wrong for lack of data.",
"grade": "NARROWED",
"grade_evidence": "BV's result itself re-derives exactly: the (2.8)->(2.10) integration by parts is a sympy identity for arbitrary phi(lam); case-1/case-2 positivity and the confinement of integrand negativity to case 3 are z3-valid over all reals; direct numerical integration of (2.8) on complete geodesics in case 2 is positive at xi = 1/6, 0.3, 5, 1e4; the marginal touching set BV omit diverges positively; FFK 2309.10848 re-derive the same integrand and conclusion; no datum enters the case analysis. The tree's quotation (higgs.py:125-127) is verbatim. The grade is NARROWED, not STANDS, because the tree's use drops hypotheses BV state and that are shown load-bearing here -- complete null geodesic with asymptotic fall-off (a case-2 profile on a finite segment gives I = -0.0025, rederive D2), and ANEC of T_eff rather than T -- and because the use carries two convention drifts that are computed, not presumed: (a) Higgs inflation's xi ~ 1.7e4 is xi_BV ~ -1.76e4 (BS footnote 1, READ), BV case 1, so 'twenty-eight orders below' (higgs.py:149-151, 634-639) compares magnitudes across a sign flip; (b) with kappa fixed by the measured G in the phi = v vacuum (BV eq. 5.51) the case-3 condition is phi^2 > v^2 + M_red^2/xi, so xi_required = (M_red/v)^2 does not 'bring the gate down to v' (consistent gate there is sqrt2 v); the two gates agree to 8.7e-29 at xi = 1.7e4. NOT over-represented in either direction: none of this reverses the tree's verdict that the Higgs at its vacuum cannot reach BV's ANEC-violating case; every drift either leaves it unchanged or strengthens it (case 1 for the Higgs-inflation sign; the LHC bound |xi| < 2.6e15 excludes xi_required by 16.6 orders). The added 'static spherically symmetric ansatz' hypothesis in the canonical entry is not in sect. 2.3 and only narrows the tree's claim. The unstated doublet extension was checked and holds.",
"what_would_change_the_grade": "To STANDS: the tree names BV's complete-geodesic/asymptotic-fall-off and T_eff hypotheses at higgs.py:124-127/220, states the sign convention (xi_BV = -xi_BS) at the Higgs-inflation comparison, and either states kappa as the bare coefficient or uses the measured-G gate phi^2 > v^2 + M_red^2/xi. To WRONG: only a smooth configuration on a complete null geodesic with asymptotic fall-off, xi > 0 and phi^2 < kappa/xi everywhere, whose ANEC integral of T_eff is negative -- rederive B2 (z3) and A1 (sympy) show none exists. To DATA-DEPENDENT: a measurement placing the Higgs xi_BV > 0 at magnitude ~1e32, which the 2012 bound already excludes by 16.6 orders.",
"reverify_command": "python3 /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/rederive/gr-qc_0003025-anec-cases.py  # expect 'FAILS: 0', exit 0; source text: sed -n 540,815p /tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67/src/gr-qc_0003025.txt ; tree sites: sed -n '109,160p;205,222p;388,400p;625,645p' /home/user/Claude-Method-Works/research/warp-drive/higgs.py",
"report_path": D + "/audits/gr-qc_0003025-anec-cases.json"
}
json.dump(R, open(R["report_path"], "w"), indent=1, ensure_ascii=False)
print("written", R["report_path"])
