import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
r = {
 "key": "lemaitre-poisson-2019-gamma1",
 "name": "LeMaitre & Poisson (2019): original radial stability threshold Gamma_1 for the thin shell",
 "source": {
  "located": "P. LeMaitre and E. Poisson, 'Equilibrium and stability of thin spherical shells in Newtonian and relativistic gravity', Am. J. Phys. 87, 961-970 (Dec 2019), DOI 10.1119/10.0000026, arXiv:1909.06253 (located by WebSearch). LP2019 ITSELF WAS NOT READ: alphaXiv returned 'assistant quota exceeded' on answer_pdf_queries, get_paper_content and discover_papers; arxiv.org, export.arxiv.org, alphaxiv.org, pith.science, semanticscholar and link.springer.com are all refused by the egress proxy (403 / EGRESS_BLOCKED). Its content was read through the restating paper Pitre, Schneider & Poisson, arXiv:2604.05980v1 (Phys. Rev. D, dated April 8 2026; Poisson is a co-author of both), full text cached at d67/src/casmag/all/2604.05980v1.txt and read there: Sec. III Eqs (3.15)-(3.18) with footnote 1 (lines 752-825), Eqs (2.4)-(2.7) (lines 505-533), Sec. X Eq (10.17) (lines 955-975), reference [34] (line 1486). The restatement is NOT exact for LP's printed formula: footnote 1 states LP's Eq (34) uses a different adiabatic-index convention.",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "arXiv:2604.05980v1 (Pitre-Schneider-Poisson 2026), cached full text; LP2019's own Eq (34) is NAMED-NOT-READ"
 },
 "published_statement": "As restated in arXiv:2604.05980 Sec. III (READ): 'If we follow M(sigma) along the equilibrium sequence, taking into account that dp = Gamma(p/sigma) dsigma and dmu = [(mu+p)/sigma] dsigma, we find that dM/dsigma >= 0 whenever Gamma >= Gamma_1, where Gamma_1 := 3/2 + 4(p/mu) + 4(p/mu)^2 (3.16a) = (1 + 2 sqrt F + 3F)/(4F) (3.16b) = (4 - 6C + 2 sqrt(1-2C))/(4(1-2C)) (3.16c), where C := M/R ... The point along the sequence at which dM/dsigma = 0 is the configuration of maximum mass for the specified equation of state, and this point also marks the onset of a radial instability -- the shell becomes dynamically unstable against time-dependent, spherically-symmetric perturbations [34].' Footnote 1: 'The criterion appears to be different from the one given in Eq. (34) of Ref. [34]. The reason has to do with inequivalent definitions of the adiabatic index. In Ref. [34] it was defined as d ln p/d ln mu, whereas it is d ln p/d ln sigma here. To maximize confusion, mu was denoted sigma in Ref. [34].' Sec. X: 'It is known [34] that these equilibrium configurations are radially stable whenever Gamma >= 3/2' (Newtonian, Eq 10.17). So what LP2019 is credited with, at the restating source, is (i) the turning-point theorem 'maximum mass <=> onset of radial dynamical instability' for thin shells and (ii) a criterion in the d ln p/d ln mu convention (their Eq 34); the expression (3.16c) the tree quotes is Pitre et al.'s form in the d ln p/d ln sigma (rest-mass) convention.",
 "published_hypotheses": [
  "H1 infinitesimally thin, static, spherically symmetric shell (timelike hypersurface), Israel junction conditions",
  "H2 Minkowski interior (no interior mass) and Schwarzschild exterior of mass M",
  "H3 perfect-fluid surface matter, areal rest-mass density sigma, energy density mu, surface pressure p",
  "H4 barotropic equation of state mu = sigma + eps(sigma), p = p(sigma) (Pitre Eq 2.4; polytrope p = K sigma^Gamma in Eq 1.1 for the QNM work), isentropic: first law dmu = (mu+p)/sigma dsigma (Eq 2.5)",
  "H5 adiabatic index Gamma := (sigma/p) dp/dsigma (rest-mass convention, Eq 2.6); LP2019 Eq (34) instead uses d ln p/d ln mu (footnote 1)",
  "H6 the criterion as derived is the turning-point condition dM/dsigma >= 0 along the one-parameter equilibrium sequence; its identification with DYNAMICAL radial (spherically symmetric, time-dependent) stability is credited to LP2019 [34]",
  "H7 radial perturbations only; 2604.05980 itself shows l >= 2 even-parity non-radial instability for all sampled C and Gamma, which this threshold does not address",
  "H8 sequence assumed to start at low sigma with Gamma > Gamma_1 (Pitre text after 3.17)"
 ],
 "hypothesis_drift": [
  "ATTRIBUTION DRIFT (discrepancy, not refutation): wall.py:112 writes 'Gamma_1 = (4 - 6C + 2 sqrt(1-2C))/(4(1-2C)), C = M/R (LeMaitre-Poisson 2019)'; wall.py:444 'PINNED. LeMaitre-Poisson 2019 / Pitre et al Eq (3.16c)'; research/README.md:1081 and paper/CLAIMS.md:9016 (row S3) say the tree 'reproduces LeMaitre-Poisson's published Gamma_1'; index3.py:1820 'converts to LeMaitre-Poisson's Gamma_1'. Per the restating paper's footnote 1 (READ), LP2019's published criterion (Eq 34) is NOT this expression: it is written in the d ln p/d ln mu convention. The expression is Pitre et al. (3.16c). Computed here: in LP's convention the same threshold is Gamma_LP,1 = (3s^2+2s+1)/(s(3s+1)) = 2(2 - 3C + sqrt(1-2C))/(3 - 6C + sqrt(1-2C)) = 3/2 + 5C/8 + 33C^2/32 + ..., which differs from (3.16c) by the factor mu/(mu+p) (1.0295 at C = 0.1, 1.3090 at C = 0.4). This LP-convention form is PREDICTED from the physics, not read: LP's Eq (34) itself was not reachable.",
  "CONVENTION HYPOTHESIS: KEPT, not dropped. wall.py:113 states 'Their Gamma is d ln p/d ln sigma in the REST-MASS density' and wall.py:114-115 uses Eq (2.7) Gamma = beta^2 (mu+p)/p. This is the correct convention for (3.16c); it is the convention of Pitre et al., not LP2019. Anyone taking 'LeMaitre-Poisson's published Gamma_1' at its word and inserting LP's d ln p/d ln mu index into (3.16c) would err by the factor above; the tree does not do this.",
  "TURNING-POINT vs DYNAMICAL (H6): the published criterion is dM/dsigma >= 0 with dynamical meaning imported from LP2019. The tree does NOT rest on that import: wall.py:281-284 derives beta^2_crit from V''(R_0) = 0 of the shell's equation of motion (a dynamical criterion), so the tree's 'independent derivation, same answer' (wall.py:116-117) is a genuine cross-check of LP's turning-point <=> dynamical-onset claim on this configuration. Confirmed identically in s here (route B == route C).",
  "SCOPE (H2, H7): the tree applies the threshold only to 'exactly this configuration' (wall.py:110-111: Minkowski inside, Schwarzschild outside) and states at wall.py:119-131 that the non-radial l >= 2 mode is NOT reached by it. No scope widening found at the wall.py sites. (stability.py's M_in < 0 configuration uses a different criterion and is outside this key.)",
  "PRECISION CLAIM (tree sentence, not source; recorded by the sibling audit 2604.05980-radial-gamma1): wall.py:115-116 and README.md:1081-1082 claim agreement 'to 1e-15 at every x from 1e-6 to 0.8'; the sibling measured wall.gamma_crit vs 40-digit (3.16c) at 9.8e-11 max relative error at small x, from the naive (1-s) cancellation in wall.statics. wall.gamma1_published itself matches (3.16c) to 3.55e-16 here. A float-precision discrepancy in a tree sentence, not in the result."
 ],
 "data_at_publication": [
  {
   "quantity": "none -- no physical measurement enters",
   "value_then": "The threshold is a closed-form function of compactness C = M/R alone (geometric units G = c = 1); no measured constant, observation or fitted datum enters LP2019's criterion or Pitre's (3.16c).",
   "value_now": "unchanged (no datum)",
   "source_now": "n/a; derivation is from the Einstein equations via Israel junction conditions and the first law",
   "moves_conclusion": "no -- there is no datum to move"
  }
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/lemaitre-poisson-2019-gamma1.py",
  "outcome": "ALL PASS (21 checks). (A) Israel statics from the junction conditions: mu = (1-s)/(4 pi R), p = (1-s)^2/(16 pi R s), s = sqrt(1-2M/R). (B) Turning-point route: inverting (mu,p)->(M,R) and imposing dM/dsigma = 0 with Pitre's dp = Gamma p/sigma dsigma, dmu = (mu+p)/sigma dsigma gives a unique root Gamma_1 = 3/2 + 4q + 4q^2 (q = p/mu), equal to (3.16c) identically; dM/dsigma is increasing in Gamma so >= 0 iff Gamma >= Gamma_1. (C) Dynamical route, derived independently of the tree: V(R) = 1 - (M/m + m/2R)^2, m' = -8 pi R p, p' = beta^2 mu', mu' = -2(mu+p)/R; V(R0) = V'(R0) = 0; V''(R0) linear in beta^2 with unique root beta^2_crit = (1-s)(3s^2+2s+1)/(4s^2(1+3s)) = wall.beta2_crit; dV''/dbeta^2 > 0; converted by Eq (2.7) it equals (3.16c) identically in s. (D) In LP2019's d ln p/d ln mu convention the threshold is (3s^2+2s+1)/(s(3s+1)) = Gamma_1 mu/(mu+p), NOT (3.16c); both -> 3/2 Newtonian; (3.16c) = 3/2 + C + 7/4 C^2 + O(C^3) as Pitre (3.17). (E) wall.gamma1_published == (3.16c) with C = x/2 to 3.55e-16 over x in [1e-6, 0.8] (wall.py imported read-only, bytecode writing disabled; git status of research/ clean).",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {
   "ref": "T. Pitre, B. Schneider, E. Poisson, arXiv:2604.05980, Phys. Rev. D (2026), 'Self-gravitating thin shells are dynamically unstable on all angular scales'",
   "effect": "confirms",
   "what": "Re-states LP2019's radial result, converts it to the rest-mass index convention as (3.16a-c), credits LP2019 for max-mass <=> radial-instability onset and for Newtonian Gamma >= 3/2; and EXTENDS (i.e. narrows the physical reach of radial stability): an even-parity l >= 2 matter mode with purely imaginary positive frequency exists for all sampled compactness and Gamma, surviving the Newtonian limit, so radial stability is not stability.",
   "read_status": "READ (cached full text d67/src/casmag/all/2604.05980v1.txt, lines 1-40, 80-110, 505-545, 730-840, 955-990, 1480-1490)"
  },
  {
   "ref": "H. Yang, B. Bonga, U.-L. Pen, Phys. Rev. Lett. 130, 011402 (2023)",
   "effect": "extends",
   "what": "Per 2604.05980's abstract: an earlier dynamical-instability conclusion for thin shells in the eikonal (l >> 1) approximation. Non-radial; does not bear on the radial threshold.",
   "read_status": "NAMED-NOT-READ (known only from 2604.05980's abstract)"
  },
  {
   "ref": "'Thermodynamical and dynamical equilibrium/stability of a self-gravitating uncharged thin shell', arXiv:2006.06766, Eur. Phys. J. C (2020) 10.1140/epjc/s10052-020-8273-3",
   "effect": "contested",
   "what": "Title-level only: a later treatment of thermodynamic vs dynamical stability of the same kind of shell, surfaced by WebSearch; its relation to the LP threshold could not be read (arxiv.org and link.springer.com egress-blocked; alphaXiv quota exhausted). Effect set to 'contested' only because the schema requires a value; NO effect is claimed -- treat as UNREAD.",
   "read_status": "NAMED-NOT-READ (WebSearch title and URL only)"
  }
 ],
 "lacked_data": "M's hypothesis tested for this result: the LP2019 threshold uses NO physical data -- it is a closed-form consequence of the Einstein equations (via Israel junction conditions) and the first law for a barotropic, isentropic surface fluid, depending on the compactness C alone. There is therefore no datum the authors could have lacked; evidence: (a) both the turning-point route and the independent dynamical V''(R0) route reproduce (3.16c) identically in s (script checks B and C); (b) the Newtonian limit 3/2 and the series (3.17) are reproduced. What later work supplied is not data but scope: Pitre et al. 2026 showed the radial criterion is not the whole story (l >= 2 instability), which the tree already records at wall.py:119-131 and which is a separate key (2604.05980-nonradial-instability). The one thing 'lacking' found here is on the tree's side, not the authors': the tree attributes Pitre's rest-mass-convention form to LP2019, whose Eq (34) (per footnote 1 of the restating paper) is in the energy-density convention. Having LP's paper in hand would not change the conclusion; it would only fix the citation.",
 "grade": "STANDS",
 "grade_evidence": "The result the tree uses -- the radial stability threshold for a thin static shell, Minkowski inside and Schwarzschild outside, Gamma >= Gamma_1 = (4-6C+2 sqrt(1-2C))/(4(1-2C)) with Gamma = d ln p/d ln sigma -- is re-derived here by two independent sympy routes (turning point dM/dsigma = 0; dynamical V''(R0) = 0 converted by Pitre Eq 2.7), both identically equal to (3.16c); wall.gamma1_published equals (3.16c) to 3.55e-16; no datum enters, so none can move it; the tree keeps the rest-mass convention (wall.py:113) and the Minkowski/Schwarzschild scope (wall.py:110-111), and itself records the non-radial caveat. Recorded discrepancies, none of which is a refutation: (1) ATTRIBUTION -- wall.py:112, wall.py:444, README.md:1081, CLAIMS.md:9016 and index3.py:1820 call the (3.16c) expression 'LeMaitre-Poisson's published Gamma_1'; the restating paper's footnote 1 (READ) says LP's Eq (34) differs in form because it uses d ln p/d ln mu; the expression is Pitre et al. (3.16c) and LP's form is predicted here as Gamma_1 mu/(mu+p). (2) PRECISION -- the tree's '1e-15' agreement sentence is 9.8e-11 at small x for gamma_crit (sibling audit 2604.05980-radial-gamma1). Caveat on the grade: LP2019 itself was not read (alphaXiv quota exhausted; arXiv egress-blocked), so STANDS rests on computation plus the READ restatement by a co-author, not on LP's own page.",
 "what_would_change_the_grade": "Reading LP2019 (arXiv:1909.06253) Eq (34) directly: (a) if it equals (3s^2+2s+1)/(s(3s+1)) in its own convention, the attribution discrepancy is confirmed as a citation-form issue only and the grade stays STANDS; (b) if LP's dynamical-stability theorem carries a hypothesis absent from Pitre's restatement (e.g. a restriction on the class of equations of state, or on the sign of dGamma/dsigma along the sequence) that the tree's configuration violates, the grade would move to NARROWED -- but the tree's own V''(R0) derivation, confirmed here, does not depend on LP's theorem, so the tree's radial criterion would survive it; (c) a demonstrated error in the Israel statics (A) or the equation of motion V(R) (C) would be needed for WRONG, and both are re-derived here and match. A reader treating radial stability as full stability would be NARROWED by 2604.05980's l >= 2 mode -- a different key, already recorded by the tree.",
 "reverify_command": "PYTHONDONTWRITEBYTECODE=1 python3 " + D + "/rederive/lemaitre-poisson-2019-gamma1.py && sed -n 752,825p " + D + "/src/casmag/all/2604.05980v1.txt && grep -n 'LeMaitre' /home/user/Claude-Method-Works/research/warp-drive/wall.py /home/user/Claude-Method-Works/research/README.md /home/user/Claude-Method-Works/research/warp-drive/paper/CLAIMS.md /home/user/Claude-Method-Works/research/warp-drive/index3.py",
 "report_path": D + "/audits/lemaitre-poisson-2019-gamma1.json"
}
json.dump(r, open(r["report_path"], "w"), indent=1, ensure_ascii=False)
print("written")
