import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S=D+"/rederive/coulomb-exterior-field-energy.py"
rep={
"key":"coulomb-exterior-field-energy",
"name":"Electrostatic energy of the Coulomb field outside radius a, Q^2/(8 pi eps0 a), and ADM mass >= X/a",
"source":{
 "located":"Three layers. (i) Flat-space field energy U = int_a^inf (eps0/2)E^2 dV = Q^2/(8 pi eps0 a): textbook electrostatics (Jackson, Classical Electrodynamics) -- pre-arXiv, NAMED-NOT-READ; its exact GR counterpart READ in arXiv:2608.16534v1 (Jaraba, Campos, Baldiotti, 17 Aug 2026) p.6 eqs (38)-(39) and p.7. (ii) ADM mass of a charged thin shell: Arnowitt, Deser, Misner, PRL 4, 375 (1960) and PR 120, 313 (1960) -- pre-arXiv, NAMED-NOT-READ; restated exactly in arXiv:1303.1274v1 (R. Casadio, 'Charged shells and elementary particles', 2013) eqs (2.22)-(2.24), (3.1)-(3.3) with Israel's junction conditions (Israel, Nuovo Cimento B44, 1 (1966) -- NAMED-NOT-READ) and in areal form eq (3.14); and in arXiv:1303.2706v3 (G. Dillon 2013) Sec. 2 eq (4) and eq (9). (iii) Constants: CODATA 2022, arXiv:2409.03787v1, Tables XXXII/XXXIII p.50-51 and Table XXXVIII p.60.",
 "read_status":"READ-VIA-RESTATEMENT",
 "via":"alphaXiv answer_pdf_queries on 2608.16534 (pp.1-2,5-10,12-13,15), 1303.1274 (pp.1-11, full paper), 1303.2706 (pp.1-7, full paper), 2409.03787 (pp.1-2,50-51,57,60-62,64). The classics (Jackson; ADM 1960; Israel 1966) are read only through these restatements. Owner lines re-read in the working tree: drivensource.py md5 5c67a71c9750390fbc83a03de745b236 (last commit 3223791), lines 144-164, 278-280, 348-363, 426-433, 459-460, 537-552; specthm.py 873-897 (R3), 2244-2247 (fixed hypothesis 'electrovac'), 2849-2856 (V6)."
},
"published_statement":"2608.16534 p.6-7: 'For an RN spacetime, the KS scalar is given by f_RN(r) = 2M/r - Q^2/r^2 ... the quasi-local energy evaluates to Delta E_RN(r) = M - Q^2/(2r)' [= Misner-Sharp mass, eqs (31)-(33)]; 'At any finite radius r, the evaluated energy is less than the total ADM mass M. The subtracted term, -Q^2/(2r), corresponds precisely to the classical electrostatic energy of the electric field stored in the exterior region (from the boundary r to spatial infinity).' Casadio 1303.1274 (restating ADM 1960 via Israel's junction equations), p.5-6: 'the discontinuity of the extrinsic curvature at the shell surface, K_thth(r = eps) - K^0_thth(r = eps) = -m0, (2.22) leads to M^2 + 2 eps M - 2 eps m0 - Q^2 = 0, (2.23) from which we obtain ... M = -eps + sqrt(eps^2 + 2 eps m0 + Q^2), (2.24)' (eps the isotropic shell radius, m0 the bare mass, M the ADM mass, G = c = 1); p.6 eq (3.1): for eps -> 0, 'M = |Q|, which shows that the bare mass m0 does not have any gravitational effects'; eq (3.2) areal shell radius rbar(eps) = (m0 + eps + sqrt(eps^2 + 2 eps m0 + Q^2))/2; p.9 eq (3.14) at areal radius lambda: 'M_lambda = m0(1 - m0/(2 lambda)) + Q^2/(2 lambda)'. Dillon 1303.2706 p.2-3 restating ADM: 'M(R) = M0 - (G/2) M(R)^2/(R c^2)' and 'adding to (4) the contribution to the mass of the electromagnetic energy e^2/2R ... M(R -> 0) = |e|/sqrt(G)'.",
"published_hypotheses":[
 "Einstein-Maxwell; static, spherically symmetric; exterior is Reissner-Nordstrom (Birkhoff for electrovac), asymptotically flat (Casadio Sec 2.2, eq 2.3)",
 "infinitely thin shell of bare (rest) mass m0 >= 0 and charge Q at isotropic radius eps >= 0 (eps >= r_min for |Q| > M); flat Minkowski interior (Casadio Sec 2.1, 2.3)",
 "Israel junction conditions: continuity of the induced metric, jump of extrinsic curvature = shell surface stress (Casadio eqs 2.21-2.22); a surface tension p on the shell (eq 2.20) -- its value is not constrained by an energy condition in the source",
 "geometric units G = c = 1, Gaussian charge (Q^2 in f); areal radius rbar vs isotropic radius eps distinguished (Casadio eq 2.6)",
 "the 'electrostatic energy outside r' (2608.16534 p.7) is the Misner-Sharp / quasi-local measure M - m(r), i.e. the integral of rho over AREAL volume 4 pi r^2 dr, not proper volume",
 "flat-space version (Jackson): Coulomb field of total charge Q inside radius a, energy density eps0 E^2/2, Euclidean volume"
],
"hypothesis_drift":[
 "WEAKENED/APPROXIMATED -- additivity with bare mass. drivensource.py:360-363 (shell_ratio docstring 'r_c / a for a shell of radius a, charge Q and BARE mass mu. Equals 1/(1 + mu a / X)') and :427 (z3 model 'Mt == mu + X / a') add the flat-space field energy to the BARE mass. In exact GR the shell's bare rest mass enters as M = m0 + Q^2/2a - m0^2/2a (Casadio eq 3.14; Israel; re-derived here, section D): the gravitational binding -G m0^2/(2 a c^2) is dropped. The additive form is EXACT if mu is read as the Misner-Sharp mass at the surface, mu := m(a+) = M - X/a (section D), which is the reading drivensource.py:149 ('the body's own contribution to M') supports. Conclusion unaffected: z3 proves r_c <= a for every GR shell with m0 >= 0 (section F). Numerically the correction for the tree's pinned configuration (1 kg on 1 m) is 3.7e-28 kg -- far below the 1e-9 tolerance at drivensource.py:550. A discrepancy of model, not a refutation.",
 "IMPLICIT -- which volume measure. drivensource.py:144-145 ('The field OUTSIDE a already carries energy Q^2/(8 pi eps0 a)') is the flat-space formula; in GR it is exact only as the AREAL integral int_a^inf 4 pi r^2 rho dr = X/a (= M - m(a)); the proper-volume integral is strictly larger (0.1654 vs 0.1350 at M = 1, Q = 0.9, a = 3, section C). The tree's bound uses only M - m(a) = X/a, so the drift is harmless; it is named because the words 'carries energy' do not say which measure.",
 "UNSTATED -- the supremum is exotic. drivensource.py:157-159 ('Equality needs ... a shell of zero bare mass, and then r_c = a exactly -- marginal, not contracting') and :552 ('zero bare mass gives exactly 1'). A static shell with m0 = 0 has sigma = 0 and, from the Israel junction, tangential stress p = -Q^2/(16 pi a^3) < 0 (section G): sigma + p < 0, the NEC fails ON THE SHELL. So the supremum is attained only by NEC-violating shell matter; with the NEC imposed on the shell, m0 > 0 and the inequality is strict (z3, section F). This strengthens the tree's conclusion rather than weakening it; the tree does not claim the supremum is physical, so it is recorded, not charged.",
 "SCOPED -- the interior step. drivensource.py:162-164 ('With a regular centre and rho >= 0, m(r) = 4 pi int_0^r rho r'^2 dr' >= 0') holds on a STATIC slice (dm/dr = 4 pi r^2 rho from G^t_t = -2m'/r^2, section H). On a non-static slice D_r m = 4 pi R^2 (rho W + j U) (drivensource.py's own MS-r identity at line 339), so rho >= 0 alone is not enough -- Hayward's positivity (gr-qc/9408002 Prop 6) needs the DEC and an untrapped slice. drivensource.EM_CLOSED_BY (line 456: 'the field's own exterior energy (static branch)') places section 4 on the static branch, so the tree's use is inside the valid class; the canonical hypothesis list does not name staticity and this entry names it.",
 "SCOPE TENSION (named, not a drift of the external result). drivensource.SCOPE (lines 459-460) says 'pure electrovac ... Charged fluids ... are not measured', while section 4's body of radius a is necessarily non-electrovac matter (a charged body or shell with stress). The re-derivation covers it with no fluid model: the bound needs only M = m(a) + X/a (exact RN exterior) and m(a) >= 0 (section F, 'general body').",
 "NO DRIFT on units: X = Q^2/(8 pi eps0 c^2) and r_c = X/M are exact in SI with G cancelling (drivensource.py:348-357 vs section B)."
],
"data_at_publication":[
 {"quantity":"X per C^2 = 1/(8 pi eps0 c^2) = mu0/(8 pi)","value_then":"5.0e-08 kg m (drivensource.py:541, with EPS0 = 8.8541878128e-12 F/m CODATA 2018 at line 278; computed 5.00000000272e-08)","value_now":"4.99999999933e-08 kg m (eps0 = 8.8541878188(14)e-12 F/m, CODATA 2022; mu0/(4 pi 1e-7) = 0.99999999987(16))","source_now":"arXiv:2409.03787v1 Table XXXIII p.51; Table XXXVIII p.60 (eps0 moved +4.5 sigma_2018)","moves_conclusion":"no -- relative move 6.8e-10; r_c <= a is an inequality independent of X"},
 {"quantity":"r_c/a for 4472 C, 1 m, 1 kg bare (drivensource.py:550 pin 0.4999847997, tol 1e-9)","value_then":"0.499984799674 (CODATA 2018 eps0)","value_now":"0.499984799505 (CODATA 2022 eps0); GR binding correction changes it by < 1e-25","source_now":"computed, section I of the script","moves_conclusion":"no -- shift 1.7e-10, inside the pin's 1e-9 tolerance"},
 {"quantity":"G (enters only the GR binding term G m0^2/(2 a c^2))","value_then":"6.67430e-11 (CODATA 2018, drivensource.py:280; not used in section 4)","value_now":"6.67430(15)e-11 (CODATA 2022, unchanged)","source_now":"arXiv:2409.03787v1 Table XXXIII p.51","moves_conclusion":"no -- G cancels from X and r_c; binding matters only for m0 ~ a c^2/G = 1.35e27 kg at a = 1 m"}
],
"rederivation":{
 "method":"sympy",
 "script_path":S,
 "outcome":"33 PASS, 0 FAIL (exit 0, ~1.6 s; script md5 80bbc20da52bcd633e2fe23211fdbf64). sympy: flat Coulomb energy outside a = Q^2/(8 pi eps0 a); RN Misner-Sharp mass in SI m(r) = M - X/r with G cancelling, unique zero r_c = X/M; GR areal integral of rho outside a = X/a exactly and dm/dr = 4 pi r^2 rho, proper-volume integral strictly larger; Israel static thin shell with flat interior gives M = m0 + Q^2/2a - m0^2/2a (= Casadio eq 3.14); ADM quadratic (Casadio 2.23) is identical to the Israel relation under a = eps + (m0+M)/2 (Casadio 3.2, 2.6); eps -> 0 gives M -> |Q| at areal radius (m0+|Q|)/2 >= r_c; G^t_t = -2m'/r^2 from the metric (static interior step); m0 = 0 shell has p = -Q^2/(16 pi a^3) < 0 (NEC fails on the shell). z3 (vacuity guards sat, drift guards sat): tree's E2 re-proved on its own model; GR shell m0 in [0,2a] => 2Ma >= Q^2, strict for m0 in (0,2a); ADM-parametrised shell with eps >= 0, m0 >= 0 => m0 <= 2a automatically and 2Ma >= Q^2 (the tree's bound in exact GR); general body M = m(a) + Q^2/2a with m(a) >= 0 => r_c <= a. Numeric: tree's X per C^2 and 0.4999847997 reproduced under CODATA 2018 and 2022. Dillon 2013's alternative Newtonian renormalisation (eq 27) sits below e^2/2R for every R, unlike exact GR.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"arXiv:1303.1274 (R. Casadio 2013), Charged shells and elementary particles","effect":"confirms","what":"Re-derives ADM 1960 from Israel's junction equations: M = -eps + sqrt(eps^2 + 2 eps m0 + Q^2), areal form M = m0(1 - m0/2lambda) + Q^2/2lambda. Every static shell with m0 >= 0 obeys M >= Q^2/(2 a_areal) (z3 here), so the tree's r_c <= a holds in exact GR, with a binding term the tree's weak-field formula drops. Also: the eps -> 0 point limit has finite M = |Q| and areal radius (m0+|Q|)/2 > 0, i.e. it is not an areal point charge; consistent with specthm V6 keeping the singular RN point charge (m(0+) = -infinity) outside the hypothesis.","read_status":"READ (full paper, pp.1-11, alphaXiv)"},
 {"ref":"arXiv:1303.2706 (G. Dillon 2013), On the gravitational self-energy of a spherical shell","effect":"contested","what":"Restates ADM's M = M0 - GM^2/(2Rc^2) (+ e^2/2R) and proposes a second, Newtonian 'additive' renormalisation (eq 25-27) in which a pure charged shell has M_e(R) = (c^2R/G)(1 - exp(-G e^2/(2R^2c^4))) < e^2/(2Rc^2) -- a model that WOULD put r_c outside the shell. It is explicitly Newtonian with an extra additivity assumption, not a solution of the Einstein-Maxwell junction problem; exact GR (Israel/ADM) gives M = Q^2/2a at m0 = 0. Recorded as a contested model, not as evidence against the tree.","read_status":"READ (full paper, pp.1-7, alphaXiv)"},
 {"ref":"arXiv:2608.16534 (Jaraba, Campos, Baldiotti 2026)","effect":"confirms","what":"Quasi-local (Iyer-Wald) energy of RN equals the Misner-Sharp mass M - Q^2/2r; the subtracted term is 'precisely' the exterior electrostatic energy. Supplies the exact GR meaning of drivensource.py:144-145 (areal/quasi-local measure).","read_status":"READ (pp.5-7 at source)"},
 {"ref":"arXiv:2409.03787 (CODATA 2022)","effect":"confirms","what":"eps0 moved by +4.5 sigma_2018 (relative 6.8e-10); G unchanged. No effect on the bound; the pinned 0.4999847997 still reproduces within its tolerance.","read_status":"READ (Tables XXXII, XXXIII, XXXVIII)"}
],
"lacked_data":"M's hypothesis tested. The external result has two parts. (1) The exterior Coulomb energy Q^2/(8 pi eps0 a) is a closed-form integral whose only datum is eps0 (equivalently mu0): the 1960s-era value was 'exact' (mu0 = 4 pi 1e-7); after the 2019 SI revision it is measured, and CODATA 2022 moved it by 6.8e-10 relative (-13(16) parts in 1e11 in mu0). Computed: X per C^2 and the tree's pinned r_c/a move by < 2e-10, and r_c <= a is an inequality that no value of eps0 can reverse. (2) The ADM/Israel shell mass is a theorem of Einstein-Maxwell with a thin-shell source; it uses no measured datum at all (G cancels from X and r_c). What earlier treatments DID lack is not data but a term: the flat-space picture (and drivensource.py's model at :360, :427) omits gravitational binding; the exact GR relation (ADM 1960, Israel 1966, restated by Casadio 2013) includes it and still gives M >= Q^2/(2a), proved here by z3. Evidence against M's hypothesis for this result: no datum that has moved, or could move, changes the conclusion. Evidence for a weaker form: the textbook flat additivity is incomplete in strong fields (a Newtonian alternative, Dillon 2013, even disagrees on the sign of the effect), but the incompleteness does not reach the bound.",
"grade":"STANDS",
"grade_evidence":"The published statements (exterior field energy = Q^2/2r as the Misner-Sharp deficit, 2608.16534 p.7; ADM/Israel charged-shell mass, Casadio 1303.1274 eqs 2.23-2.24, 3.14) are re-derived exactly (sympy, 33/33). The tree's conclusion r_c = X/M <= a is machine-checked in EXACT GR, not only on the tree's flat additive model: z3 proves 2Ma >= Q^2 for every ADM shell with eps >= 0, m0 >= 0 (which forces m0 <= 2a), and for any body with M = m(a) + Q^2/2a, m(a) >= 0; vacuity and drift guards are sat. The interior step holds on a static slice (G^t_t = -2m'/r^2), which is where drivensource.EM_CLOSED_BY places section 4. The only moved datum (eps0, CODATA 2022) shifts the pinned r_c/a by 1.7e-10, inside its 1e-9 tolerance, and cannot reverse an inequality. Recorded discrepancies, none a refutation: the tree's shell_ratio formula (drivensource.py:360-363, z3 model :427) is the weak-field form with bare mass (exact GR adds -G m0^2/(2ac^2); 3.7e-28 kg at the pinned configuration), exact if mu is the surface Misner-Sharp mass as :149 words it; the supremum r_c = a (:157-159) is attained only by an NEC-violating zero-rest-mass shell (p = -Q^2/16 pi a^3 < 0), which makes the bound strict under the NEC; staticity of the interior step is implicit. Not NARROWED: the class on which the bound holds in exact GR is not smaller than the class the tree uses (all non-negative bare mass).",
"what_would_change_the_grade":"NARROWED if the tree used the bound on a NON-STATIC charged body (then rho >= 0 is not enough; DEC + untrapped slice are needed, Hayward Prop 6), or quoted shell_ratio's 1/(1 + mu a/X) as exact for strong-field shells (m0 comparable to a c^2/G). WRONG only on a static Einstein-Maxwell configuration with a regular centre (or thin shell of non-negative rest mass) and asymptotically flat RN exterior having M < Q^2/(8 pi eps0 c^2 a) -- the z3 proofs here exclude it within the thin-shell and M = m(a) + X/a models, so a counterexample would have to break one of those (e.g. a non-RN exterior: nonlinear electrodynamics, non-spherical fields, or a cosmological constant, all outside drivensource.SCOPE). A reading of ADM 1960 / Israel 1966 at source finding a different junction relation would reopen section D/E (the restatements are READ; the classics are NAMED-NOT-READ).",
"reverify_command":"python3 "+S+"  # expect '33 PASS, 0 FAIL(s)', exit 0 (~2 s, sympy + z3); owner check: md5sum /home/user/Claude-Method-Works/research/warp-drive/drivensource.py  # 5c67a71c9750390fbc83a03de745b236; sed -n 144,164p;348,363p;426,433p;537,552p of it",
"report_path":D+"/audits/coulomb-exterior-field-energy.json"
}
json.dump(rep,open(rep["report_path"],"w"),indent=1)
print("ok")
