import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
R = {
 "key": "dlnlambdaqcd-dlnv-2-9",
 "name": "d ln Lambda_QCD / d ln v = 2/9 (QCD running through heavy-quark thresholds) -- hypothesis H1, f = 2/9 + 7S/9",
 "source": {
  "located": "The tree cites no paper: address.py:99 says 'DERIVED IN THIS FILE OVER Fraction, not quoted'. The published form is A. Coc, N.J. Nunes, K.A. Olive, J.-P. Uzan, E. Vangioni, 'Coupled variations of fundamental couplings and primordial nucleosynthesis', astro-ph/0610733 (PRD 76, 023511 (2007)), p.4 eqs. (13)-(14), which cites its ref [53] for it. Earlier cruder form (no heavy thresholds, N_f = 3 only): Campbell & Olive, hep-ph/9411272 (1994) eqs. (10)-(11). The beyond-leading-order statement of the same quantity is the heavy-quark scalar matrix element f_Q: SVZ 1978 (PLB 78, 443) at LO, Hill & Solon 1409.8290 (2014) eqs. (39), (61), (101), (119), (120) through O(alpha_s^3).",
  "read_status": "READ",
  "via": "alphaXiv answer_pdf_queries on astro-ph/0610733 (pages 1-7, 9-10 returned, eqs. (4)-(41)), on hep-ph/9411272 (pages 1, 4-6, 8, 10) and on 1409.8290 (pages 1, 15, 17-18, 22-23, 37, 39, 42-44, 46-48). SVZ 1978 is NAMED-NOT-READ, READ-VIA-RESTATEMENT through Hill-Solon eq. (101) ('the leading-order alpha_s result is well-known from Ref. [81]') and eq. (39) at O(alpha_s^0). Chetyrkin-Kniehl-Steinhauser hep-ph/9708255 (the decoupling constants Hill-Solon use) is NAMED-NOT-READ."
 },
 "published_statement": "Coc et al. 2007, eq. (13): 'Lambda = mu (m_c m_b m_t / mu^3)^(2/27) exp(-2 pi/(9 alpha_s(mu)))' 'for mu > m_t up to some unification scale in the standard model', and eq. (14): 'Delta Lambda/Lambda = R Delta alpha/alpha + (2/27)(3 Delta v/v + Delta h_c/h_c + Delta h_b/h_b + Delta h_t/h_t)'. With Delta alpha = 0 (the tree's H1: alpha_s fixed above m_t) and Delta h = 0 this is d ln Lambda/d ln v = 3 x 2/27 = 2/9. Footnote 1: 'In supersymmetric models, additional thresholds related to squark and gluino masses would affect this relation [54].' Hill & Solon 2014 give the same object beyond LO as the heavy-quark scalar matrix element: <O'_Q>/m_N = (1/(3 beta_0^(nf))){2 - 2 lambda} + (alpha_s^(nf+1)(mu_Q)/pi)(1/(3 beta_0^(nf)))^2 {57/2 - 321 lambda/2 + 8 n_f} + O(alpha_s^2) (eq. 39), and for charm f_c = 0.083 - 0.103 lambda = 0.073(3) + O(alpha_s^4, 1/m_c) (eq. 61), noting the 'poorly convergent alpha_s(m_c) expansion' (p.14).",
 "published_hypotheses": [
  "One-loop running with b_0(n_f) = 11 - 2n_f/3 (the exp(-2 pi/(9 alpha_s)) form of eq. 13 is the one-loop solution; no higher beta coefficient appears)",
  "alpha_s continuous at each heavy-quark threshold mu = m_Q (leading-order decoupling)",
  "mu > m_t, up to some unification scale; Standard-Model particle content between m_t and that scale (footnote 1: SUSY thresholds would change it)",
  "Heavy-quark masses m_Q = h_Q v (Coc et al. p.3-4: 'm_s = h_s v', 'm_e = h_e v'); the variation is split into Delta h and Delta v",
  "Delta alpha_s at the high scale tied to Delta alpha through a GUT-dependent R (R = 36 assumed); the relation 'between h, v and Lambda is quite robust' (p.5) is stated as model-independent",
  "Hill-Solon beyond LO: MSbar heavy-quark mass, mu_Q = m_Q, power corrections O(1/m_Q) neglected, QCD only"
 ],
 "hypothesis_drift": [
  "DROPPED (order of the expansion): the one-loop / leading-order qualifier is present at address.py:88 ('One-loop threshold matching ... gives EXACTLY') but absent where the number is consumed: address.py:97 ('2/9 EXACTLY'), address.py:498-500 (dln_lambda_dln_v docstring), excite.py:164-165 ('f = d ln m_p/d ln v: 2/9 + 7S/9 under H1'), excite.py:1400-1401 (chk 'd ln Lambda / d ln v = 2/9'), excite.py:1540-1541 (stable-matter density under 'f = 2/9 + 7S/9'), excite.py:1608-1613 (K_mu = 7(S-1)/9 exactly). 'EXACTLY' is exact rational arithmetic of the LO truncation, not of the physical quantity: beyond LO the heavy-quark sum is +6.2% larger (computed, rederive script section 5). MITIGATION, recorded both ways: excite.py:285 itself lists 'the Yukawa-running correction to 2/9' as unanswered and 'none is quoted as answered', so the tree names part of this drop as OPEN.",
  "DROPPED (implicit in the H1 composition): address.py:99-103 writes d ln m_p/d ln v = (d ln Lambda/d ln v)(1 - S) + S, i.e. the light-quark masses of the 3-flavour theory scale exactly as v. Beyond LO the light masses at hadronic scales inherit the heavy thresholds through their running, so the factorisation (1 - S) x const breaks: (f - S)/(1 - S) = 0.2384, 0.2359, 0.2331 at S = 0, 0.06, 0.12 (N3LO, computed) against 2/9 = 0.2222 for every S at LO.",
  "DROPPED: Coc et al.'s footnote-1 scope -- Standard-Model coloured content between m_t and the high scale. H1 at address.py:103 ('alpha_s FIXED AT A HIGH SCALE') and excite.py:164 carry no particle-content clause; excite.py:285 names only 'a BSM light scalar' as open, not heavy coloured states, which would add their own thresholds (and their own v-dependence) to the 2/27 sum.",
  "DROPPED: the O(1/m_c) power corrections of treating charm as a heavy (decoupled) quark. Hill-Solon (p.22) print f_c = 0.073(3) + O(alpha_s^4, 1/m_c) and list lattice values 0.10(3) and 0.07(3) (eq. 62); the tree's 2/27 for charm carries no such clause (address.py:88-97).",
  "NOT A DRIFT (checked): 'every heavy quark mass is proportional to v' (address.py:94-95) is Coc et al.'s m_Q = h_Q v at fixed Yukawa, stated for the same object. The tree's H1 corresponds to Coc's Delta alpha = 0 (R-term absent), and the tree names H2 (Lambda fixed) separately and refuses to choose (address.py:108-110, H1_VS_H2_IS_REFUSED) -- no drift there.",
  "NOT A DRIFT (checked): QED is not dropped silently -- excite.py:203-204 and address.py W11 name that alpha also moves under H1."
 ],
 "data_at_publication": [
  {"quantity": "one-loop coefficients b_0(n_f) = 11 - 2n_f/3, step b_0(n_f - 1) - b_0(n_f) = 2/3", "value_then": "exact group theory (Coc 2007 eq. 13 exponent 2/27 = (2/3)/b_0(3))", "value_now": "unchanged (exact)", "source_now": "Hill-Solon 1409.8290 eq. (109), READ", "moves_conclusion": "no -- the LO 2/9 involves no measured datum at all"},
  {"quantity": "alpha_s(M_Z) (enters only the beyond-LO correction, via alpha_s at m_c, m_b, m_t)", "value_then": "not used by Coc et al. (LO needs none)", "value_now": "0.1180(9), PDG 2024 -- NAMED-NOT-READ in this stage; gives alpha^(4)(m_c) = 0.3868, alpha^(5)(m_b) = 0.2246, alpha^(6)(m_t) = 0.1085 by 4-loop running", "source_now": "PDG 2024 (NAMED-NOT-READ); beta_0..beta_3 READ from Hill-Solon eq. (109)", "moves_conclusion": "no -- scanning 0.1171..0.1189 (with m_t 161..164.6 GeV and decoupling constant c2 = +11/72, 0, -11/72) moves the beyond-LO heavy-sum shift only within +6.04% .. +6.29% (computed)"},
  {"quantity": "heavy-quark MSbar masses m_c(m_c), m_b(m_b), m_t(m_t)", "value_then": "not used numerically (only their v-scaling)", "value_now": "1.2730, 4.183, 162.5 GeV (PDG 2024, NAMED-NOT-READ)", "source_now": "PDG 2024 (NAMED-NOT-READ)", "moves_conclusion": "no -- enter only the threshold scales of the correction; included in the scan above"},
  {"quantity": "S = sum_q sigma_q/m_p (lambda in Hill-Solon)", "value_then": "Coc et al. eq. (11): Sigma = 51 MeV (B_s = 1.5) gives Delta m_p/m_p = 0.76 Delta Lambda/Lambda + 0.24(Delta h/h + Delta v/v), i.e. their light-quark coefficient 0.24; the tree scans S = 0.0096, 0.06, 0.09 (address.py:451, S_MID = 0.06)", "value_now": "Hill-Solon (2014) lambda = 0.089(26); the sigma_piN value is contested (lattice ~40-45 MeV vs Roy-Steiner ~59 MeV) -- audited separately in qcd-trace-anomaly-nucleon-mass, not re-read here", "source_now": "1409.8290 eq. (61), Table 10, READ", "moves_conclusion": "moves f linearly (slope 7/9 at LO) but NOT the 2/9 at LO; beyond LO it moves (f - S)/(1 - S) from 0.2384 (S = 0) to 0.2331 (S = 0.12). K_mu stays in -0.755 .. -0.679 over S = 0.0096 .. 0.115 at N3LO (computed): O(1) and negative, as the tree concludes"},
  {"quantity": "R = d ln Lambda / d ln alpha (GUT-dependent)", "value_then": "36 (Coc et al., 'minimal assumptions')", "value_now": "model-dependent, unchanged status", "source_now": "Coc et al. p.4, READ", "moves_conclusion": "no -- under the tree's H1 the high-scale coupling is held fixed, so the R-term is zero by hypothesis"},
  {"quantity": "beyond-LO value of the heavy-quark sum f_c + f_b + f_t at S = 0.06", "value_then": "LO only: 3 x (2/27)(1 - S) = 0.20889", "value_now": "NLO 0.22126, NNLO 0.22248, N3LO 0.22177 (= 1.0617 x LO); f = 0.28177 vs 0.26889 (+4.79%); K_mu = -0.71823 vs -0.73111 (|K_mu| -1.76%); stable-matter H1 density at eps = 1e-18 (excite.py:1540-1541) 8.19956e11 -> 7.8247e11 kg/m^3 x (m_h/125.20)^2", "source_now": "computed from Hill-Solon eqs. (39), (119) READ, transcription checked against their eq. (120) and (61)", "moves_conclusion": "moves every H1 figure by a few per cent; does not move D20's order of magnitude, S6 (ROLE1_DOMINATED_BY_OWN_SOURCE) or S7 (ROLE2_REBINDS = False), nor the sign or O(1) size of K_mu"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/dlnlambdaqcd-dlnv-2-9.py",
  "outcome": "0 failures, exit 0. (1) sympy re-derives the one-loop chain independently of address.py: Lambda_3 = Lambda_6^(7/9) (m_c m_b m_t)^(2/27), mass dimension closes, d ln Lambda_3/d ln v = 2/9 exactly, top alone gives 2/23; Coc et al. eq. (13) is shown identical to the chain (difference simplifies to 0) and eq. (14) gives 2/9. (2) The tree's f = 2/9 + 7S/9, K_mu = 7(S-1)/9, f(0.06) = 0.268889, K_mu(0.06) = -0.731111 reproduced; SVZ's heavy-quark theorem iterated c -> b -> t gives 2/27 (1 - S) for EACH quark, so S + sum f_Q = 2/9 + 7S/9 identically -- an independent route (Feynman-Hellmann + trace anomaly) to the tree's H1 formula at LO. (3) Hill-Solon eq. (39)+(119) transcribed; reproduces their eq. (120) coefficients 0.074, 0.072/-0.220, 0.100/-0.528, -0.391/0.761 to 3 decimals, their eq. (61) slope -0.103 within the rounding of the printed 0.083 (-0.1030 .. -0.1069), and f_c(lambda = 0.089) = 0.0741 against their 0.073(3). (4) Beyond LO at S = 0.06: heavy sum x1.0617, f +4.79%, |K_mu| -1.76%; the correction is positive and stable (+6.04..+6.29%) across alpha_s(M_Z) +- 0.0009, m_t and the unread decoupling constant. The charm series converges acceptably at mu_c = m_c (NLO/LO = 10%, then +1.5%, -0.9%). A discrepancy of one unit in the third decimal of Hill-Solon's rounded eq. (61) slope is rounding, recorded, not an error.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "R.J. Hill, M.P. Solon, 1409.8290 (2014), eqs. (39), (61), (101), (119), (120)", "effect": "extends", "what": "Gives the exact object the tree's 2/9 approximates -- the heavy-quark scalar matrix elements f_Q -- through O(alpha_s^3); LO is 2/27 (1 - lambda) per quark. Computed here: the beyond-LO heavy sum is +6.2% over 2/9 (1 - S) at S = 0.06, and the (1 - S) factorisation breaks. Also flags the charm expansion as poorly convergent and O(1/m_c) corrections as unestimated.", "read_status": "READ"},
  {"ref": "M.A. Shifman, A.I. Vainshtein, V.I. Zakharov, PLB 78, 443 (1978)", "effect": "confirms", "what": "Heavy-quark theorem m_Q <QbarQ> = (2/27)(1 - lambda) m_N at LO -- an independent derivation giving exactly the tree's 2/9 + 7S/9 when summed over c, b, t (shown symbolically in the script).", "read_status": "NAMED-NOT-READ; READ-VIA-RESTATEMENT in 1409.8290 eq. (101) and eq. (39) at O(alpha_s^0)"},
  {"ref": "Hill-Solon eq. (62), quoting MILC (PRD 88, 054503) f_c = 0.10(3) and chiQCD (PRD 88, 014503) f_c = 0.07(3)", "effect": "contested", "what": "Non-perturbative lattice charm matrix elements; consistent with the perturbative 0.073(3) within ~30% errors, so the charm leg of 2/9 is tested only to that precision.", "read_status": "READ-VIA-RESTATEMENT (values as printed in 1409.8290 p.22; the lattice papers themselves not read)"},
  {"ref": "K.G. Chetyrkin, B.A. Kniehl, M. Steinhauser, hep-ph/9708255 (1997); Grozin et al. 1107.5970 (2011)", "effect": "extends", "what": "Decoupling relations for alpha_s and masses to O(alpha_s^3) (and simultaneous b, c decoupling) -- the machinery beyond the continuous one-loop matching Coc et al. and the tree assume. Their decoupling constant enters the correction here only at the 0.1% level (scan with c2 = +-11/72, 0).", "read_status": "NAMED-NOT-READ (surfaced by discover_papers)"},
  {"ref": "B.A. Campbell, K.A. Olive, hep-ph/9411272 (1994), eqs. (10)-(11)", "effect": "narrows", "what": "Predecessor treatment of Lambda_QCD by dimensional transmutation with N_f = 3 only and no heavy thresholds, so no 2/27 -- the heavy-threshold v-dependence is a later refinement (Coc et al. 2007 eq. 14 notes it 'has been neglected in most studies discussing the effect of varying v').", "read_status": "READ"},
  {"ref": "2605.10635 (2026), 'Heavy-Quark Condensate and Vacuum Energy Anomalous Dimension at Five Loops'", "effect": "extends", "what": "Perturbative heavy-quark condensate at five loops; would push the f_Q series one order further. Not needed: the correction is already stable at the 0.1% level between NNLO and N3LO for b and t.", "read_status": "NAMED-NOT-READ (abstract seen in discover_papers only)"}
 ],
 "lacked_data": "M's hypothesis tested. What Coc et al. (2007) did not use: any higher-order QCD. That was a choice, not a lack of data -- one-loop running and continuous matching need no measured input at all, and the O(alpha_s^3) decoupling constants (CKS 1997) already existed. What came later: the full O(alpha_s^3) heavy-quark scalar matrix elements (Hill-Solon 2014), lattice charm sigma terms (2013, +-30%), and improved sigma_piN / sigma_s (still contested). Does having them change the conclusion? The number: yes, by a computed few per cent -- the heavy-quark sum is 6.2% above 2/9 (1 - S), f(H1) 4.8% above 2/9 + 7S/9, |K_mu| 1.8% smaller, the H1 stable-matter density 4.6% smaller. The conclusions resting on it: no -- K_mu stays O(1) and negative for every S in 0.0096 .. 0.115 (-0.755 .. -0.679), D20's holding-cost order of magnitude and S6/S7 are unmoved, and the shift is stable (+6.04 .. +6.29%) under every datum varied. Evidence against M's hypothesis for THIS result: the LO value is data-free and reproduced exactly; the later data refine rather than overturn. Evidence for it (in its weak form): the 'EXACTLY' is an artefact of truncation; nobody lacked data to see that, but a reader of excite.py alone is not told.",
 "grade": "NARROWED",
 "grade_evidence": "The published statement (Coc et al. 2007 eqs. 13-14, READ) and the tree's 2/9 agree exactly (sympy: eq. 13 minus the one-loop chain simplifies to 0; d ln Lambda_3/d ln v = 2/9; SVZ's heavy-quark theorem gives the same 2/9 + 7S/9 by an independent route). But the result is a leading-order (one-loop running, continuous matching, SM content, charm treated as heavy) statement, and the tree consumes it as 'EXACTLY' with that qualifier dropped at address.py:97, 498-500 and excite.py:164-165, 1400-1401, 1540-1541, 1608-1613 (kept only at address.py:88). Beyond LO, using Hill-Solon's O(alpha_s^3) f_Q (READ, transcription checked against their eqs. 120 and 61), the heavy sum is 1.0617 x 2/9 (1 - S) at S = 0.06, f = 0.28177 not 0.26889, K_mu = -0.7182 not -0.7311, and the (1 - S) factorisation of address.py:99-103 fails at the 2% level across S. It is not WRONG: no refuting case exists -- the tree's number is the correct LO value and the tree itself lists 'the Yukawa-running correction to 2/9' as OPEN (excite.py:285). It is not DATA-DEPENDENT: the LO value uses no datum, and the correction is stable (+6.04..+6.29%) over alpha_s(M_Z), m_t and the decoupling constant. It is not plain STANDS because the statement as used ('exact') holds only on the LO class, and the SM-content and 1/m_c hypotheses are dropped. No conclusion resting on it (D20, S6, S7, K_mu O(1) and negative) moves.",
 "what_would_change_the_grade": "To STANDS: the owners carry 'leading order (one-loop running, continuous matching at m_Q, SM coloured content, charm decoupled)' wherever 2/9 and 2/9 + 7S/9 are consumed, and the +6% beyond-LO shift is either quoted or the excite.py:285 OPEN item is widened to cover it. To WRONG: a downstream conclusion that required |K_mu| or f to within <2-5% (none found; D20, S6, S7 are order-of-magnitude). To DATA-DEPENDENT: a use in which the S-dependence of the beyond-LO factor (0.2384 .. 0.2331) or the contested sigma_piN matters. To OPEN: failure of the heavy-quark expansion at charm large enough to exceed the lattice +-30% band (MILC 0.10(3) vs perturbative 0.073(3)) would make the charm leg uncheckable here; a 4-flavour lattice f_c at few-% precision would settle it.",
 "reverify_command": "python3 " + D + "/rederive/dlnlambdaqcd-dlnv-2-9.py  # expect '0 failures', exit 0; sources: alphaXiv answer_pdf_queries(astro-ph/0610733, eqs 13-14 p.4, footnote 1); (1409.8290, eqs 39, 61, 62, 101, 109, 119, 120); (hep-ph/9411272, eqs 10-11). Tree sites: grep -n '2/9\\|One-loop' research/warp-drive/address.py research/warp-drive/excite.py",
 "report_path": D + "/audits/dlnlambdaqcd-dlnv-2-9.json"
}
json.dump(R, open(R["report_path"], "w"), indent=1, ensure_ascii=False)
print("written", R["report_path"])
