import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
K="frw-metric-k-minus1-and-k0"
r={
"key":K,
"name":"Friedmann-Robertson-Walker metrics, open (k = -1) and flat (k = 0)",
"source":{
 "located":"Classic with no arXiv copy: Friedmann 1922 (k=+1) and 1924 (k=-1), Lemaitre 1927/1933, Robertson 1935-36, Walker 1936. Read via two exact restatements on arXiv: (1) D. Baumann, 'TASI Lectures on Inflation', arXiv 0907.5424v2, sec.3.1 eq.(1) ds^2 = -dt^2 + a^2(t)[dr^2/(1-kr^2) + r^2 dOmega^2] 'Assuming homogeneity and isotropy'; eq.(2)-(3) the same in chi with r^2 = sinh^2 chi, chi^2, sin^2 chi for k = -1, 0, +1; 'comoving coordinates'; Problem 1 eq.(105)-(106) and 'the only time-dependent four-dimensional spacetime that preserves homogeneity and isotropy of space is the FRW metric' (eq.107, 'simple topology'); Problem 3 eq.(109)-(111) Ricci components and Friedmann equations; p.45 'The FRW threading corresponds to the motion of comoving observers ... The slicing is orthogonal to the threading'. (2) G. F. R. Ellis & H. van Elst, 'Cosmological Models (Cargese 1998)', arXiv gr-qc/9812046v5, sec.4 and 4.1: FL models are 'characterised by a perfect fluid matter tensor and the condition that local isotropy holds everywhere' (eq.103: udot = sigma = omega = 0 => E = H = 0 => spatial homogeneity when p = p(mu)); eq.(104) 'Matter-comoving local coordinates ... ds^2 = -dt^2 + S^2(t)(dr^2 + f^2(r) dOmega^2), u^a = delta^a_0'; eq.(105) f = sin r, r, sinh r for k = +1, 0, -1, 3-spaces of constant curvature with 'k normalised to +-1, if it is non-zero'; 'unusual topologies still allow the spatial sections to be closed'; eq.(106)-(107) Raychaudhuri and Friedmann; sec.4.3.1(c) Milne S(t) = t, k = -1 'flat, empty space-time in expanding coordinates'; sec.5.2 non-empty perfect fluid models assume (mu + p) > 0.",
 "read_status":"READ-VIA-RESTATEMENT",
 "via":"alphaXiv answer_pdf_queries on 0907.5424v2 (pp.1,3,15-21,23,28,32,41-42,45,129,134,138-139) and gr-qc/9812046v5 (pp.1-2,7,10,21-26,35,71). Friedmann 1922/1924, Lemaitre, Robertson 1935, Walker 1936: NAMED-NOT-READ (restated only). Context data read at source: Planck 2018 VI arXiv 1807.06209v4 (pp.1,15,39-42,71); Millard, L'Huillier & Douspis arXiv 2601.20293v1 (pp.1,3-5,10-19). Tree read at HEAD b8b929b: nonstatic.py:80-107, 195-202, 398-452, 455-468, 640-670, 599-600; ledger.py:426-431; specthm.py:1545-1560."
},
"published_statement":"(Baumann 0907.5424 eq.1-3, 106; Ellis & van Elst gr-qc/9812046 eq.104-105) Under homogeneity and isotropy of space (isotropy about every point), in coordinates comoving with the matter (u^a = delta^a_0, t the comoving observers' proper time, slicing orthogonal to the threading), the metric is ds^2 = -dt^2 + a^2(t)[dchi^2 + S_k(chi)^2 dOmega^2], S_k = sinh chi (k = -1, open), chi (k = 0, flat), sin chi (k = +1), equivalently a^2[dr^2/(1 - k r^2) + r^2 dOmega^2] with r = S_k(chi); the t = const 3-spaces have constant curvature (3-Ricci scalar 6k/a^2). With a perfect fluid source the Einstein equations give H^2 = (8 pi G/3) rho - k/a^2 and addot/a = -(4 pi G/3)(rho + 3p) (Baumann eq.110-111; Ellis eq.106-107).",
"published_hypotheses":[
 "GR in 4 dimensions (the metric form is pure geometry; the Friedmann equations need the Einstein equations)",
 "spatial homogeneity and isotropy -- isotropy about every point (Baumann fn.1: everywhere-isotropic implies homogeneous; Ellis eq.103)",
 "matter-comoving coordinates: u^a = delta^a_0, u_a = -grad t, zero shift, t = proper time of the fundamental observers; the slicing orthogonal to the threading (Ellis eq.104; Baumann eq.1 'comoving coordinates' and p.45)",
 "fundamental flow geodesic, shear-free, irrotational (Ellis eq.103: udot = sigma = omega = 0)",
 "source a perfect fluid (Ellis sec.4 'characterised by a perfect fluid matter tensor'; Baumann eq.19-20); non-empty models assume mu + p > 0 (Ellis sec.5.2) -- a MATTER hypothesis, not a consequence of the metric",
 "k normalised to -1, 0, +1 with the curvature scale carried by a (Ellis 4.1 item 2)",
 "simple (simply connected) topology for the global chart ranges (Baumann Problem 1 'with simple topology'; Ellis 4.1: unusual topologies allow closed sections) -- global only; every local statement is unaffected"
],
"hypothesis_drift":[
 "ADDED (generality) against a CLAIM THAT NEEDS A MATTER LAW -- nonstatic.py:98-99 'OPEN FRW, k = -1. W = cosh(chi) > 1 again, with rho = 3(adot^2-1)/(8 pi a^2) > 0', while the witness is built and labelled for 'general a(t)' (nonstatic.py:450; canonical hypothesis 'general scale factor a(t) > 0'). The metric does not fix the sign of rho: C4 computes rho = -9/(8 pi (t+4)^2) < 0 for k = -1 with a = 2 + t/2, rho = 0 for a = t (Milne), and rho > 0 iff adot^2 > 1. The source's FL models carry a perfect fluid with mu + p > 0 (Ellis sec.4, 5.2), which the canonical hypothesis list drops. The very next clause at nonstatic.py:100-101 restricts to 'open dust', and open_dust_nec (nonstatic.py:455-468) imposes adot^2 = 1 + C/a, for which C4 gives rho = 3C/(8 pi a^3) > 0. So the '> 0' holds on the dust (or any rho > 0 matter) subclass, not on 'general a(t)'. For k = 0, rho = 3 adot^2/(8 pi a^2) >= 0 for every a(t) (C4) -- no drift there. The same drop, graded there, is in audits/frw-open-contraction.json (drift 3).",
 "DROPPED -- comoving slicing, at nonstatic.py:104-106 ('FLAT FRW, k = 0, is the marginal case: W = 1 EXACTLY and m3 = 0 exactly. So in FRW the contraction condition is precisely k < 0'). W and m3 are components in the comoving slicing that the source metric form presupposes (Ellis eq.104 u^a = delta^a_0; Baumann p.45). The qualifier is stated in the same passage at nonstatic.py:87 ('in geodesic slicing (Phi = 0, always available)') and in canonical.json, and the tree's section 5 says W is not a scalar (nonstatic.py:209, 'm IS A SCALAR. W IS NOT.'), but the sentence itself carries it as a property of FRW. Computed in audits/frw-open-contraction.json C6 (not re-run here): flat dust has W' = 1.231845026 > 1 in a slicing tilted by rapidity -0.5. An omitted qualifier at the site, not a contradiction.",
 "NOT A DRIFT, recorded because it could look like one -- direction of use. The tree takes the FRW form as a metric ansatz with free a(t) and DEFINES T = G/(8 pi) (nonstatic.py:420-423); the source derives the Friedmann equations the same way (Baumann Problem 3). C2 confirms that for every a(t) the Einstein tensor of both forms is automatically perfect-fluid (diagonal, p_r = p_T, j = 0), so reading rho off G loses nothing -- but a matter hypothesis is still needed for any SIGN (drift 1).",
 "NOT A DRIFT -- normalisation. The source normalises k to +-1; nonstatic.py:105 speaks of 'k < 0'. C7 shows any k = -kappa rescales exactly to k = -1 with a -> a/sqrt(kappa), so 'k < 0' and 'k = -1' are the same class.",
 "NOT A DRIFT -- vacuum flags. nonstatic.py:450-451 set vacuum_expected False for 'general a(t)'; true for symbolic a, and the vacuum members are carried separately: the Milne witness at nonstatic.py:449 is literally the k = -1 form at a = t, and C6 computes its full Riemann tensor = 0, matching Ellis sec.4.3.1(c). k = -1 with a = const is NOT vacuum (rho = -3/(8 pi a^2), C6).",
 "SCOPE NOTE (not graded) -- global topology. The tree takes chi in (0, infinity) (nonstatic.py:444, 'positive=True'), i.e. the simply connected H^3 / R^3; the source notes other topologies (Ellis 4.1). Every use in the tree is local (W, m, rho at a point), so nothing depends on it."
],
"data_at_publication":[
 {"quantity":"any numerical input of the metric or its Einstein tensor","value_then":"none: the FRW forms are exact geometry with symbolic a(t) (nonstatic.py:441-452); canonical.json data_used = []","value_now":"none","source_now":"n/a","moves_conclusion":"no -- there is no datum to move"},
 {"quantity":"spatial curvature of the real universe, Omega_K (context only; the tree uses FRW as an exact witness, not as a model of our universe)","value_then":"unknown to Friedmann 1922/24, Robertson 1935, Walker 1936; not used by the tree","value_now":"Omega_K = 0.0007 +/- 0.0019 (68 %, Planck TT,TE,EE+lowE+lensing+BAO, eq.47b), = -0.044 (+0.018 -0.015) from Planck TT,TE,EE+lowE alone (eq.46b); model-independent FLRW litmus test with DESI DR2: FLRW not ruled out, Omega_k,0 median 0.033 (+0.047 -0.072) +/- 0.037 (Pantheon+) and -0.119 (+0.113 -0.047) +/- 0.043 (DES Y5)","source_now":"Planck 2018 VI arXiv 1807.06209v4 eq.(46b),(47b), read at source; Millard et al. arXiv 2601.20293v1 abstract and Table 1, read at source","moves_conclusion":"no -- the sign of k for OUR universe is still unsettled (both signs within errors), but the tree's k = -1 and k = 0 witnesses are mathematical existence statements; no verdict among rests_on_it (ledger D10, specthm R1/K0 note, nonstatic.SUSTAINING_FORCES_NEGATIVE_RHO, NEC_ON_A_CONTRACTING_POSITIVE_MASS_CONFIGURATION) rests on the real universe being open. Were one to, it would be DATA-DEPENDENT."}
],
"rederivation":{
 "method":"sympy",
 "script_path":D+"/rederive/"+K+".py",
 "outcome":"41 PASS, 0 FAIL, exit 0 (output rederive/"+K+".out; sympy 1.14.0). C1: chi-form = r-form under r = sinh chi, chi (Baumann eq.2-3, Ellis eq.105). C2: Christoffels, Riemann, Ricci and Einstein tensor of the tree's exact metric (nonstatic.py:405, 450-451: Phi = 0, Lam = log a, R = a sinh chi or a chi) computed from scratch for arbitrary a(t): rho = 3(adot^2 + k)/(8 pi a^2), p_r = p_T = -(2 a addot + adot^2 + k)/(8 pi a^2), j = 0, Einstein tensor diagonal, acceleration equation addot/a = -(4 pi/3)(rho + 3p), Ricci scalar 6[addot/a + adot^2/a^2 + k/a^2] and R_tt = -3 addot/a (Baumann eq.109-111), comoving worldlines geodesic, m = (4 pi/3) rho R^3 exactly; r-form Ricci scalar agrees. C3: W = cosh chi (k = -1), W = 1 and m3 = 0 exactly (k = 0), m3 = -a sinh^3 chi/2, m = a sinh^3 chi (adot^2 - 1)/2 -- every value nonstatic.py:98-107 and 657-659 prints. C4: sign of rho is NOT fixed by the metric (rho = -9/(8 pi (t+4)^2) for k = -1, a = 2 + t/2); dust adot^2 = 1 + C/a gives rho = 3C/(8 pi a^3) > 0; k = 0 gives rho >= 0 always. C5: t = const slices satisfy R_ijkl = (k/a^2)(h_ik h_jl - h_il h_jk) componentwise and 3-Ricci scalar 6k/a^2 (Ellis 4.1, eq.107). C6: Milne (a = t, k = -1) full Riemann = 0 (Ellis 4.3.1c); k = -1, a = const has rho < 0. C7: any k < 0 rescales exactly to k = -1. DISCREPANCY IN A RESTATING SOURCE, recorded not repaired: Baumann 0907.5424v2 eq.(109) prints R_ij = delta_ij[2 adot^2 + a addot + 2k/a^2]; the computed r-form value is R_rr = (a addot + 2 adot^2 + 2k)/(1 - k r^2), so the printed k-term (2k/a^2 against 2k, and delta_ij against the spatial metric) matches only at k = 0 in Cartesian coordinates. R_00 and the Ricci scalar in the same equation, and the Friedmann equations (110)-(111), are correct (C2). It is a misprint in a problem-set hint, touches no tree statement, and is not a refutation of anything. First run had 3 FAIL that were sympy simplification artefacts (sinh/tanh and sin/tan identities left unreduced); rewriting to exponentials before the zero test (function iszero) clears them, and a debug run printed the four surviving Milne Riemann residues each simplifying to 0.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"C. Millard, B. L'Huillier & M. Douspis, 'Model independent test of the FLRW metric and the curvature in light of DESI DR2', arXiv 2601.20293v1 (2026)","effect":"confirms","what":"O_k litmus test of the FLRW metric with Pantheon+/DES Y5 SNIa and DESI DR2 BAO: FLRW not ruled out once high-z Pantheon+ systematics are excluded; curvature consistent with zero within ~3 sigma with dataset-dependent sign preference (Table 1). Tests whether OUR universe is FLRW, which the tree never claims; says nothing against the metric as a family of exact solutions.","read_status":"READ (pp.1,3-5,10-19)"},
 {"ref":"Planck Collaboration, 'Planck 2018 results. VI', arXiv 1807.06209v4","effect":"confirms","what":"Omega_K = 0.0007 +/- 0.0019 (eq.47b): flat to 0.2 % at 1 sigma, sign of k unsettled. Context only.","read_status":"READ (pp.1,15,39-42,71)"},
 {"ref":"discover_papers sweep (FLRW, Robertson-Walker, spatial curvature, cosmic topology, Copernican principle): 2609.29377, 2606.18437, 2604.07244, 2604.05822, 2509.01320, 2411.19252, 2207.09995, 2207.05765, 2209.14918, 2107.02296","effect":"extends","what":"Observational tests of the cosmological principle and of FLRW as a model of our universe (inhomogeneous curvature, dipole cosmology, Copernican tests). None found that contradicts or narrows the FRW metric form or its uniqueness under exact homogeneity and isotropy, which is a theorem about maximally symmetric 3-spaces. Titles and abstracts only.","read_status":"NAMED-NOT-READ (abstracts only)"}
],
"lacked_data":"M's hypothesis tested for this result: the FRW metric forms carry NO datum. They follow from exact homogeneity and isotropy alone -- the t = const slices must be maximally symmetric 3-spaces, hence of constant curvature k/a^2 (C5, Ellis 4.1) -- and the Einstein tensor is a computation, re-done here from scratch for arbitrary a(t) and matching the restated source term for term (C2). Friedmann (1922/24), Robertson and Walker (1935/36) lacked the measurement of the sign of k for our universe, and it is still not settled: Planck+BAO give Omega_K = 0.0007 +/- 0.0019 and DESI DR2 litmus tests allow either sign (2601.20293). That datum matters only to a claim that OUR universe is open or flat; the tree uses k = -1 and k = 0 as exact witnesses and makes no such claim. Evidence against M's hypothesis for this item: complete agreement of source, re-derivation and tree on every metric component and every printed frame value. The only discrepancy found in any source is a misprinted k-term in a problem-set hint (Baumann eq.109), which is a discrepancy, not a refutation, and nothing in the tree uses it. What the audit did find is not missing data but a missing matter HYPOTHESIS in one tree sentence (rho > 0 attached to 'general a(t)' at nonstatic.py:98-99) and a slicing qualifier omitted at nonstatic.py:104-106 that the same passage supplies at nonstatic.py:87.",
"grade":"NARROWED",
"grade_evidence":"The external result itself STANDS: the tree's metrics (nonstatic.py:405, 450-451) are exactly Baumann 0907.5424 eq.(2)-(3)/(106) and Ellis & van Elst gr-qc/9812046 eq.(104)-(105) for k = -1 and k = 0; sympy (41 checks, 0 FAIL) re-derives their Einstein tensor for arbitrary a(t), the Friedmann/acceleration equations, constant-curvature slices, geodesic comoving flow, Milne as the a = t member, and every frame value the tree prints (W = cosh chi, W = 1, m3 = 0, j = 0, m = (4 pi/3) rho R^3). It is graded NARROWED -- and only for that reason -- because the tree's use attaches a conclusion on a larger class than it holds on: nonstatic.py:98-99 states rho = 3(adot^2 - 1)/(8 pi a^2) > 0 for open FRW whose witness is built for 'general a(t)' (nonstatic.py:450, canonical hypothesis 'general scale factor a(t) > 0'), and C4 exhibits a(t) = 2 + t/2 with rho = -9/(8 pi (t+4)^2) < 0; the '> 0' needs the source's matter hypothesis (perfect fluid, mu > 0; Ellis sec.4, 5.2), which the next clause supplies for dust (C4: rho = 3C/(8 pi a^3)). Second, nonstatic.py:104-106 states 'precisely k < 0' without the comoving-slicing qualifier the source form presupposes (supplied at nonstatic.py:87; the slicing-dependence itself computed in audits/frw-open-contraction.json C6). NOTHING THAT RESTS ON IT FALLS: ledger D10 and nonstatic.SUSTAINING_FORCES_NEGATIVE_RHO / NEC_ON_A_CONTRACTING_POSITIVE_MASS_CONFIGURATION need one contracting witness with rho > 0 and the NEC satisfied -- open dust supplies it exactly (C3, C4; nonstatic.py:455-468); specthm's K0 note (specthm.py:1553) uses 'open FRW dust' as a gauge-only witness, already carrying 'dust'. No datum moves anything.",
"what_would_change_the_grade":"To STANDS: nonstatic.py:98-99 reading 'rho = 3(adot^2-1)/(8 pi a^2), > 0 for open dust (or any matter with adot^2 > 1)' and nonstatic.py:104-106 carrying 'in comoving slicing' -- wording changes in research/, not made here. To WRONG: a verdict resting on rho > 0 for an open FRW with adot^2 <= 1, or on 'k < 0' as a slicing-independent property -- none found among rests_on_it. To DATA-DEPENDENT: a verdict resting on our universe being open or flat (Omega_K unsettled in sign) -- none found. To OPEN: none; everything here is finite and closed-form and was computed.",
"reverify_command":"python3 "+D+"/rederive/"+K+".py",
"report_path":D+"/audits/"+K+".json"
}
json.dump(r,open(D+"/audits/"+K+".json","w"),indent=1)
print("written")
