import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
r={
"key":"frw-open-contraction",
"name":"FRW: open (k < 0) FRW contracts by this criterion, flat does not; open FRW as positive-mass NEC-satisfying witness",
"source":{
 "located":"The FRW metric and its Friedmann/LTB energy reading are classics with no arXiv copy (Friedmann 1922/1924; Lemaitre 1933; Tolman 1934; Bondi 1947; Misner & Sharp 1964). Read via exact restatements: (1) K. Enqvist, 'Lemaitre-Tolman-Bondi model and accelerating expansion', arXiv 0709.2044 (2007), eq.(2.2) FRW = X -> a/sqrt(1-kr^2), A -> a r; eq.(2.9) LTB g_rr = A'^2/(1-k(r)) with 'the FRW metric is the limit A -> a r and k(r) -> k r^2'; eq.(2.3) T includes rho_Lambda; eq.(2.15) Friedmann H^2 = 8piG(rho_M+rho_Lambda)/3 - k/a^2. (2) A. Escriva, arXiv 2504.05813v3 (2025), eq.(2.2)-(2.5): comoving gauge, Gamma = R'/B, Gamma = sqrt(1+U^2-2M/R) 'the generalised Lorentz factor'; eq.(3.3) FLRW background M_b = 4 pi rho_b R^3/3, U = H R. (3) S. A. Hayward, arXiv gr-qc/9408002v2, eq.(4) E an invariant, eq.(27) 1-2E/r = e^{-lambda} r'^2 - rdot^2 ('the form actually given by Misner & Sharp'), eq.(32a),(33) E = int 4 pi r^2 rho r' for a perfect fluid with regular centre. (4) P. Jai-akson & Y. Yokokura, arXiv 2601.03077 (2026), eq.(8) M defined from (Dr)^2 (foliation-invariant), eq.(46),(50): on radial (Kodama) slices theta_(u) = 0.",
 "read_status":"READ-VIA-RESTATEMENT",
 "via":"alphaXiv answer_pdf_queries on 0709.2044 (pp.1-17), 2504.05813 (pp.1,4-11,13-16,23-27), gr-qc/9408002 (pp.1-2,4,6-8,11-16,18-21), 2601.03077 (pp.1-2,4-6,8,10-12,20,22-23,34,47-48), 1807.06209 (pp.1,39-42,62,71). Friedmann 1922/24, Lemaitre 1933, Tolman 1934, Bondi 1947, Misner-Sharp 1964: NAMED-NOT-READ (restated only). The tree's own derivation (nonstatic.py:91-107, 441-468, 655-666) re-read at HEAD 91af62f."
},
"published_statement":"As restated (Enqvist 0709.2044 eq.2.2, 2.9): the FRW metric is the LTB metric ds^2 = -dt^2 + A'^2/(1-k(r)) dr^2 + A^2 dOmega^2 with A = a(t) r and k(r) = k r^2, in coordinates comoving with the matter and t the fluid's proper time. Hence (Escriva 2504.05813 eq.2.3-2.5, comoving gauge) Gamma = R'/B = sqrt(1 - k r^2) = sqrt(1 + U^2 - 2M/R), with M = 4 pi rho R^3/3 on the FLRW background (Escriva eq.3.3; Hayward eq.33). Gamma > 1 (the tree's 'contraction') iff k < 0 at r > 0; Gamma = 1 iff k = 0. Dust: rho + p = rho (p = 0).",
"published_hypotheses":[
 "GR, 4D, spherical symmetry about the chosen centre (FRW is isotropic about every point)",
 "homogeneous isotropic perfect fluid, T = (rho+p) u u + p g (Escriva eq.2.1; Enqvist eq.2.3 specialises to dust + rho_Lambda)",
 "comoving slicing AND threading: t = proper time of the fluid, zero shift (Escriva p.3 'comoving gauge'; Enqvist p.3-4 'spatial coordinates comove ... time coordinate measures the proper time of the comoving fluid')",
 "k(r) = k r^2 with k(r) < 1 (Enqvist eq.2.9 below) -- the FRW limit of LTB",
 "regular centre for M = int 4 pi R^2 rho dR (Hayward eq.33; Escriva eq.2.4)",
 "rho > 0 is a matter hypothesis, not a consequence of k < 0: rho = 3(adot^2 + k)/(8 pi a^2)",
 "NEC contraction = rho + p; equality with rho requires p = 0 (dust) and Lambda = 0 when rho is read off the Einstein tensor"
],
"hypothesis_drift":[
 "DROPPED -- comoving slicing, at driven.py:216-217 ('in FRW the criterion is exactly k < 0') and nonstatic.py:104-107 ('in FRW the contraction condition is precisely k < 0'). Gamma is a frame component: C6 shows, at the same events, OPEN dust FRW (a=1, C=1, chi=0.3; comoving Gamma = 1.045338514) has Gamma' = sqrt(1-2m/R) = 0.952505848 < 1 in the U'=0 (Kodama) slicing, and FLAT dust FRW (comoving Gamma = 1, U = 0.2) has Gamma' = 1.231845026 > 1 in a slicing tilted by rapidity -0.5. So 'open contracts, flat does not' holds in comoving slicing and in no slicing-free sense. The tree supplies the general principle itself at driven.py:284-293 ('m IS A SCALAR. Gamma IS NOT ... a property of the FOLIATION and not of the spacetime') and nonstatic.py:87 ('in geodesic slicing'), and canonical.json lists the hypothesis; the FRW-specific sentences omit it. A qualifier missing at the site, supplied 67 lines later in the same file -- not a refutation.",
 "DROPPED -- dust (p = 0), at driven.py:245-247 ('OPEN FRW (rho > 0, m > 0, j = 0, and the NEC contraction equals rho, STRICTLY SATISFIED)') and drivensource.py:68-71 ('open FRW holds contraction with rho > 0, m > 0 and the NEC contraction equal to rho'). The source it carries from, nonstatic.py:100, says 'for open dust', and nonstatic.open_dust_nec (455-468) computes dust only. For p = w rho the NEC contraction is (1+w) rho (C3): radiation gives 4 rho/3. The EQUALITY is dust-only; the POSITIVITY (the only thing the carried verdicts use) holds for any fluid with rho + p > 0.",
 "DROPPED -- rho > 0 needs a matter law: nonstatic.py:450 builds the witness for 'general a(t)', and for general a(t) rho = 3(adot^2 - 1)/(8 pi a^2) has either sign (C2). driven.py:245-246 attaches rho > 0, m > 0 to 'OPEN FRW' without the matter law; nonstatic.py:98-102 pairs them correctly with dust (adot^2 = 1 + C/a). m > 0 <=> rho > 0 <=> adot^2 > 1 (C2, m = 4 pi rho R^3/3 exactly).",
 "DROPPED -- Lambda = 0, at driven.py:246 and drivensource.py:70: the tree reads rho off the Einstein tensor (nonstatic.witness, 400-415), so with a cosmological constant rho_tree = rho_M + Lambda/(8 pi) while the NEC contraction is rho_M; the difference is -Lambda/(8 pi) (C4). Positivity of the NEC contraction survives.",
 "WEAKENED (scope) -- 'Two exact witnesses hold contraction forever' (driven.py:243-244; nonstatic.py:91-92) holds per COMOVING SHELL (Gamma = cosh chi is t-independent, C7). At a fixed AREAL radius in the same comoving slicing Gamma^2 = 1 + R^2/a^2 -> 1 as open dust expands (C7: 3.816 at s=1, 1.0029 at s=4, 1 + 9.0e-7 at s=8). The tree's own anchor lemma and displacement bound (driven.py:250-262) address fixed areal radius, so this is a scope note, not an error.",
 "ADDED -- none found. The regular-centre restriction chi > 0 is carried (nonstatic.py:94 'at every chi > 0')."
],
"data_at_publication":[
 {"quantity":"any numerical input of the witness","value_then":"none: the witness is an exact solution with symbolic a(t) and dust constant C (nonstatic.py:446-468); canonical.json data_used = []","value_now":"none","source_now":"n/a","moves_conclusion":"no -- there is no datum to move"},
 {"quantity":"spatial curvature of the real universe, Omega_K (context only; the tree never claims the real universe is open)","value_then":"not used by the tree","value_now":"Omega_K = 0.0007 +/- 0.0019 (68 %, Planck TT,TE,EE+lowE+lensing+BAO, eq.47b); Planck TT,TE,EE+lowE alone -0.044 (+0.018/-0.015)","source_now":"Planck 2018 VI, arXiv 1807.06209v4, eq.(46b),(47b), read at source","moves_conclusion":"no -- the witness is a mathematical existence proof, not a claim about our universe. Illustration (C8): with comoving Gamma^2 - 1 = Omega_K (R H0/c)^2, the real universe's comoving 'contraction' at the Proxima span is +6.0e-23 at the central value and changes sign within 1 sigma (-1.0e-22 at -1 sigma). Were any verdict to rest on the REAL universe being open, it would be DATA-DEPENDENT; none does."}
],
"rederivation":{
 "method":"sympy",
 "script_path":D+"/rederive/frw-open-contraction.py",
 "outcome":"ALL PASS, exit 0 (output in rederive/frw-open-contraction.out). C1: Einstein tensor of FRW in comoving slicing with general a(t) computed from scratch; Gamma = cosh chi, 1, cos chi for k = -1, 0, +1; Gamma^2 - 1 = -k f_k^2 (LTB 2E = -k r^2, Enqvist k(r) = k r^2); p_r = p_T; j = 0. C2: rho = 3(adot^2 + k)/(8 pi a^2) and m = (4 pi/3) rho R^3 exactly for all k. C3: rho + p = (adot^2 + k - a addot)/(4 pi a^2); open dust NEC - rho = 0 and rho = 3C/(8 pi a^3) (nonstatic.py:455-468 reproduced); equality fails for w != 0. C4: with Lambda, NEC - rho_tree = -Lambda/(8 pi). C5 (z3, 4 unsat + 2 sat vacuity guards): in the areal-comoving chart Gamma^2 = 1 - k r^2, Gamma^2 > 1 <=> k < 0 at r > 0. C6: boost of the slicing preserves Gamma^2 - U^2 = 1 - 2m/R; open dust untrapped event has a slicing with Gamma' = 0.952505848 < 1; flat dust has a slicing with Gamma' = 1.231845026 > 1; z3 proves every untrapped m > 0 event has a U' = 0 slicing with Gamma'^2 < 1 (negation unsat, guard sat). C7: fixed-R Gamma decays to 1. C8: Omega_K illustration.",
 "agrees_with_source":"yes"
},
"later_literature":[
 {"ref":"P. Jai-akson & Y. Yokokura, arXiv 2601.03077 (2026), 'Revisiting Spherically Symmetric Spacetime I: Geometro-Hydrodynamics'","effect":"extends","what":"Misner-Sharp M defined from (Dr)^2 is foliation-invariant (eq.8); frame transformations between foliation-adapted frames (sec.4.1); on radial slices the vertical vector is the Kodama vector with theta_(u) = 0, i.e. U = 0 (eq.46, 50). This is the frame-freedom C6 uses: Gamma is frame-dependent, m is not -- it confirms the tree's own section-6 gauge point and makes the comoving-slicing hypothesis of the FRW sentence load-bearing.","read_status":"READ (pp.1-2,4-6,8,10-12,20,22-23,34,47-48)"},
 {"ref":"A. Escriva, arXiv 2504.05813v3 (2025)","effect":"confirms","what":"Gamma = R'/B = sqrt(1+U^2-2M/R) in the comoving gauge (eq.2.3-2.5); FLRW background M_b = 4 pi rho_b R^3/3, U = HR (eq.3.3); Gamma < 0 at type-II throats shows Gamma is not bounded below by 1 even in comoving gauge.","read_status":"READ"},
 {"ref":"Planck Collaboration, arXiv 1807.06209v4 (2018/2021), eq.(47b)","effect":"confirms","what":"Omega_K = 0.0007 +/- 0.0019: the real universe is flat to 0.2 % and the sign of k is unsettled; irrelevant to the witness (a mathematical existence proof), relevant only to any reading of the witness as a feature of our universe, which the tree does not make.","read_status":"READ (pp.1,39-42,62,71)"},
 {"ref":"discover_papers sweep (Misner-Sharp, generalised Lorentz factor, FLRW, slicing, Kodama, open universe): 2609.04572, 2609.25763, 2512.17526, 2602.06509, 2010.07896, 2506.04469","effect":"confirms","what":"No paper found that contradicts or narrows the FRW Gamma = sqrt(1-kr^2) identity or the dust NEC = rho equality; the thermodynamic/apparent-horizon papers use the same M = 4 pi rho R^3/3 in non-flat FLRW. Titles and abstracts only.","read_status":"NAMED-NOT-READ (abstracts only)"}
],
"lacked_data":"M's hypothesis tested for this result: there is NO datum in it. The claim is an identity about an exact solution: Gamma = f_k'(chi) in comoving slicing follows from the FRW metric alone (C1, any a(t), any perfect fluid), and the dust NEC equality from p = 0 (C3). The classic authors (Friedmann 1922/24, Lemaitre 1933, Tolman 1934, Bondi 1947, Misner-Sharp 1964) lacked no measurement this depends on, and nothing later moves it: the re-derivation from the Einstein tensor agrees with the restated source term for term. The one piece of data that came later -- the measured curvature of our universe, Omega_K = 0.0007 +/- 0.0019 (Planck 2018 + BAO) -- is irrelevant to the witness and would matter only to a claim that OUR universe supplies contraction; the tree makes no such claim (it would be DATA-DEPENDENT and ~1e-22 at the Proxima span if it did, C8). Evidence against M's hypothesis for this item: complete agreement. What the audit did find is not missing data but missing HYPOTHESES in the tree's carried sentences (comoving slicing at driven.py:217; dust and Lambda = 0 at driven.py:245-247 and drivensource.py:68-71) -- and the tree states the slicing principle itself at driven.py:284-293.",
"grade":"NARROWED",
"grade_evidence":"The external result STANDS as published: re-derived from the Einstein tensor (sympy, C1-C3) and machine-checked (z3, C5: 4 obligations unsat, 2 vacuity guards sat), in agreement with Enqvist 0709.2044 eq.(2.2),(2.9), Escriva 2504.05813 eq.(2.3)-(2.5),(3.3) and Hayward gr-qc/9408002 eq.(27),(33). It is graded NARROWED because the tree states it on a larger class than it holds on at named sites: (i) driven.py:216-217 and nonstatic.py:104-107 drop 'comoving slicing' -- C6 exhibits, at the same events, open dust with Gamma' = 0.9525 < 1 and flat dust with Gamma' = 1.2318 > 1 in other slicings, so 'open contracts, flat does not' is a comoving-slicing statement (the tree's own driven.py:284-293 says Gamma is foliation-dependent, so this is an omitted qualifier, not a contradiction); (ii) driven.py:245-247 and drivensource.py:68-71 drop 'dust' and 'Lambda = 0' from 'the NEC contraction equals rho' (radiation: 4 rho/3; with Lambda: NEC - rho = -Lambda/8pi), which the carried source nonstatic.py:100 restricts to dust; (iii) rho > 0 is attached to 'open FRW' generically at driven.py:245-246 while it needs a matter law. NOTHING THAT RESTS ON IT FALLS: driven.NEGATIVE_MASS_NECESSARY and 'm < 0 sufficient, not necessary, off staticity' need one slicing with Gamma > 1 and m > 0 -- open dust in comoving slicing supplies it (C1-C3); drivensource.EMWARP_ROLE and driven.SUSTAINING_FORCES_NEGATIVE_RHO need an NEC-satisfying contracting witness -- rho + p = rho > 0 for open dust, and rho + p > 0 for any open perfect fluid with rho + p > 0. No moved datum exists.",
"what_would_change_the_grade":"To STANDS: the carried sentences at driven.py:216-217, 245-247 and drivensource.py:68-71 (and nonstatic.py:104-107) carrying 'in comoving slicing' and 'open dust, Lambda = 0' -- a wording change in research/, not made here. To WRONG: a verdict that rests on 'contraction is exactly k < 0' as a slicing-independent property of the spacetime, or on NEC = rho for a non-dust fluid -- none found among rests_on_it. To DATA-DEPENDENT: a verdict that rests on the REAL universe being open (Omega_K > 0), which Planck+BAO leaves unsettled at 1 sigma -- none found.",
"reverify_command":"python3 "+D+"/rederive/frw-open-contraction.py",
"report_path":D+"/audits/frw-open-contraction.json"
}
json.dump(r,open(D+"/audits/frw-open-contraction.json","w"),indent=1)
print("written")
