import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S=D+"/rederive/gr-qc_0209036.py"
r={
"key":"gr-qc/0209036",
"name":"Fewster & Roman, Null energy conditions in quantum field theory (PRD 67 044003) -- no quantum inequalities along null geodesics in 4D Minkowski; timelike-worldline QNEI in globally hyperbolic spacetimes",
"source":{"located":"arXiv gr-qc/0209036v2 (dated Sept 10 2002, revised Nov 25 2002; arXiv stamp 26 Nov 2002), ESI 1205; journal ref Phys. Rev. D 67, 044003 (2003) as cited by 2003.01815 ref.[101], 2111.05772 ref.[16], 2510.26247 ref.[47], 2108.06068 ref.[28], each adding '[Erratum: Phys. Rev. D 80, 069903 (2009)]'",
 "read_status":"READ",
 "via":"alphaXiv get_paper_content(fullText=true) -- the complete v2 text, Secs. I-IV, endnotes [34]-[46]. NOT READ: the PRD journal version and the 2009 Erratum (PRD 80 069903); arxiv.org and inspirehep.net are blocked by the egress proxy and no arXiv version carries the erratum; its content is unknown here."},
"published_statement":"Abstract (verbatim): 'For the quantised, massless, minimally coupled real scalar field in four-dimensional Minkowski space, we show (by an explicit construction) that weighted averages of the null-contracted stress-energy tensor along null geodesics are unbounded from below on the class of Hadamard states. Thus there are no quantum inequalities along null geodesics in four-dimensional Minkowski spacetime. This is in contrast to the case for two-dimensional flat spacetime, where such inequalities do exist. ... the renormalized expectation value of the stress energy tensor evaluated in these states satisfies the averaged null energy condition (as expected) ... However, we also show that in any globally hyperbolic spacetime the null-contracted stress energy averaged over a timelike worldline does satisfy a quantum inequality bound (for both massive and massless fields).' Theorem II.1: '<rho(f)>_omega [= INT dlambda f(lambda) <:T_ab: l^a l^b>_omega(gamma(lambda)), gamma(lambda)=lambda l^a] is unbounded from below as omega varies over the class of Hadamard states.' Theorem III.1: for (M,g) globally hyperbolic, l^a a smooth null field on a tubular neighbourhood of a smooth timelike curve gamma, omega_0 any Hadamard state of the Klein-Gordon field of mass m>=0, and any smooth real compactly supported g: INT dtau <:T_ab: l^a l^b>_omega(gamma(tau)) g(tau)^2 >= -INT_0^inf (dalpha/pi) Fhat(alpha,-alpha) for all Hadamard omega, normal ordering relative to omega_0; in 4D Minkowski, massless, inertial: >= -((v.l)^2/12pi^2) INT g''(tau)^2 dtau (III.10); Gaussian g: -(v.l)^2/(64 pi^2 tau0^4) (III.13).",
"published_hypotheses":[
 "H1 field: quantised, FREE, massless, MINIMALLY COUPLED real scalar (Sec. II); massive case only 'we comment that our results generalise directly' / 'we expect this result to hold for massive fields as well' (Secs. I, IV) -- asserted, not proven",
 "H2 spacetime: four-dimensional MINKOWSKI (Sec. II); curved spacetime only 'we have no reason to believe that a null worldline QNEI is any more likely to exist in curved spacetime' (Sec. IV) -- not proven",
 "H3 states: Hadamard (in Minkowski: smooth normal-ordered two-point function, endnote [35]); the counterexample is a family of vector states vacuum + multimode two-particle, momenta cut at Lambda0/alpha inside a cone of half-angle arccos(1-alpha) about l, converging to the vacuum in norm",
 "H4 sampling: f smooth, NONNEGATIVE, COMPACTLY SUPPORTED, INT f = 1, along an affinely parametrised null geodesic -- i.e. a finite null segment; Lambda0 chosen with Re fhat >= 0 on [-2Lambda0, 2Lambda0]; parameters 2nu+3/2 < sigma < 2nu+2",
 "H5 renormalisation: normal ordering w.r.t. the Minkowski vacuum",
 "H6 ANEC consistency (Sec. II D): each omega_alpha obeys ANEC in the lim-inf form (II.36), shown by replacing fhat with its distributional limit 2pi f(0) delta; 'This may also be confirmed by a more careful analysis' (not given). ANEC itself attributed to Klinkhammer (dense set of Fock states) and Wald-Yurtsever (large subclass of Hadamard states), Minkowski",
 "H7 timelike QNEI (Thm III.1): globally hyperbolic (M,g); FREE Klein-Gordon field (minimally coupled; 'Klein-Gordon field of mass m >= 0'); Hadamard states; g smooth real compactly supported; normal ordering relative to a Hadamard reference state omega_0 (bound depends on omega_0); proof 'identical to' Fewster CQG 17 1897 (2000) [14], not reproduced",
 "H8 interacting fields: only a heuristic -- the Buchholz-Verch/Woronowicz remark that in AQFT with d>2 there are no nontrivial observables localised on a bounded null segment, 'Given further reasonable conditions ... this could provide a general argument' (Sec. IV, endnotes [45],[46]) -- not a theorem",
 "Year 2002: known then -- QWEIs for free scalar/Dirac/EM/Proca; 2D null QEI (Ford-Roman 1995 Lorentzian sampling); FHR spatial no-go (gr-qc/0208045, 'closely related construction'); ANEC for free fields in flat space. Not known then: SNEC (2018), DSNEC (2021), ANEC for general interacting QFTs in Minkowski (2016-17), Fewster-Osterbrink nonminimal no-go (2007), QNEC proofs (2015-19)."],
"hypothesis_drift":[
 "DROPPED field content (H1) -- bounds.py:136-142 presents as 'its abstract:' a quotation that begins mid-sentence at 'weighted averages ...', eliding the abstract's opening clause 'For the quantised, massless, minimally coupled real scalar field in four-dimensional Minkowski space, we show (by an explicit construction) that', which is exactly the field hypothesis; the quoted segments are otherwise verbatim (the closing ', where such inequalities do exist' is replaced by a period). No ellipsis marks the cut.",
 "DROPPED field content (H1) -- bounds.py:149-150 'over a FINITE null segment no QEI exists in 4D' states the no-go with no field qualifier; the source proves it for the free massless minimally coupled scalar only (massive: expected; interacting: heuristic H8).",
 "DROPPED field content and FLAT SPACETIME (H1, H2) -- anec.py:58-59 'Fewster & Roman stands: there are no quantum inequalities along null geodesics in 4D' and anec.py:203; index3.py:361 'Register 5537: there are no quantum inequalities along null geodesics in 4D'. 'Minkowski' and the field are absent; the source proves nothing in curved spacetime. (nullbound.py:34-38 carries both hypotheses correctly: 'massless minimally coupled scalar in FOUR-dimensional Minkowski space'.)",
 "DROPPED minimal coupling / free Klein-Gordon / Hadamard / reference-state (H7) -- bounds.py:150-152 'Fewster-Roman also prove that the null-CONTRACTED stress energy smeared along a TIMELIKE worldline is bounded, in any globally hyperbolic spacetime'. Theorem III.1 is for the free minimally coupled KG field, Hadamard states, relative to a Hadamard reference omega_0. The drop is load-bearing in a tree that also seats nonminimal coupling: for xi != 0 there is NO state-independent QEI even for timelike smearing (Fewster & Osterbrink 0708.2450, restated in Kontou-Sanders 2003.01815 Table 3 and 2510.26247 p.3, and seated in the tree's own index3.py:1181). The inference at bounds.py:152-153 'so what matters is the DOMAIN of the smearing, not the character of the vector contracted in' holds only inside H7.",
 "WEAKENED qualifiers on ANEC (H6) -- bounds.py:147-149 'ANEC over a COMPLETE null geodesic holds (Klinkhammer; Wald & Yurtsever, and Fewster-Roman verify their own counterexample states obey it)'. The source: Klinkhammer for a dense set of Fock states, Wald-Yurtsever for a large subclass of Hadamard states, both Minkowski; F-R's own check is a formal distributional limit for their family only. The tree's sentence carries no flat-space or state-class qualifier. Later work extends the Minkowski clause (ANEC for general QFTs, 1605.08072, 1610.05308 -- NAMED-NOT-READ here, restated in 2510.26247 p.2); in curved spacetime ANEC fails in known cases and only achronal ANEC is conjectured (Kontou-Sanders 2003.01815 pp.35-36).",
 "ADDED provenance not located -- anec.py:59, nullbound.py:31, index3.py:361 cite 'the corpus's Register 5537'. The Register seats entries 1-1792 (CLAUDE.md); a grep of method/members/ for '5537' finds only WORKING-REGISTER.md:2272 'R at L5537' (a line reference in an unrelated periodic-table entry). Not located, not shown absent -- drive/ and the chat export were not searched.",
 "NO DRIFT on the domain: the canonical hypothesis 'FINITE null segment (vs complete geodesic)' matches H4 (compactly supported f) exactly; 'Hadamard states' and '4D Minkowski' at bounds.py:139-141 match; specthm.py:1740-1743 records only the citation and status words (its regex reads bounds.py's own text), adding no hypothesis."],
"data_at_publication":[
 {"quantity":"empirical inputs to Theorem II.1 / III.1","value_then":"none -- a mathematical construction; no measured constant enters","value_now":"none","source_now":"source text Secs. II-III","moves_conclusion":"no -- nothing can move"},
 {"quantity":"momentum reach of the counterexample (cutoff Lambda = Lambda0/alpha, alpha -> 0)","value_then":"unbounded: the construction needs modes of arbitrarily high momentum, nearly parallel to l","value_now":"no measured UV cutoff exists; SNEC (Freivogel-Krommydas 1807.03808) and its free-field proof (Fliss-Freivogel 2108.06068 eq.2.11) show that WITH a UV cutoff a (pencil area a^(d-2)) the finite-segment null average is bounded, <T++[f]> >= -(1/(12 pi a^(d-2) delta^2)) INT f'^2","source_now":"2108.06068 pp.3-9; 2111.05772 p.5; 2003.01815 p.25","moves_conclusion":"only under an ADDED hypothesis (an effective theory with a cutoff), not by a moved datum; with it the no-go becomes a cutoff-dependent finite bound. In the re-derivation the most negative member reached with alpha >= Lambda0/Lambda_UV scales as -(Lambda_UV/Lambda0)^(2nu+2-sigma) (= ^(4-sigma) at nu=1), finite for any finite cutoff."},
 {"quantity":"parameter window 2nu+3/2 < sigma < 2nu+2 (and paper's example nu=1, sigma=3.75, Lambda0=1,2, alpha=0.2,0.05,0.005)","value_then":"as printed","value_now":"re-checked: non-empty for every nu>0 and it forces N_alpha->1, rho_2 exponent sigma-2nu-2 < 0, rho_1 exponent 2sigma-4nu-3 > 0 (z3 unsat of the negations); 3.5 < 3.75 < 4","source_now":S,"moves_conclusion":"no"}],
"rederivation":{"method":"sympy","script_path":S,
 "outcome":"Exit 0, 24 PASS, 3 DISCREPANCY, 0 FAIL. Theorem II.1's chain re-derived: every alpha exponent of (II.12), (II.15), (II.22), (II.24) by explicit change of variables; the window (z3); (II.28) N_alpha = (1 + alpha^(2sigma-6)/(128 pi^4))^(-1/2); (II.31) from (II.29) with F_alpha = xi/(4 pi^2 alpha^2); (II.34). NUMERIC counterexample with a smooth compact bump f on [-1,1] (Re fhat > 0 on [0,2], first sign change ~5.0), nu=1, sigma=3.75, Lambda0=1: <rho(f)> computed in POSITION space along the null line from (II.29) agrees with the momentum-space double integral to 1e-6 and falls monotonically, -2.71e-5 (alpha=0.2), -1.02e-4 (1e-3), -1.82e-3 (1e-8), i.e. ~ -alpha^(-1/4) -> -inf while rho_1 ~ +alpha^(1/2) -> 0 and N_alpha^2 -> 1. Sec. III re-derived: (III.7) angular integral and prefactor 1/(12pi^2), (III.9) antiderivative u(u^2-m^2)^(3/2), (III.10) by Parseval, (III.13) INT g''^2 = 3/(16 tau0^4) giving 1/(64 pi^2 tau0^4); the DSNEC paper 2111.05772 eq.(99) independently reproduces (III.10). DISCREPANCIES, recorded not repaired, none load-bearing, in arXiv v2 (the journal version and its 2009 Erratum were not read, so these MUST NOT be quoted as errors of the published paper): (a) (II.22) and (II.24) print the prefactor N^2/(2pi)^4 where (II.20)/(II.21) with the measure d^3k/(2pi)^3 -> k^2 dk dbeta/(4pi^2) give 2N^2/(2pi)^4 -- factor 2, confirmed numerically (position-space rho_2 / printed (II.22) = 2.000000); an overall positive factor on both terms, sign and exponents untouched; (b) the order swap (II.16)->(II.17) prints weight u1^(2nu+1)/(2nu+1) where the exact swap gives (Lambda0^(2nu+1) - u1^(2nu+1))/(2nu+1); carried into (II.27): C = 1/(24 pi^2 Lambda0^4) printed vs 1/(8 pi^2 Lambda0^4) from (II.16) (factor 3), and into the alpha^(2sigma-3)/(24pi^2) coefficient of (II.29)/(II.31); the corrected kernel keeps properties (i)-(iv) the proof uses (continuous, C >= 0, same dimension, same alpha exponent), and it moves only rho_1, which -> 0; (c) Sec. III calls g^2 a Gaussian of 'variance tau0' -- its variance is tau0^2 (tau0 is the standard deviation); wording only.",
 "agrees_with_source":"partly"},
"later_literature":[
 {"ref":"Fliss & Freivogel, Semi-local Bounds on Null Energy in QFT, arXiv:2108.06068 (SciPost Phys. 12, 084 (2022))","effect":"extends","what":"Squeezed states of the free scalar in ANY d>2 make the finite-segment null average arbitrarily negative (eqs. 2.37-2.43, <T++[F]> ~ -M^(d-2)); smearing additionally over the transverse light-sheet directions does not help (Sec. 2.1); with a UV cutoff a the SNEC bound -1/(12 pi a^(d-2) delta+^2) INT f'^2 is proven for free and super-renormalisable theories -- the no-go is a statement about the continuum limit.","read_status":"READ (pp.1-13, 17-22 via answer_pdf_queries)"},
 {"ref":"Fliss, Freivogel & Kontou, The double smeared null energy condition, arXiv:2111.05772","effect":"confirms","what":"Restates F-R exactly ('finite lower bounds of null QEIs do not exist ... vacuum-plus-two-particle states'); proves that smearing in BOTH null directions gives a finite state-independent bound for free scalars in Minkowski (DSNEC, eq.1, 4D eq.136), and reproduces F-R's timelike QNEI (III.10) as its eq.(99). Confirms the tree's 'the DOMAIN of the smearing matters' within free fields.","read_status":"READ (pp.1-5, 8, 11, 15-20, 24, 27, 32-33)"},
 {"ref":"Fliss & Rolph, Curious QNEIs from QNEC, arXiv:2510.26247v2 (Apr 2026)","effect":"narrows","what":"Confirms the finite-segment no-go and gives a general argument beyond free fields (Sec. 3.1: Reeh-Schlieder makes INT g T_vv non-positive-semidefinite; dilatation + boost preserving the null line scale it by lambda^(d-2), so no state-independent bound) -- the argument uses dilatation covariance (CFT). It narrows the reach of a blanket 'no null QEI in d>2': in interacting CFTs with d>2 it derives state-independent QNEIs for null energy on a finite null interval in (u,v), smeared with a modular-kernel M and integrated uniformly over the d-2 transverse directions (eq.1.7/4.2; state-independent only through O(eps_u^0)). 'No QI along a single null geodesic' still stands; 'no QI on any finite null region' does not.","read_status":"READ (pp.1-8, 16-19, 26-28, refs)"},
 {"ref":"Kontou & Sanders, Energy conditions in general relativity and quantum field theory, arXiv:2003.01815 (CQG 37 193001 (2020))","effect":"confirms","what":"Restates F-R with its hypotheses ('four-dimensional Minkowski space for the massless minimally coupled scalar field'); the Buchholz-Verch route to general QFTs: 'no such rigorous result exists to this day' (p.25); Table 3: Klein-Gordon with xi != 0 has NO state-independent QWEI/QNEI (bounds the tree's timelike clause); ANEC in Minkowski vs curved-spacetime violations (pp.35-36). Its eq.(102) restating F-R's timelike QNEI prints (gamma-dot.k) unsquared -- a discrepancy of the review, not of F-R.","read_status":"READ (pp.1, 5, 24-25, 34-36, 50, refs)"},
 {"ref":"Fewster & Osterbrink, Quantum energy inequalities for the non-minimally coupled scalar field, arXiv:0708.2450 (J. Phys. A 41 025402 (2008))","effect":"narrows","what":"For xi != 0 no state-independent QEI exists for timelike (or null-contracted) smearing over any region -- the tree's timelike-QNEI clause at bounds.py:150-152 holds only for minimal coupling.","read_status":"NAMED-NOT-READ (restated in 2003.01815 Table 3, 2510.26247 p.3, and the tree's index3.py:1181)"},
 {"ref":"Faulkner, Leigh, Parrikar & Wang arXiv:1605.08072; Hartman, Kundu & Tajdini arXiv:1610.05308","effect":"extends","what":"ANEC over a complete null geodesic proven for general (interacting) QFTs in Minkowski spacetime -- extends the ANEC clause bounds.py:147-149 attributes partly to F-R, in flat space only.","read_status":"NAMED-NOT-READ (restated in 2510.26247 p.2, 2111.05772 p.4)"},
 {"ref":"Fewster & Roman, Erratum, Phys. Rev. D 80, 069903 (2009)","effect":"contested","what":"EXISTS (cited by four later papers) but its content was NOT read -- no arXiv copy, arxiv.org/inspirehep.net blocked. 'contested' is the nearest enum value to UNKNOWN and records no dispute: it may correct the discrepancies (a)-(c) found here, something else, or a clause the tree relies on.","read_status":"NAMED-NOT-READ"}],
"lacked_data":"M's hypothesis tested. The result is a theorem with no empirical input, so no datum the authors lacked can have moved it (evidence: every step re-derived in the script, and the only numbers in the paper are the free parameters of the construction). What they lacked in 2002 were LATER THEOREMS, and those cut both ways. FOR the result: Fliss-Freivogel 2021 extend the no-go to free scalars in every d>2 and show transverse light-sheet smearing does not rescue it; Fliss-Rolph 2025 give a general Reeh-Schlieder + dilatation/boost argument for a finite null segment beyond free fields; Kontou-Sanders 2020 restate it unchanged. AGAINST reading it broadly: (i) the unboundedness needs modes of arbitrarily high momentum (Lambda0/alpha -> infinity) -- with a UV cutoff it becomes a finite, cutoff-dependent bound (SNEC, proven for free fields with a cutoff in 2108.06068), which is a hypothesis choice, not a measurement: no UV cutoff has been measured; (ii) interacting CFTs in d>2 admit state-independent QNEIs over a finite null interval once integrated over the transverse directions (2510.26247), so 'no null QEI in 4D' is true for a single geodesic and false for some transversely extended null regions; (iii) the timelike QNEI of Thm III.1 fails for nonminimal coupling (Fewster-Osterbrink 2007). None of this refutes the paper as stated; (i)-(iii) bound the class the tree may carry it to. The 2009 Erratum is a named item the authors themselves issued and it is unread here.",
"grade":"NARROWED",
"grade_evidence":"The theorem as published STANDS on its own hypotheses: the full v2 text was read, the counterexample's chain re-derived symbolically (exponents, window by z3, N_alpha, (II.31), Sec. III constants) and numerically (<rho(f)> -> -inf as ~ -alpha^(-1/4) for a smooth compact bump f, position-space and momentum-space agreeing to 1e-6), and later literature (2108.06068, 2111.05772, 2510.26247, 2003.01815) confirms or extends it. Three printed-constant discrepancies in arXiv v2 (factor 2 in (II.22)/(II.24); factor 3 in (II.17)/(II.27); 'variance tau0') move no conclusion and are not refutations. The GRADE is NARROWED because the tree carries it past its hypotheses: bounds.py:136-142 quotes the abstract with the field clause elided; bounds.py:149-150, anec.py:58-59, anec.py:203 and index3.py:361 state the no-go without 'free massless minimally coupled scalar' and (anec.py, index3.py) without 'Minkowski'; bounds.py:150-152 states the timelike-worldline QNEI 'in any globally hyperbolic spacetime' without free/minimal coupling/Hadamard/reference state, and the tree itself seats Fewster-Osterbrink's xi>0 no-go (index3.py:1181); bounds.py:147-149's ANEC clause carries no flat-space qualifier. The single-geodesic, finite-segment, free-scalar, Minkowski statement is what is proven; the broader 'no null QI in 4D' is extended by later work for free fields in every d>2 but is not a theorem for interacting fields or curved spacetime, and 2510.26247 exhibits state-independent QNEIs on transversely integrated finite null regions in interacting CFTs.",
"what_would_change_the_grade":"To STANDS: the tree's sentences carrying the source's hypotheses (field content and Minkowski at bounds.py:149-150, anec.py:58-59, 203, index3.py:361; free minimally coupled KG, Hadamard, reference state at bounds.py:150-152; flat space at bounds.py:147-149), or a later theorem proving the null-segment no-go for interacting fields / curved spacetime and the timelike QNEI beyond minimal coupling (the last is refuted for xi != 0, so that clause can only be narrowed). Toward OPEN or lower: the 2009 Erratum (PRD 80 069903), unread here, correcting a clause the tree uses. Toward WRONG: nothing found; it would need a state-independent lower bound on a compactly supported average along a single null geodesic for the free massless minimally coupled scalar in 4D Minkowski, which the re-derived construction contradicts.",
"reverify_command":"python3 "+S+"   # exit 0; 24 PASS, 3 DISCREPANCY (A.pref factor 2 in (II.22)/(II.24); C.II17-printed/C.II27 factor 3 in (II.17)/(II.27); F.var 'variance tau0'), prints <rho(f)> = -1.817729e-03 at alpha = 1e-8",
"report_path":D+"/audits/gr-qc_0209036.json"}
json.dump(r,open(D+"/audits/gr-qc_0209036.json","w"),indent=1,ensure_ascii=False)
print("ok")
