import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "kodama-1980-mass-flux",
 "name": "Kodama energy/flux (Kodama mass), used as K(R) = INT 4 pi R^2 j W dtau = -m_1(R)",
 "source": {
  "located": "H. Kodama, 'Conserved energy flux for the spherically symmetric system and the back reaction problem in the black hole evaporation', Prog. Theor. Phys. 63, 1217 (1980) -- no arXiv copy. Restated exactly by: (i) S. A. Hayward, arXiv gr-qc/9408002v2 (PRD 53, 1938, 1996), Appendix B eqs (B1)-(B8), pp.19-20, ref.[53] = Kodama 1980 ('Kodama [53] showed that spherically symmetric space-times have a conserved current and defined an energy as the associated charge. This energy is the Misner-Sharp energy'); (ii) G. Abreu & M. Visser, arXiv:1004.1456v3 (2010), sec. III eqs (24)-(40) ('The Kodama miracle', proof reproduced), sec. VIII eqs (71)-(75), sec. IX eqs (76)-(82), ref.[1] = Kodama 1980; (iii) S. Kinoshita, arXiv:2402.16484v3 (2024), sec. I and III.A eqs (15)-(23), ref.[1] = Kodama 1980.",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "alphaXiv answer_pdf_queries on gr-qc/9408002 (pp.1-2,4,6-7,9,12-13,15-17,19-23), 1004.1456 (pp.1-7,10) and 2402.16484 (pp.1-10). Kodama 1980 itself NAMED-NOT-READ."
 },
 "published_statement": "Hayward gr-qc/9408002 App. B p.19-20: 'Kodama introduced vectors k and j which may be defined, up to orientation, by k = curl r (B1) and g(j) = -T(k) (B2) where the curl refers to the two-dimensional quotient space-time. It follows that g(k,k) = 2E/r - 1 (B3) so that k reduces in vacuo (Schwarzschild) to the stationary Killing vector ... k is spatial in trapped regions and causal otherwise ... Fixing the orientation so that k and j are future-causal for untrapped spheres ... k = e^{-lambda/2}(r' d/dtau - rdot d/dzeta) (B4a), j = (e^{-lambda/2}/(4 pi r^2))(E' d/dtau - Edot d/dzeta) (B4b). Thus k is tangent to the constant-r hypersurfaces and j is tangent to the constant-E hypersurfaces (B5). One also has 4 pi r^2 j = curl E (B6) ... both k and j are covariantly conserved (B7) ... By Gauss' law, any such conserved current u has a charge Q_u = -INT_Sigma *g(u,v) which is independent of Sigma (with fixed boundaries) ... Q_k = (4/3) pi r^3 (B8a), Q_j = INT *T(k,v) = INT_0 E' dzeta = E (B8b). The charge Q_j is the definition of energy of Kodama [53].' Abreu-Visser 1004.1456 p.3-4: k^a = eps_perp^{ab} nabla_b r (24); nabla_a k^a = 0 (30); 'Kodama also proved that in time-dependent spherically symmetric spacetimes there is another (somewhat unexpected) conserved current ... J^a = G^{ab}k_b, nabla_a J^a = 0 (31). This is a purely geometrical statement, ultimately due to the warped product form of the metric -- it is not related to the Bianchi identities'; J^a = -(2/r^2) eps_perp^{ab} nabla_b m (39). p.7 sec. IX: the W-less fixed-r flux integrates to the Brown-York energy U = r0(1 - sqrt(1 - 2m/r0)) (81), m = U - U^2/(2 r0) (82).",
 "published_hypotheses": [
  "spherical symmetry: the metric is a warped product of a (1+1) Lorentzian base with round 2-spheres, areal radius r(x^i) > 0 (Hayward p.2 'assumed implicitly'; Abreu-Visser eq.(1); Kinoshita eq.(15), fibre maximally symmetric for the mass function (21))",
  "four spacetime dimensions for the classic statement (Abreu-Visser p.2; Kinoshita generalises to D dimensions)",
  "conservation of k and of J = G.k is a GEOMETRIC IDENTITY, no field equation (Abreu-Visser eq.31 'purely geometrical'; Kinoshita p.6 'without the field equations'); interpreting J as an ENERGY current and its charge as matter energy needs the Einstein equation G = 8 pi T (Kinoshita p.1 'with assuming the Einstein equation'; Hayward (B2) uses T)",
  "no cosmological constant for charge = Misner-Sharp mass of MATTER (Kinoshita eq.(23): with Lambda the MS mass is a combination of two conserved charges; Hayward's units G = 1, Lambda absent)",
  "orientation fixed so k, j are future-causal on UNTRAPPED spheres; k timelike only where untrapped (Hayward p.19; Abreu-Visser p.3); normalisation |k|^2 = |1 - 2m/r| (Hayward B3, Abreu-Visser eq.56) -- the 'Kodama energy' depends on this normalisation (Abreu-Visser p.5 on T vs k)",
  "Hayward's (B8b) as written integrates from a regular centre zeta = 0; the charge between two spheres is the difference of E (Gauss' law 'with fixed boundaries'), which needs no centre",
  "Units G = c = 1 (Hayward eq.4)"
 ],
 "hypothesis_drift": [
  "NARROWER THAN THE SOURCE, and correctly carried (no harm): the tree's integrand INT 4 pi R^2 j W dtau (formation.py:132-136) is the Kodama flux through a sphere's world-tube ONLY when U = 0. Re-derived: g(J,n) = jW + p_r U (rederive C6a), D_t m = -4 pi R^2 (p_r U + jW) (C6b); at U = 0, k = W u exactly (C6c) and D_t m = -4 pi R^2 j W (C6d); with U != 0 the tree's integrand misses -4 pi R^2 p_r U (C6e, control). The tree names H_U0 in F1_THEOREM (formation.py:373, 380) and LEDGER.md:47 lists 'a passage with U != 0, which is outside F1'. Kodama's own statement (flux = -Delta m by Gauss/Stokes, C4-C5) needs no U = 0.",
  "ADDED, and carried: K = -m_1 (rather than Kodama's general m_initial - m_final) uses m_0 = 0 at the flat start; this is H_ENDS (formation.py:375). Re-derived C7g-C7h. LEDGER.md:47 itself states the general form 'priced by F1 as m_final(R) - m_initial(R)' for an observed throat.",
  "NORMALISATION, consistent (no drift): the W factor in K is Hayward's normalisation k = curl r, |k| = W at U = 0 (B3). Dropping it gives the Eulerian integral E = R(W_1 - 1) (formation.py:135), which is MINUS the Brown-York energy of Abreu-Visser eq.(81) (rederive C7k-C7l) and NOT -m_1 (vacuity guard C7j). The tree keeps E and K separate and labels K as the Kodama one -- correct.",
  "WORDING, not a drift in content: 'Kodama mass' (formation.py:155, 748, 908, 1037). Kodama defined an ENERGY, the charge Q_j (Hayward B8b: 'The charge Q_j is the definition of energy of Kodama'; Hayward pp.16, 21 argues E is energy, not mass). What the tree computes -- m_1(R_s+) - m_1(R_s-) -- is exactly the Kodama charge on any slice segment between the two spheres bounding the shell (Gauss' law, rederive C5; value 2.00010e-02 reproduced independently, C8b). The label is the tree's; the number is Kodama's charge.",
  "UNSTATED at a restating site, harmless: ledger.py:642 and specthm.py:1138 ('the Kodama energy the passage carries is -m_1(R), the object's own ENCLOSED negative mass'). 'Enclosed' needs a regular centre, H_EFE and Lambda = 0 (already recorded in the misner-sharp-1964 audit). For THIS object all three hold: the seated metric lives on R^3 with m_1 = O(R^3) at the centre (rederive C8f, m_1/R^3 -> about -1.84e4), and H_EFE is named with no Lambda (formation.py:372). No verdict moves.",
  "SCOPE of 'BY ANY ROUTE, AT ANY SPEED, IN ANY LAPSE' (formation.py:138): 'route' is any profile f(t) within the U = 0 family (per-df integrand free of fdot, rederive C7e), not any spacetime path between the endpoints; the tree says so (H_U0 in F1_THEOREM). Named here so it is not read more widely.",
  "NO DRIFT on dimension or symmetry: H_SPH (formation.py:371) is the source's spherical warped product in 4D; the family's metric is diagonal with R^2 dOmega^2 (formation.py spherical_form)."
 ],
 "data_at_publication": [
  {"quantity": "numerical inputs of Kodama's result", "value_then": "none -- a geometric identity of spherically symmetric metrics (1980)", "value_now": "none", "source_now": "rederive C1-C5, symbolic (sympy, independent Einstein tensor)", "moves_conclusion": "no; there is no datum for the identity to depend on"},
  {"quantity": "seated-object parameters m = a = 1/50, R_s = 200 (geometric units, certify's unit L) in the tree's evaluation", "value_then": "the tree's own design constants (certify.M_SEATED, A_CORE, R_SHELL), not external data", "value_now": "same", "source_now": "formation.py docstring sec. 0; recomputed independently at 40 digits (rederive C8a-C8f)", "moves_conclusion": "no; not a measured quantity. Table and shell jump 2.0000999999998e-02 reproduced to the printed digits"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/kodama-1980-mass-flux.py",
  "outcome": "ALL PASS, 29/29 (output rederive/kodama-1980-mass-flux.out; ~11 s). Independent Einstein tensor from Christoffels for ds^2 = -e^{2Phi(t,r)}dt^2 + e^{2Lam(t,r)}dr^2 + R(t,r)^2 dOmega^2, no research/ import. C1a k(R) = 0; C1b g(k,k) = 2m/R - 1; C2 Div k = 0; C3 Div(G.k) = 0 with NO field equation; C4 4 pi R^2 J = curl m (Hayward B6); C5 Gauss: charge density on t = const = dm/dr, so charge between spheres = Delta m; C6a-e the world-tube flux g(J,n) = jW + p_r U, MS-t, k = W u at U = 0, the tree's integrand at U = 0, and a nonzero-residual CONTROL at U != 0 (H_U0 load-bearing); C7a-d the tree's family (U = 0, W = W_1^f, m = (R/2)(1 - W_1^{2f}), j form) from this independent tensor; C7e integrand per df free of fdot; C7f-C7i K = R(W_1^2 - 1)/2 = -m_1 with m_0 = 0, E = R(W_1 - 1); C7j VACUITY GUARD (W dropped does not give -m_1); C7k-l E = -U_BrownYork, m = U - U^2/2R (Abreu-Visser 81-82); C8a-f numeric on the seated object at 40 digits (table to 6 digits, shell jump 2.00010e-02 > 0, m_1(R_s+) tiny positive, K -> 1/50 inside, W_1 jumps by exactly -m/R_s, regular centre). One check (C6a) failed on first run because the EXPECTED formula in the script had p_r U with the wrong sign (my error: k = W u - U n gives +p_r U); corrected, not the source's or the tree's.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Hayward, gr-qc/9408002 (PRD 53, 1938, 1996), App. B", "effect": "confirms", "what": "restates Kodama's k, j, conservation, and charge = Misner-Sharp energy E exactly (B1-B8); (B3), (B5a), (B6), (B7), (B8b) machine-checked here (C1-C5)", "read_status": "READ (pp.19-20 and context)"},
  {"ref": "Abreu & Visser, arXiv:1004.1456v3 (2010)", "effect": "confirms", "what": "reproduces Kodama's proof: Div k = 0 (30), Div J = 0 as a purely geometrical identity (31), J = -(2/r^2) eps grad m (39); sec. IX shows the W-less fixed-r flux yields the Brown-York energy (81) -- the tree's E, as opposed to its Kodama K (C7k). Notes the Kodama vector is only PARALLEL to the static Killing vector in general (not used by the tree). Discrepancy recorded, not an error of the tree: p.7 text says 'via the Einstein equations 8 pi G_ab = T_ab' while eq.(77) itself follows from G_ab = 8 pi T_ab (checked by hand from their eq.76).", "read_status": "READ (pp.1-7,10)"},
  {"ref": "Kinoshita, arXiv:2402.16484v3 (2024)", "effect": "extends", "what": "Kodama vector = associated vector of a closed conformal Killing-Yano 2-form; J = G.K conserved without field equations, also for every Lovelock order and in conformally warped products; with Lambda the MS mass is a combination of two conserved charges (eq.23). Extends the class; narrows nothing the tree uses (tree: 4D GR, Lambda = 0)", "read_status": "READ (pp.1-10)"},
  {"ref": "Kinoshita arXiv:2103.07408; Kodama-like axisymmetric fields arXiv:2402.18993; Maeda-Nozawa arXiv:0709.1199; f(R)/massive-gravity MS mass arXiv:1406.0577, 1502.00069", "effect": "extends", "what": "Kodama-type currents beyond 4D spherical GR (3D axisymmetric, some axisymmetric 4D classes, Gauss-Bonnet, modified gravity); the charge becomes theory-dependent once tied to matter -- outside the tree's H_SPH + H_EFE class, so no narrowing of its use", "read_status": "discover_papers abstracts only, NOT READ in full"}
 ],
 "lacked_data": "M's hypothesis tested for this result. Kodama's 1980 result is a geometric identity of spherically symmetric (warped-product) metrics: the vector k = curl r and the current J = -T.k = -G.k/8pi are divergence-free identically, and J's charge between two spheres is the difference of the Misner-Sharp mass. It takes no measured input, so there is no datum Kodama could have lacked that bears on its truth; re-derived here from an independently coded Einstein tensor (C1-C5, residual 0) with a control and a vacuity guard. What 1980 lacked was structural, not data: the CKY-2-form origin and Lovelock/D-dimensional generalisations (Kinoshita 2024), the Lambda bookkeeping (Kinoshita eq.23, Maeda-Nozawa 2008), the Brown-York comparison (Abreu-Visser 2010), and axisymmetric extensions (2021-24). Each reproduces the 4D spherical GR statement unchanged and widens the class; none moves it. The tree's use adds its own design constants (m = a = 1/50, R_s = 200), which are not measurements, and its figures were reproduced independently at 40 digits (C8). Evidence against M's hypothesis for THIS result: complete within the class the tree uses. The honest limit is not missing data but scope: the tree's integrand is the Kodama flux only at U = 0 and gives -m_1 only from a flat start, both of which the tree names (H_U0, H_ENDS).",
 "grade": "STANDS",
 "grade_evidence": "Statement: Hayward App. B (B1)-(B8) and Abreu-Visser eqs (24)-(40), (71)-(75) (READ) give Kodama's conserved current with charge = Misner-Sharp mass; the tree's K(R) = INT 4 pi R^2 j W dtau is that current's flux through a fixed-R world-tube, which at U = 0 equals -Delta m (rederive C6a-d), and on its family equals R(W_1^2 - 1)/2 = -m_1 from a flat start (C7f-h). Hypotheses: the tree uses H_SPH, H_EFE (no Lambda), H_U0, H_W, H_ENDS (formation.py:371-380) -- a SUBSET of Kodama's class (spherical, 4D), with U = 0 and m_0 = 0 correctly added and named, and H_W matching Kodama's untrapped (k timelike) orientation. Re-derivation agrees, 29/29, with an independent Einstein tensor, a U != 0 control (C6e) and a vacuity guard (C7j); the tree's seated table and shell jump 2.00010e-02 reproduced independently (C8). No datum enters. Recorded, not repaired, none moving a verdict: (i) 'Kodama mass' is the tree's label for Kodama's ENERGY (charge); the number is the charge; (ii) 'enclosed' at ledger.py:642 / specthm.py:1138 holds for this object (regular centre, C8f; Lambda = 0 by H_EFE); (iii) 'any route' means any f(t) inside the U = 0 family; (iv) a misprint in the restating paper Abreu-Visser p.7 ('8 pi G_ab = T_ab'), irrelevant to the tree. Kodama 1980 remains NAMED-NOT-READ; for a geometric identity, two exact restatements plus an independent machine re-derivation are sufficient to stand.",
 "what_would_change_the_grade": "To NARROWED: a tree verdict that applies K = -m_1 to a passage with U != 0 (the integrand then misses -4 pi R^2 p_r U, C6e), or from a non-flat start without subtracting m_0, or with Lambda != 0 left out of rho -- none found at formation.py, ledger.py:642, specthm.py:1138 or LEDGER.md:47, which all carry H_U0 and H_ENDS. To a recorded DISCREPANCY in attribution (not WRONG): reading Kodama 1980 at source and finding its current or normalisation differs from Hayward's (B1)-(B2) beyond orientation. Nothing makes the identity WRONG short of a nonzero residual in rederive C3-C5, which are closed-form computations.",
 "reverify_command": "python3 " + D + "/rederive/kodama-1980-mass-flux.py   # expects '29/29 checks pass' and 'ALL PASS', exit 0 (needs sympy, mpmath)",
 "report_path": D + "/audits/kodama-1980-mass-flux.json"
}
json.dump(rep, open(rep["report_path"], "w"), indent=1)
print("written", rep["report_path"])
