import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
rep = {
 "key": "misner-sharp-1964",
 "name": "Misner-Sharp mass identity Gamma^2 - U^2 = g^ab d_aR d_bR = 1 - 2m/R (Misner & Sharp 1964, via Hayward gr-qc/9408002 eq. (27))",
 "source": {
  "located": "C. W. Misner & D. H. Sharp, 'Relativistic equations for adiabatic, spherically symmetric gravitational collapse', Phys. Rev. 136, B571 (1964) -- no arXiv copy. Restated by S. A. Hayward, 'Gravitational energy in spherical symmetry', Phys. Rev. D 53, 1938 (1996), arXiv gr-qc/9408002v2 (revised 6 Nov 1995; v2 posted 17 Feb 2002): eq.(4) p.4, eqs.(23)-(28) pp.11-12, eqs.(31)-(35) pp.12-13, Prop.1 p.4, App.B p.19, ref.[4] p.22. Second, independent restatement: A. Escriva arXiv:2504.05813v3 eqs.(2.2)-(2.5), (2.24), refs.[50],[57] = MS 1964. Later context: Maeda & Nozawa arXiv:0709.1199v4 eq.(2.7), ref.[6].",
  "read_status": "READ-VIA-RESTATEMENT",
  "via": "alphaXiv answer_pdf_queries on gr-qc/9408002 (pp.1-7,12-13,15-17,19,21-22) and get_paper_content fullText (Greek glyphs recovered by decoding the TeX OML font bytes: 0x15=lambda, 0x10=zeta, 0x1C=tau, 0x19=pi, 0x1A=rho -- pi and rho decode to physically correct places, validating the map); answer_pdf_queries on 2504.05813 (pp.1,4-13,22-24,27,30) and 0709.1199 (pp.1-5,9-10,12). Misner & Sharp 1964 and Hernandez & Misner 1966 themselves NAMED-NOT-READ (arxiv.org e-print fetch returned proxy 403)."
 },
 "published_statement": "Hayward gr-qc/9408002 p.4 eq.(4): 'The Misner-Sharp spherically symmetric gravitational energy, or simply the energy, may be defined in units G = 1 by E = (1/2) r (1 - g^{-1}(dr,dr)) = (1/2) r + e^f r d+r d-r = (1/2) r + (1/4) e^f r^3 theta+ theta-. The form actually given by Misner & Sharp is derived in Section IV. Note that E is an invariant. Indeed, the only invariants of the metric and its first derivatives are functions of r and E.' p.11-12 eqs.(23)-(27): 'Consider any spatial hypersurface Sigma. Set up coordinates (tau, zeta) such that d/dzeta is tangent to Sigma and d/dtau is orthogonal to d/dzeta, with tau being proper time: g(d_tau,d_zeta) = 0, g(d_tau,d_tau) = -1. Define a function lambda by e^lambda = g(d_zeta,d_zeta) ... ds^2 = r^2 dOmega^2 + e^lambda dzeta^2 - dtau^2 (26) ... Denote phidot = d phi/d tau and phi' = d phi/d zeta. Then the definition (4) of E can be rewritten as 1 - 2E/r = e^{-lambda}(r')^2 - rdot^2 (27) which is the form actually given by Misner & Sharp [4], with different notation.' Prop.1 p.4: 'A metric sphere is trapped iff E > r/2, marginal iff E = r/2, and untrapped iff E < r/2.' App.B p.19: the Kodama current's charge is E, g(k,k) = 2E/r - 1. Escriva 2504.05813 eqs.(2.3),(2.5): U = (1/A) dR/dt = D_t R, Gamma = (1/B) dR/dr = D_r R, Gamma = sqrt(1 + U^2 - 2M/R), attributed to Misner-Sharp [57] in the general-lapse comoving metric -A^2dt^2 + B^2dr^2 + R^2dOmega^2.",
 "published_hypotheses": [
  "spherical symmetry, 'assumed implicitly in the Propositions, without repeated qualification'; all geometric objects respect it (Hayward p.2)",
  "r is the areal radius, area 4 pi r^2, r > 0; r = 0 is a centre (Hayward p.3-4)",
  "space-time time-orientable, d/dxi^pm future-pointing (Hayward p.3) -- needed for the SIGNS of theta^pm, not for E",
  "units G = 1 (c = 1) (Hayward eq.4)",
  "definition (4) uses no field equation; Einstein equations G = 8 pi T with no cosmological constant enter only for the variation formulas (10)-(11), (28) (Hayward p.6-7, 12)",
  "form (27) is written in a lapse-1, zero-shift gauge adapted to a spatial hypersurface Sigma (Hayward eqs.23a,b); for (27) and the first-order formulas (28) the gauge need hold only on Sigma",
  "Misner & Sharp's own setting (Hayward p.12; Escriva eq.2.1-2.3): adiabatic perfect fluid, comoving coordinates, general lapse",
  "regular centre for the enclosed-integral form E = int_0 4 pi r^2 rho r' dzeta (Hayward eq.33, 'if Sigma has a regular centre') -- not for the definition"
 ],
 "hypothesis_drift": [
  "DISCREPANCY IN A QUOTATION (misprint, not a refutation): driven.py:56-58 quotes Hayward eq.(27) as '1 - 2E/r = e^{-chi}(r')^2 - rdot^2'. The v2 text prints e^{-lambda}, lambda being the metric function of eq.(24) e^lambda = g(d_zeta,d_zeta); Hayward's coordinates are (tau, zeta) and no chi occurs in eqs.(23)-(27). If 'chi' were read as the coordinate the equation would be false (rederive C11b, nonzero residual). The tree's working identity is unaffected: driven.py V3 (driven.py:571-574) and foliation.py V1 (foliation.py:637-640) use e^{-2Lambda}, which is Hayward's form at lambda = 2 Lambda, Phi = 0 (rederive C2b, residual 0). foliation.py:381-383 and :875-876 cite the equation by number only and inherit nothing of the misprint. Recorded; nothing repaired.",
  "BROADENED, and supported: Hayward's (27) is in the lapse-1 gauge (23b); the tree (driven.py:145, foliation.py:632, nonstatic.py:26) uses the general lapse e^{2Phi}. driven.py:65-66 states the translation (Hayward's rdot = e^{-Phi} Rdot) correctly -- (23b) is exactly g(d_tau,d_tau) = -1. Machine-checked: the scalar equals Gamma^2 - U^2 for any diagonal lapse (C1), and equals (n.dR)^2 - (u.dR)^2 even with a shift (C1b); Schwarzschild gives E = M in the Schwarzschild, Lemaitre (Hayward's own gauge) and Painleve-Gullstrand (shift) charts (C5a-c). The tree's diagonal 'general metric, no ansatz' (driven.py:143-146) is WLOG locally (orthogonal coordinates exist locally on a 2-D quotient); the definition itself needs no coordinates at all.",
  "BROADENED, and supported: Misner & Sharp's adiabatic perfect fluid in comoving coordinates -> arbitrary spherically symmetric matter with radial flux j (nonstatic.py:28-30, formation.py:130-136). The definition (4) is geometric, and Hayward's general-matter variation formulas (28a),(28b) were re-derived here from the Einstein tensor in his gauge, residual 0 (C7a, C7b).",
  "ADDED GLOSS, not part of the source: 'ENCLOSED' Misner-Sharp mass (ledger.py:337 'kg of negative enclosed Misner-Sharp mass per metre'; ledger.py:367 D1). Hayward p.17: 'E is defined on spheres rather than hypersurfaces ... the general definition (4) or (27) is a function of spheres only'; the enclosed-matter integral (33) needs a regular centre AND the Einstein equations (and, per Maeda-Nozawa 0709.1199 p.1 and eq.2.7, no cosmological constant, or Lambda counted in rho). The sign statements the tree rests on (Gamma > 1 <=> m < 0 at U = 0; C8b) need none of this. Where there is no regular centre -- throatmass.py's own wormhole throat (m = r_0/2 by Prop.1's marginal case, throatmass.py:22-23), or vacuum Schwarzschild with M < 0 -- m is not the mass of anything enclosed. A wording drift on an interpretation, named here; it moves no verdict.",
  "UNSTATED at some use sites: no cosmological constant, when m is tied to matter. Maeda-Nozawa 0709.1199 eq.(2.7): the natural generalised mass with Lambda carries an extra -Lambda~ r^{n-1} term and reduces to Misner-Sharp only 'in the four-dimensional spherically symmetric case without a cosmological constant'. formation.py names H_EFE 'G_ab = 8 pi T_ab' (formation.py:124-126); throatmass.py:235 (rho = -G^t_t/(8 pi)) and tolman.py:705 (m = 4 pi R^3 p_r) leave it unstated. Harmless if vacuum energy is counted in rho / p_r; the geometric identity itself is Lambda-independent.",
  "WORDING, minor: foliation.py:857 ONLY_INVARIANT = 'Gamma^2 - U^2 = 1 - 2m/R'. Hayward p.3 also names DISCRETE invariants: 'the signs of theta^pm are geometrical invariants' (theta^pm = (2/R)(U pm Gamma), Escriva eq.3.17). They fix the orientation Gamma > |U| > = 0 on untrapped spheres, which foliation's range theorem uses (foliation.py:134-136, 'UNTRAPPED ... k = sqrt(1-2m/R)'), so INVARIANT_CRITERION (foliation.py:858) is unaffected; the continuous invariant is indeed unique (Hayward p.3-4).",
  "NO DRIFT (checked): hpscentre.py:644-645 and throatmass.py:20 use m = (r/2)(1 - r'^2), which is the identity only at U = 0; both metrics are static (throatmass.py:214-215 g = diag(-f(l), 1, r(l)^2, ...)), so the Killing-adapted slice has U = 0. formation.py:110 m = (R/2)(1 - W^2) carries H_U0 by name (formation.py:124-126). overturn.py:124-127 ('outside spherical symmetry ... m(r) has no definition') agrees with Hayward's scope; Hayward p.17 names the Hawking energy as the non-spherical quantity that reduces to E -- an extension relevant to the OPEN sphericity link, not a contradiction."
 ],
 "data_at_publication": [
  {"quantity": "numerical inputs of the identity", "value_then": "none -- a definition plus algebra (MS 1964; Hayward 1996)", "value_now": "none", "source_now": "rederive C1-C9 (sympy/z3), symbolic", "moves_conclusion": "no; there is no datum for the identity to depend on"},
  {"quantity": "G (Newtonian constant), used only in the tree's SI conversion EXCHANGE_RATE = c^2/(G*LAMBDA) (ledger.py:340) of the geometric m", "value_then": "6.67430e-11 m^3 kg^-1 s^-2 (CODATA 2018, foliation.py:580)", "value_now": "6.67430(15)e-11, u_r 2.2e-5 (CODATA 2022, arXiv 2409.03787 Table XXXII; Sec.XIV: 'the 2022 and 2018 recommended values of G are therefore identical')", "source_now": "Mohr et al. arXiv:2409.03787, READ", "moves_conclusion": "no; value identical, exchange rate recomputed 1.348948e26 kg/m under both (C10), and no sign statement depends on G"},
  {"quantity": "c", "value_then": "299792458 m/s exact", "value_now": "299792458 m/s exact (SI definition)", "source_now": "arXiv:2409.03787 Table XXXII", "moves_conclusion": "no"}
 ],
 "rederivation": {
  "method": "sympy",
  "script_path": D + "/rederive/misner-sharp-1964.py",
  "outcome": "ALL PASS, 24 checks (output in rederive/misner-sharp-1964.out). C1 g^ab dR dR = Gamma^2 - U^2 in the general diagonal metric, residual 0; C1b with a shift, = (n.dR)^2 - (u.dR)^2, residual 0; C2 Hayward (26)->(27) from definition (4), residual 0; C2b tree form at Phi = 0, lambda = 2 Lambda equals Hayward's, residual 0; C3a,b Hayward eq.(4) double-null forms, residual 0; C4 boost invariance, residual 0; C5a-c Schwarzschild E = M in Schwarzschild, Lemaitre and Painleve-Gullstrand charts; C5d PG frame Gamma = 1; C6 Minkowski hyperboloidal slicing m = 0 with Gamma = cosh(chi) > 1 (staticity load-bearing for the sign criterion); C7a,b Hayward (28a),(28b) re-derived from G_ab = 8 pi T_ab in his gauge, residual 0; C8 z3: identity + R > 0 + Gamma > 0 => (Gamma > 1 <=> U^2 R > 2m) unsat-proved, at U = 0 (Gamma > 1 <=> m < 0) unsat-proved, and Gamma > 1 with m > 0 SAT (witness) when U != 0; C9 Escriva (2.24) = tree V2; C11a-c vacuity guards (sign-flipped invariant, driven.py:58's e^{-chi} read as the coordinate, E = 2M) all give NONZERO residuals, so the checks are not vacuous; C10 exchange rate 1.348948e26 under CODATA 2018 and 2022 G.",
  "agrees_with_source": "yes"
 },
 "later_literature": [
  {"ref": "Hayward, gr-qc/9408002 (PRD 53, 1938, 1996)", "effect": "confirms", "what": "restates MS 1964 exactly as eq.(27) 'with different notation'; proves E invariant, trapping iff E > r/2 (Prop.1), E = Kodama charge (App.B), variation formulas (28) for general matter -- (27), (4) and (28) machine-checked here", "read_status": "READ (pp.1-7,11-13,15-17,19,21-22)"},
  {"ref": "Escriva, arXiv:2504.05813v3 (2025)", "effect": "confirms", "what": "independent second restatement attributing U = D_t R, Gamma = D_r R, Gamma = sqrt(1 + U^2 - 2M/R) to MS 1964 in the general-lapse comoving gauge; notes Gamma < 0 at type-II necks (R' < 0) makes the Misner-Sharp integrand locally negative -- consistent with the tree, which uses Gamma > 0 untrapped orientation", "read_status": "READ (pp.4-13,22-24,27,30)"},
  {"ref": "Maeda & Nozawa, arXiv:0709.1199v4 (PRD 77, 064031, 2008)", "effect": "extends", "what": "generalised MS mass for Einstein-Gauss-Bonnet with Lambda, eq.(2.7), reducing to MS in 4-D with Lambda = 0; same variation formulas; notes a gap in Hayward's POSITIVITY proof needing an extra lemma (p.9) -- positivity is not used by the tree; notes MS is not the only quasi-local mass (Brown-York differs; uniqueness open, p.1 fn.1)", "read_status": "READ (pp.1-5,9-10,12)"},
  {"ref": "Zhang et al. arXiv:1406.0577; Hu et al. arXiv:1502.00069; Faraoni arXiv:1610.02951", "effect": "extends", "what": "MS mass in f(R), massive gravity, and under conformal maps: the MS-type mass is theory-dependent once tied to matter via field equations; the tree works in GR (H_EFE), so no narrowing of its uses", "read_status": "discover_papers abstracts only, NOT READ in full"}
 ],
 "lacked_data": "M's hypothesis tested for this result. The identity has no empirical input: it is the definition 1 - 2m/R = g^ab d_aR d_bR (a contraction of the areal-radius gradient) plus the algebra of a diagonal 2-metric, so there is no datum Misner & Sharp could have lacked that bears on its truth. Re-derived here from scratch (sympy, residual 0 in 10 independent forms, three Schwarzschild charts) with vacuity guards. What 1964 lacked was CONCEPTUAL, not data: the Kodama vector (1980), Hayward's invariant/trapping formulation and the identification E = Kodama charge (1994-96), the unified first law (1998), Lambda and higher-curvature generalisations (Maeda-Nozawa 2008), and the exotic-matter geometries (Morris-Thorne wormholes, 1988) where m < 0 or no regular centre occurs. Every one of these later results reproduces the identity unchanged and adds interpretation; none moves it. The only moved-datum candidate anywhere in the tree's use is G in the SI exchange rate, and CODATA 2022 left G identical to 2018 (arXiv 2409.03787 Sec.XIV). Evidence against M's hypothesis for THIS result: complete. The later literature does sharpen one tree gloss -- 'enclosed' needs a regular centre, the Einstein equations and Lambda = 0 -- which is recorded as a drift, not as an error of the 1964 result.",
 "grade": "STANDS",
 "grade_evidence": "Statement: Hayward eq.(4) and eq.(27) (READ, gr-qc/9408002 pp.4, 12) and Escriva eq.(2.5) (READ) give exactly the tree's Gamma^2 - U^2 = g^ab d_aR d_bR = 1 - 2m/R, attributed to MS 1964 by two independent restatements. Hypotheses: the tree uses spherical symmetry + areal radius (+ untrapped, U = 0, or H_EFE where it needs them, each named at the use site) -- the source's own class; the tree's general-lapse and general-matter use is a broadening the source supports and that was machine-checked (C1, C1b, C5, C7). Re-derivation agrees, 24/24 checks, vacuity-guarded. No datum: none enters; G unchanged in CODATA 2022. Recorded, not repaired, and none moves a verdict: (i) driven.py:58 misprints Hayward's e^{-lambda} as e^{-chi} (a discrepancy in the quotation; the working equations use the correct exponent); (ii) 'enclosed' (ledger.py:337, 367) is an added gloss needing regular centre + EFE + Lambda = 0, not needed by the sign theorems; (iii) Lambda = 0 unstated at throatmass.py:235 / tolman.py:705 when m is tied to matter; (iv) foliation.py:857 ONLY_INVARIANT omits Hayward's discrete sign invariants, which the range theorem already respects. Misner & Sharp 1964 itself remains NAMED-NOT-READ; the grade rests on the restatements plus an independent derivation, which for a definition is sufficient to stand.",
 "what_would_change_the_grade": "To NARROWED: a tree verdict shown to use the 'enclosed' reading (m as a volume integral of matter) on a slice with no regular centre, or with Lambda != 0 and vacuum energy excluded from rho -- none found at the owner sites read. To a recorded DISCREPANCY against the attribution (not WRONG): reading MS 1964 at source and finding its Gamma/U relation differs from Hayward's eq.(27) and Escriva's eq.(2.5) beyond notation. Nothing can make the identity WRONG short of a residual != 0 in rederive C1/C2, which is a closed-form computation.",
 "reverify_command": "python3 " + D + "/rederive/misner-sharp-1964.py   # expects 'ALL PASS', exit 0 (needs sympy; z3-solver for C8: pip install z3-solver)",
 "report_path": D + "/audits/misner-sharp-1964.json"
}
rep["published_hypotheses"] = rep["published_hypotheses"]
json.dump(rep, open(rep["report_path"], "w"), indent=1)
print("written", rep["report_path"])
