import json
D="/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
KEY="qnec-bousso-fisher-leichenauer-wall-balakrishnan-faulkner-khandker-wang-ceyhan-faulkner"
R={
"key":KEY,
"name":"Quantum null energy condition (QNEC) as a proved QFT theorem, and its integration to ANEC, as used by anec.py / bounds.py",
"source":{
 "located":"(1) Bousso, Fisher, Koeller, Leichenauer, Wall, 'Proof of the Quantum Null Energy Condition', arXiv:1509.02542 (2015; PRD 93 024017) pp.1-7, 24-26; (2) Balakrishnan, Faulkner, Khandker, Wang, 'A General Proof of the QNEC', arXiv:1706.09432v2 (2017/2019) pp.1-10, 59-66; (3) Ceyhan & Faulkner, 'Recovering the QNEC from the ANEC', arXiv:1812.04683v2 (2018; CMP 377) pp.1-4, 15-16. Also read for the attribution and the conjecture: Bousso, Fisher, Leichenauer, Wall, 'A Quantum Focussing Conjecture', arXiv:1506.02669 pp.1-6, 12, 18-24.",
 "read_status":"READ",
 "via":"alphaXiv answer_pdf_queries on 1509.02542, 1706.09432, 1812.04683, 1506.02669 (page text quoted); later: 2503.04651 and 0910.5751 read the same way"},
"published_statement":"BFKLW 1509.02542 abstract: 'Our proof applies to free and superrenormalizable bosonic field theories, and to any points that lie on stationary null surfaces. An example is Minkowski space, where any point p and null vector k^a define a null plane N (a Rindler horizon) ... The QNEC states that <T_kk(p)> >= (hbar/2pi) lim_{A->0} S''_out/A.' Formal version eq (2.2): <T_kk(p)> >= hbar/(2pi sqrt(h(p))) delta^2 S_out/delta lambda(p)^2, the diagonal coefficient after factoring the delta-function (eq 2.1), 'if the expansion and the shear of k^a(y) vanish at p'. p.2: 'the right hand side can have any sign ... By integrating the QNEC along a null generator, we can obtain the ANEC, in situations where the boundary term S'_out vanishes at early and late times.' p.4: 'These should all be viewed as fixed background spacetimes with no dynamical gravity'; on Schwarzschild/Kerr 'our proof applies only to points on the horizon'. BFKW 1706.09432: proves Q_-(A,B;y) = INT_{dA}^{dB} dx^- <T_--> - (1/2pi) dS(B)/dx^-(y) + (1/2pi) dS(A)/dx^-(y) >= 0 (eq 1.3), flat metric (2.1), locally stationary cuts (K^+_ij = 0 and enough y-derivatives), 'we worked exclusively in flat space' (p.65); K^+ != 0 'render[s] the QNEC inapplicable' (p.59). Ceyhan-Faulkner 1812.04683: 'relativistic QFT in d-dimensional Minkowski space with d >= 2 and with cuts along a Rindler horizon' (p.1); theorem for operator algebras forming a half-sided modular inclusion, 'with the additional assumption that the input state has finite averaged null energy' (abstract); QNEC as convexity of relative entropy in the cut position (eq 3.19); 'The QNEC reduces to the ANEC in a new state' (p.2).",
"published_hypotheses":[
 "BFKLW: free or superrenormalizable, massive or massless BOSONIC fields (fermions 'expected', not proved); D > 2 directly, D = 2 by dimensional reduction (Sec 5); interacting marginal/nonrenormalizable theories open (p.26)",
 "BFKLW: the point p lies on a STATIONARY null hypersurface (everywhere vanishing expansion) -- Minkowski Rindler horizons, de Sitter/Poincare horizons, or the horizon of an eternal Schwarzschild/Kerr black hole only; FIXED background, no dynamical gravity",
 "all three: the entangling surface Sigma is deformed along the null generators by AFFINE parameter; expansion and shear vanish at p (BFKLW eq 2.2); BFKW: extrinsic curvature K^+ and enough y-derivatives vanish at the point",
 "S''_out is the diagonal (delta-function) coefficient of the second functional derivative per unit transverse area, not the second derivative under a uniform deformation (the off-diagonal part is <= 0 by strong subadditivity, BFKLW eq 5.3)",
 "<T_kk> is a quantum expectation value in a state of the QFT; the inequality holds for every such state in the stated class (BFKLW Sec 4.5 'the QNEC holds for all states'; Hollands-Longo 2503.04651 p.4: proved on a dense set, 'Proving the QNEC for all vector states remains an open problem')",
 "BFKW: flat space, QFT with interacting UV fixed point, lightcone-limit / defect-OPE / modular-flow analyticity arguments (their own word 'proof strategy', p.65); CF: half-sided modular inclusion of von Neumann algebras for null cuts of a Minkowski Rindler horizon, input state with finite averaged null energy",
 "QNEC => ANEC only when the boundary term [S'_out] vanishes at early and late times (BFKLW p.2), along a complete generator of the stationary null surface"],
"hypothesis_drift":[
 "DROPPED -- background: anec.py:52-54 'QNEC is a THEOREM in quantum field theory' is applied (anec.py:40-49) to the warp spacetime, a curved, non-stationary geometry with O(1) curvature. Every proof read is on a fixed background with a stationary null surface (BFKLW p.4), 'exclusively in flat space' (BFKW p.65), or Minkowski Rindler cuts (CF p.1). No proof read covers null surfaces in the warp metric. Hollands-Longo 2503.04651 fn 2: in curved spacetime T_ab 'has well-known ambiguities' that are absent from T_kk only on a bifurcate Killing horizon.",
 "DROPPED -- quantum state: anec.py:40-47 contracts a CLASSICAL T_mu_nu = G_mu_nu (typefour.py) and no state or S_out is specified. The QNEC's RHS carries hbar; at hbar -> 0 it is the NEC (BFLW 1506.02669 fn 8; rederive Q3). So on the tree's input the QNEC says what the NEC says, and the NEC violation is already pointwise (min T_kk = -0.160 on the y = 0 ray, rederive Q4). Nothing beyond the NEC is obtained.",
 "ASSERTED, NOT COMPUTED -- boundary term: anec.py:37-38 and 155-159 say [S'] 'vanishes' 'for a localised bubble that is asymptotically vacuum'. BFKLW give this as a condition ('in situations where'). It is load-bearing: rederive Q1 (sympy) gives a profile that saturates QNEC pointwise with [S'] = -2a and INT T_kk = -a hbar/pi < 0; Q2 (z3, 10-cell box) gives UNSAT with S'(ends) = 0 and SAT without it. qnec_implies_anec() returns True unconditionally (anec.py:159), so the selftest check at anec.py:182 and shape.py:272 pass whatever the hypotheses.",
 "DROPPED -- the ANEC that the QNEC integrates to is the flat-space / stationary-horizon ANEC. anec.py:49 'ANEC IS VIOLATED, SO QNEC FORBIDS THE CONFIGURATION' uses it on a curved background. Wall 0910.5751 pp.2-3: 'exceptions to the ANEC do occur on curved spacetime backgrounds' on chronal geodesics. The curved-space version that survives is the ACHRONAL ANEC on null lines. Graham-Olum 0705.3193 conjecture it (named in Wall; not read here). Wall proves it from the GSL, under these assumptions: a background satisfying Einstein's equation and the classical NEC, a small O(hbar) perturbation, minimal coupling, and a suitable entropy renormalisation. The warp bubble is an O(1) classical NEC violation, not a small perturbation of an NEC background, so it lies outside Wall's hypotheses too. Nobody has shown that the tree's rays are achronal.",
 "WEAKENED -- affine null generator: anec.py:101-128 integrates INT T_kk dx with k = (1, F+1, 0, 0), which is not affinely normalised, over coordinate lines at fixed y. The affine tangent on the axis is K = k/(1+F), with dlambda = dx (rederive Q4, sympy), so the ANEC integral is INT T_kk/(1+F)^2 dx. On-axis: tree -0.0807, affine -0.0524. The sign survives, and the value agrees with the sibling alcubierre-1994-metric audit E8. Off-axis the 'rays' (y = 0.2 ... 0.8, anec.py:91) are not geodesics: Gamma^y_kk = F_y = -0.537 at (0.9, 0.3). They are not generators of anything the QNEC or ANEC theorems refer to.",
 "DROPPED -- normalisation and stationarity in the statement: anec.py:35 and shape.py:134 write '<T_kk> >= (hbar/2pi) S''_out' without the per-area / diagonal-functional-derivative definition (BFKLW eqs 2.1-2.3) and without the vanishing expansion and shear at p. This is notational in flat space. It matters for the stationarity requirement, which the warp null congruences are not shown to meet.",
 "DROPPED -- field class: the owner does not say which QFT (the canonical entry itself flags this). The proofs are for free/superrenormalizable bosons (BFKLW), for flat-space QFTs with an interacting UV fixed point by a lightcone/modular 'proof strategy' (BFKW), and for AQFT half-sided modular inclusions with finite ANE (CF). None is 'every QFT' on every background.",
 "CITATION DISCREPANCY (not a refutation): anec.py:53 credits the theorem to 'Bousso, Fisher, Leichenauer & Wall'. That author list is the Quantum Focussing Conjecture paper, 1506.02669, which DERIVES the QNEC from a conjecture and sketches a proof ('A proof ... will be presented in forthcoming work', p.20). The proof paper is Bousso-Fisher-KOELLER-Leichenauer-Wall, 1509.02542.",
 "AGREES: anec.py:77-78 'QNEC is locally looser (it permits <T_kk> < 0 where S'' < 0)' matches BFKLW p.2, 'the right hand side can have any sign'. bounds.py:48/305 code a state-dependent RHS, which matches the source (S_out is the state's entropy). 'globally NO LOOSER AT ALL, because it integrates to ANEC' (anec.py:78) holds only under the [S'] = 0 hypothesis above.",
 "WORDING DISCREPANCY (outside the canonical owners, found while checking): index3.py:591 (owner entangle.py) says 'QNEC is STATE-INDEPENDENT -- it holds for every state'. The intended meaning (valid in every state) agrees with BFKLW. The label clashes with bounds.py:472-474, which pins QNEC as having a state-dependent RHS. Hollands-Longo prove it only on a dense set of vector states; all vector states remain open."],
"data_at_publication":[
 {"quantity":"coefficient hbar/(2 pi) in QNEC","value_then":"hbar/2pi (exact; BFKLW eq 1.1, BFKW eq 1.3 as 1/2pi with hbar = 1)","value_now":"hbar/2pi (exact; Hollands-Longo 2503.04651 eq 1: (1/2pi)<T_kk> >= S''_EE)","source_now":"arXiv:2503.04651 p.1","moves_conclusion":"no -- an exact constant fixed by the Bisognano-Wichmann modular temperature, not a measurement"},
 {"quantity":"empirical input of any kind","value_then":"none -- the QNEC is a mathematical theorem about QFT states; no measured datum enters any of the three proofs","value_now":"none","source_now":"1509.02542, 1706.09432, 1812.04683 (read)","moves_conclusion":"no datum exists to move"},
 {"quantity":"S''_out for the tree's configuration","value_then":"n/a (not in the source)","value_now":"never computed by the tree (canonical data_used: 'the S''_out term is never computed'); no quantum state specified","source_now":"anec.py:155-159","moves_conclusion":"the tree's QNEC step carries no number; its only computed input is the classical INT T_kk (tree -0.0807, affine -0.0524 on axis)"}],
"rederivation":{
 "method":"z3",
 "script_path":D+"/rederive/"+KEY+".py",
 "outcome":"PASS (exit 0), 18 checks. Q1 sympy: INT S'' = [S']. A QNEC-saturating profile S' = -a tanh(lambda/w) has INT T_kk = -a hbar/pi < 0, so ANEC fails when [S'] != 0; with S' -> 0 at both ends the integral is 0. Q2 z3 on a 10-cell discretised generator: pointwise QNEC + zero end-differences + sum T < 0 is UNSAT, so QNEC => ANEC on the box. The same without the end condition is SAT (witness: sum T = -1, S'(end) = -1). [S'] >= 0 already suffices (UNSAT). Q3: hbar -> 0 gives the NEC. Q4 sympy + the tree's own functions (imported read-only): k = (1, F+1, 0, 0) is null with k_t = -(1+F), and the affine tangent is k/(1+F) with dlambda = dx. On-axis tree INT T_kk dx = -0.08066 against affine -0.05241, the same sign; the affine value agrees with the sibling alcubierre audit E8. Gamma^y_kk = F_y = -0.537 at (0.9, 0.3), so the off-axis 'rays' are not geodesics. The theorems themselves (replica / modular-inclusion proofs) are not finite and are not re-proved here. What is checked is the logical step the tree takes from them, plus the tree's integral.",
 "agrees_with_source":"yes"},
"later_literature":[
 {"ref":"Hollands & Longo, 'A New Proof of the QNEC', arXiv:2503.04651 (2025)","effect":"confirms","what":"Simplified rigorous proof of CF's ant formula and QNEC (convexity of relative entropy in the cut) for half-sided modular inclusions, on a natural dense set of vector states. 'Proving the QNEC for all vector states remains an open problem.' fn 2: T_ab ambiguities in curved space are absent from T_kk only on bifurcate Killing horizons. This confirms the theorem and narrows how it may be read: it is not proved for every state, nor off Killing horizons.","read_status":"READ (answer_pdf_queries pp.1-4, 7, 11-18)"},
 {"ref":"Wall, 'Proving the Achronal ANEC from the GSL', arXiv:0910.5751 (2009/2010)","effect":"narrows","what":"ANEC is violated on chronal geodesics in curved backgrounds (compactified Casimir; Schwarzschild states, pp.2-3). The achronal ANEC on null lines follows from the GSL for minimally coupled fields, but only perturbatively in hbar about a background obeying Einstein + classical NEC. This is the curved-space statement the tree's argument actually needs, and its hypotheses exclude an O(1) NEC-violating warp background.","read_status":"READ (answer_pdf_queries pp.1-7, 10, 12-17)"},
 {"ref":"Balakrishnan, Faulkner, Khandker, Wang 1706.09432 fn 23","effect":"narrows","what":"'There is now evidence that the higher spin QNEC is violated in free theories.' This affects only the higher-spin generalisation, not the stress-tensor QNEC the tree uses.","read_status":"READ (p.65)"},
 {"ref":"Moosa, Rath, Su, 'A Renyi QNEC: Proof for Free Field Theories', arXiv:2007.15025; 'A general proof of integer Renyi QNEC' arXiv:2605.15272; 'Towards a Proof of the Improved QNEC' arXiv:2601.18860; 'QNEC in quenched 2d CFTs' arXiv:2503.17448","effect":"extends","what":"Generalisations (Renyi, improved/INEC, 2d quench tests), all in flat-space QFT settings, per their abstracts.","read_status":"NAMED-NOT-READ (discover_papers abstracts only)"},
 {"ref":"Graham & Olum, 'Achronal averaged null energy condition', arXiv:0705.3193 (2007)","effect":"contested","what":"The self-consistent achronal ANEC conjecture, the natural curved-space replacement. Per Wall 0910.5751 p.3-4, Graham-Olum show generic spacetimes satisfy it only trivially (no null lines). It is a conjecture, not a theorem.","read_status":"NAMED-NOT-READ (restated in 0910.5751 pp.3-4)"}],
"lacked_data":"M's hypothesis tested for the QNEC. No empirical datum enters the result. It is a theorem of QFT whose only constant, hbar/2pi, is exact and fixed by Bisognano-Wichmann modular structure, so no later measurement can move it, and none has. What the 2015-2019 authors lacked was not data. It was proof coverage. BFKLW proved free/superrenormalizable bosons on stationary null surfaces. BFKW gave a flat-space strategy for interacting QFTs with a UV fixed point. CF made it rigorous for Minkowski Rindler cuts, given finite ANE. Hollands-Longo (2025) simplified that proof and still record 'all vector states' as open. Curved, non-stationary null surfaces are not covered by any proof read. That gap is a limit on the THEOREM's scope, not an error in it: the evidence (four independent proofs, holographic support, no counterexample for the stress-tensor QNEC in its stated class) supports the result where it is stated. Having more 'data' would not change it. What does change is the tree's use. The QNEC is invoked outside that scope, on a curved warp background with a classical T and an asserted boundary term. There it reduces to the NEC, which already fails pointwise. The step 'QNEC integrates to ANEC, ANEC fails, so the configuration is forbidden' relies on hypotheses the source states as conditions, not on the theorem. Evidence the other way: the tree's conclusion is not shown false either. Its on-axis affine ANEC is negative (-0.0524), and the achronal-ANEC route, if its hypotheses were met, would forbid the configuration. That route is conjectural (Graham-Olum) or conditional (Wall: GSL plus NEC background), and the tree has not checked achronality.",
"grade":"NARROWED",
"grade_evidence":"The published QNEC stands as stated. Four proofs were read (BFKLW 1509.02542, BFKW 1706.09432, CF 1812.04683, and Hollands-Longo 2503.04651, which confirms it), with no counterexample to the stress-tensor QNEC in its class, and the exact coefficient hbar/2pi matches. The tree uses it on a strictly larger class than any proof covers, and drops hypotheses the sources state: (i) a fixed background with a stationary null surface or flat space, where the tree applies it to the curved warp metric; (ii) a quantum state with a specified S_out, where the tree supplies a classical T with no state, and the QNEC's hbar -> 0 limit is the NEC (Q3); (iii) [S'] = 0 at both ends, which the source gives as a condition, the tree asserts without computing, and z3 shows is load-bearing (UNSAT with it, SAT without; sympy counterexample profile with INT T_kk = -a hbar/pi); (iv) affinely parametrised generators, where the tree integrates a non-affine k and uses non-geodesic off-axis curves (Gamma^y_kk = F_y != 0; the on-axis sign survives, affine -0.0524). The ANEC the QNEC integrates to is the flat-space one; in curved space ANEC fails on chronal geodesics (Wall 0910.5751). No computed contradiction refutes the tree's conclusion, so the grade is not WRONG. No datum moved, so it is not DATA-DEPENDENT. The theorem holds only on a smaller class than the tree uses: NARROWED. Also recorded, as a discrepancy and not a refutation: anec.py:53 credits 'Bousso, Fisher, Leichenauer & Wall', the conjecture paper; the proof adds Koeller.",
"what_would_change_the_grade":"Toward STANDS for the tree's use, any of these: (a) a proof of the QNEC (or of the achronal ANEC) on null surfaces of a curved, non-stationary background of the warp type, for semiclassically self-consistent states; (b) a demonstration that the tree's on-axis ray is a null line (complete achronal geodesic) of the moving-bubble spacetime, together with a curved-space ANEC theorem whose hypotheses that spacetime meets; (c) an explicit quantum state with S_out computed and [S'] shown to vanish. Toward WRONG for the tree's conclusion (not for the QFT theorem): an explicit semiclassical state on a warp background with negative achronal ANEC. For the theorem itself: a counterexample to the stress-tensor QNEC within the stated class (none known; BFKW fn 23 concerns only the higher-spin version).",
"reverify_command":"python3 "+D+"/rederive/"+KEY+".py   # expect OVERALL: PASS, exit 0; sources: alphaXiv answer_pdf_queries on 1509.02542 (abstract, pp.2,4,6-7), 1706.09432 (pp.2,8,59,62,65), 1812.04683 (pp.1-3,15), 2503.04651 (p.1 fn 2, p.4), 0910.5751 (pp.2-3,6)",
"report_path":D+"/audits/"+KEY+".json"}
json.dump(R,open(R["report_path"],"w"),indent=1)
print("written",R["report_path"])
