import json
D = "/tmp/claude-0/-home-user-Claude-Method-Works/6d820e7d-6d3c-5ac7-8067-527dc14c2847/scratchpad/d67"
S = D + "/rederive/snec-freivogel-krommydas.py"
r = {
"key": "snec-freivogel-krommydas",
"name": "Smeared Null Energy Condition (Freivogel & Krommydas 2018), with 1/G_N and B = 1/(32 pi)",
"source": {
 "located": "B. Freivogel & D. Krommydas, 'The Smeared Null Energy Condition', arXiv:1807.03808 (v1 10 Jul 2018, titled 'Wormhole Wars IV: A New Bound' per LL ref.[8]; v4 19 Apr 2021 read), JHEP 12 (2018) 067. The value B = 1/(32 pi) is NOT in this paper: it is S. Leichenauer & A. Levine, arXiv:1808.09970 eq.(1) (JHEP 01 (2019) 133).",
 "read_status": "READ",
 "via": "alphaXiv answer_pdf_queries + get_paper_content fullText (v4, 68,992 chars saved at d67/src/1807.03808.txt; grep finds no '32 pi' and no holographic argument for B); 1808.09970 v1, 2012.11569 v2, 2108.06068 v1, 2111.05772 v1 read at source for B, status and domain. v1 (2018) text itself not read -- differences between v1 and v4 are not audited."
},
"published_statement": "FK 1807.03808 v4 p.15, 'Proposed Bound. For all states within the regime of Perturbative Quantum Gravity (PQG), in any dimension d and for locally flat regions, the expectation value of the null-null contracted Stress-Energy tensor, smeared over any achronal null geodesic is bounded by <T^s_kk> >= -B/(G_N tau^2) (36). In (36) B is a constant we have yet to determine and tau is the affine distance over which we are smearing ... The smallest distance we allow ourselves to smear is l_uv, and the largest is such that we remain in a locally flat region.' Precise form eq.(37): INT dlambda f(lambda)<T_kk>(lambda) >= -(B/G_N) INT dlambda (f')^2/f, 'for arbitrary smearing functions f which are smooth and non-negative', with 1/tau^2 = INT (f')^2/f (38), f normalised. p.4: 'We have not determined the constant B'; eq.(6): R^s_kk >= -#/tau^2 'does not have any factors of hbar, so it makes sense purely classically'. p.15: 'To our knowledge, there are no counter examples to this bound, but whether or not a rigorous proof exists is left for future research.' LL 1808.09970 eq.(1) fixes the coefficient: INT du rho <T_uu> >= -(1/(32 pi G_N)) INT du rho'^2/rho, proved for holographic theories coupled to gravity by induced gravity on a brane, from the Brane Causality Condition, on a null geodesic achronal on the support of rho.",
"published_hypotheses": [
 "H1 (FK p.4, p.15): states in the regime of perturbative quantum gravity (classical background + perturbative metric fluctuations); vacuum-subtracted <T> (eq.15)",
 "H2 (FK abstract p.1, p.4, p.15-16): smearing length tau small compared to the radius of curvature / 'locally flat regions'; motivated by the evaporating-black-hole counterexample at long affine distance (p.16)",
 "H3 (FK eq.36; LL eq.1): the smearing is along an ACHRONAL null geodesic (achronal on the support of the smearing function)",
 "H4 (FK eq.17, 36, 38, 44): null GEODESIC, affine parameter lambda, contraction with the tangent dx/dlambda; bound invariant under constant affine rescaling",
 "H5 (FK p.15-16): f smooth and non-negative, normalised; 'The bound probably does not hold for discontinuous functions f'",
 "H6 (FK p.15): tau >= l_uv; G_N ~ l_UV^2/N (1-loop, 'lore' [8]) supplies the species scaling",
 "H7 (FK p.19-20): evasion of the Fewster-Roman null no-go requires 'an additional rule that the momenta involved in making the state must lie below the UV cutoff of the theory'",
 "H8 (FK p.4, p.15): B undetermined, 'a single, order one number'; status a PROPOSAL/'best guess', unproven",
 "H9 (LL, for the B = 1/(32 pi) value): holographic CFT, induced gravity on a brane, Brane Causality Condition, semiclassical z0 << eps << l (cutoff << curvature scale), Einstein equation leading"
],
"hypothesis_drift": [
 "ATTRIBUTION DISCREPANCY (not a refutation) -- nullbound.py:67 'at Freivogel-Krommydas's holographic B = 1/(32 pi)', nullbound.py:90 'Freivogel & Krommydas argue B <= 1/(32 pi) holographically', nullbound.py:126 and anec.py:92 (constant named B_FK): FK v4 p.4 'We have not determined the constant B', p.15 'a constant we have yet to determine'; no 32 pi and no holographic argument occur in the v4 full text. The holographic value is Leichenauer-Levine 1808.09970 eq.(1) ('Freivogel & Krommydas were not able to fix the numerical factor ... in this note we determine it'); FKK 2012.11569 p.3 'SNEC was proven, and the coefficient B fixed, by Leichenauer and Levine within the framework of induced gravity on a brane'. The value itself is correctly the holographic one, and Freivogel's own later papers write the 1/(32 pi G_N) form under the SNEC name (FF 2108.06068 eq.1.2), so the NUMBER is not in question -- only whose argument it is.",
 "DROPPED H2 (domain: tau small against the curvature radius) -- anec.py:9-11 'SNEC ... IS VIOLATED TOO, AT EVERY SAMPLING WIDTH OF ORDER THE BUBBLE RADIUS OR MORE', anec.py:15 'it must hold for EVERY sampling function g', index3.py:383-384 SNEC-RETRACTED 'fails above w ~ 0.93 bubble radii'. Computed here (E8): the Einstein-curvature scale along the y = 0.3 ray is L = (max|G_ab|)^-1/2 = 0.4695 (0.4504 on the axis); the crossover w_c = 0.9274 is FK smearing length tau_c = w_c/sqrt2 = 0.656 = 1.40 L. At every width inside FK 2018's stated domain (w <= 0.5, tau <= 0.35 < L) the configuration SATISFIES SNEC. The tree's violation lives in the regime FK 2018 excluded, which FKK 2012.11569 (p.3, sec.3.2, 'Argue, by examining examples, that this bound may remain valid when smearing over distances of order the radius of curvature or larger') later argued -- from two examples, not proved -- the bound extends into. The use therefore rests on the authors' own later EXTENSION, not on the 2018 statement.",
 "DROPPED H3 (achronality on the support of g) -- nowhere in anec.py:94-152 or bounds.py is achronality of the sampled ray asked or checked; FK eq.(36) and LL eq.(1) both require it. Not checkable in this audit (OPEN).",
 "DROPPED H4 (geodesic, affine) -- anec.py:113-117 samples fixed-y coordinate lines with k = (1, v+1, 0, 0) and measure dx. The sibling Alcubierre audit (E7) shows the four off-axis lines are not geodesics; only y = 0 is. Computed here (E7): on the axis geodesic with the affine tangent K = k/(1+v) (K_t = -1, dlambda = dx in the frozen metric) INT T_KK dlambda = -0.05241 (tree-style -0.08066; agrees with the sibling audit's frozen affine -0.0524) and the affine SNEC crossover is w_c = 1.2689 (tree-style 1.0492). So a violation on a genuine affine geodesic exists at B = 1/(32 pi), at a larger width (tau = 0.897 = 2.0 L on the axis).",
 "WEAKENED H5 (smooth f) in the numerics, not in the verdict -- anec.py:119 samples x in [-6, 6], n = 240, anec.py:130-135 renormalise the truncated Gaussian and set g' = 0 at the endpoints. At w = 5 and 20 the sampled g is a window-truncated function whose edge jump is dropped (FK p.16: bound 'probably does not hold for discontinuous functions'); the printed bounds (anec.py:24-29) differ from the closed form -2B/w^2 by -36.1% (w = 5) and -94.3% (w = 20), and by -11.5% at w = 0.1 (grid h = 0.05 against w = 0.1). With untruncated Gaussians on [-8, 8], n = 1600 (E5) every printed verdict is reproduced (w = 5: LHS -1.034e-2 vs RHS -7.96e-4; w = 20: -2.66e-3 vs -4.97e-5) and w_c = 0.9274 against the tree's 0.9270. Recorded as discrepancies in printed numbers, not errors of verdict.",
 "OVER-STATEMENT in a dependent row (not an owner) -- index3.py:750 'QEIs and SNEC are STATE-INDEPENDENT theorems over all Hadamard states'. SNEC is not a theorem in general (FK p.15; FKK p.24 'SNEC remains unproven in the case of general curved spacetimes and interacting fields'); it is proved only (i) in holographic induced gravity (LL) and (ii) as a field-theory bound for free and super-renormalizable QFT in Minkowski with a UV cutoff (FF 2108.06068 eq.2.11). Over all Hadamard states WITHOUT a cutoff the finite-segment null average is unbounded below (Fewster-Roman, restated FK p.19, FFK 2111.05772 p.5). This over-representation runs in the refusal's favour. The owners' own wording -- anec.py:52 and nullbound.py:91 'a conjecture with holographic support' -- is accurate.",
 "INDEX-CODING, corroborated both ways -- bounds.py:45 and :297 code SNEC with G = 0 and bounds.py:153-155 flag it ('finite null smearing exists only because Freivogel & Krommydas insert a 1/G_N. CANDIDATE INDEX FAULT'). Source: the T-form carries 1/G_N (FK eq.4, 36, 37); the geometric form R^s_kk >= -#/tau^2 (FK eq.6) carries neither G nor hbar. The tree's 'exists only because of 1/G_N' is supported (FK p.3 'There are no existing bounds on the average of the stress tensor along a finite portion of a null geodesic above 1+1 dimensions'; LL p.1 'the G_N -> 0 limit leaves the resulting field theory energy density unconstrained'), with one hypothesis the tree does not name: H7, the UV cutoff on the momenta of the states, without which the Fewster-Roman states still break it (FK p.19; FKK sec.2.3 imposes it on transverse momenta).",
 "NO DRIFT -- anec.py:14 writes -(4B/G), anec.py:136 codes -4B with no G. E3: with typefour's T = G_munu/(8 pi) (typefour.py:163,179) SNEC is INT g^2 G_kk >= -32 pi B INT g'^2 and 32 pi B = 1 at B = 1/(32 pi), exactly LL eq.(3)'s lower bound -1/4 INT rho'^2/rho with rho = g^2. The G = 1 coding is consistent. E1: FK (f')^2/f with f = g^2 is exactly 4 (g')^2, so anec.py:14 is FK eq.(37).",
 "NO DRIFT -- applying the bound to a classical Alcubierre T_kk: FK eq.(6) reads it as a purely geometric, hbar-free constraint 'that makes sense purely classically', so testing a metric against it asks whether PQG states could source it. The frozen-bubble metric caveat (sibling audit alcubierre-1994-metric) is immaterial for G_kk along the motion."
],
"data_at_publication": [
 {"quantity": "B (dimensionless SNEC coefficient)",
  "value_then": "undetermined (FK 2018 p.4, p.15: 'a single, order one number')",
  "value_now": "1/(32 pi) derived in holographic induced gravity (LL 1808.09970 eq.1); FKK 2012.11569 sec.2.2: 'when semi-classical gravity is well under control, B << 1'; FF 2108.06068 eq.(2.11) field-theory coefficient 1/(12 pi a^(d-2)) per degree of freedom, scheme-dependent",
  "source_now": "arXiv:1808.09970 p.1; arXiv:2012.11569 pp.7-8; arXiv:2108.06068 p.8",
  "moves_conclusion": "No, toward permission. E6: w_c = 0.3747 / 0.5257 / 0.9274 / 1.5558 / 3.9265 at B = 0.01 / 0.1 / 1 / 3 / 10 x 1/(32 pi). Smaller B (the direction FKK argue for) widens the violation; only B several times larger than 1/(32 pi), which no source proposes, pushes w_c past the bubble radius."},
 {"quantity": "G_N vs l_UV and N (G_N <~ l_UV^(d-2)/N)",
  "value_then": "1-loop 'lore' [8] (FK p.5, p.16)",
  "value_now": "unchanged lore; FKK sec.2.2 notes it is typically NOT saturated in controlled constructions (hence B << 1)",
  "source_now": "arXiv:2012.11569 p.8",
  "moves_conclusion": "No: E3 shows G_N and hbar cancel from the geometric form the tree evaluates."},
 {"quantity": "curvature scale of the tested configuration (domain check for H2; not an author datum)",
  "value_then": "not computed in the tree",
  "value_now": "L = 0.4695 (y = 0.3), 0.4504 (axis), from max |G_ab| in the Eulerian frame, v_s = 0.5, sigma = 8, R = 1",
  "source_now": "computed here, E8",
  "moves_conclusion": "Yes for the scope of the use: the violation appears only at tau >= 1.40 L (axis affine: 2.0 L), outside FK 2018's tau << L. The conclusion then rests on FKK 2020's argued, unproven extension."}
],
"rederivation": {
 "method": "sympy",
 "script_path": S,
 "outcome": "SELFTEST OK (sympy E1-E3, numeric E4-E8; output at d67/rederive/snec-freivogel-krommydas.out). E1 FK eq.37 with f = g^2 is the tree's form exactly. E2 Gaussian INT g'^2 = 1/(2w^2), FK tau = w/sqrt2, RHS = -2B/w^2 = -1/(16 pi w^2). E3 G_N and hbar cancel; 32 pi B = 1 reproduces LL eq.3. E4 tree's printed bounds agree with the closed form at w = 0.5, 1 (<0.6%), disagree at w = 0.1 (-11.5%), 5 (-36.1%), 20 (-94.3%). E5 crossover w_c = 0.9274 (tree 0.9270) with analytic g on [-8, 8]; all verdicts reproduced. E6 B scan: smaller B shrinks w_c. E7 axis affine geodesic: violation persists, w_c = 1.2689. E8 curvature scale L ~ 0.47: violation at tau_c = 1.40 L.",
 "agrees_with_source": "yes"
},
"later_literature": [
 {"ref": "Leichenauer & Levine, arXiv:1808.09970 (JHEP 01 (2019) 133)", "effect": "extends", "what": "Proves the FK lower bound with B = 1/(32 pi) for holographic theories coupled to gravity by induced gravity on a brane, from the Brane Causality Condition, on geodesics achronal on the support of rho; also proves the upper bound (d-2)/(32 pi G_N). Semiclassical cutoff << curvature scale assumed.", "read_status": "READ (pp.1-8)"},
 {"ref": "Freivogel, Kontou & Krommydas, arXiv:2012.11569 (SciPost)", "effect": "extends", "what": "Attributes B = 1/(32 pi) to LL; argues B << 1 when semiclassical gravity is controlled; argues from the evaporating black hole and MMP wormhole that SNEC may hold for smearing of order the curvature radius or larger; shows SNEC -> ANEC at large support; proves a Penrose-type singularity theorem assuming SNEC; 'SNEC remains unproven in the case of general curved spacetimes and interacting fields'.", "read_status": "READ (pp.1-17, 20, 24, 26)"},
 {"ref": "Fliss & Freivogel, arXiv:2108.06068", "effect": "confirms", "what": "Proves the field-theory SNEC, <T_++[f]> >= -(1/(12 pi a^(d-2) delta^2)) INT f'^2, for free and super-renormalizable QFT in Minkowski with transverse cutoff a (light-sheet pencils); shows squeezed states make it unimprovable by light-sheet smearing alone. Narrower than the gravitational claim (no G_N, no curvature).", "read_status": "READ (pp.1-24)"},
 {"ref": "Fliss, Freivogel & Kontou, arXiv:2111.05772", "effect": "extends", "what": "Proves DSNEC (null energy smeared over two null directions) for free fields in Minkowski, cutoff-independent; recovers ANEC and (with a cutoff) SNEC as limits (App.B); states single-null smearing is unbounded in QFT without a cutoff.", "read_status": "READ (pp.1-6, 11, 13, 20, 26-32)"},
 {"ref": "arXiv:2606.08003 'Does Eternal Inflation Violate the Smeared Null Energy Condition?'; arXiv:2512.04934 'Constraints on Genesis Cosmology from the SNEC'; arXiv:2405.10228 fermionic DSNEC", "effect": "extends", "what": "Applications/extensions found by discover_papers; abstracts only.", "read_status": "NAMED-NOT-READ (discover_papers abstract only)"},
 {"ref": "Fliss, Freivogel, Kontou & Pardo Santos, arXiv:2309.10848 (cited by the tree at index3.py:1183)", "effect": "extends", "what": "SNEC-type bound for non-minimal coupling as an EFT with field-value cutoff.", "read_status": "NAMED-NOT-READ in this audit"}
],
"lacked_data": "What FK 2018 lacked: (a) the value of B -- supplied by LL 2018 (1/(32 pi)) in one holographic framework, with FKK 2020 then arguing B << 1 whenever semiclassical gravity is controlled; (b) a proof -- supplied only in two restricted frameworks (LL induced gravity; FF 2021 free/super-renormalizable Minkowski QFT with cutoff); (c) evidence about smearing beyond the curvature radius -- FKK 2020 supply two examples in which it holds. Does having it change the conclusion? For the published statement, no datum has moved against it: no counterexample is known (FKK p.24 'We do not have an example where SNEC is saturated'). For the tree's use, the later data cut both ways and are recorded both ways: the B that arrived is the LOOSEST natural value, and every smaller B strengthens the tree's violation (E6), so nothing the authors lacked would open a door; but the tree's violation sits at tau = 1.4-2.0 curvature radii, in exactly the regime FK 2018 excluded for lack of data and that later work extends into only by argument. M's hypothesis is therefore partly borne out for this result -- the 2018 statement was incomplete (no B, no proof, a domain caveat) and was completed later -- but the completion did not overturn it, and the one open part (validity at tau >~ L in curved spacetime) is OPEN, not WRONG.",
"grade": "NARROWED",
"grade_evidence": "Statement and algebra STAND as used: FK eq.37 with f = g^2 is the tree's form (E1), the G = 1 coding and B = 1/(32 pi) reproduce LL's geometric bound exactly (E3), and the tree's crossover reproduces to 4e-4 (E5). But the tree applies it on a larger class than published: (i) at smearing lengths tau_c = 1.40 L_curv (off-axis) and 2.0 L_curv (axis, affine), where FK 2018 restrict to tau << curvature radius and only FKK 2020's argued extension reaches (E8); inside FK's stated domain the configuration satisfies SNEC; (ii) on non-geodesic, non-affine coordinate lines (the axis geodesic, affine, still violates: E7); (iii) without checking achronality (OPEN); (iv) with truncated Gaussians whose printed bounds are off by up to -94% (verdicts unchanged, E4-E5). Attribution of B to FK is a discrepancy, not a refutation. index3.py:750 calls SNEC a theorem over all Hadamard states, which the source does not support. No moved datum reverses the verdict (E6). Underlying truth of SNEC in curved spacetime remains unproven (OPEN), which the owners correctly say ('a conjecture with holographic support').",
"what_would_change_the_grade": "To STANDS for the tree's use: a proof (or the tree's own re-measurement) that SNEC holds for tau >~ curvature radius in curved spacetime, plus an achronality check of the sampled ray, plus rows re-expressed on the affine geodesic. To WRONG (for the extension the use needs): an explicit PQG state violating SNEC at tau ~ L. To DATA-DEPENDENT: a derivation giving B >~ 3/(32 pi) in a controlled framework (E6 threshold for w_c > 1.5). A Weyl-inclusive curvature scale can only shorten L and so cannot bring tau_c inside tau << L.",
"reverify_command": "cd /tmp && PYTHONDONTWRITEBYTECODE=1 python3 " + S + "   # expect SELFTEST OK; w_c = 0.9274, affine axis w_c = 1.2689, L_curv(y=0.3) = 0.4695.  Source checks: grep -nE '32 ?π' " + D + "/src/1807.03808.txt (expect no hit: FK never fix B); alphaXiv answer_pdf_queries(1807.03808, ['value of B']) and (1808.09970, ['1/(32 pi)'])",
"report_path": D + "/audits/snec-freivogel-krommydas.json"
}
json.dump(r, open(r["report_path"], "w"), indent=1)
print("written", r["report_path"])
